
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<META HTTP-EQUIV="Refresh" CONTENT="13; URL=ad.asp">
<HTML>
<HEAD>
	<TITLE>news</TITLE>
</HEAD>

<BODY BGCOLOR="#1C0058"   TEXT="White" VLINK="#D2D2D2" LINK="#FFD711">
<table width="100%" align="LEFT" valign="MIDDLE"><tr><td height="100%" align="CENTER" valign="MIDDLE">
<!--#include file="nav_adbanner_beta.asp"--></td></tr>
</table>


</BODY>
</HTML>
