
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KCBA</TITLE>
<!--#include file="style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<br><br><br><br>
<p><strong>To bookmark a page, hit CTRL+D (Command+D on a Mac) on your keyboard.  If you're using an older version of AOL or Internet Explorer, select the Favorites menu and click on Add to Favorites.</strong>
<br><br>
<a href="main.asp">KCBA Home.</a><br><br><br><br><br><br><br><br><br><br><br><br><br></p>
<!--#include file="footer.inc" -->


</BODY>
</HTML>
