
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KCBA</TITLE>
<!--#include file="../style.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">

<img src="../images/theconnection.gif" width=284 height=32 alt="The Connection" border="0">
<br><br><img src="../images/classifiedslogo.gif" width=199 height=85 alt="" border=0 align="left">
<h3>Looking to buy or sell something? Try the KCBA Classifieds.</h3>
<p>You can either <A HREF="http://207.66.185.129/kcba/FMPro?-DB=kcbaclassifieds.fp3&-Format=classified.html&hidden=hidden&-Max=50&-Find" target="main">search the current listings</a>, or <a href="http://207.66.185.129/kcba/addclassified.htm">post your own ad</a>.</p><br><br>



<h3>Ready for a good book?</h3>
<p>Find one  in the <a href="bookstore.asp">KCBA Bookstore.</a></p>

<br><br><br><br><br>
<!--#include file="../footer.inc" -->

</BODY>
</HTML>
