<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Thursday, 3/5/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 3/5/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Cold Open(dead girl)>Cold Open(dead girl)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(Sheppard DNA)>(Sheppard DNA)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(hepatitis strain)>(hepatitis strain)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Dead Girl folo-INT>Dead Girl folo-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(army sex trial)>(army sex trial)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Dead Girl folo-GUT>Dead Girl folo-GUT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Moon/Ice>Moon/Ice</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Dead Girl folo-TAG>Dead Girl folo-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139CSUMB grant>CSUMB grant</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Daisy Mascada>Daisy Mascada</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Space exhibit>Space exhibit</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#133sexual predator>sexual predator</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/car seat recall>Fox Biz/car seat recall</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Teacher sick-out>Teacher sick-out</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121Bump #3a (Alan)>Bump #3a (Alan)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125bike chop shop>bike chop shop</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Sprewell>Sprewell</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131LAFCO news conf.>LAFCO news conf.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Casey Martin>Casey Martin</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Hwy 68 closed>Hwy 68 closed</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4549ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(Clinton) >Bump 1(Clinton) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(Moon Ice) >bump 2(Moon Ice) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Bump #5a (jump rop)>Bump #5a (jump rop)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Clinton Leak-INT>Clinton Leak-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50jumprope for heart>jumprope for heart</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#136Johnny Chung>Johnny Chung</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141dr. seuss reads>dr. seuss reads</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=114Cold Open(dead girl)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cold Open(dead girl)</H3><BR>
"OH, SWEET, SWEET GIRL.  GOT ALONG WITH EVERYONE.  A FRIEND TO EVERYONE."
<P>
HOW COULD SOMEONE DO SUCH A THING?
<P>
THAT'S WHAT NEIGHBORS IN ONE LOCAL COMMUNITY ARE ASKING TONIGHT, AFTER THE BRUTAL KILLING OF AN 11-YEAR OLD GIRL.
<P>
DETAILS NEXT, ON KCBA FOX NEWS, FIRST AT TEN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
IT'S A CRIME THAT HAS AN ENTIRE COMMUNITY IN SHOCK TONIGHT.
<P>
AN 11-YEAR OLD SALINAS GIRL BRUTALLY MURDERED IN HER OWN HOME. DURING WHAT INVESTIGATORS SAY WAS A BURGLARY ATTEMPT.
<P>
JINAH KIM JOINS US NOW LIVE FROM THE CRIME SCENE IN NORTH SALINAS.
<P>
JINAH. IT'S A DISTURBING STORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Dead Girl folo-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dead Girl folo-INT</H3><BR>
IT'S SUCH A HORRIFIC CRIME THAT THE ENTIRE INVESTIGATIONS STAFF AT THE MONTEREY COUNTY SHERIFF'S DEPARTMENT IS INVOLVED IN SOLVING IT.
<P>
NICOLE CARNAHAN WAS FOUND MURDERED IN HER BEDROOM LATE YESTERDAY AFTERNOON, HERE, IN THE NORTH SALINAS HOME SHE SHARES WITH HER MOM.
<P>
A FEW HOURS LATER. SHERIFF'S OFFICIALS CHARGED HER *NEXT DOOR NEIGHBOR* WITH THE CRIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Dead Girl folo-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dead Girl folo-GUT</H3><BR>
LIKE SHE DOES EVERY DAY. SALINAS SINGLE MOM BECKY CARNAHAN CAME HOME AROUND FIVE YESTERDAY EVENING, EXPECTING TO SEE HER 11-YEAR OLD DAUGHTER DOING HER HOMEWORK.
<P>
INSTEAD, SHE FOUND A HOUSE TURNED UPSIDE DOWN, APPARENTLY BURGLARIZED. WITH NO SIGN OF HER DAUGHTER.
<P>
SHE IMMEDIATELY CALLED THE SHERIFF'S DEPARTMENT. WHO INITIALLY THOUGHT THE CHILD HAD BEEN KIDNAPPED.
<P>
BUT A MORE THOROUGH SEARCH OF NICOLE CARNAHAN'S ROOM TURNED UP THE UNTHINKABLE.
<P>
SHERIFF'S OFFICIALS BELIEVE, AT SOME POINT BETWEEN THE TIME NICOLE CAME HOME AT THREE, AND HER MOTHER CAME HOME AT FIVE. A BURGLAR FORCED HIS WAY INTO THE HOUSE, AND WAS IN THE PROCESS OF STEALING SOME GOODS, WHEN THE 11-YEAR OLD WALKED IN ON HIM.
<P>
INVESTIGATORS BELIEVE THAT'S WHEN THE BURGLAR KILLED THE GIRL, AND TRIED TO HIDE HER BODY BEHIND HER OWN BED.
<P>
DEPUTIES INTERVIEWED DOZENS OF NEIGHBORS AND FRIENDS. BUT FINALLY ARRESTED THE VICTIM'S NEXT DOOR NEIGHBOR. AFTER FINDING SOME OF THE STOLEN GOODS IN HIS BACK YARD.
<P>
CHARGED WITH MURDER *AND* BURGLARY IS 47-YEAR OLD RON MOORE. A MAN WHO'S NO STRANGER TO CRIME.
<P>
MEANWHILE. THE NEWS HAS NEIGHBORS, TEACHERS AND SCHOOLMATES IN DISBELIEF.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Dead Girl folo-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dead Girl folo-TAG</H3><BR>
AN AUTOPSY ON HER BODY WILL BE COMPLETED TOMORROW. AND THAT'S WHEN OFFICIALS HOPE TO KNOW MORE ABOUT THE CIRCUMSTANCES SURROUNDING HER DEATH.
<P>
ALAN, BACK TO YOU.
<P>
JINAH. DID THE SUSPECT LIVE ALONE IN THAT HOUSE?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Daisy Mascada>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Daisy Mascada</H3><BR>
A WOMAN WHO ADMITS TO CUTTING OFF HER BOYFRIEND'S PENIS GIVES EMOTIONAL TESTIMONY BEFORE A JUDGE TODAY.
<P>
THE SENTENCING HEARING OF 18-YEAR OLD DAISY MASCADA GOT UNDERWAY TODAY.
<P>
MASCADA PLEADED NO CONTEST TO CHARGES SHE SEVERED HER BOYFRIEND'S PENIS LAST JULY, AFTER HE ALLEGEDLY BEAT HER IN A DRUNKEN RAGE.
<P>
MASCADA'S ATTORNIES HAVE REPEATEDLY ARGUED THAT SHE SUFFERED FROM BATTERED WOMEN'S SYNDROME.
<P>
TODAY, A DEFENSE PSYCHOLOGIST TOOK THE STAND TO CONFIRM THAT.
<P>
THE JUDGE ALSO HEARD FROM MASCADA HERSELF.
<P>
"HOW DO YOU FEEL ABOUT WHAT YOU DID? I FEEL VERY BAD I FEEL SORRY.  I THINK WE BOTH DESERVE PUSNICHMENT WE BOTH GUILTY.BECAUSE HE DID NOT TREAT ME GREAT SEXUALLY HE MISTREATED ME HUMILIATE ME HE HAD DONE WHATEVER HE HAD WANTED TO DO WITH ME I NEVER IMAGINE REACT LIKE THAT I NEVER THOUGHT TO HARM HIM."
<P>
IT WAS ALSO ALLEGED TODAY THAT MASCADA WAS KIDNAPPED FROM MEXICO BY THE VICTIM. JULIO LUNA.
<P>
THE HEARING CONTINUES TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=133sexual predator>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>sexual predator</H3><BR>
MEANWHILE, IN SANTA CRUZ. LAW ENFORCEMENT OFFICIALS ARE MOUNTING A CAMPAIGN TO KEEP A CONVICTED SEX OFFENDER OFF THE STREETS.
<P>
GREGORY GRANT HAS SERVED HALF OF HIS 29-YEAR PRISON SENTENCE. MAKING HIM ELIGIBLE FOR RELEASE MONDAY.
<P>
BUT THE DISTRICT ATTORNEY'S OFFICE SAYS GRANT IS STILL A THREAT TO SOCIETY. AND THAT HE IS A DIAGNOSED PEDOPHILE WHO'S USED HIS HANDICAPPED CONDITION TO LURE INNOCENT VICTIMS.
<P>
IN ONE CASE, GRANT PAID A CHILD A DOLLAR TO PUSH HIS CHAIR. THEN KIDNAPPED AND SODOMIZED HIM.
<P>
A HEARING WILL BE HELD NEXT WEEK, WHEN PROSECUTORS WILL BRING IN A TEAM OF PSYCHIATRISTS TO TESTIFY IN FAVOR OF KEEPING GRANT LOCKED UP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Teacher sick-out>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teacher sick-out</H3><BR>
EVEN  TEACHERS CALL IN SICK. BUT TODAY IN THE SALINAS UNIFIED SCHOOL DISTRICT. MORE THAN 170 DIDN'T SHOW UP FOR WORK.
<P>
IT WAS PART OF AN ORGANIZED SICK-OUT. BY TEACHERS WHO ARE TIRED OF WAITING FOR A NEW CONTRACT.
<P>
IT'S THE SECOND TIME THIS SCHOOL YEAR IT'S HAPPENED.
<P>
SOME 11-THOUSAND STUDENTS WERE AFFECTED TODAY.
<P>
TEACHERS AND THE DISTRICT HAVE BEEN IN NEGOTIATIONS FOR ABOUT A YEAR.
<P>
THE NEXT MEDIATION SESSION IS SCHEDULED FOR NEXT WEEK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125bike chop shop>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bike chop shop</H3><BR>
IF YOU'VE HAD A BICYCLE STOLEN RECENTLY. MONTEREY POLICE SAY YOU MIGHT BE IN LUCK. IN FACT YOUR BIKE MAY BE AT POLICE HEADQUARTERS.
<P>
        OFFICERS RESPONDING TO A REPORT OF A BATTERY LAST NIGHT DISCOVERED DOZENS OF BIKES AND BIKE PARTS AT A HOME ON DELA VINA AVENUE.
<P>
        IT TURNS OUT. THE BICYCLES THEY FOUND HAD ALL BEEN REPORTED STOLEN.
<P>
        AUTHORITIES ARRESTED 29 YEAR OLD DIMITRI ANDRETZ, AND CHARGED HIM WITH POSSESSION OF STOLEN PROPERTY. 
<P>
DETECTIVES SAY HE PROABABLY PLANNED TO SELL THE BIKES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131LAFCO news conf.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>LAFCO news conf.</H3><BR>
A FIGHT IS BREWING IN SANTA CRUZ COUNTY OVER AN ANNEXATION REQUEST BY THE CITY OF WATSONVILLE.
<P>
THE LOCAL AGENCY FORMATION COMMISSION. KNOWN AS LAFCO. MUST APPROVE THE PROPOSAL.
<P>
BUT WATSONVILLE LEADERS SAY THAT AGENCY IS MAKING UNREASONABLE DEMANDS.
<P>
WATSONVILLE MAYOR DENNIS OSMER HELD A NEWS CONFERENCE TODAY IN APTOS. SYMBOLICALLY SHOWING HIS CITY IS WILLING TO MEET LAFCO HALFWAY.
<P>
        WATSONVILLE WANTS TO ANNEX LAND WEST OF RIVERSIDE DRIVE FOR INDUSTRIAL USE.
<P>
        LAFCO HAS APPROVED THE 94-ACRE ADDITION. BUT ONLY IF THE CITY AGREES TO GIVE UP SOME ZONING DECISIONS TO THE COUNTY AND THE COASTAL COMMISSION.
<P>
NOW WATSONVILLE IS SUEING LAFCO.
<P>
"NO CITY IN THE STATE OF CALIFORNIA COULD OR WOULD ACQUIESCE TO THESE
<P>
CONDITIONS.  THEY CAN'T, BECAUSE IT WOULD SECEDE RESPONSIBILITY FOR
<P>
GOVERNING WATSONVILLE TO PEOPLE WHO ARE NOT RESPONSIBLE FOR 
<P>
WATSONVILLE VOTERS."
<P>
LAFCO REPRESENTATIVE PATRICK MCCORMICK SAYS HE DOESN'T THING THE COMMISSION HAS ANY ROOM FOR COMPROMISE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Hwy 68 closed>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hwy 68 closed</H3><BR>
IF YOU'RE HEADING FOR PACIFIC GROVE OR PEBBLE BEACH THIS WEEKEND. START PLANNING AN ALTERNATE ROUTE.
<P>
A SECTION OF HIGHWAY 68 WILL BE CLOSED OFF NEAR PEBBLE BEACH. TO REPLACE A CULVERT DAMAGED IN RECENT STORMS.
<P>
THE ROAD WILL BE CLOSED BETWEEN SKYLINE DRIVE AND MORSE ROAD FROM SEVEN TOMORROW NIGHT. UNTIL SEVEN SATURDAY NIGHT.
<P>
A DETOUR WILL BE AVAILABLE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(Clinton) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(Clinton) </H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
THE WHITE HOUSE COMES OUT SWINGING AFTER A WASHINGTON POST ARTICLE. THAT QUOTES PRESIDENT CLINTON'S DEPOSITION IN THE PAULA JONES CASE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(Moon Ice) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(Moon Ice) </H3><BR>
AND. COULD PEOPLE ONE DAY LIVE ON THE MOON?  AFTER A DISCOVERY BY THE LUNAR PROSPECTOR. NASA SCIENTISTS SAY WE'RE ONE STEP CLOSER TO THE ANSWER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Clinton Leak-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton Leak-INT</H3><BR>
PRESIDENT CLINTON'S PAL. VERNON JORDAN. IS DONE WITH HIS SECOND DAY OF TESTIMONY BEFORE KENNETH STARR'S GRAND JURY. 
<P>
HE SAID HIS EFFORTS TO GET MONICA LEWINSKY A JOB HAD NOTHING TO DO WITH THE AFFIDAVIT SHE GAVE IN THE PAULA JONES CASE. 
<P>
MEANWHILE. ONE OF THE PRESIDENT'S LAWYERS.BOB BENNETT. BLAMES THE PRESIDENT'S ENEMIES FOR LEAKING CLINTON'S DEPOSITION IN THE PAULA JONES CASE. TO THE MEDIA. 
<P>
FOX'S JIM ANGLE HAS THE DETAILS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=136Johnny Chung>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Johnny Chung</H3><BR>
FORMER DEMOCRATIC FUND-RAISER JOHNNY CHUNG HAS BEEN CHARGED WITH A STRING OF CAMPAIGN FINANCE VIOLATIONS.
<P>
THE CHARGES AGAINST THE CALIFORNIA BUSINESSMAN INCLUDE.. TAX EVASION, BANK FRAUD, AND CONSPIRACY TO VIOLATE FEDERAL ELECTION LAWS.
<P>
CHUNG ALLEGEDLY FUNNELED ILLEGAL DONATIONS TO THE CLINTON/GORE RE-ELECTION FUND.  THROUGH PHONY DONORS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
THE CASE INSPIRED THE T-V SHOW "THE FUGITIVE". AND NOW NEW TESTS MAY PROVE SAM SHEPPARD'S INNOCENCE.
<P>
THAT STORY FROM CLEVELAND, OHIO. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(Sheppard DNA)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Sheppard DNA)</H3><BR>
NEW D-N-A TESTS BOLSTER THE THEORY THAT DOCTOR SAM SHEPPARD DID NOT KILL HIS WIFE.IN 19-54.
<P>
SHEPPARD WAS CONVICTED OF THE CRIME AND SPENT TEN YEARS IN JAIL BEFORE BEING ACQUITTED. IN A RETRIAL.
<P>
SHEPPARD DIED MORE THAN 25 YEARS AGO, BUT HIS SON, SAM REESE SHEPPARD. IS STILL TRYING TO CLEAR HIS FATHER'S NAME. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(hepatitis strain)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(hepatitis strain)</H3><BR>
ON CAPITOL HILL TODAY.
<P>
A CONGRESSIONAL PANEL WANTS TO KNOW WHY 300-THOUSAND AMERICANS CONTRACTED 
<P>
HEPATITIS-C THROUGH TAINTED BLOOD. AND WHY THEY WEREN'T NOTIFIED ABOUT IT. 
<P>
ABOUT ONE MILLION AMERICANS RECEIVED BLOOD PRODUCTS TAINTED WITH HEPATITIS-C BEFORE 19-90.  
<P>
THAT'S WHEN A TEST WAS DEVELOPED TO SCREEN FOR THE DISEASE. 
<P>
HEPATITIS-C IS USUALLY SPREAD THROUGH CONTAMINATED BLOOD. AND BY INTRAVENOUS DRUG ABUSERS WHO SHARE DIRTY NEEDLES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(army sex trial)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(army sex trial)</H3><BR>
THE DEFENSE FOR THE ARMY'S FORMER TOP ENLISTED MAN HAS RESTED. IN HIS SEXUAL-MISCONDUCT COURT MARTIAL. 
<P>
FORMER SARGENT MAJOR GENE MCKINNEY. FINISHED 
<P>
TESTIFYING YESTERDAY. 
<P>
SIX WOMEN ACCUSE HIM OF PRESSURING THEM FOR SEX. 
<P>
MCKINNEY TESTIFIED THAT HE WENT TO ONE OF HIS ACCUSER'S HOTEL ROOMS AFTER MIDNIGHT NOT FOR SEX. BUT TO FIRE HER. 
<P>
MCKINNEY COULD GET 55 YEARS IN PRISON IF CONVICTED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Moon/Ice>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Moon/Ice</H3><BR>
THEY WERE HOPING TO FIND IT. AND THEY DID. NASA SCIENTISTS SAY THE LUNAR PROSPECTOR HAS FOUND EVIDENCE OF ICE ON THE MOON. 
<P>
THE PROSPECTOR. SENT INTO LUNAR ORBIT IN JANUARY. WAS DESIGNED TO SCAN THE MOON'S SURFACE.      AND GATHER INFORMATION THAT COULD LEAD TO FUTURE HUMAN EXPLORATION.  AND COLONIZATION.   
<P>
SCIENTISTS SAY THE EXISTENCE OF ICE AND WATER WOULD ALLOW HUMANS TO LIVE ON THE MOON. FOR ANY LENGTH OF TIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139CSUMB grant>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>CSUMB grant</H3><BR>
SPEAKING OF NASA.
<P>
THE SPACE ADMINISTRATION IS HELPING FUND A RESEARCH PROJECT HERE ON THE CENTRAL COAST.
<P>
NASA AND THE ENVIRONMENTAL PROTECTION AGENCY HAVE AGREED TO FUND A 700-THOUSAND DOLLAR STUDY.
<P>
THE RESEARCH WILL BE USED TO CREATE A COMPUTER-BASED TOOL THAT WILL HELP LOCAL COMMUNITIES BETTER UNDERSTAND WATER ISSUES.
<P>
THE STUDY'S BEING LED BY A FACULTY MEMBER AT CAL STATE MONTEREY BAY.
<P>
THE GRANT IS ONE OF THE LARGEST IN THE SCHOOL'S BRIEF HISTORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Space exhibit>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Space exhibit</H3><BR>
AND.
<P>
A  NASA EXHIBIT SHOWING THINGS LIKE THIS HYDROPONICS EQUIPMENT USED TO GROW FOOD IN SPACE. IS NOW ON DISPLAY AT SALINAS VALLEY MEMORIAL HOSPITAL. 
<P>
THE YDROPHONICS WILL LATER BE USED TO GROW FOOD FOR PATIENTS. 
<P>
IN FACT MANY OF THE HI-TECH THINGS AT THE HOSPITAL HAVE BEEN TESTED IN SPACE FIRST TO SEE THE EFFECTS ON THE HUMAN BODY.
<P>
A RIBBON CUTTING CEREMONY FOR THE NEW HEART CENTER AT S-V-M-H WILL TAKE PLACE TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/car seat recall>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/car seat recall</H3><BR>
A DANGEROUS BABY SEAT IS BEING RECALLED FOR REPAIR. 
<P>
DETAILS IN TONIGHT'S FOX NEWS REPORT.
<P>
THE CONSUMER PRODUCT SAFETY COMMISSION HAS ANNOUNCED A MAJOR RECALL. INVOLVING 800-THOUSAND INFANT CAR SEATS THAT DOUBLE AS BABY CARRIERS. 
<P>
THE "ON MY WAY" BABY CARRIERS, MANUFACTURED BY "EVENFLO". APPARENTLY HAVE HANDLES THAT CAN UNEXPECTEDLY UNLOCK. FLIPPING THE CHILD FORWARD. 
<P>
THE C-P-S-C SAYS ALREADY THERE HAVE BEEN DOZENS OF 
<P>
INJURIES BECAUSE OF THE DEFECTIVE HANDLES: 
<P>
TO PREVENT SUCH INJURIES. THE COMPANY IS OFFERING A FREE REPAIR KIT THAT WILL LOCK THE HANDLE IN POSITION. 
<P>
THE MODELS BEING RECALLED ARE 207  AND 492 AND MADE BETWEEN DECEMBER 19-95 AND JULY 19-97.
<P>
CONSUMERS WHO PURCHASED A SAFETY SEAT DURING THAT 
<P>
PERIOD SHOULD CHECK THE MODEL NUMBERS AND CALL THE COMPANY AT 1-800-424-9393. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121Bump #3a (Alan)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump #3a (Alan)</H3><BR>
COMING UP A LITTLE LATER ON FOX NEWS FIRST AT TEN.
<P>
JUMPING ROPE IS NOT JUST FOR EXERCISE ANYMORE. SOME LOCAL SCHOOL KIDS ARE DOING IT SIMPLY BECAUSE THEY HAVE A LOT OF HEART.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Sprewell>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sprewell</H3><BR>
WE'LL CALL THIS A SHOT-GUN RECONCILIATION. THANKS TO YESTERDAY'S RULING BY ARBITRATOR JOHN FEERICK, THERE IS A CHANCE THAT LATRELL SPREWELL COULD PLAY FOR THE WARRIORS AGAIN.
<P>
TODAY GOLDEN STATE HAD TO START DEALING WITH THAT REALITY.
<P>
SPREWELL HAD HIS CONTRACT WITH THE WARRIORS REINSTATED AND HIS NBA SUSPENSION REDUCED BY 5-MONTHS.
<P>
HE'LL BE ELIGIBLE TO RETURN NEXT SEASON, AND HE HAS OVER 16-MILLION DOLLARS COMING TO HIM OVER THE NEXT 2-YEARS.
<P>
THE WARRIORS WILL TRY AND TRADE SPREWELL, BUT IF THEY CAN'T, HE'LL HAVE TO PLAY FOR THE COACH THAT HE PHYSICALLY ATTACKED BACK ON DECMEBER 1ST.
<P>
TODAY AT PRACTICE, P.J. CARLESIMO WAS ASKED ABOUT THAT SCENARIO.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Casey Martin>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Casey Martin</H3><BR>
LESS THAN MONTH SINCE HE WON THE RIGHT TO USE A CART AS A PROFESSIONAL GOLFER, CASEY MARTIN WAS FINALLY ABLE TO TEE IT UP AT THE NIKE TOUR EVENT IN AUSTIN, TEXAS.
<P>
MARTIN ADMITTED TO HAVING BUTTERFLIES ON THE FIRST TEE, AND THE GOLF CHANNEL FOLLOWED HIS EVERY SHOT TODAY.
<P>
AND MARTIN COMES THROUGH, FIRING A 3-UNDER PAR 69. HE'S JUST 3-SHOTS OFF THE LEAD AFTER THE FIRST ROUND.
<P>
AND FOLLOWING HIS VICTORY IN THE COURTS, MARTIN ADMITTED IT FELT GREAT TO COMPETE ON THE GOLF COURSE AGAIN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4549ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
BAD NEWS FOR THE 49ERS TODAY, AS KIRK SCRAFFORD, WHO STARTED ALL 16-GAMES AT OFFENSIVE TACKLE THIS LAST SEASON, HAS TO DECIDED TO RETIRE.
<P>
SCRAFFORD HAS A SERIOUS NECK INJURY, HE'S DECIDED RATHER THAN HAVE SURGERY, HE'D PREFER TO CALL IT QUITS.
<P>
SCRAFFORD TURNS 31 IN 10-DAYS.
<P>
ANOTHER FOOTBALL PLAYER WHO'S CONSIDERING RETIREMENT IS CORNERBACK ERIC ALLEN. ALLEN WAS JUST TRADED TO THE RAIDERS TODAY.
<P>
IN EXCHANGE, OAKLAND GIVES UP A DRAFT PICK TO THE SAINTS.
<P>
BUT ALLEN SAID HE WAS PREPARED TO RETIRE IF HE WASN'T TRADED TO, WHAT HE TERMED A "SUITABLE" CLUB.
<P>
WE'LL SEE IF THE RAIDERS FIT THE BILL, STAY TUNNED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO HOCKEY, AND THE SAN JOSE SHARKS ARE STILL PLAYING RIGHT NOW UP AT THE ARENA.
<P>
IN THE 3RD PERIOD, THE SHARKS LEAD THE  DETROIT RED WINGS BY A SCORE OF 5 TO 4.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Bump #5a (jump rop)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump #5a (jump rop)</H3><BR>
COMING UP NEXT.
<P>
WE'LL SHOW YOU SOME LOCAL SCHOOL KIDS WHO ARE HOPING TO ROPE IN THE BIG BUCKS. FOR A GOOD CAUSE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50jumprope for heart>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>jumprope for heart</H3><BR>
SOME LOCAL MIDDLE SCHOOL STUDENTS.WITH JUMP ROPE IN HAND. ARE RAISING MONEY FOR A GOOD CAUSE AND A GOOD FRIEND.
<P>
STUDENTS AT LOS ARBOLES MIDDLE SCHOOL IN MARINA HAVE TAKEN PART IN THE AMERICAN HEART ASSOCIATION'S "JUMP FOR HEART" EVENT FOR THE PAST TWO YEARS. BUT THIS YEAR IT'S TAKEN ON A WHOLE NEW MEANING.
<P>
THE STUDENTS DECIDED TO DEDICATE THIS YEAR'S JUMP TO THEIR CLASSMATE.LAURENCIA WALKER. WHO'S UNDERGOING TREATMENT FOR CANCER.
<P>
SO FAR THE STUDENTS HAVE RAISED 565 DOLLARS.
<P>
IF YOU'D LIKE TO HELP OUT.YOU CAN CALL LOS ARBOLES MIDDLE SCHOOL FOR MORE INFORMATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141dr. seuss reads>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>dr. seuss reads</H3><BR>
MANY CHILDREN KNOW HIM AS THE VOICE OF "AYEGO THE PARROT" IN THE WALT DISNEY ANIMATED FEATURE, "ALADDIN".       BUT TODAY COMEDIAN GILBERT GOTTFRIED USED HIS UNIQUE VOCAL TALENTS TO BRING TO LIFE THE DOCTOR SEUSS STORY. "CAT IN THE HAT.".  
<P>
---READING STORY---
<P>
GOTTFRIED READ THE STORY TO SCHOOL CHILDREN IN NEW YORK CITY. AS PART OF "READ ACROSS AMERICA". A NATIONAL EFFORT TO ENCOURAGE EARLY READING. 
<P>
THE EFFORT IS TAKING PLACE DURING THE WEEK OF MARCH SECOND. TO COMMEMORATE DOCTOR SEUSS. THEODORE GEISEL'S BIRTHDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
