KCBA FIRST AT TEN, Wednesday,
                                4/15/98


           TS1 (SC suspicious)
                                         Across America
           SC suspicious object
                                         (missouri pile-up)
           Casa del rey woods
                                         (torture date verdict)
           Ford Ord shoot folo
                                         (paula jones appeal)
           PG Lucky's hearing
                                         (shuttle preview)
           Water ration protest
                                         Fox Biz/amoco
           Water recycle no co
                                         Laguna Seca (bikes)
           Local tax day MOS
                                         Laguna (Tag)
           Tax Day wrap-INT
                                         Giants
           Tax shooting 
                                         NL Board
           Methyl Bromide folo
                                         A's
           Odwalla settles
                                         AL Board
           SF pot club closed
                                         Sharks
           Bump 1(missouri pile) 
                                         taxpayer back rub
           bump 2(paula jones) 
                                         taxes pie-in-face



    TS1 (SC suspicious)


COMING UP NEXT ON KCBA FOX NEWS FIRST AT TEN. 

A DANGEROUS WEAPON IS FOUND NEAR A LOCAL SCHOOL.PUTTING
SEVERAL STUDENTS AT RISK. 

ONLY TWO HOURS LEFT UNTIL THE TAX DEADLINE.WE'LL TELL YOU HOW
PROCRASTINATORS ARE DEALING WITH THE HEADACHE. 

AND SEVERAL PEOPLE ARE INJURED AFTER A MASSIVE CAR PILEUP ON
A MAJOR INTERSTATE. 

WE'LL HAVE ALL THE TOP STORIES, WEATHER AND SPORTS. 

I'M CHERI GYURO.KCBA FOX NEWS IS NEXT. 

Return to index of stories...


    SC suspicious object


GOOD EVENING. AND THANKS FOR JOINING US. I'M CHERI GYURO. ALAN
MARSDEN HAS THE NIGHT OFF. 

A DEVICE PACKED WITH GUNPOWER IS FOUND NEAR AN ELEMENTARY
SCHOOL IN SANTA CRUZ THIS MORNING. 

LOOKING TO TAKE NO CHANCES.THE ARMY BOMB SQUAD FROM
MOFFETT FIELD RESPONDED TO DETONATE THE DEVICE. 

--EXPLOSION--- 

THE OBJECT WAS JUST A LITTLE LARGER THAN A HAND GRENADE.
ABOUT TWO AND A HALF INCHES IN DIAMETER. 

IT WAS WRAPPED IN ELECTRICAL TAPE, WITH A FUSE SHOWING. 

A JOGGER SPOTTED IT AROUND 8:30 THIS MORNING. JUST DOWN THE HILL
FROM WESTLAKE ELEMENTARY SCHOOL. 

POLICE CALLED THE BOMB SQUAD BECAUSE THEY SAY THE DEVICE
WAS DANGEROUS. 

"IT HAD A DETACHED FUSE. COULD HAVE INJURED SOMEONE? MORE
THAN LIKELY, YES." 

STUDENTS AT NEARBY WESTLAKE ELEMENTARY SCHOOL WERE KEPT
INDOORS. UNTIL THE SITUATION WAS RESOLVED. 

Return to index of stories...


    Casa del rey woods


A MAN CHARGED WITH ATTEMPTING TO ABDUCT0 ^KIDS^ AT A SEASIDE
ELEMENTARY SCHOOL WON'T BE GOING TO ^TRIAL^ ANY TIME SOON
BECAUSE THE I-N-S ^DEPORTED^ HIM. 

POLICE SAY JESUS CASAS TRIED TO LURE SEVERAL KIDS FROM THE DEL
REY WOODS SCHOOL IN SEASIDE INTO HIS CAR. 

THE INCIDENT PUT TEACHERS AND PARENTS ON ALERT. 

A SKETCH LED TO HIS ARREST. 

CASAS PLEAD NOT GUILTY LAST MONTH TO THREE CHARGES OF
ATTEMPTED KIDNAPPING.AND WAS RELEASED ON HIS OWN
RECOGNIZANCE TWO WEEKS AGO. 

THE D-A'S OFFICE SAYS THEY HAD NO IDEA THE I-N-S WAS LOOKING FOR
THEIR SUSPECT. 

Return to index of stories...


    Ford Ord shoot folo


LAWYERS FOR THE MAN ACCUSED OF A DEADLY SNIPER ATTACK AT
FORT ORD. MAY BE CONSIDERING AN INSANITY DEFENSE. 

THE TRIAL IS SCHEDULED TO START LATER THIS MONTH. 

LAWYERS FOR JOHN FILLER WENT BEFORE THE JUDGE TODAY TO ASK
FOR TIME TO CONSIDER ENTERING AN "INSANITY PLEA". 

THAT REQUEST WAS REJECTED. 

JOHN FILLER IS ACCUSED OF OPENING FIRE ON CO-WORKERS OUTSIDE
THE OLD FORT ORD ARMY HOSPITAL LAST JUNE. 

49-YEAR OLD JOE LLOYD OF PRUNEDALE DIED IN THE ATTACK. AND
ANOTHER MAN WAS INURED. 

IF CONVICTED.FILLER COULD FACE LIFE IN PRISON WITHOUT PAROLE. 

Return to index of stories...


    PG Lucky's hearing


MORE HEATED DISCUSSION TONIGHT OVER THE LUCKY SUPERMARKET
EXPANSION IN PACIFIC GROVE. 

"LUCKY" OFFICIALS WANT TO ADD ON TO THEIR STORE AT COUNTRY CLUB
GATE BY 15 -THOUSAND SQUARE FEET. 

THAT WOULD MEAN CUTTING DOWN ABOUT 55 TREES. 

THE STORE SAYS THEY'LL REPLACE THE PINES AND THEN SOME. 

SOME RESIDENTS SAY THAT'S NOT GOOD ENOUGH. 

THE TWO SIDES SQUARED OFF AGAIN AT TONIGHT'S CITY COUNCIL
MEETING. 

NO DECISION IS EXPECTED TONIGHT. 

Return to index of stories...


    Water ration protest


ACROSS TOWN. FOLKS IN MONTEREY BUTTING HEADS WITH CAL-AM
OVER PHASE FOUR: THE MANDATORY WATER RATIONING PLAN. 

THE PUBLIC PROTEST HEARING IS A REQUIRED MEETING TO GET
FEEDBACK FROM THE COMMUNITY. 

THE RATIONING PLAN IS AN EXTENSION OF THE MANDATORY
CONSERVATION PROGRAM THAT WAS IMPLEMENTED LAST MONTH. 

A PLAN THEY SAY WILL ONLY BE A LAST RESORT. 

STILL.RESIDENTS SAY IT'S UNFAIR TO MAKE EVERYONE RATION THE SAME
AMOUNT. 

THE RATION PLANS ARE A DIRECT RESULT OF AN ENVIRONMENTAL
LAWSUIT RESTRICTING PUMPING FROM THE CARMEL RIVER. 

DETAILS OF THE PLAN STILL HAVE TO BE APPROVED BY THE STATE
PUBLIC UTILITIES COMMISSION. 

IF APPROVED. IT WOULD GO INTO EFFECT JULY 1ST. 

Return to index of stories...


    Water recycle no co


^FARMERS^ IN ^NORTH SALINAS^ WILL SOON BE USING ^TREATED WASTE
WATER^ TO IRRIGATE THEIR ^CROPS^.THANKS TO A NEW
75-MILLION-DOLLAR WATER TREATMENT PLANT. 

THE PLANT WAS BUILT TO COMBAT SALT-WATER INTRUSION IN NORTHERN
SALINAS VALLEY. 

THE HUGE WATER RECLAMATION PLANT JUST NORTH OF MARINA TREATS
UP TO 20 MILLION GALLONS OF WASTEWATER A DAY. 

INSTEAD OF BEING DUMPED INTO THE MONTEREY BAY, IT'S PUMPED TO
LOCAL AGRICULTURE FIELDS. 

PLANT OFFICIALS SAY THE WATER IS AS SAFE AS EVERY DAY TAP
WATER. 

Return to index of stories...


    Local tax day MOS


IF YOU HAVEN'T FILED YOUR TAXES YET. YOU HAVE LESS THAN TWO
HOURS TO MAKE THE MIDNIGHT DEADLINE. 

THE MAD DASH TO GIVE UP THE CASH BEGAN EARLIER TONIGHT AS
CROWDS MOBBED THE POST OFFICE TO GET THEIR RETURNS IN BEFORE
THE DEADLINE. 

I-R-S AUTHORITIES SAY AS OF THIS MORNING.NEARLY HALF THE PEOPLE
IN CALIFORNIA DIDN'T FILE. 

THAT DOESN'T SURPRISE MANY LOCALS. WHO FALL RIGHT INTO THAT
CATEGORY. 

"WELL IF I GOTTA PAY. MAY AS WELL WAIT UNTIL THE LAST MINUTE." 

"WE JUST GOT CAUGHT BEHIND. GIVE THEM THEIR MONYE WITH
INTEREST." 

"THIS IS MY FIRST TIME. FROM THE TAX PERSON." 

IF YOU DON'T FILE BY MIDNIGHT. DON'T STRESS. YOU CAN STILL FILE A
48-68 FORM.AN EXTENSION. 

YOU SHOULD KNOW. IF YOU DO THAT. YOU MAY FACE A PENALTY
CHARGE. 

Return to index of stories...


    Tax Day wrap-INT


THOSE FOLKS AREN'T ALONE. ALL ACROSS THE U-S. 

LAST-MINUTE ^FILERS^ ARE RUSHING TO BEAT THE DEADLINE. 

BUT SOME PEOPLE HAVE A PROBLEM WITH SENDING ^UNCLE SAM^ A
^CHECK.^ 

FOX'S CARL CAMERON TELLS US HOW SOME FOLKS SAY THE ^TAX
CODES^ NEED TO BE OVERHAULED. 

Return to index of stories...


    Tax shooting 


TAX DAY TURNED UGLY FOR AN ACCOUNTING FIRM IN MICHIGAN AS A
GUNMAN RUSHES IN AND OPENS FIRE. 

POLICE SAY THE MAN. WHO IS STILL ON LOOSE. WALKED INTO AN
ACCOUNTING OFFICE THIS MORNING AND STARTED SHOOTING WINDOWS
AND DOORS. 

DOZENS OF ROUNDS WERE FIRED. BUT MIRACULOUSLY. NO ONE WAS
HURT. 

STILL NO WORD ON WHETHER THE SUSPECT IS A CLIENT OF THE FIRM OR
A DISGRUNTLED EMPLOYEE. 

Return to index of stories...


    Methyl Bromide folo


A NEW ^BILL^ COULD CHANGE THE WAY LOCAL ^GROWERS^ USE THE
CONTROVERSIAL PESTICIDE: ^METHYL BROMIDE.^ 

THE CHEMICAL HAS BEEN UNDER FIRE FOR SOME TIME. 

LOCAL ACTIVISTS SAY IT'S MAKING PEOPLE SICK.PARTICULARLY AMONG
SCHOOL CHILDREN. 

THE BILL WOULD REQUIRE GROWERS TO GIVE SCHOOLS. AS WELL AS
HOSPITALS AND RESIDENCES.A 96 HOUR NOTICE BEFORE SPRAYING. 

THE BUFFER ZONE WOULD HAVE TO INCREASE FROM ONE HUNDRED TO
ONE THOUSAND FEET. 

UNDER CURRENT FEDERAL LAW. METHYL BROMIDE IS SCHEDULED TO
BE PHASED OUT ALL TOGETHER BY THE YEAR 2001. 

THE BILL NOW GOES TO THE ASSEMBLY RULES COMMITTEE FOR
APPROVAL. 

Return to index of stories...


    Odwalla settles


A HEFTY ^FINE^ COULD SETTLE CHARGES OF "FOOD SAFETY
VIOLATIONS" AGAINST ^ODWALLA.^ 

THE CHARGES WERE BROUGHT AFTER AN OUTBREAK OF E-COLI
POISONING IN 1996. 

THE ILLNESSES. AND ONE DEATH. WERE LINKED TO UNPASTEURIZED
APPLE JUICE. 

ACCORDING TO A SEATTLE NEWSPAPER.THE COMPANY IS NEGOTIATING
AN AGREEMENT TO PLEAD GUILTY TO MISDEMEANOR CHARGES AND PAY
A FINE OF ONE AND 

A-HALF MILLION DOLLARS. 

THE COMPANY NOW PASTEURIZES ITS APPLE JUICE. 

Return to index of stories...


    SF pot club closed


A SUPERIOR COURT JUDGE SHUTS DOWN SAN FRANCISCO'S LARGEST
POT CLINIC. 

THE JUDGE SAYS HE MADE THE DECISION BECAUSE THE FOUNDER OF
THE CLINIC. DENNIS PERON. ADMITTED SELLING MARIJUANA TO
^NON-PATIENTS.^ 

PERON WAS ONE OF THE SPONSORS OF CALIFORNIA'S
VOTER-APPROVED MEDICAL MARIJUANA INITIATIVE.ALSO KNOWN AS
PROP 215. 

THE JUDGE MADE IT CLEAR THAT HE DID NOT SHUT THE CLINIC DOWN
BECAUSE LEGITIMATE PATIENTS RECIEVED POT. 

HE SAYS HE ONLY CLOSED THE CLINIC BECAUSE PERON VIOLATED THE
LAW. 

Return to index of stories...


    Bump 1(missouri pile) 


THERE'S MUCH MORE TO COME ON KCBA FOX NEWS FIRST AT TEN. 

A HUGE PILE UP INVOLVING ABOUT A HUNDRED CARS INJURES DOZENS
OF PEOPLE ON A MAJOR HIGHWAY. 

Return to index of stories...


    bump 2(paula jones) 


AND.IT'S THE STORY THAT JUST WON'T GO AWAY.PAULA JONES HAS
PLANS FOR TOMORROW. 

WE'LL TELL YOU WHAT THEY ARE WHEN WE COME BACK. 

Return to index of stories...


    Across America


DOZENS OF PEOPLE ARE HURT AFTER A HUGE PILE-UP INVOLVING AS
MANY AS A HUNDRED CARS. 

THAT STORY FROM OUTSIDE ST. LOUIS, MISSOURI TOPS OUR LOOK AT
NEWS ACROSS AMERICA. 

Return to index of stories...


    (missouri pile-up)


EMERGENCY CREWS SAY ABOUT NINETY CARS WERE 

INVOLVED IN THE PILEUP ON INTERSTATE 70 THIS MORNING. 

ABOUT 40 PEOPLE WERE HURT. FOUR SERIOUSLY. 

THE SUBURBAN ST. LOUIS INTERSTATE WAS CLOSED FOR SEVERAL
HOURS. AS CREWS CLEANED UP THE CRUMPLED HEAPS OF VEHICLES. 

DRIVERS SAY GLARE FROM SUNSHINE ON THE RAIN-SLICKED ROAD
TEMPORARILY BLINDED THEM.CAUSING DRIVERS TO RUN INTO EACH
OTHER. 

Return to index of stories...


    (torture date verdict)


A COLUMBIA UNIVERSITY GRADUATE STUDENT IS CONVICTED OF
KIDNAPPING AND SEXUALLY ABUSING A WOMAN HE MET THROUGH THE
INTERNET. 

OLIVER YO-VANOVIC WAS ACCUSED OF TYING UP, 

BEATING, BITING AND SEXUALLY ABUSING THE WOMAN. 

THE VICTIM SAYS HE ATTACKED HER ON THEIR FIRST DATE. AFTER
INITIALLY MEETING ON THE INTERNET. 

Return to index of stories...


    (paula jones appeal)


PAULA JONES BACK IN THE NEWS AGAIN. 

A SPOKESWOMAN SAYS HER LEAGAL TEAM WILL ANNOUNCE
TOMORROW IF THEY PLAN TO APPEAL THE DISMISSAL OF HER SEXUAL
HARASSMENT SUIT AGAINST PRESIDENT CLINTON. 

INDEPENDENT COUNSEL KEN STARR SAYS THE DECISION WILL HAVE NO
EFFECT ON HIS INVESTIGATION. 

LEGAL EXPERTS SAY AN APPEAL COULD TAKE SEVERAL YEARS. 

Return to index of stories...


    (shuttle preview)


MAYBE THE SPACE SHUTTLE COLUMBIA SHOULD BE RE-NAMED "NOAH'S
ARK." 

NASA SPENT THE DAY LOADING MORE THAN 2-THOUSAND MICE, RATS,
FISH, SNAILS AND CRICKETS ON BOARD THE SHUTTLE FOR TOMORROW'S
LIFT-OFF. 

THE ANIMALS AND BUGS. ALONG WITH SEVEN HUMANS ARE PART OF A
16-TO-17 DAY MISSION THAT'LL STUDY HOW BEING IN SPACE EFFECTS
THE BRAIN AND NERVOUS SYSTEM. 

NASA SAYS THE MISSION IS INTENDED TO SHED NEW LIGHT ON AGING
AND OTHER HEALTH PROBLEMS IN ORBIT AND ON EARTH. 

THEY SAY IT'LL PERHAPS MAKE IT EASIER FOR ASTRONAUTS TO ONE DAY
CAMP ON THE MOON OR TRAVEL TO MARS. 

Return to index of stories...


    Fox Biz/amoco


AMOCO CORPORATION AGREED TO PAY 2-POINT-6 MILLION DOLLARS TO
CLEAN UP HUNDREDS OF SERVICE STATIONS. 

DETAILS IN TONIGHT'S FOX BUSINESS REPORT. 

AMOCO WAS ACCUSED OF ALLOWING OIL AND GAS TO LEAK INTO THE
SOIL AROUND CHICAGO-AREA STATIONS FROM 19-87 TO 19-93. 

THE OIL AND CHEMICAL GIANT ADMITTED NO FAULT.AND UNDER THE
SETTLEMENT MUST EITHER PROVE 40-PERCENT OF THE TANKS ARE
SAFE. OR CLEAN THEM UP. 

AMOCO ISSUED A STATEMENT SAYING THE SITES POSE NO PUBLIC RISK.
BUT IT WILL PAY TWO-MILLION IN PENALTIES OVER TEN YEARS FOR
FAILING TO PROVIDE REGULATORS WITH ADEQUATE PAPERWORK. 

Return to index of stories...


    Laguna Seca (bikes)


THE ROAR OF THE SUPERBIKES CAN BE HEARD AT THE LAGUNA SECA
RACEWAY ONCE AGAIN. 

IT'S THE HONDA CHALLANGE OF LAGUNA SECA AND IT'S THE 3RD STOP
ON THE AMA SUPERBIKE TOUR. 

Return to index of stories...


    Laguna (Tag)


WHAT AN INCREDIBLE RIDE. YOU CAN CATCH THE RACING THIS
WEEKEND. WITH QUALIFYING BEGINING ON FRIDAY. AND THE MAIN EVENT
TAKING PLACE AT 1-O'CLOCK ON SUNDAY. 

Return to index of stories...


    Giants


FROM RACING TO THE DIAMOND. WHERE THE GIANTS ARE ON A FAST
TRACK TO THE TOP OF THE N-L WEST. 

THEY'VE WON 5 OF THEIR LAST 8 GAMES AND TONIGHT THEY WRAP UP
THEIR 9-GAME HOMESTAND AGAINST THE PADRES. 

THE GIANTS FACING. THE GIANT KILLER. WHO YOU MAY REMEMBER LAST
YEAR. WHILE PITCHING FOR THE MARLINS. NO HIT THE GIANTS IN JUNE. 

------------ 

HE WAS DOING MORE OF THE SAME TONIGHT. 9-K'S FOR THE PADRES
ACE. 

------------ 

SCORELESS IN THE 4TH. PROVIDES THE POP. GOING DEEP ON HIS 3RD
HOMER IN TWO GAMES. 1-NOTHING SAN DIEGO. 

------------ 

BROWN HAD A NO-HITTER GOING UNTIL THE 4TH. WHEN BARRY BONDS
BREAKS UP THE NO-NO. BONDS WITH 2 OF THE 3 HITS OFF BROWN. 

------------ 

BUT THEY COULDN'T SCORE. BROWN THROWS A COMPLETE GAME 3-HIT
SHUT-OUT. FINAL. 1-NOTHING PADRES. 

Return to index of stories...


    NL Board


ELSEWHERE. THE DODGERS AND ROCKIES ARE RAINED OUT. 

--------- 

SAME FATE FOR ARIZONA AND ST. LOUIS. THE METS NIP THE CUBS AT
SHEA AFTER THE YANKEE GAME. 

--------- 

MONTREAL SQUEEKS PAST MILWAUKEE. ATLANTA BLANKS PITTSBURGH. 

------------- 

THE MARLINS BEAT AND THE PHILLIES. AND CINCY HANDLES HOUSTON AT
HOME. 

Return to index of stories...


    A's


THE ROAD WOES CONTINUE FOR THE A'S. ONCE AGAIN. OAKLAND JUST
UNABLE TO DIG ONE OUT AWAY FROM HOME. 

THE A'S WRAPING UP THEIR 3 GAME SERIES WITH THE RED SOX.
DOUBLING DOWN THE LINE IN THE 5TH TO BRING HOME THAT WOULD TIE
THE GAME AT 3. 

------------- 

BUT IN THE BOTTOM OF THE 9TH. THE A'S WALK TO GET TO AND O'LEARY
MAKES THEM PAY. THE SINGLE TO RIGHT WILL SCORE AND THAT'S THE
GAME WINNER. FINAL. 4-3 BOSTON. 

Return to index of stories...


    AL Board


IT'S THE A'S 6TH STRAIGHT LOSS. THEIR 2-10 RECORD IS THE WORST
START IN FRANCHISE HISTORY. ELSEWHERE. SEATTLE FINALLY BEATS
CLEVELAND. IT'S JUST THEIR 4TH WIN THIS SEASON. THE YANKEES BEAT
ANAHEIM PLAYIN IN SHEA STADIUM FOR THE 1ST TIME IN 23 YEARS WHILE
THEY FIX YANKEE STADIUM. 

----------------- 

IT'STEXAS 7-3 OVER DETROIT. THE WHITE SOX NIP THE ORIOLES. 

------------- 

AND TORONTO LOSES TO KANSAS CITY. 

Return to index of stories...


    Sharks


THE SHARKS HAVE ONLY LOST TWO OF THEIR LAST TEN GAMES AND
THEY CONTINUE THEIR PLAYOFF PUSH TONIGHT IN CALGARY. 

IT'S THE 3RD TO LAST GAME OF THE SEASON WITH THE SHARKS
CURRENTLY HOLDING DOWN THE 8TH AND FINAL PLAYOFF SPORT IN THE
WEST. SHARKS CAN CLINCH A PLAYOFF SPOT WITH A WIN OR A TIE. 

. GAME TIED AT ONE IN THE 2ND PERIOD. FOLLOWS UP HIS OWN SHOT
AND GIVES THE TEAL AND BLACK A 2-1 LEAD. IT'S THE 5TH GOAL OF THE
SEASON FOR NICHOLS. 

---------- 

SHARKS STILL LEADING IN THE 2ND. THE 2-ON-1 BREAK. AND WILL PUT
THIS ONE PAST THE 31ST GOAL OF THE SEASON FOR FRIESEN. IT'S TIES A
FRANCHISE RECORD SET LAST YEAR BY. 

------------ 

BUT IN THE 3RD. JUST GIVES ONE AWAY. POPS IT IN THE NET TO TIE THE
GAME AT THREE. 

AND WE ARE GOING TO OVERTIME. 

----------- 

BUT NOTHING CAN BE DECIDED IN THE EXTRA PERIOD. GAME ENDS IN A
3-3 TIE. AND THE SHARKS CLINCH A PLAYOFF SPOT. THEIR FIRST IN 3
YEARS. 

Return to index of stories...


    taxpayer back rub


WELL, YOU ONLY HAVE ABOUT AN HOUR AND A HALF TO FILE YOUR
TAXES IF YOU HAVEN'T DONE SO. 

IF FILLING OUT THOSE FORMS HAS STRESSED YOU OUT.HERE'S AN IDEA. 

IN PITTSBURGH, FOLKS WHO BRING IN A COPY OF THEIR COMPLETED 1040
CAN GET A FREE 10-MINUTE.40 SECOND BACK RUB. 

OVERTAXED ACCOUNTANTS. WHO CAN PROVE 

THEIR OCCUPATION WITH A BUSINESS CARD. CAN ALSO CASH IN ON THE
TAX-DAY DEAL. 

Return to index of stories...


    taxes pie-in-face


OVER IN MARYLAND.FOLKS ARE USING FOOD TO GET RID OF TAX
STRESS. 

A BALTIMORE-AREA RADIO STATION LET THEIR ANGRY FANS RELIEVE
THEIR TAX-DAY FRUSTRATIONS BY TYING UP A "TAX MAN" IN FRONT OF A
POST OFFICE.AND LETTING THEM HIT THE GUY WHIPPED CREAM PIES. 

Return to index of stories...

                               Copyright © 1998
 All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.
   Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for
 broadcast or publication or redistribution directly or indirectly in any medium. Neither these AP materials nor any portion
  thereof may be stored in a computer except for personal and non-commercial use. AP will not be held liable for any
  delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any
                        damages arising from any of the foregoing.
