
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
<TITLE>KCBA FIRST AT TEN, Monday, 10/27/97</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<TABLE WIDTH=100% BORDER=0>
<TR><TD CLASS="a"><TR><TD CLASS="a" ><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Monday, 10/27/97</H2></CENTER></TD>
</TABLE>

<TABLE WIDTH=100% BORDER=0 >
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107stock market-int>stock market-int</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(mall fire) >(mall fire) </A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#133local reax>local reax</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22(buttons suicide)>(buttons suicide)</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127SC oiled birds-I>SC oiled birds-I</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137DENVER SNOW-I>DENVER SNOW-I</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139SC oiled birds-T>SC oiled birds-T</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/junk mail>Fox Biz/junk mail</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125salinas chase folo>salinas chase folo</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132rolls royce for sale>rolls royce for sale</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110castroville att murder>castroville att murder</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40NFL>NFL</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130INS scam>INS scam</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Sharks>Sharks</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129abalone symposium>abalone symposium</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Warriors>Warriors</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134jackson march>jackson march</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Giants>Giants</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Golf: Your Turn>Golf: Your Turn</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(HIV infected kids)>(HIV infected kids)</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50salinas culinary>salinas culinary</A></TD>

</Table>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=107stock market-int>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>stock market-int</H3><BR>
.
<P>
.
<P>
.
<P>
.
<P>
.
<P>
.
<P>
.
<P>
.
<P>
.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=133local reax>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>local reax</H3><BR>
MANY LOCAL INVESTORS ARE WAITING TO SEE WHAT TOMORROW WILL BRING WHEN THE MARKETS RE-OPEN.
<P>
	ONE LOCAL FINANCIAL ANALYST SAYS EVEN THOUGH TODAY'S LOSS MANY SEEM HIGH. IT'S NOT A THREAT TO THE U-S ECONOMY.
<P>
	THOSE STOCKS THAT WERE HIT THE HARDEST INCLUDE BANKS. DRUG COMPANIES. TECHNOLOGY STOCKS. AND H-M-O'S.
<P>
APPLE COMPUTER IS THE ONLY CALIFORNIA COMPANY TO REMAIN UNCHANGED THROUGH TODAY'S TRADING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127SC oiled birds-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC oiled birds-I</H3><BR>
THE SO-CALLED "MYSTERY GUNK" IS STILL FLOATING IN THE MONTEREY BAY OFF THE SANTA CRUZ COASTLINE.
<P>
AND A STEADY STREAM OF BIRDS ARE COMING INTO LOCAL ANIMAL SHELTERS COVERED IN IT.
<P>
THE GOO HAS ALREADY KILLED ABOUT ONE HUNDRED BIRDS.
<P>
CHERI GYURO HAS THE LATEST.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139SC oiled birds-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC oiled birds-T</H3><BR>
CALIFORNIA FISH AND GAME OFFICIALS SAY THEY'RE NOT SURE EXACTLY HOW THE WHITE SUBSTANCE GOT INTO THE OCEAN.
<P>
BUT THEY DO SAY IF IT WAS DUMPED.IT'S A VIOLATION OF THE FISH AND GAME CODE AS WELL AS FEDERAL REGULATIONS.
<P>
IF YOU HAVE ANY INFORMATION ABOUT THE "MYSTERIOUS GUNK", YOU'RE ENCOURAGED TO CALL THE U.S. COAST GUARD IN SAN FRANCISCO AT AREA CODE  437-3073.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125salinas chase folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>salinas chase folo</H3><BR>
A SAN JOSE MAN IS STILL IN THE HOSPITAL AFTER LEADING POLICE ON A HIGH SPEED CHASE. OVER THE WEEKEND.
<P>
THE CHASE FINALLY ENDED WHEN POLICE SHOT THE MAN IN SALINAS.
<P>
38-YEAR-OLD KEVIN FITZGERALD IS IN STABLE CONDITION TONIGHT.WITH A BULLET WOUND TO THE LEG.
<P>
POLICE SHOT HIM AFTER HE LED THEM ON A HIGH SPEED CHASE FROM SAN JOSE TO SALINAS. THEN ATTEMPTED TO ESCAPE ON FOOT.
<P>
FITZGERALD IS CHARGED WITH DRIVING UNDER THE INFLUENCE AND EVADING ARREST.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110castroville att murder>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>castroville att murder</H3><BR>
A CASTROVILLE MAN IS ATTACKED AND ROBBED ON HIS WAY HOME FROM A BAR EARLY THIS MONRING.
<P>
MONTEREY COUNTY POLICE ARE CALLING IT A CASE OF ATTEMPTED MURDER. 
<P>
THE VICTIM SAYS TWO PEOPLE APPROACHED HIM AND DEMANDED MONEY.
<P>
WHEN THE MAN OFFERED THEM FOUR DOLLARS. THE SUSPECTS ALLEGEDLY BEAT AND KICKED HIM. THEN STOLE HIS WALLET.
<P>
POLICE ARE STILL LOOKING FOR THE SUSPECTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130INS scam>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>INS scam</H3><BR>
A MONTH LONG INVESTIGATION INTO FAKE IMMIGRATION CARDS ENDS WITH THE ARREST OF THREE SUSPECTS IN WATSONVILLE.
<P>
INVESTIGATORS SAY AN UNDER-COVER AGENT BOUGHT PHONY CARDS FROM A SUSPECT IN DOWNTOWN WATSONVILLE.
<P>
DURING A SEARCH OF HOMES ON SEBASTIA LANE AND JEFFERSON STREET. AGENTS DISCOVERED FAKE I-N-S. SOCIAL SECURITY AND DRIVER'S LICENSE CARDS. AS WELL AS THE EQUIPMENT USED TO PRODUCE THEM.
<P>
TWO OF THE SUSPECTS WERE CHARGED WITH CONSPIRACY TO SELL AND DISTRIBUTE FRAUDULENT GOVERNMENT DOCUMENTS.
<P>
THE THIRD WAS ARRESTED ON DRUG CHARGES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129abalone symposium>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>abalone symposium</H3><BR>
HUNDREDS OF EXPERTS FROM AROUND THE WORLD ARE IN MONTEREY THIS WEEK DISCUSSING GROUND-BREAKING RESEARCH ON ABALONE.
<P>
	THE POPULAR SEA SNAIL NETS THREE MILLION DOLLARS EACH YEAR FOR CALIFORNIA'S ABALONE AQUACULTURE  INDUSTRY. 
<P>
	THIS WEEK, RESEARCHERS ARE LEARNING MORE ABOUT GENETIC RESEARCH OF THE ABALONE. AS WELL AS NEW ARTIFICIAL DIET TECHNOLOGY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134jackson march>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>jackson march</H3><BR>
THE REVEREND JESSE JACKSON LEADS THOUSANDS IN A  MARCH IN SACRAMENTO TODAY. PROTESTING PROP 209.
<P>
THE MARCH ENDED AT THE STATE CAPITOL BUILDING WHERE THE PROTESTERS HELD A FOUR HOUR RALLY.
<P>
JACKSON WAS ONE OF 50 SPEAKERS.
<P>
HE CALLED PETE WILSON A "DREAM BUSING GOVERNOR" FOR SUPPORTING THE CONTROVERSIAL END OF AFFIRMATIVE ACTION IN CALIFORNIA.
<P>
JACKSON PROMISED TO PUSH TO GET MORE THAN 250-THOUSAND VOTERS TO HELP RESTORE AFFIRMATIVE ACTION PROGRAMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A DRUG DEALER. THAT TRADED DRUGS FOR SEX. MAY HAVE INFECTED AS MANY A HUNDRED YOUNG WOMEN WITH THE VIRUS THAT CAUSES AIDS.
<P>
THAT STORY FROM UPSTATE NEW YORK. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(HIV infected kids)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(HIV infected kids)</H3><BR>
POLICE HAVE CONFIRMED THAT 20-YEAR-OLD NEWSHAWN WILLIAMS INFECTED AT LEAST 11 YOUNG GIRLS WITH H-I-V.
<P>
TWENTY-EIGHT PEOPLE REPORTEDLY HAD DIRECT SEXUAL CONTACT WITH WILLIAMS. FIFTY-THREE HAD SECONDARY CONTACT. MEANING THEY HAD SEX WITH ONE OF THE TWENTY-EIGHT.
<P>
17 OTHERS ARE STILL BEING TESTED.
<P>
THE VICTIMS RANGE IN AGE FROM 13 TO 24 YEARS OLD.
<P>
WILLIMS IS BEHIND BARS TONIGHT. ON UNRELATED DRUG CHARGES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(mall fire) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(mall fire) </H3><BR>
A POPULAR NEW JERSEY MALL IS IN RUINS.AFTER A HUGE FIRE RACED THROUGH THE BUILDING. 
<P>
TEN FIREFIGHTERS WERE HURT BATTLING THE FLAMES.AND ABOUT A DOZEN STORES INSIDE THE SHOPPING CENTER WERE DESTROYED. 
<P>
THE FIRE WAS REPORTED EARLY THIS MORNING. AND TOOK SEVERAL HOURS TO GET UNDER CONTROL.
<P>
STILL NO WORD ON HOW THE FIRE STARTED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22(buttons suicide)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(buttons suicide)</H3><BR>
THE AIR FORCE SAYS THE CRASH OF ONE OF ITS JETS INTO A COLORADO MOUNTAINSIDE LAST APRIL. WAS AN ACT OF SUICIDE. 
<P>
A MILITARY REPORT ON THE DEATH OF CAPTAIN 
<P>
CRAIG BUTTON. SAYS THE CRASH WAS A SPUR-OF-THE-MOMENT ACT. BY A MAN WHO HAD 
<P>
DISPLAYED NO SUICIDAL TENDENCIES. 
<P>
INVESTIGATORS RULED OUT AIRCRAFT MALFUNCTION AND OTHER POSSIBLE CAUSES.  
<P>
MILITARY OFFICIALS SAY THE REASON WHY BUTTON COMMITTED SUICIDE. IS STILL A MYSTERY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137DENVER SNOW-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>DENVER SNOW-I</H3><BR>
WINTER CAME EARLY. AND WITH A VENGEANCE.TO COLORADO. 
<P>
A MASSIVE SNOWSTORM DUMPED MORE THAN FOUR FEET OF SNOW OVER THE WEEKEND. 
<P>
FOX'S ALICIA ACUNA  SHOWS US WHAT'S HAPPENING IN THE MILE-HIGH CITY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/junk mail>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/junk mail</H3><BR>
STATISTICS SHOW. MOST OF US THROW OUT MORE THAN TEN PIECES OF MAIL EVERY WEEK. 
<P>
THIS SO-CALLED "JUNK MAIL". CAN BE ANYTHING FROM UNSOLICITED CREDIT CARD OFFERS TO CATALOGUES.
<P>
NOW. A NEW LAW IS MAKING IT EASIER FOR CONSUMERS TO SAY "NO" TO UNWANTED MAIL.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
ACCORDING TO THE ENVIRONMENTAL PROTECTION AGENCY. JUNK MAIL IS NOT ONLY ANNOYING CONSUMERS. IT'S ALSO FILLING UP MUNICIPAL WASTE SITES. MAKING UP AS MUCH AS 2-PERCENT OF LAND FILL SPACE.
<P>
CHANGES IN THE FAIR CREDIT REPORTING ACT COULD SLOW THE PROCESS BY REDUCING THE AMOUNT OF UNWANTED MAIL SENT TO CONSUMERS.
<P>
UNDER THE NEW LAW. CONSUMERS CAN CALL ONE OF THESE THREE TOLL FREE NUMBERS. TO HAVE THEIR NAME REMOVED FROM THE LISTS FOR TWO YEARS. OR REQUEST A FORM TO GET PERMANENTLY ERASED FROM THE DATABASE. 
<P>
IF YOU DO CALL. BE PATIENT. IT COULD BE ANYWHERE FROM THREE TO SIX MONTHS BEFORE YOU NOTICE ANY DIFFERENCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132rolls royce for sale>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>rolls royce for sale</H3><BR>
ONE OF THE PREMIERE LUXURY CAR COMPANIES IN THE WORLD. IS UP FOR GRABS. 
<P>
VICKER P-L-C. THE COMPANY THAT OWNS ROLLS ROYCE. HAS DECIDED TO UNLOAD THE FAMOUS LINE OF CARS.  
<P>
THE COMPANY SAYS IT CAN'T KEEP UP WITH THE INVESTMENT NEEDED TO CARRY THE LINE FOR THE NEXT SEVERAL YEARS.
<P>
BOTH B-M-W AND MERCEDES ARE SAID TO BE MAKING BIDS TO BUY THE COMPANY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40NFL>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NFL</H3><BR>
TONITE YOU GET 2-MONDAY NIGHT FOOTBALL GAMES FOR THE PRICE OF ONE.
<P>
BECAUSE OF LAST NIGHT'S GAME 7 OF THE WORLD SERIES, THE MIAMI/CHICAGO GAME WAS PUSHED BACK 'TIL TONITE. ONLY PEOPLE IN THOSE CITIES GOT TO SEE THAT GAME.
<P>
FOR THE REST OF US, ITS THE SUPER BOWL RE-MATCH, AS GREEN BAY VISITS NEW ENGLAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
ON SATURDAY, THE SHARKS SNAPPED THEIR 4-GAME LOSING STREAK, WITH A 4-3 WIN AT NEW JERSEY.
<P>
TONITE THE SHARKS PLAY THE 2ND OF THEIR 5-GAME ROAD TRIP, IN NEW YORK VS. THE ISLANDERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE GOLDEN ST. WARRIORS FINISHED THE PRE-SEASON WITH A 1 AND 7 RECORD, THEY'LL  PLAY FOR REAL THIS FRIDAY, IN MINNESOTA VS. THE T-WOLVES, TIP-OFF IS 5:00.
<P>
NOW THE WARRIORS MAY BE DESTINED TO BE ONE OF THE WORST TEAMS IN THE LEAGUE THIS YEAR, BUT THEY DO PULL-OFF A TRADE TODAY.
<P>
THE WARRIORS SEND POINT GUARD MARK PRICE TO THE ORLANDO MAGIC. PRICE, IN HIS 11TH SEASON, IS LONG PAST HIS ALL-STAR DAYS. IN HIS ONE AND ONLY SEASON WITH THE WARRIORS, PRICE AVERAGED 11-POINTS AND 4-ASSISTS PER GAME. THE WARRIORS WERE REALLY PAYING HIM TOO MUCH, AND HE WANTED OUT.
<P>
IN EXCHANGE THE WARRIORS GET 2-PLAYERS. GUARD BRIAN SHAW, WHO WAS THE 6TH MAN ON THE MAGIC'S 1995 EASTERN CONFERENCE CHAMPIONSHIP TEAM. THEY ALSO GET FORMER 1ST ROUND PICK, DAVID VAUGHN. HE'S A FOWARD WHO'S HAD LITTLE PLAYING TIME IN 2-YEARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
WITH THE WORLD SERIES OVER, THE GIANTS MAKE A FEW MOVES TODAY.
<P>
THEY DECLINE TO EXCERCISE THEIR OPTION ON BACKUP CATCHER DAMON BERRYHILL, WHICH MEANS HE'S NOW A FREE AGENT.
<P>
ALSO PITCHERS ROD BECK, DOUG HENRY, AND TERRY MULHOLLAND ALL FILE FOR FREE AGENCY.
<P>
THE GIANT HAVEN'T INDICATED IF THEY PLAN TO SIGN ANY OR ALL OF THEM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Golf: Your Turn>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf: Your Turn</H3><BR>
AND FINALLY ITS GOLF TIP DAY, AND JOHN GEERTSEN OFFERS ADVICE, IT IS YOUR TURN FOR SUCCESS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50salinas culinary>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>salinas culinary</H3><BR>
SOME CHEFS FROM THE SALINAS CULINARY ACADEMY ARE INTO THE HALLOWEEN SPIRIT. TODAY THEY USED A PUMPKIN TO SHOW OFF THEIR CARVING TALENTS AT THE NORTHRIDGE MALL.
<P>
BUT THIS WAS NO ORDINARY PUMPKIN. IT WEIGHS OVER 250 POUNDS.
<P>
THE FINISHED PRODUCT WILL BE ON DISPLAY AT THE SALINAS VALLEY MEMORIAL HOSPITAL FOR PATIENTS AND VISITORS TO ENJOY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
<FONT SIZE=1>
<!--#include file="../footer.inc" -->
</BODY>
</HTML>
