
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
<TITLE>KCBA FIRST AT TEN, Tuesday, 11/25/97</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<TABLE WIDTH=100% BORDER=0 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD CLASS="a"><TR><TD CLASS="a" BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Tuesday, 11/25/97</H2></CENTER></TD>
</TABLE>

<TABLE WIDTH=100% BORDER=0 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Hwy 1 safety-INT>Hwy 1 safety-INT</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(FL boat collision)>(FL boat collision)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Hwy 1 safety-TAG>Hwy 1 safety-TAG</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(armored car robbery)>(armored car robbery)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#133aptos pedofile alert>aptos pedofile alert</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143(bel air fire)>(bel air fire)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Rancho chualar-IN>Rancho chualar-IN</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Crimestoppers>Crimestoppers</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Rancho chualar-GU>Rancho chualar-GU</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/trouble toys>Fox Biz/trouble toys</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Rancho chualar-TA>Rancho chualar-TA</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Gilroy retail sale>Gilroy retail sale</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145SC/SB county shoot>SC/SB county shoot</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134Acosta plaza policies>Acosta plaza policies</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137jail escapee>jail escapee</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Warriors>Warriors</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127DBF new street>DBF new street</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43NBA>NBA</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Marina gets fort ord>Marina gets fort ord</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Sharks>Sharks</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125SC public drinking>SC public drinking</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4549ers>49ers</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#136SC hwy 1 shoot>SC hwy 1 shoot</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Bump #5a (Santa)>Bump #5a (Santa)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/Bikers feed>Good News/Bikers feed</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139santa training>santa training</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#97bye bye>bye bye</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(SD planes collide)>(SD planes collide)</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144(dallas police chase)>(dallas police chase)</A></TD>

</Table>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=142Hwy 1 safety-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hwy 1 safety-INT</H3><BR>
ALAN, IT WAS A TRAFFIC NIGHTMARE ON HIGHWAY ONE EARLIER THIS EVENING.
<P>
FROM WATSONVILLE ALL THE WAY TO MONTEREY.HIGHWAY ONE WAS AT A STANDSTILL.
<P>
ALL THIS BECAUSE OF TWO SMALL TRAFFIC ACCIDENTS.
<P>
AND WHAT'S SO IRONIC IS THAT THIS SIGN WAS JUST POSTED TODAY BY SEVERAL PEOPLE IN OUR COMMUNITY HOPING TO CHANGE THE HAZARDS OF DRIVING ON THIS ROAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Hwy 1 safety-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hwy 1 safety-TAG</H3><BR>
A FEW SAFETY TIPS WHEN DRIVING.ESPECIALLY DURING THE HOLIDAYS.
<P>
SLOW DOWN, WATCH YOUR SPEED, PAY ATTENTION TO OTHER DRIVERS AND OTHER DRIVE WAYS, DON'T DRINK AND DRIVE AND ALWAYS WEAR YOUR SEATBELT.
<P>
SOMETHING ELSE TO ADD.C-H-P OFFICERS SAY IF YOU'RE CAUGHT DRIVING ON THIS STRETCH OF HIGHWAY ONE WITH OUT YOUR HEADLIGHTS ON DURING THE DAY.YOU WILL BE CITED.
<P>
REPORTING LIVE FROM HIGHWAY ONE I'M CHERI GYURO, ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=133aptos pedofile alert>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>aptos pedofile alert</H3><BR>
POLICE ARE PUTTING OUT A WARNING TONIGHT FOR APTOS RESIDENTS. TO BE ON THE LOOK-OUT FOR A MAN WHO ATTEMPTED TO LURE A YOUNG BOY INTO HIS TRUCK.
<P>
YESTERDAY THE FATHER OF AN 11-YEAR OLD BOY TOLD POLICE HIS SON WAS WALKING HOME FROM SCHOOL ON VIENNA DRIVE. WHEN A MAN ATTEMPTED TO  LURE THE BOY INTO HIS TRUCK.
<P>
TODAY THE SANTA CRUZ COUNTY SHERIFF'S OFFICE ISSUED A WARNING TO LOCAL SCHOOLS AND PARENTS. TO BE ON THE LOOK-OUT FOR THIS TYPE OF SUSPICIOUS BEHAVIOR.
<P>
THE SUSPECT IS DESCRIBED AS A 40-TO-50 YEAR OLD WHITE MALE.
<P>
HE HAS BROWN HAIR AND A MOUSTACHE. AND DRIVES A NEWER MODEL DARK BLUE PICK-UP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Rancho chualar-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rancho chualar-IN</H3><BR>
THE MONTEREY COUNTY PLANNING COMMISSION HAS ALREADY VOTED NOT TO RECOMMEND IT. BUT IT'S UP TO THE BOARD OF SUPERVISORS TO APPROVE A CONTROVERSIAL. 900 UNIT HOUSING DEVELOPMENT IN CHULAR.
<P>
THE BOARD WAS TO HAVE CONSIDERED RANCHO CHUALAR TWO AT ITS MEETING THIS AFTERNOON. BUT A LAST MINUTE ROAD BLOCK HAS PUT THE PROJECT ON HOLD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Rancho chualar-GU>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rancho chualar-GU</H3><BR>
TALK ABOUT POPULATION GROWTH. IF THE RANCHO CHUALAR-TWO PROJECT EVER GETS OFF THE GROUND. THIS SMALL UN-INCORPORATED TOWN WILL TRIPLE ITS CURRENT NUMBER OF RESIDENTS. THAT'S *IF* IT GETS OFF THE GROUND.
<P>
THIS DOCUMENT STANDS IN THE WAY OF THE HUGE LOW AND MODERATE INCOME HOUSING PROJECT.  ITS THE COUNTY GRAND JURY REPORT ON THE RANCHO CHUALAR PROJECT. HOT OFF THE PRESSES TODAY.
<P>
THE REPORT EXPRESSES CONCERNS SIMILAR TO THOSE OF THE PROJECTS OPPONANTS. HOW WILL THE DEVELOPMENT IMPACT THE SEWAGE SYSTEM. THE WATER SYSTEM. THE SCHOOL. POLICE PROTECTION.
<P>
THE DEVELOPER PLEDGES TO TAKE CARE OF ALL OF THOSE CONCERNS. BUT THE GRAND JURY REPORT POINTS TO THE COMPLETED. AND CONSIDERABLY SMALLER. RANCHO CHUALAR ONE. IT CLAIMS THE SAME DEVELOPER DIDN'T FULFILL IT'S OBLIGATIONS THERE.
<P>
A GROUP OF CONCERNED RESIDENTS HAVE BEEN MAKING THE SAME CLAIMS.
<P>
SOT:  RCII 18:27 "Promised houses at 85-thou. none of those things happened."
<P>
AND UNTIL SOME OF THOSE CONCERNS ARE ADDRESSED. THE GRAND JURY TOLD THE BOARD OF SUPERVISORS IT SHOULDN'T EVEN CONSIDER RANCHO CHUALAR TWO.  TODAY. THE BOARD VOTED TO POSTPONE DISCUSSION ON THE MATTER UNTIL NEXT MONTH.
<P>
SOT: BOB #1 00:10 "We were surprised.  Erroneous infor. did not talk to developer."
<P>
IN FACT. DEVELOPERS SAY THE GRAND JURY REPORT SIMPLY REFLECTS THEIR OPPONANTS VIEWPOINT.
<P>
SOT:  BOB#2 05:45 "All you have to do is go to county records office. see list of conditions.  everyone of those conditions were satisfactorily addressed."
<P>
SOT:  RCII 19:06 "19 CITIZENS WHO HAVE NO POLITICAL AX TO GRIND SAW DEFICIENCIES OF RCI. VALIDATED OUR EVERY CONTENTION."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Rancho chualar-TA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rancho chualar-TA</H3><BR>
DEVELOPERS SAY. DESPITE THE GRAND JURY REPORT. THEY FEEL SATISFIED THEY HAVE FULLFILLED THEIR OBLIGATIONS REGARDING RANCHO CHUALAR ONE.
<P>
THEY ALSO SAY THEY HAVE NOTHING FURTHER TO ADDRESS REGARDING THEIR PROPOSED SOLUTIONS TO INFRASTRUCTURE CONCERNS OF RANCHO CHUALAR TWO.
<P>
THEY SAY THEY SIMPLY WANT TO TAKE UP THE ISSUE WITH THE BOARD OF SUPERVISORS.
<P>
THEY'LL NOW HAVE TO WAIT UNTIL JANUARY 27TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145SC/SB county shoot>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC/SB county shoot</H3><BR>
A MAN IS DEAD AFTER BEING SHOT IN THE BACK AND HEAD.
<P>
IT HAPPENED THIS AFTERNOON ON CHITTENDEN ROAD. NEAR THE SANTA CRUZ/ SAN BENITO COUNTY LINE.
<P>
DETECTIVES SAY NEIGHBORS HEARD GUNSHOTS AND THEN A CAR DRIVE-AWAY.
<P>
A REGISTERED NURSE ON THE SCENE. TRIED TO RESUSCITATE THE MAN. BUT HE WAS PRONOUNCED DEAD AT THE SCENE.
<P>
STILL NO WORD ON ANY SUSPECTS OR A MOTIVE IN THE SHOOTING.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137jail escapee>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>jail escapee</H3><BR>
A PRISONER FROM THE MONTEREY COUNTY JAIL. WALKED OFF HIS WORK DETAIL THIS AFTERNOON.
<P>
DEPUTIES SAY THE INMATE. BRIAN LANGLEY. WAS SERVING TIME FOR ASSAULT, BATTERY, DISTURBING THE PEACE, AND WRITING BAD CHECKS.
<P>
LANGLEY'S LAST KNOWN ADDRESS WAS ON WEST STREET IN SALINAS.
<P>
INVESTIGATORS ARE ASKING ANYONE WHO SEES HIM. TO CALL POLICE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127DBF new street>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>DBF new street</H3><BR>
WHAT HAD BEEN CONSIDERED A NATURAL DEATH IN SALINAS.HAS NOW BECOME A HOMICIDE.
<P>
THE BODY OF A HISPANIC MAN WAS FOUND YESTERDAY NEAR THE TRAIN TRACKS ON "NEW" STREET NEAR MARKET.
<P>
SALINAS POLICE DETECTIVES RETURNED TO THE SCENE TODAY TO SEARCH FOR MORE CLUES.
<P>
OFFICERS ORIGINALLY THOUGHT HE DIED OF NATURAL CAUSES, BUT AFTER AUTOPSY REPORTS RETURNED.THEY SAY HE WAS BEATEN TO DEATH.
<P>
"Obviously the injuries were internal, so when they began checking them, they discovered there was trauma to him and it was as a result of a beating, so at that point it elevated to a homicide."
<P>
POLICE SAY THE MAN  WAS AROUND 32 YEARS OLD AND  MAY HAVE BEEN HOMELESS.
<P>
RIGHT NOW, THEY'RE TRYING TO TRACK DOWN NEXT OF KIN.
<P>
TODAY, THEY QUESTIONED SEVERAL PEOPLE NEAR SOLEDAD STREET, LOOKING FOR WITNESSES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Marina gets fort ord>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marina gets fort ord</H3><BR>
THE ARMY HAS HANDED OVER MORE THAN 50 ACRES OF LAND. TO THE CITY OF MARINA.
<P>
IN A CEREMONY THIS MORNING AT THE WATER CITY ROLLER HOCKEY COMPLEX.  THE ARMY AND THE NATIONAL PARKS SERVICE. PRESENTED THE PROPERTY TO THE CITY.
<P>
THE LAND TRANSFER INCLUDES THE EQUESTRIAN CENTER, FOUR TENNIS COURTS, AN OLYMPIC SIZE POOL, AND SOME 80 BARRACKS.
<P>
A LOT OF LAND HAS EXISTING BUILDINGS. NEED TO DEMOLISH TO MAKE ROOM FOR OTHER THINGS. BUTTHEN AGAIN, TALKING ABOUT ACQUIRING 100 ADDITIONAL ACRES, FOR MARINA OPEN SPACE, WHICH WILL INCLUDE FOOTBALL AND SOCCER FIELDS AND SO ON.
<P>
ANOTHER HUNDRED ACRES, PLUS THE ABRAMS PARK FAMILY HOUSING VILLAGE.  ARE EXPECTED TO BE TURNED OVER TO THE CITY WITHIN THE NEXT YEAR. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125SC public drinking>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC public drinking</H3><BR>
A SANTA CRUZ COUNTY SUPERVISOR WANTS A COUNTY-WIDE BAN ON DRINKING IN PUBLIC PLACES.
<P>
THE BAN ALREADY EXISTS IN THE COUNTY'S FOUR MAJOR CITIES. BUT IT DOESN'T EFFECT THE UNINCORPORATED AREAS.
<P>
SUPERVISOR JEFF ALMQUIST POINTS TO THE JULY FOURTH BOULDER CREEK AUTO ACCIDENT THAT KILLED FOUR TEENAGERS. AS PROOF THE COUNTY NEEDS TOUGHER DRINKING LAWS.
<P>
THE PROPOSAL WILL NOW GO TO THE COUNTY COUNCILOR'S OFFICE FOR THEIR RECOMMENDATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=136SC hwy 1 shoot>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC hwy 1 shoot</H3><BR>
THE SANTA CRUZ D-A HAS RULED THE OFFICER INVOLVED SHOOTING ON HWY ONE LAST MONTH. WAS ACCIDENTAL.
<P>
THE SHOOTING HAPPENED WHEN 18-YEAR OLD ARMANDO GARCIA.  LED POLICE ON A DRUNKEN HIGH SPEED CHASE FROM WATSONVILLE TO CAPITOLA.
<P>
GARCIA WAS SUSPECTED OF BEING INVOLVED IN SEVERAL HIT AND RUN ACCIDENTS. AND WAS ONLY ARRESTED AFTER HE CRASHED HIS VEHICLE AND WAS SHOT BY A SHERIFF'S DEPUTY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/Bikers feed>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/Bikers feed</H3><BR>
GOOD NEWS FOR A LOCAL FOOD BANK. AS AN UNEXPECTED DONATION ROLLS IN. JUST IN TIME FOR THE HOLIDAYS. 
<P>
THE MONTEREY BAY AREA BIKERS ASSOCIATION WHEELED UP TO THE SALINAS POLICE DEPARTMENT THIS AFTERNOON. AND DONATED HOLIDAY TURKEYS FOR NEEDY FAMILIES.
<P>
THE SALINAS P-D RE-DIRECTED THE BIKERS TO DOROTHY'S KITCHEN.  A LOCAL FOOD BANK. WHERE THEY DROPPED OFF THE LOAD OF TURKEYS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
TWO PLANES COLLIDE OVER A RESIDENTIAL AREA IN SAN DIEGO. SENDING ONE PLUNGING INTO A HOUSE.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(SD planes collide)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(SD planes collide)</H3><BR>
THE PILOT OF THE PLANE THAT CRASHED INTO THE HOUSE. DIED ON IMPACT. 
<P>
LUCKILY. NO ONE WAS IN THE HOUSE AT THE TIME.
<P>
THE OTHER PLANE WAS CARRYING A STUDENT PILOT AND 
<P>
HIS INSTRUCTOR.
<P>
THAT PLANE WAS ABLE TO CRASH LAND IN A FIELD NEARBY.
<P>
THE PLANE WITH THE SINGLE PILOT APPARENTLY HIT THE SECOND PLANE. AS THE STUDENT AND INSTRUCTOR WERE PRACTICING LANDINGS AT A NEARBY AIRFIELD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(FL boat collision)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(FL boat collision)</H3><BR>
SIX PEOPLE ARE DEAD. TWO OTHERS ARE CRITICAL CONDITION. AFTER A BOAT COLLISION NEAR FORT LAUDERDALE, FLORIDA. 
<P>
IT HAPPENED WHEN A SPEEDBOAT SLICED THROUGH A THIRTY-ONE-FOOT CABIN CRUISER. SHATTERING THE BOAT INTO DOZENS OF PIECES.
<P>
ALL SIX FATALITIES WERE ON THE CRUISER.
<P>
THE TWO MEN IN THE SPEEDBOAT ARE IN CRITICAL CONDITION.
<P>
INVESTIGATORS SAY ALCOHOL MAY HAVE PLAYED A ROLE IN THE COLLISION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(armored car robbery)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(armored car robbery)</H3><BR>
POLICE IN OAKLAND. ARE ON THE HUNT FOR AN ARMORED TRUCK GUARD. WHO REPORTEDLY KILLED HIS PARTNER. AND THEN MADE OFF WITH 300-THOUSAND DOLLARS. 
<P>
20-YEAR-OLD THOMAS WHEELOCK HAD COLLECTED THE MONEY ALONG WITH HIS PARTNER. RODRIGO CORTEZ. ON THEIR ROUNDS LAST NIGHT. 
<P>
TODAY POLICE FOUND CORTEZ'S BULLET-RIDDEN BODY INSIDE THE ABANDONED TRUCK. 
<P>
WHEELOCK WAS ALREADY ON PROBATION FOR A MISDEMEANOR CONNECTED TO A 1995 ROBBERY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143(bel air fire)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(bel air fire)</H3><BR>
A HOUSE FIRE IN THE POSH LOS ANGELES SUBURB OF BEL AIR CAUSES OVER A HALF MILLION DOLLARS IN DAMAGES. 
<P>
THE FIRE WAS UNDER CONTROL IN LESS THAN AN HOUR. BUT NOT BEFORE IT HAD CONSUMED THE ROOF AND CAUSED SMOKE AND WATER DAMAGE THROUGHOUT THE MANSION. 
<P>
SEVERAL FIREFIGHTERS WERE ALSO HURT WHEN THE ROOF OF THE HOME CAVED IN ON THEM.
<P>
THEY WERE TREATED AT THE SCENE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Crimestoppers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Crimestoppers</H3><BR>
CRIMESTOPPERS TRYING TO ROPE IN AN ESCAPED CONVICT TONIGHT.
<P>
VICTOR AGUILAR WALKED AWAY FROM SALINAS VALLEY STATE PRISON IN SEPTEMBER.
<P>
HE WAS SERVING A TWO YEAR TERM FOR ROBBERY.
<P>
HE HAS THE WORD "WIZARD" TATTOOED ON HIS BACK.AND "AGUILAR" TATTOOED ON HIS CHEST.
<P>
HE'S BELIEVED TO STILL BE ON THE CENTRAL COAST AND  MIGHT BE DRIVING  BLUE VOLKSWAGEN JETTA. 
<P>
INFORMATION LEADING TO AGUILAR'S ARREST COULD BE WORTH UP TO ONE THOUSAND DOLLARS.
<P>
JUST CALL THE CRIMESTOPPERS ANONYMOUS LINE AT 1 800 499 CRIME.
<P>
CALLER IDENTITIES REMAIN ANONYMOUS.OPERATORS ARE STANDING BY RIGHT NOW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/trouble toys>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/trouble toys</H3><BR>
WHEN YOUR KIDS MAKE THEIR CHRISTMAS LISTS. YOU BETTER CHECK THEM TWICE. FOR TOYS THAT MAY BE DANGEROUS.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
TODAY. CONSUMER ADVOCATES IN WASHINGTON ATTACHED A WARNING LABEL ON 18 DIFFERENT TOYS. EVERYTHING FROM THE STOMP ROCKET TO A TINY TOY CLOWN.
<P>
CHOKING HAZARDS APPEAR TO REPRESENT THE GREATEST THREAT.
<P>
THE GROUP SAYS MANY TOYS THAT ARE BOUGHT AS LAST MINUTE STOCKING STUFFERS INCLUDE SMALL PARTS. THE KIND SMALL CHILDREN LIKE TO STICK IN THEIR MOUTHS.
<P>
THE TOYS ARE ALSO OFTEN SO-CALLED BIN ITEMS. INEXPENSIVE TOYS BOUGHT AT DOLLAR STORES. OR FROM BULK DISPLAYS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Gilroy retail sale>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gilroy retail sale</H3><BR>
THE GILROY OUTLETS HAVE BEEN SOLD.
<P>
THE PREVIOUS OWNERS. SAN DIEGO-BASED BURNHAM PACIFIC PROPERTIES. SAYS IT AGREED TO SELL THE SPACE TO HORIZON GROUP. FOR 38-POINT-5 MILLION DOLLARS TODAY.
<P>
HORIZON IS A MICHIGAN BASED FACTORY OUTLET MALL COMPANY.
<P>
THE NEW OWNERS SAY THEY DON'T HAVE ANY PLANS TO MAKE ANY CHANGES TO THE GILROY OUTLETS IN THE NEAR FUTURE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134Acosta plaza policies>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Acosta plaza policies</H3><BR>
THINGS MAY BE GETTING WORSE FOR FOLKS THAT LIVE IN THE TROUBLE-PLAGUED ACOSTA PLAZA IN SALINAS. 
<P>
THE CALIFORNIA DEPARTMENT OF INSURANCE HAS ASSIGNED A SPECIAL INVESTIGATOR. TO FIND OUT WHETHER THE RESIDENTS. WERE SOLD BOGUS HOMEOWNERS INSURANCE POLICIES BACK IN 19-95.
<P>
AS MANY AS A HUNDRED-THIRTY RESIDENTS MAY HAVE BEEN SCAMMED.
<P>
THE INVESTIGATION COMES JUST A WEEK AFTER THE MONTEREY COUNTY D-A'S OFFICE. BEGAN INVESTIGATING CHARGES OF EMBEZZLEMENT AGAINST THE HOMEOWNERS ASSOCIATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE WARRIORS HAVE A REASONABLE CHANCE TONITE OF WINNING THEIR FIRST HOME GAME OF THE YEAR.
<P>
THE NEW JERSEY NETS ARE IN TOWN, AND EVEN THOUGH AT 7 AND 4 THE NETS ARE OFF TO THEIR BEST START IN 19-YEARS, THE NETS JUST DON'T STRIKE FEAR IN THE HEARTS OF NBA PLAYERS, BUT THEN AGAIN, NEITHER DO THE WARRIORS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43NBA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA</H3><BR>
SO WITH THEIR LOSS TONITE, THE BULLS DROP TO 8 AND 6 ON THE YEAR, VERY UN-BULL LIKE.
<P>
BUT CHICAGO HAS BEEN WITHOUT INJURED ALL-STAR SCOTTIE PIPPEN ALL YEAR, AND THE CRY OUT OF THE WINDY CITY HAS BEEN, WHEN WE GET SCOTTIE PLAYING WITH MICHAEL AGAIN, EVERYTHING WILL BE FINE.
<P>
THERE'S JUST ONE PROBLEM, PIPPEN DOESN'T WANT TO PLAY FOR THE BULLS THIS YEAR.
<P>
PIPPEN DID PRACTICE TODAY IN SEATTLE, BUT SCOTTIE CONFIRMED THE RUMORS THAT HE WANTS OUT OF CHICAGO.
<P>
PIPPEN WILL MAKE LESS THAN 3-MILLION DOLLARS THIS YEAR, THAT'S A FRACTION OF WHAT MANY LESSER PLAYERS ARE MAKING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO THE ICE.    
<P>
AND WITH 2-WINS AND A TIE, THE SHARKS HAVE FEEL PRETTY GOOD ABOUT THE WAY THEY'VE PLAYED ON THIS ROAD TRIP.
<P>
TONITE SAN JOSE VISITS THE TORONTO MAPLE LEAFS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4549ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
THE 49ERS FACE THEIR GREATEST CHALLENGE OF THE SEASON SUNDAY, WHEN THEY TRAVEL TO KANSAS CITY TO FACE THE 9 AND 3 CHIEFS.
<P>
CHIEFS HEAD COACH MARTY SCHOTTENHEIMER LETS US KNOW IF EX-49ER QUARTERBACK ELVIS GRBAC WILL BE HEALTHY ENOUGH TO PLAY, OR IF K.C. WILL CONTINUE TO GO WITH RICH GANNON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Bump #5a (Santa)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump #5a (Santa)</H3><BR>
COMING UP.
<P>
NOT JUST ANYONE CAN BE SANTA. WE'LL TELL YOU WHY IT TAKES A SPECIAL *CLASS* OF PEOPLE. RIGHT AFTER THIS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139santa training>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>santa training</H3><BR>
NEW YORK SANTAS ARE GETTING READY FOR THE HOLIDAYS IN NEW YORK.
<P>
THE SANTAS OF 19-97 PREPARED TO HIT THE STREET BUT IT WASN'T EASY.
<P>
THESE VOLUNTEERS HAVE TO COMPLETE *SANTA SCHOOL* BEFORE GOING INTO ACTION.
<P>
SOME OF THE RULES FOR PROSPECTIVE SANTAS ARE. NO SMOKING IN PUBLIC AND NO EATING GARLIC.. BECAUSE IT'S NOT THE PROPER SCENT FOR SANTA CLAUS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=97bye bye>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bye bye</H3><BR>
THAT'S GOING TO DO IT FOR FOX NEWS FIRST AT TEN.
<P>
TUNE IN AGAIN TOMORROW  NIGHT AT TEN.
<P>
UNTIL THEN, TAKE CARE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144(dallas police chase)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(dallas police chase)</H3><BR>
NOT AN  ORDINARY AFTERNOON COMMUTE FOR AUTHORITIES IN DALLAS TUESDAY.
<P>
AREA POLICE ALONG WITH MEDIA HELICOPTERS CHASED A PAROLE VIOLATOR AT SPEEDS UP TO ONE-HUNDRED MILES AN HOUR.
<P>
THE PURSUIT CROSSED AT LEAST FIVE CITIES WINDING THROUGH BACK ALLEYS AS PEDESTRIANS DOVE OUT OF HIS WAY.
<P>
THE ONLY COLLISION CAUSED THE GET AWAY CAR'S TIRES TO GO FLAT AFTER IT CLIPPED ANOTHER TRUCK CAUSING THE FRONT FENDER TO CUT THE TIRE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
<FONT SIZE=1>
<!--#include file="../footer.inc" -->
</BODY>
</HTML>
