
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
<TITLE>KCBA Fox News at Ten (g/Sun), Sunday, 11/9/97</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<TABLE WIDTH=100% BORDER=0 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD CLASS="a"><TR><TD CLASS="a" BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (g/Sun), Sunday, 11/9/97</H2></CENTER></TD>
</TABLE>

<TABLE WIDTH=100% BORDER=0 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123US/Iraq-I>US/Iraq-I</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126New York Bomb>New York Bomb</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121US/Iraq-G>US/Iraq-G</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Stunt Show>Stunt Show</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114US/Iraq-T>US/Iraq-T</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#28WX/CURRENTS>WX/CURRENTS</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Hillary Plane>Hillary Plane</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39Raiders>Raiders</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Attempt 187>Attempt 187</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4249ers >49ers </A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Triple Shoot Folo>Triple Shoot Folo</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44ATL>ATL</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Fatal Dive Pebble>Fatal Dive Pebble</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Warriors>Warriors</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Fatal Bike Folo>Fatal Bike Folo</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Golf>Golf</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#136SJO Cop Wife Kill>SJO Cop Wife Kill</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Soccer>Soccer</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Barge Explosion>Barge Explosion</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Gay Chorus>Gay Chorus</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#24Reptile Smugglers>Reptile Smugglers</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#97Big Band Closer>Big Band Closer</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#124Chile Soccer Riot>Chile Soccer Riot</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Timber>Timber</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Train Crash>Train Crash</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Au Pair-I>Au Pair-I</A></TD>

</Table>
<A HREF=\main.htm>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=123US/Iraq-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>US/Iraq-I</H3><BR>
YES.  WE WENT OUT TO A LOCAL SHOPPING CENTER TO GET PEOPLE'S REACTION AND JUST ABOUT EVERYONE HAD AN OPINION ABOUT IT.
<P>
MOST PEOPLE WE SPOKE TO SAID THIS TIME AROUND, THE U.S. SHOULD *NOT* BACK DOWN FROM IRAQ'S THREATS, EVEN THOUGH *NOT* BACKING DOWN MAY MEAN *WAR*.
<P>
BECAUSE THAT'S EXACTLY WHAT PRESIDENT CLINTON SAYS MAY HAPPEN. IF THE CURRENT TENSIONS CONTINUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121US/Iraq-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>US/Iraq-G</H3><BR>
IRAQI OFFICIALS TODAY TURNED AWAY U.N. WEAPONS INSPECTORS FOR THE SEVENTH STRAIGHT DAY.  AND PROMISED TO SHOOT DOWN ANY AMERICAN SURVEILLANCE PLANES IN ITS AIR SPACE.
<P>
THESE THREATS PROMPTED STRONG WORDS FROM PRESIDENT CLINTON TONIGHT.
<P>
THE PRESIDENT AIMED HIS WARNING DIRECTLY AT IRAQI PRESIDENT SADDAM HUSSEIN.
<P>
HIS MESSAGE?  IF YOU SHOOT AT U.S. PLANES. IT'LL BE A DECLARATION OF WAR.
<P>
BUT IRAQ IS REFUSING TO BACK DOWN.  IN FACT, THE LATEST WORD FROM HUSSEIN IS: A CLASH WITH THE U.S. IS INEVITABLE.
<P>
HUSSEIN HAS TOLD HIS PEOPLE THAT THE U.S. IS TRYING TO BULLY IRAQ INTO, QUOTE, "SACRIFICE OR SLAVERY."
<P>
SECRETARY OF STATE MADELINE ALBRIGHT CALLED THOSE CLAIMS, LIES.
<P>
SADDAM HUSSEIN IS A CONGENITAL LIAR AND HE CHEATS AND HE 
<P>
STEALS AND HE CANNOT BE ALLOWED TO DEFY THE INTERNATIONAL COMMUNITY.
<P>
BACK HERE AT HOME. MOST LOCAL RESIDENTS AGREED WITH ALBRIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114US/Iraq-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>US/Iraq-T</H3><BR>
OUT OF ALL THE PEOPLE WE INTERVIEWED HERE LOCALLY, THAT WOMAN WAS THE ONLY ONE WHO *DIDN'T* FEEL THE U.S. WAS DOING THE RIGHT THING.
<P>
THE LATEST WORD FROM WASHINGTON IS, DESPITE THE THREATS, U.S. PLANES *WILL* FLY THROUGH IRAQ TONIGHT AND INTO TOMORROW, SO IT'S GOING TO BE INTERESTING TO SEE WHAT HAPPENS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Hillary Plane>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hillary Plane</H3><BR>
AN AIRPLANE CARRYING HILLARY RODDHAM CLINTON WAS FORCED TO DUMP FUEL AND RETURN TO ANDREWS AIR FORCE BASE SHORTLY BEFORE TEN P-M EASTERN TIME.
<P>
THE BOEING 7-0-7 USED AS AIR FORCE ONE SINCE THE NIXON ADMINISTRATION WAS HEADING TO CENTRAL ASIA.
<P>
AN OFFICIAL ON BOARD THE PLANE SAYS A LIGHT INDICATOR SIGNALED A PROBLEM WITH AN ENGINE.
<P>
NO INJURIES WERE REPORTED.
<P>
MRS. CLINTON WAS HEADED TO THE FORMER SOVIET UNION FOR A NINE-DAY TRIP TO ENCOURAGE DEVELOPMENT OF THE NOW-INDEPENDENT REPUBLICS.
<P>
	
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Attempt 187>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Attempt 187</H3><BR>
A FAMILY DISAGREEMENT  BETWEEN FIVE BROTHERS.  LEADS TO A SHOOTING IN SALINAS.
<P>
POLICE  RESPONDED TO A DISTURBANCE CALL LATE LAST NIGHT AT THE ONE-THOUSAND BLOCK OF JOHN STREET.
<P>
INVESTIGATORS  SAY.  THE BROTHERS WERE ARGUING. AND THE HOT WORDS ESCALATED INTO A SHOOTING SOME TIME LATER.
<P>
INCUE: @ 1:31:19 AS THEY DROVE.
<P>
THIRD BROTHER PULLED UP AND THREATENED TO SHOOT.THEY PULLED DOWN THE WINDOW TO SEE WHAT HE MEANT ADN THAT'S WHEN THEY WERE HIT BY 
<P>
OUTCUE:1:31:31  SINGLE GUN SHOT
<P>
ONE OF THE BROTHERS WAS HIT IN THE HAND.  AND ANOTHER WAS WOUNDED IN THE THIGH.
<P>
BOTH WERE TREATED FOR THEIR INJURIES  AND RELEASED.
<P>
THE SUSPECT. RONALD HERNANDEZ. IS IN CUSTODY FOR ATTEMPTED MURDER.
<P>
NO WORD ON WHY THE BROTHERS WERE ARGUING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Triple Shoot Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Triple Shoot Folo</H3><BR>
SALINAS POLICE SAY THEY BELIEVE THE MAN LIKELY RESPONSIBLE FOR YESTERDAY MORNING'S DOUBLE SHOOTING.COMMITTED SUICIDE.
<P>
INVESTIGATORS FOUND THE BODY OF A MAN MATCHING THE DESCRIPTION OF 25-YEAR OLD ELIZAR MENDEZ ON OLD STAGE ROAD YESTERDAY AFTERNOON. 
<P>
THE MAN HAD APPARENTLY SHOT HIMSELF.
<P>
SEVERAL HOURS EARLIER. MENDEZ ALLEGEDLY CONFRONTED HIS EX-GIRLFRIEND AND HER NEW BOYFRIEND ON MOHAR STREET AND SHOT THEM SEVERAL TIMES.
<P>
THE VICTIMS ARE LISTED IN STABLE CONDITION AT NATIVIDAD MEDICAL CENTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=112Fatal Dive Pebble>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fatal Dive Pebble</H3><BR>
A VACAVILLE MAN IS DEAD.  AFTER A DIVING ACCIDENT IN THE WATERS OFF PEBBLE BEACH.
<P>
SHERIFF'S DEPUTIES.  SAY 42-YEAR-OLD JAMES JEPPSON WAS DIVING WITH HIS SON  NEAR STILLWATER COVE LAST NIGHT.
<P>
JEPPSON'S SON DISCOVERED HIS FATHER ON THE OCEAN FLOOR.  60-FEET BELOW THE SURFACE.
<P>
RESCUERS TRIED TO REVIVE JEPPSON. BUT HE WAS PRONOUNCED DEAD AT THE SCENE.
<P>
AN AUTOPSY IS SCHEDULED FOR MONDAY. TO DETERMINE THE EXACT CAUSE OF DEATH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Fatal Bike Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fatal Bike Folo</H3><BR>
INVESTIGATORS HAVE IDENTIFIED THE BODY OF A MAN KILLED ON HIS BICYCLE IN NORTH MONTEREY COUNTY.
<P>
THE MONTEREY COUNTY CORONER SAYS THE VICTIM WAS 37-YEAR-OLD JAMES KLEIN OF WATSONVILLE.
<P>
KLEIN WAS ON HIS BIKE TRAVELING SOUTHBOUND ON ELKHORN ROAD YESTERDAY.WHEN HE WAS STRUCK BY A CAR TRAVELING IN THE SAME DIRECTION.
<P>
DEPUTIES SAY KLEIN WAS THROWN OVER AN EMBANKMENT LANDING 20 FEET FROM THE ROADWAY.
<P>
THE CAR FLED THE SCENE.AND INVESTIGATORS ARE SEARCHING FOR SUSPECTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=136SJO Cop Wife Kill>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SJO Cop Wife Kill</H3><BR>
IN LOS GATOS.A BODY FOUND STUFFED IN THE TRUNK OF A
<P>
CAR IS BELIEVED TO BE THAT OF A SAN JOSE POLICE OFFICER'S MISSING WIFE.
<P>
POLICE FOUND 48-YEAR-OLD JUDITH HARRIS' WHITE BUICK WHILE CHECKING THE REAR PARKING LOT OF A MEDICAL COMPLEX.
<P>
SANTA CLARA COUNTY CORONERS ARE NOT SAYING HOW LONG IT HAD BEEN IN THE TRUNK OR THE CAUSE OF DEATH.
<P>
HARRIS WAS LAST SEEN AT 10:30 FRIDAY MORNING.
<P>
APARENTLY SHE TOLD HER HUSBAND SHE WAS GOING TO SHOP AND VISIT RELATIVES IN THE HAYWARD AREA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Barge Explosion>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Barge Explosion</H3><BR>
FOUR MEN ARE INJURED IN AUSTRALIA AFTER A DEMOLITION AT SEA WENT HORRIBLY WRONG. 
<P>
THE MEN WERE ABOARD AN OLD DREDGER BOAT BEING SCUTTLED TO FORM AN ARTIFICIAL REEF. 
<P>
BUT THE EXPLOSION TO DEMOLISH IT.WAS MORE POWERFUL THAN EXPECTED. 
<P>
THE MEN WERE THROWN INTO THE WATER BY THE FORCE OF THE BLAST BUT. REMARKABLY. WERE NOT SERIOUSLY INJURED. 
<P>
THE DECK BELOW COLLAPSED AND DEBRIS WAS SENT SHOWERING DOWN ON DIVERS AND CAMERA BOATS COVERING THE OPERATION. 
<P>
POLICE ARE INVESTIGATING THE INCIDENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=24Reptile Smugglers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Reptile Smugglers</H3><BR>
ALSO FROM THE LAND DOWN UNDER.  TWO JAPANESE TOURISTS ARE ARRESTED AFTER ALLEGEDLY TRYING TO SMUGGLE  REPTILES OUT OF AUSTRALIA. 
<P>
THE SUSPECTS ARE IDENTIFIED AS A  PET SHOP OWNER AND HIS COMPANION.A NURSE. 
<P>
THEY APARENTLY HAD MORE THAN THIRTY ANIMALS IN THEIR 
<P>
POSSESSION.INCLUDING TWO SNAKES.  A DOZEN LIZARDS.  FROGS. A SCORPION. A SPIDER. COCKROACHES. AND SNAILS. 
<P>
THE TWO ARE EXPECTED TO APPEAR IN COURT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=124Chile Soccer Riot>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chile Soccer Riot</H3><BR>
MOST SOCCER RIOTS HAPPEN DURING A MATCH. BUT IN CHILE ANGRY FANS GOT INTO IT A WEEK IN ADVANCE. 
<P>
ABOUT FIFTEEN-THOUSAND PEOPLE SHOWED EARLY AT CHILE'S NATIONAL STADIUM FOR TICKETS TO A CRUCIAL MATCH NEXT WEEKEND. 
<P>
BUT WHEN TICKETS SOLD-OUT YESTERDAY. ANGRY FANS WENT WILD. 
<P>
POLICE DEPLOYED ANTI-RIOT TEAMS AND USED WATER CANNONS TO DISPERSE THE CROWD. 
<P>
CHILE MUST WIN NEXT WEEK'S MATCH AGAINST BOLIVIA IN ORDER TO QUALIFY FOR THE 19-98 WORLD CUP FINALS.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Train Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Train Crash</H3><BR>
A TRAIN CRASH IN PORTUGAL HAS CLAIMED SIX LIVES. AND LEFT THIRTEEN INJURED. 
<P>
TWO LOCAL SERVICE TRAINS COLLIDED HEAD-ON IN SOUTHERN PORTUGAL. 
<P>
RESCUERS HAD TO CUT THEIR WAY INTO THE DAMAGED PART OF THE TRAIN. 
<P>
THE ACCIDENT HAPPENED 125 MILES SOUTH OF LISBON. 
<P>
THE CAUSE OF THE CRASH IS NOT YET KNOWN AND THE DEATH TOLL IS EXPECTED TO RISE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126New York Bomb>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>New York Bomb</H3><BR>
NEW YORKERS HAD A RUDE AWAKENING TODAY. 
<P>
THE MERRILL LYNCH BUILDING. LOCATED JUST TWO BLOCKS FROM CITY HALL. WAS ROCKED BY A SMALL BOMB BLAST. 
<P>
POLICE, ANTI-TERRORIST AND EMERGENCY SERVICE WORKERS IMMEDIATELY RESPONDED. 
<P>
NO ONE WAS INJURED. 
<P>
OFFICERS SAY. A CRUDE DEVICE DAMAGED GLASS IN THE BUILDING. 
<P>
THE INVESTIGATION CONTINUES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Stunt Show>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stunt Show</H3><BR>
IT LOOKS LIKE THE DUTCH ARE HAVING A "WHEELY" GOOD TIME.
<P>
MOTORCYCLIST HORST KLAARS.  REACHED NEW HEIGHTS WHEN HE PERFORMED A SERIES OF STUNTS WITH HIS BIKE SUSPENDED ON A CABLE. 
<P>
ALTHOUGH YOU MIGHT SAY THIS SHOW WAS HANGING BY A THREAD. KLAARS WOWED THE CROWD WITH STUNTS THAT PROVED HE WAS NO UNEASY RIDER. 
<P>
EVIL KENIVIL. EAT YOUR HEART OUT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=28WX/CURRENTS>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>WX/CURRENTS</H3><BR>
THAT SITE. NEARLY AS SCARY AS OUR UPCOMING WEATHER FORECAST. RAIN AND WIND IS ON THE WAY.
<P>
BUT RIGHT NOW OUTSIDE OUR STUDIOS AT K-C-B-A IN SALINAS IT REMAINS CLOUDY.  THE TEMPERATURE IS ________ DEGREES.
<P>
MONTERY REPORTS CLOUDS AND _________.
<P>
AND FOR OUR VIEWERS IN SANTA CRUZ IT'S ________ DEGREES.
<P>
TAKING A LOOK FROM OUTER SPACE. OUR SATELLITE SHOWS THE STATE UNDER A HEAVY CLOUD COVER. IMAGES AREN'T SHOWING RAIN ON OUR CENTRAL COAST YET.
<P>
HOWEVER. A FEW LIGHT SHOWERS ARE BEGINNING TO FALL ON THE NORTHERN CALIFORNIA COASTLINE.
<P>
THERE WAS ENOUGH SUN TODAY TO WARM THE TEMPERATURES INTO THE LOW 70'S. GILROY PEAKED AT 72 TODAY. WHILE SALINAS HIT 70.
<P>
TONIGHT'S FORECAST IS CALLING FOR THIS STORM SYSTEM TO CONINUE MOVING INLAND. WITH RAIN AND WIND KICKING UP OVERNIGHT. THE SNOW LEVELS WILL DROP TOMORROW EVENING. THE HIGHER ELEVATIONS OF THE SIERRAS COULD GET UP TO A FOOT OF SNOW BY TOMORROW NIGHT.
<P>
THE FORECAST TOMORROW IS CALLING FOR RAIN TURNING TO SHOWERS BY THE AFTERNOON. THAT'S WHEN THE WIND SHOULD PICK UP AS WELL. AND WITH THE UNSTABLE AIRMASS. THERE'S EVEN A CHANCE OF A THUNDERSTORM INLAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39Raiders>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Raiders</H3><BR>
AFTER LOSING TWO STRAIGHT AND DROPPING TO 3-6. IT SEEMED LIKE IT COULDN'T GET ANY WORSE FOR THE RAIDERS.
<P>
WITH THE SAINTS IN TOWN. MOST HAD ALREADY PENCILED IN A "W" BUT WHERE THERE'S A WILL THERE'S A WAY.TO LOSE THAT IS.
<P>
HIS USUAL COOL SELF IN THIS ONE.
<P>
-------
<P>
THE RAIDERS WOULD GET OFF TO A GOOD START. IN THE 2ND QUARTER.  HIT'S  AND THE BIG MAN WILL RUMBLE DOWN TO THE SIX. DUDLEY FINISHES WITH 115 YARDS RECEIVING.
<P>
-------
<P>
WOULD DO THE REST TAKING IT IN FOR THE SCORE. RAIDERS ON TOP 7-NOTHING.
<P>
-------
<P>
THE OAKLAND DEFENSE ALSO DOING THE JOB. LOOK AT THE HIT  PUTS ON. BUT THE SAINTS WOULD KEEP IT CLOSE.
<P>
------
<P>
IN THE 4TH QUARTER.  TAKES IT IN FROM A YARD OUT. THEIR 1ST TOUCHDOWN IN THREE WEEKS. GAME TIED AT TEN.
<P>
-------
<P>
AND THEN WITH LESS THEN 3-MINUTES TO GO IN THE GAME. FORMER CAL STAR  PUTS THE SAINTS AHEAD FOR GOOD WITH A 44-YARD FIELD GOAL. FINAL. 13-10 NEW ORLEANS. THE SAINTS SNAP A 3-GAME LOSING STREAK. THE RAIDERS DROP THEIR 3RD STRAIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4249ers >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers </H3><BR>
THE 49ERS MEANTIME, FACE ANOTHER TOUGH OPPONENT THIS WEEK WHEN THEY PLAY THE PHILADELPHIA EAGLES ON MONDAY NIGHT.
<P>
THE NINERS WILL BE GOING FOR THEIR 8TH STRAIGHT VICTORY AS THEY BEGIN THE TOUGHEST PART OF THEIR SCHEDULE WITH GAMES AGAINST KANSAS CITY, MINNESOTA AND DENVER TO FOLLOW.
<P>
SPEAKING OF DENVER. THE BRONCOS HOSTING CAROLINA AT A SNOWY MILE HIGH STADIUM.
<P>
----------
<P>
BIG DAY FOR BRONCO PUNT RETURNER. THE FORMER STANFORD STAR TAKES TWO PUNTS BACK FOR TOUCHDOWNS. THIS ONE WILL GO 75 YARDS. THE OTHER AN 82 YARDER.      IT'S JUST THE 3RD TIME IN NFL HISTORY A PLAYERS HAS RETURNED TWO IN A QUARTER AND THE BRONCOS WOULD NEVER LOOK BACK. 
<P>
----------
<P>
THROWS FOR 227 YARDS AND THIS TD TO  AS THE BRONCOS ROLL OVER THE PANTHERS.
<P>
FINAL. 34-NOTHING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44ATL>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>ATL</H3><BR>
LET'S GO AROUND THE LEAGUE.  SHOWING HOW MUCH HE CARES FOR.
<P>
----------
<P>
HOW ABOUT THE JOB  DID OFF THE BENCH FOR CINCINNATI. MOST PEOPLE PROBABLY THOUGHT THE 36 YEAR OLD QB WAS RETIRED BUT HE COMES IN FOR  AND RALLY'S THE BENGALS TO VICTORY WITH TWO TD TOSSES.
<P>
----------
<P>
IT WAS A RECORD SETTING DAY FOR DETROITS. NUMBER TWENTY BECOMING THE 1ST PLAYER TO GO OVER 1-THOUSAND YARDS IN 9 STRAIGHT SEASONS AND HE ALSO MOVES INTO 3RD PLACE FOR CAREER USHING YARDAGE PASSING TONY DORSETT. HE'S JUST 432 YARDS FROM PASSING. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE WARRIORS ARE BACK ON THE HARDWOOD AFTER LOSING THEIR HOME OPENER LAST-NIGHT.
<P>
P-J CARLISIMO'S TEAM STILL WITHOUT A WIN AFTER FIVE GAMES AND IT DOESN'T GET ANY EASIER AS THEY HEAD SOUTH TO TAKE ON THE LAKERS.
<P>
DEL HARRIS'S BOYS PLAYING WELL. THE LAKERS OFF TO A 3-OH START.
<P>
------------
<P>
THEY WOULD RUN EARLY IN THE GAME. THE OUTLET TO. AND WATCH HIM BLOW PAST SPREWELL. KOBE COMES OFF THE BENCH TO SCORE 25. LAKERS BY 15 AT THE HALF.
<P>
------------
<P>
SHAQ ALSO HAS A BIG GAME PLAING IN JUST HIS 2ND GAME OF THE SEASON. THE BIG MAN POURING IN 27 POINTS TO GO WITH 19 REBOUNDS.
<P>
-----------
<P>
LAKERS JUST BLOW THIS ONE WIDE OPEN IN THE 2ND HALF.
<P>
----------
<P>
LAKERS HAND THE WARRIORS THEIR 6TH STRAIGHT LOSS.
<P>
FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
IN GOLF NEWS. GIL MORGAN FIRED A FINAL ROUND 71 TO GIVE HIM A 2-SHOT VICTORY OVER HALE IRWIN AT THE SENIOR TOUR CHAMPIONSHIP.
<P>
IT'S HIS 6TH VICTORY OF THE SEASON. AND WITH IT HE GOES OVER THE 2-MILLION MARK FOR THE SEASON JOINING IRWIN AND TIGER WOODS AS THE ONLY GOLFERS TO EVER ACCOMPLISH THE FEAT.
<P>
NEXT. FINAL ROUND OF THE KAPALUA INTERNATIONAL.11TH HOLE., LEADING BY 2 STROKES.WATCH THIS TEE-SHOT. IT'LL WIND UP A FEW FEET FROM THE CUP.HE WOULD BIRDIE TO GO 20-UNDER.
<P>
-------------
<P>
LOVE WOULD FIRE A FINAL ROUND 68. A BEAUTIFUL SHOT OF THE APPROACH AT 18. LOVE SET'S A TOURNAMENT RECORD FINISHING 22-UNDER PAR. IT'S THE 2ND TIME HE'S WON THE EVENT. AND IT COMES IN THE 16TH AND FINAL KAPALUA INTERNATIONAL.HIS WIFE AND KIDS ALSO ENJOYING THE TIME IN MAUI. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Soccer>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Soccer</H3><BR>
FINALLY. USA TAKING ON CANADA IN WORLD CUP QUALIFYING.1ST HALF. 5TH MINUTE. USA'S  PUTS THE SHOT PAST CANADA'S  THE AMEIRCANS LEAD 1-NOTHING EH.
<P>
-----------
<P>
2ND HALF. MORE FROM THE RED WHITE AND BLUE.  WILL PUNCH IN HIS SECOND GOAL OF THE GAME AND THE U.S. SHUTS OUT CANADA. 3-NILL.
<P>
WITH THE WIN. TEAM USA QULIFIES FOR THE WORLD CUP FINALS FOR THIRD STRAIGHT TIME. THE CUP WILL TAKE PLACE NEXT SUMMER IN FRANCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Gay Chorus>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gay Chorus</H3><BR>
NATURAL SOUND.SINGING
<P>
THE SUNSET CENTER IN CARMEL PLAYS HOST TO THE  WORLD-RENOWNED  "SAN FRANCISCO GAY MEN'S CHORUS".
<P>
THE TWO-HUNDRED MEMBER GROUP HAS BEEN ENTERTAINING AUDIENCES FOR NEARLY 20-YEARS. AND TODAY'S PROGRAM WAS FOR A GOOD CAUSE.
<P>
PROCEEDS FROM THE EVENT GO TO THE MONTEREY COUNTY AIDS PROJECT AND JOHN THE 23RD AIDS MINISTRY.
<P>
THE MEMBERS OF THE CHORUS ARE ALSO ACTIVE IN VOLUNTEER WORK IN THE BAY AREA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=97Big Band Closer>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Band Closer</H3><BR>
AND MUSIC OF ANOTHER SORT TONIGHT AT SHERWOOD HALL IN SALINAS.
<P>
IT WAS THE GREAT PERFORMANCE'S "BATTLE OF THE 19-40S BIG BANDS". FEATURING THE BIG BAND ALUMNI ORCHESTRA. PLAYING THE MUSIC OF THE DORSEY BROTHERS. KAY KAISER. AND GLENN MILLER. PLUS A SPECIAL APPEARANCE BY JOHNNY SMITH'S INK SPOTS.
<P>
SO WE'LL SAY GOODBYE. AND LET  YOU ENJOY THE BIG BAND SOUND.
<P>
GOOD NIGHT.
<P>
MUSIC
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Timber>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Timber</H3><BR>
AND STILL IN AUSTRALIA.  PRIME MINISTER JOHN HOWARD GOT MORE THAN HE BARGAINED FOR. WHEN HE TURNED UP TO  SIGN AN AGREEMENT HIS GOVERNMENT HAD STRUCK WITH THE TIMBER INDUSTRY. 
<P>
ENVIRONMENTAL ACTIVISTS THREW THEMSELVES ON THE AUSTRALIAN LEADER'S CAR AS HE ARRIVED AT A FOREST NURSERY IN NORTHERN TASMANIA. 
<P>
THE PROJECT CALLS FOR AN INTENSIVE PLANTING AND THINNING OPERATION.  WITH PRIVATE LANDOWNERS GETTING PAID TO PROTECT ENDANGERED TREES. 
<P>
BUT ANGRY ENVIRONMENTALISTS SAY.  IT'S A SELL-OUT TO THE TIMBER INDUSTRY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Au Pair-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Au Pair-I</H3><BR>
BRITISH NANNY LOUISE WOODWARD COULD FIND OUT HER FATE AS EARLY AS TOMORROW. WHEN THE JUDGE IS EXPECTED TO ISSUE HIS DECISION ON THE INTERNET. 
<P>
THE JURY'S VERDICT HAS SPARKED INTENSE PUBLIC DEBATE ABOUT WHAT THE JUDGE SHOULD DO WITH THE VERDICT.
<P>
FOX'S RITA COSBY HAS MORE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=\main.htm>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<!--#include file="../footer.inc" -->
</BODY>
</HTML>
