
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
<TITLE>KCBA FIRST AT TEN, Monday, 11/24/97</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<TABLE WIDTH=100% BORDER=0 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD CLASS="a"><TR><TD CLASS="a" BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Monday, 11/24/97</H2></CENTER></TD>
</TABLE>

<TABLE WIDTH=100% BORDER=0 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138CARS IN SLOUGH>CARS IN SLOUGH</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(jet crash folo)>(jet crash folo)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Morgan Hill fire-INT>Morgan Hill fire-INT</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(barnes & noble ind)>(barnes & noble ind)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Morgan Hill fire-TAG>Morgan Hill fire-TAG</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Reno prosecutor>Reno prosecutor</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Tiffany sentence>Tiffany sentence</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#136space walk satellite>space walk satellite</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#1335 salinas burglaries>5 salinas burglaries</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122contaminat turkey-IN>contaminat turkey-IN</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125n. county car shoot>n. county car shoot</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134contaminat turkey-T>contaminat turkey-T</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132soledad murder>soledad murder</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/cheap comp>Fox Biz/cheap comp</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129New seaside cops>New seaside cops</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Raiders>Raiders</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Nivette custody>Nivette custody</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4149ers>49ers</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Crime Drop>Crime Drop</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Sharks>Sharks</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/turkey give-away>Good News/turkey give-away</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Golf: Your Turn>Golf: Your Turn</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50white hse x-mas tree >white hse x-mas tree </A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(RR crossing fatals)>(RR crossing fatals)</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#97bye bye>bye bye</A></TD>

</Table>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=138CARS IN SLOUGH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>CARS IN SLOUGH</H3><BR>
GOOD EVENING AND THANKS FOR JOINING US. I'M ALAN MARSDEN. 
<P>
AN ELDERLY WOMAN IS DEAD. THREE OTHERS ARE HURT.  AFTER  A TWO-CAR COLLISION NEAR THE MOSS LANDING PG&E PLANT.
<P>
IT HAPPENED JUST AFTER 6-O'CLOCK TONIGHT. 
<P>
C-H-P SAYS THREE ELDERLY WOMEN WERE PULLING OUT OF A PRIVATE DRIVE-WAY. ONTO HIGHWAY ONE.  IN A BLUE BUICK. WHEN THEY DROVE INTO THE PATH OF A RED THUNDERBIRD.
<P>
THE IMPACT SENT BOTH CARS CAREENING INTO ELKHORN SLOUGH.    THE PASSENGER OF THE BLUE BUICK SUFFERED THE BRUNT OF THE IMPACT. SHE WAS PRONOUNCED DEAD AT THE SCENE.  
<P>
TWO OTHER ELDERLY WOMEN AND THE DRIVER OF THE RED THUNDERBIRD WERE HURT. 
<P>
THEY WERE TRANSPORTED TO WATSONVILLE COMMUNITY HOSPITAL. 
<P>
STILL NO WORD ON THEIR CONDITION TONIGHT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Morgan Hill fire-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Morgan Hill fire-INT</H3><BR>
ALAN, THIS TRAGIC STORY IS ACUALLY TURNING OUT TO HAVE A HAPPY ENDING.
<P>
ONE FAMILY WE SPOKE TO SAYS THEY'RE LUCKY TO BE ALIVE.THANKS TO THEIR OWN LITTLE GIRL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Morgan Hill fire-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Morgan Hill fire-TAG</H3><BR>
TAMMY SAYS LOCAL CHURCHES, OTHER FAMILY MEMBERS AND HER EMPLOYER HAVE ALSO BEEN HELPFUL.
<P>
ANNASTASHIA SAYS SHE LEARNED A GOOD LESSON FROM THIS FIRE.DON'T LEAVE A CANDLE UNATTENDED.
<P>
REPORTING LIVE FROM THE NEWSDESK, I'M CHERI GYURO.ALAN BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Tiffany sentence>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tiffany sentence</H3><BR>
A JUDGE THROWS THE BOOK AT A SANTA CRUZ MAN. CONVICTED OF STABBING HIS ESTRANGED WIFE TO DEATH. 
<P>
HOWARD TIFFANY RECEIVED THE MAXIMUM SENTENCE. 26 YEARS TO LIFE. FOR KILLING KATHLEEN TIFFANY ON MARCH 17TH.
<P>
IN COURT TODAY. THE VICTIM'S FATHER CONFRONTED TIFFANY ABOUT THE FUTURE OF HIS TWO CHILDREN.
<P>
IN: "I DON'T KNOW WHERE YOU GOT THE IDEA." OC: "THAT'S NEVER GOING TO HAPPEN." 
<P>
KATHLEEN TIFFANY'S PARENTS NOW HAVE CUSTODY OF THE CHILDREN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=1335 salinas burglaries>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>5 salinas burglaries</H3><BR>
THIEVES BREAK INTO FIVE BUSINESSES IN DOWNTOWN SALINAS OVER THE WEEKEND.
<P>
POLICE SAY THE BURGLARS BROKE A WINDOW AND FORCED OPEN LOCKED OFFICES YESTERDAY AFTERNOON.
<P>
THE BUSINESSES INCLUDED THE MARTIAL ARTS ACADEMY. CAREER QUEST. SUAREZ TRUCKING. HELP-U-SELL. AND THE PACIFIC LOCATIONAL ASSOCIATION.
<P>
STILL NO WORD ON HOW MUCH MONEY THE CROOKS GOT AWAY WITH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125n. county car shoot>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>n. county car shoot</H3><BR>
POLICE ARE STILL ON THE LOOKOUT FOR TWO SUSPECTS    WHO FIRED ON MONTEREY COUNTY SHERIFF DEPUTIES AND C-H-P OFFICERS THIS WEEKEND.
<P>
IT HAPPENED WHEN A HIGHWAY PATROL OFFICER STARTED CHASING A STOLEN CAR ON HIGHWAY 1-0-1 IN SALINAS.
<P>
THE SUSPECTS INSIDE THE CAR STARTED SHOOTING AT POLICE FROM OUT THE BACK WINDOW. FORCING POLICE TO SLOW DOWN.
<P>
THE SUSPECTS THEN DITCHED THE CAR AND TOOK OFF ON FOOT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132soledad murder>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>soledad murder</H3><BR>
POLICE ARE ALSO STILL INVESTIGATING THE FATAL SHOOTING OF A 21-YEAR-OLD MAN. IN THE PARKING LOT OF A FAST FOOD RESTAURANT IN SOLEDAD.
<P>
POLICE SAY TWO MEN SHOT THE VICTIM SEVERAL TIMES YESTERDAY. AS HE WALKED ACROSS THE MCDONALD'S PARKING LOT.  
<P>
THE VICTIM WAS TAKEN BY FRIENDS TO THE SOLEDAD POLICE DEPARTMENT.
<P>
THEN TO SALINAS VALLEY MEMORIAL HOSPITAL. WHERE HE DIED IN THE EMERGENCY ROOM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129New seaside cops>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>New seaside cops</H3><BR>
FOLKS IN SEASIDE WILL PROBABLY NOTICE MORE POLICE PATROLING THE STREETS.
<P>
	THAT'S BECAUSE FOUR NEW OFFICERS. TWO MEN AND TWO WOMEN. HAVE BEEN ADDED TO THAT CITY'S POLICE FORCE.
<P>
THEY WERE SWORN-IN AT A CEREMONY AT CITY HALL THIS MORNING.
<P>
THE NEW OFFICERS SPENT THE AFTERNOON IN TARGET PRACTICE, GETTING QUALIFIED TO CARRY THEIR WEAPONS.
<P>
THE STREETS ARE SAFE. THESE OFFICERS WILL ALLOW US TO DO A BETTER JOB WITH RESPECT TO PROBLEMS THAT DO OCCOUR.
<P>
ABSOLUTELY IT'LL MAKE A DIFFERENCE, PEOPLE WILL SEE THOSE FACES OUT ON THE STREET. AND OUR OFFICERS WON'T HAVE TO WORK SO MUCH OVERTIME.
<P>
	THE CHIEF SAYS HE HOPES TO HIRE FOUR MORE OFFICERS WITHIN THE NEXT SIX MONTHS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Nivette custody>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Nivette custody</H3><BR>
WHILE FORMER CARMEL PSYCHOLOGIST JAMES NIVETTE SITS IN A FRENCH PRISON.THE 18-MONTH-OLD SON HE ALLEGEDLY ABANDONED HAS BEEN PLACED IN TEMPORARY CUSTODY.
<P>
NIVETTE IS CHARGED IN SACRAMENTO COUNTY WITH MURDERING HIS GIRL FRIEND. THE BOY'S MOTHER.
<P>
NO WORK ON WHO LITTLE TYLER NIVETTE HAS BEEN PLACED WITH.
<P>
THAT'S BECAUSE THE JUDGE HAS ISSUED A GAG ORDER IN THE CUSTODY CASE.
<P>
THAT MEAN NO ONE INVOLVED IN THE CASE IS ALLOWED TO TALK ABOUT IT FURTHER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Crime Drop>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Crime Drop</H3><BR>
CRIME IN AMERICA IS ON THE DECLINE ACCORDING TO THE
<P>
F-B-I. 
<P>
IN FACT. THE FIRST HALF OF 1997 SAW A NINE-PERCENT DECREASE IN MURDER AND ROBBERY. COMPARED TO A YEAR EARLIER.
<P>
BUT HERE ON THE CENTRAL COAST. NOT ALL THE NEWS IS GOOD.
<P>
ALTHOUGH POLICE SAY THE RATE OF BURGLARIES AND ROBBERIES HAVE DECLINED  IN SALINAS.  THE CITY'S MURDER RATE IS *UP*. 13 HOMICIDES ON THE RECORD IN SALINAS  SO FAR THIS YEAR. COMPARED TO NINE LAST YEAR.
<P>
LOCAL COUNSELORS WHO TRY TO STEER KIDS AWAY FROM VIOLENCE SAY THEY'RE NOT SURPRISED.
<P>
"WE'VE SEEN STUDIES BEFORE WHERE. SOMETIMES TRIPLED."
<P>
POLICE SAY A COLLABORATIVE EFFORT BETWEEN LOCAL LAW ENFORCEMENT AND THE COMMUNITY IS THE KEY TO BRINGING THE CRIME RATE DOWN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/turkey give-away>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/turkey give-away</H3><BR>
GOOD NEWS FOR HUNDREDS OF CENTRAL COAST FAMILIES. WHO'LL HAVE MUCH MORE TO BE THANKFUL FOR THIS THURSDAY BECAUSE OF THE GENEROSITY OF OTHERS. 
<P>
	THE SALVATION ARMY BEGAN HANDING OUT HOLIDAY FOOD BASKETS AT ITS GOOD SAMARITAN CENTER IN SAND CITY THIS MORNING.
<P>
	OVER 500 LOCAL FAMILIES SIGNED UP TO RECIEVE THE DONTATED FOOD.
<P>
THE BASKETS INCLUDE FRUITS, AND VEGETABLES, A TURKEY, PLUS DINNER ROLLS, CRANBERRY SAUCE AND PUMPKIN PIE.
<P>
AND IN SANTA CRUZ COUNTY.  VALLEY CHURCHES UNITED  GAVE AWAY TURKEYS TO MORE THAN 14 HUNDRED PEOPLE TODAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
FOUR CHILDREN ARE DEAD AFTER A TRAIN SLAMS INTO THEIR MOTHER'S CAR.
<P>
THAT STORY FROM HELENA, ALABAMA.TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(RR crossing fatals)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(RR crossing fatals)</H3><BR>
POLICE SAY THE CAR DROVE PAST A RAILROAD CROSSING SIGN AND A STOP SIGN. AND STOPPED ON THE TRACKS.
<P>
TRAIN OFFICIALS SAY THE TRAIN'S EVENT RECORDER SHOWS THE ENGINEER BLEW THE HORN AS HE APPROACHED THE CROSSING.
<P>
THE CHILDREN. AGES FIVE TO 15. APPARENTLY DIED ON IMPACT. THE MOTHER IS IN SERIOUS CONDITION AT A LOCAL HOSPITAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(jet crash folo)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(jet crash folo)</H3><BR>
AN AIR FORCE F-15 FIGHTER CRASHES INTO THE ATLANTIC OCEAN. SIXTY MILES OFF THE COAST OF VIRGINIA BEACH THIS MORNING. 
<P>
THE PILOT WAS ABLE TO EJECT FROM THE PLANE. AND WAS QUICKLY RESCUED BY THE COAST GUARD.
<P>
THE CAUSE OF THE CRASH IS UNDER INVESTIGATION. 
<P>
IN SEPTEMBER. AFTER A RASH OF ACCIDENTS. THE MILITARY SUSPENDED ALL TRAINING FLIGHTS. AND HELD SAFETY REVIEWS OF ALL TRAINING MISSIONS.
<P>
NO WORD ON THE CAUSE OF TODAY'S CRASH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(barnes & noble ind)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(barnes & noble ind)</H3><BR>
A BARNES AND NOBLE BOOKSTORE HAS BEEN INDICTED UNDER A TENNESSEE OBSCENITY LAW.
<P>
A GRAND JURY CLAIMS THREE BOOKS BY PHOTOGRAPHERS JOCK STURGES AND DAVID HAMILTON MAY BE TO BLAME.
<P>
THE BOOKS.THE AGE OF INNOCENCE, THE LAST DAY OF SUMMER, AND RADIANT IDENTITIES. FOCUS ON PHOTOS OF NUDE CHILDREN. 
<P>
IT'S A MISDEMEANOR IN TENNESSEE TO DISPLAY OBSCENE MATERIALS IN PLACES VISIBLE TO MINORS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Reno prosecutor>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Reno prosecutor</H3><BR>
ATTORNEY GENERAL JANET RENO MAY BE READY TO 
<P>
END THE JUSTICE DEPARTMENT PROBE. INTO FUNDRAISING PHONE CALLS MADE BY PRESIDENT CLINTON AND VICE PRESIDENT GORE.  
<P>
AT A NEWS CONFERENCE TODAY. THE ATTORNEY GENERAL REFUSED TO COMMENT ON REPORTS THAT SHE WILL ACCEPT A JUSTICE DEPARTMENT TASK FORCE RECOMMENDATION.             THAT WOULD OFFICIALLY TURN DOWN AN INDEPENDENT COUNCIL PROBE INTO THE PRESIDENT AND VICE-PRESIDENT'S FUND RAISING PHONE CALLS
<P>
THE ATTORNEY GENERAL HAS UNTIL DECEMBER SECOND. TO DECIDE ON THE FUNDRAISER ISSUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=136space walk satellite>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>space walk satellite</H3><BR>
"FANTASTIC WORK" SAYS NASA'S MISSION CONTROL TONIGHT.
<P>
THE PRAISE WAS FOR THE CREW OF THE SPACE SHUTTLE COLUMBIA WHO SUCCESSFULLY CAPTURED A WAYWARD SATELLITE.
<P>
ASTRONAUTS WINSTON SCOTT AND TAKAO DOI MADE A SPACEWALK TO PERFORM THE TRICK.
<P>
THE TWO WAITED FOR AN HOUR FOR THE SPINNING. THREE-THOUSAND-POUND SATELLITE TO TILT THE RIGHT WAY.
<P>
THE TEN MILLION DOLLAR REUSABLE SATELLITE WAS RELEASED BY THE SHUTTLE LAST WEEK.  IT WAS SUPPOSED TO STUDY THE SUN FOR TWO DAYS.
<P>
ASTRONAUT DOI IS NOW THE FIRST JAPANESE MAN TO WALK IN SPACE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122contaminat turkey-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>contaminat turkey-IN</H3><BR>
ADEQUATELY COOKING YOUR THANKSGIVING TURKEY MAY SEEM LIKE COMMON SENSE. BUT IF IT'S NOT DONE RIGHT. THE RESULT COULD BE HAZARDOUS TO YOUR HEALTH.
<P>
TOM VACAR EXPLAINS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134contaminat turkey-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>contaminat turkey-T</H3><BR>
WE SHOULD ADD. THAT ACCORDING TO EXPERTS. COOKING BIRDS TO AT LEAST A-HUNDRED-EIGHTY DEGREES FAHRENHEIT. SERVING THEM PROPERLY. AND KEEPING ALL COUNTER TOPS, KNIVES AND OTHER UTENSILS CLEAN. WILL ENSURE A SAFE AND HEALTHY HOLIDAY MEAL.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/cheap comp>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/cheap comp</H3><BR>
IF THE HIGH PRICE TAG OF COMPUTERS HAS BEEN KEEPING YOU FROM BECOMING A CYBER-JUNKY.   YOU MAY BE IN LUCK.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
FOR THE FIRST TIME EVER. HOME COMPUTER PRICES ARE DOWN TO LESS THAN A THOUSAND DOLLARS.
<P>
THAT MAKES A P-C ONE OF THE ONLY PRODUCTS THAT'S ACTUALLY CHEAPER NOW. THAN THIS TIME LAST YEAR.
<P>
THAT'S GOOD NEWS FOR HOLDAY SHOPPERS.
<P>
MARKET ANALYSTS SAY. AT THIS RATE. MORE THAN HALF OF ALL HOMES WILL HAVE AT LEAST ONE PERSONAL COMPUTER BY THE YEAR 2-THOUSAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Raiders>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Raiders</H3><BR>
THE RAIDERS HANDED THE BRONCOS THEIR FIRST LOSS OF THE SEASON BACK ON OCTOBER 19TH, AND YOU KNEW WITH TONITE'S MONDAY NIGHT GAME IN DENVER, THAT THE MILE HIGH CROWD WOULD BE 10-MILES HIGH.
<P>
AND THERE'S STILL PLENTY OF BAD BLOOD BETWEEN AL DAVIS AND MIKE SHANAHAN, TO KEEP THIS GAME DICEY, DESPITE OAKLAND'S MISERABLE 4 AND 7 RECORD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4149ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
THE 49ERS WERE A LITTLE FLAT YESTERDAY, BUT THEY DID IMPROVE TO 11 AND 1, AND MOVED A STEP CLOSER TO CLINCHING HOME FIELD ADVANTAGE THROUGHOUT THE PLAYOFFS.
<P>
SO AS THE NINERS GO OVER THE GAME FILM TODAY OF YESTERDAY'S 17-10 WIN OVER THE SAN DIEGO CHARGERS, THE HOT TOPIC OF CONVERSATION AT COACH STEVE MARIUCCI'S PRESS CONFERENCE THIS MORNING, WAS THE CONDITION OF JERRY RICE, WHO HASN'T PLAYED A DOWN SINCE INJURING HIS KNEE IN THE OPENER AT TAMPA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO THE ICE, AND TONITE THE SHARKS VISIT THE MOLSON CENTER TO FACE THE NORTHEAST DIVISION'S FIRST PLACE TEAM, THE MONTREAL CANADIENS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Golf: Your Turn>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf: Your Turn</H3><BR>
AND FINALLY, IN OUR WEEKLY GOLF TIP, JOHN GEERTSEN TELLS US THAT THERE'S MORE TO ADRESSING THE BALL THAN JUST SAYING, "HELLO BALL."
<P>
IT IS YOUR TURN FOR SUCCESS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50white hse x-mas tree >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>white hse x-mas tree </H3><BR>
SOME ARE CALLING IT THE "CADILLAC OF CHRISTMAS TREES." 
<P>
AN 18-FOOT FRASER FIR WAS CUT DOWN AND READIED FOR ITS TRIP TO THE NATION'S CAPITOL TODAY.
<P>
SANFORD AND DEBBIE FISHEL WHO OWN A NORTH CAROLINA TREE FARM. WON THE RIGHT TO FURNISH THIS YEAR'S WHITE HOUSE TREE.
<P>
BUT THEY ENDED UP PAYING 4-HUNDRED DOLLARS FOR A NEIGHBOR'S TREE BECAUSE THEIR'S WASN'T TALL ENOUGH FOR THE "BLUE ROOM."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=97bye bye>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bye bye</H3><BR>
THAT'S GOING TO DO IT FOR FOX NEWS FIRST AT TEN.
<P>
TUNE IN AGAIN TOMORROW  NIGHT AT TEN.
<P>
UNTIL THEN, TAKE CARE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
<FONT SIZE=1>
<!--#include file="../footer.inc" -->
</BODY>
</HTML>
