
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
<TITLE>KCBA FIRST AT TEN, Thursday, 12/11/97</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 12/11/97</H2></CENTER></TD>
</TABLE>

<TABLE WIDTH=100% BORDER=0 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Cold Open(eastwo )>Cold Open(eastwo )</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(murder/torture)>(murder/torture)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Dela Vina fire>Dela Vina fire</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(amtrak accident)>(amtrak accident)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#136Eastwood b.s.-INT>Eastwood b.s.-INT</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139(arlington body mov)>(arlington body mov)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Eastwood b.s.-GUTS>Eastwood b.s.-GUTS</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132(hillary kicked out)>(hillary kicked out)</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134Eastwood b.s.-TAG>Eastwood b.s.-TAG</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Cisneros indict-INT>Cisneros indict-INT</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Toxic rain>Toxic rain</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/microsoft>Fox Biz/microsoft</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127HWY 5 pile-up-INT>HWY 5 pile-up-INT</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4049ers>49ers</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125FEMA denies>FEMA denies</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Giants>Giants</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Singleton mistrial>Singleton mistrial</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Warriors>Warriors</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Salinas peppers>Salinas peppers</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50christmas adobes>christmas adobes</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129fruitcake smash>fruitcake smash</A></TD>
<TR><TD CLASS="a" BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(orlando hostage)>(orlando hostage)</A></TD>

<TR>
<td colspan="2" bgcolor="#FFFFFF" CLASS="a"> 

<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=114Cold Open(eastwo )>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cold Open(eastwo )</H3><BR>
NATURAL SOUND OF CLINT EASTWOOD LAUGHING
<P>
CARMEL'S MOST FAMOUS RESIDENT HAS A LOT TO SMILE ABOUT TONIGHT.
<P>
AND SO DO LOCAL ENVIRONMENTALISTS.
<P>
WE'LL EXPLAIN, NEXT, ON KCBA, FOX NEWS, FIRST AT TEN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Dela Vina fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dela Vina fire</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
WE'LL HAVE THAT STORY FOR YOU IN A MOMENT BUT FIRST. DOZENS OF PEOPLE WERE EVACUATED FROM THEIR HOMES THIS AFTERNOON. AFTER A FIRE ENGULFS THE ROOF OF AN APARTMENT BUILDING.
<P>
THE FIRE WAS REPORTED  AT ABOUT 5-THIRTY ON DELA VINA AVENUE IN MONTEREY. 
<P>
FIREFIGHTERS SAY IT STARTED IN A WALL. THEN SPREAD TO THE ROOF OF THE APARTMENT BUILDING.
<P>
WHEN THE SMOKE CLEARED. TWO APARTMENTS HAD BEEN GUTTED. LEAVING FIVE PEOPLE FROM THREE DIFFERENT FAMILES. HOMELESS.
<P>
THE RED CROSS IS ON THE SCENE. AND WILL HELP THOSE PEOPLE FIND A PLACE TO STAY TONIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=136Eastwood b.s.-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Eastwood b.s.-INT</H3><BR>
WELL, FOR ONE THING, IT MEANS A BIG VICTORY FOR THE ENVIRONMENT, BECAUSE NOW, *NONE* OF THAT LAND CAN BE DEVELOPED.
<P>
*AND*, ACCORDING TO THE BIG SUR LAND TRUST, THE DONATION ALSO TRANSLATES TO GOOD NEWS FOR TOURISTS, DRIVERS. AND THE COUNTY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Eastwood b.s.-GUTS>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Eastwood b.s.-GUTS</H3><BR>
THE ARTICHOKE FIELDS SURROUNDING HIGHWAY ONE JUST SOUTH OF CARMEL HAVE BEEN AROUND FOR YEARS. IT AND THE BORDERING LAND WILD AND UNTOUCHED BY DEVELOPERS.
<P>
TODAY, IT WAS PRETTY MUCH GUARANTEED THAT IT WILL STAY THAT WAY. THANKS TO A SIX-MILLION DOLLAR DONATION BY CLINT AND MAGGIE EASTWOOD.
<P>
THE ACTOR AND HIS EX-WIFE, WHO REMAIN BUSINESS PARTNERS. TODAY DONATED MORE THAN 130 ACRES OF THEIR PROPERTY EAST OF HIGHWAY ONE, TO BE SPLIT WITH THE BIG SUR LAND TRUST, MONTEREY COUNTY, AND CAL AM.
<P>
THOUGH HE ATTENDED TODAY'S ANNOUNCEMENT PARTY IN CARMEL, CLINT EASTWOOD TRIED TO KEEP A LOW PROFILE. PREFERRING TO GIVE OTHERS THE LIMELIGHT.
<P>
PREVIOUSLY DESTINED TO BECOME A SUBDIVISION OF 82 HOMES, MUCH OF THE LAND WILL NOW PERMANENTLY REMAIN OPEN SPACE. 
<P>
THE MONTEREY COUNTY AND CAL AM PORTION WILL BE USED TO STUDY FLOOD CONTROL AND WATER USAGE ALONG THE CARMEL RIVER. AND THE REST WILL BE KEPT FOR AGRICULTURE.
<P>
=====BUTT =====
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134Eastwood b.s.-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Eastwood b.s.-TAG</H3><BR>
THE EASTWOODS ARE POTENTIALLY LOSING OUT ON A LOT OF MONEY BY CHOOSING NOT TO DEVELOP THAT LAND. BUT THEY SAY IT'S BEEN A LONG-TIME DREAM OF THEIRS TO DO WHAT THEY DID TODAY.
<P>
THEIR DONATION WILL ADD TO THE 15-THOUSAND ACRES OF OPEN SPACE THE BIG SUR LAND TRUST ALREADY HAS.
<P>
ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Toxic rain>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Toxic rain</H3><BR>
LOCAL RESIDENTS AND BUSINESS PEOPLE ARE STEAMED OVER SOME METALIC MATERIAL. THEY SAY SPEWED OUT OF THE SMOKE STACKS. AT THE P-G & E PLANT IN MOSS LANDING.
<P>
IT HAPPENED ON TUESDAY MORNING.
<P>
RESIDENTS SAY THE METALLIC FLAKES LANDED ON NEARBY CARS AND BOATS. MAKING A MESS. AND IN SOME CASES EATING RIGHT THROUGH THE PAINT.
<P>
*PG AND E*  OFFICIALS SAY THEY'RE BAFFLED AS TO WHAT CAUSED THE STUFF TO BLOW OUT.
<P>
THEY BELIEVE IT'S RUST. AND NOT ANYTHING TOXIC.
<P>
RESIDENTS SAY THEY WANT ANSWERS.
<P>
"WE WOKE UP.COMPLAINT FORMS."
<P>
P-G AND E OFFICIALS SAY THEY'VE ALREADY RECEIVED 50 OR 60 CLAIMS FROM PEOPLE WHO'VE BEEN AFFECTED. AND THEY WILL CONTINUE TO INVESTIGATE THE SOURCE OF THE MATERIAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127HWY 5 pile-up-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>HWY 5 pile-up-INT</H3><BR>
FIVE PEOPLE ARE DEAD. 26 OTHERS ARE HURT AFTER A HUGE PILE-UP ON INTERSTATE FIVE. SOUTH OF SACRAMENTO. THIS MORNING. 
<P>
NINE BIG-RIGS AND TWENTY-EIGHT CARS AND TRUCKS.  WERE INVOLVED IN THE TWISTED WRECKAGE.
<P>
THE PILE-UP STRETCHED FOR MORE THAN A QUARTER MILE. 
<P>
FOX'S MIKE EMANUEL HAS MORE ON WHAT CAUSED THE CHAIN-REACTION ACCIDENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125FEMA denies>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>FEMA denies</H3><BR>
THE FEDERAL EMERGENCY MANAGEMENT DISTRICT HAS CONCLUDED THAT A LOCAL TRANSIT SYSTEM WILL GET ONLY A TINY FRACTION OF THE EARTHQUAKE DAMAGE MONEY IT WAS HOPING FOR.
<P>
THE SANTA CRUZ METROPOLITAN TRANSIT DISTRICT WANTS 16 MILLION DOLLARS FROM FEMA.	BUT THE FEDERAL DISASTER AGENCY SAYS IT WILL ONLY PAY 4-THOUSAND DOLLARS.
<P>
FOLLOWING THE 1989 LOMA PRIETA EARTHQUAKE. METRO ESTIMATED ITS SYSTEM HAD SUSTAINED 19-MILLION DOLLARS
<P>
WORTH OF DAMAGE.
<P>
BUT METRO LATER WITHDREW A FRAUDULANT THREE-MILLION DOLLAR CLAIM FOR A DIESEL FUEL TANK THAT WAS DAMAGED BEFORE THE QUAKE.  A CONTROVERSIAL ISSUE THAT METRO WAS HOPING TO OVERCOME.
<P>
"WE'VE MADE MISTAKES, THERE'S NO QUESTION ABOUT THAT, BUT FEMA'S
<P>
SUPPOSED TO PROVIDE PEOPLE WITH RELIEF FROM EMERGENCIES AND 
<P>
DISASTERS, AND WE CERTAINLY HAD ONE HERE IN 1989, AND WE'RE OUT
<P>
THE 16-MILLION BUCKS, AND WE'RE LOOKING FOR A LITTLE MORE COOPERATION THAN WE'VE GOTTEN."
<P>
	ROTKIN SAYS BECAUSE THE BOARD CAME FORWARD, ADMITTED THE FRAUD, AND PAID A ONE-POINT-FIVE MILLION DOLLAR FINE, FEMA AGREED NOT TO BE BIASED IN DECIDING WHETHER TO GRANT THE REMAINING 16-MILLION DOLLAR CLAIM.
<P>
	THE BOARD WILL NOW PLAN ITS APPEAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Singleton mistrial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Singleton mistrial</H3><BR>
A FLORIDA JUDGE DECLARES A MISTRIAL IN A MURDER CASE INVOLVING LAWRENCE SINGLETON.
<P>
HE'S THE MAN WHO 19-YEAR-AGO. RAPED THEN CHOPPED OFF THE ARMS OF A TEENAGE HITCH-HIKER HERE IN CALIFORNIA.
<P>
IN FLORIDA. SINGLETON IS CHARGED WITH KILLING A PROSTITUTE.
<P>
A MISTRIAL WAS DECLARED BECAUSE A POTENTIAL JUROR WAS SHOWN ON T-V.
<P>
THE JUDGE NOW HAS 90 DAYS TO START SELECTING A NEW JURY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Salinas peppers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas peppers</H3><BR>
THE SALINAS PEPPERS MAY SOON BE ON THEIR WAY TO REDDING.
<P>
LAST MONTH THE TEAM LEARNED THAT A POSSIBLE MOVE WAS IN THE WORKS.
<P>
APPARENTLY THE TEAM JUST ISN'T MAKING ENOUGH MONEY HERE IN SALINAS. AND IS IN SEARCH OF A MORE LUCRATIVE MARKET.
<P>
PLAYERS WERE TOLD THOSE GREENER FIELDS MAY BE IN REDDING.
<P>
LEAGUE OFFICIALS MET TODAY. BUT HAVE YET TO STRIKE A DEAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A HOSTAGE DRAMA. NOW THREE-DAYS-OLD. CONTINUES TO FRUSTRATE POLICE IN ORLANDO, FLORIDA TONIGHT.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(orlando hostage)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(orlando hostage)</H3><BR>
SUSPECTED KILLER JOHN ARMSTRONG HAS BEEN HOLDING TWO YOUNG CHILDREN HOSTAGE SINCE TUESDAY.
<P>
TONIGHT. A POLICE NEGOTIATOR IS EXPRESSING DISAPPOINTMENT THAT THE STANDOFF HASN'T ENDED. DESPITE THE SUSPECTS REPEATED PROMISES TO LET THE CHILDREN GO.
<P>
POLICE SAY ARMSTRONG IS BONDING WITH THE CHILDREN WHICH MAKES IT LESS LIKELY HE WILL HARM THEM.
<P>
IN THE MEAN TIME. THE AROUND-THE-CLOCK NEGOTIATIONS CONTINUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(murder/torture)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(murder/torture)</H3><BR>
A WOMAN HAS TOLD POLICE SHE HELPED HER BOYFRIEND. ABDUCT, TORTURE AND KILL A 22-YEAR-OLD  PLEASANTON WOMAN.
<P>
39-YEAR-OLD MICHELLE MICHAUD SAYS SHE. AND 37-YEAR-OLD JAMES DEVAGGIO. FORCED THE WOMAN INTO THEIR VAN. REPEATEDLY RAPED AND THEN STRANGLED HER.
<P>
THE WOMAN'S BODY WAS FOUND NEAR LAKE TAHOE A WEEK AGO. 
<P>
THE PAIR IS ALSO ACCUSED OF A SIMILAR ABDUCTION IN RENO IN SEPTEMBER. AND SUSPECTED OF MOLESTING TWO GIRLS IN SACRAMENTO.
<P>
DEVAGGIO IS A REGISTERED SEX OFFENDER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(amtrak accident)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(amtrak accident)</H3><BR>
ONE MAN IS DEAD. ANOTHER HURT. WHEN A CAR TRIES TO OUTRUN AN AMTRAK TRAIN. IN JACKSONVILLE, FLORIDA.
<P>
POLICE SAY THE DRIVER OF THE RED PONTIAC WENT AROUND A CROSSING GATE. AND TRIED TO CROSS IN FRONT OF THE ON-COMING TRAIN.
<P>
THE AMTRAK SLAMMED INTO THE CAR. KILLING THE PASSENGER. AND INJURING THE DRIVER. 
<P>
NO ONE ABOARD THE TRAIN WAS HURT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139(arlington body mov)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(arlington body mov)</H3><BR>
THE WIDOW OF FORMER U-S AMBASSADOR TO SWITZERLAND LARRY LAWRENCE. HAS REMOVED HER HUSBAND'S BODY. FROM ARLINGTON NATIONAL CEMETERY.
<P>
THE BODY WAS MOVED TO A SAN DIEGO CEMETERY AFTER  PRESSURE FROM AMERICAN VETERANS. AND THE HOUSE VETERANS OVERSIGHT COMMITTEE.
<P>
LAWRENCE CLAIMED HE HAD SERVED IN THE MERCHANT MARINE. BUT A RECENT INVESTIGATION FOUND NO MILITARY RECORD OF HIS SERVICE.
<P>
LAWRENCE RAISED NEARLY 10-MILLION DOLLARS FOR THE DEMOCRATIC NATIONAL COMMITTEE DURING THE 19-90'S. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132(hillary kicked out)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(hillary kicked out)</H3><BR>
IN NEW YORK. A CONTROVERSY IS BREWING OVER WHETHER THE FIRST LADY WAS KICKED OUT OF AN EXCLUSIVE CLUB.
<P>
WHITE HOUSE OFFICIALS SAY HILLARY RODHAM CLINTON WAS HAVING A CONVERSATION WITH COLUMNIST CINDY ADAMS AT THE UNIVERSITY CLUB.  WHEN ADAMS PULLED OUT A CELL PHONE TO MAKE A CALL.
<P>
THE WOMEN WERE ASKED TO LEAVE. BECAUSE CELL PHONES ARE APPARENTLY AGAINST CLUB RULES.
<P>
THE WHITE HOUSE SAYS THE FIRST LADY WAS ON HER WAY OUT ANYWAY. SO IT WAS NO BIG DEAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Cisneros indict-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cisneros indict-INT</H3><BR>
A MEMBER OF PRESIDENT CLINTON'S FIRST CABINET IS IN HOT WATER TONIGHT. 
<P>
HENRY CISNEROS.THE FORMER HOUSING AND URBAN DEVELOPMENT SECRETARY. HAS BEEN INDICTED BY A FEDERAL GRAND JURY. ON A SERIES OF CHARGES. INCLUDING LYING TO THE F-B-I. 
<P>
FOX'S DAVID SHUSTER REPORTS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/microsoft>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/microsoft</H3><BR>
A FEDERAL JUDGE HAS RULED AGAINST MICROSOFT. ORDERING THE COMPUTER COMPANY TO CHANGE THE WAY THEY DO BUSINESS.
<P>
WE'LL DOWNLOAD THE FACTS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
U-S DISTRICT COURT JUDGE THOMAS JACKSON ORDERED MICROSOFT. TO STOP REQUIRING COMPUTER MAKERS TO PRE-INSTALL AND DISTRIBUTE IT'S INTERNET BROWSER PROGRAM.
<P>
HOWEVER. THE JUDGE REJECTED THE JUSTICE DEPARTMENT'S REQUEST THAT MICROSOFT BE PUNISHED TO THE TUNE OF A MILLION DOLARS A DAY IN FINES.
<P>
FINAL RULING ON THE LEGAL ISSUES RAISED IN THE CASE. WILL BE MADE LATER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4049ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
IN HIS 11-YEARS WITH THE 49ERS, BRENT JONES PLAYED ON 3-SUPER BOWL CHAMPIONSHIP TEAMS, AND IN 4-PRO BOWLS.
<P>
BUT WITH HIS 35TH BIRTHDAY JUST 2-MONTHS AWAY, JONES DECIDED HE WANTED TO HANG 'EM UP WHILE HE STILL HAD SOMETHING LEFT IN THE TANK.
<P>
JONES, WHO HAS BEEN A MAINSTAY OF THE NINERS OFFENSE FOR YEARS, WILL RETIRE AFTER THIS SEASON.
<P>
BRENT, A SANTA CLARA GRAD, LEAVES AS THE TOP RECEIVING TIGHT END IN THE TEAM'S HISTORY, WITH 412 CATCHES, FOR OVER 5-THOUSAND YARDS, AND 33-TOUCHDOWNS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
OPENING DAY MAY STILL BE 4-MONTHS AWAY, BUT THIS IS A SPECIAL DAY FOR ALL GIANTS FANS.
<P>
GROUNDBREAKING FOR THE NEW 262-MILLION DOLLAR PACIFIC BELL PARK TAKES PLACE TODAY. THE GIANTS SHOULD BE PLAYING IN THEIR NEW HOME IN APRIL OF THEIR YEAR 2000.
<P>
ABOUT 6-THOUSAND FANS, ALONG WITH CITY AND GIANT DIGNITARIES ARE ON HAND.
<P>
THE 42-THOUSAND SEAT STADIUM WILL BE LOCATED ON A 13-ACRE SITE IN THE CHINA BASIN AREA OF THE CITY. THE ADRESS WILL BE 1 WILLIE MAYES PLAZA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
AMIDST MORE CONTROVERSEY THAN ANY FRANCHISE DESERVES, THE GOLDEN STATE WARRIORS PULLED OFF A TREMENDOUS UPSET LAST NIGHT OVER THE L.A. LAKERS. TRUE, THE LAKERS ARE WITHOUT SHAQ, BUT THE WIN WAS IMPRESSIVE NONE THE LESS.
<P>
ZANE TABARI WAS AT THE GAME LAST NIGHT, AND HAS OUR REPORT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50christmas adobes>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>christmas adobes</H3><BR>
THEY HAVE "DECKED THE HALLS" OF THE HISTORIC ADOBES IN MONTEREY.
<P>
IT'S ALL FOR THE ANNUAL "CHRISTMAS IN THE ADOBES TOUR."
<P>
THE SELF GUIDED TOUR WILL BE HELD SATURDAY NIGHT FROM FIVE TO NINE.
<P>
IT'LL FEATURE ENTERTAINMENT BY MUSICIANS AND CHARACTERS DRESSED UP IN PERIOD COSTUMES.
<P>
AND ALL THE ADOBES IN THE TOUR ARE  WITHIN WALKING DISTANCE OF ONE ANOTHER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129fruitcake smash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>fruitcake smash</H3><BR>
IT MUST HAVE BEEN  "HEAVEN" FOR  FRUITCAKE HATERS TODAY IN DETROIT.
<P>
A STEAMROLLER SQUASHED A THOUSAND MOCK FRUITCAKES LAUNCHING AN "UNOFFICIAL" CAMPAIGN TO BAN FRUITCAKES.
<P>
IT'S ALL PART OF SARA LEE'S PROMOTION OF THEIR WHITE RUSSIAN  BROWNIES.
<P>
AS PART OF SARA LEE'S RESEARCH THEY FOUND THAT A QUARTER OF THE PEOPLE SURVEYED ADMITTED THEY PASS THEIR UNWANTED FRUITCAKES TO SOMEONE ELSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<!--#include file="../footer.inc" --></TD></TR></TABLE>
</BODY>
</HTML>
