
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
<TITLE>KCBA FIRST AT TEN, Thursday, 12/4/97</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<TABLE WIDTH=100% BORDER=0>
<TR><TD CLASS="a"><TR><TD CLASS="a" ><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 12/4/97</H2></CENTER></TD>
</TABLE>

<TABLE WIDTH=100% BORDER=0 >
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145East Beach fire>East Beach fire</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146highway 17 closed>highway 17 closed</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(foster family dead)>(foster family dead)</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107SC hypo chase-INT>SC hypo chase-INT</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(church explodes)>(church explodes)</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108SC hypo chase-GUT>SC hypo chase-GUT</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(chopper crashes)>(chopper crashes)</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132SC hypo chase-TAG>SC hypo chase-TAG</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Smack my b--- up>Smack my b--- up</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Wells fargo 211>Wells fargo 211</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Canada postal strike>Canada postal strike</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131gilroy cat fire>gilroy cat fire</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/carrots>Fox Biz/carrots</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142acosta plaza fire folo>acosta plaza fire folo</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Warriors>Warriors</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130union city plane folo>union city plane folo</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4149ers>49ers</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#133sal beer denied>sal beer denied</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43H.S. Football Prvw.>H.S. Football Prvw.</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109wharf crane ax>wharf crane ax</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Sharks>Sharks</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Fish global warm-IN>Fish global warm-IN</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50bethlehem streets>bethlehem streets</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Acoustic nets>Acoustic nets</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#97bye bye>bye bye</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Pedal boat safe>Pedal boat safe</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141El nino coastal fx>El nino coastal fx</A></TD>
<TR><TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/IHELP homeless\>Good News/IHELP homeless\</A></TD>
<TD CLASS="a" ><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134sal power out>sal power out</A></TD>

</Table>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=145East Beach fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>East Beach fire</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
20 PEOPLE ARE HOMELESS TONIGHT. AFTER A FIRE RAGES THROUGH A ROOMING HOUSE IN WATSONVILLE.
<P>
THE FIRE STARTED AT ABOUT 7-THIRTY.  IN AN UPSTAIRS BEDROOM OF A HOUSE ON BEACH STREET.
<P>
FIVE DIFFERENT CREWS OF FIREFIGHTERS WERE ABLE TO QUICKLY GET THE BLAZE UNDER CONTROL. 
<P>
BUT NOT BEFORE IT CAUSED MAJOR DAMAGE TO THE UPSTAIRS BEDROOMS AND ATTIC.
<P>
INVESTIGATORS SAY THEY BELIEVE CLOTHES THAT WERE LEFT TOO CLOSE TO A HEATER. ARE WHAT SPARKED THE FIRE.
<P>
THE HOUSE IS NOW UN-LIVEABLE.
<P>
THE RED CROSS IS ON THE SCENE. AND WILL HELP THE VICTIMS FIND A PLACE TO STAY TONIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146highway 17 closed>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>highway 17 closed</H3><BR>
WHAT STARTED AS A SEMI-TRUCK ACCIDENT ON HIGHWAY 17 IN THE SANTA CRUZ MOUNTAINS. HAS TURNED INTO AN DANGEROUS FUEL SPILL. SHUTTING DOWN THE HIGHWAY TONIGHT.
<P>
TRAFFIC WAS SLOWED FOR HOURS AFTER THE ACCIDENT HAPPENED THIS AFTERNOON. THE DRIVER WAS AIRLIFTED TO STANFORD MEDICAL CENTER.
<P>
BUT LATER. WHILE CREWS WERE ATTEMPTING TO CLEAR THE WRECKED FUEL TANKER. THEY APPARENTLY SPRUNG A LEAK.
<P>
NOW MORE THAN ONE-HUNDRED GALLONS OF FUEL HAVE SPILLED ONTO THE ROADWAY. FORCING THE C-H-P AND CAL-TRANS TO SHUT-DOWN THE HIGHWAY. IN BOTH DIRECTIONS.
<P>
OFFICIALS SAY IT WILL BE ANOTHER THREE HOURS AT LEAST. BEFORE HIGHWAY 17 IS RE-OPENED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107SC hypo chase-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC hypo chase-INT</H3><BR>
A VERY SAD AND TWISTED TURN OF EVENTS, ALAN.
<P>
THAT TOW TRUCK DRIVER WAS STUCK WITH A HYPODERMIC NEEDLE *FILLED* WITH BLOOD AND DRUGS WHILE TOWING THAT CAR YESTERDAY.
<P>
THIS, AFTER BEING CALLED OUT BY A SANTA CRUZ COUNTY SHERIFF'S DEPUTY. WHO HAD A HARROWING EXPERIENCE OF HIS OWN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108SC hypo chase-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC hypo chase-GUT</H3><BR>
JUST BEFORE EIGHT YESTERDAY MORNING, A SHERIFF'S DEPUTY ROAMING THE OCEAN STREET EXTENSION AREA OF SANTA CRUZ DISCOVERED A WOMAN SITTING IN A "CAR THAT WAS SCATTERED WITH HYPODERMIC NEEDLES."
<P>
WHEN HE TRIED TO INVESTIGATE, THE SUSPECTED DRUG ABUSER ALLEGEDLY TRIED TO RUN HIM OVER, THEN ABANDONED HER CAR AND FLED.
<P>
THE BEWILDERED DEPUTY GAVE UP THE SEARCH, BUT CALLED A TOW TRUCK TO IMPOUND THE CAR.
<P>
AND THAT'S WHEN IT HAPPENED.
<P>
THE TOW TRUCK DRIVER DIDN'T NOTICE A HIDDEN NEEDLE NEAR THE PARKING BRAKE. AND NEITHER DID THE DEPUTY, WHO HAD ALREADY CLEARED OUT FIVE SYRINGES FROM THE CAR.
<P>
THE SYRINGE WAS FILLED WITH BLOOD AND WHAT APPEARED TO BE COCAINE.
<P>
THE DRIVER WAS IMMEDIATELY TREATED AT DOMINICAN HOSPITAL. BUT LIKELY WON'T KNOW UNTIL NEXT WEEK WHETHER THE BLOOD CONTAINED ANY DISEASE.
<P>
IN THE MEANTIME, HIS CO-WORKERS SAY, HE'S DISTRAUGHT.
<P>
THE SHERIFF'S DEPARTMENT MANAGED TO CATCH THEIR SUSPECT AND HAVE CHARGED CLAIRE DEVELKIS WITH A SERIES OF OFFENSES.
<P>
MEANWHILE, THE TOW TRUCK DRIVER IS CONSIDERING WHETHER TO CHARGE THE *SHERIFF'S DEPARTMENT* WITH NEGLIGENCE, IN A LAWSUIT.
<P>
BUT A SHERIFF'S SPOKESPERSON SAYS. ONLY THE SUSPECTED DRUG ABUSER IS TO BLAME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132SC hypo chase-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC hypo chase-TAG</H3><BR>
THE DRIVER IS ON LEAVE FROM HIS JOB FOR NOW, PHYSICALLY AND EMOTIONALLY DISTRESSED.
<P>
HIS FRIENDS AT ROSSI'S TOWING HAVE THEIR FINGERS CROSSED, HOPING HE WON'T HAVE TO HEAR ANY BAD NEWS.
<P>
ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Wells fargo 211>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Wells fargo 211</H3><BR>
POLICE ARE ON THE LOOK-OUT TONIGHT FOR A MAN WHO ROBBED THE WELLS FARGO BANK. ON SOUTH MAIN IN SALINAS. THIS AFTERNOON.
<P>
POLICE SAY THE MAN WALKED INTO THE BANK AT ABOUT 5:30. HANDED A TELLER A NOTE DEMANDING MONEY. AND TOOK OFF ON FOOT WITH CASH.
<P>
THE ROBBER IS DESCRIBED AS A BLACK MALE. ABOUT THIRTY YEARS OLD. AND ABOUT SIX FEET TALL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131gilroy cat fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>gilroy cat fire</H3><BR>
A CAT IN GILROY IS TONIGHT BEING CREDITED WITH SAVING ITS OWNERS LIFE.
<P>
HELEN LETTERMAN WAS FAST ASLEEP LAST NIGHT. WHEN HER CLOTHES DRYER SPARKED A FIRE.
<P>
THERE WERE NO SMOKE ALARMS IN THE HOUSE. AND HELEN DIDN'T WAKE UP UNTIL ONE OF HER CATS JUMPED ON HER FACE.
<P>
SHE GRABBED HER FELINE HERO. AND BOTH SCRAMBLED TO SAFETY.
<P>
THE FIRE WAS CONTAINED IN THE LAUNDRY ROOM. BUT SEVERAL OTHER CATS WERE KILLED IN THE FIRE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142acosta plaza fire folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>acosta plaza fire folo</H3><BR>
THE SALINAS WOMAN THAT WAS CRITICALLY HURT IN YESTERDAY'S FIRE AT ACOSTA PLAZA. HAS DIED.
<P>
FAMILY MEMBERS SAY THE 59-YEAR-OLD WOMAN  WAS NOT ABLE TO RECOVER. FROM A CARDIAC ARREST SHE SUFFERED DURING THE FIRE.
<P>
AFTER PULLING HER FROM THE BURNING APARTMENT. FIRE FIGHTERS WORKED FOR 15 MINUTES TO RESUSCITATE THE WOMAN.
<P>
STILL NO WORD ON WHAT CAUSED THE BLAZE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130union city plane folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>union city plane folo</H3><BR>
A PILOT WHO CRASH-LANDED HIS SMALL PLANE IN THE BAY AREA. AFTER TAKING OFF FROM SALINAS. APPARENTLY KNEW HE WAS LEAKING FUEL.
<P>
AN AIRCRAFT PAINTER WHO WORKED ON THE PLANE IN SALINAS. SAYS HE TOLD THE PILOT ABOUT THE LEAK BEFORE HE TOOK OFF FOR HAYWARD.
<P>
27-YEAR-OLD DONALD ANTHROP CRASH-LANDED THE PLANE IN A UNION CITY NEIGHBORHOOD A SHORT TIME LATER. AFTER HE SAYS HE SUDDENLY LOST POWER.
<P>
STILL NO WORD ON WHETHER THE LEAK CONTRIBUTED TO THE CRASH LANDING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=133sal beer denied>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>sal beer denied</H3><BR>
ANOTHER ALCOHOL OUTLET IN EAST SALINAS HAS BEEN REJECTED.
<P>
THE CITY PLANNING COMMISSION UNAMINOUSLY  DENIED A BEER AND WINE PERMIT TO THE OWNER OF MO'S EXXON.
<P>
COMMISSION MEMBERS SAID IT WAS AN EASY VOTE.CITING HIGH CRIME RATES IN THE AREA.
<P>
ON TUESDAY. THE SALINAS CITY COUNCIL DENIED A DEVELOPER'S REQUEST TO BUILD A SUPERMARKET IN EAST SALINAS. BECAUSE THE MARKET WOULD BE SELLING LIQUOR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109wharf crane ax>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>wharf crane ax</H3><BR>
A CONSTRUCTION ACCIDENT ON THE  MONTEREY WHARF LEAVES  ONE MAN SERIOUSLY HURT.
<P>
FIRE OFFICIALS SAY PAUL STOKES HAD BEEN USING THIS CRANE TO LOWER PILINGS UNDER THE WATER.WHEN THE CRANE TIPPED OVER.
<P>
STOKES FELL OUT OF THE CRANE ONTO A PLATFORM IN THE WATER.
<P>
HE WAS RUSHED TO THE HOSPITAL WITH BRUISES TO HIS HEART, LUNG AND RIBS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Fish global warm-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fish global warm-IN</H3><BR>
SCIENTISTS AT THE INTERNATIONAL GLOBAL WARMING CONFERENCE IN KYOTO, JAPAN. SAY GLOBAL WARMING COULD  DISRUPT THE EARTH'S CLIMATE AND THREATEN SOME SPECIES.
<P>
DON KNAPP TALKS TO ONE LOCAL EXPERT ABOUT HOW FISH IN THE PACIFIC OCEAN COULD BE EFFECTED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Acoustic nets>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Acoustic nets</H3><BR>
A SMALL SOLUTION TO A BIG PROBLEM HAS FISHERMEN AND ENVIRONMENTALISTS SOUDING A VICTORY BELL.
<P>
A SMALL ORANGE ACOUSTIC DEVICE. CALLED THE "PINGER" MAY BRING AN END TO THE UNINTENTIONAL DEATHS OF SEA MAMMELS CAUGHT IN FISHING NETS.
<P>
THE PINGER IS ATTACHED TO THE NETS. THEN SENDS OFF A PINGING SOUND.  THAT SCARES AWAY WHALES, AND OTHER MARINE MAMMALS.
<P>
FOLLOWING A ONE YEAR TEST BY FISHERMEN. THE REMARKABLE DEVISE APPEARS TO BE WORKING.
<P>
BEGINNING THIS MONTH. THE "PINGER" WILL BE REQUIRED BY THE NATIONAL MARINE FISHERIES SERVICE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Pedal boat safe>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pedal boat safe</H3><BR>
AN ABORTED PEDDLE BOAT TRIP TO HAWAII ENDS THIS MORNING. 11 DAYS AFTER LEAVING MONTEREY.
<P>
THE PEDDLE DRIVEN CRAFT ARRIVED IN MORRO BAY AT ABOUT SIX THIS MORNING.
<P>
THE TWO MEN WERE LESS THAN A HUNDRED MILES OUT WHEN THEY DECIDED TO TURN BACK.
<P>
HEAVY SEAS, AND HIGH WINDS CAUSED SUBSTANTIAL DAMAGE TO THE BOAT'S GENERATOR AND COMPUTER SYSTEMS.
<P>
THE GROUP "PEDDLE FOR THE PLANET" PLANS TO TRY AGAIN IN THE SPRING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/IHELP homeless\>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/IHELP homeless\</H3><BR>
GOOD NEWS FOR A LOCAL GROUP THAT HELPS HOMELESS MEN.
<P>
PENINSULA OUTREACH IS GIVEN 10-THOUSAND DOLLARS TOWARD ITS HOMELESS EMERGENCY LODGING PROGRAM KNOWN AS I-HELP.
<P>
PROGRAM VOLUNTEERS PROVIDE SHELTER AND MEALS TO HOMELESS MEN IN THE SALINAS AND MONTEREY AREA.
<P>
THE 10-THOUSAND DOLLAR GRANT WAS A JOINT CONTRIBUTION OF THE GROVER HERMANN FOUNDATION FUND. THE ANDREW AND MARJORIE ORRICK FUND. AND THE JAMES AND MARJORIE STURGEON FUND OF THE COMMUNITY FOUNDATION FOR MONTEREY COUNTY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A COUPLE AND TWO OF THEIR CHILDREN ARE DEAD. AFTER AN INTRUDER BREAKS INTO THEIR HOME. SHOOTS THEM TO DEATH. THEN KIDNAPS THREE OTHER CHILDREN. 
<P>
THAT STORY FROM SANTA CLAUS, GEORGIA TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(foster family dead)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(foster family dead)</H3><BR>
A FARMER FOUND THE CHILDREN UNHARMED. ABOUT FORTY MILES DOWN THE ROAD. 
<P>
TWO MORE FOSTER CHILDREN WERE FOUND ALIVE IN THE HOUSE. 
<P>
FRIENDS SAY THE MOTHER AND FATHER HAD BEEN FOSTER PARENTS SINCE 19-95. AND HAVE CARED FOR UP TO SIXTEEN CHILDREN. 
<P>
POLICE HAVE A SUSPECT IN CUSTODY. HE'S NOT BELIEVED TO BE RELATED TO ANY OF THE CHILDREN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(church explodes)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(church explodes)</H3><BR>
AN ENORMOUS FIRE HAS DESTROYED A COMMUNITY CHURCH IN NEWARK, NEW JERSEY.
<P>
FIRE FIGHTERS SAY AN EXPLOSION IN THE BOWLING ALLEY UNDERNEATH THE CHURCH. STARTED THE FIRE.
<P>
THE INSIDE OF THE CHURCH SUFFERED MAJOR SMOKE AND WATER DAMAGE.
<P>
THE SCHOOL NEXT DOOR ALSO SUFFERED THE WRATH OF THE FLAMES.  
<P>
IT HAS BEEN CLOSED. DISPLACING MORE THAN 3-HUNDRED STUDENTS.
<P>
STILL NO WORD ON WHAT SPARKED THE EXPLOSION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(chopper crashes)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(chopper crashes)</H3><BR>
TWO CREWMEN ARE DEAD AFTER THEIR U-S ARMY HELICOPTER CRASHES AND BURNS DURING A TRAINING FLIGHT. 
<P>
THE CHOPPER. HAD TAKEN OFF FROM THE FORT HOOD ARMY BASE NEAR WACO, TEXAS.  
<P>
AND WAS APPARENTLY FLYING IN FORMATION WITH FIVE OTHER HELICOPTERS. WHEN THE ACCIDENT HAPPENED.  
<P>
BASE OFFICIALS SAY THE ACCIDENT WAS NOT CAUSED BY A COLLISION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Smack my b--- up>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Smack my b--- up</H3><BR>
A CONTROVERSIAL NEW SONG BY THE POP GROUP "PRODIGY". IS DRAWING FIRE FROM WOMAN'S GROUPS WHO SAY THE SONG PROMOTES VIOLENCE AGAINST WOMEN.
<P>
---SONG---
<P>
THE L-A CHAPTER OF "NOW" SAYS THE SONG SENDS A DANGEROUS MESSAGE TO KIDS.
<P>
PRODIGY SAYS THE WORDS ENCOURAGE THE LISTENER TO DO ANYTHNG INTENSELY.
<P>
THE C-D WAS RELEASED BY TIME-WARNER AND MADONNA'S MAVERICK LABEL.
<P>
MADONNA'S SPOKESPERSON SAYS "SHE IS FIRMLY COMMITTED TO ARTISTIC FREEDOM AND WOULD NEVER RESTRICT ANY ARTIST ON HER LABEL FROM SAYING WHAT THEY WANT TO SAY. WHETHER SHE LIKED IT OR NOT."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Canada postal strike>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Canada postal strike</H3><BR>
JUST IN TIME FOR CHRISTMAS. YOU CAN SEND CARDS AND LETTERS TO YOUR FRIENDS AND FAMILY IN CANADA ONCE AGAIN.
<P>
A TWO-WEEK OLD POSTAL STRIKE WAS ENDED TODAY BY ORDER OF PARLIAMENT.
<P>
WORKERS WHO DEFIED THE ORDER. FACED FINES OF UP TO 7-HUNDRED DOLLARS PER DAY.
<P>
THE CANADIAN POSTAL WORKER'S UNION SAYS WORKERS MAY STILL RETALLIATE AGAINST THE ORDER. BY MISDIRECTING GOVERNMENT AND CORPORATE MAIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/carrots>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/carrots</H3><BR>
A MINI-VEGETABLE IS BRINGING IN MEGA-BUCKS FOR LOCAL GROWERS. DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
ACCORDING TO A GOVERNMENT REPORT. MINI-CARROTS ARE A MIGHTY COMMODITY. 
<P>
THE NEW REPORT SAYS U-S CARROT CONSUMPTION HAS DOUBLED IN THE LAST TEN YEARS. MAINLY BECAUSE OF THE SO-CALLED BABY CARROTS.  
<P>
CALIFORNIA PRODUCES NEARLY 70 PERCENT OF THE NATION'S CARROT SUPPLY. MOST OF WHICH COMES FROM THE SAN JOAQUIN VALLEY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
ITS HARD TO IMAGINE, BUT TODAY, THINGS GO FROM BAD TO WORSE FOR LATRELL SPREWELL.
<P>
FOLLOWING LAST NIGHT'S GAME, A LOSS, THE WARRIORS ANNOUNCED THEY WERE TERMINATING THE REMAINING 3-YEARS OF SPREWELL'S CONTRACT FOR VIOLATION OF THE GOOD CONDUCT CLAUSE. THE UNPRESEDENTED MOVE WILL COST SPREWELL ABOUT 24-MILLION DOLLARS.
<P>
THIS MORNING, THE NBA LEVIES ONE OF THE HARSHEST SENTENCES EVER IN PROFESSIONAL SPORTS.
<P>
COMMISSIONER DAVID STERN, IN A STATEMENT RELEASED TODAY, HAS SUSPENDED SPREWELL FOR A FULL YEAR, WITHOUT PAY. FOR WHAT HE CALLS, THE PREMEDITATED ASSUALT ON WARRIORS COACH P.J. CARLESIMO.
<P>
SPREWELL, WHO REPORTEDLY HUNG-UP ON THE NBA OFFICIAL INVESTIGATING THE INCIDENT, IS NOT ELIGIBLE TO RETURN TO THE NBA UNTIL DECEMBER 3RD, 1998.
<P>
THE SHOE COMPANY CONVERSE ALSO DROPPED SPREWELL TODAY AS AN ENDORSER.
<P>
THE 3-TIME ALL-STAR IS SAID TO BE CONSIDERING PLAYING OVERSEES.
<P>
FOR THE WARRIORS, WHO HAVE RECEIVED OVERWHELMING PUBLIC SUPPORT FOR THEIR DECISION, SAID IT WAS THE "RIGHT" THING TO DO.
<P>
THE PLAYERS UNION HAS SAID IT WILL FILE GRIEVANCE ON SPREWELL'S BEHALF AGAINST THE WARRIORS AND THE LEAGUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4149ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
NOW LOST IN THE MIDST OF THE SPREWELL AND THE DEBARTALO CONTROVERSY'S, IS THE INCREDIBLE COMEBACK OF JERRY RICE.
<P>
RICE SUFFERED THE KIND OF KNEE INJURY THAT ENDS PLAYERS SEASONS, AND SOMETIMES THEIR CAREERS. BUT JERRY IS BACK ON THE PRACTICE FIELD AFTER ALL OF 3-MONTHS.
<P>
THE LEAGUE'S ALL-TIME TOUCHDOWN LEADER, IS STILL HOPING TO CONVINCE DOCTORS AND COACHES THAT'S HE'LL BE READY TO PLAY, MONDAY NIGHT, DECEMBER 15TH, VS. DENVER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43H.S. Football Prvw.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>H.S. Football Prvw.</H3><BR>
WE CONTINUE OUR COUNTDOWN TO THIS SATURDAY'S PREP FOOTBALL C.C.S. DIVISION IV CHAMPIONSHIP GAME BETWEEN THE SAN LORENZO VALLEY COUGARS, AND THE PALMA CHIEFTAINS.
<P>
THE GAME KICKS-OFF AT 2:00, AT GILROY HIGH SCHOOL.
<P>
LAST NIGHT WE MET S.L.V., TONITE ZANE TABARI TAKES A CLOSER LOOK AT THE DOMINANT LOCAL FOOTBALL POWER, KNOWN AS PALMA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
FINALLY TO THE ICE, AND TONITE THE SHARKS VISIT THE VANCOUVER CANUCKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50bethlehem streets>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bethlehem streets</H3><BR>
THE STREETS OF BETHLEHEM HAVE COME TO LIFE RIGHT HERE ON THE CENTRAL COAST.
<P>
HEAVENLY HOST. SHEPHERDS KEEPING WATCH OVER THEIR FLOCK BY NIGHT. AND OF COURSE. JOSEPH AND MARY AND THE BABE LYING IN A MANGER.
<P>
IT'S A LIVING NATIVITY SCENE WITH HUNDREDS OF CAST MEMBERS. INCLUDING THE FOUR-LEGGED KIND.
<P>
IT'S BEING PUT ON BY THE FIRST BAPTIST CHURCH, SALINAS.
<P>
THE PASTOR EVEN GOT INTO COSTUME AND INTO THE CHRISTMAS SPIRIT.
<P>
WE'RE SO HONORED THAT WE CAN LIFT THIS UP.. NOTHING AGAINST EITHER OF THOSE TWO.
<P>
YOU CAN SEE THE STREETS OF BETHLEHEM YOURSELF THROUGH THIS WEEKEND BEGINNING AT SIX P-M.
<P>
IT'S AT THE FIRST BAPTIST CHURCH, SALINAS. ON THE CORNER OF BLANCO ROAD AND SAN VINCENTE AVENUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=97bye bye>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bye bye</H3><BR>
THAT'S GOING TO DO IT FOR FOX NEWS FIRST AT TEN.
<P>
TUNE IN AGAIN TOMORROW  NIGHT AT TEN.
<P>
UNTIL THEN, TAKE CARE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141El nino coastal fx>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>El nino coastal fx</H3><BR>
EL NINO IS ALSO EXPECTED TO EFFECT GLOBAL WEATHER PATTERNS. 
<P>
FORECASTERS HAVE BEEN PREDICTING HUGE AMOUNTS OF RAINFALL FOR CERTAIN PARTS OF THE WORLD.AND DROUGHT IN OTHER AREAS. 
<P>
NOW. THREE STUDIES CONFIRM THAT IN SOME COUNTRIES. THERE WILL ALSO BE SIGNIFICANT CHANGES IN CLIMATE. 
<P>
THE NATIONAL OCEANIC AND ATMOSPHERIC ADMINISTRATION. A FEDERAL AGENCY THAT FOCUSES ON PREDICTING CLIMATE AND PROTECTING THE 
<P>
ENVIRONMENT. HELD A NEWS CONFERENCE TODAY TO ILLUSTRATE WHAT COULD BE AN UNPARALLELED WEATHER OCCURANCE. 
<P>
"IF YOU'VE BEEN LOOKING AT THESE MAPS OVER THE YEARS. 
<P>
THIS IS A BIG DEPARTURE FOR US. THIS IS A FORECAST OF UNPRECEDENTED 
<P>
CONFIDENCE FOR US."
<P>
IN THE UNITED STATES. ABOVE AVERAGE RAINFALL IS EXPECTED OVER MOST OF CALIFORNIA. THE SOUTHWEST AND SOUTHEAST.
<P>
IN THE PAST. EL NINO HAS DISRUPTED LOCAL WEATHER PATTERNS.BUT THIS YEAR FORECASTERS EXPECT IT WILL LEAVE AN IMPRINT NOT ONLY ON LOCAL WEATHER AND MARINE LIFE.BUT ON CLIMATIC CONDITIONS AROUND THE GLOBE AS WELL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134sal power out>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>sal power out</H3><BR>
SOME RESIDENTS IN CENTRAL AND WEST SALINAS HAD TO DO WITHOUT POWER THIS MORNING.
<P>
A SPOKESPERSON FROM P.G. AND E SAYS ABOUT 24-HUNDRED CUSTOMERS LOST POWER AROUND 6:30 THIS MORNING.
<P>
SCOTT BLAKLEY TELLS KION THAT THAT THE PROBLEM WAS AN EQUIPTMENT FAILURE AT THE BORONDA SUBSTATION.BASCIALLY A FUSE BLEW.
<P>
WE'RE TOLD POWER WAS RESTORED TO EVERYONE ABOUT FOUR HOURS LATER. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF="../main.asp">Return to KCBA home page</A><BR>
<FONT SIZE=1>
<!--#include file="../footer.inc" -->
</BODY>
</HTML>
