<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 1/17/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 1/17/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#8Briana Memorial>Briana Memorial</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39College Board>College Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#7Roe v. Wade-I>Roe v. Wade-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Hartnell>Hartnell</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#9NOAA Plane>NOAA Plane</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Prep Board>Prep Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#10SC Fatal Folo>SC Fatal Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#11Styles/Frusetta>Styles/Frusetta</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42NBA Board>NBA Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Dylan Symposium>Dylan Symposium</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Clinton/Paula-I>Clinton/Paula-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44College Football>College Football</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#12Clinton/Paula-G>Clinton/Paula-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Saddam Speech>Saddam Speech</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Golf Board>Golf Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#19Bird Flu Update>Bird Flu Update</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#99Wrestling>Wrestling</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Soccer Violence>Soccer Violence</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Stealth Bomber>Stealth Bomber</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#20Miners Killed>Miners Killed</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#116Balloons>Balloons</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Sweden Ice>Sweden Ice</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106Penguins>Penguins</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#28WX/CURRENTS>WX/CURRENTS</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Superbowl Bets-I>Superbowl Bets-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38Stanford>Stanford</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=8Briana Memorial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Briana Memorial</H3><BR>
GOOD EVENING.  I'M CHERI GYURO. THANKS FOR JOINING US.
<P>
AN ^EMOTIONAL^ DAY FOR HUNDREDS OF ^PEOPLE^ IN SOQUEL.AS THEY SAID GOOD BYE TO ELEVEN YEAR-OLD ^BRIANA MARIE PEARCY.^ 
<P>
PEARCY DIED IN A TRAGIC SKI ACCIDENT EARLY THIS MONTH.
<P>
MORE THAN 5-HUNDRED RELATIVES. FRIENDS. AND SCHOOL MATES GOT TOGETHER AT NORTH MAIN STREET ELEMENTARY SCHOOL IN SOQUEL TO HONOR THE LIFE AND MEMORY OF THE YOUNG GIRL.
<P>
BRIANA WAS SKIING WITH HER FATHER AND FRIENDS JANUARY 8TH AT ALPINE MEADOWS SKI RESORT.
<P>
SHE WAS SKIING DOWN AN INTERMEDIATE SLOPE WHEN SHE COLLIDED WITH ANOTHER SKIIER.
<P>
SHE DIED OF HEAD INJURIES SUFFERED IN THE COLLISION.
<P>
A MEMORIAL FUND FOR BRIANNA HAS BEEN ESTABLISHED AT THE WELLS FARGO BANK IN CAPITOLA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=7Roe v. Wade-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Roe v. Wade-I</H3><BR>
JANUARY 22ND MARKS THE 25TH ANNIVERSARY OF THE SUPREME COURT DECISION LEGALIZING ABORTION.
<P>
THE CASE, ROE VERSUS WADE DEEPLY DIVIDED AMERICANS AND CONTINUES TO SPARK CONTROVERSY NOW. 
<P>
TODAY  IN SANTA CRUZ. HUNDREDS OF PEOPLE  LINED THE STREETS FOR AN EARLY REMINDER OF WHAT HAPPENED 25 YEARS AGO THURSDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=9NOAA Plane>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NOAA Plane</H3><BR>
A NEW SCIENTIFIC ^PLATFORM^ IS JOINING THE INVESTIGATION INTO THE WEATHER PHENOMENON KNOWN AS "EL NINO."
<P>
THE P-3 ORION WEATHER AIRCRAFT IS EQUIPPED WITH RADAR AND SPECIAL MONITORS.
<P>
IT WILL FLY INTO HEAVY RAIN STORMS OFF THE WEST COAST AND WILL BE MONITORING A SYSTEM OF BUOYS THAT WILL MEASURE OFFSHORE WATER CONDITIONS WHEN STORMS STRIKE THE COAST.
<P>
IN 20:24 "ONE OF THE LINKAGES TO EL NINO IS THE INFLUENCE OF THE ATMOSPHERE ON THE OCEAN AND VICE-VERSA.  TO HELP MEASURE THAT, WE HAVE THESE INSTRUMENTS, AXBTS, THAT DROP OUT OF THE AIRPLANE.  IT'S A SMALL BUOY THAT HAS A LITTLE WEIGHT AND A LINE THAT PLAYS OUT WHEN IT HITS THE WATER.  THE WEIGHT CARRIES THE LINE OUT. AND MEASURES TEMPERATURES DOWN TO MAYBE 2000 FEET BELOW THE OCEAN'S SURFACE." OUT 20:44
<P>
THE PROJECT IS HEADED UP BY THE NATIONAL OCEANIC AND ATMOSPHERIC ADMINISTRATION. WORKING WITH GOVERNEMNT AND UNIVERSITY RESEARCHERS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=10SC Fatal Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Fatal Folo</H3><BR>
TWO TEENAGE ^GIRLS^ KILLED IN AN ACCIDENT ON HIGHWAY 17 YESTERDAY HAVE BEEN ^INDENTIFIED.^
<P>
THE  SANTA CRUZ COUNTY CORONER'S OFFICE SAYS LINDA LOANG AND PAMELA LAU. BOTH OF MILPITAS. DIED INSTANTLY.
<P>
THE TWO 15-YEAR-OLDS WERE PASSENGERS IN A CAR DRIVEN BY AN UNIDENTIFIED 18-YEAR OLD.WHO IS STILL IN SERIOUS CONDITION.
<P>
APARENTLY, THAT DRIVER LOST CONTROL. VEERED INTO ON-COMING TRAFFIC. AND CRASHED INTO ANOTHER CAR.
<P>
A 58-YEAR-OLD MAN ^IN^ THE ^OTHER^ CAR IS IN CRITICAL CONDITION AT STANDFORD MEDICAL CENTER. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=11Styles/Frusetta>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Styles/Frusetta</H3><BR>
SOME NEWS ON THE ^LOCAL ^POLITICAL^ FRONT TONIGHT.
<P>
SALINAS MAYOR ALAN STYLES SAYS HE PLANS TO SEEK THE DEMOCRATIC NOMINATION FOR THE 28TH ASSEMBLY DISTRICT IN JUNE.
<P>
THE 51-YEAR OLD STYLES. WHO SERVED THREE TERMS AS MAYOR. IS HOPING TO UNSEAT REPUBLICAN PETER FRUSETTA.
<P>
THE 28TH DISTRICT COVERS PARTS OF MONTEREY. SAN BENITO. SANTA CLARA. AND SANTA CRUZ COUNTIES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=112Dylan Symposium>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dylan Symposium</H3><BR>
THE PUBLIC  CAN'T SEEM TO GET ENOUGH OF LEGENDARY SINGER BOB DYLAN.
<P>
THE COUNTRY'S ACADEMIC ELITE IS SHOWING INTEREST. 
<P>
STANFORD UNIVERSITY HOSTED AN ACADEMIC SYMPOSIUM ABOUT THE SINGER. AND MORE THAN FOUR HUNDRED PEOPLE CAME OUT FOR THE 
<P>
GRANDLY TITLED EVENT."BOB DYLAN 19-98 INTERNATIONAL CONFERENCE." 
<P>
THESE SCHOLARLY ADMIRERS PROBED DYLAN'S LYRICS. POLITICAL VIEWS. RELIGIOUS LEANINGS. AND MUSICAL ROOTS.  
<P>
WHILE THE SCHOLARS STUDIED. DYLAN WAS PREPARING FOR A SOLD-OUT 
<P>
CONCERT IN NEW YORK CITY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Clinton/Paula-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Paula-I</H3><BR>
THEY GATHERED IN A WASHINGTON ^CONFERENCE ROOM^. MET FOR SIX HOURS.THEN ^LEFT^ WITHOUT SAYING A ^WORD.^ 
<P>
THAT SUMS UP WHAT HAPPENED TODAY DURING PRESIDENT CLINTON'S DEPOSITION IN THE "PAULA JONES' SEXUAL HARASSMENT CASE." 
<P>
THE TWO WERE FACE TO FACE.AS LAWYERS QUESTIONED THE ^PRESIDENT^ UNDER OATH. 
<P>
FOX'S WENDELL GOLER REPORTS FROM WASHINGTON. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=12Clinton/Paula-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Paula-G</H3><BR>
/O.PAULA JONES WENT TO FACE THE PRESIDENT, ON A DAY HER ADVISER 
<P>
SAYS SHE FOUGHT FOUR YEARS FOR. 
<P>
.JONES FOUGHT HER WAY THROUGH A CRUSH OF PHOTOGRAPHERS UP TO THE 
<P>
OFFICE BUILDING WHERE  HER ATTORNEYS , FOR THE FIRST TIME IN US 
<P>
HISTORY. 
<P>
.QUESTIONED A SITTING PRESIDENT AS A DEFENDANT IN A TRIAL.  
<P>
.THE MEETING WAS HELD IN MR. CLINTON'S ATTORNEY'S OFFICE, TO AVOID 
<P>
HAVING A SPECTACLE AT THE WHITE HOUSE. 
<P>
. JONES' ADVISOR RAILED AT THE MEDIA COVERAGE. 
<P>
"THERE A COUPLE OF YOU THAT ARE REAL JERKS." 
<P>
V/O.BUT SHE BRUSHED ASIDE THE CONTROVERSY SURROUNDING JONES' 
<P>
ACCUSATIONS. 
<P>
"PAULA HASN'T REALLY CARED WHAT THE REST OF THE COUNTRY THINKS. PAULA 
<P>
HAS TO WORRY ABOUT WHAT 12 JURORS IN LITTLE ROCK, ARKANSAS ARE GOING 
<P>
TO THINK." 
<P>
V/O.THE PRESIDENT AND HIS ATTORNEY HAD AN EARLY MORNING MEETING AT 
<P>
THE WHITE HOUSE, AND THE TWO RODE TOGETHER THE FEW BLOCKS TO THE 
<P>
OFFICE. 
<P>
.ENTERING AN UNDERGROUND GARAGE. CAMERAS WERE NOT ALLOWED INSIDE 
<P>
THE BUILDING. MR. CLINTON'S AIDES WANTED NO PICTURES ON THIS PAGE OF 
<P>
HISTORY.  
<P>
.BUT HIS SPOKESMAN SAID THE PRESIDENT DIDN'T DREAD THE DAY. 
<P>
"I THINK HE'S JUST GOING TO DO IT." 
<P>
V/O.JONES SAYS SHE MET THEN GOVERNOR CLINTON, IN A ROOM OF THIS 
<P>
HOTEL IN LITTLE ROCK, IN 1991. THAT HE EXPOSED HIMSELF AND ASKED FOR 
<P>
SEX.  
<P>
.THE PRESIDENT SAID IN A JULY COURT FILING, AT NO TIME DID HE MAKE 
<P>
SEXUAL ADVANCES OR OTHERWISE ACT IMPROPERLY WITH JONES." 
<P>
.BUT THAT EVEN IF JONES' ARGUMENTS WERE TRUE.THEY WOULD 
<P>
CONSTITUTE JUST A SINGLE OVERTURE, ABANDONED AS SOON AS JONES STATED 
<P>
IT WAS UNWELCOME." 
<P>
.LEGAL EXPERTS PRESDICTED THE QUESTIONING WOULD BE INTENSE. 
<P>
04 10 IT'S GOING GET IN VERY VERY DETAILED, INTERESTING STUFF ABOUT 
<P>
WHAT ALLEGEDLY HAPPENED IN THAT HOTEL ROOM DOWN IN AR WHEN HE WAS 
<P>
GOVERNOR. 
<P>
"THE QUESTIONING WENT ON FOR SIX HOURS. IT WAS RECORDED ON VIDEOTAPE 
<P>
AND WILL LIKELY SERVE AS THE PRESIDENT'S TESTIMONY AT A TRIAL THE 
<P>
SUPREME COURT SAYS HE DOESN'T HAVE TO ATTEND, BUT CAN'T PUT OFF UNTIL 
<P>
AFTER HE LEAVES OFFICE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Saddam Speech>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Saddam Speech</H3><BR>
MORE TOUGH TALK COMING FROM ^SADDAM HUSSEIN^ TODAY. 
<P>
APPEARING ON IRAQI T-V. SADDAM  WARNED. IF THE U-N DOESN'T LIFT ALL SANCTIONS IMPOSED AFTER THE WAR.  IRAQ WILL END ALL COOPERATIVE EFFORTS WITH THE UNITED NATIONS.
<P>
THE IRAQI LEADER'S ANNOUNCMENT COMES ON THE GULF WAR'S SEVENTH ANNIVERSARY. 
<P>
TO MARK THE OCCASION. SOME DEMONSTRATORS BURNED THE AMERICAN FLAG IN THE STREETS OF BAGHDAD. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=19Bird Flu Update>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bird Flu Update</H3><BR>
A LEADING EXPERT ON ^INFLUENZA^ SAYS THE "KILLER BIRD FLU" MAY HAVE COME FROM ^HONG KONG^.NOT MAINLAND CHINA.
<P>
WORLD HEALTH ORGANIZATION OFFICIALS SAY THE VIRUS IS TRANSMITTED BY DIRECT CONTACT WITH CHICKENS. 
<P>
SIX PEOPLE IN HONG KONG HAVE DIED FROM THE FLU SINCE MAY. 
<P>
MANY COUNTRIES IN ASIA. AFRICA. THE MIDDLE EAST.  AND EUROPE BANNED ^CHICKEN IMPORTS^ FROM CHINA. 
<P>
1.4 MILLION BIRDS HAVE BEEN SLAUGHTERED IN HONG KONG.   
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Soccer Violence>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Soccer Violence</H3><BR>
MORE THAN 100 ^PEOPLE^ ARE INJURED AT A SOCCER GAME IN SOUTHERN ^POLAND^ TODAY. 
<P>
FIGHTING BROKE OUT AFTER A DISPUTED PLAY BY TWO RIVAL TEAMS. 
<P>
THE ONE-HOUR  BRAWL WAS SO VICIOUS THAT THE TOWN'S SOCCER STADIUM WAS DESTROYED. 
<P>
FIFTY PEOPLE WERE TAKEN TO THE HOSPITAL. SEVERAL WITH SERIOUS HEAD INJURIES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=20Miners Killed>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Miners Killed</H3><BR>
AT LEAST 29 COAL MINERS ARE DEAD AND 19 INJURED AFTER AN EXPLOSION IN YUGOSLAVIA.
<P>
AUTHORITIES SAY THE BLAST WAS CAUSED BY A BUILD-UP OF METHANE GAS.
<P>
28 MINERS DID MANAGE TO ESCAPE UNHURT. 
<P>
THE SERBIAN GOVERNMENT DECLARED A DAY OF MOURNING TODAY.
<P>
IT IS THE FIRST MINING ACCIDENT IN THE COUNTRY SINCE 19-75. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Sweden Ice>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sweden Ice</H3><BR>
STOCKHOLM, SWEDEN HAS BEEN NAMED THE EUROPEAN CULTURAL CAPITAL. 
<P>
THE  CITY HAS JUST UNVEILED A MONUMENT IN RECOGNITION OF ITS NEW STATUS.A 210 SQUARE FOOT ICE PAVILION. 
<P>
THE PAVILION IS MADE ENTIRELY OF ICE AND SNOW. AND CONTAINS ICE SCULPTURES. 
<P>
THE ANNUAL NAMING OF A CITY OF CULTURE FOR EUROPE IS A TRADITION DATING BACK TO 19-85. 
<P>
ATHENS WAS THE FIRST TO HOLD THE TITLE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=28WX/CURRENTS>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>WX/CURRENTS</H3><BR>
THE ONLY SCULPTURES YOU'D BE ABLE TO MAKE HERE ON OUR CENTRAL COAST TODAY. WOULD BE MADE OF SAND.
<P>
AN ABSOLUTELY BEAUTIFUL. SUNNY. AND WARM DAY.
<P>
AND IT'S NOT TOO BAD RIGHT NOW EITHER.
<P>
MOSTLY CLEAR SKIES ACROSS THE REGION.
<P>
IT'S _______ DEGREES IN SALINAS.
<P>
MONTEREY IS REPORTING _________.
<P>
AND FOR OUR VIEWERS IN SANTA CRUZ. IT'S ________ DEGREES.
<P>
DAYTIME HIGHS REACHING INTO THE 70'S TODAY.
<P>
SALINAS TOPPING OFF AT 71. WELL ABOVE NORMAL FOR THIS TIME OF YEAR.
<P>
MONTEREY JUST MISSED THE 70 DEGREE MARK.
<P>
IT WAS 69 ALSO IN GILROY.
<P>
A BIT COOLER IN WATSONVILLE. THE HIGH THERE. JUST 63 DEGREES UNDER MOSTLY SUNNY SKIES.
<P>
THOSE SKIES WILL BE CHANGIN' LATER TOMORROW.
<P>
THAT'S BECAUSE OF THE NEXT STORM SYSTEM THAT'S RACING TOWARD THE CALIFORNIA COASTLINE.
<P>
LOW PRESSURE IS DRIVING THE FRONT. AND SHOULD BE HERE SOMETIME LATE TOMORROW AFTERNOON.
<P>
IT WILL BRING SOME RAIN. AND WINDY CONDITIONS TO OUR CENTRAL COAST. AND HEAVY RAIN AND SNOW IN NORTHERN CALIFORNIA.
<P>
TOMORROW'S FORECAST IS CALLING FOR SUNSHINE IN THE MORNING.
<P>
MORE CLOUDS MOVING IN BY MID-DAY. AND AREAS OF RAIN BY NIGHT.
<P>
HIGHS WILL BE IN THE 60'S.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
THE STANFORD CARDINAL ARE OFF TO THEIR BEST START IN SCHOOL HISTORY AND TODAY THEY CONTINUED TO ROLL THROUGH THE COMPETITION SNAPPING UCLA'S 4-GAME WINNING STREAK.
<P>
AT 16-O, THE CARDINAL ARE ONE OF ONLY TWO TEAMS IN THE COUNTRY STILL UNDEFEATED.
<P>
THE 1ST DAUGHTER IN ATTENDANCE. YOU'D THINK SHE COULD GET BETTER SEATS.
<P>
---------
<P>
STANFORD RUNNING OUT TO AN EARLY LEAD.  WITH THE TRIPLE AND THEN  WILL BOMB FROM BEYOND THE ARC. CARDINAL UP BY 18 AT THE HALF.
<P>
---------
<P>
2ND HALF. BRUINS MAKE A RUN.  WITH THE SPIN MOVE FOR 2 OF HIS 19. UCLA WITHIN ONE.
<P>
---------
<P>
BUT HERE COMES STANFORD.  STOPS AND POPS. STANFORD WITH 14 3-POINTERS IN THE GAME. 
<P>
-------
<P>
WITH FIVE OF THEM. HE LEADS THE CARDINAL WITH A CAREER HIGH 19-POINTS. STANFORD K-O'S THE 8TH RANKED UCLA BRUINS. FINAL. 93-80.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39College Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>College Board</H3><BR>
STANFORD HAS THE LONGEST WINNING STREAK IN THE NATION AT 18.
<P>
ELSEWHERE IN THE PAC TEN. CAL IMPROVES TO 2-3 IN CONFERENCE WITH THE WIN OVER USC.
<P>
--------
<P>
NUMBER 9 ARIZONA BEATS ASU BY TEN.
<P>
OREGON DOWNS WASHINGTON STATE.
<P>
--------
<P>
SANTA CLARA BEATS LOYOLA MARYMOUNT. BUT THE SPARTANS OF SAN JOSE STATE FALL TO 0-4 IN THE WAC.
<P>
-------
<P>
NUMBER ONE NORTH CAROLINA REBOUNDS FROM THEIR LOSS TO MARYLAND BY BEATING APPALACHIAN STATE.
<P>
DUKE SLIPS PAST CLEMSON. LOOK FOR THE BLUE DEVLIS TO TAKE OVER THE TOP SPOT WHEN THE POLLS COME OUT SUNDAY.
<P>
--------
<P>
NUMBER THREE KANSAS BEATS K-STATE BY SEVEN.
<P>
AND UTAH HAS LITTLE TROUBLE WITH WYOMING.     
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Hartnell>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hartnell</H3><BR>
IN J-C HOOPS. THE HARTNELL PANTHERS STILL SEARCHING FOR THEIR 1ST CONFERENCE VICTORY. HOSTING GAVILAN.
<P>
----------
<P>
HARTNELL COMES IN OH-AND-3. BUT THEY GET THINGS GOING AT HOME.  WITH A STRONG MOVE IN THE PAINT. PANTHERS OFF AND RUNNING.
<P>
---------
<P>
THEN. IT'S. THE SEASIDE NATIVE WILL TAKE THIS ONE ALL THE WAY HIMSELF. AND THE PANTHERS FINALLY GET A CONFERENCE VICTORY. THEY BEAT GAVILAN. 82-63. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114Prep Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Board</H3><BR>
THE PANTHERS ARE NOW. 7-12 OVERALL.AND IN GIRLS BASKETBALL. ALVAREZ BEATS KING CITY. THE EAGLES ARE NOW FIVE AND OH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE GOLDEN STATE WARRIORS ARE BEGINING TO MAKE OAKLAND FANS FORGET ABOUT THE RAIDERS.      AT 7-28, THE WARRIORS HAVE THE 4TH WORST RECORD IN THE LEAGUE.
<P>
TONIGHT THEY WRAP UP THIER 6-GAME ROAD TRIP IN PHILY LOOKING TO END A 9-GAME LOSING STREAK.
<P>
THE SIXERS WOULD GET OUT QUICK.  LEADING THE WAY. IVERSON WITH THE TRIPLE. WARRIORS DOWN 35-15 AFTER ONE.
<P>
-------
<P>
THEN WATCH NUMBER THREE GRAB THE REBOUND FROM OUT OF NOWHERE. HE'LL GET THE BALL BACK AND DRAIN 3 MORE OF HIS TEAM HIGH 28. HE HAD 15 IN THE 1ST QUARTER.
<P>
---------
<P>
WITHOUT AN ANSWER FOR ANY OF THE PROBLEMS.
<P>
---------
<P>
MORE IVERSON. THE ALLEY OOP TO ROOKIE. 15-POINTS AND 6-ASSISTS FOR THE VILLANOVA ROOKIE.
<P>
---------
<P>
THE WARRIORS ARE LED BY  WHO SCORES 19-POINTS AND PULLS DOWN 10 BOARDS.
<P>
THE WARRIORS LOSE THEIR 10TH STRAIGHT. FINAL. 112-84.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42NBA Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA Board</H3><BR>
THE WARRIORS LOSE ALL SIX GAMES ON THE ROAD TRIP THEIR BACK HOME TUESDAY WHEN THE PHOENIX SUNS COME TO TOWN.
<P>
THE LAKERS HANDLE THE HEAT AT THE FORUM. 
<P>
---------    
<P>
CLEVELAND FALLS TO SEATTLE 99-91.
<P>
CHRIS WEBBER SCORES 31 IN THE WIZZARDS VICTORY.
<P>
-----------
<P>
UTAH HANDLES ORLANDO EASILY.KARL MALONE WITH 22 OF HIS 32 IN THE 2ND HALF. 
<P>
MINNESOTA NEEDS OVERTIME TO BEAT DALLAS.
<P>
----------- 
<P>
JAYSON WILLIAMS PULLS DOWN 23 BOARDS IN THE NETS VICTORY.     
<P>
AND THE KNICKS BEAT THE RAPTORS BY ELEVEN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
OH WHAT A DIFFERENCE A YEAR MAKES. LAST YEAR AT THIS TIME. THE SAN JOSE ARENA WAS THE SITE FOR THE N-H-L'S ALL-STAR GAME. TONY GRANATO WAS A STARTER ON THE WEST SQUAD AND OWEN NOLAN SCORED A HATTRICK IN THE VICTORY.
<P>
THIS YEAR. NOT A SINGLE SHARK CAN BE FOUND ON THE ROSTER.
<P>
THIS YEARS VERSION TAKING PLACE IN BEAUTIFUL VANCOUVER BRITISH COLUMBIA. 
<P>
---------
<P>
SUNDAY IT'S NORTH AMERICA VERSUS THE WORLD. TONIGHT THE OLD-TIMERS GAME.THE LEGENDS OF THE NHL TAKING ON THE HEROES OF THE HOST CITY.
<P>
-----------
<P>
ONE OF THOSE HERO'S. DAVE "TIGER" WILLIAMS. THIS GAME TIED AT ONE. WILLIAMS HAS THE PENALTY SHOT. AND CHECK OUT THE MOVE TO BEAT. VANCOUVER UP 2-1. YOU LIKED THAT MOVE LOOK AT THIS ONE.
<P>
-----------
<P>
IT'S TIED AT 2. WHEN THE NHL HEROS GO ON TOP. HALL OF FAMER  WITH THE PUTBACK. NHL HEROS WIN IT. 3-2 IS THE FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44College Football>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>College Football</H3><BR>
NEXT. TO MOBILE ALABAMA FOR THE SENIOR BOWL.  NORTH TEAM HAVING SOME TROUBLES.
<P>
----------
<P>
ALREADY DOWN 10-NOTHING. FLORIDA'S  PICKS OFF  OF NEVADA AND HE IS "WEARY" FAST. HE'LL TAKE THIS ONE BACK 97 YARDS FOR THE SCORE. SOUTH ON TOP 17-NOTHING.
<P>
----------
<P>
HAS A GOOD DAY. PLAYING DOWN THE ROAD FROM HIS OLD HIGH SCHOOL. THE AUBURN QB TOSSES TWO TD'S AND PICKS UP THE MVP AWARD.
<P>
--------
<P>
FLORIDA STATE QB  WILL CAP THE SCORING FOR THE SOUTH WITH THE TD PASS TO TEAMMATE.  SOUTH SQUAD  WINS THIS ONE. 31-8 IS THE FINAL.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
IN GOLF. AFTER 3-ROUNDS.GIL MORGAN SITS ATOP THE LEADERBOARD AT THE MASTERCARD CHAMPIONSHIP WITH A 2-SHOT LEAD OVER GIBBY GILBERT.
<P>
AND ON THE L-P-G-A TOUR. JULI INKSTER'S 6-UNDER 66 WAS GOOD ENOUGH TO GIVE HER A 2-SHOT LEAD HEADING INTO THE FINAL ROUND OF THE HEALTHSOUTH CLASSIC.
<P>
NEXT. 4TH ROUND ACTION FROM THE BOB HOPE CLASSIC. THE TOURNAMENT HOST SHOWING HE CAN STILL SWING THE CLUB.
<P>
---------
<P>
NEVER A DOUBT ABOUT THIS GUYS ABILITY.  WITH THE BIRDIE PUTT AT THE PAR FIVE 13TH. AND HE DRAINS IT.
<P>
---------
<P>
WORKING ON HIS GAME FOR NEXT WEEKS AT&T. THIS THE T-SHOT BY THE FUTURE HALL OF FAMER AT THE 12TH HOLE. NOT BAD.
<P>
---------
<P>
HERE'S BAD.  MAKING THE 12TH A DOG LEG LEFT. DON'T QUIT YOUR DAY JOB.
<P>
---------
<P>
TO THE PROS. GREAT DAY FOR. PLAYING IN HIS 1ST TOURNAMENT OF THE SEASON HE SHOOTS HIS 2ND STRAIGHT 66. HE'S 3 SHOTS OFF THE LEAD.
<P>
--------
<P>
HERE'S YOUR LEADER.  WHO WON THIS TOURNAMENT 17 YEARS AGO. LITEZKE BLISTERS THE PALMER COURSE AT PGA WEST WITH A 10-UNDER 62. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Golf Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf Board</H3><BR>
LITZKE SHARES THE LEAD ALONG WITH ANDREW MAGEE. COUPLES AND STEVE JONES ARE 3 SHOTS BACK.
<P>
5-TIME AT&T CHAMP MARK O'MEARA FIRES A 4TH ROUND 67 TO PULL WITHIN FOUR SHOTS. HE'S TIED WITH DAVID DUVAL AND STEWART CINK. 8-GOLFERS ARE WITHIN 6-SHOTS OF THE LEAD. THE FINAL ROUND IS TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=99Wrestling>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Wrestling</H3><BR>
FINALLY. WRESTLING FROM NORTH MONTEREY HIGH SCHOOL. THE FINALS OF THE ARTICHOKE INVITATIONAL.
<P>
----------
<P>
IN THE 112 POUND DIVISION. THIS IS RICKEY MORENO OF WATSONVILLE TAKING ON JONATHON DOMINGUEZ OF N. COUNTY. MORENO WITH THE TAKE DOWN. HE WOULD WIN. 11-6.
<P>
--------
<P>
TO THE 119'S. JUSTIN ESCOVIL OF GILROY GOING UP AGAINST JASON CORNAYHO OF N. COUNTY.  ANOTHER GOOD MATCH. NORTH COUNTY WOULD TAKE THIS ONE THOUGH. CORNAYHO WINNING 8-4.
<P>
----------
<P>
FINALLY. IN THE 130 POUND DIVISION. ONE OF THE BEST WRESTLERS IN THE C-C-S. THIS IS CHRIS VALDEZ OF SALINAS. AND HE HAS HIS WAY WITH JASON FITCH OF PITTSBURGH. VALDEZ  DOMINATING IN THIS ONE. HE WINS. AND IMPROVES HIS RECORD TO 27-2.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Stealth Bomber>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stealth Bomber</H3><BR>
THE ^AIR FORCE^ IS PROVIDING A RARE-GLIMPSE INSIDE ONE OF ITS MOST SOPHISTICATED AND CONTROVERSIAL ^WEAPONS.^ 
<P>
THE B-2 STEALTH BOMBER WENT ON DISPLAY AT EDWARDS AIR FORCE BASE TODAY. 
<P>
THE 2.1AIRCRAFT HAS BEEN HEAVILY CRITICIZED FOR BEING TOO EXPENSIVE.  
<P>
BUT THE AIR FORCE SAYS.IT'S BECOME A SPECIALTY WEAPON THAT'S A TOUGH TARGET FOR RADAR. 
<P>
THE AIR FORCE SAYS THE TWENTY-ONE PLANE FLEET SHOULD BE COMBAT-READY NEXT YEAR. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=116Balloons>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Balloons</H3><BR>
ANOTHER FLYING ^CRAFT^.THIS ONE ON DISPLAY IN ^SWITZERLAND^.
<P>
BALLOONS OF ALL DIFFERENT SHAPES AND SIZES TOOK TO THE SKIES OVER THE ALPS.
<P>
IT'S THE TWENTIETH ANNIVERSARY OF THE SWISS INTERNATIONAL HOT AIR BALLOON FESTIVAL. 
<P>
THE ANNUAL EVENT IS ONE OF THE LARGEST OF ITS KIND IN THE WORLD.
<P>
ABOUT ONE-HUNDRED BALLOONERS FROM THIRTY DIFFERENT COUNTRIES ARE TAKING PART IN THE FESTIVAL. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106Penguins>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Penguins</H3><BR>
^BEACHGOERS^ IN ^SOUTH AFRICA^ ARE GETTING A SPECIAL ^TREAT^ THESE DAYS.
<P>
IT'S A CHANCE TO RENDEZVOUS WITH HUNDREDS OF *JACKASS* PENGUINS.
<P>
YES. THAT'S WHAT THEY'RE CALLED.
<P>
THE PENGUINS HAVE BECOME QUITE ACCUSTOMED TO THE TOURISTS. 
<P>
VOLUNTEERS PATROL THE BEACH TO MAKE SURE THE BIRDS ARE O-K.  AND TO HELP ANY OF THEM WHO MAY BECOME SICK OR INJURED.                                         
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Superbowl Bets-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Superbowl Bets-I</H3><BR>
THE ^MAYORS^ FROM THE TWO SUPERBOWL-BOUND CITIES HAVE LAID IT ON THE LINE.WELL, SORT-OF. 
<P>
EACH IS CONFIDENT ^HIS^ TEAM WILL WIN THE ^BIG GAME^.
<P>
BUT NEITHER WANTS TO BE ON THE SHORT END OF A WINNER-TAKE-ALL PROPOSITION. 
<P>
SO.THEY CAME TO AN AGREEMENT.
<P>
CONNIE FELDMAN TELLS US WHAT IT IS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
