<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Monday, 1/12/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Monday, 1/12/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Weather wrap>Weather wrap</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143prince scuffle>prince scuffle</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132SC flash floods>SC flash floods</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Cloning treaty>Cloning treaty</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134SC tree onto car>SC tree onto car</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139freshman survey-IN>freshman survey-IN</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Bay area floods>Bay area floods</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/penny's>Fox Biz/penny's</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Pajaro river drown?>Pajaro river drown?</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144WX/BAD  WX>WX/BAD  WX</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126robberies/clerks>robberies/clerks</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4049ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129plane crash folo>plane crash folo</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41NFL>NFL</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/bridge opens>Good News/bridge opens</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42AT&T Pebble Beach>AT&T Pebble Beach</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#136sea life el nino-INT>sea life el nino-INT</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(chopper crash)>(chopper crash)</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50SC fair theme>SC fair theme</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145(Santana hall/fame)>(Santana hall/fame)</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140wallaby on the loose>wallaby on the loose</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(ellis island dispute)>(ellis island dispute)</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137wonder woman audit>wonder woman audit</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=107Weather wrap>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Weather wrap</H3><BR>
ALAN, IT'S NOT TOO BAD OUT HERE.JUST A LIGHT DRIZZLE RIGHT NOW.
<P>
BUT ENOUGH TO MAKE THE ROADS SLICK AND DRIVING CONDITIONS A NIGHTMARE.
<P>
SEVERAL PROBLEMS TO REPORT EARLIER IN THE DAY.JUST IN TIME FOR RUSH HOUR.HIGHWAY 68 HAD ITS SHARE OF TRAFFIC ACCIDENTS.
<P>
AT ABOUT 4PM A WOMAN DRIVING A VAN HYDROPLANED AND SLID OFF THE ROAD NEAR SAN BENANCIO ROAD.THEN.JUST A FEW MINUTES LATER AND 20 FEET AWAY FROM THE FIRST ACCIDENT, ANOTHER DRIVER LOST CONTROL OF HIS CAR AND HIT A POLE.
<P>
HE WAS TAKEN TO A LOCAL HOSPITAL WITH MINOR INJURIES.AND SEVERAL HOMES IN THE AREA WERE WITHOUT POWER FOR A FEW HOURS.TRAFFIC WAS ALSO BACKED UP FOR MILES.
<P>
SOME TENSE MOMENTS FOR SCHOOL CHILDREN.AT ABOUT 4:30.SOMEONE APARENTLY REAR-ENDED THE BACK OF A SCHOOL BUS ON DOLAN ROAD NEAR CASTROVILLE.
<P>
THE DRIVER AND PASSENGER HAD MINOR INJURIES.AND NO ONE ON THE BUS WAS HURT.
<P>
C-H-P OFFICERS RESPONDED TO ANOTHER ACCIDENT ON HIGHWAY 101 AND ABBOTT.A WOMAN SAYS A CAMERO WAS SPEEDING UP BEHIND HER AND FORCED HER OFF THE ROAD.HE DROVE AWAY.AND SHE WASN'T INJURED.
<P>
THERE WERE ALSO SEVERAL REPORTS OF DOWNED POWER LINES AND TREES.
<P>
SCOTT BLAKEY WITH PG&E SAYS HUNDREDS OF PEOPLE IN SANTA CRUZ COUNTY WERE WITHOUT POWER TODAY.
<P>
AND IN SEASIDE.ABOUT 12-HUNDRED PEOPLE WERE LEFT IN THE DARK.
<P>
ONLY 174 PEOPLE DON'T HAVE ELECTRICITY IN PRUNEDALE.BUT THAT POWER IS EXPECTED TO BE RESTORED ANY MINUTE.
<P>
THE RAIN HAS SUBSIDED.BUT IT'S STILL A GOOD IDEA TO DRIVE CAREFULLY.
<P>
REPORTING LIVE FROM MONTEREY COUNTY, I'M CHERI GYURO.ALAN, BACK TO YOU.   
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132SC flash floods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC flash floods</H3><BR>
THE MOUNTAINS OF SANTA CRUZ COUNTY WERE UNDER A FLASH FLOOD WATCH EARLIER TODAY.
<P>
OVERNIGHT RAIN LEFT MANY CREEKS AND SMALL STREAMS AT NEAR FLOOD LEVELS.
<P>
THE GROUND IS STILL SOAKED. ESPECIALLY IN THE MOUNTAIN AREAS. MAKING CONDITIONS RIPE FOR MUDSLIDES.
<P>
DOZENS OF PEOPLE LOST POWER FOR SEVERAL HOURS. BUT MOST OF THE ELECTRICITY HAS BEEN RESTORED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134SC tree onto car>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC tree onto car</H3><BR>
POLICE ARE ALSO BLAMING THE WEATHER FOR AN ACCIDENT THAT CRUSHED A CAR ON OCEAN AVENUE IN SANTA CRUZ.
<P>
THE WIND AND RAIN APPARENTLY CAUSED A TREE TO TOPPLE DOWN ON TOP OF THE VEHICLE.
<P>
THE FALLEN TREE ALSO HEAVILY DAMAGED A NEARBY HOUSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Bay area floods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bay area floods</H3><BR>
SEVERE RAIN IS ALSO SOAKING THE BAY AREA.
<P>
WEATHER IS BEING BLAMED FOR TWO CAR ACCIDENTS THERE.
<P>
IN DALY CITY. A TWO-YEAR-OLD BOY WAS KILLED AND HIS 4-YEAR-OLD SISTER WAS CRITICALLY INJURED. WHEN THEIR MOTHER'S CAR SPUN OUT OF CONTROL.       
<P>
AND IN NORTHERN SANTA CLARA COUNTY. FIVE TEENAGERS WERE HURT WHEN THEIR CAR SKIDDED OFF THE ROAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Pajaro river drown?>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pajaro river drown?</H3><BR>
WATSONVILLE POLICE CALLED IN RESCUE CREWS, A SEARCH DOG AND A SEARCH HELICOPTER. AFTER A DRUG SUSPECT MAKES A BREAK FOR IT AND ENDS UP GETTING WASHED AWAY BY THE RAIN SWOLLEN PAJARO RIVER.
<P>
POLICE SAY THEY WERE ATTEMPTING TO ARREST 22 YEAR OLD JORGE ROCHA FOR POSSESSION OF HEROIN. WHEN HE TOOK OFF ON FOOT.
<P>
POLICE CHASED ROCHA TO THE EDGE OF THE PAJARO RIVER.
<P>
THAT'S WHEN HE JUMPED IN. AND DISAPPEARED.
<P>
"THE CURRENT IS SWIFT WE DO HAVE SOME COLD TEMPS AND THATS DEFINITELY OF CONCERN TO US.
<P>
A SEARCH FROM THE AIR AND THE GROUND. TURNED UP NOTHING.
<P>
FIRE DEPARTMENT OFFICIALS. TRAINED IN SWIFT-WATER RESCUE MISSIONS. COMBED THE AREA FOR ABOUT THREE HOURS. BEFORE CALLING OFF THE SEARCH.
<P>
POLICE SAY IF THEY HAVEN'T FOUND ROCHA BY NOW. CHANCES ARE SLIM HE WILL BE FOUND ALIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126robberies/clerks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>robberies/clerks</H3><BR>
FEAR IS RISING AMONG LOCAL STORE CLERKS FOLLOWING A SLEW RECENT ROBBERIES ON THE CENTRAL COAST.
<P>
IN MONTEREY. A CLERK WAS BEATEN LAST WEEK. 
<P>
AND JUST FRIDAY NIGHT. THE OWNER OF A SMALL SALINAS STORE WAS MURDERED.
<P>
RAMESH PATEL PURCHASED THE 1-2-3 MARKET JUST A FEW WEEKS AGO.
<P>
BUT AT ABOUT SEVEN-THIRTY FRIDAY NIGHT.  TWO PEOPLE WEARING MASKS DEMANDED MONEY. THEN SHOT PATEL IN THE CHEST. KILLING HIM.
<P>
ONE FRIEND OF THE FAMILY TOLD US THEY'D DISCUSSED THE POSSIBLITY OF ROBBERY. BUT PATEL WHO HAD BEEN OUT OF WORK AND CONCERNED ABOUT HIS FAMILY. BOUGHT THE STORE ANYWAY.
<P>
WE TALKED ABOUT IT. DE HIS LIFE.
<P>
PATEL ALSO OWNED TONY'S MARKET ON NORTH MAIN.
<P>
HE'D BEEN ROBBED THERE AT LEAST ONCE BEFORE AND AND WAS AWARE IT COULD HAPPEN AGAIN.
<P>
POLICE IN SALINAS SAY THIS IS SIMILAR TO OTHER ROBBERIES IN TOWN BUT THERE IS NOTHING CONNECTING THEM AT THIS POINT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129plane crash folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>plane crash folo</H3><BR>
NATIONAL TRANSPORTATION SAFETY BOARD INVESTIGATORS CONTINUE TO LOOK INTO FRIDAY NIGHT'S FATAL CRASH OF A SMALL PLANE NEAR SALINAS.
<P>
THE PILOT WHO DIED.  RICHARD GRAFF. APPARENTLY HAD EXPERIENCED ENGINE PROBLEMS WHEN THE SINGLE-ENGINE CESSNA HIT A POWER LINE THEN CRASHED INTO A COMMERCIAL GREENHOUSE.
<P>
INVESTIGATORS SAY IT WILL BE WEEKS BEFORE THEY KNOW WHAT HAPPENED.
<P>
MEANWHILE. A MEMORIAL SERVICE FOR GRAFF. THE CO-FOUNDER OF THE CHALONE WINE  GROUP. WILL BE HELD NEXT WEEK. IN SAN FRANCISCO.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/bridge opens>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/bridge opens</H3><BR>
GOOD NEWS FOR RESIDENTS AND BUSINESS OWNERS IN PAJRO.
<P>
A NEW AND IMPROVED BRIDGE. IS BACK IN BUSINESS.
<P>
THE NEW PORTER DRIVE--MAIN STREET BRIDGE WAS UNDERCONSTRUCTION FOR TWO YEARS.
<P>
IT COMES WITH WIDER INTERSECTIONS. MORE LANES AND NEW LIGHTS.
<P>
THE BRIDGE WAS ALSO BUILT HIGHER THAN THE OLD ONE TO ACCOMADATE POSSIBLE LEVEE FLOODS DURING STORMS.
<P>
THE PRICETAG.? NINE-POINT-SIX MILLION DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=136sea life el nino-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>sea life el nino-INT</H3><BR>
EL NINO APPEARS TO BE STARTING TO TAKE IT'S TOLL ON THE NATIONAL WEATHER.
<P>
BUT SCIENTISTS SAY THE WARMING CONDITIONS ARE ALSO THREATENING SEA MAMMALS.
<P>
FOX'S BROOKE SKULSKI HAS MORE ON WHAT SOME *PEOPLE* ARE TRYING TO DO TO COUNTER THE EFFECTS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A MEDICAL HELICOPTER. SENT TO RESCUE VICTIMS OF AN AVALANCHE. CRASHES. KILLING ALL FOUR PEOPLE ON BOARD.
<P>
THAT STORY FROM UTAH'S SALT LAKE COUNTY. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(chopper crash)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(chopper crash)</H3><BR>
THE CHOPPER PICKED UP ONE OF THE INJURED SKIERS AND WAS HEADING BACK TO THE SKI RESORT WHEN A SNOW STORM KICKED UP.
<P>
THE CHOPPER THEN SLAMMED BACK INTO THE MOUNTAIN.
<P>
THE ACCIDENT HAPPENED ABOUT 20 MILES SOUTH OF SALT LAKE CITY.
<P>
THE PILOT, A PARAMEDIC AND A NURSE. ALONG WITH THE INJURED SKIER.  WERE KILLED.
<P>
ANOTHER SKIER WAS SAFELY RESCUED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145(Santana hall/fame)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Santana hall/fame)</H3><BR>
CARLOS SANTANA GAVE A BILINGUAL ACCEPTANCE SPEECH TODAY. WHEN HE BECAME THE FIRST HISPANIC INDUCTED INTO THE ROCK AND ROLL HALL OF FAME.
<P>
SANTANA SAID HE FELT ALMOST LIKE JACKIE ROBINSON. WHO BROKE THE COLOR BARRIER IN BASEBALL.
<P>
OTHER INDUCTEES INCLUDED THE EAGLES. FLEETWOOD MAC. THE MAMAS AND THE PAPAS. AND JAZZ COMPOSER JELLY ROLL MORTON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(ellis island dispute)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(ellis island dispute)</H3><BR>
THE 160-YEAR-OLD BATTLE OVER ELLIS ISLAND IS IN IT'S FINAL STAGE TODAY.
<P>
AS LAWYERS FOR THE STATES OF NEW YORK AND NEW JERSEY PLEAD THEIR CASE BEFORE A SUPREME COURT JUDGE. 
<P>
NEW JERSEY SAYS NEW YORK IS ENTITLED TO ONLY 
<P>
THREE ACRES OF THE 27-POINT-5 ACRE ISLAND. 
<P>
WHILE NEW YORK IS ARGUING THAT TRADITION AND HISTORY GIVES THEM THE RIGHTFUL OWNERSHIP.
<P>
THE FEDERAL GOVERNMENT IS CURRENTLY IN CHARGE OF THE PROPERTY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143prince scuffle>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>prince scuffle</H3><BR>
ANOTHER ROYAL CLASH WITH THE PRESS OVER THE WEEKEND.
<P>
A TELEVISION JOURNALIST SAYS PRINCE ERNST AUGUST OF HANOVER BEAT HIM UP.
<P>
IT HAPPENED WHEN THE PHOTOGRAPHER CONFRONTED THE PRINCE AND PRINCESS CAROLINE OF MONACO. AS THE PAIR WAS LEAVING A FUND-RAISING DINNER. 
<P>
THIS VIDEO SHOWS THE PRINCE SWINGING A LEAD PIPE AT THE PHOTOGRAPHER. BEFORE HIS CAMERA FALLS TO THE GROUND.
<P>
THE JOURNALIST SAYS HE SUFFERED HEAD AND FACE INJURIES AND A BROKEN NOSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Cloning treaty>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cloning treaty</H3><BR>
LESS THAN A WEEK AFTER AN AMERICAN SCIENTIST ANNOUNCED HE WOULD CLONE A HUMAN. 19 EUROPEAN NATIONS SIGN A TREATY TO BAN THE PROCESS.
<P>
THE TREATY SAYS CLONING PEOPLE VIOLATES HUMAN DIGNITY. AND IS A MISUSE OF SCIENCE.
<P>
BRITAIN REFUSED TO SIGN THE MEASURE SAYING THE TREATY IS TOO STRICT.
<P>
GERMANY ALSO REFUSED. SAYING IT'S NOT STRICT ENOUGH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139freshman survey-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>freshman survey-IN</H3><BR>
A NEW SURVEY SHOWS CALIFORNIA COLLEGE CAMPUSES ARE NO LONGER HOT BEDS FOR POLITICAL DEMONSTRATIONS.
<P>
IN FACT.  MOST FRESHMAN ARE FOLLOWING THE CONSERVATIVE LEAD OF THEIR BABY BOOMER PARENTS. 
<P>
REBBCA GOMEZ HAS MORE ON THIS LATEST TREND. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/penny's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/penny's</H3><BR>
THE OLD GROVE PHARMACY IN PACIFIC GROVE. HAS CLOSED IT'S DOORS FOR GOOD.
<P>
BUT THE BUILDING WON'T STAY EMPTY VERY LONG. AS A NEW BUT FAMILIAR BUSINESS MOVES IN.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
LASTING MEMORIES. A BRIDAL REGISTRY AND SPECIALTY SHOP WILL BE MOVING IN, IN MARCH.
<P>
	OWNER OLIVIA MOTI SAYS THE LARGER SPACE WILL ALLOW HER TO EXPAND HER OWN BUSINESS. 
<P>
	IN ADDITION, SHE PLANS TO RESERVE ONE CORNER OF THE BUILDING TO OPERATE THE ONLY J-C PENNEY'S CATALOG STORE ON THE PENINSULA.
<P>
WE FELT COMMUNITY NEEDED THIS. A LOT OF ITEMS SOLD IN DEPARTMENT STORES, BRING MORE CUSTOMERS TO PACIFIC GROVE.
<P>
	YOU MAY REMEMBER J-C PENNEY'S CLOSED ITS MONTEREY STORE AND CATALOG SERVICE CENTER BACK IN AUGUST.
<P>
	MOTI WON THE CONTRACT TO RE-OPEN THE J-C PENNY'S CATALOG CENTER AFTER AN INTENSIVE INTERVIEWING PROCESS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144WX/BAD  WX>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>WX/BAD  WX</H3><BR>
"BAD WEATHER VIDEO FOR WEATHER FROM SAN FRANCISCO AND SIERRA"
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4049ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
IF YOU'RE HONEST ABOUT IT, YOU'VE GOT TO ADMIT, THE 49ERS WERE BEATEN BY A BETTER TEAM. YES, THERE WERE A FEW BAD CALLS, BUT THE PACKERS EARNED THE NFC CHAMPIONSHIP.
<P>
TODAY WAS CHECK-OUT DAY FOR THE NINERS. TIME TO CLEAN OUT THE LOCKERS IN THE SANTA CLARA FACILITY, AND START THINKING ABOUT NEXT YEAR.
<P>
AND IN CASE YOU WERE WONDEREING, THE EARLY LINE HAS THE PACKERS A 13 AND A HALF POINT FAVORITE OVER THE BRONCOS FOR THE SUPER BOWL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41NFL>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NFL</H3><BR>
TO LEAGUE NEWS, AND TONITE ITS ANNOUNCED THAT FOX WILL PAY 4.4 BILLION DOLLARS OVER THE NEXT 8-YEARS TO CONTINUE TELEVISING NFC FOOTBALL.
<P>
BUT THE BIG NEWS IS THAT CBS HAS OUTBID NBC FOR THE RIGHTS TO TELEVISE THE AFC GAMES. CBS PAID 4-BILLION OVER 8-YEARS TO GET BACK INTO THE FOOTBALL BUSINESS.
<P>
THE PEACOCK NETWORK IS NOW COMPETING WITH ABC FOR THE RIGHTS TO MONDAY NIGHT FOOTBALL.
<P>
IN OTHER NFL NEWS, FORMER NEW ORLEANS SAINTS COACH JIM MORA HAS ACCEPTED THE HEAD COACHING JOB WITH THE INDIANAPOLIS COLTS.
<P>
MORA LED THE SAINTS TO THEIR ONLY 4-PLAYOFF APPEARANCES. BUT THE COLTS JUST SEEM TO BE.THE COLTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42AT&T Pebble Beach>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>AT&T Pebble Beach</H3><BR>
WITH THE 49ERS SEASON OVER, MUCH OF OUR LOCAL ATTENTION NOW TURNS TO THE UPCOMING AT&T PEBBLE BEACH NATIONAL PRO AM.
<P>
TODAY IS THEIR ANNUAL PRE-TOURNAMENT PRESS CONFERENCE AT STANFORD. BUT DUE TO A PRIOR COMMITTMENT, DEFENDING CHAMP MARK O'MEARA WAS A NO SHOW.
<P>
IN HIS PLACE, ONE OF THE BIGGEST CELEBRITY DRAWS FOR LOCAL FANS, JERRY RICE.
<P>
ZANE TABARI HAS THE STORY OF GOLF'S LATEST CONVERT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
TO HOOPS, AND FOLLOWING THEIR MORAL VICTORY, SATURDAY NIGHT'S 5-POINT LOSS IN CHICAGO, THE WARRIORS HOPE TO GIVE A VERY HOT MINNESOTA TIMBERWOLVES TEAM A TOUGH 48-MINUTES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO THE ICE, AND TONITE THE SHARKS HOST THE DALLAS STARS. THE TEAM WITH THE BEST RECORD IN THE NHL, THE TEAM WITH THE SHARKS FORMER GOALIE ED BELFOUR, AND THE TEAM THE SHARKS BEAT 1-NOTHING THE LAST TIME THEY MET.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50SC fair theme>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC fair theme</H3><BR>
THE SANTA CRUZ COUNTY FAIR IS STILL MONTHS AWAY. BUT ORGANIZERS ARE ALREADY BUSY. AND THEY NEED YOUR HELP.
<P>
THEY'RE LOOKING FOR A FAIR THEME.
<P>
THE THEME SHOULD TOUCH UPON YOUTH. AGRICULTURE. AND EDUCATION.
<P>
OF COURSE. IT SHOULD ALSO AIM AT BEING FUN. AND UNIQUE TO SANTA CRUZ COUNTY.
<P>
SEND YOUR IDEA TO THE FAIR OFFICE AT 2601 EAST LAKE AVENUE.WATSONVILLE.95076.
<P>
THE DEADLINE IS FEBRUARY SIXTH.
<P>
THE CONTEST WINNER GETS 12.ONE-DAY PASSES TO THE FAIR AND A FRAMED COPY OF THE FAIR POSTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140wallaby on the loose>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>wallaby on the loose</H3><BR>
IT WASN'T A MOOSE ON THE LOOSE.BUT A PAIR OF WALLABIES THAT HAD HILLSBOROUGH COUNTY, FLORIDA DEPUTIES SEARCHING HIGH AND LOW TODAY.  
<P>
THE TWO ANIMALS.WHICH LOOK LIKE LITTLE WHITE 
<P>
KANGAROOS.ESCAPED FROM THE BACKYARD OF THEIR TAMPA HOME THIS MORNING.  
<P>
THEIR OWNER EASILY CAUGHT UP WITH THE FEMALE RUNAWAY. 
<P>
BUT IT TOOK A LITTLE LONGER TO GRAB HER MATE.A WILDER MALE WALLABY. 
<P>
HE JUST KEPT HOPPING OUT OF REACH. 
<P>
FORTUNATELY. THE WALLABY'S GET-AWAY PLAN WASN'T FOOL-PROOF.AND OFFICIALS WERE ABLE TO BAG HIM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137wonder woman audit>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>wonder woman audit</H3><BR>
A HOLLYWOOD STUDIO IS LOOKING TO REMAKE A POPULAR 70'S T-V SERIES. BUT FIRST THEY HAVE TO FIND THE RIGHT WOMAN. PREFERABLY ONE THAT CAN FLY AN INVISIBLE PLANE.
<P>
WARNER BROTHERS HELD AN OPEN CASTING CALL THIS WEEKEND. LOOKING FOR AN ACTRESS TO PLAY WONDER WOMAN.
<P>
THE STUDIO SAYS THEY WANT A  "90'S FEMALE" WHO IS SMART AND PEACE-LOVING. BUT CAN ALSO "KICK BUTT." NOW REMEMBER THAT'S A QUOTE.
<P>
APPARENTLY. A NUMBER OF PEOPLE MATCHED THAT DESCRIPTION. BECAUSE HUNDREDS OF WONDER WOMAN WANNA-BES SHOWED UP TO TRY-OUT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
