<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Thursday, 2/26/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 2/26/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Sal Manhunt-INT>Sal Manhunt-INT</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Sal Manhunt-GUTS>Sal Manhunt-GUTS</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(prisoner guards)>(prisoner guards)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Sal Manhunt-TAG>Sal Manhunt-TAG</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143(police indicted)>(police indicted)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Heroin bust>Heroin bust</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(chemical fire)>(chemical fire)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127school safety report>school safety report</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22(Eclipse)>(Eclipse)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Shannon arrest>Shannon arrest</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134Oprah wins-INT>Oprah wins-INT</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Chittendon murder>Chittendon murder</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/titanic trips>Fox Biz/titanic trips</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Amesti home>Amesti home</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Prep Basketball>Prep Basketball</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Giant Squid>Giant Squid</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Pinnacles home vid>Pinnacles home vid</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#136Rancho chualar>Rancho chualar</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132Clinton in California>Clinton in California</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Steinbeck house>Steinbeck house</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Wilson 7 more>Wilson 7 more</A></TD>


<TD BGCOLOR=#FFFFFF> </TD>
</Table>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=107Sal Manhunt-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal Manhunt-INT</H3><BR>
IT'S A BRUTAL STORY.
<P>
25-YEAR OLD ISAAC LOZA IS ACCUSED OF BEATING HIS GIRLFRIEND'S 2-YEAR OLD DAUGHTER SO SEVERELY. THE TODDLER SUFFERED A TORN LIVER AND MASSIVE HEAD INJURIES. AND IS IN EXTREMELY CRITICAL CONDITION TONIGHT.
<P>
THE INCIDENT ORIGINALLY TOOK PLACE IN STOCKTON. BUT THE MANHUNT FINALLY ENDED JUST A FEW HOURS AGO HERE IN SALINAS, MORE THAN A HUNDRED MILES AWAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Sal Manhunt-GUTS>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal Manhunt-GUTS</H3><BR>
THE TINY 2-YEAR OLD AIRLIFTED TO OAKLAND'S CHILDREN'S HOSPITAL YESTERDAY MORNING SUFFERED FROM INJURIES THAT SHOCKED EVEN VETERAN LAW ENFORCEMENT OFFICIALS.
<P>
AROUND 4 O'CLOCK WEDNESDAY MORNING, THE MOTHER OF THE CHILD WOKE UP IN HER STOCKTON HOME TO FIND HER BOYFRIEND, 25-YEAR OLD ISAAC LOZA, REPORTEDLY PUNCHING AND BEATING HER DAUGHTER IN THE TODDLER'S ROOM.
<P>
ACCORDING TO THE MOTHER, LOZA THEN DROVE THE MOTHER AND DAUGHTER TO THE HOSPITAL. THEN FLED.
<P>
SAN JOAQUIN SHERIFF'S OFFICIALS IMMEDIATELY CONTACTED THE SALINAS, SOLEDAD AND GONZALES POLICE DEPARTMENTS BECAUSE THEY KNEW OF LOZA'S FAMILY TIES IN MONTEREY COUNTY.
<P>
BUT NO ONE KNEW WHERE HE WAS. UNTIL THIS AFTERNOON.
<P>
LOZA WAS ARRESTED AT THIS SALINAS APARTMENT TONIGHT. WITHOUT ANY TROUBLE.
<P>
POLICE SAY. THE SHEER HORROR OF THE CASE MAY HAVE ENCOURAGED TIPPERS TO CALL IN WITH LOZA'S WHEREABOUTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Sal Manhunt-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal Manhunt-TAG</H3><BR>
AGAIN, THE 2-YEAR OLD IS STILL IN EXTREMELY CRITICAL CONDITION AT OAKLAND'S CHILDREN'S HOSPITAL.
<P>
LOZA WILL BE TAKEN FROM SALINAS BACK TO SAN JOAQUIN COUNTY TONIGHT. WHERE HE'LL FACE ATTEMPTED MURDER CHARGES.
<P>
LOZA'S MOTHER, WHO *LIVES* IN SALINAS, TOLD US TONIGHT SHE'S IN SHOCK, SAYING HER SON HAS NEVER DONE ANYTHING LIKE THIS IN HIS LIFE.
<P>
ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Heroin bust>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Heroin bust</H3><BR>
A ROUTINE TRAFFIC STOP EARLY THIS MORNING LEADS MONTEREY COUNTY SHERIFF'S OFFICIALS TO WHAT'S BEING CALLED THE LARGEST SEIZURE OF HEROIN IN THE COUNTY'S HISTORY.
<P>
TAKE A LOOK AT WHAT THEY FOUND:  11 POUNDS OF BLACK TAR HEROIN WITH A STREET VALUE OF MORE THAN TWO MILLION DOLLARS. STUFFED INSIDE A CAR DRIVEN BY A 19 YEAR OLD MAN.
<P>
THE BUST HAPPENED JUST BEFORE TWO THIS MORNING ON HIGHWAY 101 AND AIRPORT BOULEVARD IN SALINAS.
<P>
THE C.H.P. ORIGINALLY PULLED OVER SAN JOSE RESIDENT ALEJANDRO LARA FOR SPEEDING. BUT AFTER A SEARCH OF HIS CAR. FOUND THE DRUGS.
<P>
Today we seized 11 pounds.  Generally now a days, most heroin seizures are anywhere from a pound to three pounds because of the value involved in it.  To have one of this size is rare.
<P>
LARA IS BEING DETAINED ON A MILLION DOLLARS BAIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127school safety report>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>school safety report</H3><BR>
SOME GOOD *AND* BAD NEWS ABOUT CALIFORNIA SCHOOLS.
<P>
A JUST-RELEASED STUDY SHOWS VIOLENCE IS DOWN IN MOST SCHOOLS THROUGHOUT THE STATE. BUT HERE IN OUR AREA. CERTAIN CRIMES ARE ON THE RISE.
<P>
ACCORDING TO THE "CALIFORNIA SAFE SCHOOLS REPORT" RELEASED TODAY, OVERALL VIOLENCE STATE-WIDE WAS DOWN SIX PERCENT FROM LAST YEAR.
<P>
BUT *MONTEREY COUNTY* ACTUALLY SAW A LARGE *INCREASE* IN CRIME. WITH THE TWO LARGEST IN SEXUAL OFFENSES AND ASSAULT WITH A DEADLY WEAPON.
<P>
MEANWHILE. SANTA CRUZ COUNTY SAW AN INCREASE IN DRUG AND ALCOHOL-RELATED CRIMES.
<P>
LOCAL SCHOOL OFFICIALS, HOWEVER, BELIEVE THE HIGHER NUMBERS HAVE MORE TO DO WITH BETTER *REPORTING* OF CRIMES THAN ANYTHING ELSE.
<P>
THIS IS ONLY THE SECOND YEAR OF THE STUDY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Shannon arrest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Shannon arrest</H3><BR>
A FORMER GREENFIELD POLICE OFFICER. WHO'S AWAITING RE-TRIAL ON CHARGES  HE BEAT TWO SHACKLED PRISONERS. IS IN MORE HOT WATER TONIGHT.
<P>
MICHAEL SHANNON HAS BEEN ARRESTED IN SANTA CLARA COUNTY AND CHARGED WITH FIFTEEN CRIMES.
<P>
AMONG OTHER THINGS. SHANNON IS ACCUSED OF POSSESSING ASSAULT WEAPONS. AND A GRENADE LAUNCHER. 
<P>
HIS BAIL IS SET AT TWO MILLION DOLLARS.
<P>
SHANNON'S FIRST MONTEREY COUNTY TRIAL ENDED IN A HUNG JURY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Chittendon murder>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chittendon murder</H3><BR>
A JUDGE RULES THAT A SANTA CRUZ TEENAGER ACCUSED OF SHOOTING TO DEATH ANOTHER TEEN. WILL BE TRIED AS AN ADULT.
<P>
        17-YEAR OLD FRANCISCO MARQUEZ IS ACCUSED IN THE 
<P>
SHOOTING DEATH OF ULYSSES HUANTE. AN 18 YEAR
<P>
OLD CABRILLO COLLEGE STUDENT.
<P>
        PROSECUTORS SAY MARQUEZ. ALONG WITH 18-YEAR OLD JESUS ARROYO MADRIGAL. MURDERED HUANTE IN ORDER TO STEAL HIS CAR.
<P>
TODAY IN JUVENILE HALL. THE PUBLIC DEFENDER
<P>
REPRESENTING MARQUEZ. SAID HE WASN'T SURPRISED
<P>
BY THE JUDGE'S DECISION.
<P>
"We anticipated that.  The probation officer did a very
<P>
thorough investigation of the case, and he determined that
<P>
the minor would be unfit forjuvenile court, and we didn't
<P>
try to challenge that."
<P>
        THE JUDGE SAID MARQUEZ WILL BE TRIED AS AN ADULT BECAUSE OF THE SEVERITY OF THE CRIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Amesti home>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Amesti home</H3><BR>
A SANTA CRUZ COUNTY HOME IS DELIBERATELY TORCHED TODAY BY OFFICIALS WHO SAY THE STRUCTURE WAS TOO DANGEROUS.
<P>
THIS VACANT HOME. SITS ON A PLOT OF SOFT EARTH WHICH HAS BEEN MOVING WITH EACH STORM.
<P>
C-D-F OFFICIALS AND THE OFFICE OF EMERGENCY SERVICES DECIDED IT WAS TOO HAZARDOUS TO LEAVE UP.SO TODAY.THEY BURNED IT DOWN.
<P>
OFFICIALS SAY BURNING THE HOUSE WAS A MUCH MORE COST EFFECTIVE. AND SPEEDY WAY OF GETTING RID OF THE HAZZARD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Giant Squid>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giant Squid</H3><BR>
YOU COULD CALL IT ANOTHER CASUALTY OF EL NINO.
<P>
GIANT SQUID ARE RARE IN THESE PARTS. BUT ONE HAS WASHED UP NEAR HOPKINS BEACH. IN PACIFIC GROVE.
<P>
THE HUMBOLT SQUID IS THREE FEET LONG.
<P>
IT WAS FOUND ALIVE AND IS BEING CLOSELY MONITORED IN A QUARANTINED TANK AT THE MONTEREY BAY AQUARIUM.
<P>
RESCUERS SAY THEY DON'T EXPECT THE SQUID TO LIVE VERY LONG. BECAUSE THE CREATURES HAVE NEVER DONE WELL IN CAPTIVITY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Pinnacles home vid>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pinnacles home vid</H3><BR>
WORK CREWS ARE BUSY TRYING TO REBUILD PARTS OF PINNACLES NATIONAL MONUMENT. DEVASTATED BY RECENT FLOODS.
<P>
OFFICIALS SAY IT WILL BE WEEKS BEFORE THE PUBLIC IS ALLOWED BACK INTO THE PARK.
<P>
FLOOD DAMAGE HAS CUT OFF ACCESS TO THE ENTRANCE STATION.  AND DESTROYED MORE THAN A HUNDRED PARKING SPACES.
<P>
CREWS ARE ALSO BUSY REBUILDING A FEW BRIDGES THAT COLLAPSED DURING THE STORMS.
<P>
THOSE LIVING INSIDE THE PARK WERE ALLOWED TO RETURN EARLIER THIS WEEK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=136Rancho chualar>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rancho chualar</H3><BR>
A CONTROVERSIAL PROPOSED HOUSING DEVELOPMENT. WHICH WOULD MORE THAN DOUBLE THE SIZE OF CHUALAR. WAS APPROVED BY THE BOARD OF SUPERVISORS LAST WEEK. BUT OPPONANTS ARENT' GIVING UP.
<P>
A GROUP OF ANGRY SOUTH MONTEREY COUNTY RESIDENTS IS  GATHERING SIGNATURES TO STOP THE RANCHO CHUALAR TWO SUBDIVISION.
<P>
THE GROUP'S AIM IS TO SEE THE ISSUE PUT TO A VOTE OF CITIZENS.
<P>
THE GROUP SAYS IT'S CONCERNED ABOUT THE LOSS OF AG LAND. AND THEY SAY MONTEREY COUNTY COULD GO THE WAY OF ORANGE COUNTY. IF THE PEOPLE DON'T SPEAK UP.
<P>
IT'S FOREVER TAKING. FROM THAT LAND. 
<P>
OPPPONENTS NEED MORE THAN NINE-THOUSAND SIGNITURES TO FORCE A VOTE IN THE NOVEMBER ELECTION. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132Clinton in California>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton in California</H3><BR>
PRESIDENT CLINTON IS CONTINUING HIS EFFORTS TO HELP AREAS OF THE COUNTRY DEVASTATED BY "EL NINO". 
<P>
THE PRESIDENT ATTENDED A ROUNDTABLE DISCUSSION ON DISASTER RELIEF IN OAKLAND TODAY. 
<P>
ALSO PARTICIPATING IN THE DISCUSSION WAS FEDERAL EMERGENCY MANAGEMENT AGENCY DIRECTOR JAMES LEE WITT AND OAKLAND MAYOR ELIHU HARRIS. 
<P>
SO FAR THE PRESIDENT HAS PLEDGED 20-MILLION DOLLARS IN FEDERAL FUNDS FOR CALIFORNIANS.AND TODAY HE ADDED ANOTHER FOUR COUNTIES TO THE LIST RECEIVING RELIEF MONEY. 
<P>
"the people of california. flying up here."
<P>
AFTER THE DISCUSSION. THE PRESIDENT HEADED TO UTAH FOR A FAMILY VACATION TO CELEBRATE FIRST DAUGHTER CHELSEA'S 18TH BIRTHDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Wilson 7 more>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Wilson 7 more</H3><BR>
GOVERNOR WILSON TODAY DECLARED A STATE OF EMERGENCY IN SEVEN MORE COUNTIES.
<P>
MONTEREY. SANTA CRUZ AND SAN BENITO COUNTIES WERE ALREADY ON THAT LIST. A LIST THAT NOW INCLUDES 42 OF THE STATE'S 58 COUNTIES.
<P>
THE GOVERNOR ALSO SIGNED AN EXECUTIVE ORDER ALLOWING THE BURNING OF FLOOD DEBRIS ON NORMAL "NO-BURN" DAYS.
<P>
HE SAYS THAT'S NECESSARY TO DISPOSE OF DEBRIS WHICH MIGHT OTHERWISE BLOCK CREEKS AND STREAMS. AND CAUSE MORE FLOODING IN COMING STORMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
SOME CALIFORNIA STATE PRISON GUARDS ARE IN HOT WATER TONIGHT. ACCUSED OF PROVOKING PRISONERS TO FIGHT. FOR THEIR OWN AMUSEMENT.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(prisoner guards)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(prisoner guards)</H3><BR>
A FEDERAL GRANT JURY HAS ACCUSED EIGHT STATE PRISON OFFICERS OF PITTING RIVAL GANG INMATES. AT A CALIFORNIA STATE PRISON. IN DEADLY "GLADIATOR FIGHTS."
<P>
THE DEFENDANTS. A PRISON LIEUTENANT, TWO SERGEANTS, AND FIVE CORRECTIONAL OFFICERS. ALLEGEDLY CONSPIRED TO BRUTALIZE THE PRISONERS. 
<P>
STATE AND FEDERAL AUTHORITIES SAY THE DELIBERATELY-STAGED FIGHTS WERE CARRIED OUT FOR THE GUARDS' AMUSEMENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143(police indicted)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(police indicted)</H3><BR>
IN NEW YORK. PROSECUTORS HAVE FILED FEDERAL CIVIL RIGHTS CHARGES AGAINST FIVE NEW YORK CITY POLICE OFFICERS. IN CONNECTION WITH THE TORTURE BEATING OF 
<P>
HAITIAN IMMIGRANT ABNER LOUIMA. 
<P>
FOUR OFFICERS HAVE BEEN INDICTED IN STATE COURT ON CHARGES OF RACIALLY MOTIVATED ATTACKS ON LOUIMA LAST AUGUST. A FIFTH WAS CHARGED WITH LYING ABOUT THE ALLEGED ATTACK. 
<P>
A BROOKLYN D-A SAYS HE ASKED FOR FEDERAL INVOLVEMENT BECAUSE THE PENALTIES ARE STIFFER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(chemical fire)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(chemical fire)</H3><BR>
OKLAHOMA FIRE FIGHTERS HAVE FINALLY CONTAINED A HAZARDOUS CHEMICAL FIRE.
<P>
IT TOOK TWELVE HOURS AND THOUSANDS OF GALLONS OF WATER TO FIGHT THE BLAZE AT BAROID'S DRILLING FLUIDS WAREHOUSE.  
<P>
MORE THAN 2-HUNDRED PEOPLE WITHIN A FIVE MILE RADIUS WERE FORCED TO EVACUATE THEIR HOMES. AFTER DANGEROUS CHEMICALS WERE RELEASED INTO THE AIR.  
<P>
RESIDENTS WILL BE KEPT OUT OF THEIR HOMES UNTIL AT LEAST TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22(Eclipse)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Eclipse)</H3><BR>
THE WESTERN HEMISPHERE'S LAST SOLAR ECLIPSE OF THE CENTURY WAS TOTAL IN THE CARIBBEAN AND NORTHERN SOUTH AMERICA TODAY. 
<P>
IN WASHINGTON, DC. AND ALONG PARTS OF THE EASTERN SEABOARD.THE ECLIPSE WAS ONLY PARTIAL. 
<P>
THE MOON BLOCKED A PIECE OF THE AFTERNOON SUN. PROVIDING ONLOOKERS WITH A MEMORABLE SIGHT.  
<P>
WASHINGTON'S WEATHER WAS PERFECT SO THE NATURAL DRAMA ABOVE PROVIDED QUITE THE SHOW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134Oprah wins-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Oprah wins-INT</H3><BR>
IT WAS A HIGH-STAKES FIGHT OF REGAL PROPORTIONS.  THE BARONS OF BEEF AND THE QUEEN OF TALK.
<P>
WELL, TODAY, THE QUEEN WON. 
<P>
OPRAH WINFREY WALKED OUT OF COURT VICTORIOUS AFTER CATTLEMEN COULDN'T CONVINCE A JURY THAT SHE HAD SLAMMED THEIR PRODUCT UNFAIRLY. 
<P>
FOX'S GRANT RAMPY HAS THE STORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/titanic trips>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/titanic trips</H3><BR>
FOR THOSE WHO CAN'T GET ENOUGH OF THE TITANIC. A BRITISH COMPANY WILL SOON BE OFFERING SUBMARINE TRIPS TO VISIT THE WRECK AT THE BOTTOM OF THE ATLANTIC OCEAN. 
<P>
BUT THE COST MAY BE ENOUGH TO SINK YOUR BANK ACCOUNT.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
A TRAVEL AGENCY CALLED "WILDWINGS" WILL BE BOOKING TRIPS.QUITE EXPENSIVE TRIPS.FOR A DEEP OCEAN EXPEDITIONS COMPANY. 
<P>
THE PRICE TAG. A WHOPPING 35-THOUSAND DOLLARS.
<P>
THAT INCLUDES THE PASSENGER A FLIGHT TO NEWFOUNDLAND. AND A SEA TRIP TO A MOTHER SHIP ANCHORED ABOVE THE WRECK. 
<P>
FROM THERE A MINI-SUBMARINE. LIKE THE ONES USED IN THE MOVIE "TITANIC". WILL TAKE THEM TO THE 
<P>
REAL TITANIC. 
<P>
TWO MINI-SUBS WILL EACH MAKE DAILY DESCENTS TO THE TITANIC.  CARRYING A PILOT AND TWO PASSENGERS ON THE FIVE-HOUR EXPEDITION.  
<P>
THE FIRST TRIPS TO THE SHIPWRECK ARE EXPECTED TO BEGIN IN AUGUST. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Prep Basketball>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Basketball</H3><BR>
THE MONTEREY BAY LEAGUE CHAMPION SEASIDE SPARTANS JUMP INTO THE C.C.S. PLAYOFFS TONITE. THE TOP SEED IN THE DIVISION III BOYS BRACKET, PLAYS HOST TO SARATOGA HIGH SCHOOL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
FROM THE PREPS TO THE PROS, AND THE NEW LOOK WARRIORS, WINNER'S OF 2-STRAIGHT ROAD GAMES, AND 4 OF THEIR LAST 6 OVERALL, VISIT CHRIS WEBBER AND THE WASHINGTON WIZZARDS TONTIE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
TO COLLEGE HOOPS, AND BOTH STANFORD AND CAL VISIT THE STATE OF ARIZONA TONITE.
<P>
WE START WITH THE 8TH RANKED STANFORD CARDINAL, LOOKING FOR A LITTLE PAY-BACK FOR AN EARLIER OVERTIME LOSS TO THE ARIZONA STATE SUN DEVILS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
WITH THE OLYMPIC BREAK OVER, THE SHARKS RETURN TO THE ICE FOR THE FIRST TIME TONITE.
<P>
SAN JOSE PLAYS HOST TO BRETT HULL AND THE ST. LOUIS BLUES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Steinbeck house>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Steinbeck house</H3><BR>
TIME'S ALMOST UP FOR THAT CHANCE TO OWN A HOME FOR ONLY TEN DOLLARS.
<P>
THE DRAWING TAKES PLACE TOMORROW NIGHT AT 7:58.
<P>
IT'S NOT TOO LATE.
<P>
TICKETS CAN STILL BE PURCHASED AT THE NATIONAL STEINBECK CENTER AT 371 MAIN STREET UNTIL FIVE  TOMORROW EVENING.
<P>
.OR AT THE KAUFMAN AND BROAD CORPORATE OFFICE AT HARDEN RANCH.ALSO UNTIL FIVE P-M.
<P>
TICKETS WILL ALSO BE AVAILABLE UNTIL SEVEN TOMORROW NIGHT AT THE KAUFMAN AND BROAD SALES CENTER AT EIGHT CHABLIS CIRCLE.
<P>
WE WILL BE THERE LIVE FOR THAT DRAWING. SO YOU CAN WATCH IT RIGHT HERE ON K-C-B-A. AGAIN THAT'S AT 7:58 P-M.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
