<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Friday, 2/27/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Friday, 2/27/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Steinbeck draw>Steinbeck draw</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Steinbeck reax>Steinbeck reax</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(town rampage)>(town rampage)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Steinbeck walk thru>Steinbeck walk thru</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(vampire kid senten)>(vampire kid senten)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Steinbeck events>Steinbeck events</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(obese trial folo)>(obese trial folo)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Mty home lottery>Mty home lottery</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Lockerbie ruling>Lockerbie ruling</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126West marine fine>West marine fine</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/PAN AM>Fox Biz/PAN AM</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Dead Fetus>Dead Fetus</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134Child beating susp>Child beating susp</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Harry Caray>Harry Caray</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132Weiland arraign>Weiland arraign</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Corralitos slide>Corralitos slide</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Hwy 129 closed>Hwy 129 closed</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140NFL>NFL</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Hwy 101 delays>Hwy 101 delays</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50cop tipping>cop tipping</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129NPS river satellite>NPS river satellite</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139weekend movies-I>weekend movies-I</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/wilson new jobs>Good News/wilson new jobs</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Kids News>Kids News</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(lockerbie) >bump 2(lockerbie) </A></TD>


<TD BGCOLOR=#FFFFFF> </TD>
</Table>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=107Steinbeck draw>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Steinbeck draw</H3><BR>
THE PARTY *WAS* AT THE DREAM HOME IN SALINAS. BUT AFTER THE WINNER WAS ANNOUNCED, IT MOVED HERE TO THE AQUARIUM, WHICH IS WHERE MOST OF THE STEINBECK WEEKEND EVENTS ARE GOING TO TAKE PLACE.
<P>
WHO *IS* THE WINNER OF THAT DREAMHOUSE? I WISH I COULD SAY IT WAS ME. BUT IT ISN'T.
<P>
SO LET'S SHOW YOU WHO IT IS.
<P>
"AND THE WINNER IS.OF SALINAS.  
<P>
THEY MISPRONOUNCED THE NAME. IT'S ACTUALLY EDUVIJES ROSALES OF SALINAS. THIS IS HER REACTING TO THE NEWS FROM HER HOME TONIGHT.
<P>
THE NEW HOMEOWNER GETS THIS 5-BEDROOM, 3 BATH NORTH SALINAS HOME WORTH 235-THOUSAND DOLLARS - FOR FREE.
<P>
SHE ALSO GETS FREE SPPLIANCES, FREE LANDSCAPING, FREE CARPET, ETC.
<P>
COURTESY OF SEVERAL COMPANIES, WHO DONATED THEIR SERVICES, PRODUCTS. AND OF COURSE. KAUFMAN AND BROAD DONATED THE HOUSE.
<P>
SO *ALL* THE TICKET SALES FROM THIS EVENT,. NOW NEAR 400-THOUSAND DOLLARS. WILL ALL GO TO BENEFIT THE NEW "NATIONAL STEINBECK CENTER MUSEUM," WHICH OPENS THIS SUMMER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Steinbeck reax>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Steinbeck reax</H3><BR>
AS WE MENTIONED. THE PARTY HAS NOW MOVED FROM THAT DREAM HOME IN SALINAS TO THE MONTEREY BAY AQUARIUM. WHICH IS WHERE JOHN STEINBECK'S BIRTHDAY WILL BE CELEBRATED THE REST OF THE WEEKEND.
<P>
JOINING ME NOW IS CALISA MOORE. 
<P>
SO, IF YOU MISSED THE PARTY TONIGHT. AND, LIKE ME, DIDN'T GET THE HOME. YOU CAN STILL CELEBRATE STEINBECK HERE AT THE AQUARIUM THIS WEEKEND.
<P>
REPORTING LIVE IN MONTEREY, I'M J.K. ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Steinbeck walk thru>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Steinbeck walk thru</H3><BR>
MEANWHILE. *AT* THE SITE OF THE STEINBECK CENTER ITSELF. FOLKS WERE TREATED TO A SNEAK PEEK AT THE 37-THOUSAND SQUARE FOOT FACILITY.
<P>
PEOPLE WHO RAISED MONEY FOR THE CENTER GOT TO TAKE A GUIDED TOUR OF THE PLACE TODAY, HARD HATS AND ALL.
<P>
ONCE IT'S FINISHED IN JUNE. THE MUSEUM WILL ALLOW VISITORS TO STEP BACK IN TIME AND EXPLORE THE LIFE AND TIMES OF NOBEL-PRIZE-WINNING AUTHOR JOHN STEINBECK.
<P>
TODAY'S VISITORS SAID THE CENTER WILL NOT ONLY BE A BIG DRAW FOR TOURISTS. IT'LL PUT SALINAS ON THE MAP.
<P>
A LOT OF PEOPLE. BEEN HERE ALL MY LIFE, PRIDE IN SALINAS, DON'T HAVE TO SAY FROM MONTEREY PENINSULA ANYMORE. I'M FROM SALINAS WHERE STEINBECK'S FROM.
<P>
SUPPORTERS ARE STILL TRYING TO RAISE  ABOUT A MILLION AND A HALF DOLLARS TO PAY FOR THE TEN MILLION DOLLAR FACILITY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Steinbeck events>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Steinbeck events</H3><BR>
AS JINAH MENTIONED.
<P>
THE DREAMHOUSE-GIVEAWAY AND THE WALK-THROUGH AREN'T THE ONLY THINGS GOING ON THIS STEINBECK-BIRTHDAY-WEEKEND.
<P>
TOMORROW. AT THE MONTEREY BAY AQUARIUM. THERE ARE TWO FREE SYMPOSIUMS ABOUT THE HISTORY OF CANNERY ROW AND JOHN STEINBECK'S LIFE.
<P>
THEN, AFTER THAT, THERE'S A BUS TOUR OF MONTEREY THAT COMES WITH A LUNCHEON, FROM 11:30 TO FOUR.  THAT ALSO MEETS AT THE AQUARIUM AND COSTS 45-DOLLARS.
<P>
AND ON SUNDAY. A HISTORIC GUIDED TOUR OF CANNERY ROW BEGINS AT 10 AM AT THE HERITAGE RAIL-CAR ON THE REC TRAIL AND GOES ON 'TILL FOUR. COST IS 10 DOLLARS.
<P>
AND ALL DAY, YOU CAN STOP BY ED "DOC" RICKETTS' LAB ALONG CANNERY ROW FOR A TOUR THERE.   THAT COSTS 15 DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Mty home lottery>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mty home lottery</H3><BR>
WELL. ANOTHER LUCKY SOON-TO-BE HOMEOWNER TO TELL YOU ABOUT TONIGHT. THOUGH HIS HOME WASN'T EXACTLY FREE.
<P>
THE CITY OF MONTEREY TONIGHT GAVE AWAY THIS HOME ON FIFTH STREET. AT THE EXCEPTIONALLY LOW PRICE OF 92-THOUSAND, 500 DOLLARS.
<P>
ELEVEN LOW-INCOME FAMILIES QUALIFIED FOR THE DRAWING. BUT THE HOME WILL GO TO MOHAMMED HABASHI.
<P>
HABASHI NOW HAS 60 DAYS TO SECURE FINANCING AND DO ALL THE PAPERWORK NECESSARY TO PURCHASE THE HOME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126West marine fine>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>West marine fine</H3><BR>
A LOCALLY BASED BOAT SUPPLY COMPANY FACES A HUGE FINE IF THE FEDERAL AVIATION ADMINISTRATION GETS ITS WAY.
<P>
THE F-A-A IS PROPOSING A 300-THOUSAND DOLLAR FINE AGAINST "WESTMARINE," FOR ALLEGEDLY SENDING HAZARDOUS MATERIALS VIA FEDERAL EXPRESS.
<P>
THE FEDERAL AGENCY CLAIMS WESTMARINE SENT ACETONE AND VARNISH ON A FEDERAL EXPRESS FLIGHT FROM HOLLISTER TO SEATTLE. WITHOUT IDENTIFYING THE SHIPMENT AS BEING HAZARDOUS.
<P>
THE F-A-A WAS NOTIFIED BY FEDERAL EXPRESS WORKERS IN PORTLAND WHO DISCOVERED THE SHIPMENT WAS DAMAGED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Dead Fetus>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dead Fetus</H3><BR>
MONTEREY COUNTY SHERIFF'S DEPUTIES MAKE A STARTLING DISCOVERY AT A HOME IN NORTH SALINAS.
<P>
A 7-MONTH OLD FETUS WRAPPED IN PLASTIC BAGS AND STUFFED IN A BEDROOM CLOSET.
<P>
DEPUTIES FOUND THE DEAD MALE FETUS. AFTER RECIEVING A REPORT OF A SUSPICIOUS INCIDENT.
<P>
THE MONTEREY COUNTY CORONER'S OFFICE SAYS THE BABY  HAD BEEN DEAD FOR ONLY ABOUT 24 HOURS. BUT IT WILL BE ABOUT A MONTH BEFORE THEY CAN DETERMINE IF THE BABY WAS STILL BORN OR DIED SHORTLY AFTER BIRTH.
<P>
VERY LITTLE INFORMATION IS BEING RELEASED BECAUSE THE BABY'S MOTHER. WHO IS NOT IN CUSTODY AT THIS TIME.  IS A JUVENILE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134Child beating susp>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Child beating susp</H3><BR>
A STOCKTON MAN. ACCUSED OF SEVERELY BEATING HIS GIRLFRIEND'S 2-YEAR-OLD DAUGHTER. IS NOW BACK IN THE SAN JOAQUIN COUNTY JAIL.
<P>
SALINAS POLICE ARRESTED 25 YEAR OLD ISAAC LOZA AT A HOUSE ON HOLMSTEAD AVENUE LAST NIGHT.
<P>
HE WAS TAKEN BACK TO SAN JOAQUIN COUNTY EARLY THIS MORNING.
<P>
THE CHILD IS STILL IN VERY CRITICAL CONDITION AT OAKLAND CHILDREN'S HOSPITAL.
<P>
LOZA IS EXPECTED TO BE CHARGED IN CONNECTION WITH THE  BEATING.
<P>
HIS CASE HAS BEEN CONTINUED UNTIL A LEGAL TEAM CAN BE ASSIGNED TO REPRESENT HIM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132Weiland arraign>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Weiland arraign</H3><BR>
THE MAN ACCUSED OF KILLING A C-H-P OFFICER IS SCHEDULED TO APPEAR IN COURT NEXT WEEK.
<P>
45-YEAR-OLD PETER WEILAND'S ARRAIGNMENT WAS SCHEDULED FOR TODAY. BUT WAS DELAYED UNTIL NEXT FRIDAY.
<P>
THAT'S SO WEILAND. WHO IS CURRENTLY IN THE SANTA CRUZ COUNTY JAIL FOR PROBATION VIOLATIONS. CAN FIND A PRIVATE ATTORNEY.
<P>
POLICE SAY WEILAND KILLED OFFICER SCOTT GREENLY LAST MONTH. WHEN HIS CAR SWERVED ON HIGHWAY 85 AND HIT THE OFFICER. WHILE HE WAS CONDUCTING A ROUTINE TRAFFIC STOP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Corralitos slide>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Corralitos slide</H3><BR>
FINALLY. MORE THAN TWO-HUNDRED RESIDENTS IN CORRALITOS ARE NO LONGER STRANDED IN THEIR HOMES.
<P>
LAST SATURDAY. A HUGE MUDSLIDE BLOCKED OFF EUREKA CANYON ROAD. TRAPPING RESIDENTS FOR NEARLY A WEEK.
<P>
SANTA CRUZ COUNTY CONTRACTED WITH GRANITE CONSTRUCTION COMPANY TO MAKE A TEMPORARY BRIDGE.
<P>
THE PILE OF RUBBLE WAS LEVELED, THEN COVERED WITH FALLEN TREE STUMPS, MUD, PLASTIC SHEETING AND ROCK.   
<P>
"I work over in Silicon Valley, and the company I work for has been very understanding, but it's been stressful."
<P>
"You know, thanks to the county's negligence over the years, this is what happens.'
<P>
THE ONE-LANE ROAD IS ONLY OPEN TO RESIDENTS AND EMERGENCY VEHICLES AT THIS TIME, BUT MOST PEOPLE LIVING THERE SAY IT'S A RELIEF TO NO LONGER BE ISOLATED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Hwy 129 closed>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hwy 129 closed</H3><BR>
ANOTHER ROAD CLOSED DUE TO MUDSLIDES ON THE CENTRAL COAST IS EXPECTED TO REOPEN TOMORROW.
<P>
AROUND FOUR THIS MORNING MUD AND DEBRIS CAME TUMBLING ONTO HIGHWAY 129.
<P>
CREWS WERE ALREADY CLEANING THE ROADWAY BETWEEN ROGGE AND CARLTON ROADS WHEN THE EROSION OCCURRED.
<P>
WORKERS SAY EVERY TIME THEY CLEAR DIRT AWAY, MORE COMES DOWN.
<P>
CALTRANS SAYS THEY'LL BE BUSY ALL NIGHT IN ORDER TO HAVE THE HIGHWAY OPEN BY MORNING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Hwy 101 delays>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hwy 101 delays</H3><BR>
MORE ROAD DELAYS ARE EXPECTED TOMORROW ON HIGHWAY 1-0-1.
<P>
CREWS WILL CONTINE WORKING ON THE ROAD IN SOLEDAD.
<P>
TRAFFIC WILL BE DOWN TO ONE LANE IN BOTH DIRECTIONS.
<P>
CALTRANS SAYS ONE LANE OF THE HIGHWAY WILL ALSO BE SHUT DOWN FROM THE RED BARN , NORTH OF PRUNEDALE, TO THE SAN BENITO COUNTY LINE.
<P>
EXPERTS SUGGEST TAKING AN ALTERNATE ROUTE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129NPS river satellite>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NPS river satellite</H3><BR>
THERE'S NOW A WEB SITE WITH STORM INFORMATION AND RIVER LEVELS.
<P>
THE NAVAL POST GRADUATE SCHOOL HAS CREATED A WEB PAGE, WHICH SHOWS WATERWAY LEVELS IN CALIFORNIA, INCLUDING THE SALINAS AND RUSSIAN RIVERS.
<P>
THESE IMAGES ARE FROM FEBRUARY NINTH DURING HEAVY RAINFALL.
<P>
THE PICTURES ARE MADE POSSIBLE BY NOAA'S HIGH RESOLUTION RADIOMETER SATELLITE.
<P>
RESEARCHERS ARE HOPING TO LEARN MORE ABOUT THE FLOW OF SEDIMENT CAUSED BY STORMS.
<P>
IF YOU'D LIKE TO SEE THE WEB PAGE FOR YOURSELF. THE ADDRESS IS SHOWN HERE ON THE SCREEN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/wilson new jobs>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/wilson new jobs</H3><BR>
GOOD NEWS FOR FOLKS LOOKING FOR A JOB IN CALIFORNIA.
<P>
LAST YEAR SAW THE HIGHEST STATE JOB GROWTH IN 13 YEARS.
<P>
THAT'S NEARLY HALF A MILLION NEW JOBS.
<P>
        AT THE SAME TIME, THE STATE'S UNEMPLOYMENT RATE WAS THE LOWEST IT'S BEEN IN SEVEN YEARS.
<P>
JOB GAINS WERE STRONGEST IN THE SERVICE INDUSTRIES. SUCH AS CONSTRUCTION WHERE MORE THAN 200-THOUSAND JOBS WERE CREATED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(lockerbie) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(lockerbie) </H3><BR>
AND THE MEN ACCUSED OF BOMBING PAM-AM FLIGHT 103. ARE ONE STEP CLOSER TO TRIAL. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A MAN GOES ON A RAMPAGE IN A TINY COLORADO TOWN. TEARING UP BUILDINGS, BURNING A HOUSE, AND KILLING THE TOWN'S FORMER MAYOR.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(town rampage)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(town rampage)</H3><BR>
A PART-TIME SNOWPLOW DRIVER HAS CONFESSED TO A SPREE IN WHICH HE KILLED THE FORMER MAYOR OF ALMA, COLORADO. THEN TORE INTO SOME GOVERNMENT BUILDINGS WITH A STOLEN FRONT-END LOADER. 
<P>
POLICE SAY THE MAN SHOT THE FORMER MAYOR.THEN RAMMED THE LOADER INTO THE FIRE HOUSE, POST OFFICE AND WATER TREATMENT PLANT. KNOCKING OUT WATER SERVICE AND SENDING THOUSANDS OF GALLONS OF WATER POURING INTO THE STREETS. 
<P>
STILL NO WORD ON WHAT SPARKED THE RAMPAGE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(vampire kid senten)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(vampire kid senten)</H3><BR>
A TEENAGER CONVICTED OF KILLING A FRIEND'S PARENTS. AS PART OF A VAMPIRE CULT RITUAL. HAS BEEN SENTENCED TO DEATH.
<P>
17-YEAR OLD ROD FERRELL IS THE FIRST OF SEVERAL TEENS TO FACE TRIAL FOR KILLING THE COUPLE WITH A CROW BAR IN 19-96.
<P>
INVESTIGATORS SAY MEMBERS OF THE SO-CALLED VAMPIRE CULT. INCLUDING THE MURDERED COUPLE'S DAUGHTER. TOOK DRUGS. ENGAGED IN GROUP SEX AND DRANK EACH OTHER'S BLOOD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(obese trial folo)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(obese trial folo)</H3><BR>
THE CALIFORNIA MOTHER. WHO WAS CONVICTED OF ABUSING HER OVERWEIGHT TEENAGE DAUGHTER. WILL PAY FOR HER CRIME WITH HARD WORK.  
<P>
MARLENE CORRIGAN WAS SENTENCED TODAY TO 240 HOURS 
<P>
OF COMMUNITY SERVICE. 
<P>
THE JUDGE SAYS IT'S THE SAME PUNISHMENT AS THIRTY DAYS IN JAIL. 
<P>
LAST MONTH. CORRIGAN WAS CONVICTED OF MISDEMEANOR CHILD ABUSE. AFTER THE DEATH OF HER 680 POUND 13-YEAR-OLD DAUGHTER, CHRISTINA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Lockerbie ruling>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lockerbie ruling</H3><BR>
THE WORLD'S HIGHEST COURT IS STEPPING IN TO THE DEADLOCKED TRIAL OF TWO LIBYAN TERRORISTS.
<P>
THE WORLD COURT RULED TODAY THAT IT CAN INTERVENE IN THE EXTRADITION OF THE TWO MEN SUSPECTED OF BOMBING PAN-AM FLIGHT 103 IN 19-88, WHERE 270 PEOPLE DIED.
<P>
LIBYA, THE UNITED STATES AND BRITAIN HAVE BEEN FIGHTING OVER THE MEN'S EXTRADITION FOR YEARS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/PAN AM>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/PAN AM</H3><BR>
15-HUNDRED PAN AM AIRLINE WORKERS ARE WITHOUT JOBS TODAY. AFTER THE MIAMI, FLORIDA-BASED COMPANY FILED FOR BANKRUPTCY.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
ACCORDING TO THE COMPANY. THE AIRLINE DOESN'T HAVE THE ABILITY TO KEEP THE BUSINESS RUNNING WITH 50-MILLION DOLLARS IN ASSETS. AND 147-MILLION DOLLARS IN DEBTS.
<P>
THE CORPORATION'S TWO MAIN AIRLINE UNITS FILED FOR BANKRUPTCY. JUST A WEEK AFTER THE COMPANY ANNOUNCED IT WOULD LAY OFF 225 EMPLOYEES. GROUND TWO OF IT'S PLANES. AND CUT BACK ROUTES. 
<P>
THE AIRLINE CARRIED ABOUT 5-THOUSAND PASSENGERS DAILY TO 14 CITIES. INCLUDING FLORIDA, PUERTO RICO AND CITIES IN THE NORTHEAST AND MIDWEST.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
AT LONG LAST THE BASEBALL SEASON IS HERE. THE NATIONAL LEAGUE'S WESTERN DIVISION CHAMPION SAN FRANCISCO GIANTS PLAY THEIR FIRST CACTUS LEAGUE GAME TODAY.
<P>
IT MAY NOT COUNT IN THE STANDINGS, BUT WITH ALL THE RAIN WE'VE HAD, ANY SIGN OF SPRING, IS A WELCOME SIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Harry Caray>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Harry Caray</H3><BR>
IN OTHER, BUT SADDER BASEBALL NEWS, TODAY 2000-PEOPLE FILLED THE HOLY NAME CATHEDRAL IN CHICAGO TO SAY THEIR GOODBYE'S TO HALL OF FAME BROADCASTER HARRY CARAY.
<P>
HIS GRANDSON CHIP, WHO WILL JOIN THE CUBS BROADCAST TEAM THIS YEAR, WAS A PALL-BAYER. HIS SON SKIP, A BROADCASTER FOR THE BRAVES, WAS IN THE FRONT ROW.
<P>
MANY OF CHICAGO'S SPORTS ELITE WERE ON HAND.
<P>
CARAY COLLAPSED AT A VALENTINE'S DAY DINNER WHILE IN PALM SPRINGS, HE DIED A FEW DAYS LATER AT THE AGE OF 83.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
TO HOOPS, AND THE WARRIORS HAVE RETURNED TO EARTH.
<P>
A COUPLE OF NIGHTS AGO, THEY TEASED US WITH A WIN AT MADISON SQUARE GARDEN.
<P>
BUT THEN LAST NIGHT THEY GOT PUMMELLED IN WASHINGTON, AND TONITE ITS MORE OF THE SAME IN BOSTON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
TO GOLF, AND THE SKIES ARE CLEAR AGAIN FOR THE 2ND ROUND OF THE L.A./NISSAN OPEN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140NFL>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NFL</H3><BR>
DURING HIS 10-YEAR NFL CAREER, SAN DIEGO CHARGERS QUARTERBACK STAN HUMPHRIES WAS KNOWN FOR PLAYING WITH A LOT OF HEART, AND PLAYING THROUGH A LOT OF INJURIES.
<P>
BUT WHEN THE INJURIES WERE INFLICTED ON HIS HEAD, HUMPHRIES KNEW HE'D HAD ENOUGH.
<P>
TODAY HUMPHRIES ANNOUNCES HIS RETIREMENT, CITING THE DAMAGE DONE BY THE  4-CONCUSSIONS HE SUFFERED OVER AN 18-MONTH PERIOD AS THE MAIN REASON.
<P>
HUMPHRIES IS THE ONLY CHARGER QUARTERBACK TO LEAD THE TEAM TO THE SUPER BOWL, WHICH THEY LOST 49-26 TO SAN FRANCISCO.
<P>
AT AGE 32, HUMPHRIES STILL SUFFERS HEADACHES FROM THOSE CONCUSSIONS, BUT IT WAS STILL HARD FOR HIM TO SAY GOODBYE TO FOOTBALL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50cop tipping>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>cop tipping</H3><BR>
NOT LEAVING A TIP AT THE RED LOBSTER IN SALINAS COULD GET YOU ARRESTED TONIGHT.
<P>
BUT PROBABLY NOT. THESE ENTERPRISING OFFICERS ARE TAKING A BREAK FROM NABBING BAD GUYS. TO WAIT TABLES FOR CHARITY.
<P>
MEMBERS OF THE SALINAS POLICE, MONTEREY COUNTY SHERIFF'S AND DEPARTMENT OF CORRECTIOINS SERVED CUSTOMERS AT THE RESTAURANT.
<P>
THE MONEY GIVEN TO THE OFFICERS AS TIPS WILL BE DONATED TO THE MONTEREY REGION OF THE SPECIAL OLYMPICS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139weekend movies-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>weekend movies-I</H3><BR>
LAUGHING AT THE TRIBAL INSTINCT AND LOOKING INTO SOME FUTURE CHILLS AND THRILLS. 
<P>
FOX'S BILL MCCUDDY PREVIEWS SOME WEEKEND MOVIES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Kids News>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kids News</H3><BR>
HELLO. I'M ALAN MARSDEN WITH K-C-B-A KIDS' NEWS.
<P>
WHAT'S THE BIGGEST PRIZE YOU'VE EVER WON?  WELL JUST IMAGINE WINNING A WHOLE HOUSE!
<P>
KAUFMAN AND BROAD. ALONG WITH OTHER PEOPLE WHO HELP BUILD HOUSES. GOT TOGETHER TO RAISE MONEY FOR THE NEW NATIONAL STEINBECK CENTER IN SALINAS.
<P>
THEY CONSTRUCTED A HOUSE. AND SOLD THOUSANDS OF RAFFLE TICKETS FOR TEN DOLLARS A PIECE. TO PEOPLE WHO HOPED TO WIN THE HOUSE.
<P>
THE EXCITING DRAWING FINALLY HAPPENED ON FRIDAY NIGHT. THEY PICKED THE LUCKY WINNER'S NAME OUT OF A BIG BARREL. FILLED WITH THE 30-THOUSAND TICKETS.
<P>
BUT IT WAS THE ONE PURCHASED BY MRS. EDUVIJES ROSALES OF SALINAS THAT WAS PULLED FROM THE PILE.
<P>
SHE NOW GETS TO MOVE HER FAMILY INTO THIS BEAUTIFUL NEW FIVE BEDROOM HOME.
<P>
SO  CONGRATULATIONS TO MRS. ROSALES.
<P>
AND CONGRATULATIONS TO THE NATIONAL STEINBECK CENTER WHICH RAISED NEARLY HALF A MILLION DOLLARS.
<P>
AND THAT'S KIDS NEWS. HAVE A GREAT DAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
