<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Wednesday, 3/25/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Wednesday, 3/25/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x032514.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (Tornado)>TS1 (Tornado)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139School shoot folo-IN>School shoot folo-IN</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145School shoot folo-T>School shoot folo-T</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Gilroy Tornado-INT>Gilroy Tornado-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Gilroy Tornado-GU>Gilroy Tornado-GU</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(Troy Aikman fire)>(Troy Aikman fire)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Gilroy Tornado-TA>Gilroy Tornado-TA</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(trains collide)>(trains collide)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118So Cal mudslides>So Cal mudslides</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146(assisted suicide)>(assisted suicide)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#147Mo Co OES mtg>Mo Co OES mtg</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/space tours>Fox Biz/space tours</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Phase 4 water>Phase 4 water</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126MoCo vets cemetary>MoCo vets cemetary</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Cactus League>Cactus League</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Salinas gas leak>Salinas gas leak</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#148Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Rancho Chualar II>Rancho Chualar II</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129SC flouridation>SC flouridation</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45NFL>NFL</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(school shoo) >Bump 1(school shoo) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(Aikman fire) >bump 2(Aikman fire) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Jason project>Jason project</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=134TS1 (Tornado)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (Tornado)</H3><BR>
K-C-B-A FOX NEWS IS COMING YOUR WAY NEXT.
<P>
A POWERFUL STORM BRINGS HEAVY RAIN. HAIL. AND A TORNADO TO THE CENTRAL COAST TODAY. THAT'S RIGHT A TORNADO. WE'LL HAVE THE DETAILS.
<P>
AND AN ARKANSAS TOWN IS STILL IN SHOCK FOLLOWING YESTERDAY'S DEADLY SCHOOL YARD SHOOTING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
SAN BENITO COUNTY RESIDENT AFFECTED BY THAT  TORNADO THAT SANDHYA MENTIONED. STILL CAN'T BELIEVE WHAT HIT THEM.
<P>
OUR CHERI GYURO HAS BEEN ON THE SCENE. 
<P>
SHE JOINS US LIVE WITH ALL THE DETAILS.
<P>
CHERI. WHAT DID THE TWISTER DO?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Gilroy Tornado-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gilroy Tornado-INT</H3><BR>
ALAN.THERE'S A LOT OF DESTRUCTION ON FRAZIER LAKE ROAD NEAR HOLLISTER.DOWNED POWER LINES AND A HUGE GREENHOUSE THAT WAS DEMOLISHED.
<P>
A SIGHT THAT MADE MANY AREA RESIDENTS NERVOUS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Gilroy Tornado-GU>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gilroy Tornado-GU</H3><BR>
THIS IS THE AFTERMATH.THE PATH OF DESTRUCTION WENT AN EIGHTH OF A MILE BUT THE TRACKS FROM THE TORNADO WENT ON FOR ACRES.
<P>
AT ABOUT TWO THIS AFTERNOON.SEVERAL PEOPLE SPOTTED A FUNNEL CLOUD NEAR FRAZIER LAKE ROAD JUST OUTSIDE OF HOLLISTER.
<P>
ONE RESIDENT CAPTURED THE DRAMATIC TWISTER ON HOME VIDEO.
<P>
RICH. WITH THE SAN BENITO FIRE DEPARTMENT WAS RETURNING FROM A CALL WHEN HE SPOTTED THE FUNNEL CLOUD. 
<P>
THE NATIONAL WEATHER SERVICE CONFIRMS THAT THE FUNNEL TOUCHED DOWN.
<P>
THIS WAS THE END RESULT.A HUGE GREENHOUSE FLATTENED WITH DEBRIS SCATTERED EVERYWHERE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Gilroy Tornado-TA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gilroy Tornado-TA</H3><BR>
SAN BENITO COUNTY RESIDENTS WEREN'T THE ONLY ONES WATCHING THE CLOUDS WITH A NERVOUS EYE.
<P>
FOLKS IN EAST WATSONVILLE.SALINAS AND MONTEREY ALL REPORT SPOTTING FUNNEL CLOUDS THAT DIDN'T TOUCH THE GROUND.
<P>
REPORTING LIVE I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118So Cal mudslides>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>So Cal mudslides</H3><BR>
HEAVY RAINS ALSO HIT SOUTHERN CALIFORNIA TODAY. THREATENING TO SEND MORE HOMES TUMBLING DOWN MOUNTAIN SIDES.
<P>
ROCKS AND MUD WERE LEAVING POOLS OF WATER 
<P>
ALL OVER ROADS. IN AND AROUND LOS ANGELES. 
<P>
AREAS IN THAT PART OF THE STATE HAVE RECEIVED UP TO FOUR INCHES OF RAIN.
<P>
SOME ROADS ARE CLOSED BECAUSE OF FLOODING. INCLUDING THE PACIFIC COAST HIGHWAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=147Mo Co OES mtg>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mo Co OES mtg</H3><BR>
THE OFFICE OF EMERGENCY SERVICES HAD GOOD NEWS FOR RESIDENTS OF LAS LOMAS TONIGHT. THEIR HOUSES MAY SOON STOP SLIDING DOWN THE HILLSIDE.
<P>
THE RAIN SOAKED HILLSIDE BEGAN SLIDING IN FEBRUARY. FORCING THE FAMILIES OUT.
<P>
TONIGHT O-E-S MET WITH RESIDENTS OF THE 12 HOUSES AFFECTED. TO SHARE GOOD NEWS FROM A RECENT STUDY.
<P>
IN: "BASICALLY THERE ARE A VARIETY OF FIXES." OC: "WHAT STEPS TO GET BACK INTO INDIVIDUAL HOUSES."
<P>
ENGINEERS SAY IT WILL STILL BE SEVERAL MONTHS BEFORE THE RESIDENTS CAN MOVE BACK INTO THE HOUSES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Phase 4 water>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Phase 4 water</H3><BR>
HEAVY RAINS THIS WINTER HAVE FILLED RESERVOIRS AND HELPED RE-GENERATE UNDERGROUND SUPPLIES. 
<P>
BUT FOLKS ON THE PENINSULA AND IN CARMEL. ARE STILL BEING ASKED TO RATION THEIR WATER.
<P>
THAT'S BECAUSE ENVIRONMENTALISTS WON A SUIT AGAINST THE WATER COMPANY WHICH RESTRICTS PUMPING OF ITS WELLS TO PROTECT THE ENVIRONMENT. 
<P>
CAL AM WAS SUPPOSED TO CUT BACK TO 20 PERCENT. 
<P>
THEY CAME UP SHORT LAST YEAR AND WERE FINED. BY THE STATE. 
<P>
NOW THE COMPANY IS IMPLEMENTING STRICTER RESTRICTIONS. AND PENALTIES IF PEOPLE DON'T COMPLY.  
<P>
THE METER WILL RESTRICT THE FLOW FROM 20 GALLONS A MINUTE TO SIX. 
<P>
CAL AM SAYS THE RATIONING IS NOT COMPLICATED. IT'S MOSTLY COMMON SENSE. LIKE NOT WATERING BETWEEN 9 AND FIVE AND USING A HOSE VALVE THAT SHUTS OFF. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126MoCo vets cemetary>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>MoCo vets cemetary</H3><BR>
HOPES FOR A VETERANS CEMETERY ON THE CENTRAL COAST MAY SOON BECOME A REALITY.
<P>
BACKERS OF THE IDEA. JUMPED THE FIRST LEGISLATIVE HURDLE YESTERDAY.
<P>
THE SENATE COMMITTEE PASSED A BILL BY SENATOR BRUCE MCPHERSON.
<P>
IT MEANS. THE STATE WILL BEGIN A FEASIBILITY STUDY TO SEE JUST HOW MUCH IT WOULD COST TO BUILD A VETERAN'S CEMETERY AT THE FORMER FORT ORD.
<P>
THE PROPOSED VETERANS CEMETERY WOULD GO ON 160 ACRES OF LAND ON ARTILLERY HILL.
<P>
THAT PROPERTY IS ESTIMATED TO BE WORTH AS MUCH AS 15-MILLION DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Salinas gas leak>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas gas leak</H3><BR>
DOZENS OF EAST SALINAS RESIDENTS HAD TO EVACUATE THEIR HOMES THIS MORNING AFTER A GAS LINE BREAKS IN THIER NEIGHBORHOOD.
<P>
IT HAPPENED ON THE CORNER OF SIEBER AND GARNER STREETS AT ABOUT 8:30.
<P>
THE SALINAS FIRE DEPARTMENT OFFICIALS SAY CONSTRUCTION CREWS RUPTURED THE TWO-INCH LINE.
<P>
FIRE FIGHTERS. AND POLICE OFFICERS  QUICKLY EVACUATED RESIDENTS FROM TWO NEARBY APARTMENT BUILDINGS.
<P>
P-G-AND-E CREWS SEALED THE GAS LINE ABOUT AN HOUR LATER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Rancho Chualar II>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rancho Chualar II</H3><BR>
A PETITION DRIVE TO PUT A STOP TO THE CONTROVERSIAL SOUTH MONTEREY COUNTY DEVELOPMENT RANCHO CHUALAR TWO APPEARS TO HAVE BEEN SUCCESSFUL.
<P>
THE BOARD OF SUPERVISORS NARROWLY APPROVED THE PROJECT. THAT WOULD MORE THAN DOUBLE THE SIZE OF CHUALAR.
<P>
BUT OPPONENTS HAVEN'T GIVEN UP.
<P>
THEY SAY THEY'VE COLLECTED MORE THAN 17-THOUSAND. FIVE HUNDRED SIGNATURES.
<P>
THAT'S NEARLY DOUBLE THE 92-HUNDRED WHICH ARE REQUIRED TO PUT THE ISSUE ON THE BALLOT.
<P>
NOW THE REGISTRAR OF VOTERS OFFICE WILL VALIDATE THE PETITIONS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129SC flouridation>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC flouridation</H3><BR>
AN UPDATE NOW ON THE FLOURIDE ISSUE IN SANTA CRUZ.
<P>
LATE LAST NIGHT. THE CITY COUNCIL VOTED 6-TO-1 TO REJECT THE STATE MANDATE TO PUT FLOURIDE IN THE TOWN'S WATER SUPPLY.
<P>
MAYOR CELIA SCOTT SAYS THE ISSUE COULD STILL GO TO VOTERS. IF THE STATE WANTS TO COME UP WITH THE FUNDS TO ENFORCE IT.
<P>
CITIZENS FOR SAFE DRINKING WATER LOBBIED AGAINST FLUORIDATION. AND SAY THEY ARE HAPPY WITH THE DECISION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(school shoo) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(school shoo) </H3><BR>
COMING  UP ON FOX NEWS FIRST AT TEN.
<P>
A TOWN IN ARKANSAS STRUGGLES TO UNDERSTAND WHY TWO YOUNG BOYS OPENED FIRE ON CLASSMATES. KILLING FIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(Aikman fire) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(Aikman fire) </H3><BR>
AND. THE MANSION OWNED BY DALLAS COWBOYS QUARTERBACK TROY AIKMAN GOES UP IN FLAMES.
<P>
THOSE STORIES RIGHT AFTER THIS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139School shoot folo-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>School shoot folo-IN</H3><BR>
THE QUESTIONS LINGER OVER WHY FIVE PEOPLE WERE KILLED IN AN ARKANSAS SCHOOLYARD YESTERDAY. 
<P>
FOX'S BRET BAIER HAS THE STORY ABOUT HOW THE COMMUNITY OF JONESBORO IS COPING WITH THIS SHOCKING TRAGEDY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145School shoot folo-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>School shoot folo-T</H3><BR>
THE TRAGEDY IN JONESBORO IS PROVING TO BE NO ISOLATED INCIDENT. 
<P>
HERE IN CALIFORNIA TODAY.  IN DALY CITY.
<P>
A 14-YEAR-OLD BOY WAS ARRESTED AFTER ALLEGEDLY SHOOTING AT HIS SCHOOL PRINCIPAL. 
<P>
OFFICIALS SAY THE BOY WAS UPSET OVER BEING SENT HOME. 
<P>
THE SHOT. FROM A SMALL HANDGUN. MISSED. AND NO ONE WAS HURT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
TROY AIKMAN'S MANSION CATCHES FIRE. CAUSING MORE THAN A QUARTER MILLION DOLLARS IN DAMAGES.
<P>
THAT STORY FROM PLANO, TEXAS. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(Troy Aikman fire)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Troy Aikman fire)</H3><BR>
THE THREE-ALARM BLAZE BROKE OUT IN THE GARAGE AREA OF AIKMAN 12-THOUSAND SQUARE-FOOT HOME EARLY THIS MORNING.
<P>
NO ONE WAS HURT. 
<P>
ACCORDING TO A FIRE DEPARTMENT SPOKESWOMAN. THE DAMAGE WAS CONFINED MOSTLY TO THE GARAGE AREA.     
<P>
FIRE FIGHTERS SAY THEY WERE ABLE TO SAVE MOST OF
<P>
AIKMAN'S PRIZED FOOTBALL MEMORABILIA.
<P>
STILL NO WORD ON THE CAUSE. BUT INVESTIGATOR'S DON'T SUSPECT FOUL PLAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(trains collide)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(trains collide)</H3><BR>
A TRAIN WRECK EARLY THIS MORNING NEAR FT. WAYNE INDIANA. LEAVES ONE CREW MEMBER DEAD.  
<P>
A NORFOLK SOUTHERN FREIGHT TRAIN AND A CONRAIL TRAIN WERE TRAVELING TOWARD EACH OTHER ON THE SAME TRACK WHEN THEY COLLIDED.
<P>
A NATIONAL TRANSPORTATION SAFETY BOARD TEAM. IS  INVESTIGATING THE CAUSE OF THE CRASH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146(assisted suicide)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(assisted suicide)</H3><BR>
IN PORTLAND, OREGON.  
<P>
ASSISTED-SUICIDE ADVOCATES SAY AN ELDERLY WOMAN WITH BREAST CANCER. HAS BECOME THE FIRST PERSON TO MAKE USE OF THE STATE'S "DEATH WITH DIGNITY" ACT. 
<P>
IT ALLOWS DOCTORS TO PRESCRIBE LETHAL DRUGS TO TERMINALLY-ILL PATIENTS WITH LESS THAN 6-MONTHS TO LIVE. 
<P>
THE ORGANIZATION "COMPASSION IN DYING" SAYS THE WOMAN RECORDED A STATEMENT ABOUT WHAT SHE WAS PLANNING TO DO. JUST BEFORE SHE TOOK A LETHAL DOSE OF BARBITURATES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/space tours>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/space tours</H3><BR>
NIAGARA FALLS. THE GRAND CANYON. AND. THE MOON.?  IT'S THE LATEST CRAZE IN THE TOURISM INDUSTRY.
<P>
WE'LL TAKE YOU THERE IN TONIGHT'S FOX BUSINESS REPORT.
<P>
THE TRAVEL BUSINESS IS BOOMING. TO THE TUNE OF 400-BILLION DOLLARS A YEAR. IN THE U-S ALONE.
<P>
BUT SOME ARE LOOKING SKYWARD. INTO SPACE. FOR A DIFFERENT KIND OF TRAVEL EXPERIENCE.
<P>
ACCORDING TO A JOINT STUDY BY THE SPACE TRANSPORTATION ASSOCIATION AND NASA. THE PUBLIC WILL ONE DAY BE ABLE TO TRAVEL INTO SPACE.
<P>
OVER THE NEXT TEN YEARS. THE ASSOCIATION WILL LOOK AT WAYS TO GIVE ADVENTURERS WHAT COULD BE THE ULTIMATE EXPERIENCE.
<P>
AS YOU MIGHT EXPECT. IT WON'T BE CHEAP. PROBABLY STARTING IN THE MILLIONS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
THE STANFORD CARDINAL BASKETBALL TEAM, HAS LEFT THE BAY AREA, AND IS NOW IN SAN ANTONIO.
<P>
THIS IS STANFORD'S FIRST FINAL FOUR APPEARANCE SINCE 1942, AND THEY ARE GOING TO ENJOY IT.
<P>
THIS WAS THE SCENE ON THE PALO ALTO CAMPUS TODAY. ALL THE FANFARE AS THE TEAM BOARDS THE BUS TO THE AIRPORT AND THE FLIGHT TO TEXAS.
<P>
SANTA CRUZ NATIVE AND HARBOR HIGH GRAD TIM YOUNG, LOOKING FOR HIS FEED BAG. AT 7 FOOT 1, YOU NEED TO MAKE SURE YOU GET THE FULLEST ONE.
<P>
AND THE GUYS REALLY APPRECIATED THE WARM SENDOFF.
<P>
SO ITS STANFORD VS. KENTUCKY, SATURDAY AT 2:42 PACIFIC TIME. SHOULD BE A GOOD ONE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Cactus League>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cactus League</H3><BR>
WE CONTINUE OUR CACTUS LEAGUE REPORTS TONIGHT WITH A LOOK AT THE GIANTS PITCHING STAFF.
<P>
ITS A GROUP THAT FEATURES A MIX OF YOUTH AND EXPERIENCE HIGHLIGHTED BY, DARE I SAY,  A COUPLE OF FORMER DODGERS.
<P>
ZANE TABARI HAS OUR STORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=148Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
THANKS ZANE, MEANWHILE TODAY AT SPRING TRAINING, ITS THE GIANT HITTERS THAT ARE LOOKING GOOD.
<P>
J.T. SNOW COMING UP WITH THE BIG 3-RUN HOMER OFF OF FELIPE LIRA. SNOW HAS 5-RBI'S ON THE DAY.
<P>
AND LATER RICH AURILLA SINGLES IN A RUN, MAKES IT 6-NOTHING.
<P>
BUT THE GIANTS WOULD LOSE THIS SLUGFEST BY A SCORE OF 17 TO 12.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
MEANWHILE THE A'S TAKE ON THE PADRES AT PHOENIX MUNI.
<P>
SAN DIEGO'S KEN CAMINITI GOES DEEP AND OUT. CAMINITI HOMERS FOR THE 2ND STRAIGHT DAY.
<P>
BUT THE A'S JASON GIAMBI DOES HIM ONE BETTER. GIAMBI BELTS 2-HOME RUNS TODAY. THAT GIVES HIM THREE FOR THE SPRING.
<P>
HOWEVER THE PADRES WIN THEIR SIXTH STRAIGHT, BY A FINAL OF 9 TO 8.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45NFL>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NFL</H3><BR>
THE NFL OWNERS MEETINGS  WRAPPED UP TODAY, AND FOR THE 7TH STRAIGHT YEAR, INSTANT REPLAY WAS VOTED DOWN, COMING UP 2-VOTES SHORT.
<P>
NOT SINCE 1991 HAVE REFS HAD THE SAFETY NET OF TELEVISION REPLAYS TO MAKE SURE THEY GET THE CALLS RIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
AND FINALLY, GOLF'S SO CALLED 5TH MAJOR CHAMPIONSHIP TAKES PLACE THIS WEEK IN PONTE VEDRA, FLORIDA. ITS THE 25TH PLAYERS CHAMPIONSHIP.
<P>
BUT FOR JOHN DALY, THIS IS HIS FIRST ANNIVERSARY OF SORTS.
<P>
IT WAS FOLLOWING A BAD ROUND AT LAST YEAR'S PLAYERS CHAMPIONSHIP THAT DALY WENT ON A DRINKING BINGE, THAT TURNED VIOLENT.
<P>
AS A RESULT OF THE INCIDENT, DALY CHECKED IN TO THE BETTY FORD CENTER, AND HAS SINCE TURNED HIS LIFE AROUND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Jason project>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jason project</H3><BR>
A PROGRAM COMBINING OCEAN RESEARCH WITH EDUCATION
<P>
WRAPS UP THIS WEEK IN MONTEREY BAY.
<P>
        THIS PROJECT IS HEADED UP BY DR. ROBERT BALLARD. THE MAN WHO DISCOVERED THE WRECK OF TITANIC.
<P>
        IT INCORPORATES LIVE TELEVISION BROADCASTS FROM
<P>
ON-BOARD THE NOAA RESEARCH SHIP, MCARTHUR.  FROM ROBERT BALLARD AT THE MONTEREY BAY AQUARIUM. AND FROM DIVERS IN MONTEREY BAY AND BURMUDA.
<P>
ALL CARRIED LIVE OVER THE INTERNET. TO SOME 2-MILLION
<P>
SCHOOL CHILDREN.
<P>
"THE WHOLE IDEA OF JASON IS TO EXCITE STUDENTS TO ENTER FIELD 
<P>
FIELDS OF SCIENCE AND TECHNOLOGY. 
<P>
THEY'RE HAVING TROUBLE ATTRACING EMPLOYEES FOR THE 21ST CENTURY
<P>
HIGH TECH WORK FORCE.
<P>
        THE MCARTHUR WILL BE ANCHORED IN MONTEREY BAY 
<P>
THROUGH FRIDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
