<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Thursday, 3/12/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 3/12/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Bilingual ed >Bilingual ed </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Mini-mart shoot-INT>Mini-mart shoot-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Girls Education-INT>Girls Education-INT</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Mini-mart shoot-GU>Mini-mart shoot-GU</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Mini-mart shoot-TA>Mini-mart shoot-TA</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(ramsey grand jury)>(ramsey grand jury)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Del Ray woods susp>Del Ray woods susp</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(cubans rescued)>(cubans rescued)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Salinas drug bust>Salinas drug bust</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(school fire)>(school fire)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Carnahan Mom-INT>Carnahan Mom-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Asteroid expected>Asteroid expected</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Carnahan Mom-GU>Carnahan Mom-GU</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/highway>Fox Biz/highway</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#147Carnahan Mom-TAG>Carnahan Mom-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Prep Basketball>Prep Basketball</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Mo Co Court secrur>Mo Co Court secrur</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41NCAA Tourney>NCAA Tourney</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Coastal commission>Coastal commission</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145Sprewell>Sprewell</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Al Gore in SJ>Al Gore in SJ</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/pac bell>Good News/pac bell</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Gator garb disposal>Gator garb disposal</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=106TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
POLICE TONIGHT ARE LOOKING FOR A MURDERER WHO KILLED ONE TEENAGER AND SERIOUSLY WOUNDED ANOTHER.
<P>
IT HAPPENED THIS AFTERNOON IN BROAD DAYLIGHT. NEAR A BUSY SALINAS SHOPPING CENTER.
<P>
JINAH KIM JOINS US NOW LIVE FROM THE SCENE OF THE CRIME WITH THE LATEST.
<P>
JINAH. DO POLICE KNOW WHO MAY HAVE DONE THIS?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Mini-mart shoot-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mini-mart shoot-INT</H3><BR>
NO ALAN. NO ONE'S BEEN ARRESTED. AND THE LAST WE CHECKED. DETECTIVES WERE STILL ASKING FOR ANY WITNESSES TO COME FORWARD AND HELP THEM CATCH THE KILLER.
<P>
THIS IS WHAT HAPPENED. 18-YEAR OLD JOSE GARCIA WAS DRIVING OUT OF THIS SHOPPING CENTER WITH HIS FRIEND ALEJANDRO MARTINEZ WHEN A LONE GUNMAN RAN UP AND FIRED THOSE FATAL SHOTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Mini-mart shoot-GU>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mini-mart shoot-GU</H3><BR>
JUST BEFORE 3:30 THIS AFTERNOON, JOSE GARCIA BRIEFLY STOPPED BY HIS WORKPLACE, COMM SOURCE VIDEO IN EAST SALINAS.
<P>
HE WAS LEAVING THE SHOPPING CENTER WITH A FRIEND. WHEN A MAN WALKED UP TO THEIR CAR AND FIRED HIS GUN.
<P>
THAT DRIVER, 18-YEAR OLD ALEJANDRO MARTINEZ, WAS TAKEN TO THE HOSPITAL IN SERIOUS CONDITION.
<P>
THE GUNMAN FLED ON FOOT AND WAS GONE BY THE TIME POLICE ARRIVED.
<P>
DISTRAUGHT FAMILY MEMBERS RUSHED TO THE SCENE UPON HEARING ABOUT THE TRAGEDY. AND BROKE DOWN WHEN THEY LEARNED THE NEWS.
<P>
. THINGS ALWAYS HAPPEN TO THE WRONG PERSON.'
<P>
AT THE VIDEO STORE WHERE JOSE GARCIA WORKED. ALL THE EMPLOYEES WERE SENT HOME AND THE SHOP CLOSED FOR THE NIGHT.
<P>
THE STORE OWNER SAYS GARCIA WAS A GOOD EMPLOYEE WHO WAS TRYING TO BETTER HIS LIFE WHEN HE WAS SHOT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Mini-mart shoot-TA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mini-mart shoot-TA</H3><BR>
BOTH GARCIA AND MARTINEZ ARE 18-YEARS OLD. BOTH SALINAS RESIDENTS.
<P>
WE'RE TOLD MARTINEZ IS OUT OF SURGERY NOW AND HIS CONDITION IMPROVING.
<P>
AGAIN, THE KILLER IS STILL OUT ON THE LOOSE TONIGHT. SO IF YOU KNOW ANYTHING ABOUT THIS INCIDENT. SALINAS POLICE WOULD APPRECIATE YOUR CALL.
<P>
ALAN?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Del Ray woods susp>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Del Ray woods susp</H3><BR>
SEASIDE POLICE HAVE A SUSPECT IN THE CASE OF TWO ATTEMPTED ABDUCTIONS. NEAR THE DEL RAY WOODS ELEMENTARY SCHOOL.
<P>
THE MAN ALLEGEDLY APPROACHED THE STUDENTS AND OFFERED THEM A RIDE.
<P>
THE STUDENTS ALERTED TEACHERS. AND THEY IN TURN ALERTED PARENTS.
<P>
SINCE THEN. WORRIED PARENTS HAVE BEEN HELPING TO PATROL THE AREA. 
<P>
"MY DAUGHTER IS IN THE 4TH GRADE. "ONE EXTRA STRESS I DON'T NEED TO DEAL WITH."
<P>
THE SUSPECT. 22-YEAR-OLD JESUS REYES-CASES. WAS ARRESTED ON THREE COUNTS OF ATTEMPTED CHILD ABDUCTION.
<P>
POLICE ARE STILL LOOKING FOR ANYONE THAT MAY HAVE WITNESSED ANY OF THE INCIDENTS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Salinas drug bust>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas drug bust</H3><BR>
FIVE PEOPLE ARE UNDER ARREST IN SALINAS TONIGHT. AFTER A YEAR-LONG DRUG INVESTIGATION.
<P>
SEARCH WARRANTS WERE SERVED AT THREE DIFFERENT HOUSES.
<P>
POLICE SAY. THE SUSPECTS TRIED TO SELL DRUGS. INCLUDING MARIJUANA AND COCAINE. IN SALINAS AND MONTEREY.
<P>
THE SUSPECTS ARE BEING HELD ON ONE MILLION DOLLARS BAIL. AND POLICE SAY. MORE ARRESTS ARE EXPECTED AS THE INVESTIGATION CONTINUES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Carnahan Mom-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Carnahan Mom-INT</H3><BR>
YESTERDAY. 11-YEAR-OLD MURDER VICTIM NICOLE CARANAHAN WAS LAID TO REST IN A SALINAS CEMETERY.
<P>
BUT HER MOTHER. BECKY CARNAHAN STILL HAS A WHOLE LIFE AHEAD OF HER. A LIFE SHE WILL NOW LIVE WITHOUT HER ONLY CHILD.
<P>
TODAY. SHE SHARED SOME OF HER PERSONAL FEELINGS. WITH US.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Carnahan Mom-GU>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Carnahan Mom-GU</H3><BR>
JUST EIGHT DAYS AFTER THE BRUTAL MURDER OF HER 11-YEAR-OLD DAUGHTER NICOLE. BECKY CARNAHAN SORTS THROUGH BOXES AND BOXES OF MEMORIES.
<P>
SOT: THESE ARE HER BABY BOOKS.
<P>
ALONG WITH HUNDREDS AND HUNDREDS OF PICTURES. AND OTHER MEMENTOS. NICOLE LEFT BEHIND BUNDLES OF RIBBONS. AWARDS SHE EARNED IN 4-H. BY RAISING RABBITS. SOMETHING SHE'D DONE SINCE SHE WAS A LITTLE GIRL.
<P>
BUT ALONG WITH HER OWN MEMORIES. BECKY NOW HOLDS STACKS OF LETTERS AND NOTES FROM NICOLES FRIENDS AND CLASSMATES. GIVEN TO HER AT THE FUNERAL.
<P>
SOT:   "IT'S BEEN OVERWHELMING. I NEVER REALIZED THIS MANY PEOPLE KNEW MY DAUGHTER."
<P>
BECKY IS RECEIVING EMOTIONAL SUPPORT FROM LOVED ONES AS WELL. AND SHE SAYS SHE'S TRYING TO KEEP HER SELF BUSY. BUT IT'S STILL PAINFUL AND DIFFICULT. ESPECIALLY WHEN SHE SEES NICOLES SCHOOL BUS PASS BY IN THE MORNING. OR WHEN SHE SIMPLY LOOKS AT THE SURROUNDINGS IN HER OWN HOME.
<P>
SOT:  "SHE'S MY ONLY BABY.  THIS WHOLE HOUSE, EVERY PICTURE ON THE WALL. IT'S ALL ABOUT HER.  SHE WAS MY LIFE."
<P>
A LIFE LIVED IN THIS HOME. THE VERY PLACE WHERE NICOLE WAS MURDERED.
<P>
DESPITE THE HORRIBLE FACT. BECKY SAYS SHE WONT LEAVE THE HOME.
<P>
SOT: "MY DAUGHTER'S EXISTANCE IS HERE, EVERYTHING WHE KNEW WAS HERE  I CAN'T WALK AWAY FROM THAT."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=147Carnahan Mom-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Carnahan Mom-TAG</H3><BR>
BECKY CARNAHAN'S NEXT-DOOR NEIGHBOR. RONALD MOORE. HAS BEEN CHARGED WITH NICOLE'S MURDER.
<P>
HE PLEADED NOT GUILTY TO THE CRIME EARLIER THIS WEEK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Mo Co Court secrur>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mo Co Court secrur</H3><BR>
YESTERDAY WE TOLD YOU ABOUT A REPORT THAT BLASTED SECURITY AT THE MONTEREY COUNTY COURTHOUSE IN SALINAS.
<P>
TODAY ONE JUDGE TELLS US THE SECURITY PROBLEMS ARE PUTTING HIS LIFE. AND THE LIVES OF OTHERS. AT RISK.
<P>
JUDGE JONATHON PRICE SAYS THE SECURITY AT THE COURTHOUSE IS UNACCEPTABLE.
<P>
HE SAYS ANYONE WANTING TO DO HARM. CAN WALK INTO VIRTUALLY ANY PART OF THE COURTHOUSE. TO GET TO THEIR TARGET.
<P>
"YOU TELL WME WHAT'S PREVENTING ANYBODY." "SOME GUY WALKS IN WITH A GUN."
<P>
PRICE SAYS HE'S BEEN TRYING TO GET ADMINISTRATORS TO BEEF UP SECURITY FOR THE PAST 15 YEARS.
<P>
ONE OF THE CHANGES HE'S HOPING WILL TAKE PLACE IS THE ADDITION OF A CENTRAL SECURITY STATION AT THE MAIN ENTRANCE TO THE COURTHOUSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Coastal commission>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Coastal commission</H3><BR>
MEMBERS OF THE STATE COASTAL COMMISSION SPENT ALL AFTERNOON TOURING AROUND THE MONTEREY PENINSULA TODAY. GETTING A FIRST-HAND LOOK AT SOME OF THE CENTRAL COAST'S MOST CONTROVERSIAL DEVELOPMENT PROJECTS.
<P>
THEIR FIRST STOP WAS THE SAND CITY DUNES. THE PROPOSED SITE OF A 230-ROOM, TEN-STORY RESORT HOTEL.
<P>
THEN, THEY WERE BUSED TO FUTURE DEVELOPMENT AREAS ALONG DEL MONTE BEACH, CANNERY ROW, PACIFIC GROVE, AND THE PROPOSED SITE OF THE HATTON CANYON FREEWAY IN CARMEL.
<P>
THE COASTAL COMMISSION EXPECTS IT'LL HAVE TO VOTE ON THESE PLANNED PROJECTS SOMETIME SOON. AND WANTED TO SEE THEM FOR THEMSELVES.
<P>
"AND IT'S VERY, VERY HELPFUL. LIKE THE HATTON CANYON PROJECT.  TWO-DIMENSIONAL ISSUE."
<P>
COMMISSION MEMBER AND MONTEREY COUNTY SUPERVISOR DAVE POTTER HAD THIS TO SAY ABOUT THE PLANNED RESORT IN SAND CITY.
<P>
"ANYTHING ON THE BEACH IN MONTEREY IS CONTROVERSIAL. I THINK IT'LL RECEIVE A HEAVY AMOUNT OF SCRUTINY."
<P>
MOST OF THESE LOCATIONS WON'T BE DISCUSSED DURING THIS MONTH'S MEETING. HOWEVER, THE COMMISSION *WILL* VOTE ON A PLANNED BICYCLE PATH IN PACIFIC GROVE TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Al Gore in SJ>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Al Gore in SJ</H3><BR>
VICE PRESIDENT AL GORE WAS IN THE BAY AREA TODAY.
<P>
TAKING RUSSIAN PRIME MINISTER VIKTOR CHERNOMYRDIN. TO THE HEART OF CALIFORNIA'S HIGH TECH INDUSTRY. SILICON VALLEY.
<P>
THE V-P. AND THE RUSSIAN PRIME MINISTER WALKED THROUGH THE CLEAN ROOM OF THE LOCKEHED MARTIN SATELLITE ASSEMBLY PLANT.  
<P>
AND TALKED ABOUT BUSINESS DEALS WORTH BILLIONS.  
<P>
DEALS ALREADY UNDERWAY WILL PUT U.S. COMMUNICATIONS SATELLITES ON TOP OF RUSSIAN PROTON ROCKETS. 
<P>
.SPUTNIKS  TO ORBIT OVER RUSSIA, EASTERN EUROPE, AND AFRICA.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/pac bell>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/pac bell</H3><BR>
GOOD NEWS FOR FLOOD VICTIMS ON THE CENTRAL COAST.
<P>
THE PACIFIC BELL FOUNDATION ANNOUNCED TODAY IT WILL CONTRIBUTE MORE THAN 60 THOUSAND DOLLARS TO EMERGENCY RELIFEF EFFORTS.
<P>
THE GRANT WILL GO TO THE MONTEREY, SANTA CRUZ, SAN BENITO AND CARMEL BY THE SEA CHAPTERS OF THE AMERICAN RED CROSS.
<P>
THE MONEY WILL BE USED FOR THE MOST IMMEDIATE NEEDS OF STORM VICTIMS FOR THINGS LIKE FOOD, CLOTHING AND COUNSELING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Bilingual ed >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bilingual ed </H3><BR>
THE STATE SCHOOL BOARD DISMANTLED CALIFORNIA'S BILINGUAL EDUCATION POLICY TODAY.
<P>
THE BOARD DECIDED TO THROW OUT REGULATIONS THAT REQUIRE CHILDREN WHO DON'T SPEAK ENGLISH. TO FIRST BE TAUGHT IN THEIR NATIVE LANGUAGE.
<P>
TODAY'S MOVE TEMPORARILY SHIFTS CONTROL OVER BILINGUAL EDUCATION TO LOCAL SCHOOL DISTRICTS.     
<P>
IN JUNE. VOTERS WILL DECIDE WEATHER TO MAKE THE MOVE A PERMANENT ONE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Girls Education-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Girls Education-INT</H3><BR>
EDUCATIONAL STUDIES MAY SHOW THAT GIRLS FACE DISCRIMINATION IN CO-ED CLASSES. 
<P>
BUT A NEW STUDY. BY THE AMERICAN ASSOCIATION OF UNIVERSITY WOMEN. FINDS ALL-GIRL SCHOOLS AREN'T THE ANSWER. 
<P>
FOX'S CARL CAMERON HAS MORE ON THE NEW FINDINGS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
POLICE IN BOULDER, COLORADO. ARE HOPING A NEW TACTIC WILL GET RELUCTANT WITNESSES TO COME FORWARD WITH NEW INFORMATION. ON THE 14-MONTH-OLD MURDER CASE OF JON BENET RAMSEY.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(ramsey grand jury)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(ramsey grand jury)</H3><BR>
POLICE ARE ASKING THE DISTRICT ATTORNEY TO TURN THE CASE OF JON BENET RAMSEY. OVER TO A GRAND JURY.
<P>
THE 6-YEAR-OLD WAS FOUND STRANGLED TO DEATH IN THE BASEMENT OF HER HOME A YEAR AGO LAST CHRISTMAS.
<P>
POLICE SAY THEY LACK THE EVIDENCE TO MAKE AN ARREST. AND A GRAND JURY.  WITH THE AUTHORITY TO SUBPOENA RELUCTANT WITNESSES. COULD UNEARTH EVIDENCE 
<P>
THAT'S NORMALLY OFF-LIMITS. 
<P>
THE REQUEST FOLLOWS SEVERAL FAILED ATTEMPTS BY INVESTIGATORS TO RE-INTERVIEW THE GIRL'S PARENTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(cubans rescued)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(cubans rescued)</H3><BR>
A BOAT CARRYING SIXTEEN CUBANS REFUGEES. CAPSIZED IN 
<P>
CHOPPY SEAS. OFF THE COAST OF MIAMI BEACH TODAY.   
<P>
THE ACCIDENT  LEFT TWO PEOPLE DEAD. 
<P>
ONE PERSON IS MISSING AND SIX OTHERS ARE SUFFERING FROM EXPOSURE. 
<P>
A COAST GUARD HELICOPTER PATROL SPOTTED THE CUBANS. AND COAST GUARD BOATS RESCUED THE SURVIVORS.   
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(school fire)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(school fire)</H3><BR>
A FOUR-ALARM FIRE FORCED STUDENTS AND TEACHERS TO RUN FROM A PRIVATE HIGH SCHOOL IN WESTWOOD, NEW JERSEY THIS MORNING. 
<P>
FLAMES FULLY ENGULFED THE BUILDING. LEAVING IT COMPLETELY GUTTED. 
<P>
BUT POLICE SAY NO ONE WAS HURT. 
<P>
THE SCHOOL SAYS THE ONE HUNDRED AND THIRTY STUDENTS. ALL GOT OUT SAFELY. 
<P>
STILL NO WORD ON WHAT CAUSED THE FIRE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Asteroid expected>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Asteroid expected</H3><BR>
MARK OCTOBER 28TH. IN THE YEAR 20-28 ON YOUR NEW MILLENNIUM CALENDAR. 
<P>
THAT'S WHEN ASTRONOMERS SAY AN ASTEROID. MORE THAN A MILE WIDE. WILL ARRIVE. 
<P>
BUT DON'T GET TOO WORKED-UP. THE ASTEROID WON'T HIT OUR PLANET. 
<P>
BUT MAY COME AS CLOSE AS 30-THOUSAND MILES OF EARTH.
<P>
IT'S STILL PRETTY CLOSE. CONSIDERING THE MOON IS EIGHT TIMES FARTHER AWAY THAN THAT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/highway>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/highway</H3><BR>
AFTER DAYS OF DEBATE., THE SENATE TODAY APPROVED A TRANSPORTATION BILL THAT WILL ALLOT OVER 200-BILLION DOLLARS TO THE NATION'S ROADS AND MASS TRANSIT.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
SENATORS VOTED 96 TO FOUR. TO SPEND 176-BILLION DOLLARS ON HIGHWAY CONSTRUCTION OVER SIX YEARS.  AND 41-POINT-3 BILLION DOLLARS FOR PUBLIC TRANSIT. 
<P>
THAT'S A 32-BILLION DOLLAR JUMP FROM THE LEVELS SOUGHT IN THE FAILED 19-97 ATTEMPT TO RENEW THE INTERMODAL SURFACE TRANSPORTATION EFFICIENCY ACT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Prep Basketball>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Basketball</H3><BR>
MARCH MADNESS DOESN'T ONLY REFER TO COLLEGE BASKETBALL. AT PACIFIC GROVE HIGH SCHOOL, BREAKER FEVER IS AT A PITCH, AS THE BOYS BASKETBALL TEAM, WHICH HAS ALREADY WON THE DIVISION IV C.C.S. CHAMPIONSHIP, HOSTS MARIN CATHOLIC TONITE, IN THE SEMI-FINALS OF THE NORTHERN CALIFORNIA PLAYOFFS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41NCAA Tourney>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NCAA Tourney</H3><BR>
OKAY, GET YOUR BRACKETS READY, COLLEGE BASKETBALL'S TOURNAMENT IS AS GOOD AS GETS FOR SERIOUS SPORTS FANS.
<P>
32-TEAMS ARE IN ACTION TODAY.
<P>
WE'LL START WITH THE U.S.F. DONS, MAKING THEIR FIRST APPEARANCE IN THE BIG DANCE, IN 16-YEARS. AT THE WEST REGIONAL IN BOISE, THEY TAKE ON UTAH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145Sprewell>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sprewell</H3><BR>
JUST WHEN HE THOUGHT HIS TROUBLES WERE BEHIND HIM, LATRELL SPREWELL GETS WORD TODAY THAT CRIMINAL CHARGES WILL PROBABLY BE FILED AGAINST HIM FOR RECKLESS DRIVING.
<P>
C-H-P INVESTIGATORS HAVE ADVISED PROSECUTORS THAT LAST WEEK, SPREWELL, WHILE DRIVING 90-MILES AN HOUR, TRIED TO GET BACK ONTO THE FREEWAY FROM AN EXIT ONLY LANE.
<P>
HE SLAMMED INTO ANOTHER CAR, WHICH OVERTURNED. SPREWELL WAS UNHURT, THE 2-PEOPLE IN THE OTHER CAR SUSTAINED MINOR INJURIES.
<P>
THE WARRIORS ARE OFF TONITE, THEY'LL VISIT PHOENIX TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
FINALLY TO GOLF, AND THE 2ND STOP OF THE PGA TOUR'S FLORIDA SWING, IS AT THE HONDA CLASSIC.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Gator garb disposal>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gator garb disposal</H3><BR>
HATE TO TAKE OUT THE GARBAGE?  MAYBE YOU SHOULD GET  AN ALLIGATOR.
<P>
THAT'S WHAT A GUY IN COLORADO DID.
<P>
YES, COLORADO.
<P>
ERWIN AND HIS SON JAY RUN THE COLORADO ALLIGATOR FARM IN A VALLEY OF THE ROCKY MOUNTAINS.
<P>
THEY'RE ACTUALLY FISH FAMERS. WHO BOUGHT THE ALLIGATORS TO EAT ANY DEAD FISH THAT THEY DON'T USE.
<P>
THE ALLIGATORS SURVIVE THANKS TO A GEO THERMAL AQUIFER. THAT KEEPS THE WATER. A LOVELY 87-DEGREES. ALL YEAR ROUND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
