<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Wednesday, 3/11/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Wednesday, 3/11/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106Salinas Apt Fire >Salinas Apt Fire </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Ax murderer-INT>Ax murderer-INT</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Fire safety meeting>Fire safety meeting</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Thomas harvey arrai>Thomas harvey arrai</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(bank hostages)>(bank hostages)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Carnahan funeral>Carnahan funeral</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143(Miami mayor)>(Miami mayor)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109David Piper MPC>David Piper MPC</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(house sliding)>(house sliding)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Chavez arraign>Chavez arraign</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(frozen peaches)>(frozen peaches)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Mo Co security>Mo Co security</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Italy cable car>Italy cable car</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Mo Co curfew>Mo Co curfew</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/credit cards>Fox Biz/credit cards</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Required Books-IN>Required Books-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141SB Lois Capps>SB Lois Capps</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42NCAA Tourney>NCAA Tourney</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Coastal comm/goats>Coastal comm/goats</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Hatton Canyon>Hatton Canyon</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Hartnell>Hartnell</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(ax murder) >Bump 1(ax murder) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Oscar statues>Oscar statues</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(bank hostag) >bump 2(bank hostag) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Cows escape>Cows escape</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=106Salinas Apt Fire >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas Apt Fire </H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
A FIRE AT A NORTH MONTEREY COUNTY DUPLEX LEAVES NINETEEN PEOPLE HOMELESS TONIGHT.
<P>
FIREFIGHTERS SAY IT STARTED JUST AFTER NOON TODAY, ON THE BOTTOM FLOOR OF THIS DUPLEX ON SALINAS ROAD.
<P>
IT WAS BEGINNING TO SPREAD TO THE SECOND FLOOR WHEN FIRE TRUCKS ARRIVED.
<P>
10 PEOPLE WERE LIVING ON THE FIRST FLOOR. ANOTHER NINE ON THE SECOND.
<P>
INVESTIGATORS SAY THE FIRE STARTED ON THE FIRST FLOOR. BUT THEY'LL HAVE TO CLEAR IT OUT TO FIND THE SOURCE.
<P>
IN: "SEEMS THE DOWNSTAIRS." OC: "WHY IT STARTED."
<P>
NO ONE WAS HURT IN FIRE. 
<P>
THE DUPLEX WAS MORE THEN 50-PERCENT DESTROYED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Fire safety meeting>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fire safety meeting</H3><BR>
OTHER FIREFIGHTERS SPENT THEIR DAY TALKING ABOUT THE NEW SAFETY REGULATIONS CREATED BY OSHA. 
<P>
ONE OF THOSE REGULATIONS IS ALREADY DRAWING FIRE.
<P>
IT'S CALLED THE "TWO-IN, TWO-OUT" RULE.
<P>
THAT MEANS FIREFIGHTERS CAN NOT ENTER A BURNING STRUCTURE. UNLESS AT LEAST TWO OTHER FIREFIGHTERS ARE ON SCENE FOR BACK UP.
<P>
FIREFIGHTERS SAY THE NEW RULE MAY REQUIRE CHANGES IN OPERATIONS AND STAFFING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Thomas harvey arrai>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Thomas harvey arrai</H3><BR>
A MAN WHO AUTHORITIES SAY OWNED THE GUN. USED IN THE ACCIDENTAL SHOOTING OF A 7-YEAR-OLD GONZALEZ GIRL. TODAY PLED NOT GUILTY. TO FELONY STORAGE OF A FIRE ARM.
<P>
IT HAPPENED IN OCTOBER OF LAST YEAR.
<P>
INVESTIGATORS SAY THE VICTIM'S 9-YEAR OLD BROTHER FOUND THOMAS HARVEY'S GUN UNDER A BED. AND ACCIDENTALLY SHOT HIS SISTER. KATRINA EAGLE.
<P>
SHE LATER DIED. 
<P>
A PRE-TRIAL HEARING FOR THOMAS WILL BE HELD NEXT MONTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Carnahan funeral>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Carnahan funeral</H3><BR>
HUNDREDS TURN OUT TODAY TO PAY LAST RESPECTS TO A YOUNG SALINAS MURDER VICTIM.
<P>
IT WAS ONE WEEK AGO THAT. POLICE SAY. 11-YEAR-OLD NICOLE CARNAHAN WALKED IN ON A BURGLAR AND WAS MURDERED.
<P>
FUNERAL SERVICES WERE HELD AT THE ECHOES OF CALVARY CHURCH IN SALINAS.
<P>
AMONG THE MORE THAN 400 MOURNERS WAS A LARGE NUMBER OF CHILDREN.  MANY CARRYING FLOWERS. 
<P>
AFTER THE SERVICE NICOLES FATHER AND MOTHER WERE CONSOLED BY FRIENDS AND FAMILY. 
<P>
NICOLE WAS BURIED AT THE QUEEN OF HEAVEN CEMETERY IN NORTH SALINAS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109David Piper MPC>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>David Piper MPC</H3><BR>
+
<P>
A MONTEREY PENINSULA COLLEGE COUNCELER. ACCUSED OF THREATENING TO KILL A STUDENT. WILL STAND TRIAL IN SUPERIOR COURT.
<P>
        DAVID ALEXANDER PIPER HAS PLEADED NOT GUILTY TO THE CHARGES. 
<P>
THE ALLEGATIONS STEM FROM AN ALLEGED ENCOUNTER PIPER HAD WITH A FEMALE STUDENT HE WAS OFFERING GUIDANCE TO.
<P>
HE'S CHARGED WITH MAKING THREAT OF DEATH/GREAT BODILY INJURY. WEAPON IN COMMISSION OF CRIME.
<P>
        PIPER'S TRIAL DATE WAS SET FOR LATER THIS MONTH.
<P>
HIS ATTORNEY SAYS THE CHARGES ARE A RESULT OF A MISUNDERSTANDING. AND HE CLAIMS THE ALLEGED "VICTIM". WHO HAS FILED A CIVIL SUIT.  IS OUT FOR MONEY. 
<P>
        PIPER. MEANWHILE, IS ON SABATTACLE FROM M-P-C, AND IS WORKING ON HIS DOCTORATE IN EDUCATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Chavez arraign>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chavez arraign</H3><BR>
A FORMER SANTA CRUZ COUNTY CLERK. ACCUSED OF EMBEZZLEMENT. WAS IN COURT TO BE ARRAIGNED ON THOSE CHARGES TODAY. BUT THAT ARRAIGNMENT WAS POSTPONED UNTIL APRIL 16TH.
<P>
        KATHY CORRINA CHAVEZ WAS A CLERK AT THE COUNTY COURTHOUSE ANNEX IN WATSONVILLE.
<P>
        HER JOB WAS TO COLLECT FINES.
<P>
        BUT INSTEAD OF TURNING IN THE MONEY.
<P>
PROSECUTORS SAY, SHE POCKETED THE CASH, ISSUED
<P>
A PHONY RECEIPTS, THEN DOCTORED THE FILES.
<P>
        CHAVEZ IS CHARGED WITH EMBEZZLING 17-THOUSAND
<P>
DOLLARS OVER A 3-YEAR PERIOD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Mo Co security>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mo Co security</H3><BR>
AN INDEPENDENT CONSULTING FIRM HIRED TO LOOK INTO LONG-STANDING SECURITY CONCERNS FACING THE MONTEREY COUNTY COURTHOUSE. HAS RELEASED IT'S FINDINGS.
<P>
THE REPORT BLUNTLY SAYS ALL EMPLOYEES AND VISITORS TO THE MONTEREY COUNTY COURTHOUSE ARE CONSTANTLY AT RISK. AND THAT IF COUNTY ADMINISTRATORS CONTINUE TO IGNORE THE REPEATED WARNINGS. SOMEONE'S BOUND TO GET HURT SOON.
<P>
ADMINISTRATORS ADMIT THEY HAVEN'T DONE ENOUGH TO RESOLVE THE PROBLEM. BUT SAY THEY'RE NOW FOCUSING THEIR ATTENTION ON THE ISSUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Mo Co curfew>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mo Co curfew</H3><BR>
A NEW MONTEREY COUNTY LAW DESIGNED TO KEEP YOUNG PEOPLE OUT OF TROUBLE. COULD GET PARENTS IN TROUBLE IF THEIR KIDS DON'T COMPLY.
<P>
THAT'S BECAUSE PARENTS WILL BE HELD RESPONSIBLE AFTER THE NEW CURFEW GOES INTO EFFECT APRIL TENTH.
<P>
KIDS UNDER 18 WONT BE ALLOWED ON THE STREETS WITHOUT A REASON. AFTER TEN P-M.
<P>
IF KIDS ARE OUT. THE SHERIFF'S DEPARTMENT WILL HAVE THE AUTHORITY TO PICK UP THE YOUNGSTERS. 
<P>
THE CURFEW GOES INTO EFFECT APRIL TENTH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Required Books-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Required Books-IN</H3><BR>
LOOK AT MOST HIGH SCHOOL READING LISTS AND YOU'LL PROBABLY SEE NAMES LIKE SHAKESPEARE AND CHAUCER. 
<P>
PROBABLY NOT MAYA ANGELOU OR TONI MORRISON. 
<P>
THAT MAY SOON CHANGE. AT LEAST IN ONE SCHOOL SYSTEM. 
<P>
BUT AS FOX'S TRACE GALLAGHER REPORTS. NOT EVERYONE'S GIVING THE IDEA AN "A". 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141SB Lois Capps>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SB Lois Capps</H3><BR>
IN A NEAR LANDSLIDE VICTORY. THE WIDOW OF FORMER CALIFORNIA HOUSE REPRESENTATIVE. WALTER CAPPS. KEPT THE SEAT NOT ONLY IN THE FAMILY.BUT ALSO IN THE DEMOCRATIC PARTY. 
<P>
PRESIDENT CLINTON PHONED IN HIS CONGRATULATIONS TO LOIS CAPPS  THIS AFTERNOON.
<P>
CAPPS MADE A RUN FOR THE 22ND DISTRICT AFTER HER HUSBAND PASSED AWAY.
<P>
WALTER CAPPS HAD ONLY SERVED 8 MONTHS OF HIS TERM WHEN HE DIED SUDDENLY OF A HEART ATTACK.
<P>
CAPPS' OPPONENT LASHED OUT AFTER THE ELECTION. SAYING SHE GOT 53-PERCENT OF THE VOTE OUT OF SYMPATHY. AND VOTER LOYALTY TO HER HUSBAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Coastal comm/goats>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Coastal comm/goats</H3><BR>
A HEARD OF GOATS GRAZING NORTH OF SANTA CRUZ. WERE SAVED FROM BEING EVICTED TODAY. 
<P>
AFTER NEIGHBORS TRIED TO GET THE COASTAL COMMISION TO GIVE THEM THEIR WALKING PAPERS.
<P>
THE CALIFORNIA COASTAL COMMISSION APPROVED A REQUEST BY A BIOTECHNOLOGY RESEARCHER. TO KEEP THE 15-HUNDRED GOATS. ON 2-HUNDRED ACRES OF LAND.
<P>
OPPONENTS TOLD THE COMMISION THEY WEREN'T  WORRIED ABOUT WHAT WAS GOING IN. BUT WHAT'S COMING OUT. IN THE ANIMAL'S MANURE.
<P>
"IT'S THE PUBLIC HEALTH, THE GROUND WATER, SURFACE WATER PROBLEMS THAT HAPPEN DURING OPERATIONS WHERE UNLIMITED NUMBERS OF ANIMALS ARE ALLOWED TO BE PUT ONTO AGRIBULTURAL LAND."
<P>
"I THINK THE MAJOR.HE'S LOCATED.
<P>
THE GOATS ARE BEING USED FOR SCIENTIFIC RESEARCH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Hatton Canyon>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hatton Canyon</H3><BR>
IT'S BEEN IN THE WORKS FOR MORE THAN 40 YEARS. BUT NOW ENVIRONMENTALISTS HAVE PUT A SNAG IN THE HATTON CANYON PROJECT.
<P>
TODAY THE MONTEREY REGIONAL PARKS DISTRICT ANNOUNCED IT WOULD BUY 34 ACRES OF OPEN SPACE IN THE HIGH MEADOWS.
<P>
FIVE OF THOSE ACRES WERE EARMARKED FOR CAL TRANS. TO BUILD THE FREEWAY.  
<P>
        BUT OPPONENTS SAY THE LAND MUST BE KEPT IN IT'S NATURAL STATE. AS PARK LAND.
<P>
THE PARKS DISTRICT HAS A YEAR TO DECIDE WHAT TO DO WITH THE LAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(ax murder) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(ax murder) </H3><BR>
UP NEXT ON FOX NEWS.
<P>
A TEENAGER GOES ON A RAMPAGE. KILLING HIS PARENTS. AND ATTEMPTING TO KILL THE REST OF HIS FAMILY.
<P>
WE'LL TELL YOU WHY POLICE THINK HE DID IT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(bank hostag) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(bank hostag) </H3><BR>
AND A BANK ROBBER HOLDS POLICE AT BAY. BY A HOLDING A GUN TO A HOSTAGE'S HEAD.
<P>
WE'LL TELL YOU HOW IT ENDED.RIGHT AFTER THIS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Ax murderer-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ax murderer-INT</H3><BR>
AN ALABAMA TEENAGER. ACCUSED OF BRUTALLY ATTACKING MEMBERS OF HIS OWN FAMILY WITH AN AX AND SLEDGEHAMMER. IS NOW IN POLICE CUSTODY. 
<P>
POLICE SAY HIS VIOLENT RAMPAGE MAY HAVE BEEN DRIVEN BY A FANATICAL DEVOTION.TO DEVIL WORSHIP. 
<P>
FOX'S CYNTHIA GOULD HAS THE LATEST ON THIS BIZARRE STORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A BANK STANDOFF SOUTH OF SEATTLE ENDS PEACEFULLY FOR THE HOSTAGES.BUT NOT FOR THE HOSTAGE-TAKER. 
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(bank hostages)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(bank hostages)</H3><BR>
AFTER A FIVE HOUR STANDOFF WITH POLICE. THE SUSPECT EMERGED FROM THE BANK WITH A GUN PRESSED TO THE HEAD OF HIS LAST HOSTAGE. 
<P>
SOON AFTER. HE SET HER FREE.THEN TURNED THE WEAPON ON HIMSELF.FIRING ONE SHOT INTO HIS OWN STOMACH.
<P>
HE IS NOW IN SERIOUS CONDITION AT AN AREA HOSPITAL. 
<P>
IT ALL STARTED WITH A BOTCHED ROBBERY ATTEMPT.
<P>
ORIGINALLY. FIVE WOMEN AND A MAN. ALL BANK EMPLOYEES. WERE HELD HOSTAGE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143(Miami mayor)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Miami mayor)</H3><BR>
A POLITICAL ROLLER-COASTER RIDE IN MIAMI MAY HAVE COME TO A STOP. 
<P>
A FLORIDA APPEALS COURT HAS REINSTATED FORMER MAYOR JOE CAROLLO. 
<P>
HE LOST HIS SEAT IN NOVEMBER TO XAVIER SUAREZ IN A RUNOFF. 
<P>
LAST WEEK. A LOWER COURT THREW OUT THAT ELECTION. CITING MASSIVE ABSENTEE BALLOT FRAUD. 
<P>
IT WAS THOSE VOTES WHICH GAVE SUAREZ THE VICTORY. 
<P>
WEDNESDAY.  THE APPEALS COURT AGREED WITH THE CHARGES OF FRAUD. BUT THREW OUT THE LOWER COURT'S CALL FOR A SPECIAL ELECTION. 
<P>
SUAREZ IS PROMISING TO FILE AN APPEAL TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(house sliding)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(house sliding)</H3><BR>
IN INDIANA. RECENT HARD-HITTING WINTER STORMS HAVE THREATENED SEVERAL HIGH PRICED HOMES.
<P>
ONE HOME HAS ALREADY SLID INTO LAKE MICHIGAN.
<P>
THE TOWN OF BEVERLY SHORES HAS BEEN WORKING WITH THE U.S. ARMY CORPS OF ENGINEERS ON A ONE-POINT-SEVEN MILLION DOLLAR PROJECT TO SHORE UP THE CRUMBLING 
<P>
LAKEFRONT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(frozen peaches)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(frozen peaches)</H3><BR>
PEACH FARMERS ALL ACROSS ALABAMA SPENT LAST NIGHT WATCHING A DROPPING THERMOMETER. FEARING THE WORST AS A SUDDEN COLD SNAP TOOK HOLD OF THEIR CROPS.JUST AS THEY BEGAN TO BLOOM. 
<P>
FARMERS SAY THREE TO FOUR DEGREES CAN MAKE OR BREAK THE PEACH SEASON.
<P>
FOR NOW.SOME FARMERS ARE COUNTING ON THE WIND AND HEAT TO SAVE THEIR CROPS.BUT OTHERS SAY NOTHING WILL HELP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Italy cable car>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Italy cable car</H3><BR>
THE U-S MARINE CORPS HAS FINISHED ITS INVESTIGATION  INTO A MARINE JET ACCIDENT THAT KILLED 20 PEOPLE IN ITALY. 
<P>
C-N-N REPORTS. THE FOUR CREW MEMBERS OF THE PROWLER JET MAY FACE A COURT-MARTIAL. 
<P>
THE LOW-FLYING JET SEVERED A SKI LIFT CABLE LAST MONTH
<P>
SOURCES SAY THERE'S EVIDENCE THE CREW WAS HOTDOGGING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/credit cards>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/credit cards</H3><BR>
YOU'VE PROBABLY GOTTEN ONE OF THESE OFFERS IN THE MAIL. PLATINUM CREDIT CARDS. OFFERING SKY-HIGH CREDIT LIMITS AND LOW INTEREST RATES.BUT WHAT YOU SEE MAY NOT ALWAYS BE WHAT YOU GET.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
PLATINUM CREDIT CARDS ARE ALL THE RAGE AMONG CONSUMERS. BUT IN REALITY. THERE IS VERY LITTLE DIFFERENCE BETWEEN A PLATINUM CARD AND A GOLD CARD.       THE MAIN DIFFERENCE IS THE ADDITION OF 24 HOUR CUSTOMER SERVICE.
<P>
THE AVERAGE RATE FOR A PLATINUM CARD IS ABOUT 15-PERCENT. COMPARED TO 16 FOR GOLD CARDS. AND 17 FOR STANDARD CREDIT CARDS.
<P>
THE OTHER BIG LURE OF PALTINUM CARDS IS THE HUGE CREDIT LIMIT. SOMETIMES HAS HIGH AS A HUNDRED THOUSAND DOLLARS.
<P>
BUT IN FACT LESS THAN ONE HALF OF ONE PERCENT OF THE CONSUMERS WOULD EVER QUALIFY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
DURING A 2 AND A HALF HOUR INTERVIEW WITH BAY AREA REPORTERS, LATRELL SPREWELL SAID HE'D BE HAPPY TO RETURN TO THE WARRIORS, IF THEY FIRED HEAD COACH P.J. CARLESIMO.
<P>
SPREWELL ADMITTED THAT WAS UNLIKELY, AND THAT HE WILL PROBABLY BE TRADED.
<P>
TONITE THE WARRIORS HOST THE T-WOLVES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42NCAA Tourney>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NCAA Tourney</H3><BR>
BILL RUSSELL, K.C. JONES, BILL CARTWRIGHT, AND QUINTEN DAILEY. THOSE ARE JUST SOME OF THE NAMES THAT HAVE PLAYED BASKETBALL FOR THE UNIVERSITY OF SAN FRANCISCO OVER THE YEARS.
<P>
BUT ITS BEEN 16-YEARS SINCE THE DONS PLAYED IN THE NCAA TOURNAMENT. THAT WILL CHANGE TOMORROW, WHEN U.S.F. BATTLES UTAH IN THE FIRST ROUND OF THE WEST REGIONAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO THE ICE, AND TONITE THE SHARKS TAKE THEIR 3-GAME WINNING STREAK INTO MADISON SQUARE GARDEN, TO TAKE ON  WAYNE GRETSKY AND THE NEW YORK RANGERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Hartnell>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hartnell</H3><BR>
TO THE DIAMOND NOW. THE HARTNELL PANTHERS ARE LOOKING TO IMPROVE ON LAST YEARS 18-22 RECORD. BUT SO FAR THEY HAVEN'T EXACTLY BUSTED OUT OF THE GATE.
<P>
ZANE TABARI HAS MORE ON THE PANTHERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Oscar statues>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Oscar statues</H3><BR>
THE OSCARS ARE STILL TWO WEEKS AWAY. BUT THE COVETED STATUES HAVE ARRIVED.
<P>
FIFTY ACADEMY AWARD STATUETTES ARRIVED IN LOS ANGELES. 
<P>
PINKERTON GUARDS WERE ON HAND TO MAKE DISEMBARKING EASIER FOR THE ARMY OF OSCARS. 
<P>
THEY WILL BE GIVEN AWAY MARCH 23-RD AT THE 70-TH ANNUAL ACADEMY AWARDS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Cows escape>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cows escape</H3><BR>
FINALLY TONIGHT.
<P>
THE GRASS IS ALWAYS GREENER ON THE OTHER SIDE. RIGHT?
<P>
WELL IT'S TRUE FOR THESE COWS.
<P>
THE HERD ESCAPED INTO AN ORLANDO SUBURB AFTER A STORM KNOCKED DOWN PART OF A PASTURE FENCE.
<P>
RESIDENTS SAY THE COWS FINALLY FIGURED OUT.THEY COULD EXPAND THEIR GRAZING TO THE PLUSH. GREEN GRASS ON THE OTHER SIDE OF THE FENCE. 
<P>
AND SO FAR THEY'RE REFUSING TO LEAVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
