<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Thursday, 3/26/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 3/26/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x032613.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (Holli child)>TS1 (Holli child)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(5 bodies found)>(5 bodies found)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Holli child porn-INT>Holli child porn-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(bus accident)>(bus accident)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Holli child porn-GUT>Holli child porn-GUT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(Terry Nicols offer)>(Terry Nicols offer)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Holli child porn-TAG>Holli child porn-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/Intel>Fox Biz/Intel</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Seaside PD reduct>Seaside PD reduct</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Final Four>Final Four</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126watson murder folo >watson murder folo </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4149ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Mty/seaside 187>Mty/seaside 187</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Reggie White>Reggie White</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131weapons seized>weapons seized</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Prep Football>Prep Football</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Cal Trans BS tour>Cal Trans BS tour</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Funnel cloud folo>Funnel cloud folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(Megan's) >Bump 1(Megan's) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(Arkansas) >bump 2(Arkansas) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Cactus League>Cactus League</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Megan's law broth-I>Megan's law broth-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Baywatch auditions>Baywatch auditions</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Arkansas shoot folo>Arkansas shoot folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145Grease re-release>Grease re-release</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=134TS1 (Holli child)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (Holli child)</H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
A HOLLISTER MAN IS BEHIND BARS TONIGHT. CHARGED WITH A SHOCKING CRIME INVOLVING CHILDREN AND PORNOGRAPHY.
<P>
POLICE DISCOVER A MINI-ARSENAL IN THE HOME OF A CARMEL MAN.
<P>
AND FOLKS IN BIG SUR MAY FINALLY BE GETTING THEIR ROAD BACK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
IT'S HAPPENED AGAIN: A LOCAL MAN IS ARRESTED AND CHARGED WITH DISTRIBUTING CHILD PORNOGRAPHY ON THE INTERNET.
<P>
THIS LATEST CASE ALLEGEDLY ORIGINATED FROM SAN BENITO COUNTY. WHERE OFFICIALS ARE CALLING IT THE *FIRST* INTERNET CHILD PORN CASE IN THE COUNTY'S HISTORY.
<P>
JINAH KIM'S BEEN FOLLOWING THE DEVELOPMENTS.
<P>
SHE JOINS US NOW FROM THE NEWSDESK WITH MORE.
<P>
JINAH?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Holli child porn-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Holli child porn-INT</H3><BR>
ARRESTED LAST MONDAY WAS 42-YEAR OLD BRIAN FRIEND OF HOLLISTER. 
<P>
HE'S BEEN THE SUBJECT OF AN EXTENSIVE, 7-MONTH INVESTIGATION THAT'S INVOLVED POLICE FROM SOUTHERN CALIFORNIA. ALL THE WAY UP TO HOLLISTER AND SAN JOSE.
<P>
FINALLY, THIS WEEK, HE WAS CHARGED. BUT INVESTIGATORS ARE JUST STARTING TO SCRATCH THE SURFACE. NO ONE KNOWS FOR SURE JUST HOW MANY YOUNGSTERS MAY HAVE BEEN VICTIMIZED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Holli child porn-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Holli child porn-GUT</H3><BR>
THOSE PHOTOS, ACCORDING TO SAN BENITO COUNTY OFFICIALS. CAME FROM A COMPUTER INSIDE THIS HOLLISTER HOME, BACK IN SEPTEMBER OF 1997.
<P>
THE ALLEGED SENDER: 42-YEAR OLD BRIAN FRIEND. A FATHER OF TWO SUSPECTED OF CONDUCTING SEXUAL CONVERSATIONS ONLINE WITH A 13-YEAR OLD GIRL, THEN SENDING HER THOSE LEWD PICTURES.
<P>
WHAT FRIEND DIDN'T KNOW. WAS THAT THE 13-YEAR OLD GIRL WAS ACTUALLY AN UNDERCOVER POLICE OFFICER. WHO IMMEDIATELY NOTIFIED HOLLISTER POLICE.
<P>
THOUGH THE INVESTIGATION IS STILL IN ITS EARLY STAGES. OFFICIALS *DON'T* BELIEVE FRIEND IS PART OF AN ORGANIZED CHILD PORN RING.
<P>
BUT THEY'RE NOT TAKING THE CASE LIGHTLY. GIVEN ITS UNUSUAL AND  DISTURBING NATURE.
<P>
MEANWHILE, FRIEND'S NEIGHBORS. WHO HAD BEEN SUSPICIOUS EVER SINCE POLICE SEARCHED HIS HOUSE FIVE MONTHS AGO. WERE SHOCKED TO HEAR THE NEWS OF HIS ALLEGED CRIME.
<P>
===BUTT TO======
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Holli child porn-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Holli child porn-TAG</H3><BR>
RIGHT NOW, INVESTIGATORS ARE FOCUSING ON TRYING TO IDENTIFY THE YOUNG GIRLS IN THOSE PHOTOGRAPHS. AND THEY'RE STILL GOING THROUGH THE SUSPECT'S COMPUTER TO GATHER MORE EVIDENCE. THAT MIGHT LEAD THEM TO MORE SUSPECTS. AND MORE CHARGES.
<P>
BUT AS IT IS, FRIEND FACES UP TO SIX YEARS IN JAIL.
<P>
ALAN?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Seaside PD reduct>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Seaside PD reduct</H3><BR>
THE SEASIDE CITY COUNCIL IS MEETING TONIGHT TO TALK ABOUT NEW IDEAS FOR RESTRUCTING THE POLICE AND FIRE DEPARTMENTS. AND. AT THE LAST MINUTE TO PUT DOWN RUMORS OF CUTS.
<P>
THE COUNCIL WAS ORIGINALLY GOING TO REVIEW A STUDY BY AN OUTSIDE CONSULTING FIRM THAT RECOMMENDED RESTRUCTING PUBLIC SAFETY DEPARTMENTS.
<P>
BUT RUMORS OF LESS POLICE ON THE STREETS CHANGED THE TONE OF THE MEETING. 
<P>
"WE'RE BASCIALLY LOOKING AT."EFFECTIVE ORGANIZATION."
<P>
"CERRAIN EVENTS OCCURED DURING THE DAY." "REDUCT THE POLCIE DEPARTMENT."
<P>
MAYOR DON JORDAN SAYS THE 30-THOUSAND DOLLAR STUDY SIMPLY  RE-EMPHASIZED THE COUNCIL'S ORGINAL PLANS FOR RESTRUCTING THE POLICE AND FIRE DEPARTMENT. WITH LESS ADMINISTRATIVE POSITIONS. AND MORE STREET PATROL OFFICERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126watson murder folo >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>watson murder folo </H3><BR>
ARRAIGNMENT HAS BEEN POSTPONED FOR THE MAN CHARGED IN THE MURDER OF A WATSONVILLE LIMOSINE DRIVER.
<P>
26-YEAR OLD STEVEN ALLIMILLO  WAS ASSIGNED A PUBLIC DEFENDER TODAY.
<P>
        OUTSIDE THE COURTROOM. THE FAMILY OF THE VICTIM. DAVID DOUGLAS MET WITH ATTORNEY STEVE LABERGE. THE VICTIM'S FRIEND.
<P>
        LABERGE SAYS DOUGLAS'S SON GOT A HINT OF WHAT WAS ABOUT TO HAPPEN TO HIS FATHER. WHEN HE STOPPED BY. ON THE DAY OF THE MURDER.
<P>
"THE LAST WORDS TO HIS SON WERE THAT HE HAD A CLIENT HE WAS GOING TO PICK UP THAT WEEKEND TO GO TO A FUNERAL. DAVID SHARED HIS DISLIKE FOR
<P>
FUNERALS.  HE ALWAYS WANTED FUNERALS OVER AS QUICKLY AS POSSIBLE.  HE FEARED DAVID WAS BEING TOLD OF HIS OWN FUNERAL."
<P>
        DOUGLAS'S BODY WAS FOUND SUNDAY IN A STORAGE LOCKER IN WATSONVILLE. 
<P>
ALAMILLO WAS ARRESTED IN LOS ANEGELES.
<P>
HE'S CHARGED WITH MURDER, GRAND THEFT AUTO, AND PROBATION VIOLATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Mty/seaside 187>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mty/seaside 187</H3><BR>
THE SUSPECTS ACCUSED OF KILLING TWO WOMEN AND INJURING ANOTHER IN TWO SEPARATE PENINSULA SHOOTINGS LAST MONTH. PLEADED "NOT GUILTY" TODAY IN COURT.
<P>
17-YEAR OLD NORMAN WILLOVER AND 19 YEAR OLD JOSEPH MANIBUSAN.ARE SUSPECTED OF KILLING 35 YEAR OLD PRIYA MATHEWS IN MONTEREY AND INJURING HER FRIEND JENNIFER ANINGER.
<P>
THEN DRIVING TO SEASIDE AND KILLING 47 YEAR OLD FRANCES OLIVIO.
<P>
THE SUSPECTS ARE BEING HELD WITHOUT BAIL TONIGHT.
<P>
A PRELIMINARY HEARING HAS BEEN SET FOR APRIL 30-TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131weapons seized>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>weapons seized</H3><BR>
A FOUR-MONTH LONG INVESTIGATION LEADS TO THE ARREST OF A CARMEL VALLEY MAN. ACCUSED OF COMMITTING A VARIETY OF WEAPONS VIOLATIONS.
<P>
59-YEAR-OLD GERALD PETKUS WAS ARRESTED YESTERDAY AT HIS HOME.
<P>
BACK IN NOVEMBER.NEUCOM. A MULTI-AGENCY TASK FORCE. SEIZED A HUGE CACHE OF WEAPONS. INCLUDING  ASSAULT RIFLES. SILENCERS. HAND-GUNS. GRENADES. AND SHOTGUNS FROM HIS HOME.
<P>
DURING YESTERDAY'S ARREST. AUTHORITIES SAY 40 THOUSAND ROUNDS OF AMMUNITION. AND MATERIALS FOR MAKING SILENCERS.  WERE SEIZED FROM PETKUS' HOME.               HE HAS BEEN BOOKED INTO MONTEREY COUNTY JAIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Cal Trans BS tour>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cal Trans BS tour</H3><BR>
        ANOTHER LANDSLIDE THREATENS TO DELAY THE OPENING OF HIGHWAY ONE. SOUTH OF CARMEL.     
<P>
IT HAPPENED EARLY YESTERDAY MORNING. AT HURRICANE POINT.
<P>
        THAT'S THE SAME PLACE THE ENTIRE SOUTHBOUND LANE OF HIGHWAY ONE CRUMBLED DOWN THE MOUNTAINSIDE JUST BEFORE VALENTINES DAY.
<P>
        CAL TRANS DECIDED TO REBUILD THE ROAD BY CARVING INTO THE MOUNTAINSIDE.
<P>
        SO HOW WILL THIS LATEST SLIDE AFFECT THEIR TIME SCHEDULE?
<P>
ITS HARD TO SAY AT THIS POINT. STILL DECIDING HOW TO GET US GOING AGAIN. AT THIS POINT, CAN'T HAUL MATERIAL TO NORTH.
<P>
        BEFORE THIS LATEST SLIDE. CAL TRANS WAS ESTIMATING IT WOULD BE ABLE TO OPEN THE ROAD AT THE END OF APRIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Funnel cloud folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Funnel cloud folo</H3><BR>
P-G AND E CREWS ARE STILL BUSY REPAIRING LINES THAT WERE DAMAGED BY YESTERDAY'S POWERFUL STORM.
<P>
HEAVY RAIN, HAIL, LIGHTNING. AND EVEN A REPORTED TORNADO. TEMPORARILY KNOCKED OUT POWER NEAR HOLLISTER.
<P>
MOST OF THE MAJOR DAMAGE HIT NEAR THE HOLLISTER AIRPORT.
<P>
A GREENHOUSE ABOUT THREE MILES AWAY WAS COMPLETELY  FLATTENED. 
<P>
IT'S BEEN HERE. LIKE THIS.
<P>
TODAY THERE ARE REPORTS A TORNADO MAY NOT BE THE CULPRIT IN THE GREENHOUSE DESTRUCTION.
<P>
THE NATIONAL WEATHER SERVICE SAYS THE DEBRIS WOULD HAVE BEEN SCATTERED.
<P>
WEATHER GURU'S BELIEVE IT WAS A PHENOMENON CALLED STRAIGHT LINE WINDS. THE BYPRODUCT OF A DOWN BURST. 
<P>
A LITTLE LATER IN WEATHER SANDHYA PATEL WILL US IF MORE SEVERE WEATHER IS ON THE WAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(Megan's) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(Megan's) </H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
THE BROTHER OF THE CHILD MOLESTER WHO INSPIRED MEGAN'S LAW. IS BEHIND BARS TONIGHT.    
<P>
POLICE ARE NOW SAYING HE ALSO MOLESTED CHILDREN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(Arkansas) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(Arkansas) </H3><BR>
AND. POLICE HAVE MORE INFORMATION TONIGHT. ABOUT THE VAN FOUND NEAR THE SCENE OF A GRISLY SHOOOTING AT AN ARKANSAS ELEMENTARY SCHOOL.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Megan's law broth-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Megan's law broth-I</H3><BR>
PAUL TIMMENDEQUAS ONCE SAID HE WOULD BE WILLING TO EXECUTE HIS BROTHER FOR RAPING AND MURDERING MEGAN KANKA. A CASE WHICH HAS INSPIRED NATIONAL  LEGISLATION NOW KNOWN AS "MEGAN'S LAW." 
<P>
NOW THERE ARE SEXUAL CHARGES AGAINST HIM.  
<P>
HE FACED A JUDGE TODAY.AND FOX'S CRAIG TREADWAY WAS THERE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Arkansas shoot folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Arkansas shoot folo</H3><BR>
POLICE IN JONESBORO, ARKANSAS SHOWED REPORTERS THE VAN. WHERE TWO YOUNG BOYS ALLEGEDLY STORED WEAPONS FOR TUESDAY'S SHOOTING RAMPAGE AT THEIR SCHOOL. 
<P>
11-YEAR OLD ANDREW GOLDEN AND 13-YEAR OLD MITCHELL 
<P>
JOHNSON REPORTEDLY SKIPPED SCHOOL TUESDAY. DRESSED IN CAMOUFLAGE. AND LOADED GUNS INTO THIS VAN BELONGING TO JOHNSON'S STEP-FATHER. 
<P>
THE GUNS WERE REPORTEDLY STOLEN FROM GOLDEN'S GRANDFATHER'S HOUSE.
<P>
FOUR STUDENTS AND A TEACHER WERE KILLED IN THE SHOOTING. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
TWO ADULTS AND THREE CHILDREN ARE SHOT TO DEATH IN A TRAILOR HOME.
<P>
THAT STORY FROM REDFIELD, ARKANSAS. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(5 bodies found)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(5 bodies found)</H3><BR>
POLICE SAY THE VICTIMS. INCLUDING THREE CHILDREN AND TWO WOMEN.WERE SHOT TO DEATH. 
<P>
THEY INCLUDED A MOTHER AND HER TWO YOUNG CHILDREN.      THE TWO ADULTS WERE COUSINS. 
<P>
POLICE SAY THEY WERE CALLED TO THE TRAILER ON A REGULAR BASIS. FOR VARIOUS DOMESTIC DISPUTES. 
<P>
POLICE WERE CALLED THERE LAST NIGHT AT THE REQUEST OF RELATIVES. WHO FEARED FOR THE WELL-BEING OF ONE OF THE ADULT VICTIMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(bus accident)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(bus accident)</H3><BR>
TWO PEOPLE ARE DEAD. 20 OTHERS HURT. AFTER A TRACTOR-TRAILOR COLLIDES WITH A TOUR BUS IN TENNESSEE.
<P>
THE BUS WAS CARRYING HIGH SCHOOL KIDS BACK FROM AN ACADEMIC FAIR. WHEN IT MISSED IT'S EXIT.
<P>
THE DRIVER WAS TRYING TO TURN THE BUS AROUND WHEN IT WAS RAMMED BY THE BIG RIG.
<P>
A STUDENT AND A TEACHER WERE KILLED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(Terry Nicols offer)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Terry Nicols offer)</H3><BR>
IN DENVER.  A FEDERAL JUDGE HAS DENIED TERRY NICHOLS' REQUEST FOR A NEW TRIAL IN THE OKLAHOMA CITY BOMBING.
<P>
THE JUDGE ALSO TOLD NICHOLS HE FACES LIFE IN PRISON UNLESS HE ANSWERS SOME LINGERING QUESTIONS ABOUT THE BOMBING.
<P>
NICHOLS STILL FACES STATE MURDER CHARGES AND A POSSIBLE DEATH SENTENCE IN OKLAHOMA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/Intel>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/Intel</H3><BR>
HE WAS TIME MAGAZINE'S MAN OF THE YEAR.  BUT NOW. THE MAN AT THE HELM OF INTEL. IS STEPPING DOWN.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
INTEL'S C-E-O. ANDY GROVE IS STEPPING ASIDE. AND THE COMPANY'S PRESIDENT AND CHIEF OPERATING OFFICER CRAIG BARRETT. IS TAKING OVER THE POST. 
<P>
GROVE. ONCE A PENNILESS HOLOCAUST SURVIVOR. HELPED CREATE THE COMPANY THAT IS NOW THE WORLD'S BIGGEST COMPUTER CHIP MAKER. 
<P>
THE COMPANY HAD RECENTLY WARNED STOCKHOLDERS THAT ASIA'S ECONOMIC TURMOIL. AND A SLOWING P-C MARKET. WERE LIKELY TO HIT THE COMPANY'S BOTTOM LINE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Final Four>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Final Four</H3><BR>
IT HAS BEEN ONE THE MOST EXCITING NCAA TOURNAMENTS IN RECENT MEMORY, AND AS MARCH MADNESS IS ABOUT TO REACH ITS CRESCENDO WITH THE FINAL FOUR, COLLEGE BASKETBALL IS DEALT A SERIOUS BLOW.
<P>
POINT SHAVING AND GAMBLING ARE THE ISSUES, AND NORTHWESTERN UNIVERSITY, A PRIVATE SCHOOL IN CHICAGO KNOWN FOR ITS ACADEMIC EXCELLENCE, IS THE TARGET.
<P>
A FEDERAL INDICTMENT CHARGES TWO FORMER WILDCAT STARTERS, KENNETH DION LEE AND DEWEY WILLIAMS, ALONG WITH 2-OTHER PLAYERS, OF FIXING THE OUTCOME OF 3-GAMES DURING THE 1994-95 SEASON.
<P>
A FORMER NORTHWESTERN FOOTBALL PLAYER IS ACCUSED IN A SEPARATE INDICTMENT OF RUNNING A BOOKMAKING OPERATION ON CAMPUS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4149ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
FROM ONE MESSY SITUATION TO ANOTHER, THE 49ERS OWNERSHIP QUANDRY COULD BE SETTLED VERY SOON.
<P>
EDDIE DEBARTOLO IS REPORTEDLY CLOSE TO REGAINING CONTROL OF THE 49ERS FROM HIS SISTER. DENISE DEBARTOLO YORK HAS BEEN CHAIRMAN OF THE TEAM SINCE EDDIE D WAS NAMED IN A FEDERAL GAMBLING PROBE IN LOUISIANA.
<P>
DEBARTOLO IS EXPECTED TO SWAP HIS HOLDINGS IN THE FAMILY BUSINESS FOR HIS SISTER'S SHARE OF THE TEAM.
<P>
IF SUCCESSFUL, EDDIE WOULD PROBABLY DROP PLANS FOR THE 525-MILLION DOLLAR STADIUM AND SHOPPING MALL COMPLEX. AT LEAST FOR A WHILE.
<P>
THE LEAGUE WOULD HAVE TO APPROVE THE TRANSFER OF THE TEAM'S SHARES. AND THE FUTURE OF TEAM PRESIDENT CARMEN POLICY IS UNCLEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Reggie White>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Reggie White</H3><BR>
IN OTHER EVEN STRANGER NFL NEWS, GREEN BAY PACKERS ALL-EVERYTHING DEFENSIVE END REGGIE WHITE, MADE COMMENTS TO THE WISCONSIN STATE ASSEMBLY, THAT HAS CIVIL RIGHTS GROUPS ALL OVER THE COUNTRY UP IN ARMS.
<P>
WHITE, AN ORDAINED MINISTER, SPOKE IN RACIAL STEREOTYPES ABOUT BLACKS, WHITES, AMERICAN INDIANS, HISPANICS, ASIANS, WITH HIS MOST SERIOUS ATTACKS MADE TOWARDS HOMOSEXUALS.
<P>
WHITE WAS HOPING FOR A BROADCASTING JOB WITH CBS, BUT FOLLOWING COMMENTS LIKE THESE, IT NOW SEEMS UNLIKELY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Prep Football>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Football</H3><BR>
IN PREP FOOTBALL NEWS, SALINAS HIGH HAS HIRED A NEW HEAD FOOTBALL COACH.
<P>
BASSEL FALTAS TAKES OVER FOR MARK LAMBERSON WHO STEPPED DOWN A FEW WEEKS AGO.
<P>
FALTAS HAS BEEN AN ASSITANT AT NORTH COUNTY AND APTOS. HE GRADUATED FROM MONTEREY HIGH, AND PLAYED AT CABRILLO COLLEGE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
WE TURN OUR ATTENTION TO GOLF, AND TODAY THE "SO-CALLED" 5TH MAJOR GETS UNDERWAY.
<P>
YES, ITS THE PLAYERS CHAMPIONSHIP.
<P>
WE HEAD OUT TO PONTE VEDRA, FLORIDA. AND THIS, IS A BAD BIRDIE. I GUESS YOU'D DROP.
<P>
TOM LEHMAN, TRYING TO DROP ONE IN THE HOLE AT THE PAR 3, 13TH.
<P>
THIS SHOT LOOKING GOOD, BUT CHECK OUT THE ROLL, WHAT DO YOU THINK, A HOLE IN ONE?PYCHE.
<P>
LEHMAN IS AT EVEN PAR.
<P>
BUT CHECK OUT 18, THIS IS GLEN DAY, HIS 2ND SHOT. NO ONE HAS EVER EAGLED THIS HOLE ON THE STADIUM COURSE. GETTIN' THE GOOD ROLL. WOULD I TEASE YOU AGAIN.
<P>
NO, THE EAGLE HAS LANDED, AND THIS PUTS DAY IN THE LEAD.
<P>
AS WE CHECK THE BOARD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
TO TENNIS, AND AT THE LIPTON CHAMPIONSHIPS, ITS VENUS WILLIAMS AND MARTINA HINGIS IN KEY BISCAYNE.
<P>
HINGIS FOUGHT OFF 3-MATCH POINTS TO FORCE A 3RD SET. BUT IN THE 3RD SET, WILLIAMS PREVAILS.
<P>
THE NUMBERS 6-2, 5-7, AND 6-2.
<P>
YESTERDAY HINGIS BEAT VENUS' SISTER, SERANA WILLIAMS, ALSO FIGHTING OFF A COUPLE OF MATCH POINTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
QUICKLEY TO THE NBA, AND ITS FIRST VS. THE WORST IN THE PACIFIC DIVISION TONITE. AS THE WARRIORS HOST THE SEATTLE SUPERSONICS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Cactus League>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cactus League</H3><BR>
AND FINALLY, WE CONTINUE OUR CACTUS LEAGUE REPORTS, WITH A LOOK AT THE OAKLAND A'S PITCHING STAFF. 
<P>
NOW NO TEAM IN THE MAJORS HAD A WORSE STAFF THAN THE A'S LAST YEAR, AND THIS SPRING, OAKLAND PITCHERS HAD AN ERA OF 6.1.
<P>
SO TODAY THE TEAM FIRES PITCHING COACH BOB CLUCK, AND REPLACES HIM WITH ROVING INSTRUCTOR RICK PETERSON.
<P>
ZANE TABARI REPORTS, THE A'S ARE HOPING THAT THREE NEW ARMS WILL GO A LONG WAY IN '98.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Baywatch auditions>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Baywatch auditions</H3><BR>
PRODUCERS OF THE SHOW "BAYWATCH" ARE LOOKING FOR NEW BLOOD TO RUN ON THE BEACH.
<P>
THE SHOW. OFTEN NICKNAMED "BABE-WATCH" FOR OBVIOUS REASONS. IS TOURING 25 COLLEGE CAMPUSES TO FIND FRESH NEW  FACES.
<P>
EACH CONTESTANT IS GIVEN TEN SECONDS TO DO WHATEVER THEY WANTED TO GET THE JUDGES ATTENTION.
<P>
SOME SANG. SOME DANCED. OTHERS JUST HAD FUN.
<P>
WINNERS GET A GUARANTEED SPOT ON THE SHOW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145Grease re-release>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Grease re-release</H3><BR>
FINALLY TONIGHT.
<P>
TWENTY YEARS AGO. GREASE WAS THE WORD.AND NOW FILMMAKERS ARE HOPING IT *WILL-BE* AGAIN THIS SUMMER.
<P>
-----MUSIC----
<P>
THE MOST SUCCESSFUL MOVIE MUSICAL OF ALL TIME WILL BE RE-RELEASED TO A WHOLE NEW GENERATION OF FANS.
<P>
MOST PEOPLE THAT SHOWED UP FOR THE SNEAK PREVIEW STILL KNOW ALL THE WORDS.
<P>
"GREASE" WAS FIRST RELEASED IN 19-78. AND QUICKLY SOLD MORE THAN 20-MILLION ALBUMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
