<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Friday, 3/27/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Friday, 3/27/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x032712.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO FOX>TOSS TO FOX</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117TV Childhood Obese>TV Childhood Obese</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Crocker's Vigil>Crocker's Vigil</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Initial Death>Initial Death</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Stilwell Hall>Stilwell Hall</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Business News>Fox Business News</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Church's Chicken>Church's Chicken</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Big Sur Marathon>Big Sur Marathon</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Forest Grove Marine>Forest Grove Marine</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Golf: Players Champ.>Golf: Players Champ.</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Pepsi Kid>Pepsi Kid</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Cactus League>Cactus League</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Aptos High>Aptos High</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Kids Club Flight>Kids Club Flight</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Clinton/Mandela>Clinton/Mandela</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Mtn Bike Record>Mtn Bike Record</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Cops/Donut>Cops/Donut</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Glendale Hospital>Glendale Hospital</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Queen Pubbing >Queen Pubbing </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118Impotence Drug>Impotence Drug</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=106TOSS TO FOX>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO FOX</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
MORE TEARS ARE SHED TODAY. IN THE TIGHT-KNIT COMMUNITY OF JONESBORO, ARKANSAS.
<P>
THE TOWN SAID GOODBYE TO TWO OF THE CHILDREN KILLED IN THIS WEEK'S MIDDLE SCHOOL AMBUSH.
<P>
FOX'S BRETT BAIER SPENT THE DAY WITH GRIEVING FAMILY AND FRIENDS AT THE EMOTIONAL FUNERALS.
<P>
HE JOINS US NOW LIVE FROM JONESBORO WITH THE STORY.
<P>
BRETT?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Crocker's Vigil>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Crocker's Vigil</H3><BR>
MOURNERS CALL FOR JUSTICE TONIGHT. DURING A CANDLELIGHT VIGIL FOR A LIMOUSENE DRIVER 
<P>
SHOT TO DEATH IN WATSONVILLE.
<P>
        THE BODY OF 47-YEAR OLD DAVID DOUGLAS WAS FOUND
<P>
SUNDAY AT CROCKERS LOCKERS.
<P>
        POLICE IN LOS ANGELES LATER ARRESTED 26-YEAR OLD 
<P>
STEVEN ALAMILLO. AND RECOVERED DOUGLAS'S LIMO.
<P>
        TONIGHT, FRIENDS AND FAMILY OF THE MAN KNOWN AS
<P>
"POPS". GATHERED IN FRONT OF CROCKERS LOCKERS, TO PAY
<P>
THEIR RESPECTS AND TO CALL FOR JUSTICE IN THE 
<P>
PROSECUTION OF THE MAN CHARGED WITH THE MURDER.
<P>
        FORMER BUSINESS OWNER TED CROCKER SAYS THIS HAS BEEN TRAUMATIC FOR HIS FAMILY TOO.
<P>
"OUR ONE DAUGHTER THAT WAS 
<P>
HERE WHEN THEY DISCOVERED THE
<P>
CRIME SCENE WAS QUITE UPSET,
<P>
SO WE'VE TRIED TO DEAL WITH
<P>
THAT THIS WEEK. BEING IN THIS
<P>
BUSINESS 24-YEARS, WE'VE NEVER
<P>
ENCOUNTERED ANYTHING LIKE THIS."
<P>
        DAVID DOUGLAS'S FAMILY TONIGHT ENCOURAGED SUPPORTERS, TO ATTEND THE ARRAIGNMENT OF THE
<P>
ACCUSED ASSAILANT ON THURSDAY, APRIL SECOND.
<P>
        SERVICES FOR DOUGLAS WILL BE HELD THIS COMING MONDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Stilwell Hall>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stilwell Hall</H3><BR>
IT'S BEEN A CENTRAL COAST LANDMARK SINCE THE EARLY 40'S. BUT NOW THE ARMY SAYS STILWELL HALL IS IN DANGER OF FALLING INTO THE OCEAN.
<P>
THE 50-THOUSAND SQUARE FOOT OFFICERS' CLUB SITS ON A BLUFF ON THE FORMER FORT ORD.
<P>
THE OCEAN HAS BEEN SLOWLY UNDERMINING THE NEARBY CLIFFS.
<P>
BUT THIS WINTER'S EL NINO STORMS HAVE MADE MATTERS WORSE.
<P>
HUGE CHUNKS OF CONCRETE HAVE FALLEN OFF TO THE BEACH BELOW.
<P>
        THE ARMY HAD A SIMLIAR PROBLEM BACK IN 1983.
<P>
IT SPENT NEARLY HALF A MILLION DOLLARS SHORING UP THE BANK WITH LARGE ROCKS.
<P>
THE 420 FT. REINFORCED IN 1983 IS DOING ITS JOB. BUT IN DANGER OF COLLAPSING ON EACH CORNER. 120 FEET CAME IN ON EACH SIDE.
<P>
         THE STATE PARKS DEPARTMENT HAD WANTED TO RESTORE THE BUILDING AND TURN IT INTO A VISITORS CENTER.
<P>
        IF THEY WANT TO SAVE THE BUILDING. THEY CAN EITHER THROW MORE ROCKS ON THE SIDES.
<P>
.OR THEY CAN TRY TO MOVE THE BUILDING TO SAFER TERRITORY.
<P>
NEITHER OPTION IS CHEAP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Church's Chicken>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Church's Chicken</H3><BR>
THE ENVIRONMENTAL HEALTH DEPARTMENT HAS A WARNING FOR BUSINESS OWNERS. WATCH OUT FOR BOGUS INSPECTORS.
<P>
TWO WEEKS AGO CHURCH'S FRIED CHICKEN IN SEASIDE WAS ROBBED BY A PERSON IMPERSONATING A HEALTH INSPECTOR.
<P>
EMPLOYEES SAY THE MAN ARRIVED AFTER-HOURS AND DEMANDED ENTRY. FLASHING A BUSINESS CARD AND AN I-D CARD.
<P>
FIVE MINUTES LATER HE WAS GONE.AND SO WAS A THOUSAND DOLLARS.
<P>
ALL BUSINESSES ARE ADVISED TO EXAMINE CREDENTIALS VERY CAREFULLY. AND CALL THE OFFICE OF ENVIRONMENTAL HEALTH OR THE POLICE DEPARTMENT TO VERIFY THE IDENTIFICATION OF AN INSPECTOR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Big Sur Marathon>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Sur Marathon</H3><BR>
WITH JUST FOUR WEEKS TO GO BEFORE THE BIG SUR MARATHON. CAL TRANS CREWS ARE WORKING OVERTIME TO GET DAMAGED HIGHWAY ONE. REOPENED.
<P>
THE SCENIC HIGHWAY HAS BEEN CLOSED JUST NORTH OF THE BIG SUR AREA SINCE EARLY FEBRUARY DUE TO LANDSLIDES.
<P>
AND THAT'S LEFT ORGANIZERS OF THE 13-TH ANNUAL EVENT SCRAMBLING TO THINK OF ALTERNATE ROUTES.
<P>
BUT DESPITE THE WRENCH EL NINO'S THROWN INTO MARATHON PLANS. ORGANIZERS SAY IT'S MORE POPULAR THAN EVER.
<P>
"WE ARE, RIGHT NOW, WE ARE 200 AHEAD OF LAST YEAR.  IT'S A RECORD CROWD!"
<P>
CAL TRANS EXPECTS IT'LL FINISH WORK ON THE HIGHWAY BY APRIL 20-TH. SIX DAYS BEFORE THE MARATHON.
<P>
BUT IF THAT GETS PUSHED EVEN FURTHER. ORGANIZERS WILL PICK A DIFFERENT ROUTE, TO MAKE SURE THE RACE GOES ON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Forest Grove Marine>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Forest Grove Marine</H3><BR>
A UNIQUE PARTNERSHIP IN PACIFIC GROVE IS MAKING FOR A WIN-WIN SITUATION AT A LOCAL SCHOOL.
<P>
A GROUP OF 20 MARINES FROM MONTEREY'S DEFENSE LANGUAGE INSTITUTE. ARE HELPING OUT AT P-G'S FOREST GROVE ELEMENTARY SCHOOL.
<P>
THE MARINES VOLUNTEER THEIR TIME THROUGH A PROGRAM CALLED "ADOPT A SCHOOL."
<P>
THEY HELP INSIDE AND OUTSIDE THE CLASS, COACHING STUDENTS IN MATH, READING AND EVEN P-E.
<P>
THEY DO THIS THREE HOURS A DAY, FIVE DAYS A WEEK.
<P>
TEACHERS SAY. THE KIDS LOVE IT.
<P>
THESE PEOPLE. WE CAN GET. 
<P>
THE MARINES ALSO HELP WITH GROUNDS WORK ON THE CAMPUS ONE DAY A WEEK.      
<P>
THE PROGRAM'S  BEEN IN PLACE SINCE JANUARY AND THE PRINCIPAL SAYS EVERYONE INVOLVED BENEFITS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Pepsi Kid>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pepsi Kid</H3><BR>
TWO GEORGIA HIGH SCHOOL STUDENT WHO WERE SUSPENDED FOR WEARING PEPSI T-SHIRTS TO SCHOOL ON COKE DAY. ARE OFF THE HOOK.
<P>
THE SCHOOL ANNOUNCED TODAY. IT WILL REMOVE THE SUSPENSIONS FROM THE TWO GENERATION NEXT'RS RECORDS. 
<P>
SCHOOL OFFICIALS ADMITTED TO REPORTERS. THEY'VE HAD SECOND THOUGHTS ABOUT WHETHER THE BOYS SHOULD HAVE BEEN SUSPENDED.
<P>
SENIORS MIKE CAMERON AND DAN MOXLEY WORE THE PEPSI SHIRTS ON A DAY THE SCHOOL WAS HOSTING COCA-COLA OFFICIALS.
<P>
THE SCHOOL WAS TRYING TO WIN A 500-DOLLAR AWARD FROM THE COLA COMPANY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Aptos High>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Aptos High</H3><BR>
"GIVE ME A WILD COCONUT, NOT A 
<P>
PEPSI. CO, CO, CO, COLA."
<P>
NO PEPSI CONTROVERSY AT APTOS HIGH TODAY. WHERE STUDENTS COMBINED THEIR ANNUAL KOWABUNGA CELEBRATION AND GIRLS FOOTBALL GAME. WITH A *COCA-COLA* PROMOTION.
<P>
APTOS HIGH STUDENTS WERE FREE TO WEAR WHATEVER THEY WANTED TODAY.
<P>
"IT'S TOO BAD SCHOOLS ARE FORCED 
<P>
TO PROMOTE AND DO COMMERCIALS, 
<P>
BUT WE NEED THE 10,000 DOLLARS, 
<P>
AT APTOS HIGH, SO WE'RE GOING 
<P>
TO COMPETE."
<P>
        THE COCA-COLA COMPANY IS OFFERING 10-THOUSAND DOLLARS IN PRIZE MONEY TO THE SCHOOL THAT COMES UP WITH THE MOST CREATIVE AND SPIRITED WAY, TO DISTRIBUTE COKE DISCOUNT CARDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Clinton/Mandela>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Mandela</H3><BR>
SOUTH AFRICAN PRESIDENT NELSON MANDELA GIVES PRESIDENT CLINTON A TOUGH HISTORY LESSON TODAY. AS THE PAIR TOURED THE PRISON WHERE 
<P>
THE LEGENDARY APARTHEID ACTIVIST WAS JAILED.
<P>
MANDELA GAVE CLINTON A PERSONAL TOUR OF ROBBEN ISLAND: SOUTH AFRICA'S EQUIVALENT TO ALCATRAZ.
<P>
BUT BEFORE BEGINNING THE TOUR. MANDELA URGED THE PRESIDENT TO SET AN EXAMPLE FOR THE WORLD. BY BEGINNING PEACE TALKS WITH IRAN, LIBYA AND CUBA.
<P>
THEY ALSO DISCUSSED AN AFRICAN TRADE PACT THE U.S. IS PROPOSING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
BACK HERE AT HOME. A HOSPITAL EMPLOYEE CONFESSES TO KILLING SOME FIFTY PATIENTS OVER THE LAST DECADE.
<P>
THAT STORY FROM GLENDALE, CALIFORNIA. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Glendale Hospital>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Glendale Hospital</H3><BR>
THE ACCUSED MAN IS EFREN SALDIVAR. A RESPIRATORY CARE PRACTIONER AT GLENDALE ADVENTIST MEDICAL CENTER.
<P>
SALDIVAR REPORTEDLY CONFESSED TO HOSPITAL OFFICIALS THAT HE'S KILLED 40 TO 50 PATIENTS AT THE HOSPITAL SINCE 1989.
<P>
POLICE SAY SALDIVAR CONSIDERS HIMSELF AN "ANGEL OF MERCY". WHO USED LETHAL INJECTIONS TO END THE LIVES OF PATIENTS HE BELIEVED WERE CLOSE TO DEATH.
<P>
DETECTIVES ANNOUNCED THE CASE TODAY FOLLOWING A MONTH-LONG INVESTIGATION.
<P>
SALDIVAR HAS *NOT* BEEN FORMALLY CHARGED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118Impotence Drug>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Impotence Drug</H3><BR>
THE FOOD AND DRUG ADMINISTRATION HAS APPROVED THE FIRST PILL. TO TREAT IMPOTENCE IN MEN!
<P>
THE DRUG IS CALLED "VIAGRA". AND IS ALSO BEING HAILED AS THE FIRST NON-SURGICAL TREATMENT FOR THE OFTEN EMBARASSING CONDITION.
<P>
DRUG MAKER PFIZER SAYS THE PILL'S BEEN EFFECTIVE IN 70-PERCENT OF ALL MEN TESTED.
<P>
AS MANY AS 30-MILLION AMERICAN MEN SUFFER FROM VARYING DEGREES OF IMPOTENCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117TV Childhood Obese>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TV Childhood Obese</H3><BR>
A NEW STUDY SUGGESTS AMERICANS ARE RAISING A NEW GENERATION OF OVERWEIGHT COUCH POTATOES. AND THE MAIN CULPRIT APPEARS TO BE TELEVISION!!
<P>
THE STUDY, IN THIS WEEK'S "JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION," SAYS THE NUMBER OF OVERWEIGHT KIDS IS ON THE RISE. AND THAT KIDS WHO WATCH MORE THAN FOUR HOURS OF T.V. EVERY DAY. WERE FOUND TO BE AMONG THE HEAVIEST.
<P>
THE STUDY, HOWEVER, DID NOT SAY IF THE WEIGHT GAIN WAS DUE TO SNACKING DURING T-V TIME OR NOT ENOUGH PHYSICAL ACTIVITY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Initial Death>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Initial Death</H3><BR>
AND YET ANOTHER NEW STUDY SUGGESTS THE INITIALS OF YOUR NAME. MAY HAVE SOMETHING TO DO WITH HOW LONG YOU LIVE!
<P>
RESEARCHERS AT U.C. SAN DIEGO LOOKED AT 27-YEARS' WORTH OF DEATH CERTIFICATES IN CALIFORNIA. SOME FIVE MILLION PEOPLE. AND FOUND THAT PEOPLE WHOSE NAME INITIALS SPELL "JOY" OR "GOD" LIVED LONGER THAN THOSE WHOSE INITIALS SPELLED WORDS LIKE "APE," "BUM," OR "RAT."
<P>
THOSE RESEARCHERS SAY THE FINDINGS SEEM TO SUPPORT THE IDEA THAT LIKING YOUR NAME AND LIKING YOURSELF. AND THEREBY LIVING LONGER. MAY BE LINKED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Business News>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Business News</H3><BR>
A REPORT RELEASED THIS WEEK. CLAIMS ADS AIMED AT LATINO YOUTH ARE WORKING. AND THAT HAS LATINO ACTIVISTS  FIGHTING MAD.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
ACTIVISTS SAY ALCOHOL ADS FOR HOLIDAYS LIKE CINCO DE MAYO ARE AIMED AT LATINO YOUTH.  AND ARE A REASON FOR ALCOHOL RELATED ILLNESSES AND VIOLENCE IN THEIR NEIGHBORHOODS.
<P>
THEY SAY ALCOHOL USE IS ON THE INCREASE LARGELY BECAUSE OF BEER COMPANIES THAT TAKE AIM AT THEIR YOUTH. 
<P>
HOLIDAYS SHOULD BE. WE ARE DOING.
<P>
BEER COMPANIES SAY THEY'VE TRIED TO URGE  EVERYONE INCLUDING LATINOS TO DRINK RESPONSIBLY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
WE ARE ON EVE OF STANFORD'S FIRST FINAL FOUR APPEARANCE SINCE 1942.
<P>
FOR THEIR OPPONENT, KENTUCKY, ITS THEIR 3RD "STRAIGHT" TRIP TO BIG DANCE.
<P>
MAYBE ITS BECAUSE THE CARDINAL IS SUCH A DECIDED UNDERDOG FOR TOMORROW'S BIG GAME, THAT HAS MADE THEM, AT LEAST SEEM, SO RELAXED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
TO HOOPS, AND FOLLOWING LAST NIGHT'S HUGE VICTORY OVER THE PACIFIC DIVISION'S FIRST PLACE TEAM, THE SONICS, TONITE THE WARRIORS VISIT A TEAM VYING FOR THE WORST RECORD IN LEAGUE HISTORY, THE DENVER NUGGETS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Golf: Players Champ.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf: Players Champ.</H3><BR>
TO GOLF, AND THE 2ND ROUND OF THE "SO-CALLED" 5TH MAJOR IS IN THE BOOKS.
<P>
THE PLAYERS CHAMPIONSHIP HAS A GREAT FIELD, AND THE BIGGEST PAY-DAY OF THE YEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Cactus League>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cactus League</H3><BR>
TO BASEBALL, AND DESPITE WINNING THE NATIONAL LEAGUE WEST LAST YEAR, THE GIANTS ARE STILL THE RODNEY DANGERFIELD'S OF THE LEAGUE.
<P>
MOST NATIONAL PUBLICATIONS PREDICT THE GIANTS FINISHING IN THE MIDDLE OF THE PACK THIS YEAR.
<P>
BUT IN TONITE'S CACTUS LEAGUE REPORT, THE GIANTS OFFER A MORE OPTIMISTIC VIEW OF '98.
<P>
ZANE TABARI HAS OUR STORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Kids Club Flight>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kids Club Flight</H3><BR>
KCBA KIDS CLUB HOST JON DALMAN GOT TO PLAY THE PART OF A STUNT PILOT FOR A DAY.
<P>
HE FLEW HIGH OVER THE SKIES OF SALINAS WITH REAL STUNT PILOT SEAN TUCKER. IT'S ALL FOR A FUTURE KIDS CLUB SEGMENT.
<P>
WE'RE TOLD THE PLANE REACHED SPEEDS OF 200 MILES AN HOUR. WHILE UPSIDE DOWN AND 15 FEET OFF THE GROUND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Mtn Bike Record>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mtn Bike Record</H3><BR>
HERE'S A STORY FOR ALL YOU MOUNTAIN BIKING FANS OUT THERE:
<P>
THERE'S A NEW KING OF THE MOUNTAIN BIKERS. HE'S FRENCH CYCLIST CHRISTIAN TAILLEFER.
<P>
HE FLEW DOWN THE SLOPES OF THIS MOUNTAIN IN THE SOUTH OF FRANCE AT 132 MILES AN HOUR, TO SET A NEW WORLD MOUNTAIN BIKING SPEED RECORD.
<P>
HE USED A CUSTOM-BUILT PEUGEOT  BIKE FOR HIS RECORD RUN.
<P>
THE OLD RECORD WAS 130 MILES PER HOUR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Cops/Donut>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cops/Donut</H3><BR>
MOST OF US KNOW BETTER THAN TO GET BETWEEN A POLICE MAN AND HIS DONUT. BUT THAT STATEMENT COULDN'T BE TRUER IN WASHINGTON, D.C. TODAY.
<P>
THIS IS WHAT HAPPENS WHEN D-C POLICE ALONG WITH F.B.I. AND SECRET SERVICE AGENTS TEAMED UP FOR A CHARITY DONUT-EATING CONTEST.
<P>
YOU CAN BET THESE MEN IN BLUE HAD NO TROUBLE TAKING MATTERS INTO THEIR OWN MOUTHS.
<P>
IN THE END. THE WINNER WAS A DEPARTMENT OF CORRECTIONS OFFICER WHO WOLFED DOWN 15 DONUTS IN TWO MINUTES TO TAKE THE TOP PRIZE:  100 COMPLIMENTARY TICKETS TO THE CIRCUS. TO BE DONATED TO HIS FAVORITE CHARITY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Queen Pubbing >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Queen Pubbing </H3><BR>
AND FINALLY TONIGHT.    
<P>
THE BRITISH MONARCHY HAS CROSSED A WHOLE NEW THRESHOLD IN ITS CAMPAIGN TO GET COZIER WITH ITS SUBJECTS. 
<P>
THAT THRESHOLD BELONGED TO A BRITISH PUB.
<P>
THAT'S RIGHT. THAT'S QUEEN ELIZABETH THE SECOND INSIDE THE FAMOUS LONDON PUB, "BRIDGES INN."     
<P>
BUT IF YOU'RE IMAGINING HER MAJESTY SIPPING A TEQUILA 
<P>
SUNRISE, THINK AGAIN.
<P>
SHE KINDLY ACCEPTED A BOTTLE OF ALE. BUT DIDN'T DRINK IT THERE.
<P>
THIS IS BELIEVED TO BE THE MONARCH'S FIRST EVER VISIT TO A PUB OUTSIDE OF A 1981 INCIDENT WHEN SHE WAS FORCED INTO ONE BECAUSE OF A SNOW STORM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
