<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten , Sunday, 3/1/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten , Sunday, 3/1/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Las Lomas-I>Las Lomas-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Fox Hunt Protest-I>Fox Hunt Protest-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123Las Lomas-T>Las Lomas-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#36Bump #4 (Sports)>Bump #4 (Sports)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Nice Weather-I>Nice Weather-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39Surfing>Surfing</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Nice Weather-G>Nice Weather-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Nice Weather-T>Nice Weather-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Clinton/Starr>Clinton/Starr</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Lakers>Lakers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Septuplets Go Home>Septuplets Go Home</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43NBA Board>NBA Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Liz in Hospital>Liz in Hospital</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44College Hoops>College Hoops</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Di'S Bodyguard>Di'S Bodyguard</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Hoops Board>Hoops Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Propane Folo>Propane Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#9849ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#104Iraq Inspectors>Iraq Inspectors</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131A's Board>A's Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Israel Crash>Israel Crash</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Theater/Wheels-I>Theater/Wheels-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Australia Crash>Australia Crash</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#116Theater/Wheels-G>Theater/Wheels-G</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#24Peru Mudslides>Peru Mudslides</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Top Cat!!!>Top Cat!!!</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=112Las Lomas-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Las Lomas-I</H3><BR>
GOOD EVENING.I'M CHERI GYURO.THANKS FOR JOINING US.
<P>
IT'S BEEN ALMOST TWO WEEKS AND RESIDENTS IN LAS LOMAS STILL CAN'T GO HOME.
<P>
ELEVEN FAMILIES WERE EVACUATED AFTER A HUGE MUDSLIDE DESTROYED THEIR HOMES.
<P>
THE GROUND CONTINUES TO SHIFT.MAKING IT IMPOSSIBLE FOR ANYONE TO MOVE BACK IN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123Las Lomas-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Las Lomas-T</H3><BR>
MONTEREY COUNTY SHERIFF'S DEPUTIES URGE PEOPLE TO STAY AWAY FROM THE LAS LOMAS AREA.
<P>
THEY'VE POSTED ROAD CLOSURE SIGNS AND WILL HAND OUT CITATIONS.
<P>
TODAY ALONE: THEY ISSUED 6 TICKETS, TOWED TWO CARS AND MADE 2 ARRESTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Nice Weather-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Nice Weather-I</H3><BR>
FOR ONCE WE'RE NOT STANDING OUT HERE TELLING YOU ABOUT HOW WET IT IS. INSTEAD, WE'RE HERE TO TELL YOU THE EXACT OPPOSITE.
<P>
IT'S OFFICIAL. ACCORDING TO THE NATIONAL WEATHER SERVICE, YESTERDAY AND TODAY WERE THE FIRST DRY WEEKEND DAYS WE'VE HAD SINCE JANUARY.
<P>
AND THAT NOT ONLY HAD LOCALS AND TOURISTS HITTING THE BEACHES TODAY. IT ALSO PUT A SMILE ON A LOT OF BUSINESS OWNERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Nice Weather-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Nice Weather-G</H3><BR>
IT WASN'T SUCH GOOD NEWS FOR SURFERS. WHO PROBABLY MISSED THE BIG WAVES ASSOCIATED WITH THE STORMS.
<P>
BUT A RAINLESS WEEKEND WAS GREAT NEWS FOR JUST ABOUT EVERYONE ELSE. WHO COULDN'T SAY ENOUGH ABOUT THE SUNNY WEATHER.
<P>
"ALL THESE PEOPLE" IS RIGHT.
<P>
FOR THE FIRST TIME IN WEEKS. THE SUNGLASS-WEARING CROWD HIT THE BEACHES IN DROVES. MAKING OCEAN-SIDE PARKING A SMALL HEADACHE.
<P>
BUT THAT DIDN'T DETER MOST SUN-WORSHIPPERS. EVEN PARKING ENFORCEMENT WAS DONE WITH A SMILE.
<P>
THIS WEEKEND WAS ALSO A BIG BREAK FOR LOCAL BUSINESS OWNERS. WHO HAD TO WAIT OUT THEIR FINANCIAL LOSSES DURING THE STORMS.
<P>
QUAIL LODGE IN CARMEL SAW ABOUT TRIPLE ITS USUAL NUMBER OF GOLFERS THIS WEEKEND.
<P>
AND HOTELS LIKE THE MONTEREY BAY INN BOOKED MORE GUESTS FRIDAY AND SATURDAY. THAN THEY DID ALL PRESIDENT'S DAY WEEKEND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Nice Weather-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Nice Weather-T</H3><BR>
AND YOU CAN ENJOY THIS WEATHER FOR A COUPLE MORE HOURS. BUT AFTER THAT, THE NATIONAL WEATHER SERVICE *DOES* PREDICT SMALL SHOWERS TO START HITTING OUR AREA AGAIN.
<P>
BUT NOTHING LIKE WHAT HIT US ALL LAST MONTH.
<P>
REPORTING LIVE IN SALINAS, I'M J.K. C, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Clinton/Starr>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Starr</H3><BR>
A NEW POLL FINDS PRESIDENT CLINTON MORE POPULAR THAN EVER WITH CALIFORNIA VOTERS.DESPITE ALLEGATIONS HE HAD AN AFFAIR WITH AN INTERN AND URGED HER TO LIE ABOUT IT.
<P>
THE "SAN FRANCISCO EXAMINER" FOUND 60 PERCENT OF THOSE POLLED APPROVE OF HOW CLINTON IS LEADING THE NATION.
<P>
IN ADDITION. A MAJORITY SEES CLINTON AS THE TARGET OF A PARTISAN INVESTIGATION.
<P>
TOP ADVISER RAHM EMANUEL URGE SPECIAL PROSECUTOR KENNETH STARR TO ADMIT HE'S GOT NOTHING ON THE PRESIDENT AND END THE INVESTIGATION.
<P>
BUT REPUBLICAN SENATORS SAY THE REAL FOCUS SHOULD BE ON WHETHER CLINTON HAS TOLD THE TRUTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Septuplets Go Home>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Septuplets Go Home</H3><BR>
IT'S  "FAMILY REUNION TIME" FOR THE IOWA SEPTUPLETS.
<P>
THE LAST TWO BABIES FINALLY JOIN THE REST OF THE MC-KOY BUNCH AT HOME. 
<P>
EVENTHOUGH BABIES NATALIE AND ALEXIS WERE LISTED IN FAIR CONDITION.DOCTORS LET THEM GO HOME. 
<P>
THE TWO BABIES WILL NOW BEGIN THEIR LIFE WITH THEIR SIBLINGS.  KENNETH.  JOEL. KELSEY. AND NATHAN.AS WELL AS OLDER SISTER MIKAYLA. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Liz in Hospital>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Liz in Hospital</H3><BR>
ACTRESS ELIZABETH TAYLOR IS IN A LOS ANGELES HOSPITAL AFTER COLLAPSING ON HER 66TH BIRTHDAY FRIDAY.
<P>
TAYLOR REPORTEDLY FELL DOWN AT HER HOME AND WAS KNOCKED UNCONSCIOUS JUST HOURS BEFORE HER BIRTHDAY PARTY.
<P>
A SPOKESPERSON SAYS TAYLOR HAS BRUISES FROM THE FALL.
<P>
SHE'S EXPECTED TO STAY IN THE HOSPITAL FOR SEVERAL DAYS.
<P>
THE OSCAR-WINNING ACTRESS HAS ENDURED A SERIES OF HEALTH PROBLEMS.INCLUDING: BRAIN SURGERY. HIP REPLACEMENT. AND A SERIOUS RESPIRATORY PROBLEM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Di'S Bodyguard>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Di'S Bodyguard</H3><BR>
PRINCESS DIANA'S BODYGUARD SAYS SHE WAS CONSCIOUS IMMEDIATELY AFTER THE CAR CRASH THAT KILLED HER IN PARIS LAST AUGUST.
<P>
TREVOR REES-JONES. THE LONE SURVIVOR OF THE CRASH. SAYS HE HAS MEMORY "FLASHES" OF DIANA GROANING THEN CALLING OUT TO HER BOYFRIEND, DODI FAYED.
<P>
REES-JONES SPOKE WITH THE TABLOID NEWSPAPER "MIRROR".
<P>
HE SAYS HE'S REMEMBERING BITS AND PIECES OF THE INCIDENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Propane Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Propane Folo</H3><BR>
A BATTLE TO PUT OUT A WISCONSIN PROPANE FIRE HAS TURNED INTO AN UNUSUAL MURDER INVESTIGATION. 
<P>
FIREFIGHTERS FOUND A BODY IN THE TRUNK OF A CAR THAT SLAMMED INTO A PROPANE TANK.
<P>
THE ACCIDENT SPARKED A FIRE IN THE TOWN OF WALLWORTH.
<P>
600 PEPOLE WERE EVACUATED. 
<P>
A WITNESS SAYS SOMEONE JUMPED FROM THE CAR WHEN IT CRASHED. GRABBED THE LICENSE PLATES AND RAN AWAY. 
<P>
INVESTIGATORS ARE OFFICIALLY CALLING THIS A HOMICIDE. AND  AN AUTOPSY IS PLANNED TO DETERMINE THE IDENTITY AND CAUSE OF DEATH.
<P>
        
<P>
        
<P>
        
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=104Iraq Inspectors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Iraq Inspectors</H3><BR>
U-N WEAPONS INSPECTORS ARE GOING ABOUT THEIR BUSINESS IN EEROCK.
<P>
THEY'LL CONTINUE THEIR SEARCH FOR CHEMICAL AND BIOLOGICAL WEAPONS. 
<P>
THE EERAQI GOVERNMENT IS HOPING THE WEAPONS INSPECTORS WILL GIVE THE U-N THE GO-AHEAD TO REMOVE THE SANCTIONS THAT CHOKED THE EERAQI ECONOMY. 
<P>
SINCE THE AGREEMENT BETWEEN THE U-N AND SADDAM HUSSEIN HAS BEEN IN EFFECT, THERE HAVE BEEN NO REPORTS OF INSPECTORS FACING ANY DIFFICULTIES GAINING ACCESS TO KEY SITES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Israel Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Israel Crash</H3><BR>
AN ISRAELI PILOT AND HIS NAVIGATOR ARE KILLED AFTER THEIR F-15 FIGHTER JET CRASHES INTO A HILLSIDE. 
<P>
THE JET WAS ON A TRAINING FLIGHT OVER THE WEST BANK.
<P>
APPARENTLY IT HIT AN ANTENNA BEFORE GOING DOWN. 
<P>
ARMY SEARCH TEAMS SIFTED THROUGH THE WRECKAGE IN HOPES OF REVEALING A DEFINITE CAUSE FOR THE CRASH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Australia Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Australia Crash</H3><BR>
ONLOOKERS AT AN AUSTRALIAN AIRSHOW WATCHED IN HORROR AS A PLANE FLIES  OUT OF CONTROL AND CRASHES. 
<P>
A SPECTATOR'S AMATEUR VIDEO CAPTURED THE TRAGEDY. 
<P>
THE FIRE BOMBING PLANE HAD JUST DUMPED A LOAD OF FOAM WHEN IT FLIPPED AND CAME CRASHING DOWN. 
<P>
THE 42-YEAR-OLD PILOT DIED ON IMPACT WHILE HIS HORRIFIED WIFE WITNESSED THE CRASH. 
<P>
AIR SAFETY INSPECTORS ARE INVESTIGATING THE CAUSE OF THE ACCIDENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=24Peru Mudslides>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Peru Mudslides</H3><BR>
FIFTY LABORERS MISSING AND PRESUMED DEAD FOLLOWING A MUDSLIDE IN PERU HAVE BEEN FOUND ALIVE. 
<P>
THE LABORERS SAVED THEMSELVES BY CLIMBING TO HIGHER GROUND JUST BEFORE A HUGE MUDSLIDE TORE DOWN THE MOUNTAIN. 
<P>
EL NINO-DRIVEN RAINSTORMS HAVE CAUSED NUMEROUS MUDSLIDES IN THE AREA.
<P>
JUST LAST MONTH. TWENTY PEOPLE WERE KILLED IN AN AVALANCHE ONLY 12 MILES AWAY FROM THIS LATEST MUDSLIDE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Fox Hunt Protest-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Hunt Protest-I</H3><BR>
TODAY IN BRITAIN.A PROPOSED BAN ON FOX HUNTING IS STIRRING UP A CULTURE CLASH BETWEEN THE CITY AND THE COUNTRY. 
<P>
FOX'S GREG PALKOT TELLS US THAT'S NOT THE ONLY ISSUE BOTHERING RURAL BRITS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=36Bump #4 (Sports)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump #4 (Sports)</H3><BR>
AHEAD IN SPORTS. THE BULLDOG MAKES HIS GIANT DEBUT. THE UCLA BRUINS FEEL THE BITE OF THE HUSKIES.
<P>
TIGER WOODS COMES UP SHORT AT THE NISSAN OPEN.
<P>
AND THE BILLABONG WAVES GOODBYE TO THE CENTRAL COAST. BUT NOT BEFORE IT GETS A TASTE OF SOME HOME COOKING.     
<P>
ALL THAT AND MORE COMING UP ON THE SUNDAY SPORTS WRAP.    
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39Surfing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Surfing</H3><BR>
LAST YEAR. PETER MEL PUT AND END TO AN 11 YEAR DROUGHT BY SURFING HIS WAY TO FIRST PLACE AT THE BILLABONG BECOMING THE FIRST LOCAL TO WIN THE EVENT SINCE ANTHONY RUFFO IN 1985.
<P>
THIS YEAR. FOUR LOCALS WOULD ADVANCE TO THE FINAL 16. BUT ONLY ONE. CHRIS GALLAGHER OF SOQUEL. WOULD MAKE IT TO THE FINALS.
<P>
AFTER A BIG SWELL  POUNDED STEAMERS LANE EARLIER IN THE WEEK."EL NINO" LIKE CONDITIONS NOTICABLE ABSENT FROM THIS YEARS FINAL. 
<P>
GALLAGHER WAS THE FIRST TO CATCH A WAVE IN THE FINALS AND HE WOULD SET THE TONE EARLY.
<P>
1990 CLARION SURF TOUR CHAMP  WOULD MAKE A RUN WITH SOME STRONG MOVES ON THIS RIDE.
<P>
BUT IN THE END. GALLAGHER WAS ABLE TO HOLD ON TO WIN THE BILLABONG. IT'S THE 2ND STRAIGHT YEAR A LOCAL HAS WON THIS EVENT.
<P>
THE WOMEN'S FINAL CAME DOWN TO A BATTLE BETWEEN TWO SURFERS. OF AUSTRALIA GOING HEAD TO HEAD WITH BRAZILIAN. AND IT WAS SILVA DOING THE DAMAGE EARLY. WITH ONE THE HIGHEST SCORING WAVES OF THE DAY.
<P>
THE AUSSIE WOULD BATTLE BACK.LATE IN THE HEAT. MAKING IT A RACE TO THE FINISH.
<P>
BUT IN THE END IT WAS SILVA TAKING THE TITLE. WITH BROOKE FINISHING IN 2ND.
<P>
AND IN THE EXPRESSION SESSION. IT WAS LOCAL  TAKING HOME THE 1-THOUSAND DOLLAR 1ST PLACE PRIZE. OVERALL A GREAT WEEK OUT AT STEAMERS LANE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
"EL NINO" WAS NO WHERE TO BE FOUND THIS WEEK ON THE PGA TOUR.  
<P>
IN FACT, THE ONLY THUNDER IN THE FINAL ROUND OF THE NISSAN OPEN WAS COMING FROM TIGER WOODS AND BILLY MAYFAIR.
<P>
TIGER 2-SHOTS BACK WHEN THE DAY BEGINS. HE CLOSES WITH A 66. INCLUDING THIS BIRDIE AT 18 GIVING HIM THE LEAD AT 12-UNDER PAR.
<P>
--------
<P>
BUT IT WAS TOO EARLY TO CELEBRATE.  WOULD FORCE A PLAYOFF WITH A GREAT UP AND DOWN OUT OF THE BUNKER AT 18. MAYFAIR CLOSES WITH A 5-UNDER 67. AND WE ARE HEADED TO A PLAYOFF.
<P>
---------- 
<P>
TIGER HAS A CHANCE TO GRAB THE UPPER HAND WITH THE BIRDIE PUTT ON THE 1ST PLAYOFF HOLE. FROM 17 FEET. BUT IT STAYS JUST OUTSIDE THE CUP. TIGER CAN'T BELIEVE IT.
<P>
---------
<P>
THAT WOULD LEAVE MAYFAIR WITH A 4-FOOTER FOR THE VICTORY. AND HE DRAINS IT. BILLY MAYFAIR WINS THE NISSAN OPEN. HIS 1ST VICTORY IN 3-YEARS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
TO THE HARDWOOD NOW. THE WARRIORS CONTINUE THEIR WOEFUL ROAD TRIP WITH A STOP IN CLEVELAND.
<P>
GOLDEN STATE HAS DROPPED THE 1ST THREE GAMES OF THEIR 5-GAME EAST COAST SWING. AND FOUR STRAIGHT OVERALL.
<P>
THE WARRIORS HAVING TROUBLES CONTAINING THE "RAINMAN".  WITH THE THUNDEROUS JAM. CLEVELAND BY FOUR AT THE HALF.
<P>
-------
<P>
KEMP SCORE'S 14 OF HIS TEAM HIGH 28 IN THE 3RD QUARTER ALONE. THE ROAD  WEARY WARRIORS GETTING THUMPED. 
<P>
-------
<P>
. ADDS 17-POINTS AND 13 REBOUNDS AS THE WARRIORS LOSE FOR THE 3RD TIME IN FOUR DAYS. FINAL. 102-82.   
<P>
JIM JACKSON LED GOLDEN STATE WITH 18 POINTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Lakers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lakers</H3><BR>
NEXT. KNICKS HOSTING THE LAKERS AT THE GARDEN.
<P>
---------
<P>
SHAQ HAVING TROUBLES GETTING ANYTHING TO FALL. THE BIG GUY JUST 6-FOR-16 FROM THE FIELD. HE HELD TO 19 POINTS.  CASTS HIS APPROVAL ON THE DEFENSE.
<P>
---------
<P>
MEANTIME.  WAS HEADLINING ON BROADWAY. THE KNICK GUARD TORCHES THE LAKERS FOR 32 POINTS. AS THE KNICKS WIN FOR THE 8TH TIME IN TEN GAMES SINCE THE ALL STAR BREAK. 
<P>
FINAL. 101-89.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43NBA Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA Board</H3><BR>
ELSEWHERE IN THE NBA. THE SONICS HOLD OFF THE SUNS.
<P>
----------
<P>
UTAH BEATS HOUSTON. JOHN STOCKTON WITH 17 POINTS AND 14 ASSISTS FOR THE JAZZ.
<P>
THE CELTICS NIP THE BLAZERS.
<P>
---------          
<P>
MIAMI WINS FOR THE 10TH STRAIGHT TIME.
<P>
THE T-WOLVES NEED DOUBLE OVERTIME TO BEAT THE PISTONS.
<P>
------------
<P>
ATLANTA SPANKS VANCOUVER. AND THE NUGGETS LOSE THEIR 53RD GAME OF THE SEASON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44College Hoops>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>College Hoops</H3><BR>
COMING INTO TODAY'S PAC TEN MATCH-UP BETWEEN UCLA AND WASHINGTON. THE HUSKIES HAD LOST 10 IN A ROW TO THE BRUINS.
<P>
BUT WASHINGTON HAD UPSET ON ITS MIND.
<P>
THE HUSKIES LEAD BY A BUCKET WITH TIME RUNNING OUT. WHEN  CANS THE TRIPLE WITH 12 SECONDS TO PLAY. GIVING THE BRUINS A 1-POINT LEAD.
<P>
--------
<P>
WASHINGTON HAS ONE LAST SHOT. WITH 2 SECONDS TO PLAY. AND  IS CALLED FOR THE FOUL ON THE INBOUNDS.
<P>
---------
<P>
THAT WOULD SEND  TO THE LINE. AND HE HITS BOTH FREE THROWS TO GIVE THE HUSKIES A ONE POINT LEAD. MACCULLOCH LEADS THEM WITH 25.
<P>
--------
<P>
THE BRUINS HAVE ONE LAST SHOT BUT JOHNSON'S SHOT IS OFF THE MARK. AND THE WASHINGTON HUSKIES UPSET THE 18TH RANKED UCLA BRUINS. 95-94 IS THE FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Hoops Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hoops Board</H3><BR>
THE HUSKIES REMAIN IN THE HUNT FOR A TOURNAMENT BID WITH THEIR 17TH VICTORY OF THE SEASON.
<P>
ELSEWHERE. NUMBER FOUR KANSAS WINS TO GRAB THE TOP SEED FOR THE BIG 12 TOURNAMENT.
<P>
---------
<P>
MICHIGAN STATE WILL HAVE THE TOP SEED INT HE BIG TEN TOURNEY DESPITE LOSING TO PURDUE IN O-T.
<P>
TEMPLE BUMPS OFF UMASS IN THE ATLANTIC TEN.
<P>
-------      
<P>
AND TWO MORE AUTOMATIC BIDS GO OUT TODAY FOR THE BIG DANCE. MURRAY STATE BY VIRTUE OF  WINNING THE OHIO VALLEY CONFERENCE TOURNEY. AND RICHMOND GETS THE BID BY WINNING THE COLONIAL ATHLETIC ASSOCIATION TOURNAMENT. SO FAR 7-AUTOMATIC BIDS HAVE GONE OUT. NOW JUST 57 MORE SPOTS TO FILL BEFORE MARCH MADNESS BEGINS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=9849ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
IN NFL NEWS. THE 49ERS HAVE REACHED AN AGREEMENT WITH FREE AGENT QUARTERBACK TY DETMER.
<P>
THE MOVE REUNITES DETMER WITH STEVE MARIUCCI. WHO WAS HIS QUARTERBACKS COACH WHILE HE PLAYED FOR THE PACKERS.
<P>
THE FORMER HEISMAN TROPHY WINNER FROM BYU IS EXPECTED TO BACK UP STEVE YOUNG. TERMS OF THE DEAL HAVE NOT BEEN DISCLOSED.
<P>
TO CACTUS LEAGUE ACTION NOW.
<P>
MAKING HIS SPRING DEBUT FOR THE GIANTS. AS THEY GO UP AGAINST THE CUBS AND FORMER GIANT.
<P>
---------
<P>
THE GIANTS WOULD SEND 11 MEN TO THE PLATE IN THE 1ST INNING.  GETTING TO HIS OLD TEAM WITH A TWO RUN SINGLE OFF. THE GIANTS SCORE 6-RUNS IN THE 1ST. HERSHEISER ALSO WITH A 2-RUN DOUBLE IN THE INNING.
<P>
---------
<P>
ON THE MOUND THE BULLDOG WAS SHARP AS WELL. WORKING TWO SCORLESS INNINGS. GETTING SOME HELP FROM THE DEFENSE ALONG THE WAY.  WITH THE PUTOUT.
<P>
-------
<P>
HERSHEISER ALSO SHOWING EARLY ON THAT HE'S NOT AFRAID TO COME INSIDE. HE PLUNKS. NO DAMAGE DONE THOUGH. THE GIANTS ROUT THE CUBS. 18-1 IS THE FINAL. THE GIANTS ARE NOW 2-1.        
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131A's Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's Board</H3><BR>
AND THE A'S REMAIN UNDEFEATED IN CACTUS LEAGUE PLAY BEATING THE MILWAUKEE BREWERS 8-7. ROOKIE  HAD A HOMER IN THE GAME AS DID. OAKLAND IS NOW 4-0.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Theater/Wheels-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Theater/Wheels-I</H3><BR>
A LANDMARK THEATER IN NEW YORK. PUTS ON  A MOVING PERFORMANCE OF ITS OWN.IT WAS LITERALLY MOVED TO A NEW LOCATION. 
<P>
FOX'S KRISTEN GESSWEIN HAS MORE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=116Theater/Wheels-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Theater/Wheels-G</H3><BR>
NAT UP FROM THE MOVIE "NAUGHTY NINETIES" 
<P>
"Who's on first?" 
<P>
VO: 
<P>
IT'S NOT WHO'S ON FIRST. IT IS A FIRST IN NEW YORK. THE CITY IS 
<P>
MOVING THE EMPIRE, AN EIGHTY-SIX YEAR OLD LANDMARK THEATRE ON 42ND 
<P>
STREET. 
<P>
SOT: 
<P>
"It's a historic theatre anyway because it's where Abbott and 
<P>
Costello performed when I was a little boy back in 1935." 
<P>
VO: 
<P>
FOR THIS PERFORMANCE, THE BUILDING WAS PUSHED ON STEEL WHEELS 168 
<P>
FEET, TO THE END OF THE BLOCK.  
<P>
SOT: 
<P>
1:24:07 
<P>
"There are these hydrolic rams, oil filled cylenders, filled w/ oil 
<P>
simultaneously, the pressure pushes the building across a steel 
<P>
platform." 
<P>
sot: 
<P>
2:15:49 
<P>
"We got it on the girters by putting it on a steel platform  we 
<P>
took the bottom out while we supported it on a piece of steel." 
<P>
VO: 
<P>
FIREFIGHTERS WERE ON HAND IN CASE OF A PROBLEM. 
<P>
SOT: 
<P>
"When you are moving a building that's this many tons, it's an old 
<P>
building, we've got to be be concerned about the possibility of 
<P>
collapse. 
<P>
VO: 
<P>
ENGINEERS CREATED A SAFETY ZONE BY BLOCKING THE STREET AND MOVED THE 
<P>
STRUCTURE SLOWLY AT ABOUT A FOOT A MINUTE.  
<P>

SOT: 
<P>
"When you fisrt look at it, it doesn't look like it's moving.  But if 
<P>
you line it up with a building behind it.  You can see the edge 
<P>
move." 
<P>
VO: 
<P>
WE SPED UP THIS VIDEO TO SHOW YOU THE PROGESS.  WATCH HOW THE CLOCK 
<P>
IS REVEALED. 
<P>
SOT: MOS 
<P>
"I thought this was really amazing." 
<P>
VO: 
<P>
THE SEVEN MILLION POUND BUILDING WAS PUSHED TO IT'S FINAL PLACE IN 
<P>
UNDER FOUR HOURS. 
<P>
SOT: 
<P>
2:26:40 
<P>
"We will lower it and we'll build onthe foundation that already 
<P>
exists and then we'll put brick around it." 
<P>
VO: 
<P>
THE MOVE IS ALL A PART OF A REVITALIZATION PROJECT. THE CITY HOPES 
<P>
THE EMPIRE, WHEN IT'S RENNOVATED WILL DRAW PEOPLE TO THE 
<P>
NEIGHBORHOOD. 
<P>
STAND UP: 
<P>
2:15:49 
<P>
"The curtain  goes up on the Empire next year.  It will become the 
<P>
site of a 25 screen movie theatre.  The building itself will be used 
<P>
as an entrance and the screens will be built in this parking 
<P>
lot--becoming a place to entertain us into the next century.  In New 
<P>
York, Kristen Gesswein, Fox News.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Top Cat!!!>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Top Cat!!!</H3><BR>
THE VOTES HAVE BEEN "TABULATED" AND THE TOP CAT THIS YEAR IS A SNOW WHITE PERSIAN NAMED "LOUIE". 
<P>
ACTUALLY THE CAT'S REAL NAME IS "LOST IN THE CLOUDS". "LOUIE" FOR SHORT. AND HE LOOKS JUST LIKE HIS NAME.A CLOUD WITH A TONGUE HANGING OUT OF IT. 
<P>
THE SIXTEEN-MONTH OLD CAT FROM CHERRY HILL, NEW JERSEY, TOOK THE BEST-IN-SHOW HONORS AT THE 14TH ANNUAL INTERNATIONAL CAT SHOW HELD IN NEW YORK. 
<P>
THE WEEKEND CAT-FEST DREW AN ESTIMATED 35 THOUSAND FELINE-FRIENDLY FANS TO SEE THE 800 HUNDRED FEATURED CRITTERS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
