<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Tuesday, 3/24/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Tuesday, 3/24/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134SQ1 (Arkansas)>SQ1 (Arkansas)</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Arkansas shoot-IN>Arkansas shoot-IN</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(Glenn mail)>(Glenn mail)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Daly City deaths>Daly City deaths</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(F-16 crash)>(F-16 crash)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(bully lawsuit)>(bully lawsuit)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Watsonville murder-I>Watsonville murder-I</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144(cult countdown)>(cult countdown)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Watsonville muder-T>Watsonville muder-T</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/long distanc>Fox Biz/long distanc</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Chualar murder>Chualar murder</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Cactus League>Cactus League</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126SC pot clinic>SC pot clinic</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41MLB Board>MLB Board</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/Alisal >Good News/Alisal </A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Water restrictions>Water restrictions</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43NBA>NBA</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146SC water floridation>SC water floridation</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Fresno St.>Fresno St.</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Coastal purchase>Coastal purchase</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Salinas sewer fees>Salinas sewer fees</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Salinas Snowbird>Salinas Snowbird</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(Glenn) >Bump 1(Glenn) </A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145Basketball birth>Basketball birth</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(F-16) >bump 2(F-16) </A></TD>


<TD BGCOLOR=#FFFFFF> </TD>
</Table>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=134SQ1 (Arkansas)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SQ1 (Arkansas)</H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
A SHOOTING AT AN ELEMENTARY SCHOOL DEVASTATES A TOWN IN ARKANSAS. 
<P>
POLICE SAY THE YOUNG SUSPECTS. PULLED A FIRE ALARM. THEN OPENED FIRE ON THE ENTIRE STUDENT BODY.
<P>
WHEN THE SMOKE CLEARED. FOUR STUDENTS AND TEACHER WERE DEAD. 
<P>
WE'LL HAVE THE LATEST FROM THE SCENE.
<P>
AND AN UPDATE ON A FATAL SHOOTING IN WATSONVILLE.      POLICE SAY THE MURDER MAY HAVE BEEN A CASE OF A CAR JACKING GONE BAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Arkansas shoot-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Arkansas shoot-IN</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
PARENTS AND SCHOOL OFFICIALS ARE IN SHOCK TONIGHT. AFTER AUTHORITIES SAY TWO YOUNG BOYS PULL A FIRE ALARM. THEN GO ON A SHOOTING SPREE. KILLING FOUR GIRLS. A TEACHER. AND WOUNDING 11 OTHERS.
<P>
IT HAPPENED IN JONESBORO, ARKANSAS.
<P>
FOX'S UMA PEMMARAJU HAS MORE FROM THE SCENE. 
<P>
THAT WAS FOX'S UMA PEMMARAJU REPORTING. 
<P>
CHYRONS: 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Daly City deaths>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Daly City deaths</H3><BR>
THE TRAGIC DEATHS OF THREE YOUNG GIRLS IN DALY CITY TAKES A TWISTED TURN. AS POLICE ARREST THE GIRL'S MOTHER FOR THE CRIME.
<P>
POLICE SAY 25-YEAR-OLD MEGAN HOGG SUFFOCATED HER CHILDREN WITH DUCT TAPE.
<P>
THE GIRLS. AGES SEVEN. THREE. AND TWO. WERE FOUND BY THEIR GRANDPARENTS YESTERDAY.
<P>
POLICE INITIALLY THOUGHT THE GIRLS DIED OF CARBON  MONOXIDE POISONING.
<P>
NOW THEY SAY THE MOTHER LEFT NOTES DISCUSSING HER PLANS. THEN TOOK A NON-LETHAL DOSE OF PRESCRIPTION DRUGS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
WATSONVILLE POLICE SAY THEY HAVE THE MAN ACCUSED OF MURDERING A LIMO DRIVER IN CUSTODY.
<P>
        CHERI GYURO IS FOLLOWING THE STORY.SHE JOINS US LIVE FROM OUR SANTA CRUZ COUNTY BUREAU WITH ALL THE DETAILS. CHERI?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Watsonville murder-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Watsonville murder-I</H3><BR>
        ALAN, A WORKER AT A STORAGE FACILITY IN WATSONVILLE MADE THE GRIZZLY DISCOVERY YESTERDAY.THE BODY OF 57-YEAR-OLD DAVID DOUGLAS OF SANTA CRUZ.
<P>
        LESS THAN 24 HOURS LATER.THE LIMO DOUGLAS WAS DRIVING IS DISCOVERED.ALONG WITH THE MAN SUSPECTED OF THE CRIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Watsonville muder-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Watsonville muder-T</H3><BR>
        THE MANAGER AT THE STORAGE FACILITY SAYS DOUGLAS' BODY WAS FOUND NEAR THE SUSPECTS LOCKER.
<P>
        SHE ALSO SAYS THE SUSPECT WAS ACTING STRANGE WHEN HE CAME IN LAST WEEK TO PAY A BILL.ALAN?
<P>
CHERI.DID POLICE TELL YOU WHO THE SUSPECT IS?
<P>
        NO, THEY PROBABLY WON'T RELEASE HIS NAME UNTIL TOMORROW WHEN HE'S TRANSPORTED FROM L.A. BACK TO WATSONVILLE.BUT THEY DO SAY HE IS FROM WATSONVILLE.
<P>
        REPORTING LIVE FROM THE SANTA CRUZ COUNTY BUREAU I'M CHERI GYURO. ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Chualar murder>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chualar murder</H3><BR>
THREE MONTEREY COUNTY TEENAGERS ARE IN CUSTODY TONIGHT. SUSPECTED OF MURDERING A CHUALAR MAN.
<P>
SHERIFF'S DEPUTIES RESPONDED TO REPORTS OF GUNSHOTS ON CLAY STREET LATE LAST NIGHT.
<P>
WHEN THEY ARRIVED. THEY FOUND 30 YEAR OLD IGNACIO VALENCIA LYING OUTSIDE HIS APARTMENT COMPLEX. WITH MULTIPLE GUNSHOT WOUNDS.
<P>
THREE 17-YEAR-OLDS. SEEN RUNNING FROM THE CRIME SCENE. WERE TAKEN INTO CUSTODY.
<P>
VALENCIA WAS TAKEN TO SALINAS VALLEY MEMORIAL HOSPITAL WHERE HE WAS PRONOUNCED DEAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126SC pot clinic>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC pot clinic</H3><BR>
FEDERAL PROSECUTORS WANT A JUDGE TO CLOSE DOWN SIX NORTHERN CALIFORNIA CANNIBUS CLUBS. INCLUDING ONE IN SANTA CRUZ.
<P>
THE U-S ATTORNEYS BEGAN PRESENTING THEIR ARGUMENT IN SAN FRANCISCO TODAY.
<P>
THAT PROMPTED HUNDREDS OF SUPPORTERS OF VOTER-APPROVED MEDICAL MARIJUANA USE. TO MARCH DOWN MARKET STREET AND PROTEST AT THE FEDERAL COURTHOUSE.
<P>
SUPPORTERS SAY THOUSANDS OF PEOPLE SICK WITH AIDS. CANCER AND OTHER ILLNESSES RELY ON MARIJUANA.
<P>
BUT FEDERAL PROSECUTORS SAY IT IS A VIOLATION OF FEDERAL LAW.
<P>
THE JUDGE IS EXPECTED TO MAKE A DECISION IN A COUPLE OF WEEKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/Alisal >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/Alisal </H3><BR>
A COLLEGE EDUCATION IS STILL JUST A DREAM FOR MANY. BUT THERE'S GOOD NEWS FOR DISADVANTAGED STUDENTS OF THE SALINAS UNION HIGH SCHOOL DISTRICT.
<P>
U-C BERKELEY ADMINISTRATORS JOINED DISTRICT OFFICIALS IN SALINAS TODAY TO ANNOUNCE THE BERKELEY INCENTIVE AWARDS PROGRAM.
<P>
IT'S AIMED AT HELPING STUDENTS WHO HAVE OVERCOME GREAT DISADVANTAGES. WHILE MAINTAINING GOOD GRADES.
<P>
EACH YEAR. ONE STUDENT FROM EACH HIGH SCHOOL IN THE DISTRICT WILL RECEIVE A 24 THOUSAND DOLLAR SCHOLARSHIPS TO ATTEND U-C BERKELEY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Water restrictions>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Water restrictions</H3><BR>
WE MAY STILL BE IN THE MIDDLE OF THE RAINY SEASON. BUT PEOPLE ON THE PENINSULA ARE BEING ORDERED TO CUT BACK ON THEIR WATER USE. OR FACE STIFF PENALTIES.
<P>
        BEGINNING TOMORROW. CAL AM WATER COMPANY IS IMPLEMENTING PHASE-FOUR OF ITS MANDATORY WATER CONSERVATION PROGRAM.
<P>
        CUSTOMERS WHO VIOLATE THE RULES. COULD HAVE A WATER RESTRICTOR PLACED ON THEIR METER. LIMITING THE WATER FLOW INTO THEIR HOMES FROM 20 GALLONS A MINUTE. TO JUST SIX GALLONS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146SC water floridation>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC water floridation</H3><BR>
A CONTROVERSIAL DECISION IN SANTA CRUZ IS LEFT UP TO THE VOTERS.
<P>
        SANTA CRUZ CITY COUNCIL MEMBERS HAVE BEEN DEBATING OVER FLUORIDATED WATER FOR THE PAST FEW WEEKS.
<P>
        A STATE MANDATE WILL REQUIRE THE CITY TO PUT THE CHEMICALS IN ITS WATER.AN ATTEMPT TO PROMOTE DENTAL HEALTH.
<P>
        BUT THE CITY COUNCIL CHALLENGED THE MANDATE.SAYING SANTA CRUZ IS A CHARTER CITY.THEREFORE IT HAS THE RIGHT TO REGULATE ITS OWN WATER.
<P>
        TONIGHT.CITY COUNCIL MEMBERS DECIDED TO LET THE PUBLIC MAKE THE DECISION.
<P>
        THE ISSUE WILL BE PLACED ON THE BALLOT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Coastal purchase>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Coastal purchase</H3><BR>
        EFFORTS TO PRESERVE TWO ACRES OF SENSITIVE COASTAL HABITAT. THAT WERE ONCE SLATED FOR DEVELOPMENT. HAVE FINALLY PAID OFF.
<P>
        THE CALIFORNIA COASTAL CONSERVANCY. THIS MORNING. APPROVED THE PURCHASE OF A TWO ACRE PLOT OF LAND.  NEXT TO THE MONTEREY RECREATION TRAIL.
<P>
        THE LOT IS ZONED COMMERCIAL USE. AND COULD HAVE BEEN DEVELOPED. IF CONSERVATION GROUPS HADN'T STEPPED FORWARD.
<P>
THERE WERE MANY DEVELOPMENT PROPOSALS. 200 HOMES, AND OTHER PLANS TO DEPRIVE PUBLIC OF SITE.
<P>
IT USED TO BE PHILLIPS PETROLEUM SITE. STORAGE TANKS, REMOVED, ALSO HOUSES HABITAT FOR SMITHS BLUE BUTTERFLY. AN ENDANGERED SPECIES.
<P>
        THE GROUP WILL PAY 275-THOUSAND DOLLARS FOR THE LAND.
<P>
IT WILL BE MANAGED BY THE STATE PARKS DEPARTMENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Salinas sewer fees>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas sewer fees</H3><BR>
SOME FOLKS IN SALINAS ARE PUTTING UP A  STINK OVER THE FACT THAT SEWER TAXES MAY BE GOING UP. 
<P>
TONIGHT THE CITY COUNCIL HELD A PUBLIC HEARING ABOUT A PROPOSED TAX HIKE. TO UPDATE THE CITY'S 100-YEAR-OLD SEWER SYSTEM. 
<P>
THE COUNCIL SAYS IT CAN'T USE GENERAL FUND MONEY. WITHOUT TAKING RESOURCES FROM PUBLIC SAFETY DEPARTMENTS.
<P>
BUT RESIDENTS SAY THEY SHOULDN'T HAVE TO PAY FOR WHAT THEY CALL "BAD MANAGEMENT".
<P>
THE COUNCIL SAYS THE NEW SEWER SYSTEM WILL COST 12-MILLION DOLLARS. THAT BREAKS DOWN TO 22-DOLLARS PER YEAR PER RESIDENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(Glenn) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(Glenn) </H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
A MYSTERIOUS PACKAGE IS SENT TO A U-S SENATOR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(F-16) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(F-16) </H3><BR>
AND THE AIR FORCE IS INVESTIGATING THE RECENT CRASH OF AN F-16.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A MYSTERIOUS PACKAGE IS SENT TO THE OFFICE OF U-S SENATOR JOHN GLENN IN COLUMBUS, OHIO.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(Glenn mail)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Glenn mail)</H3><BR>
THE PACKAGE APPARENTLY CONTAINED GUN POWDER. WHICH MADE THREE WORKERS' HANDS NUMB AND TURN A SHADE OF PURPLE.
<P>
IT ALSO CONTAINED A 12-PAGE HANDWRITTEN 
<P>
LETTER LACED WITH ETHNIC AND RACIAL SLURS. AND THREATS TO FORMER PRESIDENT REAGAN. 
<P>
THE EMPLOYEES WERE TREATED AT A HOSPITAL AND RELEASED.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(F-16 crash)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(F-16 crash)</H3><BR>
AIR FORCE INVESTIGATORS ARE CHECKING INTO A FIRE THAT FORCED THE PILOT OF AN F-16 FIGHTER JET TO EJECT FROM HIS AIRCRAFT.JUST SECONDS BEFORE IT CRASHED INTO THE RUNWAY.
<P>
IT HAPPENED AT HILL AIR FORCE BASE IN UTAH LAST NIGHT. 
<P>
LIEUTENANT COLONEL JOHN BURGESS PUNCHED OUT OF THE BURNING JET. BEFORE IT NOSED DOWN ONTO A GRASSY LEDGE NEAR THE TARMAC. 
<P>
A TEAM IS NOW INVESTIGATING THE CAUSE OF THE PROBLEM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(bully lawsuit)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(bully lawsuit)</H3><BR>
A MICHIGAN COUPLE IS SUING A LOCAL SCHOOL DISTRICT FOR 11-MILLION-DOLLARS.
<P>
THE COUPLE CLAIMS THIER NINE-YEAR-OLD DAUGHTER WAS BULLIED BY HER CLASSMATES.
<P>
THE PROBLEMS STARTED AFTER THE CHILD COMPLAINED THAT A PREGNANT TEACHER HAD SHOWN PHOTOGRAPHS OF HER ULTRASOUND EXAM IN CLASS.
<P>
THE MOTHER.ROBIN ZAAS SAYS TWO GIRLS SCREAMED IN HER DAUGHTER'S EARS.KNEED HER IN THE BACK.AND STOMPED ON HER FEET.
<P>
POLICE INVESTIGATED.BUT NO CHARGES WERE FILED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144(cult countdown)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(cult countdown)</H3><BR>
MEMBERS OF A CHRISTIAN CULT IN GARLAND, TEXAS SAY 
<P>
GOD WILL SEND A MESSAGE TO THE WORLD TONIGHT. JUST AFTER MIDNIGHT. 
<P>
AND THEY SAY HE'LL DO IT ON TELEVISION. 
<P>
MEMBERS OF  THE "TRUE WAY" CULT OF TAIWAN SAY GOD WILL APPEAR SIMULTANEOUSLY  AROUND THE WORLD ON TELEVISION CHANNEL 18. TONIGHT. AT MIDNIGHT CENTRAL TIME.
<P>
THE CULT ALSO BELIEVES GOD WILL APPEAR IN GARLAND, TEXAS ON MARCH 31ST.
<P>
THEY SAY THEY SELECTED GARLAND BECAUSE IT SOUNDS LIKE "GOD'S LAND". 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/long distanc>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/long distanc</H3><BR>
LONG DISTANCE RATES MAY SOON BE GETTING CHEAPER FOR EVERYONE.
<P>
WE'LL DIAL UP THE DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
THE DISCOUNTS ARE EXPECTED BECAUSE OF INCREASED COMPETITION BY COMPANIES OFFERING SERVICE THROUGH WHAT IS CALLED INTERNET PROTOCOL.
<P>
THREE COMPANIES IN DENVER. INCLUDING QUEST COMMUNICATIONS. ARE OFFERING THE SERVICE RATES CHEAPER THAN THOSE OFFERED BY CONVENTIONAL COMPANIES. AS LOW AS 5-POINT-9 CENTS PER MINUTE.
<P>
THAT'S DRIVING DOWN THE RATES OFFERED BY COMPANIES LIKE M-C-I AND SPRINT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Cactus League>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cactus League</H3><BR>
THE OAKLAND A'S HAD THE FEWEST WINS IN BASEBALL LAST YEAR. AND DREW JUST OVER A MILLION FANS.
<P>
OBVIOUSLY THERE'S PLENTY OF ROOM FOR IMPROVEMENT. AND THAT'S EXACTLY WHAT THEY'RE HOPING FOR IN 1998.
<P>
TONIGHT WE TAKE A LOOK AT THE REVAMPED OAKLAND A'S. A CLUB WITH THE POTENTIAL TO SNEAK UP ON SOME PEOPLE THIS YEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41MLB Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>MLB Board</H3><BR>
NOT A GOOD DAY IN ARIZONA TODAY FOR THE LOCAL TEAMS. IN MESA. THE CUBS POUNDED THE A'S. 15-7.  AND  DID HOMER FOR THE A'S IN THE LOSS.
<P>
AND IN PEORIA.  HIT A TWO-RUN SHOT OFF.THAT HELPED THE PADRES BEAT THE
<P>
GIANTS 7-4. IT'S CAMINITI'S FIRST HOMER OF THE SPRING.
<P>
TOMORROW IN OUR CACTUS LEAGUE REPORT. WE'LL TAKE A LOOK AT THE GIANTS PITCHING STAFF.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
THE N-H-L TRADE DEADLINE HAS COME AND GONE WITH THE SHARKS MAKING A BIT OF NOISE.
<P>
SAN JOSE TRADING TODD GILL TO ST. LOUIS FOR RIGHT WING JOE MURPHY. AND THEY ALSO GET DEFENSEMAN BRIAN MARCHMENT AND DAVID SHAW FROM TAMPA. FOR WINGER ANDREI NAZAROV. 
<P>
MEANTIME. SHARKS HOSTING THE KINGS. NO SCORE IN THE 1ST PERIOD WHEN L-A GIVES ONE AWAY.  WITH THE PUCK AND HE WILL FEED. FORGET ABOUT IT. FRIEZEN SCORES HIS 24TH GOAL OF THE SEASON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43NBA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA</H3><BR>
NBA OWNERS CONTINUE TO DISCUSS A NEW LABOR AGREEMENT IN THEIR ANNUAL MEETINGS. A MOVE THAT COULD LEAD TO A LOCKOUT.  
<P>
THE CURRENT 6-YEAR DEAL EXPIRES JUNE 30 AND IF A
<P>
NEW AGREEMENT IS NOT REACHED BY BY THEN. A LOCKOUT COULD BEGIN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Fresno St.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fresno St.</H3><BR>
FRESNO STATE TAKING ON MINNESOTA IN THE SEMIFINALS OF THE N-I-T.
<P>
--------
<P>
MINNESOTA TRAILS BY THREE LATE IN THE GAME.  CAN'T HIT THE TRIPLE. BUT  IS THERE FOR THE REBOUND AND HE'LL STEP BACK. AND HIT FROM BEYOND THE ARC. GAME TIED AT 77 WITH FOUR POINT EIGHT SECONDS TO PLAY.
<P>
THE BULLDOGS HAVE ONE LAST SHOT.  FOR THE WIN. NO GOOD. AND WE ARE GOING TO OVERTIME.
<P>
---------
<P>
IN THE O-T.  THE GOPHERS TAKE OVER.  WITH 2 OF HIS 24. MINNESOTA SENDS TARKANIAN'S GUYS PACKING.
<P>
FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
TAKING ON  IN THE LIPTON CHAMPIONSHIPS.
<P>
-------
<P>
THIS ONE TIED AT ONE SET APIECE 
<P>
HINGIS IN TROUBLE IN THE 3RD SET. THE UNFORCED ERROR. BLAME IT ON THE RACKET. THE WORLDS NUMBER ONE WOULD RALLY.
<P>
--------
<P>
HINGIS HANGS ON TO WIN THE BATTLE OF THE TEENAGERS. LOOK AT THE DROP SHOT. PRETTY.
<P>
HINGIS BEATS WILLIAMS. 7-4 IN THE 3RD SET TIEBREAKER. SISTER VENUS LOOKING DISSAPPOINTED.   
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Salinas Snowbird>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas Snowbird</H3><BR>
IN THE UNITED STATES WE'VE GOT THE "THUNDERBIRDS". AND THE "BLUE ANGELS".
<P>
CANADA'S TOP GUNS ARE CALLED THE SNOWBIRDS. AND THEY'RE MAKING A RETURN TRIP TO THE CALIFORNIA INTERNATIONAL AIRSHOW.
<P>
TODAY ONE THE TEAM'S PILOTS LANDED AT SALINAS AIRPORT TO SCOUT OUT THE FACILITIES IN ADVANCE OF THIS YEAR'S SHOW.
<P>
HE SAYS THE SNOWBIRDS ARE EXCITED ABOUT COMING BACK TO THE CENTRAL COAST.
<P>
THIS YEAR'S AIRSHOW FALLS ON THE WEEKEND OF SEPTEMBER 26TH AND 27TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145Basketball birth>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Basketball birth</H3><BR>
FINALLY TONIGHT.
<P>
TALK ABOUT  A SPORTS FANATIC.  MARY ANNE FITZGERALD HAD A DECISION TO MAKE. GIVE BIRTH. OR WATCH HER KENTUCKY WILDCATS BATTLE DUKE IN THE N-C-DOUBLE-A TOURNAMENT SUNDAY.
<P>
THE LOUISVILLE WOMAN HAD BEEN IN LABOR. BUT PUT A HALT TO THE DELIVERY WHEN HER TEAM BEGAN STAGING A FURIOUS COMEBACK.
<P>
SHE RECEIVED AN EPIDURAL TO BLOCK THE PAIN. AND ENDED UP DELAYING THE BIRTH BY TEN MINUTES.
<P>
KENTUCKY WON. HER NEW BABY BOY WAS NAMED AFTER ONE OF THE TEAMS STAR PLAYERS. WHO MADE A CLUTCH 3-POINTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
