<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Tuesday, 3/17/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Tuesday, 3/17/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107St. Patty's Day-INT>St. Patty's Day-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(chemical spill)>(chemical spill)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109St. Patty's Day-TAG>St. Patty's Day-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(sex tours)>(sex tours)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139NYC prarade>NYC prarade</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(VMI rats)>(VMI rats)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Clinton/St Pats-INT>Clinton/St Pats-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Crimestop-Olinger-I>Crimestop-Olinger-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#147Sal panhandling>Sal panhandling</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/chase>Fox Biz/chase</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Sal crime prevention>Sal crime prevention</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Sal fire bomb>Sal fire bomb</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Fresno St.>Fresno St.</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Garner gas leak>Garner gas leak</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Fishing emergency>Fishing emergency</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Minority Enrollment>Minority Enrollment</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Rockies>Rockies</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#148SC chancellor obit>SC chancellor obit</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Gore/Quayle 2000-I>Gore/Quayle 2000-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Linscott Leprechaun>Linscott Leprechaun</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
EVERYONE'S GREEN!!!
<P>
ALL DAY FOLKS HAVE BEEN CELEBRATING ST. PATRICK'S DAY.
<P>
AND TONIGHT.THE CELEBRATIONS CONTINUE ACROSS THE CENTRAL COAST.
<P>
OUR REPORTER CHERI O'GYURO HIT SOME OF THOSE BIG PARTIES AND JOINS US LIVE FROM MONTEREY WITH MORE.
<P>
CHERI, I SEE YOU'RE WEARING GREEN TONIGHT!
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107St. Patty's Day-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>St. Patty's Day-INT</H3><BR>
YES I AM.I HAVE A SPLASH OF IRISH IN ME.
<P>
I'M STANDING IN FRONT OF THE GREENEST BAR IN TOWN.O'KANES IRISH PUB ON CANNERY ROW.
<P>
THERE'S A LOT OF PARTYING ON THE CENTRAL COAST.BUT TO SOME FOLKS.ST. PATTY'S DAY ISN'T JUST FOR FUN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109St. Patty's Day-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>St. Patty's Day-TAG</H3><BR>
ASIDE FROM THE SMOKING BAN.THERE'S THE ISSUE OF DRINKING AND DRIVING.
<P>
WE ASKED BOTH THE SALINAS POLICE DEPARTMENT AND THE CALIFORNIA HIGHWAY PATROL ABOUT BEEFING UP ENFORCMENT.AMAZINGLY.NEITHER DEPARTMENT IS GOING TO.
<P>
REPORTING LIVE FROM MONTEREY I'M CHERI GYURO.ALAN BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139NYC prarade>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NYC prarade</H3><BR>
THE 237TH SAINT PATRICK'S DAY PARADE IN NEW YORK CITY DREW HUNDREDS OF THOUSANDS OF SPECTATORS. FROM ALL AROUND THE WORLD TODAY.
<P>
THE OLDEST AND LARGEST PARADE IN THE WORLD INCLUDED THE OBLIGATORY KILTS AND BAGPIPES. AS WELL AS FLOATS AND MARCHING BANDS.
<P>
PROTESTORS FROM THE IRISH LESBIAN AND GAY ORGANIZATION ALSO MADE AN APPEARANCE.
<P>
THE GROUP WAS DENIED AN APPLICATION TO MARCH IN THE PARADE WITH ITS OWN BANNER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Clinton/St Pats-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/St Pats-INT</H3><BR>
PRESIDENT CLINTON SPENT MUCH OF THIS SAINT PATRICK'S DAY.PUSHING FOR PEACE IN NORTHERN IRELAND. 
<P>
HE TALKED WITH IRISH PRIME MINISTER BERTIE AHERN  ABOUT THE PROSPECTS FOR PEACE IN THE REGION. 
<P>
AND LATER HE MET WITH REPRESENTATIVES FROM IRISH CATHOLIC AND PROTESTANT PARTIES. 
<P>
FOX'S WENDELL GOLER HAS MORE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=147Sal panhandling>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal panhandling</H3><BR>
THE SALINAS CITY COUNCIL HAS PASSED A BAN ON AGRESSIVE PANHANDLING WITHIN THE CITY LIMITS.
<P>
AMONG OTHER THINGS. THE NEW ORDINANCE MEANS PEOPLE WILL NO LONGER  BE ABLE TO SOLICIT MONEY AT PLACES LIKE BUS STOPS OR STORES.AND PANHANDLERS MUST STAY FARTHER THAN 25 FEET FROM BANKS AND ATM MACHINES.
<P>
THE FINAL VOTE WAS 6-TO-1. WITH COUNCIL MEMBER JUAN OLIVEREZ. OPPOSING.
<P>
MEMBERS OF THE A-C-L-U IN MONTEREY HAD TRIED TO GET THE CITY COUNCIL TO DELAY THE VOTE UNTIL A SIMILAR ONE WAS DECIDED IN SOUTHERN CALIFORNIA. 
<P>
THE ORGANIZATION STILL HAS THE OPTION OF FILING SUIT TO TRY TO HAVE THE ORDINANCE REVERSED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Sal crime prevention>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal crime prevention</H3><BR>
FEAR IS GROWING IN EAST SALINAS AFTER TWO SHOOTINGS IN TWO DAYS LEAVES ONE MAN DEAD. TWO OTHERS SERIOUSLY HURT.
<P>
BUT DOES LAST WEEKS VIOLENCE MEAN CRIME IS ON THE RISE? 
<P>
SO FAR THIS YEAR THERE HAVE BEEN FIVE MURDERS IN SALINAS.
<P>
POLICE SAY THAT'S ACTUALLY SIMILAR TO LAST YEAR AT THIS TIME.
<P>
BUT BY THE END OF LAST YEAR. SALINAS SAW 19 MURDERS.
<P>
THAT FACT. ALONG WITH THE RECENT VIOLENCE PROVOKED A RESPONSE THIS PAST WEEKEND. A COUNTERATTACK WITH PRAYER.
<P>
WITH ALL THE THINGS.PEACE IN HERE IN SALINAS
<P>
SALINAS POLICE SAY THE MAJORITY OF LAST YEAR'S MURDERS WERE DOMESTIC OR DRUG RELATED. THE TYPE THEY SAY THAT ARE ALMOST IMPOSSIBLE TO PREDICT AND PREVENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Sal fire bomb>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal fire bomb</H3><BR>
AN EARLY MORNING FIRE BOMB ATTACK DESTROYS A VEHICLE. AND DAMAGES A HOUSE IN SALINAS.
<P>
IT HAPPENED AT ABOUT FIVE THIS MORNING ON RANIER DRIVE.
<P>
ONE OF THE TWO HOMEMADE "MOLOTOV COCKTAILS". WAS THROWN INTO A MINI-VAN.
<P>
THE OTHER WAS THROWN ONTO A NEARBY PORCH. DAMAGING A DOOR. AND BURNING A SMALL PORTION OF THE HOUSE.
<P>
NO ONE WAS REPORTED HURT IN THE ATTACKS.AND SO FAR POLICE HAVE NO SUSPECTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Garner gas leak>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Garner gas leak</H3><BR>
SOME TENSE MOMENTS TODAY IN EAST SALINAS. AS A GAS LEAK  FORCES A NUMBER OF RESIDENTS OUT OF THEIR HOMES.
<P>
AROUND TEN THIRTY THIS MORNING. A SMALL BULLDOZER SEVERED A NATURAL GAS LINE ON GARNER AVENUE. 
<P>
FIRE FIGHTERS AND POLICE OFFICERS EVACUATED A DOZEN PEOPLE FROM SURROUNDING HOMES. AND CORDONED OFF A ONE BLOCK AREA.
<P>
PG AND E ARRIVED ON SCENE. CUT OFF THE FLOW. AND THEN PATCHED THE LINE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Fishing emergency>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fishing emergency</H3><BR>
WHILE EL NINO HAS BEEN SENDING ABOVE NORMAL RAIN OUR WAY. THE WEATHER PHENOMENON HAS SENT SQUID AND HERRING IN SEARCH OF COLDER WATERS.
<P>
THAT HAS MADE FOR A TERRIBLE YEAR FOR FISHERMEN.
<P>
TODAY. LOCAL FISHERMEN APPEALED TO THE MONTEREY COUNTY BOARD OF SUPERVISORS FOR RELIEF.
<P>
        ONE COUNTY ANALYST SAYS THE LOSS OF BOTH THE HERRING AND SQUID FISHERIES HAS COST THE LOCAL INDUSTRY 28 MILLION DOLLARS.
<P>
        THE BOARD UNANIMOUSLY APPROVED A RESOLUTION WHICH WILL ALLOW COMMERCIAL FISHERMEN TO APPLY FOR LOW INTEREST LOANS, AND GRANTS TO HELP KEEP THEM AFLOAT, UNTIL THE FISHERIES RETURN. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Minority Enrollment>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Minority Enrollment</H3><BR>
THE END OF AFFIRMATIVE ACTION HAS RESULTED IN A SHARP DROP IN MINORITY ENROLLMENT AT THREE U-C CAMPUSES.
<P>
THE NUMBERS AREN'T IN YET FOR SANTA CRUZ. BUT AT U-C IRVINE--DAVIS--AND SAN DIEGO. MINORITY ADMISSIONS ARE DOWN. EVEN THOUGH APPLICATIONS ARE UP.
<P>
U-C-L-A AND BERKELEY DON'T PLAN TO RELEASE THIER FUGURES UNTIL EARLY NEXT MONTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=148SC chancellor obit>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC chancellor obit</H3><BR>
THE FOUNDING CHANCELLOR OF U-C SANTA CRUZ. DEAN MCHENRY. HAS DIED.
<P>
MCHENRY DIED OF NATURAL CAUSED AT DOMINICAN HOSPITAL IN SANTA CRUZ THIS AFTERNOON. HE WAS 87.
<P>
THE POLITICAL SCIENCE PROFESSOR HELPED PLAN AND OPEN THE SANTA CRUZ CAMPUS IN THE 19-60'S.
<P>
AND WAS APPOINTED CHANCELLOR IN 19-61 FOUR YEARS BEFORE THE UNIVERSITY OPENED.HE RETIRED IN1974.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Gore/Quayle 2000-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gore/Quayle 2000-I</H3><BR>
WHILE FORMER VICE PRESIDENT DAN QUAYLE IS IN NEW HAMPSHIRE LAYING DOWN THE GROUNDWORK FOR HIS WHITE HOUSE BID IN THE YEAR 2-THOUSAND.
<P>
VICE PRESIDENT AL GORE HAS BEEN OFF AND RUNNING 
<P>
THE RACE.EVEN BEFORE THE GATES ARE OPENED. 
<P>
FOX'S CARL CAMERON TAKES A LOOK AT THE ROAD GORE'S TAKING. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A CHEMICAL SPILL IN SOUTHEAST MISSOURI HAS KILLED THOUSANDS OF FISH.AND FORCED THE EVACUATION 
<P>
OF FIFTY FAMILIES. 
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(chemical spill)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(chemical spill)</H3><BR>
OFFICIALS SAY  IT APPEARS THE CHEMICAL. IDENTIFIED AS STYRENE. A SUBSTANCE USED IN AIRPLANE GLUE. WAS INTENTIONALLY LEAKED INTO A CREEK NEAR BLOOMSDALE.
<P>
THE CHEMICAL WAS TRACED TO AN AREA NEAR A REST 
<P>
STOP ALONG INTERSTATE 55. 
<P>
AUTHORITIES SAY THE WATER TURNED A STRANGE GREEN AND KILLED THOUSANDS OF FISH.
<P>
POLICE ARE LOOKING FOR A SUSPECT WHO WAS SEEN NEAR THE AREA AT THE TIME OF THE SPILL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(sex tours)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(sex tours)</H3><BR>
AT LEAST 25 AGENCIES ACROSS THE U-S. ARE UNDER INVESTIGATION TONIGHT FOR OPENLY ADVERTISING "SEX TOURS" THROUGH VIDEOS AND ON THE INTERNET.
<P>
CRITICS SAY THEY'RE PROMOTING PROSTITUTION AND SEX WITH MINORS.
<P>
ORGANIZERS SAY THE TOURS HELP AMERICAN MEN FIND TRUE LOVE AND MARRIAGE OVERSEAS.
<P>
THE U-S JUSTICE DEPARTMENT HAS LAUNCHED THE INVESTIGATION. THEY SAY ANYONE TRAVELING WITH THE INTENT TO HAVE SEX WITH MINORS COULD GET AS MUCH AS TEN YEARS BEHIND BARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(VMI rats)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(VMI rats)</H3><BR>
FOR THE FIRST TIME IN THE 158-YEAR HISTORY OF THE VIRGINIA MILITARY INSTITUTE. FEMALE CADETS HAVE COMPLETED THE GRUELING "RAT LINE".
<P>
THE LINE IS DESIGNED TO BREAK DOWN CADETS. AND START THEM ON THE ROAD TO BECOMING SOLDIERS.
<P>
IT INCLUDES MARCHING FOR FOUR HOURS. THEN CRAWLING THROUGH MUD. AND FINALLY CLIMBING A WET AND SLIPPERY 20-FOOT HILLSIDE. ALL THE WHILE BEING DRAGGED BACK BY UPPER CLASSMEN. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Crimestop-Olinger-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Crimestop-Olinger-I</H3><BR>
A NIGHT TIME PHOTOGRAPHY OUTING IN PACIFIC GROVE TURNS INTO A MURDER CASE ALONG THE WATER'S EDGE.
<P>
NOW SIX MONTHS LATER.INVESTIGATORS AND CRIMESTOPPERS ARE STILL SEEKING THE KILLER OF 17 YEAR OLD KRIS OLINGER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/chase>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/chase</H3><BR>
THE BIGGEST BANK IN THE COUNTRY ANNOUNCES IT'S CUTTING  45-HUNDRED JOBS.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
CHASE MANHATTAN BANK SAYS HALF THE 45-HUNDRED JOBS IT'S ELIMINATING ARE POSITIONS THAT HAVEN'T BEEN FILLED YET.
<P>
THE OTHERS WILL BE STREAMLINED THROUGH ATTRITION AND LAYOFFS.
<P>
A  COMPANY SPOKESMAN ADDS THAT MANY *NEW* JOBS WILL BE CREATED AS THE COMPANY USES THE MONEY IT SAVES TO MAKE NEW INVESTMENTS.
<P>
THE NEW JOBS WILL INCLUDE POSITIONS IN GLOBAL BANKING OPERATIONS, CREDIT CARD BUSINESS, AND OTHER AREAS.
<P>
CHASE MANHATTAN SAYS THE CUTS WILL START IN THE SPRING AND CONTINUE FOR THE NEXT YEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
THE HIGHEST HURDLE ON STANFORD'S ROAD TO THE FINAL FOUR, WILL COME FRIDAY NIGHT IN ST. LOUIS, WHEN THE CARDINAL DOES BATTLE WITH THE BIG 10'S CO-CHAMPION PURDUE BOILMAKERS.
<P>
PURDUE HAS A BALANCED ATTACK, AND A 28 AND 7 RECORD.
<P>
BUT THEIR REAL SECRET WEAPON, IS THEIR COACH. GENE KEADY IS A 5-TIME NATIONAL COACH OF THE YEAR. HE'S WON 6-BIG 10 CHAMPIONSHIPS. BUT IN HIS 18-YEARS AT PURDUE, HE'S NEVER ADVANCED TO THE FINAL FOUR.
<P>
KEADY HAS JOKED THAT HE'LL CAST A SPELL ON STANFORD THIS WEEK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Fresno St.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fresno St.</H3><BR>
IN OTHER COLLEGE BASKETBALL NEWS, LESS THAN 48-HOURS AFTER 60-MINUTES DID A STORY DETAILING THE TROUBLED FRESNO STATE BASKETBALL PROGRAM, HEAD COACH JERRY TARKANIAN IS FORCED TO THROW CENTER AVONDRE JONES OFF THE TEAM, AND SUSPEND RECRUIT KENNY BRUNNER INDEFINATELY.
<P>
FOLLOWING LAST NIGHT'S FRESNO ST. WIN OVER MEMPHIS IN THE N.I.T., JONES AND BRUNNER ALLEGEDLY WAVED A HANDGUN IN A MAN'S FACE, THEY POKED HIM WITH A SAMURI SWORD, THEN STOLE HIS MONEY AND CAMERA.
<P>
ONLY 2-SCHOLARSHIP PLAYERS ON THE FRESNO ST. TEAM HAVE BEEN ELIGIBLE FOR EVERY GAME THIS YEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
TO PRO HOOPS, AND ITS A BATTLE OF THE CELLAR DWELLERS, AS THE WARRIORS HOST THE L.A. CLIPPERS TONITE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
JUST 2-MORE WEEKS UNTIL OPENING DAY. AND THE GIANTS MAIN MAN, BARRY BONDS, IS LOOKING FOWARD TO ANOTHER BIG SEASON, BUT WITH AN EYE ON THE END OF HIS CAREER.
<P>
BARRY ADMITS THE MOST IMPORTANT THING TO HIM IS WINNING, BUT IT ISN'T EVERYTHING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Rockies>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rockies</H3><BR>
MEANWHILE BARRY DOESN'T MAKE THE TRIP TO TUCSON, HE'S HAVING HIS BACK CHECK OUT AS THE GIANTS TAKE ON THE ROCKIES.
<P>
1ST BATTER DARRYL HAMILTON IS ROBBED BY VINNY CASTILLA.
<P>
OREL HERSHISER GETS HIT PRETTY HARD AGAIN.
<P>
LATER ROCKIES ROOKIE TODD HELTON GOES YARD, AS THE ROCKIES GO ON TO WIN.
<P>
FINAL, ROCKIES 5 AND THE GIANTS 2.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
MEANWHILE THE A'S HAVE SPLIT SQUAD PLAYING IN PEORIA, ARIZONA TODAY.
<P>
THE PADRES TONY GWYNN COMES UP WITH THIS LONG SINGLE THAT DRIVES IN 2-RUNS.
<P>
THE PADS BUILD AN 11-NOTHING LEAD, AND THEN HOLD ON TO WIN.
<P>
FINAL, PADRES 15 AND THE A'S 11. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Linscott Leprechaun>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Linscott Leprechaun</H3><BR>
THIRD GRADERS AT LINSCOTT CHARTER SCHOOL IN WATSONVILLE WENT LOOKING FOR A POT OF GOLD TODAY. 
<P>
THE STUDENTS HAVE BEEN STUDYING LEPRECHANS ALL WEEK, AND LAST NIGHT THEY DESIGNED AND BUILT SOME SPECIAL TRAPS. IN HOPES OF CATCHING THE MISCHEVIOUS WEE FAIRIES.
<P>
THIS MORNING THEY ARRIVED TO FIND THEIR CLASS IN CHAOS.BUT NO LITTLE LEPRECHAN TO TAKE THE BLAME.
<P>
WHOEVER VISTED THE CLASSROOM DID TAKE THE TIME TO LEAVE BEHIND SOMES TREATS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
