<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 3/28/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 3/28/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x032804.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Snow Pack-I>Snow Pack-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#20Olympic Park>Olympic Park</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118Snow Pack-G>Snow Pack-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#11Special Olympics>Special Olympics</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Snow Pack-T>Snow Pack-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#10S.C. Bad Heroin>S.C. Bad Heroin</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Final Four>Final Four</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#19Arkansas Funerals>Arkansas Funerals</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123Strawberry Protest>Strawberry Protest</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Clinton/Soweto>Clinton/Soweto</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#18UK Pot Protest>UK Pot Protest</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#99Cactus League>Cactus League</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122N. Ireland>N. Ireland</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121Swiss Inventions>Swiss Inventions</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=120Snow Pack-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Snow Pack-I</H3><BR>
IT'S DEFINITELY *NOT* SNOWING WHERE WE ARE. AND IT'S ACTUALLY PLEASANT OUT HERE RIGHT NOW. BUT IT WAS A DIFFERENT STORY EARLY THIS MORNING.
<P>
SEVERAL INCHES OF SNOW FELL OVER NIGHT AND COVERED PARTS OF SALINAS, CARMEL VALLEY AND THE SANTA CRUZ MOUNTAINS.
<P>
AND IF YOU'RE FAMILIAR WITH HIGHWAY 68. IT EVEN SNOWED ON LAURELES GRADE THIS MORNING.
<P>
VERY CHILLY TEMPERATURES. BUT MANY FAMILIES WE SPOKE TO WELCOMED THE CHANGE OF SCENERY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118Snow Pack-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Snow Pack-G</H3><BR>
IT WAS LIKE TAKING A TRIP TO MAMMOTH. OR LAKE TAHOE. WITHOUT ACTUALLY LEAVING THE CENTRAL COAST.
<P>
THIS MORNING. FAMILIES IN SALINAS AND CARMEL VALLEY WOKE UP TO A WINTER WONDERLAND OF SORTS. COMPLETE WITH SNOW-CAPPED MOUNTAINS AND FROSTY TEMPERATURES.
<P>
BUT FEW SEEMED TO MIND.
<P>
MEANWHILE. IN SANTA CRUZ COUNTY. NOT AS MUCH SNOW AS MOUNT TORO. BUT THE MOUNTAINS STILL GOT THEIR FAIR SHARE.
<P>
THIS WAS THE SCENE ON THE ROAD TO LOMA PRIETA:  HOMES, MAILBOXES AND CARS COVERED IN POWDERY WHITE.
<P>
RESIDENTS HAD TO GET OUT THEIR CHAINS JUST TO DRIVE OUT OF THEIR DRIVEWAYS.
<P>
IT CAME AS A SURPRISE. BUT NOT BY MUCH.
<P>
AND ACCORDING TO THE NATIONAL WEATHER SERVICE. IT LOOKS LIKE IT *WILL* GET WORSE.
<P>
METEOROLOGISTS EXPECT THE COLDEST NIGHT TO COME SUNDAY INTO MONDAY.
<P>
THEY ADMIT. SNOW IS PRETTY UNUSUAL FOR EARLY SPRING. BUT IN AN EL NINO YEAR. ANYTHING CAN HAPPEN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Snow Pack-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Snow Pack-T</H3><BR>
THIS COLD FRONT *ISN'T* RELATED TO EL NINO. IT ACTUALLY COMES FROM THE GULF OF ALASKA.
<P>
BUT AS YOU HEARD. IT MAY GET EVEN COLDER TOMORROW NIGHT. SO YOU MAY WANT TO BUNDLE UP. AND CARRY CHAINS IF YOU'RE HEADING TO THE MOUNTAINS.
<P>
REPORTING LIVE IN SALINAS. I'M J.K. CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=10S.C. Bad Heroin>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>S.C. Bad Heroin</H3><BR>
HEALTH OFFICIALS ISSUE A WARNING TODAY.
<P>
THEY SAY A FLESH-EATING ^BACTERIA^ MAY BE CONTAMINATING ^HEROIN^ IN SANTA CRUZ COUNTY.  
<P>
        ACCORDING TO A  PUBLISHED REPORT. TWO SANTA CRUZ RESIDENTS ^DIED^ FROM WOUND INFECTIONS STEMMING FROM HERION CONTAMINATION.
<P>
        A THIRD PERSON IS HOSPITALIZED DUE TO INFECTION.
<P>
        LOCAL ALCOHOL AND DRUG COUNSELORS ARE PUTTING THE WORD OUT: ABOUT THE DEADLY DRUG.
<P>
6:03/"THESE HAVE BEEN AROUND FOR SOME TIME THIS IS A VERY RESISTANT STRAIN WRE SEEING AND A VERY MEAN STRAIN."
<P>
        APARENTLY, THE INFECTION CAUSES GANGRENE AND RAPIDLY DESTROYS TISSUE.
<P>
        
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=19Arkansas Funerals>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Arkansas Funerals</H3><BR>
MORE TEARS IN ARKANSAS TODAY.
<P>
THE LAST THREE VICTIMS OF  TUESDAY'S SCHOOL SHOOTINGS WERE LAID TO REST.   
<P>
HUNDREDS OF PEOPLE SHOWED UP TO SAY THEIR LAST GOOD-BYES TO 11-YEAR-OLD BRITTANY VARNER.  AND 12-YEAR-OLD STEPHANIE JOHNSON.AND TEACHER.SHANNON WRIGHT. 
<P>
A TOTAL OF FIVE VICTIMS DIED IN THE RAMPAGE. 
<P>
TWO BOYS ARE CHARGED WITH FIVE COUNTS OF CAPITAL MURDER AND TEN COUNTS OF FIRST DEGREE BATTERY IN THE SHOOTINGS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123Strawberry Protest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Strawberry Protest</H3><BR>
HUNDREDS OF PEOPLE TAKE TO THE STREETS IN NEW YORK TO PROTEST THE WORKING CONDITIONS OF STRAWBERRY WORKERS. 
<P>
THEY MARCHED MORE THAN A MILE DOWN BROADWAY PAST STORES SELLING BERRIES. 
<P>
THE UNITED FARM WORKERS SAY 20-THOUSAND PICKERS IN CALIFORNIA HARVEST ABOUT 80 PERCENT OF THE NATION'S STRAWBERRIES. 
<P>
THE U-F-W SAYS.  MOST WORKERS EARN ABOUT 8-THOUSAND DOLLARS A-YEAR WITH NO HEALTH INSURANCE OR BENEFITS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Clinton/Soweto>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Soweto</H3><BR>
PRESIDENT CLINTON CONTINUES HIS AFRICAN TRIP.
<P>
TODAY.HE HONORED THOSE WHO FOUGHT TO END APARTIED. 
<P>
THE PRESIDENT AND FIRST LADY VISITED  A SCHOOL.
<P>
THEY SAT DOWN WITH YOUTH LEADERS TO DISCUSS CRIME AND THE IMPACT OF U-S POLICY ON SOUTH AFRICA'S POOR. 
<P>
LATER.THE PRESIDENT AND FIRST LADY TRAVELED TO THE LARGEST GHETTO WHERE BLACKS WERE SEPARATED FROM WHITES DURING THE APARTIED ERA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=18UK Pot Protest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>UK Pot Protest</H3><BR>
THOUSANDS OF PRO-POT SUPPORTERS OUT IN FULL FORCE TODAY IN LONDON. 
<P>
PROTESTERS WANT TO SHOW THE BRITISH GOVERNMENT THAT PEOPLE WHO SMOKE MARIJUANA ARE NOT CRIMINALS. 
<P>
EDUCATORS. POLITICIANS. AND MEMBERS OF THE MEDICAL PROFESSION ALL PARTICIPATED IN THE PROTEST. 
<P>
MARCHERS FOCUSED ON  BENEFITS CANNABIS CAN PROVIDE TO SUFFERERS FROM A RANGE OF DISEASES. 
<P>
MARIJUANA HAS BEEN ILLEGAL IN BRITAIN FOR THE PAST 27 YEARS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122N. Ireland>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>N. Ireland</H3><BR>
AN ALL-TOO-FAMILIAR SCENE UNFOLDS IN NORTHERN IRELAND.
<P>
A FORMER POLICE OFFICER IS GUNNED DOWN IN THE STREETS.  
<P>
A GROUP OF I-R-A GUERRILLAS.IN RESISTANCE TO CURRENT PEACE EFFORTS.ARE SUSPECTED OF KILLING 52-YEAR-OLD CYRIL STEWART FRIDAY NIGHT. 
<P>
STEWART WAS LEAVING A SUPERMARKET WITH HIS WIFE WHEN TWO MASKED MEN OPENED FIRE ON HIM IN A PARKING LOT.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=20Olympic Park>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Olympic Park</H3><BR>
THOUSANDS OF PEOPLE FLOCK TO CENTENNIAL OLYMPIC PARK TODAY TO CELEBRATE ITS RE-OPENING. 
<P>
THE REDESIGNED PARK INCLUDES THE OLYMPIC RING FOUNTAINS AND A SERIES OF PLAZAS AND WATER GARDENS. 
<P>
OLYMPIC ATHLETES SIGNED AUTOGRAPHS. 
<P>
THERE IS A GLASS MARKER TO HONOR THE GEORGIA WOMAN KILLED WHEN A BOMB EXPLODED THERE DURING THE 19-96 OLYMPICS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=11Special Olympics>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Special Olympics</H3><BR>
THE STANFORD GAME WASN'T THE ONLY BASKETBALL EXCITEMENT TODAY.
<P>
IN FACT MORE THAN 400 SPECIAL OLYMPIC ATHLETES TOOK PART IN A TOURNAMENT RIGHT HERE ON THE CENTRAL COAST.
<P>
THE MONTEREY BAY REGION OF THE SPECIAL OLYMPICS HOSTED THE INVITATIONAL AT PALMA HIGH SCHOOL AND HARTNELL COLLEGE TODAY.
<P>
ABOUT 200 COACHES AND VOLUNTEERS HELPED PUT ON THE EVENT.
<P>
"THERE'S APPROXIMATELY 33-TEAMS THAT HAVE COME FROM DIFFERENT COUNTIES WITH A VARIETY OF DIFFERENT PLAYING SKILLS.  WHY DO I LIKE IT.IT'S THE GREATEST THING I'VE EVER BEEN A PART OF IN THE LAST FEW YEARS."
<P>
"THIS IS MY FIRST TIME PLAYING FOR THE MONTEREY SEALS.  THEY'RE A GOOD TEAM.  I LIKE THEM SO MUCH.  I'LL ALSO BE DOING THE SWIMMING AND BOWLING SOON.  I'M JUST LEARNING MORE AND MORE EVERY DAY."
<P>
THE MONTEREY "SEALS" WON THEIR DIVISION TODAY. BUT ALL THE PARTICIPANTS ARE WINNERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
THE LAST TIME THAT STANFORD MADE IT TO THE FINAL FOUR. F-D-R WAS IN THE WHITE HOUSE AND THE CARDINAL WASN'T THE STANFORD MASCOT. IT WAS THE INDINANS.
<P>
WELL, THEY'D HAVE TO CIRCLE THE WAGON'S IN TODAY'S MATCH-UP AGAINST KENTUCKY. A TEAM THAT IS MAKING ITS 3RD STRAIGHT APPEARANCE IN THE FINAL FOUR.
<P>
STANFORD COMES OUT FIRING ON ALL CYLINDERS. THEY WOULD SCORE THE 1ST 8-POINTS OF THE GAME.  WITH THE BOMB. CARDINAL BY FIVE AT THE HALF. LEE WITH 26.
<P>
---------
<P>
2ND HALF. THE WILDCATS RALLY.  WITH THE STEAL AND THE JAM. CUTTING THE LEAD TO JUST ONE. 
<P>
--------
<P>
KENTUCKY WOULD LEAD BY THREE WITH TIME WINDING DOWN.  LEE DOES IT AGAIN FOR STANFORD. HITTING FROM OUTSIDE THE ARC. THAT TIES THE GAME AT 73. AND WE ARE GOING TO OVERTIME.
<P>
---------
<P>
IN THE O-T.  SCORES SIX OF HIS CAREER HIGH 27. 
<P>
---------
<P>
THE CARDINAL WOULDN'T GO AWAY THOUGH.  WITH ANOTHER TRIPLE TO CUT THE LEAD TO JUST ONE.
<P>
--------
<P>
MISSES 2-FREE THROWS WITH JUST 2-POINT SIX LEFT TO PLAY. BUT  DESPERATION SHOT WON'T GO. STANFORD LOSES BY A SINGLE POINT. 86-85.IN OVERTIME. A GREAT RUN NONTHELESS FOR THE CARDINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Final Four>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Final Four</H3><BR>
THE OTHER SEMIFINAL FEATURES THE ONLY REMAINING NUMBER ONE SEED. AS THE TOP SEEDED TAR HEELS OF NORTH CAROLINA GO UP AGAINST THE UTAH UTES.
<P>
UTAH JUMPING OUT TO AN EARLY LEAD. ALREADY UP BY 9 IN THE 1ST HALF. BURRIES THE TRIPLE. UTAH BY 12.
<P>
---------
<P>
HAD A TRIPLE DOUBLE AGAINST ARIZONA. HE COMES UP 4-ASSISTS SHORT OF REPEATING THE FEAT. MILLER WITH 16 POINTS AND 14 BOARDS.THE UTES LED BY 13 AT THE HALF.
<P>
---------
<P>
CAROLINA WOULD TRAIL BY 15 POINTS SIX TIMES IN THE 2ND HALF.THEY CUT THE LEAD TO 9 LATE IN THE GAME ON THE LAY IN BY.
<P>
--------
<P>
BUT THE UTES HOLD ON. KNOCKING OF THE MIGHTY TAR HEELS. 65-59 IS THE FINAL. IT'S THE 2ND TRIP TO THE FINALS IN SCHOOL HISTORY. UTAH WON THE NATIONAL TITLE BACK IN 1944.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE WARRIORS HAVE THE DAY OFF AFTER LOSING TO THE LOWLY DENVER NUGGETS.
<P>
THEY'LL RETURN TO ACTION ON SUNDAY WHEN THE PORTLAND TRAILBLAZERS COME TO TOWN.
<P>
SPEAKING OF BLAZING. SHARKS IN DALLAS.  BLAZING A TRAIL TO THE NET. BUT HE'S STONNED BY HIS FORMER TEAMMATE.  WITH A GREAT SAVE.
<P>
--------
<P>
STILL 1ST PERIOD. SHARKS ON THE POWER-PLAY AGAIN. WATCH THE PASS FROM.AND  KNOWS WHAT TO DO WITH IT. HIS 27TH GOAL. SHARKS ON TOP 1-ZIP.
<P>
-------
<P>
BIG DAY FOR  BETWEEN THE PIPES. THE SHARKS NETMINDER TALLY'S 36-SAVES. CONTINUING HIS MASTEREY AGAINST DALLAS.
<P>
--------
<P>
SHARKS LEAD 3-1 IN THE 3RD. WHEN BELFOUR GIVES ONE AWAY.   PUTS THE BISCUT IN THE BASKET. HIS 2ND GOAL OF THE GAME AND 16TH OF THE SEASON. SHARKS WIN 4-1. IT'S THEIR 2ND STRAIGHT VICTORY ON THIS 6-GAME ROAD TRIP. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
THE TEEN BEAT IS PUMPING HARD IN WOMEN'S TENNIS. EVIDENCED BY THE ALL-TEEN FINAL IN THE LIPTON CHAMPIONSHIPS.
<P>
17-YEAR OLD  TAKING ON 16-YEAR OLD.
<P>
KOURNIKOVA LOOKING FOR HER 1ST PRO TITLE.
<P>
----------
<P>
1ST SET.KOURNIKOVA DISPLAYING SOME POWERFUL GROUNDSTROKES. MOVING WILLIAMS ALL OVER THE COURT.IT LEADS TO THE EASY OVERHEAD SMASH.SHE TAKES THE FIRST SET, 6-2. 
<P>
----------
<P>
2ND SET. AS SHE DID AGAINST  IN THE SEMI'S.WILLIAMS FIGHTS BACK. THIS TIME IT'S VENUS MOVING KOURNIKOVA FROM SIDE TO SIDE. CLOSING OUT THE POINT WITH THE RIPPED CROSSCOURT WINNER, VENUS WINS THE 2ND SET, 6-4. 
<P>
----------
<P>
SHE LEADS 5-1 IN THE 3RD. AND ON MATCH POINT.KOUNIKOVA CAN'T HANDLE THE HEAT.WILLIAMS WINS. 6-1 IN THE 3RD. IT'S HER 2ND TITLE OF THE SEASON. AND WITH IT SHE COLLECTS A HEFTY 235-GRAND.  FACES  IN THE MENS FINAL ON SUNDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
NOT A GOOD DAY FOR TIGER AT THE PLAYERS CHAMPIONSHIP. THE FORMER STANFORD STAR STRUGGLES TO A 73. HE'S 2-OVER FOR THE CHAMPIONSHIP.
<P>
-------
<P>
PRETTY GOOD DAY. FOR. HE SHOOTS 70. GOOD ENOUGH TO LEAVE HIM IN 2ND PLACE. 3-SHOTS OFF THE LEAD.
<P>
-------
<P>
WOULD BLISTER THE FRONT. WITH A FIVE UNDER 31. BUT HE SHOOTS 39 ON THE BACK. HE'S 7-BACK.
<P>
--------
<P>
OF THIS GUY.  WITH A 69. ONE OF ONLY  6 ROUNDS IN THE 60'S. HE'LL TAKE A 3 SHOT LEAD INTO THE FINAL ROUND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=99Cactus League>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cactus League</H3><BR>
AND FINALLY TONIGHT. WE CONTINUE OUR CACTUS LEAGUE REPORT WITH A LOOK AT THE A'S SLUGGERS.
<P>
GONE ARE THE DAYS OF THE BASH BROTHERS.BUT IN THEIR PLACE. A CROP OF NEW PLAYERS THAT OAKLAND FANS COULD BE CHEERING FOR A LONG TIME TO COME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121Swiss Inventions>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Swiss Inventions</H3><BR>
AND FINALLY.  IT'S THAT TIME OF YEAR AGAIN. FOR THE INTERNATIONAL EXHIBITION OF INVENTIONS IN SWITERLAND. 
<P>
THIS YEAR'S BIG ITEM. "THE SINGING TOILET".AND IT COULD SOON BE SERENADING USERS IN A BATHROOM NEAR YOU. 
<P>
AND YOU AREN'T LIMITED TO JUST ONE SONG.YOU COULD CHOOSE FROM A VARIETY OF SONGS.FROM BIG BAND TO FRANK SINATRA. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
