<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Friday, 3/13/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Friday, 3/13/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106El Charito shoot>El Charito shoot</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Paula Jones today>Paula Jones today</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Salinas shoot folo>Salinas shoot folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Vallarta Arraignment>Vallarta Arraignment</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(foster care)>(foster care)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(lesbian methodist)>(lesbian methodist)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Bilingual ed local-IN>Bilingual ed local-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(ford sex harass)>(ford sex harass)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Bilingual ed local-GU>Bilingual ed local-GU</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22(safe sex payment)>(safe sex payment)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Mo Co court cuts>Mo Co court cuts</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/peaches>Fox Biz/peaches</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130PG rec trail>PG rec trail</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/Hwy 1>Good News/Hwy 1</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Gray Davis gov>Gray Davis gov</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Kennedy drops out>Kennedy drops out</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Picabo>Picabo</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(mckinney) >Bump 1(mckinney) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Aquarium opening>Aquarium opening</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(paula jones) >bump 2(paula jones) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Titanic guy>Titanic guy</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137McKinney verdict-I>McKinney verdict-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Weekend movies-I>Weekend movies-I</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=106El Charito shoot>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>El Charito shoot</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
FOR THE SECOND DAY IN A ROW. A SHOOTING ON SANBORN ROAD IN SALINAS SENDS A MAN TO THE HOSPITAL. AND LEAVES POLICE SEARCHING FOR THE SHOOTER.
<P>

THE VICTIM WAS SHOT SEVERAL TIMES AT THE EL CHARRITO MARKET ON NORTH SANBORN ROAD.
<P>
POLICE SAY THE VICTIM WAS WALKING INTO THE MARKET WHEN HE EXCHANGED WORDS WITH A HISPANIC MALE OVER  THE SUSPECT'S FEMALE COMPANION.
<P>
STILL NO WORD ON THE VICTIM'S CONDITION TONIGHT.
<P>
POLICE ARE LOOKING FOR TWO HISPANIC MALES AND ONE FEMALE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Salinas shoot folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas shoot folo</H3><BR>
STILL NO SUSPECTS IN YESTERDAY'S MURDER OF AN 18- YEAR OLD SALINAS MAN.
<P>
JOSE GARCIA AND HIS FRIEND ALEJANDRO MARTINEZ WERE SITTING IN THEIR CAR. OUTSIDE THE MONTE MART SHOPPING CENTER. WHEN THEY WERE SHOT.
<P>
GARCIA DIED AT THE SCENE.MARTINEZ WAS IN SERIOUS CONDITION LAST NIGHT.
<P>
HOSPITAL OFFICIALS ARE NOT RELEASING ANY FURTHER INFORMATION ON HIS CONDITION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Vallarta Arraignment>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Vallarta Arraignment</H3><BR>
A MARINA MAN ACCUSED OF KILLING HIS STEPSON. 14-YEARS AGO. HAD HIS CASE CONTINUED TODAY.  
<P>
43-YEAR-OLD JACKSON VILLARTA WAS IN COURT FOR A PRELIMINARY HEARING. BUT THE CASE WAS CONTINUED UNTIL APRIL. SO THAT AUTOPSY AND OTHER REPORTS CAN BE COMPLETED.
<P>
VILLARTA IS ACCUSED OF SHOOTING 16-YEAR-OLD CHRISTOPHER DENOYER. AND THEN BURYING HIM IN THE CRAWL SPACE BENEATH HIS SALINAS HOME.
<P>
THE BODY WAS DISCOVERED LAST MONTH  BY ANOTHER FAMILY NOW  LIVING IN THE HOUSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
        HUNDREDS OF PEOPLE PACKED AN AUDITORIUM IN WATSONVILLE TONIGHT.
<P>
FOR A FORUM ON PROPOSITION 227. THE CONTROVERSIAL STATE INITIATIVE THAT PROPOSES TO DO AWAY WITH BILINGUAL EDUCATION.
<P>
        JINAH KIM WAS THERE. AND JOINS US NOW LIVE FROM OUR SANTA CRUZ COUNTY BUREAU WITH THE STORY.
<P>
        JINAH. THIS IS AN ISSUE THAT'S BEEN SPARKING A LOT OF DEBATE LATELY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Bilingual ed local-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bilingual ed local-IN</H3><BR>
        IT'S A HOT TOPIC BECAUSE WE'RE LESS THAN THREE MONTHS AWAY FROM
<P>
HAVING TO VOTE ON IT. BUT IF YOU RECALL. IT GOT EVEN HOTTER YESTERDAY,
<P>
WHEN THE STATE BOARD OF EDUCATION REVERSED ITS 30-YEAR POLICY. AND TOLD
<P>
SCHOOLS IT'S NO LONGER *MANDATORY* TO OFFER BILINGUAL EDUCATION CLASSES.
<P>
        TONIGHT'S FORUM WAS ORGANIZED BY TEACHERS AND PARENTS WHO ARE
<P>
FRANKLY ALARMED AT ALL THIS APPARENT BACKLASH AGAINST BILINGUAL EDUCATION.
<P>
SO THEY INVITED A U.C. BERKELEY PROFESSOR TO EXPLAIN. AND HELP GET
<P>
SUPPORT BEHIND IT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Bilingual ed local-GU>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bilingual ed local-GU</H3><BR>
        BILINGUAL EDUCATION GOT AN ENTHUSIASTIC THUMBS UP AT A FORUM
<P>
IN WATSONVILLE TONIGHT.
<P>
        HUNDREDS OF PARENTS, TEACHERS AND STUDENTS LISTENED IN AGREEMENT
<P>
AS U.C. BERKELEY'S DEAN OF EDUCATION SPELLED OUT WHY PROPOSITION 227 
<P>
MUST *NOT* PASS.
<P>
        IF PASSED BY CALIFORNIA VOTERS IN JUNE, PROP 227 PROMISES TO
<P>
DO AWAY WITH CURRENT BILINGUAL EDUCATION PROGRAMS.  ALL CLASSES WILL BE
<P>
TAUGHT IN ENGLISH. UNLESS A PARENT SHOWS THAT THEIR CHILD HAS SPECIAL
<P>
NEEDS.  AND IF A CHILD CLEARLY HAS A DIFFICULT TIME LEARNING ENGLISH. 
<P>
THEY'LL BE ALLOWED BILINGUAL EDUCATION.BUT FOR ONLY ONE YEAR, INSTEAD OF
<P>
THE CURRENT THREE OR FOUR YEARS.
<P>
        SOME PARENTS.AND MOST EDUCATORS SAY. THAT'S NOT ENOUGH.
<P>
        THE DEBATE IS ESPECIALLY HEATED IN THE PAJARO UNIFIED SCHOOL
<P>
DISTRICT, WHERE THE MAJORITY OF STUDENTS COME FROM SPANISH-SPEAKING
<P>
BACKGROUNDS.
<P>
        BUT EVEN FAMILIES WHO *DON'T* SPEAK SPANISH CAME TO SUPPORT THE
<P>
FORUM TONIGHT. SAYING THEY THINK BILINGUAL EDUCATION BENEFITS ALL
<P>
STUDENTS.
<P>
                
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Mo Co court cuts>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mo Co court cuts</H3><BR>
MONTEREY COUNTY COURT CLERKS WILL SHUT THEIR DOORS MUCH EARLIER STARTING MONDAY.
<P>
ADMINISTRATORS REPORTEDLY SAY THERE'S JUST TOO MUCH WORK PILING UP, BECAUSE OF THE NUMBER OF CRIMES AND A SHORTFALL IN STATE FUNDING.
<P>
14 JOBS ARE ALSO UNFILLED AND THERE'S A HIRING FREEZE.
<P>
BEGINNING NEXT WEEK THE DOORS WILL CLOSE TO THE PUBLIC AT THREE IN THE AFTERNOON, TO GIVE THE CLERKS TIME TO WORK ON THE BACKLOG.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130PG rec trail>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG rec trail</H3><BR>
THE CALIFORNIA COASTAL COMMISSION TODAY. PUTS THE BREAKS ON PLAN TO EXPAND A BIKE TRAIL ON THE MONTEREY PENINSULA.
<P>
IT'S THE PLAN OF THE MONTEREY PENINSULA REGIONAL PARKS DISTRICT TO HAVE A CONTINUOUS 26-MILE RECREATIONAL TRAIL.
<P>
SOME PACIFIC GROVE RESIDENTS DON'T THINK IT'S A GOOD IDEA. FOR THEIR CITY.
<P>
THEY'RE CONCERNED THERE'S NO ROOM ALONG THE NARROW STRETCH OF OCEAN VIEW BOULEVARD.
<P>
TODAY THE COASTAL COMMISSION ADDRESSED THE ISSUE. AND EFFECTIVELY NIXED THE IDEA.
<P>
"WHICH WOULD HAVE MEANT. ALONG OUR SHORELINE."
<P>
A PARKS DISTRICT SPOKESMAN SAYS HE HOPES THE COASTAL COMMISSION'S VOTE DOESN'T MEAN THE AGENCY WONT RECONSIDER IN THE FUTURE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/Hwy 1>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/Hwy 1</H3><BR>
GOOD NEWS FOR BIG SUR RESIDENTS WHO'VE BEEN STRANDED FOR MORE THAN A MONTH.
<P>
AN ALTERNATE ROAD HAS BEEN OPENED TO HELP THEM BYPASS THE DAMAGED HIGHWAY ONE.
<P>
LOCALS CAN TAKE OLD COAST ROAD, WHICH HEADS EAST AT THE BIXBY BRIDGE AND THEN RETURNS TO THE COAST NEAR ANDREW MOLERA STATE PARK.
<P>
THIS ALLOWS FOLKS TO DRIVE AROUND THE HURRICANE POINT SLIDE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Gray Davis gov>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gray Davis gov</H3><BR>
LIEUTENANT GOVERNOR GRAY DAVIS WANTS A PROMOTION.
<P>
DAVIS KICKED OFF HIS CAMPAIGN FOR GOVERNOR THIS MORNING IN MONTEREY. THE FIRST STOP ON A FIVE CITY TOUR.
<P>
DAVIS IS ONE OF SIX DEMOCRATS SEEKING HIS PARTY'S NOMININATION.
<P>
HE SAYS HIS CAMPAIGN WILL FOCUS ON TWO IMPORTANT ISSUES. THE STATE'S ETHNIC DIVERSITY. AND IMPROVING EDUCATION.
<P>
DAVIS IS A VIETNAM VETERAN. A FORMER ASSEMBLYMAN.AND HAS SERVED AS CALIFORNIA'S CONTROLLER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Kennedy drops out>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kennedy drops out</H3><BR>
IN NATIONAL POLITICS. MASACHUSETTS CONGRESSMAN JOSEPH KENNEDY IS CALLING IT QUITS.
<P>
THE SIX-TERM DEMOCRAT ANNOUNCED HE'LL RETIRE FROM CONGRESS IN LIGHT OF THE DEATH OF HIS BROTHER MICHAEL.
<P>
KENNEDY SAYS THE LOSS OF HIS BROTHER GIVES HIM NEW RESPONSIBILITIES TO HIS FAMILY AND TO A BUSINESS HE FOUNDED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(mckinney) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(mckinney) </H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
A VERDICT IN THE COURT MARTIAL OF THE ARMY'S FORMER TOP ENLISTED MAN. ACCUSED OF SEXUAL MISCONDUCT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(paula jones) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(paula jones) </H3><BR>
AND PAULA JONES' ATTORNEYS HAND A JUDGE MORE THAN 7-HUNDRED PAGES OF EVIDENCE AGAINST THE PRESIDENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137McKinney verdict-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>McKinney verdict-I</H3><BR>
A MIXED VERDICT IN THE SEXUAL MISCONDUCT COURT MARTIAL OF SERGEANT MAJOR GENE MCKINNEY. 
<P>
THE ARMY'S FORMER TOP ENLISTED MAN WAS CONVICTED OF ONE COUNT OF OBSTRUCTION OF JUSTICE. BUT JURORS FOUND HIM NOT GUILTY OF EIGHTEEN CHARGES RANGING FROM MISCONDUCT TO SEXUAL ABUSE. 
<P>
FOX'S RITA COSBY REPORTS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Paula Jones today>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Paula Jones today</H3><BR>
PAULA JONES' ATTORNEYS ARE PRESENTING THEIR ARGUMENT FOR KEEPING THEIR CLIENT'S SEXUAL HARASSMENT CASE ALIVE.
<P>
THE TEAM FILED MORE THAN 7-HUNDRED PAGES OF LEGAL DOCUMENTS IN WASHINGTON TODAY. 
<P>
JONES' LAWYERS SAY THE DOCUMENTS ARE PROOF ENOUGH THAT THE CASE AGAINST THE PRESIDENT SHOULD GO FORWARD. 
<P>
BUT PRESIDENT CLINTON'S PERSONAL ATTORNEY SAYS THE DOCUMENTS ARE PART OF A PUBLIC SMEAR CAMPAIGN AGAINST HIS CLIENT. 
<P>
THE PRESIDENT'S LEGAL TEAM HAS ASKED THAT THE ENTIRE CASE BE THROWN OUT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
TWO YOUNG BROTHERS HAVE BEEN CHARGED WITH MURDERING A FIVE-YEAR-OLD FOSTER CHILD LIVING IN THEIR FAMILY'S HOME IN CHICAGO. 
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(foster care)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(foster care)</H3><BR>
THE TWO BOYS. AGES 9 AND 14. ARE ACCUSED OF BEATING THE CHILD TO DEATH WITH THEIR FISTS AND A BELT. 
<P>
THE MEDICAL EXAMINER SAYS THE CHILD DIED OF TEARING OF THE INTESTINE. AND SWELLING OF THE BRAIN. 
<P>
THE BOY WAS TAKEN FROM HIS BIOLOGICAL PARENTS AND PUT INTO FOSTER CARE. AFTER ALLEGATIONS OF PHYSICAL ABUSE. 
<P>
THE BOY'S BROTHERS. WHO WERE LIVING IN THE SAME FOSTER HOME. HAVE BEEN TAKEN INTO PROTECTIVE CUSTODY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(lesbian methodist)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(lesbian methodist)</H3><BR>
A JURY OF UNITED METHODIST MINISTERS HAS FOUND A PASTOR INNOCENT OF DISOBEYING CHURCH RULES. BY PERFORMING A LESBIAN UNITY CEREMONY. 
<P>
THE CASE INVOLVED THE REVEREND JIMMY CREECH. THE SENIOR PASTOR OF THE LARGEST UNITED METHODIST CHURCH IN OMAHA, NEBRASKA. 
<P>
CREECH TESTIFIED HE WAS SIMPLY SERVING THE SPIRITUAL NEEDS OF TWO WOMEN CHURCH MEMBERS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(ford sex harass)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(ford sex harass)</H3><BR>
THE FORD MOTOR COMPANY HAS BEEN HIT WITH A FEDERAL LAWSUIT. CHARGING SEXUAL HARRASSMENT AND RACIAL DISCRIMINATION. 
<P>
TWO AFRICAN AMERICAN WOMEN SAY THEY WERE FONDLED. AND PRESSED FOR SEX FROM THEIR SUPERVISORS AT FORD. 
<P>
THE WOMEN WORK AT THE FORD STAMPING PLANT IN FORD HEIGHTS, ILLINOIS. AND AT THE FORD ASSEMBLY PLANT IN LANSING, ILLINOIS. 
<P>
A SPOKESMAN FOR FORD SAYS THE COMPANY KNOWS ABOUT THE PROBLEM.. AND SAID IT'S GOING TO FIRE THOSE RESPONSIBLE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22(safe sex payment)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(safe sex payment)</H3><BR>
TWO MISSOURI STATE LAWMAKERS ARE PROPOSING A LAW THAT WOULD REWARD FIRST-TIME COUPLES. WITH A THOUSAND BUCKS.
<P>
THE ONLY STIPULATION. THE COUPLE MUST BE FREE OF SEXUALLY TRANSMITTED DISEASES. HAVE NEVER HAD AN ABORTION. AND HAVE NO OUT-OF- WEDLOCK CHILDREN.
<P>
THE LAW ALSO INCLUDES A CLAUSE THAT SAYS IF THE MARRIAGE DOESN'T WORK OUT. THE COUPLES HAVE TO GIVE THE MONEY BACK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/peaches>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/peaches</H3><BR>
SOUTHERN STATES ARE STARTING TO THAW. BUT THE DAMAGE HAS BEEN DONE.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
GEORGIA OFFICIALS SAY THIS WEEK'S COLD SNAP AND FLOODS COULD PUSH CROP DAMAGE PAST 200-MILLION DOLLARS.
<P>
THAT COULD MEAN A 30-PERCENT RISE IN PEACH PRICES THIS YEAR.
<P>
OTHER CROPS INCLUDING COTTON AND SOYBEAN HAVE BEEN SEVERLY DAMAGED. 
<P>
AND AT LEAST 50-PERCENT OF GEORGIA'S BLUEBERRY CROP IS GONE. THAT MEANS BLUEBERRIES WILL PROBABLY NOT BE AVAILABLE IN SUPERMARKETS UNTIL MID SUMMER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
STANFORD'S NOT GOING TO SNEAK UP ANYONE THIS YEAR. THE CARDINAL FISHISHED THE REGULAR SEASON 26 AND 4, AND RANKED 10TH IN THE NATION.
<P>
STANFORD BEGINS PLAY IN THE MIDWEST REGIONAL TODAY VS. A TEAM THEY LOST TO LAST YEAR, THE COLLEGE OF CHARLESTON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE NBA ALWAYS TAKES A BACK SEAT TO COLLEGE HOOPS DURING THE TOURNAMENT.
<P>
BUT TONITE THE WARRIORS VISIT THE PHOENIX SUNS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
TO GOLF, AND TO FLORIDA, FOR THE 2ND ROUND OF THE HONDA CLASSIC.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Picabo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Picabo</H3><BR>
AND FINALLY TO THE SLOPES OF SWITZERLAND.
<P>
AND OLYMPIC GOLD MEDAL SKIER, AMERICAN PICABO STREET, TAKES A SERIOUS SPILL TODAY.
<P>
THIS DURING THE LAST DOWNHILL OF THE WORLD CUP SEASON.
<P>
STREET BREAKS HER LEFT FEMUR, THAT UPPER LEG BONE IS A BIG ONE TO BREAK.
<P>
SHE HAS TO BE HELICOPTERED DOWN THE MOUNTAIN, WHERE SHE NEEDED 3-HOURS OF SURGERY. DOCTORS SAY IT WILL BE MANY MONTHS BEFORE SHE CAN SKI AGAIN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Aquarium opening>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Aquarium opening</H3><BR>
THE MONTEREY BAY AQUARIUM HAS A NEW, SPECIAL EXHIBIT.
<P>
TODAY WAS THE GRAND OPENING OF  *THE INSIDE STORY*. THE  NEW DISPLAY TEACHES VISITORS THE  BEHIND THE SCENES SECRETS OF THE AQUARIUM.
<P>
THE SHOW FEATURES THE SEA OTTER NURSERY WHERE OFFICIALS ARE GETTING THE OTTERS READY TO BE RELEASED INTO THE WILD.
<P>
MARINE SCIENTISTS ALSO GIVE FOLKS AN IDEA OF WHAT IT TAKES TO FEED AND CARE FOR THE CREATURES OF THE SEA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Titanic guy>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Titanic guy</H3><BR>
THE  AQUARIUM IS INVOLVED IN ANOTHER SPECIAL PROJECT AND THE PUBLIC CAN ALSO TAKE PART VIA THE INTERNET.
<P>
THE MAN WHO DISCOVERED THE WRECK OF THE TITANIC IS LAUNCHING THE EXPEDITION.
<P>
ROBERT BALLARD IS THE FOUNDER OF THE *JASON PROJECT* AND HE'LL USE STRATEGICALLY PLACED CAMERAS TO EXPLORE THE MONTEREY BAY AND THE BAHAMAS.
<P>
THE EXPLORATION WILL CONTINUE FOR TWO WEEKS AND INVOLVES MILLIONS OF SCHOOL CHILDREN.
<P>
STARTING MONDAY KIDS CAN WATCH THE EVENT, LIVE, ON THE INTERNET.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Weekend movies-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Weekend movies-I</H3><BR>
HE WOW'D AUDIENCES IN THE MOVIE "TITANIC". AND AS A REWARD LEONARDO DECAPRIO GOT A WHOPPING 20-MILLION FOR HIS NEXT PROJECT.
<P>
FOX'S DOROTHY LUCEY HAS A SNEAK PEAK AT THE "MAN IN THE IRON MASK". 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
