<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Tuesday, 3/3/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Tuesday, 3/3/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Hutchings court slide>Hutchings court slide</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Pacifica slide>Pacifica slide</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(cut from womb)>(cut from womb)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145school bond issue>school bond issue</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(Mckinney trial)>(Mckinney trial)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Sal panhandling-IN>Sal panhandling-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(small plane crash)>(small plane crash)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Sal panhandling-TA>Sal panhandling-TA</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Crimestoppers>Crimestoppers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Amick Plea/Trial>Amick Plea/Trial</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/coast save>Fox Biz/coast save</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Loza murder charge>Loza murder charge</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Prep Basketball>Prep Basketball</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#133Espinoza appeal>Espinoza appeal</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43NBA>NBA</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132SC sex predator>SC sex predator</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#14649ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Monterey dive study>Monterey dive study</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Casey Martin>Casey Martin</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144DUI watson high>DUI watson high</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Tiger Woods>Tiger Woods</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Clinton/drunk drive>Clinton/drunk drive</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142MLB>MLB</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Jordan/Grand jur-IN>Jordan/Grand jur-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50hyatt bell boys>hyatt bell boys</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=127Hutchings court slide>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hutchings court slide</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
THE WRATH OF EL NINO DRIVEN STORMS. THREATENS EVEN MORE HOMES ON THE CENTRAL COAST. THIS TIME ON HUTCHINGS COURT IN NORTH MONTEREY COUNTY.
<P>
A MASSIVE CHUNK OF EARTH HAS GIVEN WAY. SLIDING THE LENGTH OF A FOOTBALL FIELD.
<P>
AT LEAST FOUR HOMES. PERCHED ON TOP OF A HILL. JUST SOUTH OF PAJARO. ARE AFFECTED.
<P>
FROM THE FRONT. YOU'D NEVER KNOW ANYTHING WAS WRONG. BUT AROUND BACK. WHAT USED TO BE GREEN LAWN. IS NOW A HUGE CRATER.
<P>
"I WAS SCARED AND SHOCKED. BECAUSE WE'VE HAD HEAVY RAINS BEFORE. LOST WITH EROSION THIS WAS A HUGE LOT. AT ONE TIME WE DIDN'T SEE IT HAPPENING BUT SAY A HUGE CRACK STARTING NEIGHTBORS SIDE. CAME ACROSS SORT OF FELL AWAY."
<P>
THE ARNOLDS SAY GEOLOGISTS HAVE BEEN OUT TO LOOK AT THE SLIDE. BUT REPAIRS WILL COST TOO MUCH FOR ANY ONE FAMILY TO AFFORD.
<P>
SO THE FOUR FAMILIES ARE GOING IN ON A PROPOSAL. AND HOPE FEMA. AND SMALL LOANS WILL HELP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Pacifica slide>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pacifica slide</H3><BR>
THE PEOPLE IN HUTCHINGS COURT AREN'T ALONE.
<P>
WEEKS OF HEAVY RAINS. STRONG TIDES AND WAVES HAVE TAKEN THEIR TOLL ON HOMES IN PACIFICA.
<P>
FIERCE EL NINO WEATHER HAS BEEN CHIPPING AWAY AT THE CLIFFS AND THREATENING NINE RED-TAGGED CLIFF HOMES.  
<P>
EARLY THIS MORNING. ONE OF THE HOMES SUCCUMBED TO THE SATURATED CLIFF.  
<P>
A ROOM-SIZED SECTION OF THE HOUSE FELL TOWARD THE OCEAN.
<P>
LUCKILY. NO ONE WAS HURT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145school bond issue>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>school bond issue</H3><BR>
THE STATE SENATE HAS APPROVED WHAT COULD BE THE BIGGEST BOND MEASURE IN STATE HISTORY.
<P>
THE PROPOSAL TO FIX UP CALIFORNIA SCHOOLS. WAS PASSED BY THE SENATE AFTER AN INITIAL PUSH FAILED TO GET ENOUGH VOTES.
<P>
THE BILL WOULD DEVOTE 9-BILLION DOLLARS TO SCHOOL FACILITY PROJECTS STATE-WIDE.
<P>
6-BILLION WILL BE USED FOR KINDERGARDEN THROUGH 12TH GRADES.
<P>
3-BILLION FOR U-C, C-S-U. AND CALIFORNIA COMMUNITY COLLEGES.
<P>
THE MEASURE NOW HEADS TO THE ASSEMBLY. WHERE MANY SAY. IT'S CHANCES OF PASSING ARE SLIM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Sal panhandling-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal panhandling-IN</H3><BR>
ALAN, IT'S A SCENE MOST OF US ARE USED TO.WALKING DOWN THE STREET.SOMEONE COMES UP AND ASKS FOR SPARE CHANGE.
<P>
IT'S A SITUATION THAT MAKES SOME PEOPLE FEEL UNCOMFORTABLE.
<P>
THAT'S WHY CITY COUNCIL MEMBERS WANT TO FINE TUNE EXISTING LAWS ABOUT PANHANDLING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Sal panhandling-TA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sal panhandling-TA</H3><BR>
COUNCIL MEMBERS VOTED TO PUT THIS ISSUE ON HOLE UNTIL THEY SPEAK TO THE ACLU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Amick Plea/Trial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Amick Plea/Trial</H3><BR>
A SUSPECTED SERIAL RAPIST IS ON TRIAL ONCE AGAIN FOR ANOTHER ATTACK ON A YOUNG WOMAN.
<P>
20-YEAR-OLD RICHARD AMICK OF APTOS HAS ALREADY PLED GUILTY TO RAPING TWO YOUNG WOMEN.
<P>
NOW HE'S ON TRIAL FOR ANOTHER RAPE HIS ATTORNEY SAYS HE DIDN'T COMMIT.
<P>
TODAY TWO WOMEN TOOK THE WITNESS STAND FOR THE PROSECUTION.
<P>
BOTH WOMEN SAY AMICK FIXED THEM A MIXED DRINK. AND 20 MINUTES LATER THEY LOST COMPLETE CONTROL OF THEIR MOTOR SKILLS.
<P>
"I JUST FELT OUT OF IT WHETHER I WAS DREAMING
<P>
OR NO WHAT WAS GOING ON AND HE WAS HAVING SEX WITH ME.
<P>
HE WAS HAVING SEX WITH ME."
<P>
INVESTIGATORS IN THE CASE SAY THEY'VE IDENTIFIED AT LEAST FIVE VICTIMS. WHO SAY RICHARD AMICK SEXUALLY ASSAULTED THEM WHILE THEY WERE PASSED OUT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Loza murder charge>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Loza murder charge</H3><BR>
A TWO YEAR OLD GIRL ALLEGEDLY BEATEN BY HER MOTHER'S BOYFRIEND HAS DIED IN AN OAKLAND HOSPITAL.
<P>
THE BRUTAL ATTACK HAPPENED IN STOCKTON LAST WEEK.
<P>
THE MAN AUTHORITIES SAY BEAT THE LITTLE GIRL. ISAAC LOZA FLED TO SALINAS. WHERE HE WAS ARRESTED LAST THURSDAY.
<P>
LOZA. HAS BEEN CHARGED WITH MURDER. TORTURE. AND CHILD ABUSE.
<P>
HE REMAINS BEHIND BARS IN THE SAN JOAQUIN COUNTY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=133Espinoza appeal>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Espinoza appeal</H3><BR>
A FORMER SAN BENITO COUNTY RESIDENT. CONVICTED OF KILLING HER ESTRANGED HUSBAND THREE YEARS AGO. IS TRYING TO GET HER PRISON SENTENCE REDUCED.
<P>
MARTHA KELLY. FORMERLY MARTHA ESPINOZA. WAS SENTENCED TO 14 YEARS IN PRISON FOR KILLING HER ANGEL ESPINOZA.
<P>
AN APPELLATE COURT IN FRESNO OVERTURNED PART OF HER CONVICTION. STATING SHE WAS SENTENCED IMPROPERLY.
<P>
THE INVOLUNTARY MANSLAUGHTER STILL STANDS THOUGH. WHICH MEANS SHE WILL NOT GO FREE. BUT MAY HAVE HER SENTENCED REDUCED.
<P>
ESPINOZA APPEARED IN COURT TODAY AND  THE JUDGE IN THE CASE IS NOW REVIEWING ALL THE FILES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132SC sex predator>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC sex predator</H3><BR>
SANTA CRUZ COUNTY DISTRICT ATTORNEY ART DANNERS IS VOWING TO KEEP A CONVICTED PEDOPHILE OFF THE STREETS. DESPITE THE FACT THE MAN'S SET TO BE RELEASED FROM PRISON ON MONDAY.
<P>
DANNER HAS PETITIONED THE SANTA CRUZ COUNTY SUPERIOR COURT TO HAVE GRORY GRANT COMMITTED TO A STATE MENTAL HOSPITAL AS A SEXUALLY VIOLENT PREDATOR.
<P>
IN 1983. GRANT WAS CONVICTED ON A NUMBER OF CRIMES INCLUDING A FORCIBLE LEWD ACT ON A CHILD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Monterey dive study>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Monterey dive study</H3><BR>
A NEW STUDY SHOWS DIVERS ARE HAVING A SERIOUS IMPACT ON THE UNDERWATER ENVIRONMENT OF THE MONTEREY BAY.
<P>
AN ESTIMATED 65 THOUSAND DIVES TAKE PLACE EACH YEAR.
<P>
ONE RESEARCHER FROM THE MOSS LANDING MARINE LAB LOOKED INTO WHAT EFFECT THE DIVES MAY BE HAVING.
<P>
        TIM SCHAEFFER FOLLOWED 42 DIVERS LAST SUMMER.
<P>
        HE FOUND ON AVERAGE THAT EACH DIVER TOUCHES THE SEA FLOOR OVER 40 TIMES IN A HALF HOUR DIVE.
<P>
IN ADDITION DIVERS TOUCH OR PICK UP AT LEAST FOUR MARINE ANIMALS. AND TEAR OFF ABOUT 2 FRONDS OF KELP.
<P>
THE NUMBERS THEMSELVES NOT VERY IMPRESSIVE. BUT TAKE INTO CONSIDERATIONS 65 THOUSAND DIVERS A YEAR. ANIMALS PICKED UP.
<P>
ONE LOCAL DIVER CALLED THE STUDY BOGUS BECAUSE HE SAYS IT FOLLOWED BEGINNING DIVERS IN AN AREA USED FOR TRAINING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144DUI watson high>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>DUI watson high</H3><BR>
A MAN WHO KNOWS FIRST HAND THE DISASTEROUS RESULTS OF DRINKING AND DRIVING. IS NOW SHARING THAT LESSON WITH LOCAL HIGH SCHOOL KIDS.
<P>
JIM ROCKWELL WAS IN A DRUNK DRIVING ACCIDENT 13 YEARS AGO THAT LEFT HIM DISABLED.
<P>
TODAY HE TALKED TO MORE 600 HIGH SCHOOL STUDENTS IN WATSONVILLE. ABOUT WHAT CAN HAPPEN WHEN A DRUNK DRIVER GETS BEHIND THE WHEEL OF A CAR. 
<P>
"THE BEST THING YOU CAN DO. HELP THEM TO LEARN FROM YOUR LIFE."
<P>
ROCKWELL HOPES HIS MESSAGE TO THESE WATSONVILLE HIGH STUDENTS WILL SAVE LIVES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Clinton/drunk drive>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/drunk drive</H3><BR>
THE SAME ISSUE WAS ON THE MIND OF THE PRESIDENT TODAY. 
<P>
AT A WHITE HOUSE CEREMONY.  PRESIDENT CLINTON ANNOUNCED HIS SUPPORT FOR A PROPOSAL IN CONGRESS. THAT WOULD REQUIRE STATES TO LOWER THE LIMIT FOR BLOOD ALCOHOL LEVELS. 
<P>
RIGHT NOW MOST STATES CONSIDER A PERSON LEGALLY DRUNK IF THEIR BLOOD ALCOHOL LEVEL IS POINT-ONE-OH PERCENT. 
<P>
IN CALIFORNIA IT'S A STRICTER POINT-OH-EIGHT PERCENT. CLINTON WANTS THAT LEVEL TO BE ADAPTED NATION-WIDE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Jordan/Grand jur-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jordan/Grand jur-IN</H3><BR>
THE MONICA LEWINSKY INVESTIGATION TOOK AN IMPORTANT TURN TODAY. 
<P>
ONE OF THE KEY WITNESSES IN THE CASE.LONGTIME CLINTON FRIEND VERNON JORDAN.SPENT THE DAY IN FRONT OF THE GRAND JURY. 
<P>
FOX'S DAVID SHUSTER HAS THE DETAILS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A CASE THAT SHOCKED CHICAGO. A MOTHER MURDERED. HER UNBORN BABY CUT FROM HER WOMB. IS ABOUT TO GO TO TRIAL.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(cut from womb)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(cut from womb)</H3><BR>
IT HAPPENED IN NOVEMBER 19-95. POLICE SAY THE BABY'S FATHER AND TWO ACCOMPLICES. MURDERED THE MOTHER AND HER TWO CHILDREN. AND CUT HER 9-MONTH OLD BABY FROM HER WOMB.
<P>
THE BABY SURVIVED. 
<P>
THE LONE WITNESS. A 2-YEAR-OLD TODDLER. IS EXPECTED TO TESTIFY IN THE TRIAL.
<P>
POLICE SAY THE BOY IS STILL SHAKEN BY THE EVENT BUT CAN TALK ABOUT IT.
<P>
THE TRIAL IS EXPECTED TO START ON MONDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(Mckinney trial)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Mckinney trial)</H3><BR>
THE ARMY'S FORMER TOP ENLISTED MAN TOOK THE STAND TODAY. AT HIS COURT MARTIAL ON SEXUAL MISCONDUCT CHARGES.  
<P>
TESTIFYING IN HIS OWN DEFENSE.  GENE MCKINNEY DENIED GROPING. OR PRESSURING SIX FEMALE SUBORDINATES FOR SEX WHILE HE WAS SERGEANT MAJOR OF THE ARMY.
<P>
MCKINNEY FACES MORE THAN 55 YEARS IN PRISON. IF FOUND GUILTY OF ALL NINETEEN COUNTS AGAINST HIM. 
<P>
HIS LAWYER EXPECTS TO WRAP UP HIS CASE BY THE END OF THE WEEK. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(small plane crash)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(small plane crash)</H3><BR>
TWO MEN AND FOUR CHILDREN ARE DEAD AFTER A SMALL PLANE CRASHES IN SOUTHWESTERN IDAHO. 
<P>
OFFICIALS SAY THE PLANE WENT DOWN LAST NIGHT IN A REMOTE AREA NEAR BOISE 
<P>
THE VICTIMS HAD TAKEN THE FLIGHT TO CELEBRATE THE BIRTHDAY OF ONE OF THE CHILDRENS.
<P>
STILL NO WORD ON WHAT CAUSED THE CRASH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Crimestoppers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Crimestoppers</H3><BR>
CRIMESTOPPERS TONIGHT IS OFFERING A REWARD OF UP TO ONE THOUSAND DOLLARS FOR INFORMATION ABOUT A SUSPECTED GANG MEMBER WHO ROBBED AND BRUTALLY BEAT TWO PEOPLE DURING A HOME INVASION. 
<P>
19 YEAR OLD SONNY ANGEL MORENO IS 6 FEET TALL. AND WEIGHS 125 POUNDS. HE HAS A VERY DISTICTIVE CHARACTERISTIC. THE LETTERS "V S L" TATTOOED ACROSS HIS CHEST.
<P>
POLICE SAY MORENO. WHO CLAIMS TO BE A NORTENO GANG MEMBER.  ROBBED AN APARTMENT IN SAN LUCAS AND REPEATEDLY STABBED TWO PEOPLE INSIDE. 
<P>
IF YOU HAVE ANY INFORMATION ON MORENO'S WHERE ABOUTS.
<P>
CALL THE CRIMESTOPPERS ANONYMOUS LINE AT 1 800 499 CRIME.
<P>
IF YOUR CALL LEADS TO THE ARREST OF A SUSPECT.YOU COULD BE ELIGIBLE FOR A REWARD OF UP TO ONE THOUSAND DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/coast save>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/coast save</H3><BR>
IT'S HARD TO KEEP TRACK OF JUST WHICH BANKS ARE JOINING FORCES THESE DAYS. AND NOW A HUGE MERGER ON THE CENTRAL COAST WILL AFFECT HUNDREDS OF CUSTOMERS.
<P>
DETAILS IN TONIGHT'S FOX BUSINES REPORT.
<P>
COAST FEDERAL BANK HAS MERGED WITH HOME SAVINGS OF AMERICA.
<P>
THIS WILL MEAN DIFFERENT THINGS FOR CUSTOMERS IN DIFFERENT CITIES.
<P>
THE COAST BRANCHES ON ALVARADO STREET IN MONTEREY AND IN PACIFIC GROVE WILL BOTH BE CLOSED.AS WELL AS THE HOME SAVINGS BRANCH ON SOUTH MAIN IN SALINAS.
<P>
AFFECTED BRANCHES WILL CLOSE AT THREE THIS FRIDAY.AND REMAIN CLOSED THROUGH THE WEEKEND TO HELP WITH THE CHANGE-OVER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Prep Basketball>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Basketball</H3><BR>
THE C.C.S. PREP BASKETBALL PLAYOFFS CONTINUE TONITE, AND WE'VE REACHED THE SEMI-FINALS.
<P>
WE BEGIN WITH THE BOYS DIVISION I BRACKET, WHERE THE HOLLISTER HAYBALERS, 21 AND 8 OVERALL AND THE 6TH SEED, FACE THE 2ND SEED, ST. IGNATIUS HIGH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43NBA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA</H3><BR>
WE'VE GOT AN INTERESTING MATCHUP IN THE NBA TONITE, AS THE 2-TIME DEFENDING NBA CHAMPION CHICAGO BULLS PLAY HOST TO THE 5 AND 53 DENVER NUGGETS.
<P>
ITS PERHAPS THE BEST OF ALL-TIME VS. PERHAPS THE WORST OF ALL-TIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=14649ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
IN A MOVE THAT UNFORTUNATELY WAS EXPECTED, TODAY THE 49ERS RELEASE A KEY PLAYER FROM LAST YEAR'S OFFENSE.
<P>
RUNNING BACK TERRY KIRBY WAS LET GO TODAY, SAVING THE 49ERS ALMOST 700-THOUSAND DOLLARS IN SALARY CAP ROOM.
<P>
WHEN THE NINERS GAVE GARRISON HEARST THE BIG CONTRACT A FEW WEEKS AGO, YOU KNEW KIRBY'S DAYS IN SAN FRANCISCO WERE NUMBERED.
<P>
BACKING UP HEARST LAST YEAR, KIRBY GAINED 418-YARDS RUSHING, AND 279-YARDS RECEIVING.
<P>
NOT TO MENTION A CAREER BEST 120-YARDS ON THE GROUND VS. THE VIKINGS IN THE PLAYOFFS.
<P>
BUT AS NINERS GM DWIGHT CLARK PUT IT, IN THIS DAY AND AGE OF THE SALARY CAP, ITS HARD TO KEEP A MILLION DOLLAR BACKUP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Casey Martin>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Casey Martin</H3><BR>
FOR THE FIRST TIME SINCE HE WON THE RIGHT TO USE A GOLF CART, CASEY MARTIN WILL DO JUST THAT, AS HE TEES IT UP THIS WEEK AT THE NIKE TOUR EVENT IN AUSTIN, TEXAS.
<P>
NOW THE NIKE TOUR IS THE MINOR LEAGUE'S OF GOLF, NORMALLY  THIS EVENT GETS ABOUT 20 MEDIA REQUESTS. BUT WITH MARTIN PLAYING THEY'VE HAD OVER 150 CREDINTIALS REQUESTED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Tiger Woods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tiger Woods</H3><BR>
MEANWHILE ON THE PGA TOUR, MARTIN'S FORMER COLLEGE TEAMMATE, TIGER WOODS IS PREPARING FOR THIS WEEK'S DORAL RYDER OPEN IN MIAMI.
<P>
LAST WEEK IN L.A., TIGER LOST IN A PLAYOFF TO BILLY MAYFAIR. WOODS HASN'T WON ON TOUR SINCE JULY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142MLB>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>MLB</H3><BR>
FINALLY IN BASEBALL NEWS, THE VETERAN'S COMMITTEE OF THE HALL OF FAME ADDS 4-NAMES FOR ENSHRINEMENT TO COOPERSTOWN. LEADING THE LIST, IS LARRY DOBY, WHO'S SORT OF THE BUZZ ALDRIN OF BASEBALL. DOBY WAS THE 2ND BLACK PLAYER IN THE MAJORS, FOLLOWING JACKIE ROBINSON BY ONLY A FEW WEEKS. AND PLAYING FOR THE CLEVELAND INDIANS, MADE DOBY THE "FIRST" BLACK PLAYER IN THE AMERICAN LEAGUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50hyatt bell boys>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>hyatt bell boys</H3><BR>
SOME LOCAL KIDS TRY THEIR HAND AT ONE OF THE CENTRAL COAST'S BIGGEST INDUSTRIES.
<P>
FIFTH GRADERS FROM ONE LOCAL SCHOOL ATTENDED 'CAMP HYATT" A DAY-LONG  INTRODUCTION TO THE HOSPITALITY INDUSTRY.
<P>
        THE YOUNG PEOPLE TRIED  THEIR HANDS AT THE BELL DESK. THE FRONT DESK AND AS CONCIERGE.
<P>
        SOME OF THE YOUNGSTERS EVEN DONNED CHEFS UNIFORMS AND HELPED OUT IN THE KITCHEN.
<P>
        THE GOAL OF THE PROGRAM IS TO GET THE STUDENTS  INTERESTED IN THE TOURISM INDIUSTRY AT AN EARLY AGE. AND SHOW THEM THE DIFFERENT JOB OPPORTUNITIES IN THE FIELD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
