<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Tuesday, 3/10/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Tuesday, 3/10/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Flouride H2O-INT>Flouride H2O-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Flouride H2O-GUT>Flouride H2O-GUT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(bus/train ax)>(bus/train ax)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Flouride H2O-TAG>Flouride H2O-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(Willey/grand jury)>(Willey/grand jury)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126SC rapist>SC rapist</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(SAG strike)>(SAG strike)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Moore court>Moore court</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Lloyd Bridges dies-I>Lloyd Bridges dies-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Anderson rejected>Anderson rejected</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/insurance>Fox Biz/insurance</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125SUHD audit results>SUHD audit results</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Prep Basketball>Prep Basketball</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Pajaro warning sirens>Pajaro warning sirens</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41R.L.S. Girls Hoops>R.L.S. Girls Hoops</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Immigrant smuggling>Immigrant smuggling</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Food bank study>Food bank study</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43All-Americans>All-Americans</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135coastal commission>coastal commission</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/packard>Good News/packard</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(weather) >Bump 1(weather) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Significant others>Significant others</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(Bridges) >bump 2(Bridges) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Taco bell protest>Taco bell protest</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Midwest weather-IN>Midwest weather-IN</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=107Flouride H2O-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Flouride H2O-INT</H3><BR>
         GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
        PROPONANTS SAY IT CUTS DOWN ON DENTAL PROBLEMS. OPPONANTS SAY IT'S A DANGEROUS CHEMICAL.
<P>
BUT IT'S UP TO THE SANTA CRUZ CITY COUNCIL TO DECIDE WHETHER OR NOT TO COMPLY WITH A STATE MANDATE TO FLORIDATE THE CITY'S DRINKING WATER.
<P>
CHERI GYURO WAS AT TONIGHT'S COUNCIL MEETING AND HAS THE STORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Flouride H2O-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Flouride H2O-GUT</H3><BR>
                        FLUORIDATE GUTS 3
<P>
        IT'S SOMETHING WE HARDLY THINK ABOUT EVERYTIME WE TAKE A DRINK OF WATER.WHAT CHEMICALS ARE GOING INSIDE MY BODY?
<P>
        BUT THE STATE OF CALIFORNIA WANTS TO IMPOSE FLUORIDATED WATER IN SANTA CRUZ TO IMPROVE LOCAL DENTAL HEALTH.
<P>
        LOCALS SAY THEY FEEL THE GOVERNMENT IS INTRUDING ON THEIR PRIVATE LIVES.
<P>
        "I DON'T WANT THE GOVERNMENT PUTTING CHEMICALS IN MY WATER.  I THINK IT'S VERY DANGEROUS."
<P>
        "SOME SAY DRINKING FLUORIDATED WATER CAUSES CANCER, BRITTLE BONES AND BRAIN DAMAGE.BUT OTHERS SAY THE WATER CAN ONLY HELP NEEDY CHILDREN GROW UP WITH STRONG TEETH."
<P>
        KITTEN REYNOLDS SAYS SHE GREW UP IN A LOW-INCOME SANTA CRUZ NEIGHBORHOOD.
<P>
        HER TEETH ARE WEAK AND MOST HAVE FALLEN OUT.SHE BLAMES THE PROBLEM ON LACK OF FLUORIDE."
<P>
        "WHAT HAPPENS UNTIL HE GETS THE FLUORIDE, SINCE MOMMY AND DADDY CAN'T AFFORD IT? HIS TEETH ARE STILL DEVELOPING.THIS COULD GIVE HIM A LOT OF PROBLEMS THAT I HAVE FOR A LIFETIME.AND MY MOUTH IS RIPPED UP."
<P>
        THE MANDATE WOULD REQUIRE THE FLUORIDATION TO BEGIN AS SOON AS  FUNDING IS AVAILABLE.BUT THE LAW DIDN'T SET ANY MONEY ASIDE.
<P>
        SOME FOLKS SAY THAT COULD RAISE WATER RATES.
<P>
        COUNCIL MEMBERS SAY THE CITY SHOULD HAVE CONTROL OVER IT'S WATER.
<P>
        "OUR CITY ATTORNEY HAS ADVISED UP THAT AS A CHARTER CITY, WE HAVE THE ABILITY TO CONTROL OUR OWN WATER SUPPLY AND THE QUALITY OF OUR WATER."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Flouride H2O-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Flouride H2O-TAG</H3><BR>
        CAL-AM OFFICIALS SAY THE FLUORIDE MANDATE WILL AFFECT WATER ON THE MONTEREY PENINSULA.
<P>
        AND REPORTIDLY. A PETITION AGAINST THE MANDATE HAS ALREADY BEEN FILED WITH THE STATE.
<P>
        
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126SC rapist>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC rapist</H3><BR>
SANTA CRUZ POLICE SAY THEY HAVE ARRESTED A SUSPECTED RAPIST. WHO MAY BE RESPONSIBLE FOR MORE THAN ONE CRIME.
<P>
35-YEAR OLD DEREK JOHNSON FACES CHARGES OF RAPE AND BURGLARY.
<P>
HE'S ACCUSED OF ATTACKING A 21 YEAR OLD COLLEGE STUDENT IN HER DOWNTOWN APARTMENT.
<P>
POLICE SAY AFTER THE VICTIM GAVE THEM A DETAILED DESCRIPTION OF JOHNSON. HE WAS QUICKLY ARRESTED A FEW BLOCKS FROM THE CRIME SCENE. 
<P>
INVESTIGATORS SAY JOHNSON MAY BE CONNECTED TO OTHER UNSOLVED ASSAULT CASES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Moore court>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Moore court</H3><BR>
THE SALINAS MAN ACCUSED OF KILLING AN 11 YEAR OLD NEIGHBOR DURING A ROBBERY. PLED NOT GUILTY TODAY. 
<P>
RONALD MOORE IS CHARGED WITH THE MURDER OF NICOLE CARNAHAN. 
<P>
POLICE BELIEVE NICOLE WALKED IN ON MOORE AS HE ROBBED HER HOME. AND THEN KILLED HER TO COVER UP THE ROBBERY. 
<P>
PROSECUTORS SAY THAT MAKES HIM ELIGIBLE FOR THE DEATH PENALTY.
<P>
MOORE'S ATTORNEY SAYS HIS CLIENT'S SURPRISED TO BE IN JAIL. 
<P>
HE'S SHOCKED STUNNED. LOU GEHRIG'S DEISEASE.
<P>
THE VICTIM'S MOM. BECKY CARNAHAN. WAS IN COURT TODAY FOR THE FIRST TIME. SHE SAYS SHE'S LIVED NEXT TO MOORE FOR 14 YEARS. AND  ALWAYS THOUGHT HE WAS ODD. BUT NEVER THOUGHT HE WAS CAPABLE OF MURDER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Anderson rejected>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Anderson rejected</H3><BR>
THE SALINAS CITY COUNCIL HAS REJECTED THE LATEST BID BY FORMER POLICE OFFICER RICHARD ANDERSON. TO GET HIS OLD RANK BACK.
<P>
THE RULING WAS EXACTLY THE SAME AS IT WAS LAST MAY. WHEN ANDERSON. WHO'S BEEN DEMOTED TO PATROL OFFICER. APPEALED TO HAVE HIS FORMER RANK OF SERGEANT RESTORED.
<P>
HE WAS DEMOTED AFTER HE REPORTEDLY DISCUSSED SEX AND RELIGION WITH CO-WORKERS. AND TWO TEENAGE EXPLORER SCOUTS.
<P>
THE COUNCIL VOTED FIVE TO ONE AGAINST ANDERSON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125SUHD audit results>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SUHD audit results</H3><BR>
A NEW REPORT ON LOCAL SCHOOLS. SAYS STUDENTS AT SALINAS HIGH SCHOOLS ARE GETTING SHORT CHANGED.
<P>
THE AUDIT CONDUCTED FOR THE SALINAS UNION HIGH SCHOOL DISTRICT FOUND THE CURRICULUM LACKS FOCUS. 
<P>
THERE'S ALSO A DISCREPENCY OVER WHAT IS TAUGHT IN THE CLASSROOM.
<P>
WE FOUND MANY EFFORTS ON-GOING. BUT LACKING FOCUS ON TWO MOST IMPORTANT ELEMENTS OF STUDENT LEARNING. THAT IS QUALITY OF TEACHING AND OF MEASURING STUDENT LEARNING, AND OF USING INFO FROM TESTING TO IMPROVE OUR JOB FOR THE NEXT DAY.
<P>
FRASE'S AUDIT ALSO FOUND DISCREPENCIES IN THE GRADES STUDENTS ARE EARNING IN THE CLASSROOM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Pajaro warning sirens>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pajaro warning sirens</H3><BR>
WHEN THE HEAVY RAINS FALL ON THE CENTRAL COAST. THE TOWN OF PAJARO IS USUALLY ONE OF THE FIRST COMMUNITIES TO BE THREATENED BY FLOODING.
<P>
BUT NOW A BLARING SIREN. MAY ALERT RESIDENTS TO DANGER BEFORE IT'S TOO LATE.
<P>
---SIREN---
<P>
A NEW WARNING SYSTEM WAS TESTED TODAY.
<P>
TOWN ADVISORS BROUGHT IN A MOBIL SIREN.AND SEARCHED FOR THE BEST LOCATION TO INSTALL A PERMANENT ONE.
<P>
THE SIREN ROTATES. AND CAN BE HEARD FROM A MILE AWAY.
<P>
IN THE EVENT OF AN EMERGENCY IT WOULD SOUND OFF FOR THREE MINUTES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Immigrant smuggling>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Immigrant smuggling</H3><BR>
NEARLY FIVE YEARS AGO.  BOATLOADS OF CHINESE IMMIGRANTS SAILED INTO MOSS LANDING AND HALF MOON BAY.
<P>
TONIGHT A FEDERAL JUDGE IS PUSHING AHEAD IN THE TRIAL OF THE MEN ACCUSED OF SMUGGLING  "HUMAN" CARGO.
<P>
THE IMMIGRANTS WERE CAUGHT AND HELD, BACK IN JUNE OF 1993.
<P>
THE NOW NINE WEEK OLD TRIAL OF SIX SUSPECTED SMUGGLERS STALLED WHEN A DEFENSE ATTORNEY WAS JAILED FOR CONTEMPT LAST FRIDAY.
<P>
THE JUDGE DENIED THAT ATTORNEY'S ATTEMPT TO DELAY THE TRIAL BECAUSE THE JAILING WAS "DEHUMANIZING."
<P>
THE TRIAL SHOULD RESUME TOMMORROW IN SAN FRANCISCO.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Food bank study>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Food bank study</H3><BR>
A RECENT NATIONAL STUDY REVEALS SOME STARTLING STATISTICS. ON JUST WHO'S GOING HUNGRY IN THE GOLDEN STATE.
<P>
ACCORDING TO THE CALIFORNIA ASSOCIATION OF FOOD BANKS. THE STUDY BREAKS SOME STEREOTYPES.
<P>
BY ONE ESTIMATE. ALMOST HALF OF FOOD BANK RECIPIENTS IN AMERICA  ARE WHITE.
<P>
62-PERCENT OF RECIPIENTS ARE WOMEN. AND MORE THAN A THIRD ARE CHILDREN.
<P>
HERE ON THE CENTRAL COAST. CLOSE TO *50* PERCENT OF THE HUNGRY. ARE CHILDREN.
<P>
"IT'S TOUGH ESPECIALLY TOUGH IN SANTA CRUZ AND SAN BENITO COUNTIE. WE HAVE A BOUT SIX-THOUSAND FAMILIES WORKING AND CAN'T FEED THEIR FAMILIES."
<P>
THE STUDY SHOWS AT LEAST ONE-THIRD OF THE PEOPLE  WHO ARE HUNGRY HAVE TO  CHOOSE BETWEEN BUYING FOOD *OR* PAYING RENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135coastal commission>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>coastal commission</H3><BR>
THE CALIFORNIA COASTAL COMMISSION BRINGS ITS MONTHLY MEETING TO THE MONTEREY PENINSULA THIS WEEK.
<P>
A BUS TOUR. THAT INCLUDES A LOOK AT THE CONTROVERSIAL HATTON CANYON FREEWAY PROJECT IS ON THE AGENDA.
<P>
OTHER LOCAL ISSUES OF INTEREST THAT COME BEFORE THE COMMISSION THIS WEEK INCLUDE A PLAN TO EXTEND THE RECREATION TRAIL IN PACIFIC GROVE.
<P>
ON THURSDAY. A WORKSHOP IS PLANNED. LOOKING INTO THE MONTEREY BAY SANCTUARY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/packard>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/packard</H3><BR>
GOOD NEWS FOR OUR GOLDEN STATE. CALIFORNIA IS RECEIVING ONE OF THE LARGEST PRIVATE GIFTS FOR LAND CONSERVATION. IN U-S HISTORY.
<P>
A 175 MILLION DOLLAR GIFT FROM THE DAVID AND LUCILLE PACKARD FOUNDATION WILL HELP PROTECT OPEN SPACE. FARMLAND AND WILD-LIFE HABITAT.
<P>
EVENTUALLY. THE FOUNDATION HOPES TO PROTECT 250-THOUSAND ACRES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(weather) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(weather) </H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
HEAVY SNOW. BLIZZARDS. AND FLOODS CONTINUE TO POUND THE MIDWEST. WE'LL HAVE THE LATEST ON THE DAMAGE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(Bridges) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(Bridges) </H3><BR>
AN ACTOR WHO APPEALED TO ALL GENERATIONS THANKS TO MOVIES. LIKE "HIGH NOON". AND "AIRPLANE". HAS DIED.
<P>
THAT STORY RIGHT AFTER THIS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Midwest weather-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Midwest weather-IN</H3><BR>
WINTER HAS COME ROARING BACK WITH A VENGEANCE OVER MUCH OF THE COUNTRY. 
<P>
FROM THE MIDWEST TO THE DEEP SOUTH. BLIZZARDS AND FLOODS ARE MAKING LIFE MISERABLE FOR MILLIONS. 
<P>
FOX'S RICK LEVENTHAL HAS THE STORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A TRAIN SLAMS INTO A SCHOOL BUS LEAVING TWO BROTHERS DEAD. AND FOUR OTHERS SERIOUSLY HURT. 
<P>
THAT STORY FROM BUFFALO, MONTANA. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(bus/train ax)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(bus/train ax)</H3><BR>
THE ACCIDENT HAPPENED AT A RAILROAD CROSSING IN THE TOWN OF BUFFALO. A HUNDRED MILES SOUTHEAST OF GREAT FALLS. 
<P>
A SPOKESPERSON FOR THE RAILROAD SAYS THE ENGINEER BLEW THE WHISTLE. AND TRIED TO STOP THE TRAIN. BUT IT WAS TOO LATE.
<P>
THE NATIONAL TRANSPORTATION SAFETY BOARD IS ON THE SCENE. BUT HAS NOT RELEASED THE CAUSE OF THE ACCIDENT.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(Willey/grand jury)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Willey/grand jury)</H3><BR>
THE WHITEWATER GRAND JURY IS HEARING FROM A FORMER WHITE HOUSE AIDE TODAY. 
<P>
KATHLEEN WILLEY HAS CLAIMED UNDER OATH. THAT PRESIDENT CLINTON MADE AN UNWANTED  ADVANCE TOWARD HER IN 19-93.  WHEN SHE TALKED TO HIM ABOUT GETTING A FULL-TIME JOB. 
<P>
INDEPENDENT COUNSEL KEN STARR IS TRYING TO FIND OUT IF ANYONE URGED HER TO CHANGE HER STORY. IN THE DEPOSITION SHE GAVE IN THE PAULA JONES SEXUAL HARASSMENT LAWSUIT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(SAG strike)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(SAG strike)</H3><BR>
IT MAY FEEL LIKE DE JA VU FOR THOUSANDS OF ACTORS IN HOLLYWOOD. AS THE SCREEN ACTORS GUILD IS THREATENING TO GO ON STRIKE.
<P>
THE LAST TIME THIS HAPPENED. IN 19-80. THE ENTIRE FALL TELEVISION SERIES WAS PUT ON HOLD FOR MONTHS.
<P>
RIGHT NOW THE BIGGEST HURDLE INVOLVES RESIDUAL PAYMENTS TO ACTORS.  
<P>
THE CURRENT CONTRACT EXPIRES ON JUNE 30TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Lloyd Bridges dies-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lloyd Bridges dies-I</H3><BR>
MANY REMEMBER HIM AS THE DEPUTY SHERIFF IN THE 19-52 CLASSIC "HIGH NOON". OTHERS FOR THE FAMOUS LINE FROM THE MOVIE "AIRPLANE". 'I PICKED A BAD WEEK TO STOP SNIFFING GLUE.'
<P>
ACTOR LLOYD BRIDGES HAS DIED AT THE AGE OF 85.
<P>
BILL TUSH TAKES A LOOK BACK. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/insurance>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/insurance</H3><BR>
SOME LAWMAKERS ON CAPITOL HILL ARE LOOKING TO BRING DOWN THE HIGH COST OF CAR INSURANCE PREMIUMS.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
AT A NEWS CONFERENCE IN WASHINGTON TODAY.
<P>
"THE AUTO CHOICE REFORM ACT" WAS INTRODUCED.
<P>
THE BILL OFFERS DRIVERS CHOICES. WHEN THEY BUY CAR INSURANCE. 
<P>
THEY CAN BUY A TRADITIONAL LIABILITY POLICY. OR THEY CAN BUY A LESS EXPENSIVE POLICY.
<P>
ONE THAT WOULD ALLOW THEM TO RECOVER LOSSES FROM THEIR OWN INSURANCE COMPANY.WITHOUT GOING TO COURT.AND WITHOUT REGARD TO FAULT. 
<P>
"AUTO CHOICE" COULD SAVE THE AVERAGE AUTO INSURANCE POLICY HOLDER.NEARLY 2-HUNDRED DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Prep Basketball>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Basketball</H3><BR>
WITH THE C.C.S. PLAYOFFS BEHIND US, WE TURN OUR ATTENTION TO THE NORTHERN CALIFORNIA PLAYOFFS.
<P>
OUR 2-LOCAL C.C.S CHAMPS ARE REWARDED WITH OPENING ROUND HOME GAMES.
<P>
WE START WITH THE PACIFIC GROVE BOYS HOSTING CORNING HIGH SCHOOL.
<P>
THE BREAKERS RIDING A 20-GAME WINNING STREAK AND THEY WOULD POUR ON THE OFFENSE.
<P>
-----------
<P>
JUST BEFORE THE END OF THE 3RD QUARTER.  LAUNCHES FROM THE CORNER AND BURRIES THE TRIPLE. PACIFIC GROVE BY 31. YES 31.
<P>
----------
<P>
THE BREAKERS KEEP ON THE ATTACK. ALSO WORKING IT IN THE PAINT.  WITH THE HOOP AND THE FOUL.
<P>
---------
<P>
WOULD EMPTY THE BENCH AND THE RESERVES RESPOND AS WELL.
<P>
---------
<P>
LOOK AT THE MOVE BY JUNIOR. GREAT SHOT.
<P>
THE BREAKERS BLOW OUT CORNING. FINAL. 68-36. IT'S PG'S 21ST CONSECUTIVE VICTORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41R.L.S. Girls Hoops>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>R.L.S. Girls Hoops</H3><BR>
NEXT. THE RLS GIRLS DOING SOME DAMAGE OF THEIR OWN AGAINST CLEAR LAKE.
<P>
--------
<P>
1ST HALF.  CONTINUES HER HOT SHOOTING BY CANNING THE BASELINE JUMPER. THE PIRATES ROLLING IN THIS ONE.
<P>
--------
<P>
THEN. ON THE DEFENSIVE END.  GETS THE BLOCK AND SHE COMES UP WITH THE BALL.  GIRLS PICKING UP WHERE THEY LEFT OFF IN C-C-S.
<P>
---------
<P>
PROVING MORE OFFENSE. THIS TIME FROM THE OTHER BASELINE.
<P>
--------
<P>
THE PIRATES TAKE A 17 POINT LEAD INTO THE BREAK AND THEY GO ON TO WIN BY 20.
<P>
FINAL. RLS 63,  CLEAR LAKE 43. THE PIRATES IMPROVE TO 25-6. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
MEANWHILE COLLEGE BASKETBALL'S MARCH MADNESS GETS UNDERWAY THURSDAY.
<P>
STANFORD WILL JOIN THE PARTY ON FRIDAY.
<P>
MIKE MONTGOMERY'S CREW FINISHED THE SEASON 26 AND 4, RANKED 10TH IN THE NATION, AND ARE THE 3RD SEED IN THE MIDWEST REGIONAL.
<P>
THEY'LL PLAY FRIDAY, AT ABOUT NOON PACIFIC TIME, VS. THE COLLEGE OF CHARLESTON, A TEAM THAT BEAT THEM LAST YEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43All-Americans>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>All-Americans</H3><BR>
IN OTHER COLLEGE BASKETBALL NEWS, THE ASSOCIATED PRESS ALL-AMERICAN TEAM IS NAMED TODAY.
<P>
ITS FULL OF TEAMMATES.
<P>
THE GUARDS, BOTH FROM THE DEFENDING NATIONAL CHAMPION ARIZONA WILDCATS ARE MILES SIMON AND MIKE BIBBY.
<P>
THE KANSAS JAYHAWKS SUPPLY 2-PLAYERS AS WELL, RAEF LAFRENTZ AND PAUL PIERCE.
<P>
AND NORTH CAROLINA'S ANTWAIN JAMISSON ROUNDS OUT THE FIRST FIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
WHILE BEING INONDATED WITH LATRELL SREWELL INTERVIEW'S FROM EVERY ANGLE, THE WARRIORS STILL MANAGED TO WIN IN SACRAMENTO LAST NIGHT.
<P>
GOLDEN STATE WILL PLAY IN MINNESOTA TOMORROW NIGHT.
<P>
AS FOR SPREWELL, HE'S TRYING TO REBUILD HIS IMAGE, DOING INTERVIEW'S AS THOUGH HE'S RUNNING FOR OFFICE.
<P>
OVER AND OVER AGAIN, SPREWELL HAS MENTIONED HE'D LIKE TO PLAY WITH THE WASHINGTON WIZARDS, AND FORMER TEAMMATE CHRIS WEBBER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
AND FINALLY WE'VE GOT A LITTLE PREP GOLF TO SHOW YOU TONITE.
<P>
KCBA'S NEWEST FAVORITE LOCAL COURSE, SAN JUAN OAKS, HOSTED TODAY'S MISSION TRAIL LEAGUE MATCH.
<P>
AT THE 10TH HOLE, R.L.S.'S JASON MCARTHUR COMES UP WITH THE LONG BIRDIE PUTT, WATCH IT CLANK IN.
<P>
R.L.S. WINS TODAY'S TEAM COMPETITION BY 18-STROKES OVER PALMA. CARMEL FINISHES 3RD.
<P>
THE LOW MEDALIST'S OF THE DAY, ARE DAVID ADDISON AND DAVID MORGAN, BOTH OF R.L.S., AND BOTH SHOOT 36.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Significant others>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Significant others</H3><BR>
"PARTY OF FIVE" FANS LOOKING FOR THE SHOW TOMORROW NIGHT WILL FIND A NEW ADDITION TO THE FOX FAMILY INSTEAD. 
<P>
FOR THE NEXT SIX WEEKS. A NEW DRAMA CALLED "SIGNIFICANT OTHERS" WILL TAKE OVER THAT  
<P>
WEDNESDAY NIGHT SLOT.  
<P>
THE SHOW FOCUSES ON FIVE CHARACTERS IN THEIR MID-TWENTIES LIVING IN L-A.TRYING TO FIGURE OUT THEIR CAREERS AND THEIR LOVE-LIVES. 
<P>
THE SHOW IS CREATED AND WRITTEN BY CHRIS KEYSER AND AMY LIPPMAN.  THE SUCCESSFUL CREATORS OF FOX'S HIT "PARTY OF FIVE." 
<P>
BUT TWO OF THE NEW SHOW'S STARS SAY THEIR SHOW IS DIFFERENT.
<P>
GARNER SAYS: "AMY AND CHRIS ARE KNOWN FOR THEIR DIALOGUE--IT'S 
<P>
DEFINITELY TOTALLY DIFFERENT CHARACTERS.OUR CHARACTERS ARE SELFISH, 
<P>
IN PARTY OF FIVE THEY HAVE TO TAKE CARE OF EACH OTHER-- WE LOOK OUT 
<P>
FOR OURSELVES."  
<P>
THE CAST IS HOPING THAT VIEWERS WHO TAKE THE TIME TO WATCH THE SHOW. WILL BECOME ATTACHED TO THE CHARACTERS AS THEY HAVE WITH "PARTY  OF FIVE."        
<P>
"SIGNIFICANT OTHERS" PREMIERES TOMORROW WEDNESDAY AT 9 O'CLOCK.  RIGHT HERE ON FOX 35.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Taco bell protest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Taco bell protest</H3><BR>
FINALLY TONIGHT. TACO BELL IS IN THE DOG HOUSE WITH SOME HISPANIC GROUPS. OVER THEIR LATEST COMMERCIAL.
<P>
---CLIP FROM COMMERCIAL---- 
<P>
THE GROUP SAYS THE SPANISH SPEAKING CHIHUAHUA. NAMED "DINKY". IS OFFENSIVE. AND THEY'RE ASKING FOR A BOYCOTT OF TACO BELL.
<P>
TACO BELL SAYS DINKY. QUICKLY ROSE TO CULT FIGURE STATUS. AND NEVER MEANT TO BE OFFENSIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
