<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Monday, 3/2/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Monday, 3/2/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140(jerry springer)>(jerry springer)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Kidnap/Abduction-I>Kidnap/Abduction-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(missing millions)>(missing millions)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Kidnap/Abduction-T>Kidnap/Abduction-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(grand jury/jordan)>(grand jury/jordan)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Las Lomas folo>Las Lomas folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22(baby abandoned)>(baby abandoned)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Watsonville burglar>Watsonville burglar</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Diana bodyguard>Diana bodyguard</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Yuba City Robbers>Yuba City Robbers</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Diana's will>Diana's will</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Seaside shooting>Seaside shooting</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/sunbeam>Fox Biz/sunbeam</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Madrigal arraignment>Madrigal arraignment</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129SC inmate death>SC inmate death</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135Bilingual Education-I>Bilingual Education-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132school breakfast>school breakfast</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Golf(Saving Strokes)>Golf(Saving Strokes)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(jerry spring) >Bump 1(jerry spring) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Bump #5a (dream)>Bump #5a (dream)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(di bodyguar) >bump 2(di bodyguar) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50dream home move>dream home move</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Magician Special>Magician Special</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(boy scouts/gays)>(boy scouts/gays)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141extreme bungee>extreme bungee</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
SOME TENSE MOMENTS FOR A SAN JOSE WOMAN THIS AFTERNOON.
<P>
SHE'S KIDNAPPED AT KNIFE POINT AND DRIVEN TOWARDS MEXICO.
<P>
BUT THEY DIDN'T GET FAR. THE ORDEAL ENDED IN MONTEREY COUNTY.
<P>
CHERI GYURO JOINS US LIVE FROM CASTROVILLE WITH ALL THE DETAILS. CHERI?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Kidnap/Abduction-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kidnap/Abduction-I</H3><BR>
ALAN, THIS IS ONE OF THE MANY PLACES THE VICTIM AND HER ABDUCTOR STOPPED.
<P>
AND INSIDE THIS BURGER KING.SHE GOT A MESSAGE TO SOMEONE THAT SHE NEEDED HELP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Kidnap/Abduction-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kidnap/Abduction-T</H3><BR>
GARIBAY WAS ARRESTED FOR DOMESTIC VIOLENCE.
<P>
BUT MONTEREY COUNTY SHERIFF'S DEPUTIES SAY THE SAN JOSE POLICE DEPARTMENT WILL TAKE OVER THE CASE.
<P>
REPORTING LIVE FROM CASTROVILLE, I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Las Lomas folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Las Lomas folo</H3><BR>
THIS DRY SPELL WE'VE BEEN ENJOYING HAS DONE LITTLE TO EASE THE FEARS OF LAS LOMAS RESIDENTS.
<P>
IN FACT.  MORE COULD BE FORCED FROM THEIR HOMES.
<P>
FOR MORE THAN A WEEK A SLOWLY SLIDING HILLSIDE HAS BEEN THREATENING HOMES ON FLORA DRIVE.
<P>
NOW. INSPECTORS ARE SAYING THE WHOLE HILLSIDE COULD GO AT ANY TIME.
<P>
THAT HAS RESIDENTS DOWN BELOW ON LOS LOMAS DRIVE WORRIED TONIGHT.
<P>
THEY SAY STEADY EARTH MOVEMENT IS NOW CAUSING *THEIR* DRIVEWAYS. AND FRONT LAWNS TO BUCKLE. 
<P>
AND. CREWS WERE ON SCENE ALL DAY. WORKING TO FIX A  SEWER MAIN THAT BROKE LAST NIGHT.
<P>
"WE ARE PUTTING TEMPORARY LINES OVER GROUND MAINTAIN FLOW. TO ANOTHER MANHOLE DOWN STREAM."
<P>
COCHRAN SAYS *THIS* MAIN. SERVICES DOZENS OF FAMILIES IN THE AREA.
<P>
HE SAYS THEY'LL BE O.K. FOR NOW. BUT MORE SLIDING COULD CAUSE MORE BREAKS IN THE LINE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Watsonville burglar>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Watsonville burglar</H3><BR>
A  WATSONVILLE HOUSE OF WORSHIP BECAUSE THE TARGET OF A BURGLAR. MAN FACES BURGLARY CHARGES TONIGHT. AFTER ALLEGEDLY STEALING A T-V AND VCR FROM A CHURCH.
<P>
JOSE DE-JESUS MENDOZA FACES BURGLARY CHARGES AFTER WATSONVILLE POLICE RESPOND TO AN ALARM AT THE LUTHERAN CHURCH ON ALTA VISTA DRIVE.
<P>
POLICE SAY MENDOZA WAS FOUND FLEEING THE SCENE. A T-V AND VCR BELONGING TO THE CHURCH WERE FOUND IN THE BUSHES NEARBY.
<P>
MENDOZA IS IN CUSTODY AT THE SANTA CRUZ COUNTY JAIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Yuba City Robbers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Yuba City Robbers</H3><BR>
THREE SALINAS MEN. ACCUSED OF ROBBERY. ARE ARRESTED IN NORTHERN CALIFORNIA AFTER WHAT POLICE DESCRIBE AS A VERY CONSPICUOUS GETAWAY.
<P>
TWO OF THE MEN ALLEGEDLY ROBBED A CIRCLE K STORE IN YUBA CITY. THEN FLED IN A BRIGHT YELLOW RENTAL TRUCK.
<P>
THEY WERE SPOTTED BY POLICE.
<P>
30-YEAR-OLD EDWIN PAJIMOLA. 31-YEAR-OLD ROBERT LONGORIA. AND 33-YEAR-OLD OY FLORES WERE TAKEN INTO CUSTODY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Seaside shooting>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Seaside shooting</H3><BR>
AN EARLY MORNING SHOOTING IN SEASIDE SENDS A LOCAL MAN TO THE HOSPITAL.
<P>
        AT TWO THIS MORNING. OFFICERS WERE CALLED TO THIS HOUSE ON TRINITY AVENUE, WHERE THE FOUND 32 YEAR OLD STEVEN ARELLANO SUFFERING FROM AT LEAST ONE GUNSHOT WOUND.
<P>
        ARELLANO WAS TAKEN TO COMMUNITY HOSPITAL. BUT TONIGHT, A SPOKESMAN AT THE HOSPITAL HAD NO INFORMATION ON HIS CONDITION.
<P>
        SO FAR. AUTHORITIES HAVE NO SUSPECTS IN THE SHOOTING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Madrigal arraignment>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Madrigal arraignment</H3><BR>
THE 18-YEAR-OLD MAN ACCUSED IN THE SHOOTING DEATH OF A WATSONVILLE COLLEGE STUDENT. IS BACK IN COURT TODAY.
<P>
A TRIAL DATE OF JUNE FIRST HAS BEEN SET FOR JESUS MADRIGAL. WHO FACES CHARGES OF KIDNAPPING. CARJACKING AND MURDER.
<P>
THE BODY OF ULYSSES HUANTES  WAS DISCOVERED LAST NOVEMBER ON CHITTENDEN ROAD.
<P>
PROSECUTORS SAY MADRIGAL AND FRANCISCO MARQUEZ KILLED THE VICTIM WHILE TRYING TO STILL HIS CAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129SC inmate death>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC inmate death</H3><BR>
THE SANTA CRUZ POLICE DEPARTMENT AND THE SANTA CRUZ COUNTY CORONER'S OFFICE ARE INVESTIGATING THE BIZARRE DEATH OF A MAN WHO SPENT SEVERAL HOURS AT THE JAIL LAST WEEK.
<P>
53 YEAR- OLD JAMES BAYCH WAS ARRESTED AT DOMINICAN HOSPITAL LAST WEDNESDAY NIGHT FOR BEING UNDER THE INFLUENCE OF ALCOHOL.
<P>
HE WAS  RELEASED. ONLY TO BE FOUND A SHORT TIME LATER   LYING UNDER A PARKED CAR.
<P>
BAYCH WAS TAKEN TO THE EMERGENCY ROOM WHERE HE WAS TREATED AND RELEASED TO THE COUNTY JAIL.
<P>
THE NEXT DAY.HE WAS DEAD.
<P>
THE INITIAL INVESTIGATION SAYS HE DIED OF A SUBDURAL HEMATOMA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135Bilingual Education-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bilingual Education-I</H3><BR>
THE POLITICS OF LANGUAGE RAGE ON. HERE IN THE GOLDEN STATE.
<P>
A STUDY ON BILINGUAL EDUCATION HAS BEEN RELEASED AND BOTH ADVOCATES AND OPPONENTS SAY THAT THE FINDINGS SUPPORT *THEIR* SIDE. 
<P>
FOX'S REBECCA GOMEZ TAKES A CLOSER LOOK AT THIS POLITICALLY DIVISIVE ISSUE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132school breakfast>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>school breakfast</H3><BR>
OTHER EDUCATIONAL STUDIES HAVE PROVEN KIDS WHO EAT A GOOD BREAKFAST DO BETTER IN SCHOOL. BUT NOT ALL PARENTS HAVE THE MONEY TO BUY THE FOOD THIER CHILDREN NEED.
<P>
SO NOW. MOST SCHOOL CAFETERIAS NOT ONLY SERVE UP A HOT LUNCH. THEY PROVIDE BREAKFAST AS WELL.
<P>
THE FEDERAL SCHOOL BREAKFAST PROGRAM BEGAN BACK IN THE LATE SIXTIES.
<P>
THIS WEEK THE PROGRAM IS CELEBRATING ITS 32ND ANNIVERSARY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(jerry spring) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(jerry spring) </H3><BR>
COMING UP NEXT ON K-B-C-A FOX NEWS FIRST AT TEN.
<P>
TEACHERS ARE WARNING PARENTS ABOUT THE LATEST DANGEROUS TREND TO HIT SCHOOLS. IT'S NOT A NEW WEAPON OR DRUG. IT'S JERRY SPRINGER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(di bodyguar) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(di bodyguar) </H3><BR>
AND NEW DETAILS ABOUT THE LAST MOMENTS BEFORE THE DEATH OF PRINCESS DIANA. AS HER BODYGUARD BEGINS TO REGAIN HIS MEMORY OF THE FATAL CRASH.
<P>
WE'LL TELL YOU JUST *WHAT* HE REMEMBERS. RIGHT AFTER THIS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A NEW JERSEY COURT HAS RULED THAT THE BOY SCOUTS OF AMERICA. CAN NOT DENY ADMISSION TO GAYS.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(boy scouts/gays)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(boy scouts/gays)</H3><BR>
A NEW JERSEY APPEALS COURT RULED THAT THE BOY SCOUTS OF AMERICA'S BAN ON ADMITTING GAYS. VIOLATED THE STATE'S LAWS AGAINST DISCRIMINATION. 
<P>
JAMES DALE. A SCOUTMASTER. WAS EXPELLED FROM HIS BOY SCOUT TROOP IN 19-90. AFTER SCOUT AUTHORITIES LEARNED FROM A NEWSPAPER ARTICLE THAT HE WAS GAY. 
<P>
THE BOY SCOUTS STILL HAVE AN AUTOMATIC APPEAL BEFORE NEW JERSEY'S TOP COURT. BECAUSE THE RULING WAS NOT UNANIMOUS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140(jerry springer)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(jerry springer)</H3><BR>
THE JERRY SPRINGER SHOW IS GETTING SOME LOW RATINGS FROM EDUCATORS IN NORFOLK, VIRGINIA. 
<P>
TEACHERS THERE SAY ELEMENTARY SCHOOL STUDENTS ARE IMITATING THE BRAWLS THEY SEE ON THE NATIONALLY-SYNDICATED SHOW. AND THEY'RE ACTING THEM OUT ON THE PLAYGROUND. 
<P>
ONE SCHOOL SENT HOME NOTES ASKING PARENTS TO KEEP THEIR KIDS FROM WATCHING THE SHOW. 
<P>
PRODUCERS OF THE HIGHLY RATED TALK SHOW SAY THEY DON'T RECOMMEND YOUNG KIDS WATCH THE SHOW. BUT DEFEND ITS CONTENT SAYING THERE'S MORE VIOLENCE 
<P>
DEPICTED ON THE EVENING NEWS.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(missing millions)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(missing millions)</H3><BR>
A NORTH CAROLINA MAN.. WANTED FOR THE 17-MILLION DOLLAR ROBBERY OF AN ARMORED CAR COMPANY LAST OCTOBER. HAS BEEN CAPTURED IN MEXICO.
<P>
AT A PRESS CONFERENCE IN NORTH CAROLINA. THE F-B-I ANNOUNCED THAT 28-YEAR-OLD DAVID SCOTT GHANTT HAD BEEN CAPTURED. AFTER A NEARLY 5-MONTH 
<P>
MANHUNT. 
<P>
SIX OTHER PEOPLE WERE ALSO ARRESTED IN NORTH CAROLINA TODAY IN CONNECTION WITH THE CASE. 
<P>
THE ACCOMPLICES HAD BEEN ON SPENDING SPREES SINCE THE HEIST. WITH ONE COUPLE MOVING FROM A TRAILER. TO A HALF-MILLION DOLLAR HOUSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(grand jury/jordan)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(grand jury/jordan)</H3><BR>
A GRAND JURY INVESTIGATING PRESIDENT CLINTON'S ALLEGED SEXUAL RELATIONSHIP WITH MONICA LEWINSKY.
<P>
WILL HEAR FROM PRESIDENTIAL CONFIDANT VERNON JORDAN TOMORROW. 
<P>
JORDAN HAS BEEN AT THE CENTER OF THE CLINTON/LEWINSKY SCANDAL SINCE THE BEGINNING. ALLEGEDLY ACTING AS A GO-BETWEEN WHEN THE FORMER WHITE HOUSE INTERN NEEDED A JOB. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22(baby abandoned)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(baby abandoned)</H3><BR>
POLICE IN JEFFERSON, INDIANA ARE SEARCHING FOR THE MOTHER OF A NEWBORN BABY. FOUND ON THE STEPS OF THE LOCAL CHURCH.
<P>
POLICE SAY THE BABY GIRL WAS LEFT. JUST MINUTES BEFORE THE WORSHIP SERVICE STARTED. 
<P>
SHE WAS WRAPPED IN BLANKETS. AND SURROUNDED WITH CLOTHES AND BABY SUPPLIES. 
<P>
ALSO IN THE BASKET. WAS A NOTE FROM THE BABY'S MOTHER. SAYING "I WILL NEVER GET OVER WHAT I HAVE DONE" 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Diana bodyguard>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Diana bodyguard</H3><BR>
THE BODYGUARD. WHO WAS THE SOLE SURVIVOR IN 
<P>
THE CRASH THAT KILLED PRINCESS DIANA AND DODI FAYED. IS REPORTEDLY REGAINING HIS MEMORY OF THE ACCIDENT. 
<P>
TREVOR REES-JONES SAYS HE NOW REMEMBERS  DIANA CALLING OUT FOR DODI. MOMENTS AFTER THE CRASH. 
<P>
DODI WAS SITTING NEXT TO HER IN THE BACK SEAT OF THE CAR. 
<P>
THE NEW INFORMATION COULD ESTABLISH THAT DIANA WAS CONSCIOUS AFTER THE ACCIDENT. A FACT THAT HAS BEEN PREVIOUSLY DENIED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Diana's will>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Diana's will</H3><BR>
THE ANNOUNCEMENT CAME ON THE SAME DAY PRINCESS DIANA'S LAST WILL AND TESTAMENT WAS MADE PUBLIC. 
<P>
AS EXPECTED. DIANA LEFT THE BULK OF HER 35-MILLION 
<P>
DOLLAR FORTUNE IN TRUST FOR HER TWO SONS. PRINCES WILLIAM AND HARRY. 
<P>
THEY WILL BE ENTITLED TO THE FORTUNE WHEN THEY TURN 25. 
<P>
THE ESTATE PAID A HEFTY TAX BILL. TO TUNE OF 14-MILLION DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/sunbeam>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/sunbeam</H3><BR>
A MAJOR APPLIANCE COMPANY HAS GONE ON A SPENDING SPREE. AND THAT COULD MEAN MAJOR LAYOFFS FOR SEVERAL BUSINESSES.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
CHANCES ARE BETTER THAN EVER THAT SOMETHING IN YOUR HOUSE IS MADE BY "SUNBEAM." 
<P>
THE HOME APPLIANCE GIANT WENT ON A SHOPPING SPREE. SPENDING 1-POINT-8 BILLION DOLLARS FOR THREE COMPANIES. 
<P>
SUNBEAM IS BUYING MR. COFFEE AND FIRST ALERT. THE SMOKE DETECTOR MANUFACTURER. 
<P>
ALSO THE COLEMAN COMPANY. WHICH IS KNOWN FOR ITS OUTDOOR GRILLS AND CAMPING EQUIPMENT. 
<P>
BEFORE THE ACQUISITIONS. CHAIRMAN AL DUNLAP CUT THE JOBS OF HALF OF SUNBEAM'S 12-THOUSAND WORKERS.
<P>
DUNLAP SAYS HE PLANS MORE CUTS. INCLUDING REDUNDANT STAFF AND OVERHEAD.
<P>
Q:36 "MUSIC'
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE WARRIORS VISIT THE CHARLOTTE HORNETS TONITE, BUT BEFORE WE GET TO THE HILITES, WE'VE GOT A LATRELL SPREWELL UPDATE, AND NO, IT HAS NOTHING TO DO WITH THE ARBITRATION HEARING.
<P>
SPREWELL WAS INVOLVED IN AN AUTO ACCIDENT YESTERDAY.
<P>
WHILE DRIVNG SOUTHBOUND ON THE 680 NEAR PLEASANT HILL, SPREWELL TRIED TO GET BACK ONTO THE FREEWAY FROM AN EXIT ONLY LANE. HE SMASHED INTO SOME SAND BARRELLS, AND KNOCKED INTO ANOTHER CAR WHICH OVERTURNED ONTO ITS ROOF.
<P>
LUCKILY THERE WERE NO SERIOUS INJURIES. THE C-H-P SAYS SPREWELL WAS TRAVELING AT HIGH SPEEDS, AND THAT THE ACCIDENT IS UNDER INVESTIGATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
LIKE THE WARRIORS, TONITE THE SHARKS FACE A TEAM FROM CHARLOTTE. ONLY UNLIKE THE WARRIORS THE SHARKS ARE HOME TO FACE THE CAROLINA HURRICANES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
TO SPRING TRAINING, AND I KNOW THESE GAMES DON'T OFFICIALLY COUNT FOR MUCH, BUT THE RE-BUILT OAKLAND A'S COME INTO THE DAY WITH A PERFECT 4 AND 0 RECORD.
<P>
BUT THIS AFTERNOON THE A'S B-TEAM FACES THE SEATTLE MARINERS A-TEAM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Golf(Saving Strokes)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf(Saving Strokes)</H3><BR>
AND FINALLY, ARE YOU HAVING TROUBLE WITH THOSE LONG PUTTS?
<P>
WELL BRUCE LEWIS IS HERE TO HELP, TIME NOW FOR SAVING STROKES AT SAN JUAN OAKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Bump #5a (dream)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump #5a (dream)</H3><BR>
COMING UP NEXT. THE SALINAS COUPLE THAT WON THE STEINBECK DREAM HOUSE.
<P>
IS WASTING NO TIME. WE'LL TAKE YOU TO MOVING DAY.RIGHT AFTER THIS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50dream home move>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>dream home move</H3><BR>
THE WINNERS OF THE STEINBECK DREAM HOUSE ARE GEARING UP TO MOVE INTO THEIR NEW HOME. 
<P>
THE WINNER IS EDUVIJES ROSALEZ.
<P>
HER NAME WAS ONE OF THOUSANDS ENTERED INTO THE DRAWING. 
<P>
NOW SHE IS FILLING OUT THE NECESSARY PAPERWORK TO TAKE POSSESION OF THE HOUSE. 
<P>
ROSALEZ IS SHOPPING FOR A LOAN TO PAY THE TAX ON THE HOME VALUED AT 235-THOUSAND.
<P>
SHE IS EXPECTED TO MOVE IN BY THE END OF THE MONTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Magician Special>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Magician Special</H3><BR>
THE MASKED MAGICIAN STRIKES AGAIN. FOX IS READY TO AIR PART TWO OF MAGIC SECRETS REVEALED. HOSTED BY THE MASKED WIZAR.
<P>
THE 20-YEAR VETERAN MAGICIAN PROMISES TO BREAK THE SILENT CODE ON TOMORROW'S SHOW. AND TELL THE WORLD HOW THE TRICKS ARE DONE. 
<P>
THE MASKED MAGICIAN EXPLAINS WHY HE IS WILLING TO GIVE UP THE TRICKS OF THE TRADE. 
<P>
THE MASKED MAGICIAN SAYS "MY REASONS FOR DOING THIS IS FOR THE 
<P>
ADVANCEMENT OF THE ART. THERE ARE A LOT OF MAGICIANS OUT THERE WHO ARE 
<P>
NOT MAGICIANS YET. THEY HAVE AN INTEREST IN MAGIC.THEY DON'T KNOW 
<P>
HOW TO GET IN OR EVEN KNOW THEY CAN BECOME A PART OF THE MAGIC WORLD, 
<P>
AND THIS SPECIAL IS ONE MESSAGE OUT THERE. ANYONE WANTING TO BECOME 
<P>
PART OF THE MAGIC WORLD CAN. 
<P>
THE DIFFERENCE THIS TIME AROUND.  HE SAYS. ARE THE 
<P>
TRICKS.THEY ARE BIGGER AND RISKIER THAN EVER BEFORE.
<P>
TUNE IN TOMORROW TO "MAGIC SECRETS REVEALED". RIGHT ON HERE K-C-B-A FOX 35. AND SEE HOW THE FOMER MAGICIAN REVEALS ONE OF HOUDINI'S FAVORITE TRICKS. ESCAPING FROM A WATER TANK. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141extreme bungee>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>extreme bungee</H3><BR>
LOOKING FOR THE LATEST TREND IN EXTREME SPORTS. HOW ABOUT A 6-HUNDRED FOOT BUNGEE JUMP.
<P>
THE ONLY SMALL HURDLE. YOU HAVE TO GO TO SOUTH AFRICA TO DO IT. 
<P>
THE BUNGEE JUMPING OUTFIT KIWI EXTREME. WHICH HANDLED JUMPING FROM VICTORIA FALLS IN ZIMBABWE. DECIDED TO TAKE ON THE BLAUKRANS  BRIDGE. THE THIRD HIGHEST IN THE WORLD.
<P>
AT 691 FEET. IT'S THE DEEPEST POSSIBLE BUNGEE JUMP. AVAILABLE TO THRILL SEEKERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
