<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Monday, 3/30/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Monday, 3/30/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x033011.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Black Widow Death>Black Widow Death</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Willover - i>Willover - i</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117Taxi Driver Death>Taxi Driver Death</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Willover - g>Willover - g</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118Malcolm X>Malcolm X</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Willover - t>Willover - t</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Aids Disability>Aids Disability</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Salinas School Dist.>Salinas School Dist.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Aids Breakthrough>Aids Breakthrough</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#1273 Strikes - Rogers>3 Strikes - Rogers</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Smaller Milky Way?>Smaller Milky Way?</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Lisa Davis Trial>Lisa Davis Trial</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Business News>Fox Business News</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144PG&E Deregulation!!>PG&E Deregulation!!</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Final Four>Final Four</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Natural Gas Hear>Natural Gas Hear</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Del Monte Dunes>Del Monte Dunes</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4349ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141152 Ax Folo>152 Ax Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Golf: Saving Strokes>Golf: Saving Strokes</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Cancer Motorcycle>Cancer Motorcycle</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Mock Election>Mock Election</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Increased Cigar Use>Increased Cigar Use</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Xena Marries>Xena Marries</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Macauley Marries>Macauley Marries</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
17-YEAR-OLD NORMAN WILLOVER TELLS KCBA HE HAD NOTHING TO DO WITH A TWO-HOUR CRIME SPREE THAT TOOK THE LIVES OF TWO PENINSULA WOMEN.
<P>
IN FACT. HE SAYS HE WAS SET UP.
<P>
CHERI GYURO IS FOLLOWING THE STORY.SHE JOINS US LIVE FROM THE NEWS DESK WITH ALL THE INFORMATION. WHAT DID WILLOVER SAY?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Willover - i>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Willover - i</H3><BR>
ALAN, WILLOVER CALLED FROM JUVENILE HALL TODAY.ASKING TO SPEAK TO A KCBA REPORTER.
<P>
HE SAID HE WANTED TO GIVE HIS SIDE OF THE STORY.
<P>
WILLOVER IS ACCUSED OF SHOOTING AND KILLING TWO WOMEN AND INJURING A THIRD IN FEBRUARY.    
<P>
BUT WILLOVER SAYS HE WAS NOWHERE NEAR EITHER CRIME SCENES THE NIGHT OF THE MURDERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Willover - g>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Willover - g</H3><BR>
NORMAN WILLOVER CALLED KCBA FROM JUVENILE HALL SAYING HE WANTS THE PUBLIC TO KNOW HIS SIDE OF THE STORY.
<P>
WILLOVER AND 19-YEAR-OLD JOE MANIBUSAN ARE ACCUSED OF SHOOTING 35-YEAR-OLD PRIYA MATHEWS AND 27-YEAR-OLD JENNIFER ANINGER IN MONTEREY.THEN SHOOTING 47-YEAR-OLD FRANCES OLIVIO IN SEASIDE.ALL IN THE SAME NIGHT.
<P>
MATHEWS AND OLIVIO BOTH DIED.
<P>
WILLOVER SAYS HE WAS NOT INVOLVED IN THE SHOOTINGS.AND THAT HE WAS NOT IN THE VEHICLE WHERE THE SHOTS WERE FIRED.
<P>
BUT HE DOES SAY MONTEREY POLICE ARRESTED HIM FOR RUNNING AWAY FROM A GROUP HOME IN UTAH.AND FORCED HIM TO CONFESS TO THE SHOOTINGS.
<P>
WILLOVER SAYS THE POLICE CAME TO HIS HOUSE BEFORE THE SHOOTING ONCE.INJECTED TRUTH SYRUM IN HIM.AND TRIED TO FORCE HIM TO CONFESS TO A ROBBERY AT THE GALAXY THEATRE.
<P>
HE SAYS HE WAS NOT ARRESTED FOR THAT CRIME.BUT HE SAYS POLICE PLOTTED AGAINST HIM TO GET INCRIMINATING EVIDENCE AGAINST HIM FOR THE MURDERS.
<P>
"WE SPOKE WITH WILLOVER'S ATTORNEY.JOHN HOWELL.HE DIDN'T WANT TO APPEAR ON CAMERA.BUT HE DID SAY THAT WILLOVER ONCE EXPRESSED A DESIRE TO SPEAK WITH THE MEDIA.HOWELL SAYS HE DISCOURAGED THAT."
<P>
HOWELL TOLD KCBA QUOTE: "HE HAS A HISTORY OF MENTAL ABERRATION.  HE'S DISTURBED, HE SHOULDN'T BE TALKING TO THE MEDIA."  HE ALSO SAID QUOTE: "HE'S A SERIOUSLY DISTURBED PERSON.DOCTORS WHO EVALUATED HIM SAY HE IS IN NEED OF PSYCHIATRIC HELP IN A LOCKED FACILITY."
<P>
WILLOVER ADMITS HE'S HAD PROBLEMS WITH THE LAW IN THE PAST.
<P>
WILLOVER ADMITS.HE'S HAD TROUBLE WITH THE LAW IN THE PAST.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Willover - t>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Willover - t</H3><BR>
WILLOVER SAYS HE'S AFFILIATED WITH A GROUP CALLED "THE ORIENTAL BOYS".BUT IT'S NOT A GANG.
<P>
JOHN HOWELL TELLS KCBA THAT A PLEA OF "NOT GUILTY" BY REASON OF INSANITY IS VERY MUCH IN THE PICTURE FOR WILLOVER.
<P>
WILLOVER WILL BE TRIED AS AN ADULT.
<P>
BOTH HE AND MANI-BUSAN WILL BE IN COURT ON THURSDAY.REPORTING LIVE FROM THE NEWS DESK.I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Salinas School Dist.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas School Dist.</H3><BR>
AFTER MONTHS OF NEGOTIATIONS, SICK-OUTS AND PROTESTS. THE SALINAS UNION HIGH SCHOOL DISTRICT HAS FINALLY REACHED A CONTRACT AGREEMENT WITH ITS TEACHERS.
<P>
THE DEAL WAS MADE PUBLIC AT A PRESS CONFERENCE AT DISTRICT HEADQUARTERS THIS AFTERNOON.
<P>
IT INCLUDES A SIX PERCENT PAY RAISE RETROACTIVE TO LAST JULY, AND IMPROVED HEALTH BENEFITS.
<P>
"IT CATCHES US UP. WE WERE 16-TH OUT OF 17 IN TERMS OF PAY IN STATE. WE'RE NOT THERE YET.BUT NOT NEAR THE BOTTOM ANY MORE."
<P>
I ANTICIPATE RATIFICATION. SETTLEMENT IS FAIR, KEEPS THE DISTRICT SOLVENT, NEED TO HEAL THE WOUND.
<P>
EGAN SAYS HE'S CONFIDENT TEACHERS WILL VOTE IN FAVOR OF THE NEW CONTRACT THIS FRIDAY.
<P>
THE PLAN HAS THE FULL BACKING OF THE NEGOTIATING TEAM. AND THE EXECUTIVE BOARD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
