<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Friday, 3/6/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Friday, 3/6/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Cold Open(chitten)>Cold Open(chitten)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(high speed) >bump 2(high speed) </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Chittenden fire>Chittenden fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134Lottery shooting-INT>Lottery shooting-INT</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Moore arraign-INT>Moore arraign-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(landlord arrest)>(landlord arrest)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Moore arraign-TAG>Moore arraign-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(vampire vandals)>(vampire vandals)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Amick verdict>Amick verdict</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(capeman closes)>(capeman closes)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Daisy Mescada>Daisy Mescada</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22(high speed chase)>(high speed chase)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Aptos pot bust>Aptos pot bust</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/longs suit>Fox Biz/longs suit</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Big Sur Today/RC>Big Sur Today/RC</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50steinbeck tally>steinbeck tally</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132Big Sur/ Mo co>Big Sur/ Mo co</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140SVMH Heart>SVMH Heart</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(lottery) >Bump 1(lottery) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137IMAX/everest-INT>IMAX/everest-INT</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=114Cold Open(chitten)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cold Open(chitten)</H3><BR>
DESPITE THE HEROIC EFFORTS OF A FORMER POLICE OFFICER. A YOUNG BOY DIES IN TRAGIC HOUSE FIRE IN SANTA CRUZ.  
<P>
THAT STORY NEXT ON K-C-B-A FOX NEWS FIRST AT TEN. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Chittenden fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chittenden fire</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
A FIRE GUTS A HOUSE IN AROMAS. FOLLOWING A PROPANE TANK EXPLOSION LAST NIGHT.
<P>
AND DESPITE THE HEROIC EFFORTS OF A QUICK THINKING NEIGHBOR. THE EIGHT YEAR OLD BOY WHO WAS INSIDE THE HOME.  HAS DIED.
<P>
        IT HAPPENED JUST BEFORE 11:30 LAST NIGHT.
<P>
NEIGHBOR JACKIE SOOHOO. A FORMER POLICE OFFICER. RAN TO THE BURNING HOME AND PULLED THE EIGHT-YEAR-OLD BOY OUT OF THE WINDOW.
<P>
WHEN SHE SPOKE TO US TODAY. THE LITTLE BOY SHE RESCUED WAS STILL CLINGING TO LIFE.
<P>
"I HAVE AN 8-YEAR OLD SON EXACTLY THE SAME AGE AS HIM. THEY'RE BEST FRIENDS.  AND GETTING HIS UNCONSCIOUS BODY OUT OF THE WINDOW WAS VERY SCARY."
<P>
        THE BOY'S MOTHER. TANYA HOLLANDER, AND HER BOYFRIEND, HAD THOUGHT HER SON MADE IT OUT, BEFORE THEY ESCAPED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
A NORTH SALINAS MAN ACCUSED OF KILLING HIS 11-YEAR-OLD NEXT DOOR NEIGHBOR IS BROUGHT BEFORE A JUDGE TODAY.
<P>
CHERI GYURO IS FOLLOWING THE STORY, SHE JOINS US LIVE FROM THE MONTEREY COUNTY COURTHOUSE WITH MORE, CHERI, WHAT HAPPENED IN COURT TODAY?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Moore arraign-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Moore arraign-INT</H3><BR>
ALAN, A MONTEREY COUNTY JUDGE CHARGED 47-YEAR-OLD RONALD MOORE WITH MURDER AND BURGLARY.THERE'S ALSO A SPECIAL CHARGE THE COULD MAKE HIM ELIGIBLE FOR THE DEATH PENALTY.IF HE'S CONVICTED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Moore arraign-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Moore arraign-TAG</H3><BR>
A MEMORIAL FUND HAS BEEN SET UP FOR NICOLE CARNAHAN AT THE BANK OF SALINAS.IF YOU'RE INTERESTED IN DONATING.CALL THE NUMBER ON YOUR SCREEN.757-2274.
<P>
MEANWHILE.RONALD MOORE IS BEING HELD AT THE MONEREY COUNTY JAIL WITHOUT BAIL.
<P>
HE'LL BE BACK IN COURT AGAIN NEXT TUESDAY.
<P>
REPORTING LIVE IN SALINAS I'M CHERI GYURO, ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Amick verdict>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Amick verdict</H3><BR>
A SANTA CRUZ JUDGE HAS FOUND A 20-YEAR OLD
<P>
MAN GUILTY OF 5-COUNTS OF SEXUAL ASSAULT. FOR A 
<P>
SERIES OF RAPES INVOLVING TEENAGE GIRLS.
<P>
        RICHARD AMICK ADMITTED HE RAPED ONE WOMAN WHO WAS
<P>
UNCONSCIOUS.
<P>
        PROSECUTORS HAD PRODUCED WITNESSES WHO SAID AMICK TOOK ADVANTAGE OF HIS VICTIMS.  AFTER GIVING THEM LIQUOR THAT MAY HAVE BEEN SPIKED WITH DRUGS.
<P>
        AMICK WAS FOUND. GUILTY OF SEXUAL BATTERY, FALSE IMPRISONMENT, AND HAVING SEX WITH AN UNDERAGE WOMAN.
<P>
        THE D-A'S OFFICE IS ASKING FOR A SENTENCE OF AT LEAST SIX YEARS.
<P>
"WE JUST DON'T THINK THAT ANY PERSON WHO HAS BEEN FOUND GUILTY
<P>
OF ASSAULTING WOMEN WHILE THEY ARE EITHER ASLEEP, UNCONSCIOUS,
<P>
OR IN SOME OF THESE CASES, WE BELIEVE DRUGGED BY MR. AMICK, IS
<P>
SOMEONE WE WANT ON OUR STRETS, AND IS A VIABLE CANDIDATE FOR
<P>
PROBATION."
<P>
"THIS IS A LEARNING PROCESS FOR EVERYONE.  MY CLIENT KNOWS HE'S
<P>
MADE MISTAKES, KNOWS HE'S DONEHINGS WRONG, AND SOME OF THE 
<P>
TRAGEDY OF YOUTH THAT OCCURS;ALCOHOL, IS A BIG FACTOR IN
<P>
THIS."
<P>
        SENTENCING FOR AMICK IS SET FOR APRIL 27TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Daisy Mescada>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Daisy Mescada</H3><BR>
DAISY MESCADA. THE LOCAL WOMAN WHO ADMITS SHE SEVERED HER BOYFRIEND'S PENIS. WILL REMAIN IN CUSTODY FOR THE TIME BEING.
<P>
MESCADA'S SENTENCING HAS BEEN POSTPONED UNTIL A SPECIALIZED TEST CAN BE CONDUCTED.
<P>
THE JUDGE ORDERED A DIAGNOSTIC TEST TO DETERMINE IF MASCADA SHOULD GO TO PRISON OR NOT.
<P>
THE JUDGE MADE THAT ANNOUNCEMENT FOLLOWING MORE TESTIMONY FROM WITNESS'S. INCLUDING MESCADA'S SISTER.  AND A DOCTOR. WHO SAYS MESCADA SUFFERS FROM POST TRAUMATIC STRESS DISORDER. AND BATTERED WOMAN'S SYNDROME.
<P>
"WHAT IT MEANS IS SHE'S BEEN VIOLATED NUMEROUS TIMES AND HER SENSE OF ANY TYPE OF SAFETY FROM THIS MAN IS GONE."
<P>
MESCADA MAINTAINS SHE SNAPPED AFTER 6 MONTHS OF EMOTIONAL, SEXUAL AND PHYSICAL ABUSE.
<P>
THE PROSECUTION SAYS SHE WAS JEALOUS OF ANOTHER WOMAN AND PLANNED THE CRIME.
<P>
IT MAY TAKE AS MANY AS SIX MONTH TO RECEIVE THE TEST RESULTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Aptos pot bust>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Aptos pot bust</H3><BR>
SHERIFF'S DEPUTIES IN SANTA CRUZ COUNTY HAVE SHUT DOWN A HIGH TECH IN-DOOR MARIJUANA GARDEN.
<P>
DEPUTIES SAY THE CULTIVATION AND PROCESSING OPERATION WAS BEING RUN IN AN APTOS HOME.
<P>
DEPUTIES SEIZED MORE THAN A QUARTER MILLION DOLLARS WORTH OF POT. AND ARRESTED THE SUSPECTED OPERATORS.  32-YEAR-OLD MICHAEL SHINER. AND 27-YEAR-OLD HEATHER GARRETT.
<P>
MORE THAN 400 GROWING PLANTS. AND NEARLY 200 MATURE DRIED PLANTS WERE SEIZED INSIDE THEIR HOME ON EL SERENO COURT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Big Sur Today/RC>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Sur Today/RC</H3><BR>
IT'S BEEN FIVE WEEKS SINCE HIGHWAY ONE DAMAGE CUT OFF BIG SUR RESIDENTS.
<P>
TODAY. THE RED CROSS MADE A SPECIAL TRIP TO THE ISOLATED AREA.
<P>
RELIEF WORKERS HAD TO CROSS NACIMIENTO FERGUSON ROAD TO GET THERE.
<P>
DOZENS OF RESIDENTS GATHERED TO SIGN UP FOR AID THIS AFTERNOON.
<P>
MANY OF THESE FOLKS HAVE ALSO APPLIED FOR UNEMPLOYMENT BENEFITS BECAUSE OF THE SITUATION. THEY'RE HOPING THE RED CROSS CAN FILL IN THE GAP.
<P>
.WAITING FOR THE ROAD TO OPEN
<P>
RED CROSS WORKERS WILL ALSO BE TAKING APPLICATIONS FOR DISASTER RELIEF TOMORROW.
<P>
FOLKS WHO QUALIFY WILL GET VOUCHERS FOR FOOD AND FUEL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132Big Sur/ Mo co>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Sur/ Mo co</H3><BR>
RELIEF FOR STRANDED BIG SUR RESIDENTS ALSO CAME IN THE FORM OF FOOD SUPPLIES TODAY.
<P>
A HUNDRED BOXES OF FOOD FROM THE MONTEREY COUNTY FOOD BANK WERE DELIVERED THIS AFTERNOON.
<P>
THE EMERGENCY RATIONS INCLUDED NON-PERISHABLES ITEMS LIKE PASTA, RICE, BEANS. AND CANNED FRUITS AND VEGETABLES.
<P>
FOOD BANK OFFICIALS SAY THEY'LL CONTINUE TO DELIVER THE EMERGENCY RATIONS ONCE A WEEK UNTIL HIGHWAY ONE IS REPAIRED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(lottery) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(lottery) </H3><BR>
UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
A LOTTERY OFFICE IS THE SCENE OF A DEADLY SHOOTING RAMPAGE TODAY. WILL TELL YOU WHERE IT HAPPENED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(high speed) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(high speed) </H3><BR>
AND POLICE IN SACRAMENTO FIND A LITTLE BUMP IS JUST THE THING TO END A DANGEROUS HIGH-SPEED CHASE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134Lottery shooting-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lottery shooting-INT</H3><BR>
A CONNECTICUT OFFICE BUILDING BECAME THE SCENE OF A BLOODY MASSACRE TODAY. 
<P>
A DISGRUNTLED EMPLOYEE SHOWED UP FOR WORK AT THE CONNECTICUT STATE LOTTERY HEADQUARTERS WITH A GUN. HE SHOT AND KILLED FOUR COWORKERS. BEFORE KILLING HIMSELF AS THE POLICE CLOSED IN. 
<P>
FOX'S RICK LEVENTHAL HAS MORE ON THE TRAGIC STORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A LANDLORD IS BEHIND BARS TONIGHT. AFTER HE WAS CAUGHT ON VIDEO TAPE. RUMMAGING THROUGH ONE OF HIS TENANT'S APARTMENTS. AND WORSE.
<P>
THAT STORY FROM LONG ISLAND, NEW YORK.  TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(landlord arrest)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(landlord arrest)</H3><BR>
POLICE SAY THE LANDLORD USED HIS MASTER KEY TO ENTER THE APARTMENT. THREE TIMES IN FIVE DAYS.
<P>
THE MAN WAS CAUGHT ON TAPE RUMMAGING THROUGH THE APARTMENT. THROWING THINGS AROUND. AND URINATING IN THE REFRIGERATOR BEFORE MAKING HIS EXIT.
<P>
THE TENANT PLANTED THE CAMERA AFTER SUSPECTING THE LANDLORD WAS SNOOPING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(vampire vandals)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(vampire vandals)</H3><BR>
FOUR TEENAGERS WHO CLAIM TO BE VAMPIRES WERE ARRESTED AFTER A SUBURBAN CRIME SPREE. 
<P>
THE BOYS REPORTEDLY TRASHED A MIDDLE-CLASS DALLAS NEIGHBORHOOD. SPRAY PAINTING CARS AND SLASHING TIRES. 
<P>
THEY ALSO TORCHED A LOCAL LUTHERAN CHURCH WITH MOLOTOV COCKTAILS. AND PAINTED "SIX-SIX-SIX," OBSCENITIES AND RACIST GRAFFITI ON WALLS THROUGHOUT THE PREDOMINANTLY WHITE AREA. 
<P>
THE GANG WAS ARRESTED AFTER THEY WERE CAUGHT SPYING ON THE ARSON INVESTIGATORS. WHO WERE LOOKING AT THE CHARRED RUINS OF THE CHURCH. 
<P>
THE DAMAGE IS ESTIMATED TO BE AROUND 300-THOUSAND DOLLARS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(capeman closes)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(capeman closes)</H3><BR>
SONGWRITER TURNED PLAYWRIGHT PAUL SIMON'S FIRST ATTEMPT AT BROADWAY THEATER IS ABOUT TO END IN FAILURE. 
<P>
ON MARCH 28TH.  AFTER JUST TWO MONTHS. THE CURTAINS WILL CLOSE. FOR GOOD. ON SIMON'S MUSICAL, "THE CAPEMAN". MAKING IT THE BIGGEST FLOP EVER TO HIT BROADWAY. 
<P>
IT COST 11-MILLION DOLLARS TO STAGE THE SHOW. AND IT'S ONLY MADE ABOUT A MILLION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22(high speed chase)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(high speed chase)</H3><BR>
A DRAMATIC END TO HIGH SPEED CHASE IN SACRAMENTO. AS POLICE RAM THE CAR TO A HALT.
<P>
POLICE THEN CHASED 30-YEAR-OLD LEON WYNNE, JR. ON FOOT.
<P>
WYNNE IS WANTED ON FELONY KIDNAPPING  AND SPOUSAL ABUSE CHARGES. AND NOW ADDITIONAL CHARGES OF FLEEING POLICE. 
<P>
OFFICIALS SAY THE RAMMING MANUEVER WORKED JUST THE WAY IT SHOULD HAVE TO CAPTURE WYNNE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/longs suit>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/longs suit</H3><BR>
A GROUP OF PHARMACISTS IS SUING LONGS DRUGS FOR REFUSING TO PAY THEM OVERTIME.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
THE FEDERAL CLASS ACTION SUIT CLAIMS LONGS REFUSED TO PAY THEM TIME AND A HALF WHEN THEY WORKED MORE THAN 40 HOURS IN ONE WEEK.
<P>
THE PHARMACISTS HAVE ALSO ASKED FOR THE HELP OF THE UNITED FOOD AND COMMERCIAL WORKERS UNION. EVEN THOUGH THEY ARE IN NOT IN A UNION.
<P>
LAST YEAR. THE U-F-C-W HELPED NON-UNION ALBERTSON'S EMPLOYEES WIN A BACK-PAY SETTLEMENT.
<P>
WAL-MART IS ALSO CURRENTLY BEING SUED BY IT'S PHARMACISTS TO COLLECT UNPAID OVERTIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50steinbeck tally>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>steinbeck tally</H3><BR>
THE TALLY IS IN FOR THE STEINBECK DREAM HOUSE GIVE-AWAY.
<P>
ORGANIZERS SAY THEY MADE MORE THAN A HALF MILLION DOLLARS FOR THE NATIONAL STEINBECK CENTER MUSEUM.
<P>
THE LAST MINUTE PUSH SEEMS TO HAVE PAID OFF. MOST OF THE TICKETS WERE SOLD IN THE LAST TWO WEEKS BEFORE THE DRAWING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140SVMH Heart>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SVMH Heart</H3><BR>
IMAGINE.SOMEONE IN YOUR FAMILY NEEDS OPEN HEART SURGERY.
<P>
USUALLY, THEY'D BE SENT TO A HOSPITAL ALMOST TWO HOURS AWAY, LIKE STANFORD.
<P>
BUT ADMINISTRATORS AT SALINAS VALLEY MEMORIAL HOSPITAL ARE MAKING LIFE A LITTLE EASIER FOR LOCAL HEART PATIENTS.
<P>
THE EXPANSION OF THE HEART CENTER OPENED TODAY.
<P>
THE MULTI-MILLION DOLLAR FACILITY WILL HAVE THE LATEST STATE-OF-THE ART TECHNOLOGY, RIGHT IN OUR OWN BACK YARD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137IMAX/everest-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>IMAX/everest-INT</H3><BR>
NOT MANY OF US WILL HAVE THE CHANCE. OR WANT TO TAKE THE RISK. TO GET TO THE TOP OF THE WORLD'S HIGHEST PEAK. 
<P>
BUT NOW. FROM THE COMFORT OF A MOVIE SEAT. YOU CAN EXPERIENCE MOUNT EVEREST'S MAJESTY. AND FEEL THE FEAR AS CLIMBERS PICK THEIR WAY TO THE TOP.
<P>
THE FAMOUS MOUNTAIN IS NOW THE SUBJECT OF AN IMAX MOVIE.  
<P>
FOX'S MARIA STEPHANOS HAS A LOOK AT THE MAN WHO RISKED HIS LIFE TO MAKE THE FILM. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
