<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Wednesday, 3/18/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Wednesday, 3/18/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(mob hit)>(mob hit)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107PG Lucky's-INT>PG Lucky's-INT</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(Stockton drug bust)>(Stockton drug bust)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109PG Lucky's-TAG>PG Lucky's-TAG</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22(minnesota/canada)>(minnesota/canada)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Marijuana mayors>Marijuana mayors</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(kennedy auction)>(kennedy auction)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Prop 187>Prop 187</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/Dodgers>Fox Biz/Dodgers</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Lamb trial>Lamb trial</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139El Nino future-INT>El Nino future-INT</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Stop the bus >Stop the bus </A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Sprewell>Sprewell</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Mty historic site>Mty historic site</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Final Four>Final Four</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/Kaiser>Good News/Kaiser</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Drexler>Drexler</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Quake danger-INT>Quake danger-INT</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(Fox biz) >Bump 1(Fox biz) </A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(El nino) >bump 2(El nino) </A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50PB/SPCA mural>PB/SPCA mural</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141PG HS city council>PG HS city council</A></TD>

</Table>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
        A CONTROVERSIAL ISSUE IN THE CITY OF PACIFIC GROVE TONIGHT.
<P>
        IT INVOLVES TWO THINGS P.G. FOLKS ARE PASSIONATE ABOUT.GROWTH AND TREES.
<P>
        CHERI GYURO IS COVERING THE ISSUE AND JOINS US LIVE FROM OUR MONTEREY BUREAU WITH MORE CHERI?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107PG Lucky's-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG Lucky's-INT</H3><BR>
        ALAN.FOLKS WHO LIVE NEAR THE LUCKY SUPERMARKET ON FOREST AVENUE PROBABLY RECEIVED ONE OF THESE FLYERS IN THE MAIL.
<P>
        A QUESTIONARE ABOUT HOW THE STORE CAN IMPROVE.
<P>
        IT'S ALL A PART OF AN EXPANSION PROJECT THAT HAS SOME FOLKS STEAMING MAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109PG Lucky's-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG Lucky's-TAG</H3><BR>
        THE MATTER WILL BE ON THE APRIL 15 COUNCIL ADGENDA.DURING A PUBLIC HEARING.
<P>
        REPORTING LIVE FROM THE MONTEREY BUREAU I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Marijuana mayors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marijuana mayors</H3><BR>
THE MAYORS OF FOUR CALIFORNIA CITIES. INCLUDING SANTA CRUZ. WANT PRESIDENT CLINTON'S HELP IN KEEPING MEDICAL MARIJUANA CLINICS OPEN IN THE STATE. 
<P>
        SAN FRANCISCO MAYOR WILLIE BROWN WROTE A LETTER. URGING  THE PRESIDENT TO SUPPORT A BILL THAT WOULD SET UP A TASK FORCE TO ADDRESS THE ISSUE.  INSTEAD OF SHUTTING DOWN THE CLUBS.
<P>
        ALL FIVE OF THE MAYORS' LETTERS SAID THE WELL-BEING OF 11-THOUSAND CALIFORNIANS IS AT STAKE.
<P>
        LOCAL CANNABIS CLUB ATTORNEY KATE WELLS. SAYS SHE WELCOMES THIS KIND OF SUPPORT.
<P>
"I think that the cities are well aware of the fact that we are doing
<P>
them a favor.  When you think about all of those patients in wheel chairs and crutches, wandering along the levy here in Santa Cruz, risking life and limb to get their medication, and then when they get it; we have patients that would die if they got a small amount of mold."
<P>
        WELLS SAYS THE SANTA CRUZ CANNABIS CLUB WAS FORCED TO SHUT DOWN. AFTER LOCAL LEADERS IMPOSED STRICT REGULATIONS FOR THE DISTRIBUTION OF MEDICAL MARIJUANA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Prop 187>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prop 187</H3><BR>
PROP 187 IS NOW OFFICIALLY DEAD.
<P>
CALIFORNIA'S VOTER APPROVED LAW TO DENY BENEFITS TO UNDOCUMENTED IMMIGRANTS. WAS RULED COMPLETELY UNCONSTITUTIONAL. BY A LOS ANGELES FEDERAL JUDGE  TODAY.
<P>
IN NOVEMBER. THE SAME JUDGE STRUCK DOWN MOST PROVISIONS OF THE MEASURE. TODAY SHE REJECTED THE REST OF IT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Lamb trial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lamb trial</H3><BR>
TRIAL IS UNDERWAY TO DETERMINE IF A FORMER MONTEREY COUNTY MAN  SHOULD GO BACK TO PRISON UNDER THE SEXUAL PREDATORS LAW.
<P>
38-YEAR-OLD JAMES LAMB WAS CONVICTED OF CHILD MOLESTATION TWICE. ONCE IN 1984 ON TWO COUNTS. AND AGAIN IN 1991. 
<P>
WITHIN A MONTH OF BEING RELEASED FROM PRISON LAST JUNE. LAMB WAS FOUND TO BE IN POSSESSION OF PORNOGRAPHY, AND PICTURES OF YOUNG BOYS.
<P>
THOSE ARE VIOLATIONS OF HIS PROBATION.
<P>
TODAY, A NOTED PSYCHIATRIST TESTIFIED THAT LAMB DOESN'T FIT THE CRITERIA FOR BEING A SEXUAL PREDATOR. BUT UNDER CROSS EXAMINATION DR. ROBERT HALON CHANGED HIS MIND.
<P>
HE'S PREDISPOSED TO DO IT. VOLITIONALLY IMPAIRED..SUBSTANTIAL SEXUAL CONTACT.
<P>
CLOSING ARGUMENTS IN THE CASE ARE EXPECTED TO WRAP UP TOMORROW, THE JURY COULD GET THE CASE BY FRIDAY.
<P>
LAMB COULD BE SENT BACK TO PRISON FOR TWO YEARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Stop the bus >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stop the bus </H3><BR>
NEARLY THREE MONTHS AFTER THE NEW LAW WENT INTO EFFECT. MANY DRIVERS ARE STILL IGNORING THE FLASHING RED SCHOOL BUS LIGHTS.
<P>
THE LAW IS DESIGNED TO PROTECT CHILDREN GETTING ON AND OFF SCHOOL BUSSES.
<P>
IF THE FLASHING RED LIGHTS ARE ON. CARS MUST STOP. IN BOTH DIRECTIONS.
<P>
TODAY. SALINAS POLICE JOINED FORCES WITH C-H-P TO ALERT VIOLATORS.
<P>
WE'VE RECEIVED. NOBODY'S COMPLYING WITH IT.
<P>
POLICE ISSUED 16 TICKETS TODAY. INCLUDING ONE TO A FORMER SCHOOL BUS DRIVER.
<P>
THE FIRST OFFENSE IS 150 DOLLARS. THREE VIOLATIONS IN ONE YEAR AND YOUR LICENSE GETS SUSPENDED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Mty historic site>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mty historic site</H3><BR>
PROPERTY OWNERS IN MONTEREY. WANTING  TO TEAR DOWN BUILDINGS MORE THAN FIFTY YEARS OLD. WILL NOW HAVE AN EXTRA HOOP TO JUMP THROUGH.
<P>
BEFORE GETTING A DEMOLITION PERMIT. PROPERTY OWNERS MUSH GET THE APPROVAL OF THE HISTORIC PRESERVATION COMMISSION.
<P>
IT'LL BE THAT COMMISSION'S JOB TO DETERMINE IF THE BULDING HAS ANY HISTORICAL SIGNIFICANCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/Kaiser>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/Kaiser</H3><BR>
GOOD NEWS FOR STRIKING NURSES AT KAISER PERMANENTE.
<P>
THE UNION HAS REACHED A TENTATIVE AGREEMENT WITH THE HOSPITAL. 
<P>
KAISER'S NURSES HAVE BEEN STRIKING FOR ABOUT A YEAR NOW OVER CONTRACTS.IN ABOUT THREE DOZEN CITIES. INCLUDING GILROY.
<P>
AS PART OF THE PROPOSAL.MEMBERS OF THE UNION WILL RECEIVE A 9-PERCENT WAGE INCREASE OVER THREE YEARS.
<P>
BENEFITS WON'T BE CUT. AND EMPLOYEES WILL HAVE A SAY OVER SICK TIME AND VACATION.
<P>
A FINAL VOTE ON THE AGREEMENT WILL BE HELD ON APRIL 12-TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Quake danger-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Quake danger-INT</H3><BR>
CALIFORNIANS CAN RELAX, A LITTLE. 
<P>
SCIENTISTS NOW SAY WE WON'T BE HAVING MORE EARTHQUAKES THAN USUAL. ANYTIME SOON. 
<P>
BUT AS FOX'S REBECCA GOMEZ REPORTS WE COULD STILL BE IN FOR "THE BIG ONE".  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(Fox biz) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(Fox biz) </H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
ATLANTA BRAVES OWNER TED TURNER IS LOOKING TO TOMAHOC CHOP  FOX OWNER RUPERT MURDOCH'S BID TO BUY THE DODGERS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(El nino) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(El nino) </H3><BR>
AND JUST WHEN YOU THOUGHT IT WAS SAFE TO GO OUTSIDE. EL NINO MAY ONCE AGAIN BE REARING IT'S UGLY HEAD. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
POLICE IN PHILADELPHIA ARE CALLING A FATAL SHOOTING THIS MORNING A "MOB HIT". 
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(mob hit)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(mob hit)</H3><BR>
THE MAN WHO WAS "HIT". ANTHONY TURRA. WAS AN ACCUSED MOB HITMAN HIMSELF.  
<P>
THE 61-YEAR OLD TURRA. WHO WAS WHEELCHAIR BOUND WITH CANCER. WAS BEING LED OUT OF HIS SOUTH PHILADELPHIA HOME. WHEN A MASKED GUNMAN SHOT HIM. 
<P>
POLICE SAY THEY HAVE NO SUSPECTS IN THE KILLING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(Stockton drug bust)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Stockton drug bust)</H3><BR>
POLICE IN STOCKTON STOP A CAR BECAUSE OF A BURNT OUT REAR LICENSE PLATE LIGHT. AND END UP FINDING 11-MILLION DOLLARS IN COCAINE.
<P>
IT HAPPENED ON INTERSTATE 5 LAST NIGHT. 
<P>
THE TWO PEOPLE IN THE CAR HAVE BEEN CHARGED WITH TRANSPORTING ILLEGAL DRUGS.
<P>
A CONVICTION COULD PUT THEM BEHIND BARS FOR 20 YEARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22(minnesota/canada)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(minnesota/canada)</H3><BR>
FOLKS LIVING IN A REMOTE CORNER OF MINNESOTA ARE LOOKING TO GIVE UP THEIR CITIZENSHIP. SO THEY CAN KEEP THEIR LIVELIHOOD.
<P>
NORTHWEST ANGLE IS ACCESSIBLE ONLY THROUGH CANADA. AND IS NOT PHYSICALLY CONNECTED TO THE REST OF MINNESOTA.
<P>
THE PEOPLE WHO LIVE THERE SAY ONTARIO HAS RESTRICTED THEIR FISHING PRIVILEGES.
<P>
SO THEY ASKED THEIR CONGRESSMAN TO PROPOSE AN AMENDMENT TO THE CONSTITUTION. TO ALLOW THEM TO VOTE ON WHETHER THEY WANT TO SECEDE FROM THE U-S. AND JOIN MANITOBA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(kennedy auction)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(kennedy auction)</H3><BR>
A ROCKING CHAIR AND A SWEATER ARE JUST TWO OF THE ITEMS ONCE BELONGING TO THE LATE JOHN F- KENNEDY.  THAT ARE BEING AUCTIONED OFF IN NEW YORK. 
<P>
NOT ON THE BLOCK ARE A CLOCK HE KEPT IN THE OVAL OFFICE AND TWO OF HIS HANDWRITTEN JOURNALS. 
<P>
KENNEDY'S CHILDREN ASKED FOR THOSE BACK. AND COLLECTOR ROBERT WHITE AGREED IN A  LAST-MINUTE DEAL. 
<P>
ONE LOT. INCLUDING A HANDWRITTEN LINE FROM J-F-K'S INAUGURAL ADDRESS. AS WELL AS NINE PHOTOCOPIED PAGES THE SPEECH. HAS ALREADY FETCHED 39-THOUSAND 
<P>
DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/Dodgers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/Dodgers</H3><BR>
A LONGTIME RIVAL OF RUPERT MURDOCH IS "STEPPING UP TO THE PLATE". TO KEEP THE AUSTRALIAN MEDIA TITAN FROM BUYING THE L-A DODGERS. 
<P>
BUT TED TURNER AND PUBLIC SENTIMENT MAY NOT BE ENOUGH TO STOP THE "GRAND SLAM"-SIZE DEAL.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
THE O'MALLY FAMILY TRANSFERED OWNERSHIP OF THE DODGERS TO MURDOCH'S FOX GROUP LAST FRIDAY. 
<P>
THE PRICE TAG. 300-MILLION DOLLARS.
<P>
BUT 14 OF THE 16 NATIONAL LEAGUE OWNERS AND 8 OF THE 14 AMERICAN LEAGUE OWNERS NEED TO OKAY THE DEAL.
<P>
ATLANTA BRAVES OWNER TED TURNER IS THE BIGGEST STUMBLING BLOCK.
<P>
TURNER HAS BEEN TRYING TO BLOCK THE SALE FROM THE VERY BEGINNING. WILL ATTEND HIS FIRST OWNERS MEETING SINCE 19-89. TO TRY AND RALLY SUPPORT AGAINST MURDOCH.
<P>
WHILE SOME TEAMS HAVE EXPRESSED RESERVATIONS. THE TRANSFER IS EXPECTED TO BE BE APPROVED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139El Nino future-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>El Nino future-INT</H3><BR>
SPRING IS JUST TWO DAYS AWAY. AND THAT MAY BE A BLESSING FOR MANY AMERICANS STUNG BY WICKED EL NINO WINTER STORMS. 
<P>
BUT DON'T UN-BATTEN THE HATCHES JUST YET. 
<P>
EL NINO HAS A SISTER. AND SHE COULD BRING SOME MORE WICKED WEATHER THIS WAY. 
<P>
FOX'S CARLOS HARRISON HAS MORE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Sprewell>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sprewell</H3><BR>
HE MAY HAVE HAD HIS CONTRACT REINSTATED WITH THE WARRIORS, BUT LATRELL SPREWELL COULD NOW FACE UP TO 30-DAYS IN JAIL.
<P>
TODAY IN MARTINEZ, CALIFORNIA, THE DISTRICT ATTOURNEY FORMALLY CHARGED SPREWELL WITH RECKLESS DRIVING.
<P>
IT WAS A COUPLE WEEKS AGO THAT SPREWELL WAS ALLEGEDLY  DRIVING 90 MILES PER HOUR ON THE FREEWAY, TRIED TO GET BACK ONTO THE HIGHWAY FROM AN EXIT ONLY LANE.
<P>
HE STRUCK ANOTHER CAR, WHICH OVERTURNED. SPREWELL WAS UNHURT, BUT ARNULFO PERLAS, 54, AND IRMA FELICIANO, 53, SUSTAINED MINOR INJURIES.
<P>
THE WARRIORS' SUSPENDED GUARD WAS DRIVING A 1997 MERCEDES AT THE TIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Final Four>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Final Four</H3><BR>
MARCH MADNESS CONTINUES TOMORROW. STANFORD AND U.C.L.A. PLAY FRIDAY, BUT THE DEFENDING NATIONAL CHAMPION ARIZONA WILDCATS BATTLE THE MARYLAND TERRAPINS THURSDAY NIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Drexler>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Drexler</H3><BR>
IN OTHER HOOP NEWS, AT THE END OF THIS NBA SEASON, CLYDE DREXLER WILL RETIRE FROM THE HOUSTON ROCKETS, AND TAKE OVER AS HEAD COACH OF HIS ALMA MATTER, THE UNIVERSITY OF HOUSTON.
<P>
DREXLER LED PHI SLAMA JAMMA TO A COUPLE OF FINAL FOURS, HE HAS AN NBA CHAMPIONSHIP RING WITH THE ROCKETS.
<P>
AND AN OLYMPIC GOLD MEDAL FROM THE ORIGINAL DREAM TEAM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
SHARKS BACKUP GOALIE KELLY RUDY IS 5 AND 1 VS. DALLAS. SO ITS RUDY IN NET TONITE, AS THE SHARKS HOST THE STARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
BARRY BONDS MISSED THE GIANTS CACTUS LEAGUE GAME YESTERDAY TO HAVE AN MRI DONE ON HIS SORE BACK.
<P>
EVERYTHIHG CHECKED OUT, AND BARRY WAS IN THE LINEUP TODAY.
<P>
EARLIER THIS WEEK, BONDS WAS ASKED IF HE PLANS TO SPEND THE REST OF HIS CAREER, WITH THE GIANTS?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50PB/SPCA mural>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PB/SPCA mural</H3><BR>
THIRD GRADERS AT SHERWOOD ELEMENTARY ARE DOING THIER PART TO HELP PRESERVE SEALIFE IN THE MONTEREY BAY.
<P>
EACH YEAR THE PEBBLE BEACH COMPANY ERECTS A WALL TO SAFEGUARD THE PRIVACY OF HARBOR SEALS AND THIER NEWBORN PUPS.
<P>
SCHOOL KIDS ARE ASKED TO DECORATE THAT BARRIER WITH BEAUTIFUL MURALS.
<P>
TODAY THE STUDENTS AT SHERWOOD PAINTED THIER PANEL.
<P>
ITS ONE OF THIRTY-SEVEN THAT'LL ULTIMATELY MAKE UP THE WALL AT PEBBLE BEACH.
<P>
NOT ONLY DO THE KIDS GET A CHANCE TO EXHIBIT THIER ARTISTIC SKILLS. THEY ALSO GET A VALUABLE LESSON IN MARINE BIOLOGY AND CONSERVATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141PG HS city council>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG HS city council</H3><BR>
FINALLY TONIGHT. THE PACIFIC GROVE HIGH SCHOOL BASKET BALL TEAM IS OFF TO THE STATE CHAMPIONSHIPS IN SACRAMENTO THIS FRIDAY. 
<P>
BUT WHETHER THEY WIN OR LOSE THEY'RE STILL LOCAL HEROES.
<P>
----CHEERING----
<P>
TONIGHT THE CITY COUNCIL CONGRATULATED THE ENTIRE TEAM FOR GETTING THIS FAR. AND PROMISED TO BE ON THE BOOSTER BUS. ALONG WITH THE REST OF THE FANS AND FAMILY. TO CHEER THEM ON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
