<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Tuesday, 3/31/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Tuesday, 3/31/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x033114.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Jonesboro Memorial>Jonesboro Memorial</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Deregulation - i>Deregulation - i</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Clinton/Miss America>Clinton/Miss America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Deregulation - t>Deregulation - t</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118Whale Rescue>Whale Rescue</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Highway 1 Dirt Delay>Highway 1 Dirt Delay</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Chewing Tobacco>Chewing Tobacco</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Pinnacles Reopen>Pinnacles Reopen</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#149Therapeutic Touch>Therapeutic Touch</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Pogonip Meeting>Pogonip Meeting</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Grape Juice>Grape Juice</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Smoking in Line>Smoking in Line</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#150877 Area Code>877 Area Code</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Firefighter Rules>Firefighter Rules</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Business News>Fox Business News</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Dispatch Center Sup>Dispatch Center Sup</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121TZ/Toss to Sandhya>TZ/Toss to Sandhya</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145Seaside ATM Rob>Seaside ATM Rob</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Watsonville Ozone>Watsonville Ozone</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142UCSC El Nino Grant>UCSC El Nino Grant</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143UC Minorities>UC Minorities</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Peacebuilders Award>Peacebuilders Award</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/Mo.D.A.>Good News/Mo.D.A.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Buddy Hackett>Buddy Hackett</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
HISTORY IS MADE IN CALIFORNIA.
<P>
IN JUST TWO HOURS THE CENTRAL COAST WILL NO LONGER HAVE A MONOPOLY POWER SERVICE.
<P>
HOW WILL THIS EFFECT PG&E CUSTOMERS?
<P>
CHERI GYURO JOINS US NOW FROM THE NEWS DESK WITH THE ANSWER. CHERI?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Deregulation - i>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Deregulation - i</H3><BR>
ALAN, THE CALIFORNIA PUBLIC UTILITIES COMMISSION FINALIZED THE DE-REGULATION ORDER TODAY.
<P>
IT GOES INTO EFFECT AT MIDNIGHT.
<P>
NOW, THE STATE'S ELECTRICITY INDUSTRY WILL BE OPEN TO SOME BIG TIME COMPETITION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Deregulation - t>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Deregulation - t</H3><BR>
IF YOU'RE CONFUSED ABOUT THE NEW DEREGULATION ORDER.THERE'S AN 800 NUMBER YOU CAN CALL.
<P>
1-800-253-0500.
<P>
PG&E OFFICIALS SAY THEY'RE REDUCING ELECTRIC BILLS BY TEN PERCENT.AND WILL FREEZE THE RATES UNTIL 2004.
<P>
BUT THAT'S JUST ONE OF HUNDREDS OF OFFERS.GET READY TO FIND YOUR MAILBOX STUFFED WITH FLYERS FROM OTHER ELECTRIC COMPANIES.
<P>
REPORTING LIVE FROM THE NEWS DESK.I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Highway 1 Dirt Delay>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Highway 1 Dirt Delay</H3><BR>
CALTRANS ENGINEERS WORKING TO REPAIR STORM DAMAGED HIGHWAY ONE. FACE A PROBLEM THAT COULD CAUSE MAJOR DELAYS.
<P>
THE ISSUE. WHERE TO DUMP THE TONS OF EARTH BEING EXCAVATED TO REPAIR THE ROADWAY.
<P>
HAULING IT OUT OF THE AREA COULD DELAY THE PROJECT BY MONTHS.     
<P>
THE COASTAL COMMISSION HAS OFFERED CALTRANS AN EMERGENCY PERMIT TO DUMP THE DEBRIS INTO THE OCEAN. BUT THERE'S A CATCH.
<P>
CALTRANS WOULD HAVE TO FILE FOR A REGULAR PERMIT. AND THAT COULD LEAD TO LONG TERM REPAIR PROJECTS THE AGENCY IS UNWILLING TO TAKE ON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Pinnacles Reopen>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pinnacles Reopen</H3><BR>
MEANWHILE. ANOTHER CASUALTY OF THE WINTER STORMS IS SET TO PARTIALLY RE-OPEN THIS WEEKEND.
<P>
STARTING SATURDAY. VISITORS WILL BE ALLOWED ACCESS TO THE EAST SIDE OF PINNACLES NATIONAL MONUMENT, IN SAN BENITO COUNTY.
<P>
HEAVY RAINS AND FLOODS IN FEBRUARY WASHED OUT ACCESS ROADS AND DAMAGED TRAILS.
<P>
THE WEST ENTRANCE WILL REMAIN CLOSED FOR ANOTHER SEVERAL WEEKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Pogonip Meeting>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pogonip Meeting</H3><BR>
JUST ABOUT NOW. SANTA CRUZ RESIDENTS AND THE CITY COUNCIL ARE WRAPPING UP A HEATED PUBLIC DEBATE ABOUT THE CONTROVERISAL "POGONIP" AREA.
<P>
THE SANTA CRUZ CITY COUNCIL TONIGHT PRESENTED A DRAFT ENVIRONMENTAL IMPACT REPORT AND A MASTER PLAN FOR THEIR PROPOSED USE OF THE POGONIP.
<P>
POGONIP IS A 640-ACRE STRETCH OF LAND NEAR U.C. SANTA CRUZ THAT HOUSES AN HISTORIC CLUBHOUSE AND A REC TRAIL FOR PEDESTRIANS.
<P>
THE CITY WANTS TO TURN THE CLUBHOUSE INTO A COMMUNITY FACILITY. ADD EQUESTRIAN AND BIKE ACCESS TO THE REC TRAIL. AND BUILD A SITE FOR THE HOMELESS GARDEN PROJECT.
<P>
THE PUBLIC GOT TO VOICE THEIR OPINIONS ON THE PROJECT TONIGHT.
<P>
THE CITY COUNCIL PLANS TO MAKE A FINAL DECISION ON THE FUTURE OF THE LAND. BY JUNE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Smoking in Line>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Smoking in Line</H3><BR>
SMOKING IS ALREADY BANNED INSIDE SANTA CRUZ BUILDINGS.  NOW THAT CITY'S MAYOR SAYS THAT'S NOT ENOUGH.
<P>
CELIA SCOTT IS PROPOSING A BAN ON SMOKING WHILE WAITING IN OUTSIDE LINES. SUCH AS AT A MOVIE THEATER.
<P>
HERE'S WHAT SOME RESIDENT'S THING OF THE IDEA.
<P>
"SINCE WE KNOW.OUTQ.STRONGLY ABOUT IT."
<P>
I THINK YOU.OUTQ.SHOULDN'T BE A LAW."
<P>
CITY COUNCIL MEMBERS WILL VOTE ON THE PROPOSAL NEXT MONTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Firefighter Rules>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Firefighter Rules</H3><BR>
TWO IN - TWO OUT. IT'S A NEW RULE FROM OSHA. DESIGNED TO MAKE FIRE FIGHTING SAFER. 
<P>
WHAT IT MEANS IS THAT WHEN THERE ARE ONLY TWO FIRE FIGHTERS ARRIVING ON A SCENE. THEY MUST WAIT UNTIL AT LEAST TWO MORE FIRE FIGHTERS ARRIVE BEFORE THEY ENTER THE BUILDING.
<P>
FIRE FIGHTER'S AND LOCAL UNIONS ARE PRAISING THE POLICY SAYING IT'S DESIGNED FOR THE SAFETY OF THE PEOPLE FIGHTING FIRES.
<P>
BUT FIRE OFFICIALS RECOGNIZE IT COULD CAUSE SOME QUESTIONS.
<P>
"WHAT MOST PEOPLE WILL SEE IS FIRE FIGHTERS SHOWING UP TO A FIRE AND DOING WHAT APPEARS TO BE NOTHING WAITING FOR 
<P>
SUPPORT TO SHOW UP SO THEY CAN SAFELY ENTER A BUILDING"
<P>
WHEN PEOPLE ARE TRAPPED INSIDE A BURNING BUILDING THE NEW TWO IN - TWO OUT POLICY DOES NOT APPLY.
<P>
THE NEW FEDERAL POLICY STARTS IN APRIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Dispatch Center Sup>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dispatch Center Sup</H3><BR>
MONTEREY COUNTY IS TAKING STEPS TO MAKE LIFE EASIER FOR 9-1-1 EMERGENCY DISPATCHERS.
<P>
THIS MORNING, THE BOARD OF SUPERVISORS APPROVED PRELIMINARY STEPS TO DEVELOP A NEWER, BIGGER BUILDING TO HOUSE EMERGENCY STAFF.
<P>
THE 13-THOUSAND SQUARE FOOT FACILITY IS ESTIMATED TO COST ABOUT FIVE AND A HALF MILLION DOLLARS.
<P>
IT'LL HOUSE THE DISPATCHERS AND THE OFFICE OF EMERGENCY SERVICES.
<P>
EMPLOYEES SAY THE IMPROVEMENTS ARE LONG OVERDUE.
<P>
"SO THEY CAN HEAR."
<P>
CURRENTLY. THE O-E-S IS HOUSED IN THE BASEMENT OF THE COUNTY COURTHOUSE.
<P>
THE NEW PROPOSED SITE IS NEXT TO THE SALINAS AIRPORT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145Seaside ATM Rob>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Seaside ATM Rob</H3><BR>
POLICE IN SEASIDE TONIGHT ARE ON THE LOOKOUT FOR A PAIR OF A-T-M ROBBERS.
<P>
DETECTIVE SAY TWO MASKED MEN HELD UP AN ATM CUSTOMER IN BROAD DAYLIGHT THIS MONRING. OUTSIDE THE BANK OF AMERICA ON FREMONT.
<P>
THE VICTIM SAYS THE ROBBERS STOLE ABOUT 43-HUNDRED DOLLARS FROM HIM.
<P>
BOTH ROBBERS WERE LAST SEEN LEAVING THE AREA IN A GREEN 96 NISSAN COUPE.
<P>
AUTHORITIES ARE ASKING ANY WITNESSES. TO CALL THE SEASIDE POLICE DEPARTMENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Watsonville Ozone>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Watsonville Ozone</H3><BR>
A CALIFORNIA SCIENTIST THINKS HE MAY HAVE THE ANSWER TO THE CONTROVERSIAL USE OF THE PESTICIDE METHYL BROMIDE.
<P>
ALAN PRYOR. WHO GROWS ORGANIC FRUIT IN THE SAN JOAQUIN VALLEY. SAYS HE'S FOUND AN ALTERNATIVE IN SOMETHING CALLED. *OZONE!*
<P>
HE SAYS HE'S BEEN USING OZONE AS A PESTICIDE FOR SIX YEARS. AND IS CURRENTLY TESTING HIS METHODS. IN A WATSONVILLE FIELD.
<P>
PRYOR CLAIMS IT'S JUST AS EFFECTIVE AS METHYL BROMIDE IN KILLING BUGS. EXCEPT *WITHOUT* THE DANGEROUS HEALTH HAZARDS.
<P>
"EVEN IF WE SHOULD HAVE EMISSIONS BREAK DOWN VERY RAPID. INTO SIMPLE OXYGEN. CONSIDERED LESS TOXIC THAN OTHER ALTERNATIVE CHEMICALS THEY WILL USE OR ARE USING NOW."
<P>
METHYL BROMIDE IS KNOWN TO CAUSE HEALTH PROBLEMS IN HUMANS AND DEPLETE THE OZONE.
<P>
THE U.S. GOVERNMENT HAS BANNED THE CHEMICAL. AND IT'S SCHEDULED TO BE COMPLETELY PHASED OUT BY THE YEAR 2001.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142UCSC El Nino Grant>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>UCSC El Nino Grant</H3><BR>
TWO TEAMS OF RESEARCHERS FROM U.C. SANTA CRUZ RECEIVE A GRANT TO STUDY THE EFFECTS OF EL NINO.
<P>
THE GRANT. TOTALLING 142-THOUSAND DOLLARS. COMES FROM THE NATIONAL OCEANIC AND ATMOSPHERIC ADMINISTRATION.
<P>
ONE OF THE TEAMS WILL LOOK  INTO HOW EL NINO WEATHER PATTERNS CHANGE THE REPRODUCTIVE BEHAVIOR OF NORTHERN CALIFORNIA'S ELEPHANT SEALS.
<P>
THE OTHER TEAM WILL INVESTIGATE EL NINO'S IMPACTS ON WHAT'S CALLED 'TROPHIC LINKS" BETWEEN THE LEVELS OF THE FOOD CHAIN IN THE MONTEREY BAY.
<P>
NOAA PLANS TO AWARD ADDITIONAL GRANTS TO FURTHER THE STUDY OF THE WEATHER PHENOMENON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143UC Minorities>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>UC Minorities</H3><BR>
MEANWHILE. UNIVERSITY OF CALIFORNIA OFFICIALS ANNOUNCE TODAY A DRAMATIC DECREASE IN THE NUMBER OF MINORITY STUDENTS BEING ADMITTED TO U-C SCHOOLS.
<P>
AT U.C. BERKELEY. THE NUMBER OF BLACK, HISPANIC AND AMERICAN INDIAN STUDENTS ADMITTED THIS FALL DROPPED BY 55-PERCENT.
<P>
AT U.C.L.A. IT'S DOWN BY ABOUT 36-PERCENT.
<P>
THE SHARP DECREASE IS BEING BLAMED ON THE DISMANTLING OF AFFIRMATIVE ACTION POLICIES.
<P>
THE BAN ON AFFIRMATIVE ACTION BEGAN TAKING EFFECT THIS SCHOOL YEAR.
<P>
U.C. BERKELEY'S CHANCELLOR HAS VOWED TO WAGE A CAMPAIGN TO REVERSE THOSE NUMBERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/Mo.D.A.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/Mo.D.A.</H3><BR>
SOME GOOD NEWS ABOUT THE MONTEREY COUNTY AGENCY RESPONSIBLE FOR COLLECTING CHILD SUPPORT.
<P>
THE MONTEREY COUNTY "FAMILY SUPPORT DIVISION" RANKED NUMBER ONE IN THE STATE. FOR LOCATING MORE ABSENTEE PARENTS THAN ANY OTHER MID-SIZED COUNTY IN CALIFORNIA.
<P>
THE DIVISION ALSO RANKED SECOND IN THE STATE FOR THE "MOST IMPROVED CHILD SUPPORT PROGRAM."
<P>
SINCE IT BEGAN. THE DEPARTMENT HAS INCREASED ITS CHILD SUPPORT PAYMENTS MORE THAN THREE-FOLD.
<P>
"WHEN WE FIRST STARTED THIS.WE'RE GETTING."
<P>
THE FAMILY SUPPORT DIVISION WAS HONORED BY STATE AND COUNTY OFFICIALS DURING A BOARD OF SUPERVISORS MEETING THIS MORNING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
THE PRESIDENT AND OTHER WASHINGTON LEADERS JOIN RESIDENTS OF JONESBORO, ARKANSAS ONE-WEEK AFTER THE TRAGIC MIDDLE-SCHOOL SHOOTING.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Jonesboro Memorial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jonesboro Memorial</H3><BR>
THE GRIEVING TOWN PAID HOMAGE TO THE FOUR STUDENTS AND TEACHER WHO DIED IN THE SHOOTING AMBUSH ONE WEEK AGO TODAY.
<P>
FIRST THERE WAS A MOMENT OF SILENCE DURING THE DAY.THEN TONIGHT. A MEMORIAL.
<P>
THE PRESIDENT SENT A TAPED MESSAGE OF CONDOLENCE. AND ATTORNEY GENERAL JANET RENO SPOKE AT THE MEMORIAL.
<P>
MEANWHILE. IT WAS REVEALED TODAY. ONE OF THE SUSPECTS IN THE SHOOTING, 13-YEAR OLD MITCHELL JOHNSON. IS REPORTEDLY IN TROUBLE IN MINNESOTA WHERE, ON A VISIT LAST SUMMER, HE ALLEGEDLY MOLESTED A TODDLER-AGED LITTLE GIRL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Clinton/Miss America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Miss America</H3><BR>
ANOTHER WOMAN HAS COME FORWARD WITH ALLEGATIONS THAT SHE HAD SEX WITH PRESIDENT CLINTON.
<P>
FORMER MISS AMERICA AND PLAYBOY MODEL ELIZABETH WARD GRACEN TELLS THE NEW YORK DAILY NEWS THAT SHE HAD CONSENSUAL SEX WITH CLINTON BACK IN 1983, WHEN HE WAS GOVERNOR OF ARKANSAS.
<P>
THOUGH SHE'S CONSISTENTLY DENIED ANY RELATIONSHIP WITH CLINTON. GRACEN SAYS SHE'S COMING FORWARD NOW TO *PROTECT* THE PRESIDENT FROM ACCUSATIONS THAT HE FORCED HIMSELF ON HER.
<P>
GRACEN'S TESTIMONY IS BEING SOUGHT IN THE PAULA JONES LAWSUIT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118Whale Rescue>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Whale Rescue</H3><BR>
