<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 3/14/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 3/14/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#7Crazy Horse Body>Crazy Horse Body</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#24Beer Drinkers>Beer Drinkers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Boat Aground>Boat Aground</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23St. Pat'S Day>St. Pat'S Day</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127SC Near-Drowning>SC Near-Drowning</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121Albany Floods>Albany Floods</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#8El Charrito Folo>El Charrito Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38Prep Basketball >Prep Basketball </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#12Stillwell Dedication>Stillwell Dedication</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Habitat/Humanity>Habitat/Humanity</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Carolina>Carolina</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Salmon Fishing>Salmon Fishing</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Arizona>Arizona</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Aquarium Exhibit>Aquarium Exhibit</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Cincy>Cincy</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Titanic Craze-I>Titanic Craze-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117Titanic Craze-G>Titanic Craze-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#99Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118Titanic Craze-T>Titanic Craze-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Giants/A's>Giants/A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#18Letourneau Pregnant>Letourneau Pregnant</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123Soccer>Soccer</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Clinton Deposition-I>Clinton Deposition-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106Miss CA/Miss SC>Miss CA/Miss SC</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#124Clinton Deposition-G>Clinton Deposition-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Engagement>Engagement</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Factory Fire>Factory Fire</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=7Crazy Horse Body>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Crazy Horse Body</H3><BR>
GOOD EVENING. I'M CHERI GYURO. THANKS FOR JOINING US.
<P>
CALIFORNIA HIGHWAY PATROL OFFICERS NEED YOUR HELP TONIGHT FINDING THE DRIVER WHO APARENTLY STRUCK AND KILLED A PEDESTRIAN IN PRUNEDALE.
<P>
AROUND 3:30 THIS MORNING A PASSING MOTORIST FOUND THE BODY OF 37-YEAR-OLD SUSAN PEREZ LYING ON CRAZY HORSE CANYON ROAD IN PRUNEDALE.
<P>
INVESTIGATORS SAY THE SEASIDE RESIDENT WAS THE VICTIM OF A HIT AND RUN.
<P>
THE MONTEREY COUNTY CORONER SAYS THE CAUSE OF DEATH WAS MULTIPLE BLUNT FORCE TRAUMA.
<P>
ANYONE WITH INFORMATION IS ASKED TO CALL THE CALIFORNIA HIGHWAY PATROL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Boat Aground>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Boat Aground</H3><BR>
AN UNUSUAL SITE ON THE MONTEREY BAY SHORE TODAY.
<P>
A 40-FOOT SAILBOAT RAN AGROUND LATE LAST NIGHT. AFTER BREAKING LOOSE FROM ITS ANCHOR IN THE MARINA.JUST OFF FISHERMAN'S WHARF.
<P>
ACCORDING TO THE U-S COAST GUARD. THE OWNER OF THE VESSEL. WHO LIVES ON-BOARD. IS OUT OF TOWN.
<P>
LUCKILY, THERE WERE NO INJURIES AND NO OTHER BOATS WERE DAMAGED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127SC Near-Drowning>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Near-Drowning</H3><BR>
A NEAR TRAGEDY AT PLEASURE POINT BEACH IN SANTA CRUZ TONIGHT.
<P>
A 10-YEAR-OLD BOY WAS PLAYING IN THE SAND WITH SOME FRIENDS THIS EVENING.
<P>
PARAMEDICS SAY. SOON AFTER HE BURIED HIMSELF IN THE SAND. HIS FRIENDS STARTED YELLING FOR HELP.
<P>
SOME SURFERS HEARD THE CRIES. PULLED THE BOY FROM THE SAND. AND CALLED 911.
<P>
THE UNIDENTIFIED BOY WAS TRANSPORTED TO DOMINICAN HOSPITAL. WHERE HE'S BEING TREATED FOR HYPOTHERMIA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=8El Charrito Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>El Charrito Folo</H3><BR>
THE MOTHER OF AN 18-YEAR-OLD SALINAS MAN SHOT AND KILLED TWO DAYS AGO. IS SPEAKING OUT.
<P>
EVENGELINA GARCIA IS ASKING ANYONE WITH INFORMATION ABOUT THE DEATH OF HER SON TO COME FORWARD.
<P>
JOSE GARCIA WAS SHOT THURSDAY WHILE HE WAS LEAVING THE PARKING LOT OF A SHOPPING CENTER IN EAST SALINAS.
<P>
SALINAS POLICE SAY THEY DON'T HAVE ANY SUSPECTS.
<P>
AUTHORITIES ARE ALSO LOOKING FOR THE MAN WHO SHOT 29-YEAR OLD GILBERTO FERNANDEZ YESTERDAY IN FRONT OF EL CHARRITO MARKET.
<P>
HE IS IN SERIOUS CONDITION AT NATIVIDAD MEDICAL CENTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=12Stillwell Dedication>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stillwell Dedication</H3><BR>
A BUILDING AT THE FORMER FORT ORD HAS BEEN RE-NAMED IN HONOR OF A WORLD WAR TWO LEADER.
<P>
DOZENS OF PEOPLE ATTENDED THE DEDICATION OF THE *GENERAL STILLWELL COMMUNITY CENTER* THIS AFTERNOON ON GIGLING ROAD.
<P>
THE CENTER HONORS THE MEMORY OF GENERAL JOSEPH STILLWELL WHO COMMANDED THE 7TH INFANTRY DIVISION AND FORT ORD IN THE 19-40'S.
<P>
HE LATER COMMANDED THE PRESIDIO OF MONTEREY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Habitat/Humanity>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Habitat/Humanity</H3><BR>
IN WATSONVILLE."HABITAT FOR HUMANITY" DEDICATES THREE NEW HOMES TO LOW-INCOME FAMILIES.
<P>
OWNERS AND VOLUNTEERS HAVE WORKED ALMOST THREE YEARS TO BUILD THE HOUSES.
<P>
THE FAMILIES SPENT MORE THAN FIVE-HUNDRED HOURS HELPING TO BUILD THEIR OWN HOMES AND WILL PAY FOR THEM ON A NO-INTEREST MORTGAGE FOR THE NEXT 25-YEARS.
<P>
HABITAT HAS NOW BUILT 16-HOUSES SINCE 19-86.
<P>
THE ORGANIZATION'S NEXT PROJECT WILL BE IN CAPITOLA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=112Salmon Fishing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salmon Fishing</H3><BR>
SPORT FISHING SEASON FOR SALMON IS OFFICIALLY UNDERWAY.
<P>
AND LOCAL FISHERMEN DIDN'T WASTE ANY TIME.
<P>
FISH-AND-GAME AUTHORITIES WERE AT THE MONTEREY HARBOR. KEEPING TABS ON THE NUMBER OF FISH CAUGHT AND THE NUMBER OF PEOPLE OUT FISHING.
<P>
THEY SAY RECENT STORMS HAVE KEPT MANY FISHERMEN AWAY. 
<P>
IC: 3:31 LAST YEAR GOOD WEATHER.THIS YEAR MORE WINDY AND GROUND SWELLS SO PEOPLE ARE MORE INCLINED TO NOT GO OUT RANGE AS FAR AS THEY NORMALLY WOULD
<P>
FISH AND GAME ALSO SAYS PEOPLE FISHING NEED TO KNOW THE REGULATIONS.
<P>
THERE ARE CHANGES COMING SOON.
<P>
MANY RECREATIONAL BOATS USED FOR FISHING NEED TO BE INSPECTED.
<P>
BOATERS CAN CALL THE COAST GUARD AUXILIARY AT 372-3008 TO SCHEDULE A FREE VESSEL EXAMINTION.
<P>
EXAMS FOR COMMERCIAL FISHING VESSELS ARE ALSO AVAILABLE. CALL 647-7366.
<P>
THERE IS A LIMITED NUMBER OF EXAMINERS.SO IT MIGHT BE A GOOD IDEA TO CALL EARLY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Aquarium Exhibit>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Aquarium Exhibit</H3><BR>
EVER WONDER WHAT IT TAKES TO KEEP ALL THOSE ANIMALS ALIVE AT THE MONTEREY BAY AQUARIUM?
<P>
WE'LL THE SECRET IS OUT!
<P>
THE AQUARIUM OPENED ITS NEW EXHIBIT CALLED, "INSIDE STORY" TODAY.
<P>
VISITORS CAN WALK BEHIND THE SCENES TO GET AN IDEA OF WHAT IT TAKES TO MAINTAIN MORE THAN 3-THOUSAND MARINE PLANTS AND ANIMALS.
<P>
"THEY'VE WORKED SO HARD AT STUFF, IT SEEMS LIKE THEY'VE DONE SO MANY THINGS TO MAKE THIS A GREAT PLACE TO BE OUT"
<P>
IT'S A REALLY COMPLICATED JOB AND I THINK PEOPLE ARE FASCINATED WITH WHAT GOES ON BEHIND THOSE CLOSED DOORS.AND THEY'RE REALLY FUN STORIES WITH ALL THE DIFFERENT NUTRITIONAL NEEDS OF THE ANIMALS AND THE DIFFERENT WAYS THEY EAT."
<P>
THE "INSIDE STORY" EXHIBIT IS OPEN UNTIL JANUARY IN THE YEAR 2-THOUSAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Titanic Craze-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Titanic Craze-I</H3><BR>
AND THE ANSWER TO THAT IS. JUST LIKE EVERYBODY ELSE.
<P>
IT'S BEEN MORE THAN THREE MONTHS SINCE THE MOVIE FIRST CAME OUT. BUT WHEN WE CHECKED THE LINES AT LOCAL THEATERS TONIGHT. IT WAS STILL OUT THE DOOR.
<P>
WE ASKED MOVIE-GOERS WHY THEY KEEP COMING BACK TO SEE THE MOVIE. AND THE MOST POPULAR ANSWERS WE GOT WERE. THE SPECIAL EFFECTS. AND LEONARDO DICAPRIO.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117Titanic Craze-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Titanic Craze-G</H3><BR>
THOSE WORDS ARE REPEATED LIKE A BROKEN RECORD AT THEATERS ALL ACROSS THE COUNTRY. IF NOT THE WORLD.
<P>
IN FACT, THEATER EMPLOYEES PRACTICALLY SLEEP, EAT AND BREATH "TITANIC."
<P>
BUT NO ONE'S COMPLAINING.
<P>
. "NOW CLOSE YOUR EYES.  GO ON." 
<P>
TO SAY IT "DID WELL" WOULD BE AN UNDERSTATEMENT.  UNLIKE THE REAL THING. THE MOVIE IS LITERALLY UNSINKABLE.
<P>
TODAY, IT SAILED PAST STAR WARS TO BECOME THE NUMBER ONE DOMESTIC GROSSING MOVIE OF ALL TIME.
<P>
AND. WHILE STAR WARS TOOK TWENTY YEARS AND FIVE RE-RELEASES TO MAKE ITS 461 MILLION DOLLARS. "TITANIC" TOOK JUST 12 WEEKS TO MAKE 465 MILLION.
<P>
IF IT'S NOT THE MOVIE OR THE SONG. IT'S BOOKS.
<P>
AT LOCAL BOOK STORES. ANYTHING TITANIC SELLS LIKE HOTCAKES. AND IT'S ALL EMPLOYEES CAN DO TO KEEP THEIR SHELVES STOCKED.
<P>
AND IF FANS' REACTIONS ARE ANY INDICATION. YOU CAN BET ANY OTHER MOVIES FEATURING STAR LEONARDO DICAPRIO WILL RIDE THE TITANIC SUCCESS WAVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118Titanic Craze-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Titanic Craze-T</H3><BR>
THOUGH TITANIC NOW HOLDS THE NUMBER ONE SPOT. IF YOU ACTUALLY TAKE THE MOVIE "GONE WITH THE WIND" AND CALCULATE ITS EARNINGS USING TODAY'S TICKET PRICES. *IT* WOULD HOLD THE NUMBER ONE SPOT WITH 1.3 BILLION DOLLARS IN DOMESTIC GROSSES.
<P>
AND IF YOU DO THAT WITH STAR WARS, IT WOULD HAVE MADE 812-MILLION DOLLARS IN TODAY'S PRICES.
<P>
BUT EVEN WITH ALL THAT. GONE WITH THE WIND WAS RELEASED IN 19-39 AND STAR WARS CAME OUT IN 19-77.
<P>
TITANIC, HOWEVER, HAS BEEN CRUISING ALONG FOR ONLY THREE MONTHS.
<P>
CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=18Letourneau Pregnant>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Letourneau Pregnant</H3><BR>
IN WASHINGTON STATE.THE FORMER TEACHER CONVICTED OF RAPING.THEN HAVING THE CHILD OF A FOURTEEN YEAR-OLD BOY.MAY BE PREGNANT AGAIN.
<P>
A SEATTLE NEWSPAPER IS REPORTING THE SAME BOY WILL BE THE FATHER. 
<P>
MARY KAY LETOURNEAU IS SERVING A 7 1/2 YEAR SENTENCE FOR HER SEXUAL RELATIONSHIP WITH THE BOY THAT PRODUCED A DAUGHTER LAST YEAR. 
<P>
AFTER RECEIVING A SUSPENDED SENTENCE.  SHE WAS FORCED TO RETURN TO PRISON A MONTH LATER AFTER SHE AND THE BOY WERE FOUND TOGETHER AGAIN. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Clinton Deposition-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton Deposition-I</H3><BR>
NOW THAT THE ONCE-SECRET DOCUMENTS AND DEPOSITIONS IN THE PAULA JONES CASE AGAINST THE PRESIDENT ARE PUBLIC.THE CASE HAS BECOME 
<P>
MORE THAN JUST "HE SAID.SHE SAID."   
<P>
FOX'S JULIE KIRTZ TELLS US ABOUT THE NEWLY-RELEASED, SWORN STATEMENTS OF "OTHER" WOMEN WHO CLAIMS SHE WAS HARASSED BY THE PRESIDENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=124Clinton Deposition-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton Deposition-G</H3><BR>
MONICA LEWINSKY AND ALLEGATIONS OF AN AFFAIR WITH THE PRESIDENT HAVE 
<P>
MADE HEADLINES FOR MONTHS. 
<P>
AND PAULA JONES IS FAMOUS FOR ACCUSING THEN GOVERNOR BILL CLINTON OF 
<P>
CRUDELY PROPOSITIONING HER IN A LITTLE ROCK HOTEL. HE DENIES IT, 
<P>
BUT THE MASSIVE 700-PAGE FILING BY THE JONES LEGAL TEAM FRIDAY. 
<P>
DETAILS THE TESTIMONY OF OTHER LESSER KNOWN WOMEN WITH FIRST HAND 
<P>
STORIES TO TELL ABOUT SEX AND MR CLINTON. 
<P>
THERE IS DOLLY KYLE BROWNING.A HIGH SCHOOL FRIEND.WHO REFERS TO 
<P>
CLINTON'S SEXUAL ADDICTION. IN HER DEPOSITION SHE SAYS. 
<P>
GRAPHIC-------------------------------------------- 
<P>
"DURING THE  PERIOD FROM THE MID-1970S UNTIL JANUARY 1992, WE HAD A 
<P>
RELATIONSHIP THAT INCLUDED SEXUAL RELATIONS." 
<P>
--------------------------------------------------- 
<P>
AND THERE IS KATHLEEN WILLEY.A FORMER WHITE HOUSE VOLUNTEER WHO 
<P>
TESTIFIED BEFORE THE WHITEWATER GRAND JURY AND WAS A RELUCTANT 
<P>
WITNESS FOR THE JONES CAMP. SHE SAYS WHEN SHE WENT  TO THE PRESIDENT 
<P>
FOR A PAID JOB HE KISSED HER AND  QUOTE 
<P>
GRAPHIC ---------------------------------------------: 
<P>
".PUT MY HANDS ON HIS GENITALS."."IT WAS VERY UNEXPECTED.I JUST 
<P>
RESISTED." 
<P>
-------------------------------------------------- 
<P>
THE PRESIDENT HAD NO COMMENT AS HE LEFT FOR A WEEKEND AT CAMP DAVID 
<P>
WITH THE FIRST LADY. 
<P>
BUT IN HIS JANUARY 17TH DEPOSITION IN THE JONES CASE. HE ADMITS TO 
<P>
HAVING SEX ONCE WITH JENNIFER FLOWERS.  ON THE ENCOUNTER WITH 
<P>
KATHLEEN WILLEY.HE SAID. 
<P>
GRAPHIC------------------------------------------------- 
<P>
"I EMBRACED HER. I PUT MY ARMS AROUND HER. I MAY HAVE EVEN KISSED HER 
<P>
FOREHEAD. THERE WAS NOTHING SEXUAL ABOUT IT." 
<P>
----------------------------------------- 
<P>
CHYRON: JULIE KIRTZ -STANDUP 
<P>
PRESIDENT CLINTON'S ATTORNEY SAYS HE'S OUTRAGED BY THE RELEASE OF THE 
<P>
DOCUMENTS. BUT THERE'S MORE TO COME.   KATHLEEN WILLEY TELLS HER 
<P>
STORY PUBLICLY FOR THE FIRST TIME SUNDAY NIGHT ON "60 MINUTES".   SIX 
<P>
YEARS AFTER CANDIDATE BILL CLINTON USED THE SAME SHOW TO CONFRONT 
<P>
ALLEGATIONS OF AN AFFAIR WITH JENNIFER FLOWERS,. AT THE WHITE HOUSE 
<P>
JULIE KIRTZ.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Factory Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Factory Fire</H3><BR>
BILLOWS OF BLACK SMOKE AND FLAMES REACHED FOR MILES FROM A FIRE AT AN INDIANA FACTORY.
<P>
THE BLAZE BROKE OUT AT A PLASTICS FACTORY IN ELKHART.
<P>
MORE THAN 100 FIREFIGHTERS FROM DIFFERENT DEPARTMENTS HELPED CONTAIN THE BLAZE. 
<P>
NO ONE WAS INJURED. 
<P>
FIREFIGHTERS SAY THEY THINK THE FIRE STARTED IN A WOMEN'S RESTROOM IN THE FACTORY'S MAIN BUILDING.
<P>
DAMAGE IS ESTIMATED AT  FIVE-MILLION DOLLARS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=24Beer Drinkers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Beer Drinkers</H3><BR>
COULD BEER HOLD THE SECRET FOR PROTECTING YOURSELF AGAINST CANCER? 
<P>
RESEARCHERS AT OREGON STATE UNIVERSITY SAY IT'S POSSIBLE.
<P>
THEIR STUDIES FIND A SUBSTANCE IN HOPS CALLED "FLAV-O-NOIDS" HELP INHIBIT AN ENZYME THAT CAN ACTIVATE THE CANCER PROCESS. 
<P>
BUT BEFORE YOU REACH FOR A  SIX-PACK. RESEARCHERS WARN AGAINST DRINKING MORE BEER. 
<P>
THEY SAY HE SUBSTANCE MAY EVENTUALLY BE AVAILABLE IN OTHER FORMS. SUCH AS A PILL. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23St. Pat'S Day>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>St. Pat'S Day</H3><BR>
IRISH EYES WERE SMILIN' TODAY.JUST A WEE BIT EARLY. 
<P>
FOLKS ACROSS THE COUNTRY JUST COULDN'T WAIT TO CELEBRATE SAINT PATRICK'S DAY. 
<P>
GREEN FACES AND GREEN BEER FILLED THE STREETS OF NORFOLK, VIRGINIA DURING A PARADE TODAY. 
<P>
IN CHICAGO.THE WATER TURNED GREEN AS SPECTATORS LOOKED ON.ALTHOUGH A LITTLE DUCKY APPEARED TO BE CONFUSED BY THE WHOLE THING. 
<P>
EVERYONE WILL BE IRISH ON TUESDAY.WHEN THE PATRON SAINT OF IRELAND WILL HAVE HIS DAY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121Albany Floods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Albany Floods</H3><BR>
THE FLOODWATERS ARE FINALLY FALLING IN  GEORGIA. 
<P>
THE FLINT RIVER IS STARTING TO RECEDE.
<P>
AREA RESIDENTS ARE STARTING TO GET THEIR LIVES BACK TOGETHER. 
<P>
MORE THAN 11-THOUSAND PEOPLE WERE FORCED TO SEARCH FOR HIGHER GROUND THIS WEEK. AS HUNDREDS OF HOMES WERE DAMAGED BY THE FLOODS. 
<P>
TEN COUNTIES IN GEORGIA HAVE BEEN DECLARED FEDERAL DISASTER AREAS.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38Prep Basketball >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Basketball </H3><BR>
IT STARTED WITH A DREAM AND 20-CONSECUTIVE VICTORIES LATER. THE PACIFIC GROVE BREAKERS FIND THEMSELVES IN THE NOR-CAL CHAMPIONSHIP GAME.
<P>
ALONG THE WAY. THE BREAKERS PILED UP A PERFECT MISSION TRAIL RECORD. A DIVISION FOUR C-C-S TITLE. AND NOW THEY HAVE A CHANCE TO KEEP THEIR HOOP DREAMS ALIVE.
<P>
TODAY IN STOCKTON.THE BREAKERS BEAT MODESTO CHRISTIAN IN THE NOR CAL DIVISION FOUR CHAMPIONSHIP GAME.
<P>
THIS ONE A THRILLER.  GETTING THE TIP IN WITH 6-SECONDS TO PLAY AS P-G WINS 55-54. 
<P>
LEADING THE WAY  WITH 18 POINTS. LAZARRI SCORES 16. THE WIN PROPELS THE BREAKERS INTO THE STATE FINAL. WHICH WILL TAKE PLACE NEXT SATURDAY AT ARCO ARENA IN SACRAMENTO.
<P>
PACIFIC GROVE WILL PLAY  OF SOUTHERN CALIFORNIA. GAME TIME IS 4:15.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
TO THE N-C DOUBLE-A TOURNEY NOW. THE PAC TEN ALREADY SHOWING THE STRENGTH OF THE CONFERENCE BY GOING 4-O IN THE FIRST ROUND.
<P>
THE STANFORD CARDINAL ONE OF THOSE FIRST ROUND WINNERS. TOMORROW THE CARDINAL WILL LOOK TO ADVANCE TO THE SWEET 16 FOR THE 2ND STRAIGHT YEAR AS THEY TAKE ON WESTERN MICHIGAN.
<P>
SPEAKING OF THE PAC TEN. THE WASHINGTON HUSKIES TAKING ON THE RICHMOND SPIDERS. THE HUSKIES THE UNDERDOGS IN THE 1ST ROUND. THINGS CHANGE ROUND TWO.
<P>
---------
<P>
END OF THE 1ST HALF.  CANS THE TRIPLE. ONE OF FIVE IN THE GAME FOR LUTON. HUSKIES BY 7 AT THE BREAK.
<P>
--------
<P>
2ND HALF. THE BIGGEST DOG TAKES OVER. 7-FOOT CENTER  RULING THE PAINT.
<P>
HE WOULD SCORE 17 POINTS IN THE FIRST 10-MINUTES OF THE 2ND HALF TO HELP WASHINGTON PUSH THE LEAD TO 16.
<P>
---------
<P>
MACCULLOUGH  POURS IN 31 POINTS AND PULLS DOWN 18 REBOUNDS AS THE WASHINGTON HUSKIES MAKE IT TWO IN A ROW. WASHINGTON WINS 81-66. THE HUSKIES ARE OFF TO THE SWEET 16 FOR THE 1ST TIME SINCE 1984.     
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Carolina>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Carolina</H3><BR>
THE TOP SEEDED NORTH CAROLINA TAR HEELS GOT A SCARE TODAY. TAKING ON UNC CHARLOTTE.
<P>
THE HEELS LEAD BY THREE WITH TIME WINDING DOWN. WHEN CHARLOTTE'S  THROWS UP A PRAYER FROM BEYOND THE ARC. AND IT GOES. IT WOULD TIE THE GAME AT 74. THIS GAME GOING TO OVERTIME.
<P>
-------
<P>
THE HEELS GETTING ALL THEY CAN HANDLE IN THE REGULATION. THEY TAKE OVER IN THE O-T. OUT SCORING THE 49ERS. 19-9.  WITH 32 TO LEAD NORTH CAROLINA.
<P>
------
<P>
WILL PUT THE EXCLIMATION POINT ON THIS ONE.
<P>
NORTH CAROLINA ESCAPES WITH THE VICTORY.
<P>
FINAL. 93-83.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Arizona>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Arizona</H3><BR>
OVER IN THE WEST REGION. ANOTHER PAC TEN TEAM CONTINUES TO PLAY WELL.
<P>
THE DEFENDING CHAMPION ARIZONA WILDCATS ADVANCING TO THE SWEET 16 ALONG WITH THE HUSKIES.
<P>
ARIZONA TAKING ON ILLINOIS STATE. THE LEAD IS JUST THREE AT THE HALF.
<P>
--------
<P>
BUT THE CATS TURN IT UP IN THE 2ND HALF.  WITH THE BOMB FROM THE CORNER. ARIZONA WOULD REEL OFF 15 STRAIGHT.
<P>
--------
<P>
SCORING FROM BOTH THE OUTSIDE AND INSIDE.  WITH THE BUCKET. CATS BY 19.
<P>
--------
<P>
THE REDBIRDS WOULD NEVER GET CLOSER THAN 18 FROM THEN ON OUT.
<P>
--------
<P>
AND  PACE THE CATS WITH 19-POINTS APIECE. BIBBY WITH THE JAM. AS ARIZONA WINS. 82-49. 
<P>
THE CATS AVERAGE MARGIN OF VICTORY AFTER TWO GAMES IS 36 POINTS. THEY'RE OFF TO THE SWEET 16 FOR THE 7TH TIME IN 11 YEARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Cincy>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cincy</H3><BR>
ANOTHER SEED PLANTED TODAY IN THE WEST. NUMBER TWO CINCINATTI TAKING ON THE 10TH SEED. WEST VIRGINIA. AND THIS ONE WOULD BE A BATTLE TO THE FINISH.
<P>
--------
<P>
WEST VIRGINIA UP ONE WITH TIME RUNNING OUT.  LAUNCES ONE FROM WAY DOWNTOWN AND HE CONNECTS. CINCY WITH A 2-POINT LEAD. JUST OVER 7-SECONDS TO PLAY.
<P>
----------
<P>
PLENTY OF TIME FOR THE MOUNTAINEERS.  WITH THE BALL. HE HAD ALREADY DRAINED FOUR 3-POINTERS IN THE GAME. THIS ONE FOR THE WIN. AND HE HITS IT OFF GLASS. AND THE MOUNTAINEERS BUMP OF THE NUMBER TWO SEED. IT'S THE 2ND CLUTCH SHOT OF THE TOURNEY FOR WEST. 75-74 IS THE FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
JUST ANOTHER EXAMPLE OF HOW SORRY THE WARRIORS SEASON HAS BEEN.
<P>
WITHOUT EVEN PLAYING. THE WARRIORS ARE BUMPED OUT OF THE POST SEASON TODAY BY VIRTUE OF THE HOUSTON ROCKETS VICTORY OVER SACRAMENTO.
<P>
IT'S THE 4TH STRAIGHT YEAR THE WARRIORS HAVE FAILED TO MAKE THE PLAYOFFS.
<P>
TO THE ICE. SHARKS IN CAROLINA LOOKING TO END A 2-GAME ROAD LOSING STREAK.
<P>
----------
<P>
DOWN 1-ZIP IN THE 1ST.  RIPS THE SLAP SHOT. BUT  GLOVES IT.
<P>
---------
<P>
SHARKS STAY AGRESSIVE.   MISPLAYS THE PUCK. AND  TAKES ADVANTAGE, SCORING HIS 11TH GOAL OF THE SEASON. MORE IMPORTANTLY IT TIES THE GAME AT ONE.
<P>
---------
<P>
DOES THE JOB ON DEFENSE FROM THERE. 28 SAVES FOR VERNON.    
<P>
----------
<P>
THE SHARKS TAKE THE LEAD IN THE 2ND PERIOD. ON THE POWER PLAY.  PUT'S THE PUCK PAST KIDD. A RARE POWER PLAY GOAL FOR THE SHARKS. BUT IT'S THE WINNER. FINAL. 2-1 SAN JOSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=99Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
IN GOLF.  SHOT A 3RD ROUND.2-UNDER 70 AND HAS A ONE-SHOT LEAD OVER  AT THE WELCH'S/CIRCLE-K CHAMPIONSHIP. 
<P>
AND ON THE SENIOR TOUR. 5-UNDER 66 HAS HIM IN THE LEAD AFTER THE SECOND ROUND OF THE TOSHIBA SENIOR CLASSIC.HE LEADS  BY ONE SHOT.
<P>
3RD ROUND ACTION FROM THE HONDA CLASSIC. 36 HOLE LEADER  SHOWING US HOW NOT TO HIT THE BUNKER SHOT. FIVE BOGEYS ON THE BACK WOULD LEAD TO A 76.
<P>
-----------
<P>
ON THE OTHER HAND  DIDN'T HAVE MUCH TROUBLE. THE BIRDIE AT 7. ONE OF FOUR ON THE FRONT FOR CALCAVECCIA.
<P>
----------
<P>
HE SHOOTS A 68.EVEN SINKING THEM IN THE RAIN. THE LONG BIRDIE AT 12. CALCAVECCIA IS YOUR LEADER BY ONE SHOT OVER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Giants/A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants/A's</H3><BR>
IN CACTUS LEAGUE ACTION TODAY. BOTH THE A'S AND GIANTS GO IN OPPOSITE DIRECTIONS.
<P>
AND  EACH DROVE IN TWO RUNS FOR THE GIANTS.  ALSO DROVE IN A RUN TO GO WITH HITS. BUT THE WHITE SOX SCORE 3 IN THE 9TH TO BEAT GIANTS 8-7. SAN FRANCISCO NOW 6-12 IN THE EXHIBITION SEASON.
<P>
-------------
<P>
IN PEORIA. THE A'S RALLY FOR 5-RUNS IN THE 9TH TO BEAT THE MARINERS. OAKLAND EVENS IT'S RECORD AT 9-9.
<P>
-----------
<P>
AND IN J-C BASEBALL. THE HARTNELL PANTHERS LOSE TO SAN JOSE CITY COLLEGE. 11-9. THE PANTERS DROP TO 1-5 IN LEAGUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123Soccer>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Soccer</H3><BR>
FINALLY. USA TAKING ON PARAGUAY IN SAN DIEGO.2ND HALF.TIED AT 1- WITH THE DIVING
<P>
HEADER FOR THE SCORE.U.S. GOES ON TOP 2-1. AND THE SAN DIEGO STATE ALUMNI GETS MOBBED. 
<P>
----------
<P>
LATE IN THE GAME THOUGH. PARAGUAY ON THE ATTACK. KEEPER  WITH THE ILL.ADVISED TACKLE TO PREVENT THE GOAL.IT WOULD LEAD TO A PENALTY SHOT IN THE 74TH MINUTE. 
<P>
----------
<P>
BLASTS IT INTO THE CORNER TO TIE THE GAME.AND THAT'S HOW IT ENDS WITH THE GAME TIED AT 2.
<P>
WERE JUST 3-MONTHS AWAY FROM THE START OF THE WORLD CUP IN FRANCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106Miss CA/Miss SC>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Miss CA/Miss SC</H3><BR>
TOMORROW IS THE "MISS SANTA CRUZ COUNTY PAGEANT" AND.TWO SPECIAL GUESTS WILL BE IN ATTENDANCE AT THIS YEAR'S EVENT.
<P>
MISS CALIFORNIA 19-97. REBEKEH KELLER AND MISS SANTA CRUZ COUNTY 19-97. JENNIFER CISCO WERE IN SALINAS TODAY PROMOTING THE FESTIVITIES.
<P>
REBEKAH AND JENNIFER WILL BE SPECIAL GUESTS IN TOMORROW'S PAGEANT SCEDULED TO TAKE PLACE AT HARBOR HIGH SCHOOL.
<P>
EIGHT CONTESTANTS WILL BE COMPETING FOR 55-HUNDRED DOLLARS IN SCHOLARSHIP FUNDS AND THE MISS SANTA CRUZ COUNTY TITLE.
<P>
THE WINNER WILL GO ON TO COMPETE IN THE MISS CALIFORNIA PAGEANT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Engagement>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Engagement</H3><BR>
FINALLY TONIGHT.YOU'VE HEARD OF LONG ENGAGEMENTS.BUT THIS ONE TAKES THE CAKE.
<P>
IT TOOK JOHN FOWLES 27 YEARS TO SAY.  "I DO" TO  CAROL CAMPBELL. 
<P>
THE ENGLISH COUPLE ANNOUNCED THEIR ENGAGEMENT BACK WHEN NIXON WAS PRESIDENT.  IN 19-71.
<P>
BUT IT WAS ONLY LAST CHRISTMAS THEY SET A DATE. 
<P>
FOLLOWING THE CEREMONY. THE HAPPY PAIR DECIDED TO GO SOMEWHERE SPECIAL. LAS VEGAS.
<P>
NO WORD ON HOW LONG THEY'LL BE THERE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
