<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (g/Sun), Sunday, 3/29/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (g/Sun), Sunday, 3/29/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x032904.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Big Rig 152>Big Rig 152</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Bathing Brawl>Bathing Brawl</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Hollister Burn-I>Hollister Burn-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Cherry Blossoms>Cherry Blossoms</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#124Hollister Burn-G>Hollister Burn-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39NCAA Final (women)>NCAA Final (women)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Hollister Burn-T>Hollister Burn-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Men's Final>Men's Final</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114El Nino Surf>El Nino Surf</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109UFW March/SF>UFW March/SF</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42NBA Board>NBA Board</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Women Honored>Women Honored</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Cabin Fire Memorial>Cabin Fire Memorial</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Paula Jones-I>Paula Jones-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Paula Jones-G>Paula Jones-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Cactus League>Cactus League</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#104Peru Plane Crash>Peru Plane Crash</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Rose>Rose</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123West Bank>West Bank</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Chippendale-I>Chippendale-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21New Zealand Storm>New Zealand Storm</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#116Chippendale-G>Chippendale-G</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=113Big Rig 152>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Rig 152</H3><BR>
GOOD EVENING.I'M CHERI GYURO.THANKS FOR JOINING US.
<P>
OUR TOP STORY TONIGHT.
<P>
AN OVERTURNED PRODUCE TRUCK CAUSED QUITE A MESS ON HIGHWAY 152 NEAR WATSONVILLE.
<P>
CALIFORNIA HIGHWAY PATROL OFFICERS SAY THE BIG RIG FELL DOWN A RAVINE AROUND EIGHT LAST NIGHT, WHILE TRAVELING WESTBOUND ON THE ROAD.
<P>
CAL TRANS SAYS THE TRUCK FULL OF VEGETABLES WAS JUST TOO BIG TO MAKE THE TIGHT TURN.
<P>
"APPARENTLY THIS DRIVER CAME DOWN WESTBOUND AND 40-TO-60 FOOTERS ARE ILLEGAL ON THIS PARTICULAR ROUTE. ONE REASON IS BECAUSE THE ROAD IS SOMEWHAT NARROW."
<P>
NO ONE WAS HURT IN THE ACCIDENT, BUT THE ROAD IS DAMAGED.
<P>
CAL TRANS SAYS THE WEIGHT OF THE TRUCK CAUSED THE HIGHWAY'S DIRT SHOULDER TO COLLAPSE.
<P>
IF IT RAINS, THE PAVEMENT MAY FACE THE THREAT OF EROSION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Hollister Burn-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hollister Burn-I</H3><BR>
IF YOU SAW *AND* SMELLED A WHOLE LOT OF SMOKE COMING FROM HOLLISTER THIS WEEKEND. THAT'S WHAT IT WAS.
<P>
FIREFIGHTERS FROM ALL OVER SAN BENITO AND MONTEREY COUNTIES SPENT THE WEEKEND DOING SOMETHING THEY RARELY GET TO DO: SET HOMES ON FIRE.
<P>
BUT IT'S NOT WHAT YOU THINK.
<P>
THE COUNTY *WANTED* THOSE HOMES BURNED. SO FIREFIGHTERS DECIDED TO MAKE A GOOD TRAINING EXERCISE OUT OF IT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=124Hollister Burn-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hollister Burn-G</H3><BR>
HERE'S A SCENE YOU DON'T SEE TOO OFTEN:
<P>
FIREFIGHTERS JUST STANDING AROUND WATCHING AS A HOME BURNS TO THE GROUND.
<P>
IT GETS WORSE:  THEY NOT ONLY WATCHED. THEY VIDEOTAPED IT FOR KEEPSAKE. AND BRAGGED ABOUT THE FLAMES TORCHING THEIR GEAR.
<P>
REAL FIREFIGHTERS. REAL HOMES. FAKE EXERCISE.
<P>
ALL WEEKEND LONG, FIREFIGHTERS FROM ALL OVER THE CENTRAL COAST *PRACTICED* PUTTING OUT LIVE HOUSE FIRES AT THE SAN BENITO MIGRANT CAMP.
<P>
YOU SEE, THE COUNTY NEEDED 67 VACANT HOMES IN THE CAMP DESTROYED. AND ASKED LOCAL FIRE DEPARTMENTS IF THEY WANTED TO HELP OUT.
<P>
PRACTICING THEIR CRAFT WERE BOTH VETERAN *AND* ROOKIE FIREFIGHTERS. SOME OF WHOM HAD *NO* EXPERIENCE FIGHTING REAL FIRES.
<P>
THAT WAS THE OFFICIAL REASON FOR THE PRACTICE DRILL. THIS WAS THE UNOFFICIAL REASON:
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Hollister Burn-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hollister Burn-T</H3><BR>
ONE PERSON CALLED IT A FIREFIGHTER'S DISNEYLAND.
<P>
TWELVE FIRE DEPARTMENTS BURNED 26 HOMES TODAY AND YESTERDAY.
<P>
NEXT WEEKEND, A NEW GROUP OF FIREFIGHTERS WILL GET THE CHANCE TO BURN THE REMAINING HOMES.
<P>
CHERI?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114El Nino Surf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>El Nino Surf</H3><BR>
TODAY'S NICE, SUNNY WEATHER HAD SEVERAL FOLKS TAKING ADVANTAGE OF THE GREAT OUTDOORS.
<P>
LOCAL BEACHES WERE LOADED WITH PEOPLE ENJOYING THE LONG-AWAITED SPRING-LIKE WEATHER.
<P>
BUT THE SURF WAS HIGH ALL ALONG THE COAST.
<P>
AUTHORITIES WITH STATE PARKS ISSUED A WARNING TO FOLKS WHO WANT TO GO IN THE WATER.
<P>
MOST OF OUR SERIOUS RESCUES AND DROWNINGS OCCUR THIS TIME OF THE YEAR.SPRINGTIME.WITH TORN UP BEACHES IN LOTS OF AREAS AND RIP CURRENT ACTION.
<P>
BEACH GOERS AND SWIMMERS NEED TO BE AWARE OF THEIR SURROUNDINGS.AND USE THE APPROPRIATE SWIM WEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109UFW March/SF>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>UFW March/SF</H3><BR>
HUNDREDS OF STRAWBERRY WORKERS MARCH THROUGH SAN FRANCISCO'S MISSION DISTRICT TODAY.RALLYING FOR BETTER WORKING CONDITIONS.
<P>
THE PROTESTERS  GATHERED ALONG A STREET NAMED AFTER CESAR CHAVEZ.THE FOUNDER OF THE UNITED FARM WORKERS.
<P>
CALIFORNIA STRAWBERRY GROWERS EMPLOY ABOUT 20-THOUSAND PICKERS DURING PEAK SEASON.APRIL TO JULY.
<P>
MARCHERS SAY WORKERS DON'T HAVE SUITABLE ACCESS TO SANITARY BATHROOMS OR WATER. AND SUFFER FROM ILL-HEALTH LINKED TO  PESTICIDE EXPOSURE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Women Honored>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Women Honored</H3><BR>
THE MOST OUTSTANDING WOMEN OF MONTEREY COUNTY: HONORED TONIGHT IN SALINAS.
<P>
HERE'S A LIST OF RECIPIENTS.
<P>
THE "COMMISSION ON THE STATUS OF WOMEN" RECOGNIZED THEM FOR THEIR CONTRIBUTION TO THE COUNTY.
<P>
THEY'RE ALSO RECOGNIZED FOR EMPOWERING WOMEN THROUGH EXAMPLE.
<P>
CONGRATULATIONS TO ALL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Cabin Fire Memorial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cabin Fire Memorial</H3><BR>
A SOMBER DAY IN SMALL PENNSYLVANIA TOWN.
<P>
A MEMORIAL IS HELD FOR THE STUDENTS KILLED IN A HUGE CABIN FIRE LAST WEEKEND. 
<P>
ALMOST 2-THOUSAND FELLOW STUDENTS.  FAMILIES.  AND FRIENDS GATHERED AT THE LINE MOUNTAIN HIGH SCHOOL.
<P>
THE FIRE HAPPENED IN A MOUNTAIN CABIN. 
<P>
POLICE SAY THE VICTIMS. ALL IN THEIR LATE TEENS OR EARLY TWENTIES.DIED OF SMOKE INHALATION BEFORE THE FLAMES CONSUMED THE BUILDING. 
<P>
THE CAUSE IS STILL UNDER INVESTIGATION. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Paula Jones-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Paula Jones-I</H3><BR>
ATTORNEYS FOR PAULA JONES SAY THEY'RE STILL GETTING THE RUNAROUND FROM THE WHITE HOUSE. 
<P>
THIS LATEST ATTACK SPARKED REACTION FROM WASHINGTON.EVENTHOUGH THE CLINTONS ARE OUT OF TOWN. 
<P>
FOX'S BOB COSTANTINI EXPLAINS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Paula Jones-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Paula Jones-G</H3><BR>
S/VBOTSWANA/AFRICA 
<P>
PRESIDENT AND MRS. CLINTON BAKING IN THE AFRICAN HEAT, WERE 
<P>
GREETED BY TRIBAL LEADERS IN BOTSWANA.WHILE THE HEAT OVER 
<P>
PAULA  
<P>
JONES' SEXUAL HARASSMENT LAWSUIT WAS TURNED UP A FEW MORE 
<P>
DEGREES. 
<P>
IN A COURT FILING SATURDAY, JONES' ATTORNEYS CONTEND THEY 
<P>
SUBPOENAED 
<P>
ALL NOTES AND LETTERS BETWEEN KATHLEEN WILLEY AND PRESIDENT 
<P>
CLINTON, 
<P>
TWO MONTHS AGO, BUT WERE TOLD THERE WERE NONE. 
<P>
S/VMAR. 16/THE WHITE HOUSE 
<P>
YET, LESS THAN TWENTY-FOUR HOURS AFTER WILLEY'S INTERVIEW 
<P>
ON SIXTY  
<P>
MINUTES, THE WHITE HOUSE RELEASED PAGES OF CORRESPONDENCE, 
<P>
INCLUDING  
<P>
ONE NOTE WHERE WILLEY CALLS HERSELF MR. CLINTON'S NUMBER 
<P>
ONE FAN. 
<P>
SOME REPUBLICANS WERE QUICK TO AGREE WITH JONES' ATTORNEYS  
<P>
ASSESSMENT: 
<P>
S/VREP. BOB BARR/--GA./JUDICIARY COMMITTEE 
<P>
"THE PRESIDENT CANNOT, AT LEAST WITH A STRAIGHT FACE, CLAIM THAT 
<P>
THESE WERE EITHER PERSONAL RECORDS OR PRESIDENTIAL RECORDS.  THEY ARE 
<P>
CLEARLY COVERED BY THAT REQUEST AND CLEARLY THERE HAS BEEN IN THIS 
<P>
INSTANCE, AGAIN, OBSTRUCTION OF JUSTICE."  
<P>
THE NOTES WERE CLEARLY PERSONAL IN NATURE, BUT THE 
<P>
ADMINISTRATION IS 
<P>
CLAIMING THEY ARE OFFICIAL WHITE HOUSE DOCUMENTS, AND NOT 
<P>
COVERED BY 
<P>
JONES' ATTORNEYS' REQUEST: 
<P>
S/VFOX NEWS SUNDAY 
<P>
S/VRAHM EMANUEL/PRESIDENTIAL ADVISOR 
<P>
"IN THE PAST, THEY UNDERSTAND THE DISTINCTION BETWEEN HIM AS AN 
<P>
INDIVIDUAL AS WELL AS THE WHITE HOUSE; AND THEY FAILED THEIR CLIENT 
<P>
AND NOW THEY'RE TRYING TO MAKE UP FOR THEIR FAILURE."   
<P>
WHILE THE WHITE HOUSE CLAIMS IT'S NOTHING PERSONAL, OTHERS 
<P>
SAY IT  
<P>
DOESN'T MATTER: 
<P>
S/VSEN. ARLEN SPECTER/--PA./JUDICIARY COMMITTEE 
<P>
"YOU DON'T ESCAPE RESPONSIBILITY BECAUSE YOU HAVE SOMEBODY FILE THEM 
<P>
IN SOME OTHER DRAWER." 
<P>
S/VBOB COSTANTINI/REPORTING 
<P>
"THE JONES FILING INCLUDES ANOTHER CLAIM THAT AS ATTORNEY 
<P>
GENERAL IN ARKANSAS, TWENTY YEARS AGO, BILL CLINTON SEXUALLY 
<P>
ASSAULTED A WOMAN.   
<P>
BUT THE WOMAN REPORTEDLY DENIED THE INCIDENT UNDER OATH IN 
<P>
A DEPOSITION IN THE JONES CASE." 
<P>
THE WHITE HOUSE TERMED THE ACCUSATION "OUTRAGEOUS!" 
<P>
EVEN ONE REPUBLICAN THINKS IT'S OUT OF BOUNDS: 
<P>
"THAT JOINS ONE OF THE MANY,MANY LINES OF RECKLESS ACCUSATIONS WHICH 
<P>
GO BOTH WAYS." 
<P>
UNLESS THE JUDGE DISMISSES THE CASE,  
<P>
THE TRIAL OF JONES VERSUS CLINTON REMAINS ON TRACK TO START 
<P>
MAY 27. 
<P>
IN WASHINGTON, BOB COSTANTINI, FOX NEWS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=104Peru Plane Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Peru Plane Crash</H3><BR>
TURNING TO INTERNATIONAL NEWS. 28 PEOPLE ARE DEAD AFTER A PERUVIAN AIR FORCE PLANE CRASHES IN PERU. 
<P>
THE PLANE WAS CARRYING ABOUT 50 PASSENGERS.MOST CIVILIANS.
<P>
THE AIR FORCE PILOT MAY HAVE KEPT THE CRASH FROM BEING MUCH WORSE.BY STEERING THE PLANE INTO A CANAL TO AVOID HITTING HOMES NEARBY. 
<P>
THE PILOT RADIOED THE CONTROL TOWER TO REPORT ONE ENGINE HAD FAILED SHORTLY BEFORE THE CRASH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123West Bank>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>West Bank</H3><BR>
ON ISRAEL'S WEST BANK. A CAR BOMB EXPOLODES. KILLING ONE PERSON.AND INJURING SEVERAL OTHERS. 
<P>
THERE IS NO WORD YET AS TO WHETHER THE BOMB WAS THE WAS A PART OF A TERRORIST SUICIDE ATTACK.
<P>
OFFICIALS SAY. NO LICENSE PLATE WAS SEEN ON THE REMNANTS OF THE CAR. 
<P>


<P>
        
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21New Zealand Storm>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>New Zealand Storm</H3><BR>
DOZENS OF HOUSES ARE DAMAGED IN NEW ZEALAND FOLLOWING A BRIEF,  BUT VIOLENT CYCLONE.NAMED  YALI. 
<P>
YALI HIT THE NORTH AND SOUTH ISLANDS OF NEW ZEALAND, FLOODING HOMES.  RIPPING ROOFS APART. AND CUTTING OFF ELECTRICAL POWER. 
<P>
HEAVY RAINS ALSO SNARLED TRAFFIC AND DELAYED DOMESTIC FLIGHTS. 
<P>
DAMAGE WAS MINIMAL. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Bathing Brawl>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bathing Brawl</H3><BR>
MORE THAN ONE HUNDRED MONKS AND POLICEMEN ARE INJURED AFTER A RELIGIOUS BRAWL IN INDIA. 
<P>
THE FIGHTING BROKE OUT WHEN MONKS BELONGING TO TWO DIFFERENT GROUPS ARGUED OVER WHO SHOULD LEAD THE PROCESSION OF THE "ROYAL BATH" IN THE GAN-JEEZ RIVER. 
<P>
THE TWO GROUPS CLASHED WITH SWORDS AND STICKS.
<P>
NAKED MONKS PELTED POLICEMEN WITH STONES WHEN THEY TRIED TO INTERVENE.   
<P>
THE ROYAL BATH IS ONE OF THE WORLD'S LARGEST RELIGIOUS CELEBRATIONS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Cherry Blossoms>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cherry Blossoms</H3><BR>
IT'S A RITE OF SPRING IN WASHINGTON EVERY YEAR.
<P>
IT'S NOT THE RETURN OF CONGRESS. BUT THE RETURN OF THE CHERRY BLOSSOMS. 
<P>
THE TWO-WEEK NATIONAL CHERRY BLOSSOM FESTIVAL OPENS TODAY.
<P>
THE CELEBRATION HONORS THE FRIENDSHIP BETWEEN THE UNITED STATES AND JAPAN.AND OF COURSE.THE BEAUTY OF THE CHERRY BLOSSOMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39NCAA Final (women)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NCAA Final (women)</H3><BR>
MARCH MADNESS HEADS DOWN THE HOME STRETCH WITH THE MEN MEETING IN THE CHAMPIONSHIP GAME ON MONDAY. BUT FIRST THE WOMEN HOLD CENTER STAGE.
<P>
TENNESSEE TAKING ON LOUSIANA TECH. OR DAVID VERSUS GOLIATH IF YOU WISH.
<P>
THE VOLS COMING IN WITH 5 TITLES IN THE LAST 11 YEARS. THE COACH OF THE YEAR IN PAT SUMMIT. AND THE PLAYERS OF THE YEAR. CHAMIQUE HOLDSCLAW.
<P>
SUMMIT'S TEAM WOULD JUMP ON THE LADY TECHSTERS FROM THE GET GO. LOOK AT THE BALL MOVEMENT AFTER THE STEAL. TENNESSEE BY 23 AT THE HALF.
<P>
-----------
<P>
THEY WOULD NEVER LOOK BACK. HOLDSCLAW SCORES 25 AND IS NAMED THE FINALS MVP. AS TENNESSEE ROUTS TECH. 93-75. IT'S THE LADY VOLS' 45TH STRAIGHT VICTORY AND SIXTH TITLE. THEY FINISH THE SEASON A PERFECT 39-0. THE MOST VICTORIES EVER FOR A WOMEN'S N-C DOUBLE-A TEAM.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Men's Final>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Men's Final</H3><BR>
THE MENS FINAL PITTS THE "GIANT KILLERS"  VERSUS THE "COMEBACK KIDS".
<P>
UTAH BUMPED OFF TWO OF THE TOP SEEDS ON THEIR ROAD TO THE CHAMPIONSHIP. AND NOW THEY HAVE PAYBACK ON THEIR MIND AGAINST KENTUCKY. THE TEAM THAT HAS ENDED THE UTES SEASON THE PAST TWO YEARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE WARRIORS WOEFULL SEASON CONTINUES TONIGHT WITH ANOTHER LOSS. THEIR 10TH IN THE LAST 11 GAMES.
<P>
P.J'S GUYS TAKING ON THE PORTLAND TRAILBLAZERS.
<P>
--------
<P>
WARRIORS HANGING WITH THE BLAZERS IN THE FIRST QUARTER.  WITH THE NICE DISH TO  FOR 2 OF HIS 16 POINTS. GOLDEN STATE BY TWO AT THE END OF ONE.
<P>
---------
<P>
THE BLAZERS RESPOND.  WITH SOME NIFTY DRIBBLING. AND THEN THE JUMPER. STAUDOMIRE SCORES 12 POINTS AND DISHES OUT 6 ASSISTS.
<P>
---------
<P>
GOLDEN STATE JUST STRUGGLING. THE ALLEY-OOP TO. OH MY. THE WARRIORS FALL AGAIN.
<P>
FINAL.99-83.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42NBA Board>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA Board</H3><BR>
THE WARRIORS WERE WITHOUT  WHO IS OUT WITH A SPRAINED ANKLE.
<P>
ELSEWHERE. THE LAKERS HAMMER THE WIZZARDS.
<P>
---------
<P>
MINNESOTA BEATS SACRAMENTO WHILE THE CLIPPERS HANDLE THE MAVS.
<P>
----------
<P>
PHOENIX BEATS VANCOUVER. INDIANA SETS A MODERN DAY RECORD BY SCORING THE FEWEST POINTS SINCE THE ADVENT OF THE SHOT CLOCK.
<P>
---------
<P>
M-J SCORES 30 IN THE BULLS VICTORY. THE HORNETS GET DUMP BY THE CAVS.
<P>
--------
<P>
ORLANDO WINS EASILY. SCORES 22 TO LEAD THE HEAT PAST THE ROCKETS. 
<P>
---------
<P>
PHILY WINS AT HOME. AND THE ATLANTA HAWKS GET THEIR HIGHEST OUTPUT OF THE SEASON. IN THE WIN OVER DETROIT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
PETE SAMPRAS RULED TENNIS FOR 102 WEEKS. BUT HIS REIN HAS COME TO AN END.
<P>
THANKS TO A 22-YEAR OLD SOUTH AMERICAN BY THE NAME OF MARCELO RIOS.
<P>
RIOS WILL TAKE OVER THE TOP SPOT WHEN THE RANKINGS COME OUT ON MONDAY. AFTER HIS WIN OVER  IN THE FINALS OF THE LIPTON CHAMPIONSHIP.
<P>
---------
<P>
AGASSI WAS GOING FOR HIS 3RD TITLE OF THE YEAR. BUT THE CHILEAN WAS JUST TOO HOT. WITH BLISTERING GROUND STROKES. RIOS WOULD WIN THE FIRST SET 7-5.
<P>
---------
<P>
MORE OF THE SAME IN THE 2ND SET. AGASSI TRYING TO GO WIDE ON THE SERVICE. BUT RIOS HAS AN ANSWER FOR EVERY SHOT. HE WOULD WIN THE 2ND SET 6-3.
<P>
--------
<P>
THEN ON MATCH POINT. AGASSI HIT'S HIS RETURN LONG. RIOS WINS IN STRAIGHT SETS. 6-4 IN THE 3RD.
<P>
---------
<P>
RIOS BECOMES JUST THE SECOND PLAYER TO REACH NUMBER ONE WITHOUT HAVING WON A MAJOR TOURNAMENT. THE OTHER WAS  IN 1983, WHO WENT ON TO WIN EIGHT GRAND SLAMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
NEXT. WHAT A COMEBACK BY  IN THE FINAL ROUND OF THE PLAYERS CHAMPIONSHIP.
<P>
----------
<P>
LEONARD. 5-SHOTS OFF THE LEAD WHEN THE DAY BEGINS. WOULD MAKE A SERIOUS CHARGE.
<P>
HE WOULD MAKE 4 BIRDIES IN A FIVE HOLE STRETCH. AT 13. THE BIRDIE PUTT GIVES HIM A 1 SHOT LEAD.
<P>
-----------
<P>
HE WOULD SHARE THE LEAD WITH  BEFORE MATTICE SELF-DESTRUCTS AT 17. HIS DRIVE FINDING A WATERY GRAVE. 
<P>
THEN ON HIS 4TH SHOT OUT OF THE BUNKER. OH MY. MORE WATER. HE WOULD MAKE AN 8. THE DREADED QUINTUPLE  BOGEY.
<P>
---------
<P>
SO BASICALLY. LEONARD ONLY NEEDS TO HIT THE CENTER OF THE GREEN ON 17 TO CLINCH IT. AND HE DOES.  CLOSES WITH A 67 TO WIN THE PLAYERS CHAMPIONSHIP AND THE WHOPPING 720-THOUSAND DOLLAR 1ST PLACE PRIZE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
IT'S HARD TO BELIEVE BUT WERE JUST A COUPLE OF DAYS AWAY FROM OPENING DAY.
<P>
BOTH THE A'S AND GIANTS WRAP UP THE EXHIBITION SEASON TODAY IN OAKLAND.
<P>
IT'S BEEN A TOUGH SPRING FOR DUSTY'S CREW. THE GIANTS WITH JUST 9 WINS IN CACTUS LEAGUE PLAY. AND OH-AND-4 AGAINST THE A'S.
<P>
-------
<P>
THEY TRAIL 2-NOTHING IN THE 4TH WHEN  GIVES THE  FASTBALL A RIDE. AND RICKEY THINKS HE GOT ALL OF THIS ONE. BUT IT HIT'S OFF THE WALL FOR A 2-RUN DOUBLE. RICKEY CAN'T BELIEVE IT DIDN'T GO OUT. THE FANS DON'T CARE. 4-NOTHING A'S.
<P>
--------
<P>
STILL IN THE 4TH. ROOKIE  AT THE PLATE.AND THE ROOK GOES THE OTHER WAY. GRIEVE FINISHES WITH 2-RIBBIES IN THE GAME. AS THE A'S BLANK THE GIANTS 6-NOTHING.
<P>
THE A'S FINISH THE SPRING 18-13, WHILE THE GIANTS END UP 9-21.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Cactus League>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cactus League</H3><BR>
WELL. THE GIANTS WILL HAVE THEIR HANDS FULL IN THE N-L WEST. THE TOUGHEST DIVISION IN BASEBALL.
<P>
THEY'LL ALSO GET A CHANCE TO FACE ONE OF THE MOST POPULAR FORMER GIANTS ON A REGULAR BASIS. AS MATT WILLIAMS RETURNS TO THE NATIONAL LEAGUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Rose>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rose</H3><BR>
AND FINALLY.  IS BANNED FROM BASEBALL. BUT THAT DIDN'T KEEP HIM FROM STEPPING INTO THE RING FOR WRESTLEMANIA 14.
<P>
------------
<P>
HE MAY THINK TWICE ABOUT GOING BACK THOUGH. THE HIT KING WAS RUNG UP BY "KANE THE UNDERTAKER"  AFTER CALLING BOSTON THE "CITY OF LOSERS". THE UNDERTAKER PLANTED ROSE.
<P>
I'M SURE THIS SHOULD HELP ROSE IN HIS BID TO GET INTO THE HALL OF FAME. THE WRESTLING HALL OF FAME THAT IS. ROSE WAS WHEELED OFF ON A STRETCHER.  A WWF SPOKESMAN SAID HOWEVER. WITH A STRAIGHT FACE. THAT ROSE WAS FINE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Chippendale-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chippendale-I</H3><BR>
IT MAY BE ONE OF THE FEW JOB INTERVIEWS WHERE YOU'RE NOT ENCOURAGED TO DRESS UP. BUT TO DRESS DOWN. ALL THE WAY DOWN. 
<P>
FOX'S ELISEA HART HAS THE STORY ABOUT SOME REAL-LIFE MEN WHO AREN'T AFRAID OF THE "FULL MONTY." 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=116Chippendale-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chippendale-G</H3><BR>
NAT 26:13 HI HOW ARE YOU 
<P>
DOZENS OF MEN CRAMMED INTO A SMALL NEW YORK CITY DANCE STUDIO FOR THE 
<P>
AUDITIONS. 
<P>
NAT DANCING: 
<P>
BUT THEY'RE NOT JUST LOOKING FOR FANCY FOOTWORK. THIS IS KINDA LIKE 
<P>
A REAL-LIFE VERSION OF "THE FULL MONTY." 
<P>
NAT SOUND OF MOVIE-- CATTLE CALL 
<P>
CUT TO NAT SOUND OF AUDITION  
<P>
THE CHIPPENDALE AUDITIONS - AND THEY'RE LOOKING FOR ARE MEN WHO ARE 
<P>
-- SHALL WE SAY -- NOT SHY. 
<P>
SOUND IN 1:07 OBVIOUSLY SOMEONE WHO'S COMFORTABLE WITH THEMSELVES - 
<P>
SO THEY'RE COMFORTABLE ENOUGH TO TAKE OFF MOST OF THEIR CLOTHING IN 
<P>
FRONT OF LARGE GROUPS OF WOMEN. 
<P>
SO - IT STANDS TO REASON - THE FIRST QUESTION YOU;RE ASKED HERE - IS 
<P>
PLEASE TAKE OFF YOUR SHIRT.  
<P>
MUSIC/LET'S TALK ABOUT SEX BABY 
<P>
STANDUP:  54:24 NOW IT'S NICE IF THEY CAN PERFORM - BUT WHAT REALLY 
<P>
COUNTS IS HOW THEY LOOK WITHOUT THEIR CLOTHES -- BUT THE CHIPPENDALE 
<P>
DANCERS DON'T TAKE IT ALL OFF - JUST MOST OF IT. 
<P>
MUSIC FULL "YOU CAN LEAVE YOUR HAT ON" 
<P>
AND IF THEY DON'T LIKE WHAT THEY SEE -- THEY TELL YOU 
<P>
50:13 YOU HAVE A GREAT ATTITUDE - BUT YOUR GOING TO HAVE TO WORK ON 
<P>
YOUR BODY. 
<P>
SOUND 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
