<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Thursday, 3/19/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFFF><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 3/19/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (PG pep)>TS1 (PG pep)</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(school safe) >bump 2(school safe) </A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107PG pep rally-INT>PG pep rally-INT</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(plane crash)>(plane crash)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108PG pep rally-GUT>PG pep rally-GUT</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(LA car chase)>(LA car chase)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109PG pep rally-TAG>PG pep rally-TAG</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(police beat verdict)>(police beat verdict)</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Salinas teachers>Salinas teachers</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142School safety-INT>School safety-INT</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#147Lamb verdict>Lamb verdict</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/video game>Fox Biz/video game</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Casa/del ray woods>Casa/del ray woods</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Final Four>Final Four</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Mty Seaside 187>Mty Seaside 187</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Beach flats bust>Beach flats bust</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Sliding Homes-INT>Sliding Homes-INT</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145Fox Sports>Fox Sports</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Jason project>Jason project</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Peter Paul Mary/UF>Peter Paul Mary/UF</A></TD>
<TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140fort ord planting>fort ord planting</A></TD>
<TR><TD BGCOLOR=#FFFFFF><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(plane crash) >Bump 1(plane crash) </A></TD>


<TD BGCOLOR=#FFFFFF> </TD>
</Table>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
</CENTER><HR><BR>
<A NAME=134TS1 (PG pep)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (PG pep)</H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
FOLKS IN PACIFIC GROVE PREPARE A BIG SEND OFF FOR THEIR HOME TOWN HEROES. 
<P>
AND A TRAGIC PLANE CRASH IN SOUTHERN CALIFORNIA LEAVES DEATH AND DESTRUCTION SPREAD OVER HALF A MILE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
        THE USUALLY QUIET TOWN OF PACIFIC GROVE BROKE OUT INTO NOISY CELEBRATION TONIGHT.
<P>
        THE COMMUNITY TURNED OUT FOR A GOOD-LUCK SENDOFF FOR THE P-G HIGH BASKETBALL TEAM. WHICH IS JUST HOURS AWAY FROM A CHAMPIONSHIP GAME THAT *COULD* MAKE THEM NUMBER ONE IN THE STATE.
<P>
        JINAH KIM WAS AT THE BIG PEP RALLY AT P-G HIGH TONIGHT.
<P>
SHE JOINS US NOW LIVE FROM OUR MONTEREY NEWSROOM WITH THE STORY.  JINAH?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107PG pep rally-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG pep rally-INT</H3><BR>
        PACIFIC GROVE IS CELEBRATING IN A BIG WAY. AND WHEN
<P>
WE SAY PACIFIC GROVE. WE MEAN JUST ABOUT THE WHOLE TOWN. SO MUCH OF THE COMMUNITY IS ROOTING FOR THE TEAM.
<P>
        THEY PLAY IN SACRAMENTO TOMORROW NIGHT AGAINST *VERBUM DEI* HIGH FROM SOUTHERN CALIFORNIA. FOR THE STATE CHAMPIONSHIP
<P>
TITLE.
<P>
        IT'S A BIG GAME. THAT GOT A BIG SEND-OFF TONIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108PG pep rally-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG pep rally-GUT</H3><BR>
        FOR PG HIGH. IT'S THE MOTHER OF ALL PEP RALLIES.
<P>
        HUNDREDS OF BREAKER FANS CHEERING ON THEIR FAVORITE TEAM.
<P>
        THE ONE THAT, FOR THE FIRST TIME IN THE SCHOOL'S 100-YEAR
<P>
HISTORY, BEAT OUT ALL OF NORTHERN CALIFORNIA IN THE C.C.S. 
<P>
DIVISION FOUR CHAMPIONSHIPS LAST WEEK.
<P>
        THE ONE THAT HOPES TO MAKE HISTORY AGAIN. WHEN IT GOES
<P>
FOR THE *STATE* TITLE TOMORROW NIGHT.
<P>
        LOOK AROUND TOWN AND YOU SEE BREAKERS' BANNERS, SIGNS.RIBBONS.
<P>
        LOCAL GROCERY STORE CLERKS TALK ABOUT THEM AS THE ONES WHO
<P>
MADE HISTORY FOR AMERICA'S LAST HOMETOWN.
<P>
        THE TEAM'S GOT PRACTICALLY THE WHOLE TOWN ROOTING FOR THEM.
<P>
BUT THE REALITY IS. THEIR SOUTHERN CALIFORNIA CHALLENGER IS ONE
<P>
OF THE TOUGHEST HIGH SCHOOL TEAMS IN THE COUNTRY.
<P>
        THE PLAYERS DON'T DENY. THEY'VE GOT THE JITTERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109PG pep rally-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG pep rally-TAG</H3><BR>
        THAT TEAM IS GOING TO HAVE A TOUGH TIME FALLING
<P>
ASLEEP TONIGHT.
<P>
        TOMORROW. SOME TWO-THOUSAND FANS ARE GOING TO 
<P>
ACCOMPANY THE TEAM AS THEY HEAD UP TO SACRAMENTO FOR THE FOUR O'CLOCK GAME.
<P>
        THAT'S A LOT OF PEOPLE. CONSIDERING THERE'S ONLY
<P>
590 STUDENTS IN THE ENTIRE SCHOOL.
<P>
        ALAN??
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Salinas teachers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas teachers</H3><BR>
THE BITTER BATTLE CONTINUES TODAY. AS TEACHERS' UNION REPRESENTATIVES. AND SALINAS UNION HIGH SCHOOL DISTRICT OFFICIALS MEET TO NEGOTIATE A LONG OVERDUE CONTRACT AGREEMENT.
<P>
MEANWHILE. CLASSES GO ON AS USUAL AT DISTRICT SCHOOLS. 
<P>
BUT STUDENTS ARE LEFT WONDERING IF A TEACHER'S STRIKE IS IN THEIR FUTURE.
<P>
AND TEACHERS ARE LEFT ASKING WHAT'S TAKING SO LONG?
<P>
Three years ago. haven't given us any raises.
<P>
DISTRICT SUPERINTENDENT FERNANDO LIZONDO SAYS TEACHERS *HAVE* RECEIVED ADDITIONAL COMPENSATION. 
<P>
TEACHERS TELL US THEY *DID* RECEIVE A BONUS. BUT THEY SAY IT'S JUST NOT ENOUGH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=147Lamb verdict>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lamb verdict</H3><BR>
HE HAS ALREADY SERVED HIS TIME. BUT A CONVICTED CHILD MOLESTER IS HEADING BACK TO PRISON FOR TWO YEARS ANYWAY.
<P>
A JURY FOUND 38-YEAR-OLD JAMES LAMB. TO BE A SEXUALLY VIOLENT PREDATOR. MEANING HE'S LIKELY TO STRIKE AGAIN.
<P>
LAMB WAS CONVICTED OF MOLESTING TWO SALINAS BOYS IN 1984. AND AFTER HE SERVED TIME FOR THAT. HE STRUCK AGAIN,  MOLESTING A LITTLE BOY IN SPRECKLES IN 1991.
<P>
LAST JULY, HE WAS RELEASED ONCE AGAIN FROM PRISON. BUT LESS THAN A MONTH LATER, AUTHORITIES FOUND HIM IN POSESSION OF PORNOGRAPHY. AND PHOTOS OF YOUNG BOYS. A VIOLATION OF HIS PROBATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Casa/del ray woods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Casa/del ray woods</H3><BR>
THE MAN ACCUSED OF TRYING TO ABDUCT YOUNG CHILDREN NEAR A LOCAL SCHOOL IS ARRAIGNED TODAY.
<P>
        SEASIDE AUTHORITIES SAY JESUS CASAS TRIED TO ABDUCT KIDS NEAR DEL REY WOODS SCHOOL ON THREE SEPARATE OCCASIONS.
<P>
        CASAS REPORTEDLY TOLD THE CHILDREN HE WAS SENT BY THEIR PARENTS TO PICK THEM UP.
<P>
IN ALL THREE CASES. THE YOUNGSTERS RAN AWAY AND TOLD AN ADULT.
<P>
        CASAS. WHO AUTHORITIES SAY IS AN ILLEGAL IMMIGRANT FROM MEXICO. PLEADED NOT GUILTY TO THE CHARGES TODAY.
<P>
HE'LL BE BACK IN COURT NEXT MONTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Mty Seaside 187>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mty Seaside 187</H3><BR>
THE TEENAGER CHARGED IN THE SHOOTING DEATHS OF TWO WOMEN.WILL BE TRIED AS AN ADULT.
<P>
THE 17-YEAR-OLD IS ACCUSED OF SHOOTING THREE WOMEN IN TWO SEPARATE INCIDENTS.ONE ON MONTEREY WHARF NUMBER TWO. THE OTHER IN SEASIDE.
<P>
TWO OF THE WOMEN. INCLUDING A MOTHER OF SIX. WERE KILLED.
<P>
THE CHARGES AGAINST THE TEEN INCLUDE SPECIAL CIRCUMSTANCES.
<P>
THAT COULD LEAD TO LIFE IN PRISON WITHOUT PAROLE. 
<P>
THE TEEN IS EXPECTED TO BE BACK IN COURT TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Beach flats bust>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Beach flats bust</H3><BR>
NARCOTIC AGENTS  TODAY GO AFTER ALLEGED DRUG SUPPLIERS IN THE BEACH FLATS AREA OF SANTA CRUZ.
<P>
OFFICERS WITH SC-C-NET. SERVED EIGHT SEARCH WARRANTS.
<P>
SOME NEW TECHNOLOGY HELPED THEM OUT. 
<P>
RATHER THAN UNDERCOVER STREET BUYS. OFFICERS TRACKED PHONE CALLS INSTEAD.
<P>
EIGHTY AGENTS PARTICIPATED IN THIS MORNING'S BUST.
<P>
OFFICERS SAY THIS IS A RESULT OF A YEARLONG INVESTIGATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Sliding Homes-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sliding Homes-INT</H3><BR>
"EL NINO" WAS AT IT AGAIN TODAY IN SOUTHERN CALIFORNIA. EVEN THOUGH IT DIDN'T EVEN RAIN! 
<P>
IT WAS PREVIOUS WET EL NINO WEATHER THAT HELPED BRING DOWN TWO HOUSES ON A HILLSIDE IN LAGUNA, NIGUEL.      FOX'S JANE WELLS HAS THE STORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Jason project>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jason project</H3><BR>
STUDENTS IN MONTEREY ARE GETTING A VIRTUAL LOOK AT THE BOTTOM OF THE OCEAN THANKS TO NASA. 
<P>
THE "JASON" PROJECT IS HELPING STUDENTS FROM FOURTH TO NINTH GRADES LEARN MORE ABOUT OCEAN LIFE AND ITS DYNAMICS. 
<P>
TODAY. STUDENTS WERE ABLE TO CONTROL REMOTE-OPERATED UNDERWATER  VEHICLES. AND CAMERAS IN MONTEREY BAY, BERMUDA AND THE GUAYMA BASIN. 
<P>
AND AS THE STUDENTS LEARNED. THE PROJECT TAKES THEM WHERE NO CHILD HAS GONE BEFORE.
<P>
"we just came here to learn about stuff and i 
<P>
think it's really amazing because of all the interesting things in 
<P>
the sea." 
<P>
"i think it's really important to take care of our 
<P>
oceans because animals need to live and plants need to live.and 
<P>
not have the ocean be all polluted." 
<P>
THE VIRTUAL SCIENCE FIELD TRIP TOOK PLACE AT NASA AMES RESEARCH CENTER IN MOFFETT FIELD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Peter Paul Mary/UF>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Peter Paul Mary/UF</H3><BR>
THE UNITED FARM WORKERS HAVE ENLISTED THE HELP OF A POPULAR SINGING GROUP. TO ORGANIZE LOCAL STRAWBERRY PICKERS.
<P>
PETER, PAUL AND MARY HAVE LONG SUPPORTED THE U-F-W.
<P>
THIRTY YEARS AGO. THEY CAME TO THE AID OF U-F-W FOUNDER Caesar CHAVEZ. DURING THE GRAPE GROWERS STRIKE.
<P>
THIS TIME THE TRIO IS CAMPAIGNING FOR BETTER LIVING AND WORKING CONDITIONS FOR FARM WORKERS.
<P>
THE GROUP VISITED THE SAN ANDREAS LABOR CAMP TO SEE FIRST HAND WHAT KIND OF REPAIRS ARE NEEDED.
<P>
CAMP MEMBERS SAY THEY HOPE THE GROUP'S POPULARITY WILL BRING ATTENTION TO THEIR STRUGGLE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(plane crash) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(plane crash) </H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
A FIERY MID-AIR COLLISION IN SOUTHERN CALIFORNIA LEAVES AT LEAST THREE PEOPLE DEAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(school safe) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(school safe) </H3><BR>
AND THE WHITE HOUSE UNVEILS A PLAN TO MAKE PUBLIC SCHOOLS SAFER.
<P>
THOSE STORIES RIGHT AFTER THIS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
AT LEAST THREE PEOPLE ARE DEAD AFTER TWO SMALL PLANES COLLIDE IN MID-AIR.  
<P>
THAT STORY FROM CORONA, CALIFORNIA TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(plane crash)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(plane crash)</H3><BR>
TWO SEPARATE FIRES ERUPTED THIS AFTERNOON. WHEN DEBRIS FROM THE MIDAIR COLLISION SCATTERED OVER A HOUSE AND A CONDOMINIUM ABOUT A HALF MILE APART.
<P>
INVESTIGATORS SAY THEY STILL DON'T KNOW IF THE THREE BODIES WERE IN THE PLANE OR RESIDENTS ON THE GROUND.
<P>
TWO OF THE BODIES WERE FOUND IN THE CONDOMINIUM. THE OTHER IN THE HOUSE.
<P>
STILL NO WORD ON WHAT CAUSED THE COLLISION. OR WHERE THE PLANES WERE HEADED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(LA car chase)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(LA car chase)</H3><BR>
TWO BANK ROBBERY SUSPECTS SPIN OUT OF CONTROL AND CRASH ON A LOS ANGELES FREEWAY.
<P>
POLICE SAY THAT BOTH MEN. ALONG WITH TWO OTHERS. ARE SUSPECTED IN THE HOLDUP OF A BANK OF AMERICA BRANCH IN BAKERSFIELD. 
<P>
THE SUSPECTS  REACHED SPEEDS IN EXCESS OF A HUNDRED MILES AN HOUR. BEFORE HITTING A GUARDRAIL AND SPINNING OUT OF CONTROL. 
<P>
AFTER A FOOT PERSUIT. THE SUSPECTS WERE QUICKLY CAUGHT BY POLICE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(police beat verdict)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(police beat verdict)</H3><BR>
IN DETROIT, MICHIGAN. A WHITE POLICE OFFICER HAS BEEN CONVICTED FOR THE SECOND TIME. OF BEATING A BLACK MOTORIST TO DEATH.
<P>
FIVE YEARS AGO A JURY CONVICTED WALTER BUDZYN OF SECOND-DEGREE MURDER. IN THE DEATH OF MALICE GREEN.
<P>
BUDZYN HAD ALREADY SERVED FOUR-AND-A-HALF YEARS OF AN EIGHT-TO-EIGHTEEN YEAR SENTENCE. WHEN THE 
<P>
STATE SUPREME COURT THREW OUT THE VERDICT. 
<P>
TODAY THE JURY FOUND HIM GUILTY OF A LESSER CHARGE. SECOND-DEGREE MANSLAUGHTER. 
<P>
PROSECUTORS SAY THEY MAY NOT ASK FOR ANY ADDITIONAL JAIL TIME. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142School safety-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>School safety-INT</H3><BR>
ALTHOUGH ONLY ONE IN TEN AMERICAN PUBLIC SCHOOLS EXPERIENCED SERIOUS VIOLENCE LAST YEAR. PRESIDENT CLINTON SAYS THAT'S NOT GOOD ENOUGH. 
<P>
THIS AFTERNOON, THE PRESIDENT ANNOUNCED A SEVENTEEN-AND-A-HALF MILLION DOLLAR PLAN TO MAKE SCHOOLS EVEN SAFER. 
<P>
FOX'S STEVE CENTANNI HAS MORE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/video game>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/video game</H3><BR>
DRUGS. SHOOTINGS. STEALING CARS. RUNNING PEOPLE OVER.
<P>
SOUNDS LIKE SCENES FROM A VERY VIOLENT MOVIE.
<P>
BUT BELIEVE IT OR NOT. IT'S ACTUALLY A VIDEO GAME THAT'S BEING BEING SOLD TO KIDS.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
IT'S CALLED GRAND THEFT AUTO. A CRIME SIMULATION GAME IN WHICH PLAYERS STEAL CARS AND OTHER VEHICLES. RUN DRUGS. SHOOT PEOPLE. INCLUDING POLICE OFFICERS. AND MOW DOWN PEDESTRIANS FOR EXTRA POINTS.
<P>
THE GAME. DISTRIBUTED BY AMERICAN SOFTWORKS CORPORATION. HAS ALREADY BEEN BANNED IN BRAZIL.
<P>
HERE IN THE U-S. THE GAME GETS A WARNING LABEL THAT IT'S INTENDED FOR PLAYERS. 17 AND OLDER. BUT THERE ARE NO PENALTIES FOR RETAILERS WHO SELL IT TO KIDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Final Four>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Final Four</H3><BR>
IT WAS 3-LONG DAYS WITHOUT GAMES, BUT MARCH MADNESS CONTINUES TONITE.
<P>
WE START WITH THE DEFENDING NATIONAL CHAMPION ARIZONA WILDCATS, WHO ARE THE TOP SEED IN THE WEST REGIONAL, TAKING ON THE 4TH SEEDED MARYLAND TERRAPINS OF THE ACC.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
STANFORD GETS BACK INTO ACT TOMORROW NIGHT, WHEN THEY FACE THE BIG-10 CO CHAMPIONS, THE PURDUE BOILMAKERS IN THE MIDWEST REGIONAL.
<P>
WITH THE RHODE ISLAND/VALPO WINNER UP NEXT, THE STANFORD/PURDUE WINNER WILL HAVE A GREAT SHOT AT THE FINAL FOUR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE NBA ALWAYS TAKES A BACKSEAT TO THE COLLEGE GAME DURING TOURNAMENT TIME.
<P>
BUT TONITE THE WARRIORS DO VISIT THE DALLAS MAVERICKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145Fox Sports>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Sports</H3><BR>
ITS OFFICIAL, FOX HAS JUMPED INTO BASEBALL WITH BOTH FEET.
<P>
MR. FOX, RUPPERT MURDOCH, IS NOW THE OWNER OF THE LOS ANGELES DODGERS.
<P>
BASEBALL'S OWNERS APPROVED THE LONG DISCUSSED DEAL TODAY.
<P>
THE ONLY DISSENTING VOTES, BRAVES OWNER TED TURNER, WHO'S TV BIZ HAS HAD HIM AT ODDS WITH MURDOCH FOR YEARS, AND THE WHITE SOX JERRY REINSDORF.
<P>
THE DODGERS HAD BEEN OWNED BY THE O'MALLEY FAMILY SINCE 1950, WHEN THE TEAM WAS STILL IN BROOKLYN.
<P>
A RECORD 350-MILLION DOLLARS WAS THE PRICE TAG FOR THE DODGERS AND THEIR PROPERTIES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
FINALLY TO GOLF, AND THE PGA TOUR JUST CAN'T SEEM TO SHAKE EL NINO.
<P>
NOT EVEN IN ORLANDO, FLORIDA, FOR THE PLAYING OF ARNOLD PALMER'S BAY HILL INVITATIONAL.     
<P>
ROBERT DAMRON GREW UP ON THIS COURSE, LITERALLY. HIS FAMILY OWNS A HOME ON THE 10TH GREEN.
<P>
NICE APPROACH AT 17, HE'D GET TO 7-UNDER.
<P>
THEN DAMRON WILL THE SAND SAVE AT 17.
<P>
HE'S THE CLUBHOUSE LEADER, BUT THE RAINS CAME. NOT EVEN HALF THE FIELD COMPLETED THEIR 1ST ROUND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140fort ord planting>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>fort ord planting</H3><BR>
SOME LOCAL KIDS ARE WORKING TO RESTORE SOME VALUABLE LAND. THAT WAS ERODED AWAY BY TWO SEPARATE NATURAL DISASTERS.
<P>
LAST YEAR YOU MAY REMEMBER.FIRE RACED THROUGH  THE MUDHEN LAKE AREA OF FORT ORD.
<P>
THE AREA WAS STRIPPED OF ALL VEGETATION.
<P>
THEN EL NINO CAME ALONG.WIPING OUT WHAT LITTLE WAS LEFT.
<P>
THANKS TO MORE THAN 300 KIDS AND THE WATERSHED INSTITUTE AT C-S-U-M-B.THAT LAND WILL BE RESTORED WITH OVER FIVE THOUSAND CALIFORNIA NATIVE PLANTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA home page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
