<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 3/21/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 3/21/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#8PG Team Return-I>PG Team Return-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#20Korea Talks>Korea Talks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114PG Team Return-T>PG Team Return-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Kosovo Update>Kosovo Update</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#11SC Traffic Violations>SC Traffic Violations</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#24Students Arrested>Students Arrested</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120DUI Checkpoint>DUI Checkpoint</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Germany Demo>Germany Demo</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Arroyo Seco dbf>Arroyo Seco dbf</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#9Sea Otter Classic>Sea Otter Classic</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#12SB High Shoot Folo>SB High Shoot Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38Final Four>Final Four</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Morgan Hill Shoot>Morgan Hill Shoot</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#10Hemp Expo SC>Hemp Expo SC</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Prep Basketball>Prep Basketball</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#18NC Storm Cleanup>NC Storm Cleanup</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#19GA Storm Folo>GA Storm Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#116Plane Crash>Plane Crash</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121Skydive Crash>Skydive Crash</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Gallery Gala>Gallery Gala</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=8PG Team Return-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG Team Return-I</H3><BR>
GOOD EVENING.I'M CHERI GYURO.THANKS FOR JOINING US.
<P>
IT'S BEEN AN EXCITING COUPLE OF WEEKS.BUT THINGS ARE WINDING DOWN IN PACIFIC GROVE.
<P>
TODAY, THE NOR-CAL CHAMPION BASKETBALL TEAM RETURNED HOME AFTER THE EXPERIENCE OF A LIFETIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114PG Team Return-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG Team Return-T</H3><BR>
P.G. TEAM PLAYERS ARE ALREADY LOOKING FORWARD TO NEXT YEAR.
<P>
WE'LL HEAR FROM THE BREAKER COACH.LATER ON IN SPORTS WITH KEN ROTHHOUSE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=11SC Traffic Violations>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Traffic Violations</H3><BR>
A POLICE CRACK-DOWN ON HIGHWAY VIOLATIONS NEAR SANTA CRUZ.
<P>
59 DRIVERS WERE CITED FOR SEVERAL DIFFERENT VIOLATIONS ON HIGHWAY ONE.
<P>
POLICE SAY THEY WANT TO REDUCE THE NUMBER TRAFFIC ACCIDENTS.    
<P>
IN 15:58 "Yesterday's endeavor was one of those details that we're calling a CRASH or Collision Reduction ans Safer Highway detail.  Our officers went out and did increased patrols and enforcement action along state route one." OUT 16:13
<P>
OFFICERS SAY 56 OF THE CITATIONS HAD COLLISION POTENTIAL. INCLUDING SPEEDING. FOLLOWING TOO CLOSELY. RIGHT OF WAY VIOLATIONS. AND FAILURE TO OBEY TRAFFIC LIGHTS OR STOP SIGNS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120DUI Checkpoint>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>DUI Checkpoint</H3><BR>
POLICE IN SALINAS HAVE A SOBRIETY CHECKPOINT SET UP TONIGHT IN SALINAS. AND IT'S ONE WITH A "SOBERING" MESSAGE.
<P>
THE CHECKPOINT FEATURES A DISPLAY  INCLUDING A WRECKED CAR. AND A STUDENT PORTRAYING  A DRUNK DRIVER.
<P>
THE CHECKPOINT ALSO HONORS THE MEMORY OF A LOCAL MAN WHO WAS KILLED BY A DRUNK DRIVER.
<P>
TONIGHT WOULD HAVE BEEN ERICK SCOTT SMITHSON'S  21st BIRTHDAY.   
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Arroyo Seco dbf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Arroyo Seco dbf</H3><BR>
THE BODY OF A GREENFIELD MAN. MISSING FOR ALMOST TWO WEEKS.IS FOUND FLOATING IN A LAKE AT ARROYO SECO.
<P>
34-YEAR-OLD ROBERTO HERNANDEZ DISAPPEARED MARCH 9TH. WHILE ON A FISHING TRIP.
<P>
HIS BODY WAS DISCOVERED BY FISHERMEN AT ABBOT LAKE THIS MORNING.
<P>
POLICE SAY. THEIR INVESTIGATION CONTINUES. BUT  AT THIS TIME. THEY DON'T SUSPECT FOUL PLAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=12SB High Shoot Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SB High Shoot Folo</H3><BR>
A SAN BENITO HIGH STUDENT REMAINS IN THE HOSPITAL. AFTER BEING SHOT ON CAMPUS YESTERDAY.
<P>
ABOUT A DOZEN STUDENTS. TEACHERS. AND PARENTS WERE AT THE AG BARN. WHEN SEVERAL SHOTS WERE HEARD FROM BEHIND THE SCHOOL.
<P>
SHERIFF'S DEPUTIES SAY THEY BELIEVE THE GUNFIRE CAME FROM SOMEONE TARGET-SHOOTING BY THE SAN BENITO RIVER.
<P>
SCHOOL OFFICIALS AND COUNSELORS SPENT MUCH OF YESTERDAY AFTERNOON DEALING WITH REACTIONS TO THE INCIDENT.
<P>
IN:40 "They met with the students who were at the ag facility with the young man who was shot.  They met with students on Friday, immediately afterwards, within 10 minutes and thru the noon hour, and they will be available to visit classrooms on Monday to talk to his classmates through the course of the day to assess the situation." OUT 1:00
<P>
THE 16-YEAR-OLD BOY UNDERWENT SURGERY LAST NIGHT.
<P>
HE'S LISTED IN CRITICAL, BUT STABLE CONDITION AT STANFORD MEDICAL CENTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=112Morgan Hill Shoot>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Morgan Hill Shoot</H3><BR>
AN UNUSUAL STORY FROM MORGAN HILL.
<P>
POLICE SAY THEY ARRESTED 20-YEAR-OLD ALVIN REYNOLDS OF GILROY FOLLOWING A DISTURBANCE OUTSIDE A LIQUOR STORE.
<P>
POLICE NOTICED HE LOOKED PALE AND SENT HIM TO THE HOSPITAL.
<P>
REYNOLDS WAS RELEASED BACK IN POLICE CUSTODY.BUT CONTINUED TO COMPLAIN OF PAIN.
<P>
PARAMEDICS WERE CALLED.AND THEY FOUND A "BULLET" IN HIS CHEST.
<P>
22-YEAR-OLD ANTONIO CALDERON OF MORGAN HILL WAS ARRESTED ACCUSED OF SHOOTING REYNOLDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=10Hemp Expo SC>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hemp Expo SC</H3><BR>
IT'S A MATERIAL WITH AN UNEVEN REPUTATION. AND IT'S ON DISPLAY IN SANTA CRUZ THIS WEEKEND.
<P>
IT'S THE "SANTA CRUZ INDUSTRIAL HEMP EXPO". WHERE OVER SEVENTY VENDORS ARE DISPLAYING PRODUCTS RANGING  FROM MEDICINE AND CLOTHING. TO CARPETING AND PAINT.
<P>
ORGANIZERS  ARE HOPING.  THE HEMP EXPO WILL PROMOTE THE MANY USES FOR A PRODUCT THAT MANY PEOPLE DON'T KNOW ABOUT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=18NC Storm Cleanup>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NC Storm Cleanup</H3><BR>
CLEANUP IS UNDERWAY IN NORTH CAROLINA.WHERE A DEADLY TORNADO TOUCHED DOWN FRIDAY. 
<P>
TWO PEOPLE WERE KILLED AND 27 INJURED.WHEN THE 
<P>
TORNADO STRUCK. 
<P>
THE BUSINESS DISTRICT OF STONEVILLE IS DEVASTATED.
<P>
MORE THAN 50 HOMES AND OTHER BUILDINGS WERE DAMAGED OR DESTROYED. 
<P>
NORTH CAROLINA'S GOVERNOR HAS DECLARED ROCKINGHAM COUNTY A DISASTER AREA.AND ASKED FOR FEDERAL AID. 
<P>
DAMAGE ESTIMATES ARE IN THE MILLIONS OF DOLLARS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=19GA Storm Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>GA Storm Folo</H3><BR>
RESIDENTS OF NORTHEAST GEORGIA ARE PICKING UP THE PIECES AFTER FRIDAY'S DEADLY TORNADO THAT KILLED  11 PEOPLE AND INJURED MORE THAN 80. 
<P>
THE TORNADO DEMOLISHED A TEN MILE STRETCH OF LAND.
<P>
41 HOUSES.AND 29 MOBILE HOMES WERE DESTROYED.
<P>
OFFICIALS ESTIMATE THE DAMAGE IN THE MILLIONS OF DOLLARS. 
<P>
A STATE OF EMERGENCY HAS ALSO BEEN DECLARED FOR FIVE GEORGIA COUNTIES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=116Plane Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Plane Crash</H3><BR>
FOUR PEOPLE ARE DEAD AFTER THEIR PRIVATE PLANE CRASHES NEAR A RESIDENTIAL AREA IN INDIANA. 
<P>
POLICE SAY THE TWIN-ENGINE BEECHCRAFT BONANZA WENT DOWN.ON ITS WAY FROM KENTUCKY TO ILLINOIS. 
<P>
A WITNESS SAYS HE SAW THE PLANE NOSE-DIVE INTO THE GROUND.THEN HEARD AN EXPLOSION. 
<P>
AUTHORITIES SAY IT'S NOT CLEAR IF THE PLANE CAUGHT FIRE IN THE AIR OR AFTER IT CRASHED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121Skydive Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Skydive Crash</H3><BR>
SIX PEOPLE ARE KILLED.AFTER A SMALL PLANE CRASHES JUST SHORT OF THE KANSAS CITY AIRPORT. 
<P>
OFFICIALS SAY THE PLANE WAS CARRYING MEMBERS OF THE GREATER KANSAS CITY SKYDIVING CLUB. 
<P>
WITNESSES SAY THEY SAW SMOKE AND FLAMES COMING FROM THE PLANE BEFORE IT CRASHED. 
<P>
THE PILOT REPORTED AN ELECTRICAL EMERGENCY SHORTLY AFTER TAKEOFF FROM MISSOURI. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=20Korea Talks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Korea Talks</H3><BR>
THE FIRST ROUND OF NEW TALKS DESIGNED TO BRING PERMANENT PEACETO NORTH AND SOUTH KOREA ENDED WITHOUT MUCH PROGRESS  
<P>
THE UNITED STATES AND CHINA WERE AMONG THE FOUR NATIONS INVOLVED. 
<P>
CHINA'S FOREIGN MINISTER SAYS THE FOUR SIDES WILL CONTINUE WORKING TO KEEP THE PROCESS ALIVE. 
<P>
THE HEAD OF THE U-S DELEGATION BLAMED NORTH KOREA FOR THE LACK OF PROGRESS.ACCUSING THE NORTH KOREAN'S OF STONEWALLING. 
<P>
BUT WASHINGTON REMAINS COMMITTED TO THE PEACE PROCESS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Kosovo Update>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kosovo Update</H3><BR>
CONTROVERSY IN YUGOSLAVIA.
<P>
ETHNIC ALBANIANS WILL BE ELECTING A PRESIDENT AND PARLIAMENT TOMORROW IN KOSOVO. 
<P>
THIS.DESPITE STRONG DISAPPROVAL BY THE INTERNATIONAL COMMUNITY.  
<P>
THERE WAS ALSO SOME SERIOUS OUTBREAKS OF ELECTION-RELATED VIOLENCE. 
<P>
SERBIA HAS ALREADY SIGNALED ITS REFUSAL TO RECOGNIZE ANY NEW GOVERNMENT.CALLING THE ELECTION ILLEGAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=24Students Arrested>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Students Arrested</H3><BR>
IN A RELATED STORY. SERB AUTHORITIES THREW SIX AMERICANS IN THE SLAMMER.FIVE ARE COLLEGE STUDENTS FROM SAN FRANCISCO.
<P>
APARENTLY, THEY FAILED TO REGISTER THEIR PRESENCE IN YUGOSLAVIA.
<P>
FIVE AMERICANS WITH THE SAN FRANCISCO-BASED GROUP PEACEWORKERS AND AN AMERICAN JOURNALIST WERE ARRESTED EARLY TODAY AND SENTENCED TO TEN DAYS IN JAIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Germany Demo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Germany Demo</H3><BR>
^NUCLEAR WASTE^ IS THE CENTER OF CONTROVERSY IN GERMANY TODAY.
<P>
THOUSANDS PROTESTED THE SHIPMENT OF 60 TONS OF NUCLEAR WASTE TO A STORAGE SITE NEAR THE DUTCH BORDER. 
<P>
SOME PROTESTERS CHAINED THEMSELVES TO THE RAILS.TRYING TO STOP THE TRAIN CARRYING THE WASTE.  
<P>
ONE ACTIVIST EVEN CEMENTED HIMSELF TO THE TRACKS. 
<P>
THE TRAIN REACHED ITS DESTINATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=9Sea Otter Classic>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sea Otter Classic</H3><BR>
IT'S RACING, RIDING, SKATING FUN.THE ANNUAL SEA OTTER CLASSIC AT LAGUNA SECA BEGAN THIS MORNING.
<P>
AND THERE'S TOUGH COMPETITION WITH MOUNTAIN BIKE RACING.B-M-X RACING AND IN-LINE SKATING.
<P>
THE RACES ARE GREAT ENTERTAINMENT FOR THE FAMILY.
<P>
THESE TWIN SISTERS SAY THEY LOVE TO CHALLENGE EACH OTHER.
<P>
" we push each other.we kind of like that.it's like that's my sister.i puch her she pushed me.it's really neat."
<P>
THE SEA OTTER CLASSIC CONTINUES TOMORROW.
<P>
ORGANIZERS SAY ALL THE PROFITS BENEFIT LOCAL CHARITIES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38Final Four>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Final Four</H3><BR>
FOLKS LOST SOME "BIG" POINTS ON THEIR BRACKETS TODAY.
<P>
UTAH IS KNOWN FOR SENDING STUDENTS TO DO MISSIONARY WORK, BUT TODAY VS. THE DEFENDING NATIONAL CHAMPION ARIZONA WILDCATS, THE UTES WERE ON A MISSION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
NOW TOMORROW STANFORD GETS ITS CHANCE TO ADVANCE TO THE FINAL FOUR FOR THE FIRST TIME SINCE 1942.
<P>
THE CARDINAL WILL FACE JIM HARRICK'S CINDERELLA RHODE ISLAND TEAM.
<P>
NOW WITH THEIR WIN OVER PURDUE LAST NIGHT, STANFORD HAS BEEN CRITISIZED A LITTLE, FOR THEIR VERY PHYSICAL PLAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Prep Basketball>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Prep Basketball</H3><BR>
THE PACIFIC GROVE BREAKERS WON THEIR LEAGUE CHAMPIONSHIP, THEIR C.C.S. CHAMPIONSHIP, AND THE NORTHERN CALIFORNIA CHAMPIONSHIP.
<P>
AND EVEN THOUGH THEY FAILED TO WIN THE STATE TITLE YESTERDAY, THEY DID WIN OUR HEARTS.
<P>
THE GAME WAS PLAYED AT THE ARCO ARENA, HOME TO THE NBA'S SACRAMENTO KINGS.
<P>
A GOOD PORTION OF THE CENTRAL COAST WAS THERE.
<P>
VERBUM DEI IS COACHED BY DAVID GREENWOOD, WHO STARRED AT UCLA AND IN THE NBA.
<P>
TODD BULLER DID A GREAT JOB WITH THE BREAKERS.
<P>
VERBUM DEI IS KNOWN AS A BASKETBALL FACTORY IN LOS ANGELES, BUT THE BREAKERS WEREN'T INTIMINDATED.
<P>
COACH BULLER THOUGHT THE PLAY OF MARLON PALMER, WHO LED THE EAGLES WITH 21 POINTS WAS THE KEY.
<P>
MANY THOUGHT THIS GAME WOULD BE A BLOWOUT. BUT VERBUM DEI NEEDED TO HIT THEIR FOUL SHOTS LATE, TO HOLD ON TO A 59 TO 50 VICTORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO THE ICE, AND TODAY THE SHARKS HOST A SLUMPING COLORADO AVALANCHE.
<P>
BUT THE DIVISION LEADERS LOOK ANYTHING BUT SLUGGISH IN SAN JOSE THIS AFTERNOON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
TO GOLF, AND THANKS TO EL NINO, IT TOOK 2-DAYS TO COMPLETE THE FIRST ROUND OF THE BAY HILL INVITATIONAL.
<P>
BUT AFTER TODAY'S 2ND ROUND, ITS OBVIOUS THAT SUNDAY'S FINAL 36-HOLES COULD PRODUCE SOME OF THE BEST OF GOLF OF 1998.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
FINALLY TO SPRING TRAINING, WHERE THE A'S HAVE BEEN PLAYING BETTER THAN EXPECTED.
<P>
TODAY OAKLAND TAPS THE ROCKIES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Gallery Gala>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gallery Gala</H3><BR>
A NEW ART GALLERY OPENS ITS DOORS IN HOLLISTER.AND A WELL KNOWN LOCAL ARTIST IS THE FIRST TO SHOW HIS WORK.
<P>
DUTCH-BORN PAINTER PETER TEEKAMP IS OPENING THE "TEEKAMP GALLERY" WITH A SPECIAL CELBRATION TONIGHT.
<P>
THE SELF-TAUGHT ARTIST IS KNOWN FOR A STYLE FEATURING FANTASY. REALISM. SURREALISM. AND SYMBOLISM.
<P>
IN 27:35  "It's an emotional experience for me to see my whole life floating back in a split second.  It's 25 years of work. that's a lot of paint brushes.  OUT 27:48
<P>
A SPECIAL FEATURE OF THE OPENING IS THE DISPLAY OF A WORK ENITLED "PORTRAIT OF AMANDA". PAINTED FOR A WOMAN WHO LOST HER CHILD AT BIRTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
