<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (g/Sun), Sunday, 3/22/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (g/Sun), Sunday, 3/22/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Russell Rd. Fatal>Russell Rd. Fatal</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Confederate General>Confederate General</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Salina DUI numbers>Salina DUI numbers</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Sphinx>Sphinx</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Cesar Chavez Ann.>Cesar Chavez Ann.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39Stanford>Stanford</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Missionaries>Missionaries</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Pa. Fatal Fire>Pa. Fatal Fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Ca. Cement Body>Ca. Cement Body</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Clinton/Africa>Clinton/Africa</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Racing>Racing</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#104Plane Crash>Plane Crash</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Oscar Bleachers>Oscar Bleachers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Boat Rescue>Boat Rescue</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=108Russell Rd. Fatal>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Russell Rd. Fatal</H3><BR>
GOOD EVENING. I'M CHERI GYURO. THANKS FOR JOINING US.
<P>
ONE MAN IS DEAD TONIGHT.ANOTHER: IN THE HOSPITAL AFTER AN EARLY MORNING ACCIDENT ON HIGHWAY 1-0-1.
<P>
IT HAPPENED JUST SOUTH OF RUSSELL ROAD. 
<P>
CALIFORNIA HIGHWAY PATROL OFFICERS SAY A VAN TRAVELING SOUTH-BOUND WAS REAR-ENDED BY A FAST-MOVING TOYOTA.
<P>
THE VAN OVERTURNED. AND THE DRIVER. VICTOR ESCOBOSO OF CHUALAR. WAS INJURED.
<P>
THE TOYOTA VEERED ACROSS BOTH LANES OF TRAFFIC. AND CRASHED THROUGH A FENCE.
<P>
IN 10:09     "The car, upon the initial officers' responding to the scene and their arrival. the car was so far out of the way of the initial impact. it wasn't apparant.  It wasn't visible during the hours of darkness and was found later on. "  OUT 10:21
<P>
THE DRIVER. 50-YEAR-OLD  JAMES ERKMAN OF SALINAS WAS PRONOUNCED DEAD AT THE SCENE.
<P>
THE CRASH IS UNDER INVESTIGATION BY THE HIGHWAY PATROL.
<P>
OFFICERS SAY ALCOHOL MAY BE INVOLVED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Salina DUI numbers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salina DUI numbers</H3><BR>
SALINAS POLICE ARREST HALF A DOZEN PEOPLE LAST NIGHT FOR DRUNK DRIVING.
<P>
IT WAS PART OF A SOBRIETY CHECKPOINT SET UP AT NORTH MAIN IN SALINAS BETWEEN 8PM AND 12 AM.
<P>
THE ROAD BLOCK FEATURED A DISPLAY OF A WRECKED CAR AND A STUDENT PORTRAYING A DRUNK DRIVER.
<P>
POLICE OFFICERS SAY ALL SIX PEOPLE ARRESTED LAST NIGHT HAD A SOBER PERSON WITH THEM IN THE PASSENGER SEAT.
<P>


<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Cesar Chavez Ann.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cesar Chavez Ann.</H3><BR>
THOUSANDS GATHER IN SALINAS TODAY.TO REMEMBER A MAN WHO FOUGHT FOR FARMWORKERS RIGHTS.
<P>
THESE FOLKS ARE CELEBRATING THE UPCOMING BIRTHDAY AND DEATH OF CESAR CHAVEZ.WHO FOUNDED THE U-F-W.
<P>
ASIDE FROM MUSIC AND DANCING.CHAVEZ WAS REMEMBERED FOR HIS STRUGGLE TO FIGHT FOR JUSTICE.
<P>
"it give us lots of pride..recognizes what he's done.we continue to give for what he sacrificed and the changes he brought to farmworkers."    
<P>
IN ABOUT TWO WEEKS CHAVEZ WOULD HAVE BEEN 71 YEARS OLD.
<P>
NEXT MONTH MARKS THE FIFTH ANNIVERSARY OF HIS DEATH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114Missionaries>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Missionaries</H3><BR>
THE MORMAN CHURCH SAYS ITS PRAYERS HAVE BEEN ANSWERED.
<P>
TWO KIDNAPPED MISSIONARIES ARE RELEASED FROM RUSSIA. 
<P>
ANDREW PROPST AND TRAVIS TUTTLE WERE ABDUCTED IN SOUTHERN RUSSIA WEDNESDAY. 
<P>
A 300-THOUSAND-DOLLAR RANSOM WAS NOT PAID. 
<P>
RUSSIAN POLICE SAY THE TWO MORMONS HAVE A FEW BRUISES.BUT ARE IN GOOD CONDITION. 
<P>
THE RELEASE COMES AS WELCOME NEWS TO LOCAL MORMAN CHURCH LEADERS.
<P>
IN 8:37 "We have 60, 000 out there and very few instances of bad things happening." OUT 8:42  IN 9:16 "They go forth on their own expense and on their own timw to send the message. and it's done very quietly, kindly, and very spiritually." OUT 9:25
<P>
SO FAR. THERE'S NO INFORMATION ON THE KIDNAPPERS.
<P>
THE U.S. EMBASSY IS HELPING WITH THE INVESTIGATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Pa. Fatal Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pa. Fatal Fire</H3><BR>
ELEVEN PEOPLE ARE KILLED AFTER FIRE RIPS THROUGH A CABIN IN PENNSYLVANIA.
<P>
STATE POLICE SAY THE FIRE BROKE OUT AT 5:30 THIS MORNING AT A CAMP ABOUT 20 MILES FROM STATE COLLEGE.
<P>
THE STRUCTURE WAS COMPLETELY DESTROYED. 
<P>
NO SURVIVORS HAVE BEEN FOUND.
<P>
SOME OF THE VICTIMS HAVE BEEN IDENTIFIED AS HIGH SCHOOL STUDENTS FROM LINE MOUNTAIN HIGH SCHOOL. ABOUT 30 MILES FROM THE STATE CAPITAL OF HARRISBURG.
<P>
THE CAUSE OF THE FIRE IS STILL UNDER INVESTIGATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Ca. Cement Body>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ca. Cement Body</H3><BR>
A GREUSOME DISCOVERY IN SOUTHERN CALIFORNIA.
<P>
A RESIDENT IN LA HABRA  FOUND A CEMENT BLOCK WITH BLOOD ON IT YESTERDAY.
<P>
AN OFFICER SEARCHING FOR MORE EVIDENCE FOUND THAT THE CEMENT BLOCK HAD THE BODY OF A 12-YEAR-OLD BOY INSIDE.
<P>
HE ALSO FOUND ANOTHER BLOCK CONTAINING BODY PARTS A HALF-MILE AWAY.
<P>
THE BOY HAS BEEN IDENTIFIED AS JUAN DELGADO WHO WAS REPORTED MISSING LAST THURSDAY.
<P>
SEVEN PEOPLE HAVE BEEN ARRESTED FOR DELGADO'S MURDER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Clinton/Africa>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Africa</H3><BR>
PRESIDENT CLINTON HAS LEFT WASHINGTON.AND HIS RECENT CONTROVERSIES.  BEHIND. 
<P>
THE FIRST FAMILY BEGAN THEIR JOURNEY TO AFRICA EARLY THIS EVENING. 
<P>
PRESIDENT CLINTON WILL SPEND 12 DAYS TRAVELING ACROSS THE CONTINENT.
<P>
IT'S HIS FIRST VISIT TO AFRICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=104Plane Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Plane Crash</H3><BR>
THREE PEOPLE ARE DEAD.ALMOST ONE HUNDRED INJURED.AFTER A PHILIPPINE AIRLINER CRASHES INTO A ROW OF HOUSES.  
<P>
THE AIRCRAFT OVER-FLEW THE RUNWAY WHILE LANDING AT AN AIRPORT ABOUT 300-MILES SOUTHEAST OF MANILA. 
<P>
THE PLANE SKIDDED ON ITS BELLY AND STOPPED NEAR A HIGHWAY. 
<P>
THE THREE PEOPLE KILLED WERE PEDESTRIANS.
<P>
APARENTLY THEY WERE TRAPPED UNDER THE PLANE WHEN IT LANDED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Boat Rescue>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Boat Rescue</H3><BR>
A DESPERATE STRUGGLE AT SEA.
<P>
RESCUE WORKERS TRY TO SAVE CREW MEMBERS FROM TWO CHINESE FISHING BOATS.SINKING OFF THE COAST OF SOUTH KOREA. 
<P>
THE BOATS WERE VICTIMS OF HEAVY SEAS.
<P>
18 CREW MEMBERS ARE MISSING.
<P>
NINE OTHERS STRUGGLED TO STAY ABOVE WATER AS THEY WERE THROWN INTO THE CHOPPY SEA. 
<P>
HUGE WAVES AND COLD WATER TEMPERATURES HAMPERED RESCUE EFFORTS TO CATCH THE VICTIMS. 
<P>
MIRACULOUSLY.THE NINE CREW MEMBERS WERE BROUGHT TO DRY LAND. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Confederate General>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Confederate General</H3><BR>
A SIGNIFICANT PART OF CIVIL WAR HISTORY WAS LAID TO REST IN VIRGINIA TODAY. 
<P>
IN FRONT OF HUNDREDS OF ON-LOOKERS.THE REMAINS OF LASALLE CORBELL PICKETT WERE BURIED ALONG SIDE HER HUSBAND.
<P>
SHE WAS THE WIFE OF CONFEDERATE GENERAL GEORGE E. 
<P>
PICKETT.  FAMOUS FOR LEADING "PICKETT'S CHARGE" DURING THE BATTLE OF GETTYSBURG. 
<P>
SALLY  PICKETT OUTLIVED HER HUSBAND BY MORE THAN FIFTY YEARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Sphinx>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sphinx</H3><BR>
EGYPTIANS AND TOURISTS ARE CELEBRATING THE FESTIVAL OF THE SPHINX AND THE ARRIVAL OF SPRING.
<P>
THE 45-HUNDRED YEAR-OLD SPHINX SEES THE SUN SET DIRECTLY BEHIND IT ON THE VERNAL AND AUTUMNAL EQUINOXES.WHICH FALL ON MARCH 21ST AND SEPTEMBER 21ST. 
<P>
EXPERTS SAY THIS PROVES THE PLACEMENT OF THE SPHINX IS NO RIDDLE. AND IT SERVES AN ASTRONOMICAL AS WELL AS A RELIGIOUS PURPOSE. 
<P>
THE WEATHERED SCULPTURE WILL RE-OPEN SOON, AFTER TEN YEARS OF RESTORATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39Stanford>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stanford</H3><BR>
IN 1942, STANFORD WON THE NCAA TOURNAMENT. BUT FOR THE NEXT 47-YEARS, THEY COULDN'T EVEN GET IN THE TOURNAMENT.
<P>
ALL THAT CHANGED THOUGH WHEN MIKE MONTGOMERY SHOWED UP ON THE FARM. IN HIS 11-YEARS AT STANFORD, THE CARDINAL HAVE PLAYED IN 6-NCAA'S.
<P>
AND TODAY MONTY GETS HIS TEAM TO THE FINAL FOUR, A TEAM THAT DOES NOT HAVE A SENIOR IN THE STARTING LINEUP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
IT ONLY SEEMS AS THOUGH STANFORD COULD BEAT THE WARRIORS.
<P>
BUT WE ALL KNOW HOW GREAT THE NBA PLAYERS ARE, ALTHOUGH ITS HARD TO USE THE WORDS WARRIORS AND GREAT IN THE SAME SENTENCE THESE DAYS.
<P>
TODAY GOLDEN STATE VISITS ORLANDO.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO THE ICE, AND AFTER LOSING AT HOME YESTERDAY VS. COLORADO, THE SHARKS HIT THE ROAD TODAY, TO PLAY PHOENIX.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
THE DREAM THREESOME OF TIGER WOODS, DAVIS LOVE, AND ERNIE ELS PLAYING THE FINAL 36-HOLES OF THE BAY HILL INVITATIONAL TOGETHER, ON PAPER LOOKED FANTASTIC.
<P>
BUT IN REALITY, THE 6 FOOT 4 ELS, STANDS HEAD AND SHOULDERS ABOVE THE PACK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Racing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Racing</H3><BR>
FINALLY TO RACING, AND WE'LL CHECK-IN WITH THE NASCAR CROWD. WITH THE RUNNING OF THE TRANSOUTH 400.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Oscar Bleachers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Oscar Bleachers</H3><BR>
SOME CALL IT THE SUPERBOWL OF ENTERTAINMENT.
<P>
LOYAL BLEACHER FANS ARE BEGINNING THE COUNTDOWN TO THE 70TH ANNUAL ACADEMY AWARDS.
<P>
THE BIG NIGHT IS ONLY A DAY AWAY.
<P>
MORE THAN ONE THOUSAND FANS STAKED THEIR SPOT AT THE HISTORIC SHRINE AUDITORIUM. 
<P>
TO HELP EASE THE ANTICIPATION. KENTUCKY FRIED CHICKEN EMPLOYEES PASSED OUT SURVIVAL KITS.  TO HELP FANS WITH THE LONG WAIT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=../main.asp>Return to KCBA Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
