<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 4/11/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 4/11/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#7Tax Weekend>Tax Weekend</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Fire Weapon>Fire Weapon</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#8SC Rape Folo>SC Rape Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#18George Michael>George Michael</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#9County Curfew>County Curfew</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38Masters>Masters</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#10Passover Seder>Passover Seder</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Easter Eggs Mty.>Easter Eggs Mty.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Pope Vigil>Pope Vigil</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#17Australia Storms>Australia Storms</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#99Great 18>Great 18</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Britain Floods>Britain Floods</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106Japan Festival>Japan Festival</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121Iran Quake>Iran Quake</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123Cherry Festival>Cherry Festival</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=7Tax Weekend>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tax Weekend</H3><BR>
GOOD EVENING.I'M CHERI GYURO.THANKS FOR JOINING US.
<P>
TIME IS TICKING AWAY.
<P>
ONLY FOUR MORE DAYS UNTIL THE TAX DEADLINE.
<P>
IF YOU'RE SCRAMBLING TO GET IT DONE.THERE ARE MANY SERVICES THAT CAN HELP.
<P>
H & R BLOCK CAN ASSIST WITH THE MATH INVOLVED AND FILE RAPID RETURN.
<P>
AND FOR THE ELDERLY OR THOSE WITH  LOWER INCOMES.THERE'S THE ALLIANCE ON AGING.
<P>
"OUR REGULAR INCOME TAX SERVICE IS ALL BIZ WHERAS THESE ARE MORE PERSONAL TAKING TO PERSON."  "PEOPLE WANT RETURNS CHECKED AND IT HELPS THEM FEEL MORE SECURE ABOUT SENDING THEM OUT."
<P>
A NATIONAL STUDY SHOWS THAT MOST AMERICANS AREN'T FILING TAXES THE OLD WAY.
<P>
MOST ARE DOING IT ELECTRONICALY.
<P>
SOME SAY IT'S LESS STRESSFUL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=8SC Rape Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Rape Folo</H3><BR>
AN 11-YEAR-OLD GIRL IS HOME FROM THE HOSPITAL TONIGHT AFTER A GREUSOME ATTACK.    
<P>
COUNTY SHERIFF'S DEPUTIES SAY THE GIRL WAS TAKEN TO A LOCAL BEACH, DRUGGED WITH HEROIN AND REPEATEDLY RAPED BY A MAN AND THREE BOYS.
<P>
SHE WAS DROPPED OFF AT THE METRO CENTER.AND WAS TAKEN TO THE HOSPITAL BY HER PARENTS.
<P>
OFFICIALS SAY SHE WAS RELEASED TODAY.
<P>
THE ADULT CHARGED WITH THE CRIME IS IDENTIFIED AS 18-YEAR-OLD ERNESTO GARCIA OF SANTA CRUZ.HE'S BEHIND BARS.
<P>
THE THREE BOYS ARE ALSO CHARGED WITH THE ATTACK.
<P>
INVESTIGATORS SAY THE GIRL KNEW ONE OF HER ATTACKERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=9County Curfew>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>County Curfew</H3><BR>
THE RESULTS ARE IN FOR MONTEREY COUNTY'S NEW CURFEW ENFORCMENT PROGRAM.
<P>
ACCORDING TO THE MONTEREY COUNTY SHERIFF'S OFFICE. THE FIRST NIGHT OF ENFORCEMENT WAS A SUCCESS.
<P>
BUT ONLY 2 JUVENILES WERE TRANSPORTED HOME BY AUTHORITIES.
<P>
THE NEW RULES REQUIRE TEENS UNDER 18 TO BE IN THEIR HOMES BY TEN P-M. EXCEPT FOR THOSE ACCOMPANIED BY A PARENT OR GUARDIAN. HAVING A PERMISSION SLIP. OR THOSE WHO ARE WORKING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=10Passover Seder>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Passover Seder</H3><BR>
THIS WEEK IS PASSOVER AND TONIGHT HUNDREDS OF LOCALS CELEBRATE IN SALINAS.
<P>
THE HOLIDAY IS ONE OF THE MOST IMPORTANT FOR THE JEWISH COMMUNITY.
<P>
TONIGHT IS THE SECOND NIGHT OF SEDER, WHICH TELLS THE STORY OF THE ISRAELITES EXODUS FROM EGYPT.
<P>
THE SEDER LEADER AT TEMPLE BETHEL TOLD US WHY THE WEEK-LONG HOLIDAY IS SO SPECIAL.
<P>
"THIS IS A PEOPLE THAT IS CELEBRATING FREEDOM, CELEBRATING THE COMING OF SPRING, CELEBRATING LOVE, CELEBRATING SINGING AND FEELING JOY."
<P>
DURING THE SEDER, PARTICIPANTS EAT FOODS, WHICH REPRESENT PASSOVER SYMBOLS. INCLUDING UNLEAVENED BREAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Easter Eggs Mty.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Easter Eggs Mty.</H3><BR>
600 HAPPY CHILDREN PARTICIPATED IN A TRADITIONAL EASTER EGG HUNT.
<P>
PETER RABBIT WAS AT THE MONTEREY COUNTY YOUTH CENTER TODAY.
<P>
HE GAVE AWAY MORE THAN 7-THOUSAND BRIGHTLY COLORED EGGS TO KIDS AND THEIR FAMILIES.
<P>
ORGANIZERS SAY THIS YEAR'S EASTER EGG HUNT WAS A SUCCESS. DESPITE THE RAIN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Pope Vigil>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pope Vigil</H3><BR>
POPE JOHN PAUL THE SECOND BEGINS THE EASTER VIGIL IN VATICAN CITY. 
<P>
HUNDREDS OF CATHOLICS LIT CANDLES AND JOINED A PROCESSION AS THE WORDS.LIGHT OF CHRIST. WERE PRONOUNCED. 
<P>
THE POPE WILL DELIVER THE TRADITIONAL EASTER MESSAGE AT SAINT PETER'S CHURCH TOMORROW MORING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=17Australia Storms>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Australia Storms</H3><BR>
DEADLY STORMS ARE ALSO POUNDING AUSTRALIA.
<P>
THREE PEOPLE DIED.HOMES AND ROADS ARE FLOODING.
<P>
THE EASTER STORMS CAUSED SEVERAL CAR CRASHES ALONG SYDNEY'S HIGHWAYS.
<P>
DRIVERS ABANDONED THEIR CARS ON WATERLOGGED ROADS. 
<P>
SYDNEY RECEIVED MORE THAN 7  AND A HALF INCHES OF RAIN IN TWO DAYS. 
<P>
A MAN. HIS WIFE. AND A CHILD WERE KILLED BY LIGHTNING DURING SEVERE THUNDERSTORMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Britain Floods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Britain Floods</H3><BR>
RECORD SPRING FLOODS HAVE KILLED AT LEAST TWO PEOPLE IN ENGLAND.
<P>
TWO OTHERS ARE REPORTED MISSING IN THE WAKE OF POUNDING RAINS.THE WORST IN FIFTY YEARS. 
<P>
HUNDREDS OF HOMES ARE EMPTY AS PEOPLE BOAT TO HIGHER, DRIER GROUND. 
<P>
TOWN STREETS ARE DEEP STREAMS AFTER RIVERS JUMPED THEIR BANKS. 
<P>
RESCUE WORKERS SAY THE WATER HAS ALREADY CAUSED MILLIONS OF DOLLARS IN DAMAGES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121Iran Quake>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Iran Quake</H3><BR>
AN EARTHQUAKE ROCKS EASTERN IRAN. KILLING 12 PEOPLE AND INJURING SEVERAL OTHERS. 
<P>
THE QUAKE HAD A MAGNITUDE OF 5-POINT-9.
<P>
IT STRUCK NEAR THE AFGHAN BORDER. 
<P>
20 STRONG AFTERSHOCKS HAVE ALREADY HIT THE REGION.
<P>
SEISMOLOGISTS PREDICT MORE TREMORS. 
<P>
MORE THAN 15-HUNDRED PEOPLE ARE HOMLESS. 
<P>
RESCUERS ARE WORKING FRANTICALLY TO PITCH TENTS AND DISTRIBUTE FOOD. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Fire Weapon>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fire Weapon</H3><BR>
FIRE FIGHTERS IN SOUTHERN CALIFORNIA HAVE A NEW WEAPON TO USE FOR THE RAPIDLY APPROACHING FIRE SEASON.
<P>
THE TOOL IS A WATER CANNON MOUNTED ON A HELICOPTER AND IT'S EXPECTED TO HELP SAVE HOMES DURING LARGE WILDLAND FIRES.
<P>
THE LATEST PIECE OF TECHNOLOGY FOCUSES THOUSANDS OF GALLONS OF WATER ON A SPECIFIC SPOT.
<P>
FIRE OFFICIALS SAY THE CANNON CAN DELIVER UP TO 30-THOUSAND GALLONS OF WATER. OR FIRE RETARDANT PER HOUR. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=18George Michael>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>George Michael</H3><BR>
A MUSIC STAR FINALLY TALKS ABOUT HIS RECENT TROUBLES. 
<P>
SINGER GEORGE MICHAEL WAS CHARGED WITH COMMITTING AN UNSPECIFIED "LEWD ACT" IN A PARK  RESTROOM LAST WEEK.
<P>
TODAY MICHAEL TOLD REPORTERS THAT HE WANTS TO APOLOGIZE TO HIS FANS.
<P>
HE SAYS HE PUT HIMSELF IN A STUPID AND VULNERABLE POSITION.AND REVEALED THAT HE'S IN A RELATIONSHIP WITH ANOTHER MAN.
<P>
THE SINGER WAS RELEASED AFTER POSTING 500-DOLLARS BAIL. 
<P>
PROSECUTORS WILL DECIDE WHETHER TO FILE CHARGES NEXT WEEK. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38Masters>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Masters</H3><BR>
FOR THE 1ST TWO ROUNDS.IT LOOKED MORE LIKE A GUSTA WIND THAN AGUASTA NATIONAL.IN FACT.ONLY EIGHT PLAYERS WERE UNDER PAR AFTER 36 HOLES AT THE MASTERS. 
<P>
BUT ROUND THREE WOULD BE IDEAL FOR SCORING WITH 12 PLAYERS FINISHING IN THE 60'S COMPARED TO JUST FOUR IN THE 1ST TWO ROUNDS COMBINED.
<P>
ONE OF THOSE GUYS IN THE 60'S.. A FIVE UNDER 67 FOR THE REIGNING PGA CHAMP. IT HELPS WHEN YOU TAKE THE PUTTER OUT OF THE EQUATION AT AUGUSTA. AN EAGLE FOR LOVE AT 17.
<P>
------------
<P>
HAD A SHARE OF THE LEAD AT ONE POINT. AT NUMBER THREE. HAAS WITH THE PUTTER OFF THE GREEN. AND THIS ONE FINDS THE BOTTOM OF THE CUP FOR BIRDIE. HAAS WITH A 71. HE'S FOUR BACK OF THE LEADER.
<P>
------------
<P>
IS STILL IN THE HUNT FOR HIS FIRST MAJOR. THE LEFTY WITH A 69. AND WITHIN STRIKING DISTANCE.
<P>
------------
<P>
HERE'S YOUR LEADER.  PLAYING STEADY BUT UNSPECTACULAR GOLF. HE FINISHES THE DAY WITH A 71. BUT CHECK OUT THIS APPROACH AT 13. IT ROLLS TO WITHIN A FOOT FOR AN EASY EAGLE. HE'S AT 6-UNDER.
<P>
-----------
<P>
SHOT A 65 IN LAST YEARS 3RD ROUND. HE COULD ONLY MANAGE EVEN PAR TODAY. BUT DON'T COUNT TIGER OUT.
<P>
----------
<P>
OR THIS GUY. JACK NICKLAUS WITH ANOTHER MASTERS MOMENT.  AT 18.THE GOLDEN BEAR WITH THE 25-FOOTER FOR PAR. HE'S STILL GOT IT. NICKLAUS JUST 5-SHOTS BACK. LET'S CHECK THE LEADERBOARD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
THERE'S BEEN A POWER OUTAGE IN SAN FRANCISCO THAT CAN'T BE BLAMED ON EL NINO.
<P>
AFTER FOUR GAMES AT THE STICK.THE GIANTS ARE STILL HOMERLESS ON THEIR CURRENT 9-GAME HOME STAND. AND THE TRIO OF BONDS, KENT AND SNOW HAVE COMBINED FOR JUST ONE HOMER OVERALL THIS SEASON.
<P>
GIANTS TRYING TO MAKE IT TWO IN A ROW OVER  CARDINALS.
<P>
---------
<P>
NO SCORE. TOP OF THE 3RD.  WITH A MISSLE TO LEFT OFF. ST. LOUIS GOES ON TOP 1-ZIP.
<P>
-------
<P>
THE GIANTS TIE THE GAME IN THE BOTTOM OF THE INNING. AFTER A DOUBLE FROM BONDS.  DRIVES IN HIS 12 RUN OF THE SEASON. GAME TIED AT ONE.
<P>
--------
<P>
THE CARDS UNTIE THE GAME IN THE VERY NEXT INNING.  GOING NORTH OF THE BOARDER OFF ESTES. WHO STRUGGLES AGAIN. GIVING UP FIVE RUNS IN 6-PLUS INNINGS.
<P>
----------
<P>
IT'S TIED AT TWO IN THE 7TH.  COMES IN WITH THE BASES LOADED. AND BEANS JORDAN. TO SCORE A RUN.
<P>
----------
<P>
NEXT BATTER.. AND REED WALKS HIM. BRINGING IN ANOTHER RUN.IT'S BIG MAC'S ONE-THOUSANDTH CAREER RBI. CARDS GO ON TO WIN. 7-2 IS THE FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
THE A'S CONTINUE THEIR ROAD TRIP IN THE BIG APPLE.  SWINING.
<P>
-------
<P>
THEN. THE SLIDER TO. AND HE COMES UP EMPTY.
<P>
----------
<P>
PETTITTE LIMITS THE A'S TO ONE RUN IN SIX INNINGS OF WORK AND HE STRIKES OUT SEVEN TO PICK UP HIS FIRST WIN IN THREE STARTS.
<P>
-----------
<P>
MEANTIME.  PROVIDES THE OFFENSE. WITH THE SINGLE OFF  IN THE 3RD. IT SCORES TWO RUNS AS THE YANKEES GO ON TO WIN THEIR 4TH STRAIGHT. FINAL. 3-1 NEW YORK.       
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
THE SHARKS CONTINUE THEIR PLAYOFF HUNT TONIGHT HOSTING THE VANCOUVER CANNUCKS.
<P>
THE TEAL AND BLACK ARE HOT OF LATE. HAVING WON THEIR PAST THREE IN A ROW AND FIVE OF THEIR LAST SEVEN.
<P>
NO TV TONIGHT THOUGH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=99Great 18>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Great 18</H3><BR>
TONIGHT WE DEBUT A NEW GOLF SEGMENT ON KCBA SPORTS. CALLED THE "GREAT 18".
<P>
FOR THE NEXT 18 WEEKS. BRUCE LEWIS AND I WILL FEATURE SOME OF THE MOST CHALLANGING GOLF HOLES ON THE CENTRAL COAST. AND FITTINGLY WE START WITH SAN JUAN OAKS. THE GOLF COURSE CO-DESIGNED BY CURRENT MASTERS LEADER FRED COUPLES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106Japan Festival>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Japan Festival</H3><BR>
IT'S FESTIVAL TIME IN JAPAN.BUT THIS ONE IS FOR MEN ONLY.
<P>
IN THIS MATCH OF STAMINA. MEN TRY TO JUMP ABOARD LOGS AS THEY GO CAREENING DOWN A STEEP HILLSIDE.
<P>
FORTUNATELY. NO ONE WAS HURT DURING THE DAREDEVIL RIDE. 
<P>
LAST YEAR, ONE JAPANESE MAN WAS KILLED WHEN A TREE TRUNK ROLLED OVER HIM. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123Cherry Festival>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cherry Festival</H3><BR>
THOUSANDS OF PEOPLE FROM ALL OVER THE COUNTRY GATHERED IN WASHINGTON D-C TODAY FOR THE ANNUAL CHERRY BLOSSOM FESTIVAL.
<P>
THERE WAS JUST ONE PROBLEM THOUGH. MOST OF THE BLOSSOMS ARE GONE.
<P>
THEY'VE BEEN ABSENT FOR AWHILE NOW. BUT THAT DIDN'T SEEM TO BOTHER ALL OF THE SPECTATORS.
<P>
AFTER ALL THERE WERE PLENTY OF BANDS AND FLOATS TO ENTERTAIN FOLKS ALONG CONSTITUTION AVENUE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
