<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 4/25/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 4/25/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#8PG&E Update-I>PG&E Update-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#116Shuttle>Shuttle</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#9PG&E Update-G>PG&E Update-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#10PG&E Update-T>PG&E Update-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Salinas Fire>Salinas Fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Moss Landing Fire>Moss Landing Fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42NBA Playoffs>NBA Playoffs</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Carbo Feast>Carbo Feast</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Suns>Suns</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Marathon Traffic>Marathon Traffic</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Jaguars>Jaguars</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#20Kevorkian>Kevorkian</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Clash>Clash</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Miss America>Miss America</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#99Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Hillary Questioned>Hillary Questioned</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Mty. H.S. Jazz Closer>Mty. H.S. Jazz Closer</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118Bill at Dinner>Bill at Dinner</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=8PG&E Update-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG&E Update-I</H3><BR>
THE LATEST UPDATE FROM PG&E IS. AS OF THIS HOUR 37,500 PG&E CUSTOMERS HAVE GAS RESTORED TO THEM.
<P>
THAT'S GOOD NEWS TO ALL THOSE WHO'VE BEEN PATIENTLY DOING WITHOUT SINCE WEDNESDAY. BUT THERE ARE STILL 23,000 HOMES AND BUSINESSES WITH *NO* GAS.
<P>
NOT WANTING TO LEAVE THEM OUT IN THE COLD. PG&E TODAY SUPPLIED THEM WITH THEIR MOST DIRE NECESSITY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=9PG&E Update-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG&E Update-G</H3><BR>
FOR SOME. IT WAS LIKE HEARING AGAIN FROM A LONG-LOST FRIEND.
<P>
HOT WATER RETURNED TO THE SANTA CRUZ AREA FOR THE FIRST TIME SINCE WEDNESDAY. AND RESIDENTS FROM SCOTTS VALLEY TO WATSONVILLE FLOCKED TO TEMPORARY SHOWER FACILITIES SET UP AROUND THE COUNTY.
<P>
MEANWHILE. THOUSANDS MORE GOT TO TAKE HOT SHOWERS IN THEIR OWN HOMES TODAY.
<P>
MORE THAN 700 PG&E FIELD REPS CONTINUED GOING HOUSE TO HOUSE FROM MORNING TILL NIGHT. RESTORING GAS SERVICE TO CUSTOMERS DELIGHTED TO SEE THEM.
<P>
DESPITE THE INCONVENIENCE, MOST RESIDENTS WERE TAKING THE GAS PROBLEMS IN STRIDE.
<P>
"
<P>
=======BUTT TO=====
<P>
EVEN AS THEIR CREWS WENT FROM HOUSE TO HOUSE. PG&E MANAGERS CALLED A PRESS CONFERENCE THIS AFTERNOON. TO ANNOUNCE A NEW TIME TABLE FOR FULL RESTORATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=10PG&E Update-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG&E Update-T</H3><BR>
SO TOMORROW NIGHT IS NOW THE NEW TARGET DATE FOR PG&E TO RESTORE GAS TO EVERYONE IN THE COUNTY.
<P>
IN THE MEANTIME. TWO SHOWER FACILITIES WILL REMAIN OPEN ALL DAY TOMORROW. TO FIND OUT WHERE, YOU CAN CALL PG&E'S HOTLINE NUMBER AT 1-800-PGE-5000.
<P>
CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Salinas Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas Fire</H3><BR>
A FIRE TONIGHT IN SALINAS DESTROYS A RADIO BROADCASTING FACILITY.
<P>
FIRE INVESTIGATORS SAY IT BROKE OUT AROUND 7 THIS EVENING ACROSS THE STREET FROM EDWARD ALVAREZ HIGH SCHOOL.
<P>
THE BUILDING.IS GUTTED.
<P>
ACCORDING TO FIREFIGHTERS.THE STRUCTURE HAD BEEN THE SCENE OF PREVIOUS VANDALISM.
<P>
THEY SAY TONIGHT'S BLAZE IS SUSPICIOUS.
<P>
NO ONE WAS INJURED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Moss Landing Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Moss Landing Fire</H3><BR>
FIRE INVESTIGATORS ARE TRYING TO FIND OUT WHAT CAUSED A LOCAL RESTAURANT TO BURN TO THE GROUND.
<P>
SKIPPERS CAFE ALONG HIGHWAY ONE IN MOSS LANDING WENT UP IN FLAMES AROUND 2:30 THIS MORNING.
<P>
NORTH MONTEREY COUNTY FIREFIGHTERS SAY IT TOOK ALMOST AN HOUR FOR MORE THAN A DOZEN AUTHORITIES AND THREE ENGINES TO PUT OUT THE BLAZE.
<P>
DAMAGE TO THE POPULAR SEAFOOD RESTAURANT IS ESTIMATED AT 125-THOUSAND DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=112Carbo Feast>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Carbo Feast</H3><BR>
IT'S CARBO LOADING TIME FOR THOSE PREPARING TO RUN IN THE BIG SUR MARATHON.
<P>
EVERY YEAR. ON THE NIGHT BEFORE THE BIG RACE. THOUSANDS OF RUNNERS GATHER AT THE MONTEREY MARRIOTT HOTEL FOR AN ENERGIZING DINNER.
<P>
THEY LOAD UP ON FOODS HIGH IN CARBOHYDRATES. SUCH AS PASTA. POTATOES. RICE AND EVEN BEER.
<P>
A FEAST THAT'S PUMPING UP 70-YEAR-OLD CHARLES STALZAR.
<P>
"THIS IS MY FOURTH ONE HERE AND OF COURSE I'VE RUN SINCE THE LATE 19-60'S BEFORE THEY SOLD RUNNING SHOES. THEY JUST HAD RUNNING KEDS."
<P>
THE MARATHON BEGINS AT HIGHWAY ONE AND RIO ROAD TOMORROW MORNING AT SEVEN.
<P>
THERE WILL ALSO BE WALKING EVENTS. A FIVE-K RUN.  AND A RELAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Marathon Traffic>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marathon Traffic</H3><BR>
A LOT OF FOLKS ARE IN TOWN FOR THE BIG SUR MARATHON.
<P>
RUNNERS. WALKERS. VOLUNTEERS. SUPPORT STAFF. FRIENDS. FAMILY. AND SPECTATORS.
<P>
THAT MEANS A TRAFFIC NIGHTMARE FOR THOSE GETTING TO AND FROM THE RACE.
<P>
THE CALIFORNIA HIGHWAY PATROL EXPECTS VERY HEAVY TRAFFIC ON MOST PENINSULA ROADS THROUGHOUT THIS WEEKEND.ESPECIALLY ON RACE DAY.
<P>
IN:38  "THE TRAFFIC WILL BE CONCENTRATED AROUND THE CARMEL VALLEY, PARTICULARLY AROUND THE CROSSROADS SHOPPING CENTER.  SO WE WOULD ASK PEOPLE THAT DON'T HAVE BUSINESS DOWN THERE AND DON'T WANT TO BE CAUGHT UP IN TRAFFIC OR ACTIVITIES. TO KEEP OUT OF THE AREA." OUT:50
<P>
IN 2:19 "WE EXPECT HEAVY TRAFFIC.  WE'VE GOT A LOT OF CHP PRESENCE OUT THERE. WE HOPE TO MINIMIZE TRAFFIC CONGESTION, BUT WE ASK FOR THE VIEWERS' HELP IN ACCOMPLISHING THAT." OUT 2:26
<P>
C-H-P OFFICERS SAY YOU SHOULD ALLOW PLENTY OF TIME TO GET AROUND TOMORROW.
<P>
OFFICERS REMIND DRIVERS TO RELAX. TAKE IT EASY. AND ENJOY THE DRIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=20Kevorkian>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kevorkian</H3><BR>
THE MAN KNOWN AS DOCTOR DEATH. JACK KEVORKIAN.  IS AT IT AGAIN. 
<P>
A MICHIGAN HOSPITAL SPOKESMAN SAYS. A WOMAN'S BODY WAS LEFT AT THE  HOSPITAL BY TWO PEOPLE. 
<P>
KEVORKIAN COULD BE INVOLVED IN HELPING LUCILLE ALDERMAN DIE FROM AN INTRAVENOUS INJECTION. 
<P>
KEVORKIAN IS DECLINING TO COMMENT ON HER  DEATH. AND HIS ATTORNEY  SAYS HE HAS NO INFORMATION ABOUT THE WOMAN. 
<P>
THE DEATH HAS BEEN RULED A HOMICIDE BY MEDICAL EXAMINERS. 
<P>
THIS IS THE FIFTH ASSISTED SUICIDE ALLEGEDLY ATTENDED BY KEVORKIAN THIS MONTH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Miss America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Miss America</H3><BR>
A FORMER MISS AMERICA APOLOGIZES TO FIRST LADY HILLARY CLINTON FOR A ONE-NIGHT STAND SHE HAD WITH THE PRESIDENT. 
<P>
ELIZABETH WARD GRACEN SAYS SHE HAD A SECRET MEETING WITH MR. CLINTON IN 1983 WHEN SHE WAS 22 YEARS OLD.
<P>
GRACEN SAYS  SHE MET HIM WHILE HE WAS THE GOVERNOR OF ARKANSAS. AND SHE WAS A STRUGGLING ACTRESS ONE YEAR AFTER BEING CROWNED MISS AMERICA.  
<P>


<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Hillary Questioned>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hillary Questioned</H3><BR>
MEANWHILE.THE FIRST LADY SPENT HER DAY BEING  QUESTIONED AGAIN BY WHITEWATER PROSECUTORS. 
<P>
MRS. CLINTON GAVE VIDEOTAPED TESTIMONY THIS AFTERNOON AT THE WHITE HOUSE. 
<P>
SHE'S BEING ASKED ABOUT HER WORK AS A PRIVATE LAWYER FOR A FAILED SAVINGS AND LOAN. 
<P>
IT'S THE SIXTH TIME SINCE JUNE OF 19-94 THAT MRS. CLINTON HAS BEEN QUESTIONED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118Bill at Dinner>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bill at Dinner</H3><BR>
THEY WERE DINNER COMPANIONS AT THE WHITE HOUSE CORRESPONDENTS ASSOCIATION DINNER.
<P>
WELL.SORT OF.
<P>
PAULA JONES. THE WOMAN WHO ACCUSED PRESIDENT CLINTON OF SEXUAL HARASSMENT. SHARED THE SPOTLIGHT WITH THE COMMANDER-IN-CHIEF IN WASHINGTON TONIGHT. 
<P>
HOWEVER.IT WAS FAR FROM A WELCOME RECEPTION. 
<P>
JONES. INVITED BY THE STAFF OF A CONSERVATIVE MAGAZINE.WAS BOOED BY ONLOOKERS.
<P>
DESPITE THE PRESENCE OF A WOMAN STILL SUING HIM.  PRESIDENT CLINTON RECEIVED A VERY WARM RECEPTION FROM THE CROWD.ABOUT THIRTY MINUTES AFTER JONES ARRIVED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=116Shuttle>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Shuttle</H3><BR>
REPAIR EFFORTS UNDERWAY ON BOARD THE SPACE SHUTTLE COLUMBIA. 
<P>
A LIFE SUPPORT SYSTEM THAT REMOVES CARBON DIOXIDE FROM THE SHUTTLE. FAILED LATE LAST NIGHT. 
<P>
NASA SAYS THE ASTRONAUTS AREN'T IN ANY IMMEDIATE DANGER BECAUSE A BACKUP SYSTEM IS WORKING. 
<P>
IF REPAIR EFFORTS FAIL. COLUMBIA WILL HAVE TO RETURN HOME EARLY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
THE GIANTS HAVE BEEN ABOUT AS COLD AS A GREEN BAY WINTER NIGHT. HAVING LOST 7 OF THEIR LAST 8 GAMES.
<P>
FOUR OF THOSE LOSSES COMING AT THE HANDS OF THE MILWUAKEE BREWERS.
<P>
GIANTS GET THINGS GOING IN THE 5TH.  WITH THE SINGLE OFF. IT SCORES. GIANTS UP 1-ZIP.
<P>
-----------
<P>
ON THE VERY NEXT PITCH. DRIVES ONE DEEP TO RIGHT CENTER. IT'LL HIT OFF THE WALL. BERNARD SCORES FROM 1ST. 2-NOTHING GIANTS.
<P>
-----------
<P>
THAT'S ENOUGH FOR  WHO GOES 6-PLUS. GIVING UP JUST 3-HITS. WHILE STRIKING OUT FIVE. THE BULLDOG LOOKING ON.
<P>
---------
<P>
COMES IN TO CLOSE OUT THE GAME. BY RETIRING THE SIDE IN THE 9TH. THE GIANTS WIN 2-1. ENDING A 3-GAME SKID. SAME TWO TEAMS TOMORROW. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
THE A'S CONTINUE THEIR SERIES WITH BALTIMORE WITH CAL RIPKEN HITTING ANOTHER MILESTONE BY PLAYING IN HIS 2-THOUSAND FIVE HUNDREDTH CONSECUTIVE GAME.
<P>
IN CONTRAST. A'S ROOKIE BEN GRIEVE HAS THE LONGEST CURRENT STREAK FOR OAKLAND. HAVING PLAYED IN 44 STRAIGHT.
<P>
HAS 72 CAREER LEADOFF HOMERS. HE THINKS HE HAS NUMBER 73 OFF  BUT  GOES OVER THE WALL AND BRINGS THIS ONE BACK.
<P>
------------
<P>
IN THE 2ND INNING. RICKEY RETURNS THE FAVOR.  BLOOPS ONE TO LEFT. AND RICKEY MAKES THE DIVING CATCH.
<P>
-----------
<P>
THIS ONE SCORLESS UNTIL THE 6TH. WHEN MR. IRONMAN HIMSELF TAKES MATTERS INTO HIS OWN HANDS WITH THE BLOOP TO RIGHT. IT'LL SCORE TWO RUNS AS THE ORIOLES GO ON TO WIN. 8-2 IS THE FINAL. BALTIMORE SNAPS A 2-GAME LOSING STREAK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
THE SHARKS HAVE THE NIGHT OFF. TRAILING THE STARS 2-0 IN THE BEST OF SEVEN SERIES. AS THE TWO TEAMS HEAD TO SAN JOSE.
<P>
LAST NIGHT. THE SHARKS LOST ANOTHER PHYSICAL GAME. WITH THE STARS SCORING 5-GOALS TO RAISE THEIR TOTAL TO 9 IN TWO GAMES.
<P>
AND AS THE SERIES SWITCHES TO SAN JOSE. DON'T EXPECT THE LEVEL OF PLAY TO SLOW DOWN ONE BIT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42NBA Playoffs>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA Playoffs</H3><BR>
ON THE HARDWOOD. THE DEFENDING WESTERN CONFERENCE CHAMPS LACE UP THEIR SNEAKERS TONIGHT AS THE JAZZ LOOK TO EVEN THINGS UP WITH THE EXPERIENCED ROCKETS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Suns>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Suns</H3><BR>
MEANTIME.  RETURNS TO THE LINEUP FOR THE SUNS. HE SCORES 16-POINTS AGAINST THE SPURS.
<P>
------------
<P>
BUT THE STAR OF THE GAME IS. THE PHOENIX FORWARD SCORING 21 POINTS TO GO WITH 11 BOARDS AS THE SUNS EVEN THINGS UP. FINAL. 108-101.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Jaguars>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jaguars</H3><BR>
IN SOCCER. THE CALIFORNIA JAGUARS LOOK TO MAKE IT 3 IN A ROW TONIGHT AFTER STARTING THE SEASON WITH 2-LOSSES.
<P>
THE FANS HUNGRY FOR ANOTHER WIN AT THE SALINAS SPORTS COMPLEX. 
<P>
-----------
<P>
AND THE JAGUARS GET ON THE BOARD FIRST.  WITH A BREAKAWAY. AND DAVINI FIRES TO THE FAR POST FOR THE GOAL. JAGS UP 1-NOTHING.
<P>
----------
<P>
LESS THAN TWO-MINUTES LATER. THE JAGS TALLY ANOTHER GOAL.  WITH THE PASS TO  WHO LEAVES IT FOR DAVINI. AND HE SCORES HIS 2ND GOAL OF THE GAME.
<P>
FINAL.
<P>
JAGUARS.
<P>
THUNDER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Clash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clash</H3><BR>
NEXT. CLASH DOWN 3-2 TO THE METRO STARS. WHEN  POPS IN THE HALF VOLLEY. HIS 2ND GOAL OF THE GAME. AND WE'RE TIED AT THREE.
<P>
----------
<P>
IT STAY'S THAT WAY UNTIL THE 90TH MINUTE.  BEATS DAVE KRAMER WITH JUST 13 SECONDS TO PLAY. AND THE CLASH LOSE A HEARTBREAKER. 3-2 IS THE FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=99Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
IN GOLF. SKIP KENDAL, BOB ESTES AND SCOTT VERPLANK ALL HAVE A SHARE OF THE LEAD AFTER 3 ROUNDS OF THE GREATER GREENSBORO CLASSIC. 11 OTHER GOLFERS ARE WITHIN 4 SHOTS OF THE LEAD.
<P>
MEANTIME. THE LADIES ARE IN GEORGIA FOR THE CHICK FILET CHARITY CHAMPIONSHIP.  WITH THE TEE SHOT AT NUMBER 11. AND THIS ONE IS A BEAUTY. IT ALMOST GOES IN. SHE WOULD MAKE BIRDIE. ONE OF NINE ON THE DAY.
<P>
----------
<P>
AT 14. SAN JOSE STATE GRAD  ROLLS IN THE BIRDIE. SHE FOLLOWS HER 1ST ROUND 65 WITH A 70. SHE'S 3-SHOTS OFF THE LEAD.
<P>
---------
<P>
FIRES A 65 TODAY. AND SHE'S THE LEADER AT 12-UNDER. WITH ONE ROUND TO GO.    
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114Mty. H.S. Jazz Closer>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mty. H.S. Jazz Closer</H3><BR>
FINALLY. THERE'S MUSIC IN THE AIR TONIGHT ON THE MONTEREY PENINSULA.
<P>
IT'S THE "MONTEREY JAZZ FESTIVAL'S HIGH SCHOOL COMPETITION".  A THREE-DAY EVENT CONTINUING THROUGH THE WEEKEND.
<P>
THE 28-TH ANNUAL EVENT BRINGS TOGETHER SOME OF THE BEST HIGH SCHOOL JAZZ GROUPS FROM AROUND THE COUNTRY.
<P>
THE LOS ANGELES COUNTY SCHOOL FOR THE ARTS TOOK FIRST PLACE IN THE "COMBO" COMPETITION. AND FOLSOM HIGH PLACED FIRST IN THE "VOCAL" DIVISION.
<P>
MONTEREY HIGH IS AMONG THE FINALISTS  IN THE "BIG BAND" COMPETITION.
<P>
SO. AS WE SAY GOODNIGHT. LET'S GIVE A LISTEN TO THOSE BIG BAND SOUNDS OF THE YOUNG MUSICIANS FROM MONTEREY.
<P>
NATURAL SOUND UP AND OUT
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
