<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Friday, 4/17/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Friday, 4/17/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106Valeau/Racial slur>Valeau/Racial slur</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137(bubba gump charg)>(bubba gump charg)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Gilroy Graffiti>Gilroy Graffiti</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143(bldg implosion)>(bldg implosion)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Peace march vigil>Peace march vigil</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22(shuttle launch)>(shuttle launch)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127New Wats hospital>New Wats hospital</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/tax preps>Fox Biz/tax preps</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Latino admissions>Latino admissions</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Raiders>Raiders</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131CA border chase>CA border chase</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Manning>Manning</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Arkansas tornado >Arkansas tornado </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4249ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Detroit tornado>Detroit tornado</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Senior Golf>Senior Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(virginia bombs)>(virginia bombs)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45PGA Tour Golf>PGA Tour Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145(dallas postal shoot)>(dallas postal shoot)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Laguna Seca>Laguna Seca</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(shark attack)>(shark attack)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50USS cowpens visit>USS cowpens visit</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(police beat senten)>(police beat senten)</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=106Valeau/Racial slur>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Valeau/Racial slur</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M CHERI GYURO. ALAN MARSDEN HAS THE NIGHT OFF.
<P>
A SEXUAL HARASSMENT COMPLAINT IS FILED AGAINST THE PRESIDENT OF A LOCAL JUNIOR COLLEGE.
<P>
AND IT'S NOT THE FIRST TIME.
<P>
THE COMPLAINT WAS FILED AGAINST HARTNELL COLLEGE PRESIDENT ED VALEAU BY KATHRYN BUTLER.
<P>
BUTLER IS THE DIRECTOR OF MARKETING AND PUBLIC RELATIONS FOR THE COLLEGE. 
<P>
THE MONTEREY COUNTY AFFIRMATIVE ACTION OFFICER IS  INVESTIGATING THE CLAIM.
<P>
ONE THAT VALEAU'S ATTORNEY SAYS IS COMPLETELY GROUNDLESS.
<P>
HE SAYS: "I CAN TELL YOU. DETERMINATIONS ARE ACCURATE."
<P>
SHE SAYS: "BASED ON ALL THE INFORMATION I HAVE. THE CHARGES ARE WITHOUT MERIT."
<P>
THIS IS NOT THE FIRST TIME VALEAU'S BEEN INVESTIGATED FOR SEXUAL HARASSMENT. 
<P>
A PREVIOUS CHARGE WAS DROPPED AFTER THE COLLEGE'S BOARD OF TRUSTEES AGREED TO GRANT THE ACCUSER A PAID LEAVE OF ABSENSE LEADING UP TO HER RESIGNATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Gilroy Graffiti>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gilroy Graffiti</H3><BR>
THERE'S A BIG STINK IN THE GARLIC CAPITOL THESE DAYS.
<P>
IT'S BEING CAUSED BY GRAFFITI.
<P>
VANDALS STEPPED UP THEIR ACTIVITY IN  RECENT WEEKS.
<P>
SO FAR THIS YEAR.GILROY HAS BEEN HIT WITH TENS OF THOUASANDS OF DOLLARS IN DAMAGES. 
<P>
INCLUDING A RECENT ATTACK TO THE TOWN'S MEDICAL COMPLEX.
<P>
BUSINESS OWNERS WHO'VE BEEN HIT SAY THEY'RE FRUSTRATED. BUT THEY KNOW THE POLICE CAN'T BE EVERYWHERE AT ONCE.  
<P>
ACTUALLY THEY DID. BOTH SIDES OF THE STREET. 
<P>
WE CAN'T PUT ALL.THEY ARE PART OF THE SOLUTION BUT WE ARE ALSO.
<P>
A ONE THOUSAND DOLLAR REWARD IS BEING OFFERED FOR INFORMATION ON THE VANDALS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Peace march vigil>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Peace march vigil</H3><BR>
HUNDREDS OF LOCALS ARE SPEAKING OUT AGAINST GANG ACTIVITY TONIGHT.
<P>
THE CITY OF SALINAS AND "SALINAS BARRIOS UNIDOS" JOINED TOGETHER THIS EVENING FOR A PEACE MARCH AND VIGIL.
<P>
IT BEGAN AT THE BREADBOX RECREATION CENTER ON NORTH SANBORN ROAD.
<P>
PARTICIPANTS SAY THEY WANT TO TAKE BACK THE STREETS AND KEEP THEM SAFE FOR THEIR CHILDREN.
<P>
OC: "WE EXPECTED."
<P>
TONIGHT FAMILY AND FRIENDS ALSO HONORED THE MEMORY OF LOVED ONES WHO ENDED UP BECOMING VICTIMS OF GANG VIOLENCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127New Wats hospital>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>New Wats hospital</H3><BR>
AFTER EIGHT YEARS.THE WATSONVILLE COMMUNITY HOSPITAL IS FINALLY GETTING NEW DIGS.
<P>
IN 1990. ENGINEERS REALIZED THE GROUND
<P>
FLOOR OF THE OLD HOSPITAL WAS SEVERELY DAMAGED BY THE LOMA PRIETA EARTHQKE.
<P>
        THAT BEGAN THE MOVE TO BUILD A NEW HOSPITAL.
<P>
78-MILLION DOLLARS LATER.AND WITH NEW OWNERS AT THE HELM. THE DOORS ARE READY TO OPEN.
<P>
"THE HOSPITAL WAS IN JEAPARDY OF CLOSING, THERE WERE SOME ECONOMIC
<P>
HARD TIMES, THE CORE STAFF IS STILL HERE, BUT THERE ARE SOME AREAS THAT
<P>
NEED TO BE BEEFED UP, AND I THINK THE NEW AFFILLIATION WILL HELP US DO THAT."
<P>
THE NEW OWNERS. COMMUNITY HEALTH SYSTEMS.ARE FROM A NATIONAL CHAIN. BASED IN TENNESSEE.
<P>
THE HOSPITAL WILL CHANGE FROM NON-PROFIT STATUS TO FOR-PROFIT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Latino admissions>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Latino admissions</H3><BR>
HISPANICS AND OTHER MINORITIES CLAIM THEY'RE BEING SHUT OUT OF CALIFORNIA'S TOP STATE UNIVERSITIES IN THE WAKE OF PROP 2-0-9.
<P>
THE CONTROVERSIAL INITIATIVE ABOLISHED RACIAL PREFERENCES IN CALIFORNIA TWO YEARS AGO.
<P>
THE EFFECTS ARE STARTING TO SHOW UP ON TOP COLLEGE MINORITY ADMISSIONS. 
<P>
ONE-THIRD TO ONE-HALF FEWER BLACK AND HISPANIC FRESHMAN WILL ATTEND BERKELEY AND U-C-L-A NEXT FALL.
<P>
MINORITY ADVOCATES SAY SHUTTING OUT MINORITIES IS UNFAIR. AND COULD LEAD TO STRING OF COPY-CAT INITIATIVES ACROSS THE U-S.
<P>
"TO DENY ACCESS TO LATINOS AND AFRICAN AMERICANS TO THE MOST PRESTIGIOUS AND ELITE UNIVERSITIES AND THEN SAY WELL WHAT DO 
<P>
YOU WANT TO GO THERE FOR, 'IT'S ELITIST', THAT'S ADDING INSULT TO 
<P>
INJURY."  
<P>
"THAT'S THE FEAR THAT NATIONALLY THIS IS GOING TO BE AN 
<P>
ISSUE BECAUSE YOU WILL SEE COPYCAT INITIATIVES FOLLOWING THE 
<P>
CALIFORNIA MODEL OF 209." 
<P>
OVERALL. MINORITY ADMISSIONS AT THE UNIVERSITY OF CALIFORNIA'S EIGHT CAMPUSES ARE DOWN ABOUT 17-PERCENT FOR BLACKS AND 7-PERCENT FOR HISPANICS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131CA border chase>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>CA border chase</H3><BR>
DOZENS OF PEOPLE ARE HURT. WHEN A CHASE INVOLVING BORDER PATROL AGENTS AND TWO VANS CAME TO A CRASHING END.
<P>
IT STARTED THIS MORNING NEAR THE CALIFORNIA-MEXICO BORDER.
<P>
THE VANS.CARRYING ABOUT 50 UNDOCUMENTED IMMIGRANTS.SPED THROUGH A CHECKPOINT. 
<P>
ONE VAN.CARRYING THIRTY-FOUR PASSENGERS.LEFT THE FREEWAY AND CRASHED INTO A SUPERMARKET. 
<P>
THIRTEEN PASSENGERS WERE TAKEN TO THE HOSPITAL AND ANOTHER TWELVE WERE TREATED ON THE SCENE. 
<P>
THE OTHER VAN SPED THROUGH THREE FREEWAYS BEFORE STOPPING IN AN ORANGE GROVE.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Arkansas tornado >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Arkansas tornado </H3><BR>
A SIMILAR STORY IN ARKANSAS.
<P>
FOLKS THERE TRY TO PICK UP THE PIECES FROM A DEADLY WAVE OF TORNADOS AND STORMS.
<P>
THE SMALL TOWN OF MANILA WAS HIT HARDEST.
<P>
THE TWISTER LEFT TWO SMALL CHILDREN DEAD AND TWENTY-ONE PEOPLE HURT.
<P>
MANY PEOPLE WHO LOST THERE HOMES. CONTINUE TO SEARCH FOR ITEMS SCATTERED ON THE GROUND WHERE THEY LIVED. 
<P>
THE FUNNELLING WIND DESTROYED 31 HOUSES.  ONE APARTMENT COMPLEX. AND DAMAGED 131 OTHERS. 
<P>
THE TWO CHILDREN KILLED WERE 2 AND 5 YEAR OLD SISTERS.
<P>
THEIR MOBILE HOME STUCK THE TORNADO HEAD ON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Detroit tornado>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Detroit tornado</H3><BR>
THE SOUTH ISN'T THE ONLY AREA BEING HIT HARD BY TORNADOES. 
<P>
IN PORT SAN-A-LAC, MICHIGAN. MORE THAN TWO DOZEN HOMES ARE DAMAGED.
<P>
20 BARNS FLATTENED AFTER A TORNADO TORE THROUGH THE AREA. 
<P>
LUCKILY NO ONE WAS HURT. 
<P>
SIRENS WARNED RESIDENTS ABOUT TWENTY MINUTES BEFORE THE TORNADO TOUCHED DOWN. 
<P>
THE TWISTER CUT A SIX MILE-LONG PATH THROUGH THE COUNTY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
ANOTHER ROUND OF BOMB ATTACKS IN VIRGINIA LEAVES THREE PEOPLE HURT.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(virginia bombs)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(virginia bombs)</H3><BR>
THE FIRST BOMB. HIDDEN INSIDE A TACKLE BOX. WENT OFF THIS MORNING.     
<P>
A 50-YEAR-OLD MAN AND HIS 22 YEAR OLD SON.FOUND IT OUTSIDE THEIR HOUSE AND BROUGHT IT INSIDE. BEFORE IT EXPLODED. 
<P>
BOTH SUFFERED BURNS ON THEIR ARMS.
<P>
THE SECOND BOMB WENT OFF AN HOUR LATER AT A PIZZA HUT TEN MILES AWAY.
<P>
ONE WOMAN WAS SERIOUSLY HURT.     
<P>
THE AREA HAS BEEN PLAGUED WITH BOMB ATTACKS.ONE PERSON WAS KILLED LAST DECEMBER.
<P>
STILL NO WORD ON WHETHER THE ATTACKS ARE RELATED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145(dallas postal shoot)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(dallas postal shoot)</H3><BR>
A DALLAS POST OFFICE IS THE SCENE OF A DEADLY SHOOTING TODAY. 
<P>
POLICE SAY A 34-YEAR-OLD WOMAN. WHO HAD BEEN A CLERK IN THE POST OFFICE FOR THE PAST FIFTEEN YEARS. WAS SHOT BY A 27-YEAR-OLD MAN. WHO WORKED AS A MAIL-CARRIER.
<P>
POSTAL OFFICIALS SAY THE TWO HAD BEEN ARGUING IN THE BREAK ROOM JUST BEFORE THE SHOOTING. 
<P>
NO ONE ELSE WAS HURT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(shark attack)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(shark attack)</H3><BR>
A FUN TRIP TO THE FLORIDA KEYS TURNS INTO A NIGHTMARE FOR AN ILLINOIS TEEN.
<P>
16-YEAR-OLD KEVIN MORRISON WAS SWIMMING IN THE OCEAN.BECAME FASCINATED WITH A FISH AND PULLED ITS TAIL.
<P>
THAT FISH TURNED OUT TO BE A 3-FOOT NURSE SHARK WHO SNAPPED AROUND AND CHOMPED DOWN ON THE BOY'S CHEST.
<P>
THE SHARK HUNG ON ALL THE WAY TO THE EMERGENCY ROOM.
<P>
DOCTORS SPLIT THE SHARK'S SPINE TO UNLOCK ITS JAW, AND MORRISON WAS RELEASED FROM THE HOSPITAL RIGHT AWAY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(police beat senten)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(police beat senten)</H3><BR>
A FORMER DETROIT POLICE OFFICER IS SENTENCED TO 4 TO 15 YEARS IN PRISON FOR THE 1992 BEATING DEATH OF AN AFRICAN-AMERICAN MAN.
<P>
WALTER BUDZYN SERVED ALMOST FOUR YEARS FOR HIS FIRST CONVICTION. 
<P>
THAT VERDICT WAS OVERTURNED LAST YEAR BECAUSE THE JURORS HAD WATCHED A TAPE OF MALCOLM "X". DURING A BREAK IN DELIBERATIONS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137(bubba gump charg)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(bubba gump charg)</H3><BR>
THE ACTOR WHO PLAYED BUBBA IN THE MOVIE "FORREST GUMP" HAS BEEN ORDERED TO STAND TRIAL ON ATTEMPTED MANSLAUGHTER CHARGES.
<P>
WILLIAMSON IS ACCUSED OF STABBING HIS EX-WIFE'S FRIEND WITH A BUTCHER KNIFE.
<P>
THE VICTIM TESTIFIED THAT WILLIAMSON WAS IN A RAGE WHEN HE STABBED HIM IN THE HAND AND ABDOMEN.
<P>
WILLIAMSON'S EX-WIFE SAYS HE HAD BEEN STALKING HER BEFORE THE ALLEGED INCIDENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143(bldg implosion)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(bldg implosion)</H3><BR>
---IMPLOSION---
<P>
CONSTRUCTION CREWS IMPLODED THE DIPLOMAT HOTEL ON OCEAN DRIVE. IN MIAMI TODAY. 
<P>
THE LUXURY HOTEL WAS BUILT IN 19-58. ATTRACTING STARS SUCH AS SAMMY DAVIS JUNIOR, JUDY GARLAND AND JACKIE GLEASON.  
<P>
THE HOTEL WILL BE REBUILT AS THE 4-MILLION DOLLAR  
<P>
DIPLOMAT RESORT AND COUNTRY CLUB. 
<P>
IT WILL BE THIRTY-NINE STORIES HIGH. AND HAVE ONE-THOUSAND ROOMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22(shuttle launch)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(shuttle launch)</H3><BR>
--LAUNCH--
<P>
AFTER A ONE-DAY DELAY.SKIES OVER FLORIDA'S KENNEDY SPACE CENTER WERE CLEAR ENOUGH FOR THE SHUTTLE COLUMBIA TO BLAST-OFF. 
<P>
SEVEN ASTRONAUTS. AND HUNDREDS OF BUGS AND RODENTS. ARE ON BOARD FOR THE TWO-WEEK MISSION. 
<P>
THE CREW WILL CONDUCT AN IN-DEPTH STUDY OF WHAT HAPPENS TO THE BRAIN AND THE NERVOUS SYSTEM IN OUTER SPACE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/tax preps>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/tax preps</H3><BR>
TAX DAY HAS COME AND GONE. AT LEAST FOR THOSE PEOPLE WHO DIDN'T FILE EXTENSIONS.
<P>
ACCORDING TO THE NUMBER-CRUNCHERS. MORE AND MORE PEOPLE ARE LEAVING IT UP TO THE PROS TO DO THEIR TAXES.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
ACCORDING TO THE SEMI-FINAL TALLY. MORE TAX FILERS TURNED TO PROFESSIONAL NUMBER-CRUNCHERS THIS YEAR: 
<P>
EARLY REPORTS FROM H-AND-R BLOCK SHOW ITS TAX PREPARATION VOLUME WENT UP 10-PERCENT FROM JANUARY THROUGH MARCH. TO ALMOST A HUNDRED-MILLION DOLLARS. 
<P>
12-POINT-3 MILLION AMERICANS USED H-AND-R BLOCK THIS YEAR. THAT'S ABOUT A 2-PERCENT INCREASE FROM LAST YEAR. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Raiders>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Raiders</H3><BR>
AS THE DESIGNATED FRANCHISE PLAYER, THE RAIDERS HAD THE RIGHT TO MATCH THE OFFER THE KANSAS CITY CHIEFS MADE TO ALL PRO DEFENSIVE TACKLE CHESTER MCCLOCKTON.
<P>
BUT THE RAIDERS RESPONSE TODAY, "JUST GO BABY."
<P>
MCCLOCKTON SIGNS A 5-YEAR DEAL WITH KANSAS CITY, REPORTEDLY IN THE RANGE OF ABOUT 5-MILLION A YEAR.
<P>
WITH RUSSELL MARYLAND AND DARRELL RUSSELL IN HOUSE, THE RAIDERS WERE ACTUALLY RELEIVED TO GET RID OF THE MOODY MCCLOCKTON.
<P>
NOT TO MENTION THE FACT THAT OAKLAND WILL GET TWO  DRAFT PICKS AS COMPENSATION, A FIRST AND A 2ND ROUND PICK IN THE DEAL.
<P>
MCCLOCKTON HAS 39-CAREER SACKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Manning>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Manning</H3><BR>
THE NFL DRAFT GETS UNDERWAY TOMORROW, STARTING AT 9:00 LOCAL TIME.
<P>
WORD COMES TODAY, THAT THE INDIANAPOLIS COLTS WILL INDEED USE THE FIRST OVERALL PICK IN THE DRAFT TO TAKE TENNESSEE QUARTERBACK PEYTON MANNING.
<P>
THAT MEANS THE SAN DIEGO CHARGERS WILL USE THE 2ND PICK TO TAKE WASHINGTON ST. QUARTERBACK RYAN LEAF.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4249ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
ONE OTHER BIT OF FOOTBALL NEWS, NFL COMMISSIONER PAUL TAGLIABUE ANNOUNCED THAT CARMEN POLICY WILL CONTINUE AS 49ERS PRESIDENT THROUGH THE 1998 SEASON.
<P>
THE COMMISSIONER WANTED TO MAKE SURE THERE WAS STABILITY WITH SAN FRANCISCO WHILE THE DEBARTALO FAMILY WORKS OUT THE OWNERSHIP QUANDRY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
IN HIS FIRST FULL SEASON IN THE MAJORS, SHAWN ESTES WON 19-GAMES FOR THE GIANTS.
<P>
SO THIS SEASON HE'S BEEN DUBBED "THE ACE" OF THE GIANT STAFF, BUT SO FAR THIS YEAR, ESTES HAS BEEN "CLUBBED" BY THE NATIONAL LEAGUE.
<P>
THE GIANTS MAKE THEIR FIRST TRIP TO MILWAUKEE TONITE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Senior Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Senior Golf</H3><BR>
TO GOLF, AND THIS WEEK'S PGA SENIORS CHAMPIONSHIP MARKS THE 2ND MAJOR OF THE YEAR FOR THE SENIOR TOUR.
<P>
WE'RE OFF TO PALM BEACH GARDENS, FLORIDA.
<P>
COMING OFF HIS GREAT SHOWING AT THE MASTERS, JACK NICKLAUS IS IN THE HUNT AGAIN.
<P>
BUT HE FOLLOWS UP YESTERDAY'S 68 WITH A 74. HE'S TIED FOR 4TH, 6-SHOTS OFF THE LEAD.
<P>
YESTERDAY'S OTHER CO-LEADER, 2-TIME DEFENDING CHAMP HALE IRWIN, HAS ANOTHER GREAT DAY.
<P>
HIS 2ND STRAIGHT 68, HAS HIM 8-UNDER PAR, SITTING COMFORTABLY WITH A 4-STROKE LEAD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45PGA Tour Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PGA Tour Golf</H3><BR>
MEANWHILE THE PGA TOUR IS ON HILTON HEAD ISLAND, SOUTH CAROLINA FOR THE MCI CLASSIC.
<P>
WE'VE GOT A COUPLE OF GREAT SHOTS TO SHOW YOU.
<P>
BILLY RAY BROWN, CHIPPING AT THE 11TH.THANK YOU VERY MUCH.
<P>
TO 18, AND THE APPROACH OF R.W. EAKS, LOOKS GOOD, IS GOOD. ALMOST IN THE HOLE.
<P>
BUT GOLFERS ARE NEVER SATISFIED.
<P>
JAY HAAS HOLDS A 1-STROKE LEAD AFTER 2-ROUNDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Laguna Seca>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Laguna Seca</H3><BR>
FINALLY, THIS IS DAY ONE OF QUALIFYING FOR THE AMA SUPERBIKE RACE COMING UP THIS WEEKEND AT LAGUNA SECA.
<P>
AND SALINAS' DOUG CHANDLER STEELS THE SHOW, AGAIN.
<P>
CHANDLER WINS THE PROVISIONAL POLE FOR SUNDAY'S HONDA CHALLENGE OF LAGUNA SECA.
<P>
AND ITS WITH A RECORD QUALIFYING LAP OF 1:25.769 OVER THE 2.238-MILE TRACK.
<P>
BUT THE RECORD CHANDLER BROKE, WAS HIS OWN THAT HE SET LAST YEAR, BEFORE WINNING AT LAGUNA SECA FOR THE 2ND STRAIGHT YEAR.
<P>
CHANDLER, WHO RIDES FOR THE MUZZY-KAWASKI TEAM, IS A 3-TIME NATIONAL SUPERBIKE CHAMPION.
<P>
HE IS ALSO A NORTH SALINAS HIGH GRAD.
<P>
LETS CHECK SOME RESULTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50USS cowpens visit>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>USS cowpens visit</H3><BR>
MONTEREY IS PLAYING HOST TO A VERY WELCOME AND REGULAR VISITOR HERE ON THE CENTRAL COAST.
<P>
THE U-S-S COWPENS IS A SIX HUNDRED FOOT.U-S NAVY. GUIDED MISSILE CRUISER.
<P>
THE SHIP ROARED INTO PORT EARLIER THIS AFTERNOON.
<P>
PUBLIC TOURS WILL BE OFFERED TOMORROW AND SUNDAY AT MONTEREY'S WHARF NUMBER ONE. BETWEEN NINE IN THE MORNING AND FOUR IN THE AFTERNOON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
