<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Wednesday, 4/22/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Wednesday, 4/22/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#150SC Fire>SC Fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(Office Shooting)>(Office Shooting)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#149Landslide/Gas Break>Landslide/Gas Break</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/ATM>Fox Biz/ATM</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Sex Assault Vigil SC>Sex Assault Vigil SC</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Morgan Hill Harass>Morgan Hill Harass</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Hwy. 17 Shoot Folo>Hwy. 17 Shoot Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127DD Dog Sentence>DD Dog Sentence</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Reggie White>Reggie White</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Earth Day Local>Earth Day Local</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Norman>Norman</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Clinton/Earth Day>Clinton/Earth Day</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142Earth Day Demo>Earth Day Demo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145Soccer>Soccer</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Another Nanny-I>Another Nanny-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(Grossberg Plea)>(Grossberg Plea)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#148Special Days-I>Special Days-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(McCartney Death)>(McCartney Death)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Special Days-G>Special Days-G</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=150SC Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Fire</H3><BR>
        GOOD EVENING. I'M ALAN MARSDEN.
<P>
OUR TOP STORY TONIGHT. AN ELECTRICAL FIRE AT THE SANTA CRUZ COUNTY BUILDING SENDS ONE PERSON TO THE HOSPITAL AND FORCES AN EVACUATION OF THE BUILDING.
<P>
COUNTY OFFICIALS SAY.  A 2-MAN CREW WAS WORKING IN THE BASEMENT OF THE MAIN COUNTY BUILDING ON AN ELECTRICAL PANEL.
<P>
WITNESS'S SAY. THEY SAW A WIRE ARC AND A WORKER WAS HIT WITH THE LIVE WIRE.
<P>
FIRE OFFICIALS SAY. THE BUILDING WAS FULL OF SMOKE WHEN THEY ARRIVED.
<P>
THE WORKER WAS TAKEN TO DOMINICAN HOSPITAL WHERE HE'S LISTED IN STABLE CONDITION TONIGHT.
<P>
IN THE MEANTIME. THE MAIN COUNTY BUILDING AT 7-0-1 OCEAN STREET IS CLOSED TOMORROW AND THAT INCLUDES ALL COURTROOMS AT THE SAME LOCATION.
<P>
THE COUNTY ADMINISTRATOR SAYS. THIS IS AN EMERGENCY CLOSURE AND COUNTY EMPLOYEES WHO WORK AT THIS SITE WILL BE PAID.
<P>
OTHER COUNTY FACILITIES WILL BE OPEN TOMORROW.
<P>
THE EXACT COST AND CAUSE OF THE FIRE IS STILL UNDER INVESTIGATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=149Landslide/Gas Break>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Landslide/Gas Break</H3><BR>
        A MASSIVE LANDSLIDE IN SAN BENITO COUNTY SEVERS  TWO P-G-AND-E GAS LINES SERVING SANTA CRUZ COUNTY.
<P>
THE SLIDE OCCURRED NEAR THE INTERSECTIONS OF ANZAN AND  CANNON ROADS IN SAN BENITO COUNTY EARLY THIS MORNING.
<P>
        SOME GAS REMAINS IN THE LINES. AND IN A STORAGE FACILITY IN SANTA CRUZ.
<P>
ACCORDING TO P-G-& E. THERE IS A POSSIBILITY SOME CUSTOMERS IN SANTA CRUZ  MAY LOSE GAS  SERVICE. BUT THE REPAIR WORK WILL CONTINUE AROUND THE CLOCK.
<P>
"AS YOU CAN SEE HERE, THE GROUND IS STILL MOVING, IT'S VERY SOFT.  YOU CAN SEE WHERE THE 10-INCH LINE DID BREAK AND MOTHER NATURE ISN'T BEING VERY FRIENDLY TO US RIGHT NOW. SO AGAIN, WE ARE ASKING OUR CUSTOMERS TO HELP US OUT AND GET THROUGH THIS.  WE'RE TARGETING SOMETIME TOMORROW MORNING TO BE ABLE TO GET THIS WORK DONE IF EVERYTHING GOES WELL." 
<P>
ROAKE SAYS. THERE IS  A LIMITED AMOUNT OF NATURAL GAS AVAILABLE TO THE SANTA CRUZ AREA.ABOUT 10 HOURS WORTH REMAINS IN THE FEEDER PIPES. AND PG & E IS ASKING PEOPLE TO USE A MINIMUM AMOUNT TO CONSERVE THE SUPPLY.
<P>
THE COMPANY ASKS CONSUMERS TO KEEP USAGE OF GAS APPLIANCES AT A MINIMUM. AND TO LIMIT THE USE OF GAS WHILE COOKING.
<P>
        NO ONE WAS REPORTED INJURED AS A RESULT OF EITHER THE SLIDE OR THE  RUPTURE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Sex Assault Vigil SC>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sex Assault Vigil SC</H3><BR>
CANDLE-LIGHT VIGILS ARE HELD TONIGHT THROUGHOUT CALIFORNIA. IN REMEMBRANCE OF THE VICTIMS AND SURVIVORS OF RAPE AND SEXUAL ASSAULT. 
<P>
MEMBERS OF THE CALIFORNIA COALITION AGAINST SEXUAL ASSAULT  LED THE VIGIL TONIGHT IN SANTA CRUZ.
<P>
IT'S ANOTHER IN A SERIES OF ACTIVITIES AND PROGRAMS BEING HELD IN HONOR OF SEXUAL ASSAULT AWARENESS MONTH.
<P>
IN 14:36"THOUSANDS OF.   OUT 14:50". YOU"RE NOT ALONE.
<P>
TONIGHT'S VIGIL WAS ORGANIZED BY THE WOMEN'S CRISIS SUPPORT CENTER OF SANTA CRUZ.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Morgan Hill Harass>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Morgan Hill Harass</H3><BR>
CHARGES ARE FILED AGAINST THE MORGAN HILL UNIFIED SCHOOL DISTRICT ALLEDGING. OFFCIALS  DIDN'T DO ENOUGH TO PROTECT STUDENTS FROM SEXUAL HARASSMENT AT THREE OF THE DISTRICT'S SCHOOLS. 
<P>
THE LAWSUIT ALLEGES.  ALLANA FLORES AND THREE UNNAMED STUDENTS ARE VICTIMS OF THE HARASSMENT. 
<P>
THE ATTORNEY REPRESENTING THE FOUR STUDENTS SAYS.  THE ABUSE HAS BEEN GOING ON FOR YEARS. 
<P>
"THE ALLEGATIONS DEAL WITH DISCRIMINATION AND HARASSMENT ON THE BASIS OF SEXUAL ORIENTATION AND THE ADMINISTRATION'S UNWILLINGNESS TO PROTECT ANY OF THE CHILDREN."  
<P>
"THEY ARE ALLEGATIONS AT THIS TIME.  BUT WE T THE DISTRICT OFFICE HAD NOT BEEN AWARE OF. I"VE NEVER REIEIVED A LETTER FROM A PARENT, OR HAD A MEETING WITH A PARENT, OR ANYONE, TO LET US KNOW THERE WERE CONCERNS ABOUT THE TREATMENT OF STUDENTS." 
<P>
AN INVESTIGATION OF THE CHARGES IS UNDERWAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Hwy. 17 Shoot Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hwy. 17 Shoot Folo</H3><BR>
INVESTIGATORS HAVE IDENTIFIED THE MAN SHOT AND KILLED YESTERDAY.  BY A C-H-P OFFICER ON HIGHWAY 17.  
<P>
21-YEAR OLD THOMAS PETER STAV OF PITTSBURG WAS INVOLVED IN A SERIES OF HIT-AND-RUN ACCIDENTS THROUGH THE HIGHWAY 17 CORRIDOR YESTERDAY.
<P>
POLICE PICKED UP THE CHASE. ENDING  WITH A FATAL SHOOTING NEAR THE SUMMIT.
<P>
ACCORDING TO THE SANTA CLARA SHERIFF'S DEPARMENT. STAV WAS *NOT* ARMED WHEN HE WAS SHOT BY THE C-H-P OFFICER.
<P>
''SOME OF THE WITNESSES HAVE INDICATED THAT HE HAD SOMETHING IN HIS HAND WHEN HE EXITED THE VEHICLE. WAVING IT AROUND.  HE WAS MAKING STATEMENTS TO THE FACT THAT HE WAS ARMED, AND THAT HE WAS GOING TO SHOOT SOMEBODY."  
<P>
WITNESSES SAY.  IT DID LOOK LIKE STAV WAS WAVING A GUN AT OFFICERS. BUT NO WEAPON WAS FOUND.
<P>
AN AUTOPSY WAS PERFORMED. AND TOXICOLOGY REPORTS SHOULD BE OUT IN ABOUT TWO WEEKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127DD Dog Sentence>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>DD Dog Sentence</H3><BR>
IN MARCH.  WE BROUGHT YOU THE STORY OF D-D THE DOG. SHOT AND LEFT FOR DEAD IN A GARBAGE DUMPSTER.
<P>
TODAY THE MAN WHO PULLED THE TRIGGER. AND SHOT D-D. WAS SENTENCED TO THREE YEARS PROBATION. AND 150 DAYS IN JAIL.
<P>
AARON RAINES PLED NO CONTEST TO THE SHOOTING.  AND SAID HE SHOT D-D BECAUSE THE DOG WAS ON HIS PROPERTY AND LOOKED SICK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Earth Day Local>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Earth Day Local</H3><BR>
EARTH DAY WAS CELEBRATED AROUND THE CENTRAL COAST TODAY.
<P>
OFFICIALS AT A LOCAL LANDFILL SAY.  IT'S A TIME TO FOCUS ON JUST HOW MUCH WE THROW OUT. AND WHAT WE CAN DO TO REDUCE THE AMOUNT.
<P>
LOCAL CITIES AND COUNTIES ARE UNDER PRESSURE TO CUT BACK THE AMOUNT GOING INTO LOCAL LANDFILLS. OR FACE PENALTIES.
<P>
WE'RE DOING GOOD, BUT LONG WAY TO GO..35 PERCENT GOT TO REACH 50 PERCENT BY THE YEAR 2000,. SO HARDER LAST FEW PERCENTAGE POINTS. ARE THE HARDEST.
<P>
IF THE 50 PERCENT REDUCTION GOAL IS NOT REACHED ON SCHEDULE.  LOCAL CITIES AND COUNTIES FACE A FINE OF 10-THOUSAND DOLLARS A DAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Clinton/Earth Day>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Earth Day</H3><BR>
PRESIDENT CLINTON MARKS EARTH DAY BY URGING LAWMAKERS TO FALL IN LINE WITH HIS ENVIRONMENTAL AGENDA. 
<P>
THE PRESIDENT SPENT THE MORNING WITH  VICE-PRESIDENT GORE AND VOLUNTEERS.  ALONG THE APPALACHIAN TRAIL IN HARPERS FERRY NATIONAL PARK.  
<P>
HE ALSO URGED CONGRESS TO TAKE ACTION ON GLOBAL WARMING.  AND CLEANING UP THE NATION'S WATERWAYS. 
<P>
THE PRESIDENT SUGGESTED. AMERICANS URGE THEIR LOCAL CONGRESSMEN TO FREE UP THE MONEY TO PAY FOR ENVIRONMENTAL INITIATIVES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142Earth Day Demo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Earth Day Demo</H3><BR>
A SMOKE STACK ON LONG ISLAND COMES TUMBLING DOWN  AS PART OF AN EARTH DAY CELEBRATION. 
<P>
THE TWO-HUNDRED-FIFTY FOOT HIGH STRUCTURE TUMBLED TO THE EARTH IN A CLOUD OF DUST DURING A MID-DAY CEREMONY. 
<P>
THE TOWN'S MAYOR SAID.  BRINGING DOWN THE STRUCTURE WAS AN APPROPRIATE WAY FOR THE TOWN TO CELEBRATE EARTH DAY. 
<P>
OFFICIALS FROM THE ENVIROMENTAL PROTECTON AGENCY WERE ON HAND TO MONITOR THE EVENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Another Nanny-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Another Nanny-I</H3><BR>
BRITISH POLICE OFFICIALS ARE INVESTIGATING CHARGES FILED AGAINST AN AUSTRALIAN NANNY.WHO IS SUSPECTED OF CAUSING THE DEATH OF A BABY IN HER CARE. 
<P>
THE CASE IS DRAWING COMPARISON TO THE SENSATIONAL U-S TRIAL OF BRITISH AU PAIR LOUISE WOODWARD.
<P>
AND AS FOX'S DAVID LEE MILLER TELLS US. THERE ARE OTHER SHOCKING SIMILARITIES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(Grossberg Plea)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Grossberg Plea)</H3><BR>
AMY GROSSBERG  ENTERED THE PLEA IN A DELAWARE COURTROOM TODAY.
<P>
PROSECUTORS SAY.  AFTER SHE GAVE BIRTH IN A MOTEL IN LATE 19-96. THE FATHER.BRIAN PETERSON. DUMPED THE BABY'S BODY IN A TRASH BIN OUTSIDE. 
<P>
PETERSON PLEADED GUILTY TO MANSLAUGHTER LAST MONTH. 
<P>
UNDER SENTENCING GUIDELINES. PETERSON  AND GROSSBERG COULD EACH GET TWO-AND-A-HALF YEARS IN PRISON. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(McCartney Death)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(McCartney Death)</H3><BR>
WORD TONIGHT.  AUTHORITIES ARE LOOKING INTO THE DEATH OF LINDA MCCARTNEY. WHO DIED OF BREAST CANCER FRIDAY AT AGE 56.
<P>
A SPOKESMAN FOR THE SANTA BARBARA COUNTY SHERIFF'S DEPARTMENT SAYS. IT HAS SOME QUESTIONS THAT STILL MUST BE ANSWERED.
<P>
THE "SANTA BARBARA NEWS-PRESS"  REPORTS.  THE CORONER HAS NO DEATH CERTIFICATE.  AND DIDN'T ISSUE THE NECESSARY PERMIT FOR HER TO BE CREMATED.
<P>
A FAMILY SPOKESMAN IS DENYING RUMORS. HER DEATH WAS AN ASSISTED SUICIDE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(Office Shooting)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Office Shooting)</H3><BR>
POLICE ARE INVESTIGATING THE DEATHS OF THREE U-S DEPARTMENT OF AGRICULTURE EMPLOYEES.  SHOT DURING A MEETING TODAY AT A DISTRICT OFFICE IN SOUTHERN CALIFORNIA. 
<P>
THE THREE WORKERS WERE MEETING BEHIND LOCKED DOORS. WHEN OTHER EMPLOYEES HEARD SHOTS COMING FROM THE ROOM SHORTLY AFTER THREE THIS AFTERNOON.
<P>
POLICE SAY. THE SHOOTING SUSPECT MAY HAVE BEEN ONE OF THE PEOPLE WHO WAS KILLED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/ATM>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/ATM</H3><BR>
GETTING CASH FROM THE A-T-M MACHINE WILL SOON BECOME A HI-TECH TRANSACTION.   
<P>
HERE'S TONIGHT'S FOX BUSINESS REPORT.
<P>
IF YOU HAVE TROUBLE REMEMBERING YOUR A-T-M PIN NUMBER -- DON'T DESPAIR -- THERE'S SOME RELIEF IN "SIGHT." 
<P>
NEW TECHNOLOGY WILL SOON ALLOW YOU TO GET MONEY AT THE CASH MACHINE BY JUST LOOKING AT IT. 
<P>
A VIDEO CAMERA AT AN A-T-M IMAGES YOUR EYE'S IRIS. AND THEN A COMPUTER MATCHES YOUR IRIS CODE TO THE ONE THE BANK HAS ON FILE. 
<P>
SCIENTISTS CLAIM THE SYSTEM IS FRAUD-PROOF.  BECAUSE AN IRIS HAS MORE THAN 250 UNIQUE FEATURES.  AND IS MORE ACCURATE THAN D-N-A. 
<P>
AND THE IRIS REMAINS THE SAME FROM THE  AGE OF EIGHTEEN MONTHS UNTIL DEATH.  
<P>
THE TECHNOLOGY SHOULD BE AVAILABLE AT CASH MACHINES ACROSS THE COUNTRY BY THE SUMMER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
THE SHARKS ARE THE 8TH SEED, AND THE DALLAS STARS ARE THE TOP SEED IN THE WESTERN CONFERENCE. BUT THAT DOESN'T TELL THE WHOLE STORY, SAN JOSE HAS WON 6 OF 8 FROM THE STARS OVER THE LAST 2-YEARS.
<P>
GOALIE ED BELFOUR BOLTED FROM SAN JOSE TO SIGN WITH DALLAS THIS LAST YEAR.
<P>
AND EVEN THOUGH THIS IS THE SHARKS FIRST PLAYOFF GAME IN 3-YEARS, THEY'VE NEVER LOST A GAME ONE OF A SERIES IN THEIR SHORT HISTORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
THE GIANTS DID MORE THAN LOSE A BALLGAME IN PITTSBURGH TONITE, TEAMMATES BARRY BONDS AND DANNY DARWIN LOST THEIR COOL, AND REPORTEDLY GOT INTO SCUFFLE BETWEEN INNINGS.
<P>
DARWIN AND BONDS ALREADY HAD A SHAKY RELATIONSHIP, BUT WHEN BONDS MISPLAYED A BALL IN THE 6TH, DARWIN TOOK EXCEPTION.
<P>
THIS GAME WAS NOT TELEVISED, BUT WE DO HAVE LOCAL HILITES FROM PITTSBURGH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
THE A'S WERE 6-OUTS AWAY FROM WINNING THEIR 3RD STRAIGHT.
<P>
BUT OAKLAND'S BULLPEN FAILS MISERABLEY, AND THE TWINS ESCAPE TOWN WITHOUT BEING SWEPT.
<P>
LETS HEAD TO THE COLISEUM, ONLY 7-THOUSAND ON HAND FOR THIS ONE.
<P>
PICK IT UP IN THE 4TH, WHEN MIKE BLOWERS RIPS ONE TO CENTER, OITIS NIXON, TURNS IT INTO AN ADVENTURE. BIG KEVIN MITCHELL COMES INTO SCORE. BEN GRIEVE IS RIGHT ON HIS TAIL.
<P>
THE A'S LEAD IT 2 TO 1.
<P>
TO THE 8TH, WHEN TODD WALKER GIVES BILLY TAYLOR A PRETTY GOOD RIDE.
<P>
2-RUNS COME INTO SCORE. THE TWINS SNAP A 6-GAME LOSING STREAK.
<P>
FINAL, TWINS 4 AND THE A'S 2.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Reggie White>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Reggie White</H3><BR>
I GUESS THE GREEN BAY PACKERS HAVE GOD TO THANK FOR REGGIE WHITE'S DECISION TO RETURN FOR ANOTHER YEAR.
<P>
2-DAYS AGO, THE 36-YEAR OLD DEFENSIVE END ANNOUNCED HE WAS RETIRING BECAUSE OF A BAD BACK.
<P>
A SCINIC WOULD SAY THAT WHITE DOESN'T WANT TO RETIRE FOLLOWING THE CONTROVERSIAL REMARKS HE MADE A FEW WEEKS AGO.
<P>
BUT THE NFL'S ALL-TIME SACK LEADER SAID DEVINE INTERVENTION IS THE REASON HE IS GOING TO PLAY ONE MORE YEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Norman>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Norman</H3><BR>
NOW AN ATHLETE WHO WON'T BE AROUND FOR THE REST OF THIS SEASON, IS GOLFER GREG NORMAN.
<P>
THE SHARK HAD ARTHROSCOPTIC SURGERY ON HIS LEFT SHOULDER.
<P>
IT WAS TROUBLE WITH THE SHOULDER THAT FORCED NORMAN TO WITHDRAW FROM THE PLAYERS CHAMPIONSHIP, AND THEN GREG MISSED THE CUT AT THE MASTERS.
<P>
HE'LL MISS THE OTHER 3-MAJORS THIS YEAR, AND THE REST OF THE PGA SEASON, BUT NORMAN HOPES TO BE ABLE TO PLAY IN THE PRESIDENT'S CUP IN AUSTRALIA IN DECEMBER.
<P>
NORMAN, WHO IS 43, IS THE ONLY PLAYER EVER TO LOSE ALL FOUR MAJOR CHAMPIONSHIPS IN PLAYOFFS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
LOCALLY. THE WOMEN'S WESTERN ATHLETIC CONFERENCE CHAMPIONSHIPS WRAP UP TODAY OUT AT POPPY HILLS GOLF COURSE.
<P>
IT WAS A BLUSTERY DAY AND THE SCORES PROVED HOW TOUGH THIS GOLF COURSE CAN BE.
<P>
---------
<P>
SAN JOSE STATE. THE DEFENDING CHAMPS. WOULD COME IN 6-SHOTS BACK OF THE LEAD. BUT THEY STRUGGLED.. ONE OF ONLY TWO SPARTAN GOLFERS TO SHOOT A SUB 80 ROUND. SIMPSON FINISHES WITH A 75. GOOD ENOUGH FOR A SHARE OF 2ND PLACE.
<P>
---------
<P>
7-SHOTS BACK OF TULSA'S  WHO GOES WIRE TO WIRE TO WIN THE INDIVIDUAL TITLE. SHE WAS THE ONLY GOLFER TO FINISH WITH 3-ROUNDS IN THE 70'S.
<P>
----------
<P>
THE TEAM TITLE GOES TO THE HORNED FROGS OF TEXAS CHRISTIAN. THE SPARTANS FINISH A RESPECTABLE THIRD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145Soccer>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Soccer</H3><BR>
MEANWHILE IN VIENNA, AUSTRIA, THE UNITED STATES SOCCER TEAM, SHUTSOUT AUSTRIA 3 TO 0, TO IMPROVE ITS RECORD TO 5-3-1, WITH 3-EXHIBITION MATCHES LEFT BEFORE THE WORLD CUP STARTS IN JUNE.
<P>
CLAUDIO REYNA SET UP 2-GOALS, AND SCORED THE 3RD FOR THE U.S.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
AND FINALLY IN TENNIS, PETE SAMPRAS FACES ANDRE AGASSI IN THE 2ND ROUND OF THE MONTE CARLO OPEN. ITS A TUNE-UP FOR THE UPCOMING FRENCH OPEN.
<P>
AND SAMPRAS BEATS HIS ARCH-RIVAL, ON THE CLAY. THE NUMBERS 6-4 AND 7-5.
<P>
IF HE CAN WIN HIS NEXT MATCH, SAMPRAS WILL RECLAIM THE NUMBER ONE RANKING IN THE WORLD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=148Special Days-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Special Days-I</H3><BR>
OH, WHAT A DIFFERENCE A DAY MAKES. 
<P>
IF YOU HAVE ANY DOUBTS.  LOOK AT THE LINEUP: TODAY IS "EARTH DAY." 
<P>
TOMORROW IS "TAKE YOUR DAUGHTERS TO WORK DAY." 
<P>
THEN THERE'S "SECRETARY'S DAY,".  "MOTHER'S DAY,".  "FATHER'S DAY,". "ARBOR DAY,".  "MAY DAY".  "SADIE HAWKINS' DAY,".AND SO ON AND SO FORTH. 
<P>
THE QUESTION IS: WHERE DID ALL THESE ACKNOWLEDGEMENTS COME FROM? 
<P>
FOX'S TRACE GALLAGHER TELLS US WHY THERE ARE DAYS LIKE THESE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Special Days-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Special Days-G</H3><BR>
AS A CONSCIENTIOUS MEMBER OF SOCIETY--BY NOW YOU SHOULD ALREADY 
<P>
HAVE GIVEN YOUR SECRETARY FLOWERS. PICKED UP SOME TRASH-- AND 
<P>
PLANTED A TREE-- 
<P>
AFTER ALL--IT IS SECRETARY'S DAY. AND EARTH DAY. AND ARBOR DAY--- 
<P>
A RARE CALENDER TRIFECTA-- 
<P>
THEN AGAIN-- THESE DAYS IT SEEMS EVERY DAY IS A SPECIAL DAY-- 
<P>
THERE'S BE AN ANGEL DAY-- BE LATE FOR SOMETHING DAY--BE BALD AND BE 
<P>
FREE DAY 
<P>
--SOT-- 
<P>
38:25-IF YOU FORGET AND YOUR SECRETARY AN BALD FRIENDS FEEL 
<P>
SLIGHTED. THAT MAY LEAD TO MORE GUILT-- 
<P>
--TRACK-- 
<P>
DON'T FORGET CHILDREN'S DAY. NOT TO BE CONFUSED WITH CHILD HEALTH 
<P>
DAY-- READ TO YOUR CHILD DAY OR ABSOLUTELY INCREDIBLE KID DAY--  
<P>
IN SOME CASES ONE DAY JUST WON'T DO. 
<P>
THAT'S WHY JANUARY IS HOT TEA MONTH--  AUGUST IS VEGETARIAN 
<P>
MONTH--NOVEMBER PEANUT BUTTER MONTH--   
<P>
SO WHAT GIVES?-- SOME BELIEVE WE ARE TARGETS OF A GREETING CARD 
<P>
CONSPIRACY?-- 
<P>
--SOT-- 
<P>
31:02-I BELIEVE IT'S SOMETHING INVENTED BY A MAJOR CARD COMPANY-- 
<P>
--TRACK-- 
<P>
THE TRUTH IS CONGRESS---NOT CARD COMPANIES HAVE ESTABLISHED MOST 
<P>
DAYS OF RECOGNITION-- 
<P>
INCLUDING CITIZENSHIP DAY- NATIVE AMERICAN DAY AND EMANCIPATION 
<P>
DAY-- WHICH OBSERVES THE END OF SLAVERY-- 
<P>
PRESIDENT CLINTON WILL DECLARE AUGUST 26TH WOMEN'S EQUALITY DAY. 
<P>
MARKING THE ANNIVERSARY OF THE 19TH AMMENDMENT GIVING WOMAN THE RIGHT 
<P>
TO VOTE. 
<P>
INFACT MOST SPECIAL DAYS DON'T HAVE GREETING CARDS-- 
<P>
EVEN GRANDPARENTS DAY WHICH WAS SIGNED INTO LAW BY FORMER PRESIDENT 
<P>
JIMMY CARTER. 
<P>
NEVER REALY CAUGHT ON-- 
<P>
--SOT-- 
<P>
WE JUST DON'T SELL MANY GRANDPARENT CARDS. 
<P>
--STANDUP-- 
<P>
SOME MINOR HOLIDAY'S DON'T SELL. BUT SOME LIKE SECRETARY'S DAY AND 
<P>
BOSSES DAY SELL VERY WELL. 
<P>
THEY WERE'NT CREATED BY CARD COMPANIES BUT THEY'RE CERTAINLY 
<P>
CATERED BY CARD COMPANIES. 
<P>
INFACT MINOR HOLIDAYS HAVE HELPED PUSH GREETING CARDS INTO A SIX 
<P>
BILLION DOLLAR INDUSTRY.  
<P>
JUST IMAGINE IF BALD OR BE FREE CARDS EVER CATCH ON-- IN SAN 
<P>
FRANCISCO TRACE GALLAGHER FOX NEWS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
