<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Friday, 4/3/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Friday, 4/3/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x040314.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (teachers)>TS1 (teachers)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(police racial slur)>(police racial slur)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146(WTC verdict)>(WTC verdict)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Teachers vote-INT>Teachers vote-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(VA mountain fire)>(VA mountain fire)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Teachers vote-GUT>Teachers vote-GUT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137(high school hit list)>(high school hit list)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Teachers vote-TAG>Teachers vote-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145(camouflage ban)>(camouflage ban)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Capitola cop suicide>Capitola cop suicide</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/united/delta>Fox Biz/united/delta</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Pajaro river legislat>Pajaro river legislat</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142M Jackson baby girl>M Jackson baby girl</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Ft. Ord Vets Cemetar>Ft. Ord Vets Cemetar</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Cameron raise>Cameron raise</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131SC paper prank>SC paper prank</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130SC skeletal remains>SC skeletal remains</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Cubs>Cubs</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#147Watsonville kidnap>Watsonville kidnap</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Nat'l equal pay>Nat'l equal pay</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45College Basketball>College Basketball</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(espionage) >Bump 1(espionage) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Senior Golf>Senior Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(jackson) >bump 2(jackson) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50NPS/paper planes>NPS/paper planes</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Mty Roller rink folo>Mty Roller rink folo</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(espionage arrest)>(espionage arrest)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Wild police chase-IN>Wild police chase-IN</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=134TS1 (teachers)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (teachers)</H3><BR>
NEXT ON FOX NEWS FIRST AT TEN.
<P>
A LONG BATTLE OFFICIALLY COMES TO AN END TONIGHT AS LOCAL TEACHERS VOTE TO ACCEPT. FINALLY. A NEW  CONTRACT.
<P>
A FORMER CENTRAL COAST POLICE OFFICER IS INVOLVED IN AN APPARENT MURDER-SUICIDE. WE'LL TELL YOU ABOUT.
<P>
DID THE APRIL 1ST EDITION OF A LOCAL NEWSPAPER REALLY INCLUDE A FREE SAMPLE OF A HALLUCENIGENIC DRUG?
<P>
FIND OUT NEXT ON FOX NEWS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
IT'S TAKEN THREE YEARS, AND NUMEROUS PROTESTS AND DEMONSTRATIONS. BUT FINALLY TONIGHT, TEACHERS AT ONE OF THE LARGEST SCHOOL DISTRICTS ON THE CENTRAL COAST HAVE A CONTRACT.
<P>
THE NEWS JUST CAME HOURS AGO. 
<P>
JINAH KIM JOINS US FROM THE NEWSDESK WITH THE STORY.
<P>
JINAH. IT SOUNDS LIKE A LONG, DRAWN OUT ORDEAL IS FINALLY COMING TO AN END.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Teachers vote-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teachers vote-INT</H3><BR>
IT REALLY IS. AND A LOT OF TEACHERS, STUDENTS AND ADMINSTRATORS ARE BREATHING A BIG SIGH OF RELIEF TONIGHT.
<P>
OF COURSE, WE'RE TALKING ABOUT THE SALINAS UNION HIGH SCHOOL DISTRICT. TEACHERS THERE HAVE BEEN HOLDING DEMONSTRATIONS AND SICK-OUTS BECAUSE THEY'VE GONE FOR THREE YEARS WITHOUT A RAISE.
<P>
WELL, LAST SATURDAY. A *TENTATIVE* AGREEMENT WAS REACHED. AND *TODAY*, THE TEACHERS VOTED TO RATIFY IT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Teachers vote-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teachers vote-GUT</H3><BR>
CHEERS AND SCREAMS FINALLY REPLACED MONTHS OF PROTESTS AND NEGOTIATIONS.
<P>
TONIGHT, TEACHERS AT THE SALINAS UNION HIGH SCHOOL DISTRICT GATHERED AT A LOCAL PIZZA PARLOR TO CELEBRATE SOMETHING THEY HAVEN'T SEEN IN THREE YEARS:  A RAISE.
<P>
EARLIER IN THE AFTERNOON. THE TEACHERS UNION COUNTED ALL THE VOTES CAST BY ITS MEMBERS THROUGHOUT THE DAY.
<P>
AN OVERWHELMING MAJORITY AGREED THIS WAS THE BEST CONTRACT THE TEACHERS ARE GOING TO GET RIGHT NOW:  A SIX PERCENT PAY RAISE ACROSS THE BOARD. AND MORE MONEY FOR HEALTH BENEFITS.
<P>
BUT IT WASN'T AN EASY BATTLE. DISSATISFIED TEACHERS HAVE BEEN HOLDING PROTESTS, PICKETS AND SICK-OUTS THAT HAVE INTENSIFIED OVER THE LAST FEW MONTHS. WHILE REJECTING OFFER AFTER OFFER FROM THE DISTRICT.
<P>
SALINAS TEACHERS SAY THEY'RE SOME OF THE WORST-PAID EDUCATORS IN CALIFORNIA. AND THIS CONTRACT *STILL* DOESN'T BRING THEM UP TO THE STATE AVERAGE.
<P>
FOR THEM. THIS IS ONLY A FIRST STEP IN A CONTINUING BATTLE.
<P>
"I AM NOT JUMPING FOR JOY. I'M NOT GOING TO PARTY TONIGHT."
<P>
====BUTT TO===
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Teachers vote-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teachers vote-TAG</H3><BR>
THE RAISE IS CERTAINLY A TRIUMPH FOR THE TEACHERS. BUT THEY SAY THERE'S STILL SO MUCH THEY NEED. INCLUDING BETTER EQUIPMENT, BETTER LEARNING TOOLS FOR STUDENTS AND SMALLER CLASSROOMS.
<P>
AND THOSE ARE THE THINGS THEY'LL BE FOCUSING ON THE *NEXT* TIME THEY HIT THE NEGOTIATING TABLES.
<P>
ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Capitola cop suicide>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Capitola cop suicide</H3><BR>
THE MAN WHO KILLED HIS TWO YOUNG SONS BEFORE TURNING THE GUN ON HIMSELF. APPARENTLY SERVED FOR A BRIEF TIME AS A CAPITOLA POLICE OFFICER.
<P>
42-YEAR-OLD ROBERT COLE. WAS FOUND DEAD IN HIS HOME ON TUESDAY. THE BODIES OF HIS SONS. AGES 11 AND 13. WERE LYING ON EITHER SIDE OF HIM.BOTH HAD BEEN SHOT ONCE IN THE HEAD.
<P>
INVESTIGATORS BELIEVE COLE KILLED HIS FAMILY BECAUSE HE AND HIS WIFE WERE HAVING MARITAL PROBLEMS. 
<P>
IT HAPPENED IN A THE SMALL NEVADA TOWN NEAR NEVADA CITY.
<P>
POLICE SAY COLE WORKED AS A POLICE OFFICER IN CAPITOLA WHEN HE WAS IN HIS TWENTIES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Pajaro river legislat>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pajaro river legislat</H3><BR>
A NEW BILL AIMS AT KEEPING THE PAJARO RIVER AT BAY.
<P>
27TH DISTRICT ASSEMBLYMAN FRED KEELEY. ANNOUNCED THE INTRODUCTION OF THE BILL. DURING A MEETING WITH FOLKS WHO FELT THE WRATH OF THE RIVER DURING RECENT FLOODS.       THE BILL. KNOWN AS A-B 19-86. WOULD HAVE MONTEREY, SANTA CRUZ, SAN BENITO AND SANTA CLARA COUNTIES. ALL COUNTIES WHICH BORDER THE PAJARO WATERSHED. HELP EACH OTHER. TO TRY TO PREVENT FUTURE FLOODING.
<P>
WE ARE GOING. CONTROL  PROGRAM. 
<P>
KEELEY ALSO ANNOUNCED THAT HE. AND OTHER ELECTED OFFICIALS FROM THE CENTRAL COAST. SENT A LETTER TO THE GOVERNOR. ASKING FOR 150-MILLION DOLLARS FROM A FLOOD BOND. TO FUND THOSE PROJECTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Ft. Ord Vets Cemetar>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ft. Ord Vets Cemetar</H3><BR>
CLOSE TO A HUNDRED VETERANS PACKED A TOWN HALL MEETING IN SALINAS TODAY. TO SHOW THEIR SUPPORT FOR A PROPOSED VETERANS CEMETERY ON FORT ORD.
<P>
SENATOR BRUCE MCPHERSON HOSTED THE EVENT. TO UPDATE SUPPORTERS ON BILL 20-78.
<P>
THE BILL'S PASSED ONE SENATE COMMITTEE ALREADY.
<P>
NOW, IT'S GOT ANOTHER POLITICAL HURDLE BEFORE IT GOES BEFORE THE STATE ASSEMBLY.  THAT'S THE SENATE APPROPRIATIONS COMMITTEE.
<P>
IT'S CRITICAL.  WE HAVE TO HAVE THIS STUDY DONE TO LET PEOPLE KNOW THAT YES THIS IS A LEGITIMATE USE FOR THIS 156 ACRES ON THIS FORT ORD SITE.  ONCE WE GET THAT, WE CAN PROCEED IS SAYING WE HAVE 300,000 IN THIS CENTRAL COAST AREA THAT CAN BE SERVED BY A CEMETERY AT THIS LOCATION.
<P>
THE BILL CALLS FOR 20-THOUSAND DOLLARS TO CONDUCT THE FEASIBILITY STUDY.
<P>
AFTER THAT. THE NEXT ISSUE TO DEAL WITH WOULD BE THE FUNDING OF THE CEMETERY.
<P>
IT COULD COST THE STATE UP TO 500-THOUSAND DOLLARS A YEAR TO MAINTAIN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131SC paper prank>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC paper prank</H3><BR>
A SANTA CRUZ NEWSPAPER IS NO LONGER A STRANGER TO APRIL FOOL'S DAY PRANKS.
<P>
IN  METRO'S APRIL FIRST ISSUE, THE MAIN STORY WAS ABOUT A NEW PSYCO-ACTIVE DRUG CALLED AKIMA.
<P>
BUT THE PAPER DIDN'T JUST TALK ABOUT THE BRAZILLIAN DRUG, IT ALSO OFFERED A FREE SAMPLE. RIGHT THERE ON THE PAGE.
<P>
OF COURSE, THE DRUG IS FICTIONAL AND ALL ANYONE ACTUALLY TASTED WAS THE PULP FROM THE NEWSPAPER.
<P>
METRO'S GENERAL MANAGER SAYS THE PAPER IS NOT PRO-DRUG, THEY WERE SIMPLY TRYING TO TEACH PEOPLE NOT TO BELIEVE EVERYTHING THEY READ.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130SC skeletal remains>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC skeletal remains</H3><BR>
THE  SANTA CRUZ COUNTY SHERIFF'S DEPARTMENT HAS FOUND A PILE OF HUMAN REMAINS. BUT SO FAR THEY DON'T HOW THE PERSON DIED. OR WHO IT WAS.
<P>
THE REMAINS WERE FOUND IN THE WOODS. NEAR THE CORNER OF MAR MONTE AND LARKIN VALLEY ROAD.
<P>
        SHERIFF'S INVESTIGATORS SAY THE REMAINS ARE OF AN ELDERLY MAN. WHO  MAY HAVE DIED TWO OR THREE YEARS AGO. OF NATURAL CAUSES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=147Watsonville kidnap>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Watsonville kidnap</H3><BR>
