<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Thursday, 4/23/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 4/23/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134SQ1 (SC gas line)>SQ1 (SC gas line)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(james earl ray obit)>(james earl ray obit)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107SC gas line break-IN>SC gas line break-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(man gives son aids)>(man gives son aids)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109SC gas line break-T>SC gas line break-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(movie bank robber)>(movie bank robber)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Slide reax/house>Slide reax/house</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Springer fake?-IN>Springer fake?-IN</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Filler trial starts>Filler trial starts</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/hollywood>Fox Biz/hollywood</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Hoolie kiddie porn>Hoolie kiddie porn</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145Trailor fire>Trailor fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125SC cthse fire folo>SC cthse fire folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43NBA Playoffs>NBA Playoffs</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Cannibus clubs-IN>Cannibus clubs-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98PGA Tour Golf>PGA Tour Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Longer school year>Longer school year</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142bring daughter to wk>bring daughter to wk</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(james earl) >Bump 1(james earl) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#148Kid safe>Kid safe</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(springer) >bump 2(springer) </A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=134SQ1 (SC gas line)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SQ1 (SC gas line)</H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
THOUSANDS OF SANTA CRUZ COUNTY RESIDENTS ARE STILL WITHOUT NATURAL GAS TONIGHT FOLLOWING YESTERDAY'S MAIN BREAK.
<P>
WE'LL TELL YOU HOW LONG THE PROBLEM IS EXPECTED TO LAST.
<P>
THR MURDER TRIAL OF THE MAN WHO WENT ON A SHOOTING SPREE AT FORD ORD LAST YEAR. GETS UNDERWAY TODAY. 
<P>
PLUS. FIST FIGHTS AND ALL. IT'S FAST BECOMING ONE OF THE MOST POPULAR DAY TIME TALK SHOWS ON TELEVISION. BUT HOW MUCH OF IT IS REAL.?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
TONIGHT  SANTA CRUZ COUNTY IS GRAPPLING WITH A PROBLEM THEY HAVEN'T SEEN SINCE THE 19-89 LOMA PRIETA EARTHQUAKE. 
<P>
NEARLY 70-THOUSAND HOMES AND BUSINESSES ARE WITHOUT NATURAL GAS. LEAVING ALMOST THE ENTIRE COUNTY. WITHOUT HEAT. STOVE AND SHOWER.
<P>
OUR JINAH KIM'S IS LIVE ON THE SCENE.
<P>
JINAH. WHAT'S THE LATEST?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107SC gas line break-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC gas line break-IN</H3><BR>
ALAN. 
<P>
THAT MEANS THOUSANDS WILL HEAD INTO THE WEEKEND WITHOUT SOME OF LIFE'S BASIC NECESSITIES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109SC gas line break-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC gas line break-T</H3><BR>
IN THE MEANTIME HERE ARE SOME HELPFUL:
<P>
NUMBERS.
<P>
THAT'S ALL FROM HERE.
<P>
REPORTING LIVE IN SANTA CRUZ. I'M JINAH KIM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Slide reax/house>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Slide reax/house</H3><BR>
AS JINAH MENTIONED. THE GAS MAIN BREAK WAS CAUSED BY A MUDSLIDE.
<P>
A NATURAL DISASTER THAT ALSO DESTROYED A LOG CABIN.
<P>
THE HILLSIDE SLID 500-FEET ALL TOGETHER.    
<P>
THE HOME BELONGED TO MARK AND KATHY BETTENCOURT.
<P>
        THEIR NEIGHBOR PAT SWINDELL WAS OUT SURVEYING THE DAMAGE TODAY.
<P>
        HER FATHER BUILT THIS HOUSE 20-YEARS AGO, AND SHE SOLD IT TO THE BETTENCOURTS, AFTER HE DIED.
<P>
        SWINDELL SAYS THE SLIDE WAS A TOTAL SURPRISE.
<P>
"THEY HAD A GEOLOGIST OUT HERE 3 OR 4 DAYS AGO AND HE SAID THERE HAD BEEN A MASSIVE SLIDE HERE, PROBABLY A COUPLE HUNDRED YEARS AGO. YOU COULD TELL BY THE SLOPE."
<P>
CREWS SAY THEY STILL DON'T KNOW WHAT TRIGGERED THE MUDSLIDE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Filler trial starts>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Filler trial starts</H3><BR>
IN A SAN JOSE FEDERAL COURTROOM TODAY. TRIAL GETS UNDERWAY FOR THE FORMER DEFENSE DEPARTMENT EMPLOYEE. ACCUSED OF SHOOTING TWO CO-WORKERS AT THE FORMER FORT ORD.
<P>
JOHN FILLER HAS PLEADED NOT GUILTY TO FIRST DEGREE MURDER. AND ATTEMPTED MURDER.
<P>
BUT TODAY, HIS  DEFENSE ATTORNEY ADMITTED THAT FILLER COMMITTED THE CRIME.
<P>
FILLER'S ATTORNEY SAYS HIS CLIENT HAD "DIMINISHED MENTAL CAPACITY" AT THE TIME OF THE SHOOTING. IN WHICH JOE LLOYD WAS MURDERED. AND JAMES GARAN WAS WOUNDED.
<P>
BUT THE LEAD PROSECUTOR  SAYS THIS IS A CLEAR CASE OF PREMEDITATED FIRST-DEGREE MURDER.
<P>
IT'S UPSETTING, THIS WAS PREMEDITATED. HE WENT WIT HTHE SOLE PURPOSE OF KILLING 1ST 2 MEN AT WORK. LUCID ENOUGH AS TO WHAT HE WAS DOING.
<P>
MRS. LLOYD IS ALSO UPSET OVER A DECISION MADE BY ATTORNEY GENERAL JANET RENO, NOT TO SEEK THE DEATH PENALTY IN THIS CASE.
<P>
FILLER FACES A MANDATORY TERM OF LIFE WITHOUT PAROLE. IF HE'S CONVICTED OF FIRST DEGREE MURDER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Hoolie kiddie porn>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hoolie kiddie porn</H3><BR>
A HOLLISTER MAN ACCUSED OF DELIVERING CHILD PORNOGRAPHY OVER THE INTERNET ENTERS HIS PLEA IN A SAN BENITO COUNTY COURTROOM TODAY.
<P>
42- YEAR -OLD BRIAN FRIEND  PLEADED  NOT GUILTY.
<P>
FRIEND WAS ARRESTED LAST MONTH AFTER AN EXTENSIVE SEVEN MONTH INVESTIGATION BY THREE LAW ENFORCEMENT AGENCIES.
<P>
IF CONVICTED. HE FACES UP TO THREE YEARS IN PRISON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145Trailor fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Trailor fire</H3><BR>
A MOBILE HOME IS DESTROYED. ANOTHER SERIOUSLY DAMAGED. WHEN A FIRE BREAKS OUT IN A MOBILE HOME PARK IN NORTH MONTEREY COUNTY.
<P>
THE PARK IS LOCATED ON SPRINGFIELD ROAD.OFF HIGHWAY ONE IN MOSS LANDING.
<P>
FIRE FIGHTERS SAY ONE PERSON. WHO WAS INSIDE ONE OF THE MOBILE HOMES WHEN THE FIRE BROKE OUT. GOT OUT SAFELY.
<P>
WITNESSES SAY THEY BELIEVE A BROKEN LIGHT-SWITCH MAY HAVE STARTED THE FIRE.  BUT OFFICIALS ARE STILL INVESTIGATING TONIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125SC cthse fire folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC cthse fire folo</H3><BR>
THAT ELECTRICAL FIRE AT THE SANTA CRUZ COUNTY COURTHOUSE WHICH WE TOLD YOU ABOUT LAST NIGHT. PUTS COUNTY BUSINESS ON HOLD TODAY.
<P>
THE COUNTY BUILDING HAD TO BE SHUTDOWN. AND WORKERS SENT HOME BECAUSE THE FIRE KNOCKED OUT POWER AND PHONES.
<P>
THE FIRE IS BEING BLAMED ON A SHORT IN A DEVICE ELECTRICIANS WERE USING TO REPAIR AN ELECTRICAL PANEL.
<P>
ONE MAN REMAINS IN THE HOSPITAL IN FAIR CONDITION AFTER SUFFERING 2ND AND 3RD DEGREE BURNS.
<P>
THE INDIVIDUALS. IN THE JAIL COURTHOUSE.
<P>
ALL COURT CASES SCHEDULED FOR TOMORROW WILL BE HEARD AT THE SCHEDULED TIMES. 
<P>
THE COUNTY BUILDING WILL BE CLOSED AGAIN TOMORROW FOR MORE REPAIR WORK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Cannibus clubs-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cannibus clubs-IN</H3><BR>
THE DEBATE CONTINUES TO RAGE OVER THE MEDICINAL 
<P>
USE OF MARIJUANA. 
<P>
EIGHTEEN MONTHS AFTER CALIFORNIA VOTERS APPROVED THE USE OF POT FOR MEDICAL PURPOSES.  CANNABIS "CLUBS". OPENED UNDER THE INITIATIVE. ARE BEING SHUT DOWN. 
<P>
FOX'S CLAUDIA COWAN VISITED ONE SUCH CLUB IN SAN FRANCISCO TO FIND OUT MORE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Longer school year>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Longer school year</H3><BR>
A LONGER SCHOOL YEAR MAY BE IN STORE FOR CALIFORNIA STUDENTS.
<P>
RIGHT NOW. DISTRICTS CAN SUBSTITUTE UP TO EIGHT DAYS OF CLASSROOM INSTRUCTION. WITH TEACHER TRAINING.
<P>
BUT A STATE PANEL HAS APPROVED A BILL THAT WOULD ELIMINATE THAT TRAINING. AND INCLUDE THOSE DAYS AS PART OF THE SCHOOL YEAR. EXTENDING THE CURRENT 180 DAY SCHOOL YEAR.
<P>
THE BILL IS NOW ON ITS WAY TO THE SENATE APPROPRIATIONS COMMITTEE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(james earl) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(james earl) </H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN. 
<P>
THE MAN CONVICTED OF KILLING MARTIN LUTHER KING HAS DIED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(springer) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(springer) </H3><BR>
IT'S ONE OF THE MOST POPULAR DAYTIME TALKS SHOWS AROUND. BUT NOW FORMER GUESTS ARE COMING FOWARD TO SAY. IT'S ALL AN ACT.
<P>
THOSE STORIES. RIGHT AFTER THIS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
THE MAN WHO CONFESSED TO KILLING DOCTOR MARTIN LUTHER KING JUNIOR. HAS DIED.
<P>
THAT STORY FROM NASHVILLE, TENNESSEE. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(james earl ray obit)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(james earl ray obit)</H3><BR>
70-YEAR-OLD JAMES EARL RAY SLIPPED INTO A COMA YESTERDAY. 
<P>
HE SUFFERED FROM LIVER CANCER. AND HAD BEEN IN AND OUT OF THE HOSPITAL  A DOZEN TIMES SINCE DECEMBER OF 19-96.
<P>
RAY PLEADED GUILTY TO KILLING KING IN 19-68. BUT SOON RECANTED.
<P>
KING'S FAMILY AND OTHER CIVIL RIGHTS LEADERS FOUGHT TO WIN RAY A NEW TRIAL. TO NO AVAIL.
<P>
LAST SUMMER. A TEST TO PROVE RAY'S INNOCENCE BY RE-FIRING THE RIFLE USED TO SHOOT KING.  PROVED INCONCLUSIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(man gives son aids)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(man gives son aids)</H3><BR>
IN COLUMBIA, ILLINOIS.
<P>
A MEDICAL ASSISTANT PLEADS GUILTY TO INJECTING HIS SON WITH H-I-V INFECTED BLOOD. TO GET OUT OF PAYING CHILD SUPPORT FOR HIM. 
<P>
BRIAN STEWART IS BEING HELD ON 5-HUNDRED THOUSAND DOLLARS BAIL. 
<P>
HIS 7-YEAR-OLD SON HAS DEVELOPED AIDS. AND PROSECUTORS SAY THE FATHER WILL BE CHARGED WITH MURDER IF THE BOY DIES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(movie bank robber)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(movie bank robber)</H3><BR>
POLICE ARE LOOKING FOR A BANK ROBBER WHO MADE OFF WITH STOLEN LOOT. THEN MADE AN APPEARANCE ON THE JERRY SPRINGER SHOW.
<P>
JEFFREY DERN ALLEGEDLY ROBBED BANKS IN THE SAME STYLE AS THE MOVIE "HEAT" STARRING AL PACINO AND ROBERT DENIRO.
<P>
THEN. WITH POLICE HOT ON HIS TRAIL. HE APPEARED ON THE JERRY SPRINGER SHOW. TO TALK ABOUT DATING TRANSEXUALS.
<P>
POLICE SAY SPRINGER IS COOPERATING IN THE INVESTIGATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Springer fake?-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Springer fake?-IN</H3><BR>
FORMER GUESTS ON THE JERRY SPRINGER SHOW ARE NOW WISHING THEY HADN'T COOPERATED WITH THE SHOW'S PRODUCERS.
<P>
THE GUESTS ARE COMING FORWARD TO SAY THE FIGHTS. THAT HAVE MADE THE SHOW SO POPULAR WITH ITS FANS. WERE ACTUALLY STAGED. 
<P>
FOX'S GRANT RAMPY HAS THE STORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/hollywood>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/hollywood</H3><BR>
CALIFORNIA IS ONCE AGAIN THE PLACE TO MAKE MOVIES.
<P>
WITH THE ENTERTAINMENT INDUSTRY PUMPING ALMOST 30-BILLON DOLLARS INTO THE STATE'S ECONOMY.
<P>
DETAILS IN TONIGHT'S FOX BUSINES REPORT.
<P>
ACCORDING TO A NEW STUDY BY THE MOTION PICTURE ASSOCIATION OF AMERICA. MOVIE, TELEVISION AND COMMERCIAL PRODUCTION SKYROCKETED. ALMOST 70-PERCENT FROM 19-92 TO 19-96.
<P>
ABOUT TWO-THIRDS OF ALL U-S FEATURE FILMS WERE MADE IN CALIFORNIA DURING 19-92. BY 19-96. THAT NUMBER JUMPED TO MORE THAN 80-PERCENT.
<P>
THE NUMBER OF FILM PRODUCTIONS DURING THAT PERIOD JUMPED FROM 319 TO 572.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
THE WHEELS ARE COMING OFF FOR THE GIANTS. LAST NIGHT BARRY BONDS AND DANNY DARWIN GOT INTO A SCUFFLE.
<P>
TODAY, THEIR SO-CALLED ACE, SHAWN ESTES, DROPS TO 0 AND 4, WITH AN ERA OF 6.6.
<P>
THE GIANTS HAVE LOST 6 OF 7, THEY'RE A GAME UNDER.500, AND THEY TRAIL THE PADRES BY 6 AND A HALF.
<P>
I KNOW ITS EARLY, BUT COME ON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
LAST NIGHT THE SHARKS LOST GAME ONE OF THEIR BEST OF SEVEN GAME SERIES WITH THE DALLAS STARS BY A SCORE OF 4 TO 1.
<P>
NOW THE SHARKS MAY HAVE LOST THE BATTLE, BUT IT APPEARS THERE WILL BE MANY WARS TO COME.
<P>
DOWN 2 TO 1 IN THE FIRST PERIOD, THE SHARKS BRYAN MARCHMENT CHECKED THE STARS LEADING SCORER, JOE NIEUWENDYK INTO THE BOARDS.
<P>
NO PENALTY WAS CALLED, BUT NIEUWENDYK INJURED HIS KNEE, HE HAD TO LEAVE THE GAME, DOCTORS SAY HE'LL BE OUT ABOUT 2-WEEKS.
<P>
WHILE PLAYING FOR EDMONTON THIS SEASON, MARCHMENT INJURED STARS CAPTAIN MIKE MADANO.
<P>
RETALIATION COULD BE IN THE WORKS.
<P>
GAME TWO IS FRIDAY NIGHT IN DALLAS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43NBA Playoffs>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA Playoffs</H3><BR>
TODAY THE SUNS DANNY MANNING IS NAMED THE NBA'S 6TH MAN OF THE YEAR, EDGING OUT THE LAKERS KOBE BRYANT.
<P>
TOO BAD FOR PHOENIX THAT MANNING IS OUT FOR THE YEAR WITH A KNEE INJURY.
<P>
TONITE THE SUNS BEGIN THEIR FIRST ROUND, BEST OF 5-GAME PLAYOFF SERIES WITH THE SPURS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98PGA Tour Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PGA Tour Golf</H3><BR>
TO GOLF, AND THE PGA TOUR STOPS IN NORTH CAROLINA TODAY, FOR THE 1ST ROUND OF THE GREATER GREENSBORO OPEN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142bring daughter to wk>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bring daughter to wk</H3><BR>
A SPECIAL DAY FOR DAUGHTERS AND PARENTS IN THE WORK FORCE  ACROSS THE NATION TODAY.
<P>
EVEN THOUGH IT WAS TAKE YOUR DAUGHTERS TO WORK DAY.  HERE ON THE CENTRAL COAST.NOBODY WAS LEFT OUT.
<P>
NIECES. NEPHEWS. GRANDCHILDREN. ALL ACCOMPANIED GROWNUPS TO WORK.
<P>
THE MS. FOUNDATION CREATED  "TAKE OUR DAUGHTERS TO WORK DAY" SIX YEARS AGO. ON THE HEELS OF RESEARCH THAT REVEALED A DROP IN SELF-ESTEEM, AS GIRLS APPROACH ADOLESCENCE. 
<P>
THIS IS THE FIRST YEAR HOWEVER.MONTEREY COUNTY HAS STRAYED FROM THE TREND AND DECIDED TO INVITE ALL KIDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=148Kid safe>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kid safe</H3><BR>
A NEW PROGRAM KICKS OFF TODAY ON THE PENINSULA.DESIGNED TO KEEP KIDS SAFE BY PUTTING VITAL INFORMATION RIGHT AT THE "FINGERTIPS" OF PARENTS.
<P>
IT'S CALLED THE "KIDS-SAFE" PROGRAM.
<P>
IT'S A CHILD INDENTIFICATION PROJECT STARTED BY THE BOYS AND GIRLS CLUB.
<P>
EACH CHILD GETS A KIT COMPLETE WITH A CURRENT PHOTO, FINGERPRINTS, AND EMERGENCY INFORMATION RELATING TO THE CHILD'S IDENTITY.
<P>
THIS PROGRAM WILL CONTINUE THROUGH SATURDAY.
<P>
IF YOU WANT TO PICK UP A KIDSAFE KIT.STOP BY THE BOYS AND GIRLS CLUB ON LA SALLE AVENUE IN SEASIDE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
