<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 4/4/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 4/4/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x040403.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#8Pesticide Conf.-I>Pesticide Conf.-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Pinnacles Re-open>Pinnacles Re-open</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#9Pesticide Conf.-G>Pesticide Conf.-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38Giants >Giants </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#10Pesticide Conf.-T>Pesticide Conf.-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39McGwire>McGwire</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#11SC Church Fire>SC Church Fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114SC Harley Museum>SC Harley Museum</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#12Sex Assault Month>Sex Assault Month</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#19Planes Collide>Planes Collide</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Michigan>Michigan</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Brush Fire>Brush Fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Disney Animals>Disney Animals</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#24Tragedy Museum>Tragedy Museum</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121Pig Kiss>Pig Kiss</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Ukraine Mine Blast>Ukraine Mine Blast</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Wag'n Walk>Wag'n Walk</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117Horse Race>Horse Race</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106Good Old Days-I>Good Old Days-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119Rube Contest>Rube Contest</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#105Good Old Days-T>Good Old Days-T</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=8Pesticide Conf.-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pesticide Conf.-I</H3><BR>
AT FIRST GLANCE IT SEEMS VERY APPROPRIATE TO HAVE IT IN WATSONVILLE. SINCE IT IS A GIANT CENTER OF AGRICULTURE IN THE STATE.
<P>
BUT IF YOU THINK THIS CONVENTION IS GEARED TOWARDS FARMERS AND BIG BUSINESSES. YOU'LL BE SURPRISED TO KNOW. IT'S GEARED TOWARDS FOLKS LIKE YOU AND ME. AND ABOUT THE CHEMICALS WE USE EVERY DAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=9Pesticide Conf.-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pesticide Conf.-G</H3><BR>
ONE OF THE MOST POPULAR WORKSHOPS AT THE NATIONAL PESTICIDE CONVENTION TODAY HAD NOTHING TO DO WITH THE HEAVY, INDUSTRIAL USE OF THE CHEMICALS.
<P>
IT WAS ABOUT DAY-TO-DAY EXPOSURE TO PESTICIDES RIGHT IN YOUR OWN HOME.
<P>
THAT'S WHY *THESE* INQUIRING MINDS PACKED THE THREE-DAY CONVENTION.
<P>
THEY CAME FROM ALL OVER THE COUNTRY TO HEAR ABOUT HOW YOU *NEVER* NEED TO USE WEED KILLERS, OR BOMBS OR FOGGERS OR SPRAYS OF *ANY* SORT.
<P>
SO WHY DO PEOPLE USE SO MANY CHEMICALS IN *AND* OUT OF THE HOME?
<P>
THE CONFERENCE IS ALL ABOUT LEARNING. AND PARTICIPANTS WERE URGED TO FIRST AND FOREMOST, GET EDUCATED. THEN PUT IT TO WORK FOR YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=10Pesticide Conf.-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pesticide Conf.-T</H3><BR>
IF YOU THINK YOU COULD STAND TO LEARN A FEW THINGS FROM THIS PESTICIDE CONFERENCE. IT'S NOT TOO LATE.
<P>
IT CONTINUES TOMORROW AT THE MOUNT MADONNA CONFERENCE CENTER, WHICH IS LOCATED TWO MILES UP SUMMIT ROAD, OFF HIGHWAY 152.
<P>
CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=11SC Church Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Church Fire</H3><BR>
ONE MAN IS HURT AFTER A CHURCH GOES UP IN FLAMES
<P>
THE BLAZE STARTED IN A VAN BEHIND "EVANGELICAL FREE CHURCH" ON GRAHAM HILL ROAD IN FELTON AROUND TEN-30 LAST NIGHT.
<P>
FIRE-FIGHTERS IT HAD THE POTENTIAL TO BE MUCH WORSE.
<P>
THE UNIDENTIFIED MAN SUFFERS SECOND AND THIRD DEGREE BURNS.
<P>
HE WAS TRANSPORTED TO THE SANTA CLARA BURN UNIT.
<P>
FIRE OFFICIALS ESTIMATE THE DAMAGE AT 40-THOUSAND DOLLARS.
<P>
THE CAUSE OF THE BLAZE IS UNDER INVESTIGATION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114SC Harley Museum>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Harley Museum</H3><BR>
MORE THAN ONE-THOUSAND PEOPLE SHOW UP IN SANTA CRUZ TODAY FOR THE GRAND OPENING OF THE NEW HARLEY DAVIDSON MUSEUM.
<P>
IT'S ACTUALLY PART OF THE MOTORCYCLE SHOP ON SOQUEL AVENUE.
<P>
IT FEATURES VINTAGE BIKES, SPORT CYCLES, AND HISTORIC PHOTOGRAPHS.
<P>
THE GENERAL MANAGER SAYS THE MUSEUM IS ONE OF THE FIRST TO HAVE A SHOWROOM FULL OF MEMORABILIA FROM THE HARLEY DAVIDSON ARCHIVES.     
<P>
"SANTA CRUZ IS A GREAT TOWN.  THERE'S A MILLION THINGS TO DO IN SANTA CRUZ AND SO WE FELT PEOPLE WOULD DRIVE TO SANTA CRUZ, SEE THE MUSEUM, GET A GOOD MEAL ON PACIFIC AVENUE, WHATEVER, AND JUST REALLY HAVE A FUN TIME IN SANTA CRUZ."
<P>
AS PART OF THE CELEBRATION, LIVE ENTERTAINMENT AND A BARBECUE WERE ALSO PROVIDED OUTSIDE THE SHOP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=12Sex Assault Month>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sex Assault Month</H3><BR>
THE WOMEN'S CRISIS CENTER IN SALINAS REACHES TO THE PUBLIC FOR AN IMPORTANT EDUCATION PROGRAM. 
<P>
APRIL IS "SEXUAL ASSAULT AWARENESS MONTH".
<P>
WOMEN GATHERED TODAY AT HARTNELL COLLEGE FOR A SELF-DEFENSE CLASS.
<P>
THE SELF-DEFENSE CLASS IS THE FIRST OF SEVERAL EVENTS TO BE HELD FOR SEXUAL ASSAULT AWARENESS MONTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=19Planes Collide>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Planes Collide</H3><BR>
FOUR PEOPLE ARE DEAD AFTER A MID-AIR COLLISION NEAR ATLANTA. 
<P>
IT HAPPENED EARLY THIS MORNING AS A PRIVATE JET AND A SINGLE ENGINE PLANE CROSSED PATHS. 
<P>
BOTH PILOTS WERE KILLED AND TWO PASSENGERS IN THE JET. 
<P>
A  WITNESS SAYS THE PLANES WENT NOSE-FIRST INTO THE GROUND.
<P>
THE F-A-A ADMINISTRATION AND THE NATIONAL 
<P>
TRANSPORTATION SAFETY BOARD ARE  INVESTIGATING THE CRASH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Brush Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Brush Fire</H3><BR>
IN COLORADO.  A HOME IS DESTROYED.THREE OTHERS SCORCHED. AFTER A GRASS FIRE IS TRIGGERED BY A MODEL ROCKET. 
<P>
AN 8-YEAR-OLD BOY AND HIS 30-YEAR-OLD FATHER SAY THEIR MODEL ROCKET FELL OVER AND SHOT OFF THROUGH THE GRASS.  
<P>
IT CAUSED ABOUT 500-THOUSAND DOLLARS IN DAMAGES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Disney Animals>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Disney Animals</H3><BR>
DISNEY OFFICIALS ARE SCRATCHING THEIR HEADS OVER A RASH OF BIZARRE ANIMAL DEATHS AT THEIR NEWEST FLORIDA ATTRACTION. 
<P>
DISNEY'S ANIMAL KINGDOM IS SET TO OPEN IN THREE WEEKS.AND THE ORLANDO ATTRACTION HAS ALREADY LOST ALMOST A DOZEN ANIMALS. 
<P>
AUTHORITIES SAY. FOUR CHEETAH CUBS DIED AFTER SWALLOWING A DEADLY CHEMICAL COMMONLY FOUND IN ANTI-FREEZE.  TWO WEST AFRICAN BIRDS WERE RUN OVER BY PARK TOUR BUSES.  AND A HIPPOPOTAMUS DIED OF BLOOD POISONING. 
<P>
THREE HERD ANIMALS ALSO DIED OF UNKNOWN CAUSES. 
<P>
AN INVESTIGATION INTO THE DEATHS IS NOW UNDERWAY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=24Tragedy Museum>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tragedy Museum</H3><BR>
AND. ALSO IN FLORIDA. YOU CAN BUY A PIECE OF "TRAGEDY". 
<P>
THE CONTENTS OF THE FORMER "TRAGEDY IN U-S" MUSEUM ARE GOING ON THE AUCTION BLOCK IN SAINT AUGUSTINE. 
<P>
AMONG THE ITEMS UP FOR GRABS: FURNITURE ONCE OWNED BY LEE HARVEY OSWALD. AND BONNIE AND CLYDE'S GETAWAY CAR. COMPLETE WITH BULLET HOLES. 
<P>
THE MUSEUM CLOSED ITS DOORS LAST MONTH AFTER ITS FOUNDER DIED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Ukraine Mine Blast>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ukraine Mine Blast</H3><BR>
AT LEAST 23 MINERS ARE DEAD.37 MISSING AFTER AN EXPLOSION AT A COAL MINE IN  UKRAINE. 
<P>
EFFORTS ARE CONTINUING TO  LOCATE SURVIVORS TRAPPED IN THE CAVES BELOW THE CITY.
<P>
FIVE MINERS WERE TAKEN TO AREA HOSPITALS. 
<P>
THE CITY IS BUILT ON TOP OF THE COALFIELD. AND THOUSANDS FLOCKED TO THE OPENING OF THE MINESHAFT.  WAITING ANXIOUSLY FOR NEWS OF RELATIVES AND FRIENDS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117Horse Race>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Horse Race</H3><BR>
15-HUNDRED POLICE AND SECURITY OFFICERS ARE PUT ON GUARD FOR ENGLAND'S GRAND NATIONAL STEEPLECHASE 
<P>
LAST YEAR IT WAS POSTPONED AFTER TWO BOMB THREATS FROM IRISH REPUBLICAN ARMY GUERRILLAS.
<P>
EVERY RACEGOER WAS SEARCHED AND HAD TO PASS THROUGH METAL DETECTORS. 
<P>
LAST YEAR ABOUT 60-THOUSAND RACEGOERS HAD TO FLEE THE TRACK AFTER I-R-A THREATS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119Rube Contest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Rube Contest</H3><BR>
STUDENTS FROM THE UNIVERSITY OF TEXAS WIN THE RUBE GOLDBERG AWARD FOR THE SECOND YEAR IN A ROW. 
<P>
THE ANNUAL COMPETITION OF IMAGINATION AND CREATIVITY. HONORS GOLDBERG WHO WAS A FAMOUS CARTOONIST KNOWN FOR DRAWING COMPLICATED MACHINES THAT PERFORMED VERY SIMPLE TASKS. 
<P>
THE TASK OF THE TEXAS TEAM'S INVENTION WAS TO USE 20 DIFFERENT STEPS TO HIT THE SNOOZE BUTTON ON AN ALARM CLOCK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Pinnacles Re-open>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pinnacles Re-open</H3><BR>
THE PINNACLES NATIONAL MONUMENT IS RE-OPENED TO THE PUBLIC.
<P>
REPAIRS TO STORM DAMAGED ROADS AND TRAILS ARE COMPLETE. 
<P>
VISITORS ARE NOW ALLOWED ACCESS TO THE EAST SIDE OF THE PARK. OFF HIGHWAY 25 IN SAN BENITO COUNTY.
<P>
THE *WEST* ENTRANCE WILL REMAIN CLOSED FOR ANOTHER SEVERAL WEEKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38Giants >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants </H3><BR>
WE'RE JUST FIVE GAMES INTO THE BASEBALL SEASON. BUT THE GIANTS ALREADY HAVE SHOWN THE SAME WINNING ATTITUDE THAT LED THEM TO THE DIVISION TITLE LAST YEAR.
<P>
GIANTS AND D-BACKS AT THE BOB.
<P>
---------
<P>
ARIZONA UP 3-NOTHING IN THE 7TH. WHEN  GETS THE RALLY GOING. HE SMOKES ONE TO LEFT AND THIS ONE'S NOT COMING BACK. A 2-RUN HOMER FOR JOHNSON. HIS FIRST OF THE SEASON. GAME TIED AT THREE.
<P>
--------
<P>
THE GIANTS WOULD SCORE 4-RUNS IN THE INNNING.  BREAKS UP THE TIE WITH AN RBI SINGLE THAT SCORES.
<P>
--------
<P>
SAN FRANCISO WITH A 5-3 LEAD INTO THE 9TH. AND IT'S TIME FOR. HE GET'S. JOHNSON THROWS HIM OUT AT FIRST TO END THE GAME. AS THE GIANTS WIN FOR THE 4TH TIME IN FIVE GAMES. 5-3 IS THE FINAL. NENN GETS HIS FIRST SAVE.  PICKS UP THE WIN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39McGwire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>McGwire</H3><BR>
CONTINUES TO THUMP THE BASEBALL IN ST. LOUIS AND TODAY HE TIED  NATIONAL LEAGUE
<P>
RECORD BY HITTING HIS 4TH HOMER IN AS MANY GAMES.
<P>
A 3-RUN JOB OFF. BIG MAC NOW WITH 12 RIBBIES. ALL COMING FROM THE LONG BALL.AS THE CARDS GO ON TO BEAT THE PADRES.    
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
AFTER GETTING RAINED OUT ON FRIDAY. THE A'S BATS PROVIDED THE THUNDER TODAY. BASHING THE YANKEES TO PICK UP THIER FIRST WIN OF THE SEASON.
<P>
CLUB STILL WINLESS.
<P>
---------
<P>
THE A'S WOULD TRAIL 3-ZIP UNTIL THE 5TH.  HANGS ONE AND  JUMPS ON IT. A TWO -RUN SINGLE FOR RICKEY. IT SCORES  AND. CUTTING THE LEAD TO 3-2.
<P>
----------
<P>
THE A'S GO OFF IN THE 6TH. SPEZIO AT THE PLATE WITH THE BASES FULL. AND IT'S ALL GOOD. BABY. A GRAND SLAM FOR SPEZIO. THE 2ND OF HIS CAREER. IT'S PART OF A 5 RUN 6TH. FINAL. 7-3.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
THE WARRIORS HAVE WON JUST 16 GAMES THIS SEASON. AND WITH 8-GAMES LEFT. IT'S UNLIKLEY THEY'LL BREAK THE FRANCHISE RECORD FOR FUTILITY.
<P>
IN 1964. THE WARRIORS WON JUST 17 GAMES. BUT TWO YEARS LATER. RICK BARRY LED THEM TO THE NBA FINALS.
<P>
WARRIORS IN SAN ANTONIO.  LAUNCHS THE BUZZER BEATER. AND IT GOES. WARRIORS DOWN 2 AT THE BREAK.
<P>
-----------
<P>
GOLDEN STATE WOULD HOLD SAN ANTONIO TO 11 4TH QUARTER POINTS.  SPURS THE RUN THAT GETS THE WARRIORS BACK INTO THE GAME.
<P>
-----------
<P>
SCORES 20-POINTS TO GO WITH 14 REBOUNDS. THIS GAME GOES TO OVERTIME.
<P>
-----------
<P>
BUT IN THE O-T. THE SPURS PULL AWAY. THEY WIN IT 88-80. IT'S THEIR 5TH STRAIGHT VICTORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
WHILE THE WARRIORS ARE FLOUNDERING. THE SHARKS ARE SWIMING TOWARD A PLAYOFF SPOT.
<P>
SAN JOSE JUST 2-POINTS BACK OF THE IDLE OILERS FOR THE 8TH AND FINAL PLAYOFF SPOT IN THE WEST.
<P>
THE SHARKS IN TORONTO. GAME TIED AT THREE IN THE 3RD PERIOD.
<P>
WHEN LEAFS GOALIE  GET'S CAUGHT OUT OF THE NET. 
<P>
TAKES ADVANTAGE AND BREAKS THE TIE WITH HIS 30TH GOAL OF THE SEASON. HIS 2ND OF THE GAME AS THE SHARKS WIN. 5-3 AND PULL EVEN WITH EDMONTON FOR THE FINAL PLAYOFF SPOT. WITH JUST 6-GAMES REMAINING IN THE SEASON.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Michigan>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Michigan</H3><BR>
MICHIGAN AND BOSTON COLLEGE    IN THE N-C DOUBLE-A CHAMPIONSHIP GAME. 
<P>
---------
<P>
THIS ONE TIED AT TWO IN OVERTIME. WHEN MICHIGAN'S  SCORES THE GAME WINNER. THE FRESHMAN BEATING  WHO HAD STOPPED 32 SHOTS BEFORE LETTING THE GAME WINNER BY.
<P>
3-2 IS THE FINAL. IT'S THE 9TH HOCKEY TITLE FOR THE WOLVERIENS. A NEW N-C DOUBLE A RECORD. NO OTHER SCHOOL HAS MORE THAN SIX.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
IN GOLF. BRITIAN'S  IS THE LEADER AFTER 3-ROUNDS OF THE FREEPORT-MCDERMOT CLASSIC.
<P>
THE 24-YEAR OLD IS LOOKING FOR HIS FIRST U-S VICTORY. HE HAS A 1-SHOT LEAD OVER 2ND ROUND LEADER.
<P>
3RD ROUND ACTION FROM THE SENIOR TRADITION IN SCOTTSDALE ARIZONA.
<P>
-----------
<P>
WITH THE BIRDIE PUTT AT 15. THE GOOD DOCTOR WITH A 69. HE'S TWO SHOTS OFF THE LEAD.
<P>
------------
<P>
HERE'S THE GUY HE'S CHASING.  SAVING PAR AT 17. HE ALSO SHOOTS A 69. HE'S 12-UNDER.   LEADS A LIST OF FOUR OTHER GOLFERS 6-SHOTS BEHIND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
USA TAKING ON RUSSIA IN DAVIS CUP ACTION.BIG DAY FOR.
<P>
-----------
<P>
FACING 18 YEAR OLD. AGASSI NEEDED JUST  1-HOUR AND 35 MINUTES TO FINISH OFF THE YOUNGSTER.
<P>
----------
<P>
NOW RANKED 22ND IN THE WORLD. AGASSI WOULD WIN IN STRAIGHT SETS. 6-3 IN THE 3RD. IT'S HIS 16TH CONSECUTIVE DAVIS CUP VICTORY. TYING THE AMERICAN RECORD SET BY  IN 1926. THE BEST OF FIVE SERIES IS TIED AT ONE MATCH APIECE AFTER DAY ONE. PLAY CONTINUES ON SUNDAY.   
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121Pig Kiss>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pig Kiss</H3><BR>
AN ELEMENTARY SCHOOL PRINCIPAL HAD TO PUCKER UP AND KISS A PIG FOR HIS SCHOOL TODAY. 
<P>
TOM IRVIN PROMISED  IF STUDENTS AT STINE ELEMENTARY SCHOOL IN BAKERSFIELD COULD RAISE TWO THOUSAND DOLLARS FOR NEW PLAYGROUND EQUIPMENT.HE WOULD KISS A SWINE. 
<P>
SO.  KIDS AND PARENTS HAVE BEEN DONATING MONEY TOWARD THE NEW PROJECT.
<P>
THEY WENT ABOVE THE TWO THOUSAND MARK.SO IRVIN GAVE THIS PIG A BIG FAT KISS FOR HIS STUDENTS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=112Wag'n Walk>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Wag'n Walk</H3><BR>
IT'S TRUE. MAN IS DOG'S BEST FRIEND. ESPECIALLY THIS MORNING IN MONTEREY.
<P>
IT'S THE THIRD ANNUAL "WAG AND WALK" EVENT. A FUND RAISER FOR THE LOCAL S-P-C-A.
<P>
MORE THAN 5-HUNDRED DOGS. ACCOMPANIED BY HUMANS ON A LEASH. SHOWED UP FOR THE WALK ALONG THE REC TRAIL. FROM CANNERY ROAD TO PACIFIC GROVE.
<P>
THE SPCA HOPES TO RAISE 60-THOUSAND DOLLARS FROM THIS YEAR'S EVENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106Good Old Days-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good Old Days-I</H3><BR>
IT'S AMERICA'S LAST HOMETOWN.AND TODAY.THOUSANDS WERE IN THE STREETS.
<P>
THIS WEEKEND IS THE ANNUAL "GOOD OLD DAYS" CELEBRATION IN PACIFIC GROVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=105Good Old Days-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good Old Days-T</H3><BR>
ALL THE FUN AT GOOD OLD DAYS CONTINUES TOMORROW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
