<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Thursday, 4/2/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Thursday, 4/2/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x040206.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134SQ1 (Toxic)>SQ1 (Toxic)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Virginia Tornado-IN>Virginia Tornado-IN</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO JINAH>TOSS TO JINAH</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Toxic Tour-INT>Toxic Tour-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(shooting spree)>(shooting spree)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Toxic Tour-GUT>Toxic Tour-GUT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(Michael Fay/drugs)>(Michael Fay/drugs)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Toxic Tour-TAG>Toxic Tour-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(cult moves)>(cult moves)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Second chance>Second chance</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142(base closings)>(base closings)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141Davis guilty>Davis guilty</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137(NASA telescope)>(NASA telescope)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Kicking Butts>Kicking Butts</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/job fair>Fox Biz/job fair</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Big Sur Marathon >Big Sur Marathon </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Carmel water>Carmel water</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131SC DUI arrest suit>SC DUI arrest suit</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Paula Jones folo-IN>Paula Jones folo-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Seniors Golf>Seniors Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(Virginia) >Bump 1(Virginia) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Monterey Wine fest>Monterey Wine fest</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(Mike Fay) >bump 2(Mike Fay) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Monterey Jazz fest>Monterey Jazz fest</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=134SQ1 (Toxic)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SQ1 (Toxic)</H3><BR>
UP NEXT ON KCBA FOX NEWS.
<P>
WE'LL TELL YOU WHY SOME PARENTS SAY THERE'S TROUBLE THAT NEEDS TO BE WEEDED OUT IN ONE LOCAL SCHOOL.
<P>
WILL RUNNERS HAVE PAVEMENT TO POUND ON FOR THE BIG SUR MARATHON?WE'LL HAVE THE ANSWER.
<P>
AND.TIRED OF HEARING ABOUT THE PAULA JONES/CLINTON CASE.GLAD IT'S OVER?WE'LL THINK AGAIN.THERE'S MORE TO COME.
<P>
ALL THE DAY'S TOP STORIES.SANDHYA WITH WEATHER.KEN WITH GIANTS HIGHLIGHTS.
<P>
I'M CHERI GYURO.KCBA FOX NEWS IS NEXT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO JINAH>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO JINAH</H3><BR>
GOOD EVENING, AND THANKS FOR JOINING US. I'M CHERI GYURO. ALAN MARSDEN HAS THE NIGHT OFF.
<P>
A POPULAR WEED KILLER COMES UNDER ATTACK AT A LOCAL ELEMENTARY SCHOOL.
<P>
PARENTS AND TEACHERS BAND TOGETHER DEMANDING THAT SCHOOL OFFICIALS STOP SPRAYING THE CAMPUS WITH THE PESTICIDE OR HERBICIDE.
<P>
JINAH KIM JOINS US FROM THE NEWS DESK WITH THE STORY.
<P>
JINAH WHAT PRODUCT ARE WE TALKING ABOUT?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Toxic Tour-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Toxic Tour-INT</H3><BR>
THE PESTICIDE IS "ROUNDUP" AND YOU CAN FIND IT ON THE SHELF OF JUST ABOUT ANY HARDWARE STORE.
<P>
IT'S BEEN USED IN THE PAJARO UNIFIED SCHOOL DISTRICT FOR YEARS. AND THE MAKERS OF ROUNDUP SAY THE SUBSTANCE IS SAFER THAN TABLE SALT.
<P>
BUT SOME PARENTS AND TEACHERS IN THE DISTRICT SAY, TO THE CONTRARY, IT'S ONE OF THE BIGGEST CAUSES OF SKIN AND EYE ILLNESSES AROUND. AND THEY WANT IT BANNED FROM SCHOOLS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Toxic Tour-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Toxic Tour-GUT</H3><BR>
A TOUR OF OHLONE ELEMENTARY SCHOOL IN PAJARO REVEALS A NOTICEABLY DEAD, BROWNED STRETCH OF SHRUBBERY OUTLINING MUCH OF THE SCHOOL.
<P>
THE CAUSE, ACCORDING TO ANTI-PESTICIDE GROUPS THAT ARRANGED THE TOUR TODAY:  THE HEAVY. AND CARELESS USE OF THE POPULAR WEED KILLER "ROUNDUP."
<P>
BUT THE POINT OF TODAY'S TOUR WASN'T TO POINT OUT HOW AESTHETICALLY DAMAGING "ROUNDUP" IS.
<P>
TEACHERS, PARENTS AND RESIDENTS WITHIN THE PAJARO UNIFIED SCHOOL DISTRICT BROUGHT DOCUMENTS THAT SHOWED HOW DANGEROUS THE HERBICIDE IS. ESPECIALLY TO YOUNG CHILDREN. AND THEY WANT DISTRICT ADMINSTRATORS TO FIND AN ALTERNATIVE WEED CONTROLLER.
<P>
WHILE A PROFESSIONAL LANDSCAPER POINTED OUT THE SCHOOL'S GARDENING DEFICIENCIES. THE DISTRICT SUPERINTENDENT STEPPED IN TO DEFEND HIS ADMINSTRATION'S PRACTICES.
<P>
THAT SET OFF A PUBLIC DEBATE THAT HAD EVERYONE GIVING A PIECE OF THEIR MIND.   
<P>
====BUTT TO====
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Toxic Tour-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Toxic Tour-TAG</H3><BR>
SUPERINTENDENT CASEY SAYS ONE SCHOOL HAS ALREADY STOPPED USING "ROUNDUP" FOR A YEAR NOW. AND THAT SCHOOL WILL BE USED AS A PILOT PROGRAM TO SEE IF OTHER SCHOOLS SHOULD FOLLOW SUIT.
<P>
HE SAYS HE'S WILLING TO CONSIDER ALL THE ALTERNATIVES. BUT IT TAKES TIME.
<P>
BUT ANTI-PESTICIDE GROUPS SAY EVERY DAY IT TAKES FOR HIM TO MAKE THAT DECISION. IS ONE MORE DAY CHILDREN ARE EXPOSED TO THE WEED KILLER.
<P>
CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Second chance>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Second chance</H3><BR>
THE FUTURE OF MONTEREY COUNTY'S ONLY GANG OUTREACH PROGRAM IS IN QUESTION.
<P>
SALINAS TAXPAYERS HAVE BEEN SUPPORTING PART OF THE SECOND CHANCE YOUTH PROGRAM SINCE 19-90.
<P>
THE CITY DONATES 127-THOUSAND DOLLARS TO SECOND CHANCE EVERY YEAR.
<P>
BUT MAYOR ALAN STYLES SAYS THE CITY COUNCIL IS LOOKING INTO USING THAT MONEY FOR OTHER AT-RISK YOUTH PROGRAMS.
<P>
"IT'S NOT AN ISSUE OF MOVING OUT.CANT CUT IT.IT'S WHAT IT'S DOING.GETTING EVALUATED AND LOOK AT ITS EFFECTIVENESS."
<P>
SECOND CHANCE ORGANIZERS SAY THEY NEED THE MONEY.TO KEEP THE REPORE ALREADY ESTABLISHED WITH MANY KIDS TRYING TO LEAVE GANGS.
<P>
COUNCIL MEMBERS WILL TACKLE THE TOUGH DECISION DURING BUDGET HEARINGS IN MAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141Davis guilty>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Davis guilty</H3><BR>
A SALINAS WOMAN IS CONVICTED OF DRIVING HER CAR WHILE HIGH ON HEROIN. AND CAUSING A FATAL HEAD-ON COLLISION. 
<P>
LISA MICHELLE DAVIS NOW FACES UP TO 26 YEARS IN PRISON.
<P>
LAST MAY.DAVIS SLAMMED HEAD-ON INTO 74-YEAR-OLD MELIDA VILLAREAL.
<P>
THE WOMEN WERE DRIVING IN OPPOSITE DIRECTIONS ON HIGHWAY 183 NEAR CASTROVILLE.
<P>
THE CONVICTION INCLUDES GROSS VEHICULAR MANSLAUGHTER. AND A NUMBER OF DRUG CHARGES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Kicking Butts>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Kicking Butts</H3><BR>
TODAY. ACROSS THE U-S. IT'S "KICK BUTTS" DAY. 
<P>
THE THIRD ANNUAL EVENT IS DESIGNED TO RALLY YOUNG PEOPLE AGAINST TOBACCO USE. 
<P>
TO ATTRACT LOCAL ATTENTION. CONGRESSMAN SAM FARR VISITED KIDS AT WESTLAKE ELEMENTARY IN SANTA CRUZ. 
<P>
        HE TALKED ABOUT HIS DAUGHTER'S STRUGGLE WITH TOBACCO.
<P>
"WELL, I NOTICED IT WITH MY OWN DAUGHTER.  HIGH SCHOOL PRESSURE IS JUST INCREDIBLE, PARTICULARLY FOR YOUNG GIRLS. IT'S REAL HARD.  SHE DID IT FOR A LARK BECAUSE OF PEER PRESSURE, AND THEN ALL OF A SUDDEN, YOU'RE HOOKED." 
<P>
A REPORT BY THE CENTERS FOR DISEASE CONTROL AND PREVENTION SAYS 43 PERCENT OF HIGH SCHOOL STUDENTS ARE EITHER LIGHTING UP OR CHEWING TOBACCO. 
<P>
SMOKING BY AFRICAN-AMERICAN STUDENTS HAS ALMOST DOUBLED SINCE 19-95. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Big Sur Marathon >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Sur Marathon </H3><BR>
DESPITE DAMAGE TO THE RACE COURSE. THE BIG SUR MARATHON IS READY TO WELCOME RUNNERS ON APRIL 26TH.
<P>
        BUT DELAYS TO RE-BUILDING HIGH-WAY ONE MAY PUSH THE RACE.OFF-COURSE.
<P>
        THIS TIME IT'S MONTAINS OF DIRT RESPONSIBLE FOR THE SETBACK.
<P>
        CALTRANS WORKERS SAY THEY'RE HAVING TROUBLE FINDING A PLACE TO DUMP THE DIRT LEFT OVER  FROM RESHAPING THE HIGHWAY.
<P>
THEY CAN'T PUT IT INTO THE SEA WITHOUT PROPER PERMITS FROM CALTRANS. 
<P>
        RACE ORGANIZERS ARE STILL HOPING THE ROAD WILL BE OPEN ON TIME.
<P>
BUT IF NOT.THEY MAY CHANGE THE COURSE. 
<P>
ONE OF THE PLANS. IF HAVE TO.
<P>
        MARATHON ORGANIZERS SAY THEY'RE CONCERNED ABOUT THE SAFETY OF THE RACERS AND ALL THE VOLUNTEERS. 
<P>
        THEY SAY THEY'RE HOPING TO USE THE ORIGINAL COURSE EVEN IF IT'S DOWN TO ONE LANE IN PLACES. 
<P>
        RACE OFFICIALS HOPE TO MAKE THE DECISION BY THE 15TH OF THIS MONTH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Carmel water>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Carmel water</H3><BR>
SOME TENSE MOMENTS FOR TWO DIVERS NEAR CARMEL THIS AFTERNOON.
<P>
        RESCUE TEAMS WERE CALLED OUT TO MONASTERY BEACH AFTER ONE OF THE TWO MEN BEGAN YELLING FOR HIS DIVE PARTNER TO SURFACE. 
<P>
        THE DIVERS APPARENTLY GOT CAUGHT IN A CURRENT THAT KICKED UP SOME SAND. TEMPORARILY BLINDING AND DISORIENTING THE MEN. 
<P>
        CREWS SENT OUT A ZODIAC TO PULL THE TWO MEN IN. 
<P>
        BOTH ARE EXPECTED TO BE OKAY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131SC DUI arrest suit>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC DUI arrest suit</H3><BR>
BOTH THE SANTA CRUZ COUNTY SHERIFF'S DEPARTMENT. AND THE WATSONVILLE POLICE DEPARTMENT. ARE FACING CHARGES OF POLICE BRUTALITY TONIGHT.
<P>
        GLEN ALLEN RAMIREZ.A SAN JOSE MAN. HAS FILED A
<P>
LAWSUIT CLAIMING HE WAS BEATEN BY SHERIFF'S DEPUTY FRANK COMBOS. WHILE COMBOS' GIRLFRIEND. A WATSONVILLE POLICE OFFICER. WATCHED. THEN HELPED COVER IT UP.
<P>
        THE SHERIFF'S DEPARTMENT SAYS RAMIREZ' INJURIES WERE THE RESULT OF THE AUTO ACCIDENT AND
<P>
A FALL DURING A FOOT CHASE.
<P>
        THE CITY OF WATSONVILLE AND THE COUNTY REJECTED RAMIREZ' EARLIER CLAIM FOR 200-THOUSAND DOLLARS FROM EACH AGENCY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Paula Jones folo-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Paula Jones folo-IN</H3><BR>
PRESIDENT CLINTON RETURNS FROM HIS TOUR OF AFRICA. BREATHING A SIGH OF RELIEF TONIGHT.
<P>
BUT. AS WOLF BLITZER REPORTS. THE PAULA JONES CASE IS FAR FROM OVER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(Virginia) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(Virginia) </H3><BR>
THERE'S STILL MUCH MORE TO COME ON KCBA FOX NEWS FIRST AT TEN.
<P>
A HUGE TWISTER TAKES THE LIVES OF A MOTHER AND HER CHILD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(Mike Fay) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(Mike Fay) </H3><BR>
AND.HE WAS ONCE WHIPPED IN SINGAPORE FOR VANDALISM.NOW HE'S IN TROUBLE WITH THE U.S. LAW.
<P>
WE'LL EXPLAIN WHEN WE COME BACK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Virginia Tornado-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Virginia Tornado-IN</H3><BR>
A TORNADO THAT TOUCHED DOWN JUST OUTSIDE OF RICHMOND, VIRGINIA HAS CLAIMED THE LIFE OF A WOMAN AND HER INFANT SON. 
<P>
THE TWISTER SPUN OUT OF A SEVERE STORM THAT SWEPT OVER THE STATE LAST NIGHT.DAMAGING HOMES, KNOCKING DOWN TREES AND LEAVING THOUSANDS OF PEOPLE WITHOUT POWER. 
<P>
REPORTER MARK HUBBARD TAKES A LOOK AT THE AFTERMATH.AND TALKS TO THOSE WHO SURVIVED THE HAVOC. 
<P>
THAT WAS MARK HUBBARD REPORTING. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
TWO MEN WHO REPORTEDLY WENT ON A SHOOTING SPREE IN ILLINOIS. KILLING FOUR PEOPLE.APPARENTLY TURNED ON EACH OTHER.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(shooting spree)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(shooting spree)</H3><BR>
19-YEAR-OLD CHALK WESSELL WAS FOUND SHOT TO DEATH IN SOUTHERN ILLINOIS THIS AFTERNOON. HIS ACCOMPLICE. 21-YEAR-OLD STEVEN HALE. WAS ARRESTED IN A FIELD NEARBY.
<P>
POLICE SAY THE PAIR KILLED THREE PEOPLE YESTERDAY. THEN DROVE TO ANOTHER TOWN. AND SHOT TWO OTHERS.
<P>
WESSELL APPARENTLY KNEW ONE OF THE VICTIMS.
<P>
THE OTHERS WERE APPARENTLY RANDOM KILLINGS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(Michael Fay/drugs)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Michael Fay/drugs)</H3><BR>
THE AMERICAN TEENAGER WHO WAS CANED FOR VANDALIZING CARS IN SINGAPORE FOUR YEARS AGO. IS ONCE AGAIN IN TROUBLE WITH THE LAW. 
<P>
MICHAEL FAY WAS BUSTED FOR DRUG POSSESSION IN WINTER PARK, FLORIDA.
<P>
HIS NEIGHBORS CALLED POLICE TO COMPLAIN ABOUT LOUD MUSIC COMING FROM HIS HOME.  
<P>
THE COPS SAY THEY FOUND MARIJUANA AND OTHER DRUG PARAPHERNALIA IN HIS POSSESSION. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(cult moves)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(cult moves)</H3><BR>
THE GARLAND TEXAS CULT WHICH CLAIMS GOD WILL APPEAR TO THEM. HAS LEFT FOR A NEW HOME.  
<P>
THE LEADER OF THE "TRUE WAY" GROUP AND SOME OF HIS FOLLOWERS BOARDED A PLANE TO BUFFALO, NEW YORK LAST NIGHT.  
<P>
THEY SAY GOD TOLD THEM TO MOVE THERE.  
<P>
ONCE THERE.MEMBERS BELIEVE THEY WILL BOARD A FLYING SAUCER THAT WILL TAKE THEM TO GARY, INDIANA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142(base closings)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(base closings)</H3><BR>
DEFENSE SECRETARY WILLIAM CO-HEN IS LOOKING TO CLOSE TWO MORE MILITARY BASES. 
<P>
CO-HEN SAYS THE U-S IS SPENDING BILLIONS OF DOLLARS EACH YEAR ON BASES IT DOESN'T NEED. 
<P>
HE SENT A NEW PENTAGON REPORT TO CONGRESS TODAY TO SUPPORT THAT CLAIM. 
<P>
CONGRESS REJECTED HIS LAST REQUEST. 
<P>
COHEN SAYS WITHOUT ADDITIONAL CLOSINGS. THE MILITARY WON'T BE ABLE TO AFFORD NEW WEAPONS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137(NASA telescope)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(NASA telescope)</H3><BR>
A SATELLITE THAT WILL STUDY SOLAR EVENTS.IS LAUNCHED FROM VANDENBERG AIR FORCE BASE.
<P>
THE SOLAR EVENTS MAY ENDANGER ASTRONAUTS AND SPACECRAFT.
<P>
THE 469-POUND SATELLITE. BETTER KNOWN AS TRACE. WILL OBSERVE THE SUN FOR A YEAR. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/job fair>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/job fair</H3><BR>
A GROUP OF LOCAL KIDS GOT A LITTLE TASTE OF THE REAL WORKING WORLD TODAY.
<P>
HUNDREDS STEPPED INTO THE SHOES OF FOLKS WHO ALREADY HAVE A JOB.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
STUDENTS AT THE JOB FAIR AT MONTEREY PENNINSULA COLLEGE.GOT FIRST HAND EXPERIENCE AT BECOMING A CHEF.THANKS TO THE CALIFORNIA CULINARY ACADEMY.
<P>
SOME EVEN WENT BEHIND A FLIGHT SIMULATOR TO BE PILOTS FOR THE DAY. 
<P>
OTHER CAREERS INCLUDED ENGINEER AND EVEN.A T-V NEWS REPORTER.
<P>
MORE THAN 6-HUNDRED LOCAL HIGH SCHOOL STUDENTS WERE BUSSED TO THE FAIR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
ITS A GOOD START TO THE SEASON. AND FOR THOSE NATIONAL BASEBALL PUBLICATIONS WHO CONTINUE TO SLIGHT THE GIANTS, THIS IS A SOLID, FUNDAMENTALLY SOUND TEAM, WITH A LOT OF "HOOTSBA."
<P>
JUST ASK THE ASTROS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
PLAYING A DAY GAME AFTER A NIGHT GAME IS NEVER EASY, THE A'S WERE BLANKED BY PEDRO MARTINEZ AND THE RED SOX IN THEIR OPENER LAST NIGHT.
<P>
THIS AFTERNOON, THEY'RE GREETED BY A WHOPPING 7-THOUSAND FANS AT THE OAKLAND COLISEUM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
TO HOOPS, AND TONITE THE WARRIORS AT LEAST GET TO PLAY A TEAM THAT'S HEADED FOR THE PLAYOFFS, THE HOUSTON ROCKETS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Seniors Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Seniors Golf</H3><BR>
TO GOLF, AND WITH THE MASTERS STILL A WEEK AWAY, THE SENIOR TOUR HOLDS ITS FIRST MAJOR, ITS THE TRADITION.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Monterey Wine fest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Monterey Wine fest</H3><BR>
YESTERDAY.  WE TOLD YOU CALIFORNIA WINEMAKERS ARE ENJOYING A RECORD YEAR.
<P>
WELL. TODAY THE FRUIT OF THE VINE IS BEING  CELEBRATED IN MONTEREY.
<P>
THE TWENTY-SECOND ANNUAL MONTEREY WINE FESTIVAL KICKED OFF EARLIER TODAY.
<P>
MORE THAN A HUNDRED FIFTY WINERIES ARE TAKING PART IN THE FOUR DAY EVENT. AS WELL AS DOZENS OF CENTRAL COAST RESTAURANTS.
<P>
FOR MORE INFORMATION ABOUT THE FESTIVAL. YOU CAN CALL 656-WINE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Monterey Jazz fest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Monterey Jazz fest</H3><BR>
AND THE OTHER POPULAR FESTIVAL ON THE CENTRAL COAST WILL HOST SOME BIG NAMES IN THE JAZZ INDUSTRY THIS SUMMER.
<P>
THOSE NAMES WERE RELEASED TODAY IN OAKLAND.
<P>
THEY INCLUDE SUCH FOLKS AS THE PAT METHENY TRIO, THE DAVE BRUBECK QUARTET, MCCOY TURNER, AL JARREAU, TOWER OF POWER AND SISTA MONICA.
<P>
THE 41ST ANNUAL MONTEREY JAZZ FESTIVAL WILL BE HELD SEPTEMBER 18TH THROUGH THE 20TH OUT AT THE MONTEREY COUNTY FAIRGROUNDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
