<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Wednesday, 4/1/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Wednesday, 4/1/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x040113.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (P. Jones)>TS1 (P. Jones)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(Atlanta tornado)>(Atlanta tornado)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO LIVE>TOSS TO LIVE</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(TX chemical spill)>(TX chemical spill)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(Philly bus hijack)>(Philly bus hijack)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Jones local reax-IN>Jones local reax-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137(Hwy bill passes)>(Hwy bill passes)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Jones local reax-GU>Jones local reax-GU</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Spotlight - Hollywood>Spotlight - Hollywood</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Jones local reax-TA>Jones local reax-TA</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144(Howard Stern show)>(Howard Stern show)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Jolon/Meth lab bust>Jolon/Meth lab bust</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145(New Fox show)>(New Fox show)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Cal-am dam costs>Cal-am dam costs</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/ATM fees>Fox Biz/ATM fees</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Cannery row car>Cannery row car</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4049ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Steinbeck truck>Steinbeck truck</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Seaside Soup kitch>Seaside Soup kitch</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Good News/Ca wine>Good News/Ca wine</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(tornado) >Bump 1(tornado) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50NPS/satellite>NPS/satellite</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(Stern show) >bump 2(Stern show) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141SPCA mural dedica>SPCA mural dedica</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=134TS1 (P. Jones)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (P. Jones)</H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
THE PAULA JONES CASE COMES TO A SCREECHING HALT TODAY. FOX'S TRACE GALLGHER WILL HAVE THE LATEST IN A LIVE REPORT FROM LITTLE ROCK.
<P>
FOLKS ON THE CENTRAL COAST COULD SEE THEIR WATER BILLS DOUBLE IN THE NEXT TEN YEARS. 
<P>
AND MOVE OVER SATURDAY NIGHT. THE SELF-PROCLAIMED "KING OF ALL MEDIA". IS LOOKING TO MAKE A NAME FOR HIMSELF ON LATE-NIGHT T-V.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO LIVE>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO LIVE</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
IT'S BEING CALLED A HUGE VICTORY FOR PRESIDENT CLINTON.AND A MASSIVE SETBACK FOR BOTH HIS CRITICS AND KENNETH STARR. 
<P>
THIS AFTERNOON. A FEDERAL JUDGE THREW OUT PAULA JONES'S SEXUAL HARASSMENT LAWSUIT AGAINST HIM. SAYING THE CASE DESCRIBES "OFFENSIVE CONDUCT". BUT DOESN'T MEET THE LEGAL STANDARD FOR SEXUAL HARASSMENT.
<P>
**THE DECISION THAT IS NOW DRAWING STUNNED REACTIONS FROM LEGAL OBSERVERS ALL ACROSS THE NATION.** 
<P>
**THE TRIAL HAD BEEN SCHEDULED TO BEGIN MAY 20TH**
<P>
FOX'S TRACE GALLAGHER JOINS US NOW LIVE FROM LITTLE ROCK WITH THE LATEST. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
WHAT DOES TODAY'S DECISION MEAN FOR SEXUAL HARASSMENT LAWSUITS IN AMERICA?
<P>
COULD THE LAWS CHANGE?
<P>
OUR REPORTER CHERI GYURO TACKLED THAT QUESTION.SHE JOINS US LIVE FROM THE NEWS DESK WITH LOCAL REATION.
<P>
CHERI, WHAT DID YOU FIND OUT?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Jones local reax-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jones local reax-IN</H3><BR>
ALAN, MOST PEOPLE WE SPOKE TO TODAY AGREE WITH THE JUDGE.THERE WASN'T ENOUGH EVIDENCE TO SUPPORT JONES' CLAIM THAT SHE WAS SEXUALLY HARASSED BY THE PRESIDENT.IN THE WORK PLACE.
<P>
BUT SOME LEGAL EXPERTS SAY TODAY'S DECISION MAY SEND THE WRONG MESSAGE TO THOSE WHO ARE HAVING SEXUAL HARASSMENT PROBLEMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Jones local reax-GU>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jones local reax-GU</H3><BR>
"IT WOULD BE UNFORTUNATE IF PEOPLE TOOK TO HEART THAT THIS IS THE STATUS OF SEXUAL HARASSMENT LAWS AND THA6T THEY CAN'T FILE IF THEY ARE VICTIMS OF SEXUAL HARASSMENT.THAT WOULD BE A SHAME."
<P>
ATTORNEY MICHELLE WELSH IS WITH THE ACLU.
<P>
WELSH SAYS TODAY'S DECISION ISN'T GOING TO CHANGE SEXUAL HARASSMENT LAWS.
<P>
SHE SAYS THEY'RE DESIGNED TO PROTECT PEOPLE WHO ARE HAVING TROUBLE IN THE WORKPLACE."
<P>
"I HOPE THIS DOESN'T SEND THE WRONG MESSAGE.THAT THEY DON'T HAVE A REMEDY.THEY DO."
<P>
WE ASKED LOCAL RESIDENTS ABOUT TODAY'S DECISION.SOME THINK IT'S SOLID.
<P>
"I BELIEVE CLINTON DID COME ON TO HER.AND I KNOW A LOT OF PEOPLE FEEL THAT WAY, BUT, HOW WAS SHE INJURED BY THAT?" "THERE'S SO MUCH HYSTERIA THAT I THINK IT'S GOOD FOR THE COUNTRY.GOOD FOR THE PRESIDENT.MAYBE NOT FOR PAULA JONES.BUT PEOPLE ARE JUST TIRED OF THE WHOLE AFFAIR." "IT'S GETTING OLD.I THINK IT WAS A GOOD MOVE."
<P>
.OTHERS SAY THEY FEEL FOR PAULA JONES.
<P>
CHRISTINA HUNT SAYS SHE WAS SEXUALLY HARASSED AT WORK BACK IN THE EARLY 80'S.REPORTED IT TO HER SUPERVISOR.WHO BRUSHED HER OFF.
<P>
"I NEVER DID PURSUE IT.NOW THAT I'M 39.I WOULD HAVE DONE THINGS DIFFERENTLY."
<P>
BUT THE PAULA JONES CASE WAS COMPLETELY DIFFERENT.
<P>
THE JUGE RULED THAT JONES WAS NOT SEXUALLY HARASSED IN THE WORK PLACE.THERE WAS NO EVIDENCE TO PROVE IT.EVEN IF CLINTON'S ALLEGED SEXUAL PROPOSITION DID HAPPEN.
<P>
EVIDENCE MICHELLE WELSH SAYS WAS LACKING IN THIS CASE.
<P>
"SHE JUST DIDN'T HAVE THE PROOF THAT A VIOLATION OF THE LAW OCCURED."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Jones local reax-TA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jones local reax-TA</H3><BR>
WELSH ALSO SAYS IF THIS CASE HAPPENED HERE IN CALIFORNIA.THE OUTCOME PROBABLY WOULD HAVE BEEN THE SAME.
<P>
SHE SAYS IT WOULD BE HARD FOR ANY CALIFORNIA LAWYER TO PROVE.
<P>
REPORTING LIVE FROM THE NEWS DESK I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Jolon/Meth lab bust>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jolon/Meth lab bust</H3><BR>
FIVE PEOPLE HAVE BEEN ARRESTED IN SOUTH MONTEREY COUNTY AFTER DRUG AGENTS BUST WHAT THEY SAY WAS A  METHAMPHETAMINE OPERATION.
<P>
DEPUTIES BEGAN A SEARCH OF THE SITE OFF OF ARGYLE ROAD, IN THE JOLON AREA  YESTERDAY MORNING.
<P>
A FULL-SCALE LAB OPERATION, TWO AUTOMATIC HANDGUNS, ASSORTED CHEMICALS AND OTHER PARAPHERNALIA WERE  FOUND AT THE SITE.  
<P>
HEALTH OFFICIALS WILL BE ON SCENE TOMORROW.CHECKING OUT THE POSSIBILITY OF WATER CONTAMINATION TO WELLS AND RESIDENTS IN THE AREA.
<P>
MEANWHILE.THE FIVE SUSPECTS WILL APPEAR IN COURT TOMORROW.CHARGED WITH CONSPIRACY TO MANUFACTURE AN ILLEGAL SUBSTANCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Cal-am dam costs>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cal-am dam costs</H3><BR>
THE CAL-AM WATER COMPANY RELEASED ITS UPDATED COST FIGURES FOR THE PROPOSED CARMEL RIVER DAM AND RESERVOIR.
<P>
THE COST HAS GONE UP. WHICH MEANS CUSTOMERS WATER BILLS WILL LIKELY GO UP.
<P>
IN FACT THEY COULD DOUBLE IN THE NEXT SEVERAL YEARS. 
<P>
THE DAM PROJECT IS SCHEDULED TO BE COMPLETED BY THE 20-05.
<P>
WHAT WE'RE BUILDING NOW IS A RESERVOIR. SOLVE THE PROBLEM WITH STATE WATER RESOURCES CONTROL BOARD. RESERVOIR WILL  CARRY WITH IT ENOUGH CAPACITY FOR 100% DROUGHT RESERVE NEEDED FOR THIS COMMUNITY.
<P>
BEGINNING IN THE YEAR 2006 AN AVERAGE RESIDENTIAL USER SHOULD EXPECT TO PAY ABOUT 63-DOLLARS.
<P>
THAT'S ABOUT A 36-DOLLAR JUMP FROM THIS YEAR'S BILLS.
<P>
A CAL-AM SPOKESMAN SAYS COST DEPRECIATION SHOULD EVENTUALLY BRING THE BILLS BACK DOWN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Cannery row car>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cannery row car</H3><BR>
A HALF -BURIED RAILROAD TANK CAR WILL STAY RIGHT WHERE IT IS FOR NOW.
<P>
THE MONTEREY COUNTY HEALTH DIRECTOR SAYS THE CAR CAN'T BE REMOVED WITHOUT A FULL ANALYSIS OF ITS POTENTIAL AS A HISTORIC RESOURCE.
<P>
THE OLD RAILROAD CAR IS ONE OF SEVERAL STUCK IN THE GROUND NEAR THE FORMER SAN XAVIER CANNERY WAREHOUSE.
<P>
THE STATE REGIONAL WATER QUALITY CONTROL BOARD FOUND THE TANKS HAD CONTAMINATED UNDERGROUND WATER.AND ORDERED THEM REMOVED.
<P>
BUT THE OFFICE OF HISTORIC PRESERVATION CLAIMED JURISDICTION OVER THEM.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Steinbeck truck>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Steinbeck truck</H3><BR>
A PIECE OF HISTORY HAS TRAVELLED BACK TO THE CENTRAL COAST.
<P>
THE TRUCK AUTHOR JOHN STEINBECK DROVE ACROSS THE UNITED STATES IN 1960 HAS BEEN DONATED TO THE STEINBECK ARCHIVES.
<P>
STEINBECK RECOUNTED THAT JOURNEY IN HIS BEST SELLER "TRAVELS WITH CHARLEY."
<P>
STEINBECK NAMED THE TRUCK "ROCINANTE" AFTER DON QUIXOTE'S HORSE.BECAUSE HIS FRIENDS CALLED HIS TRIP "QUIXOTIC"
<P>
THE TRUCK HAS BEEN RESTORED BY A LOCAL BODY SHOP.AND WILL BE DISPLAYED AT THE STEINBECK CENTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Seaside Soup kitch>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Seaside Soup kitch</H3><BR>
A LOCAL SOUP KITCHEN. THAT'S FED THE NEEDY FOR MORE THAN TEN YEARS. IS  LOOKING FOR A NEW HOME TONIGHT. 
<P>
PENINSULA OUTREACH HAS RUN A HOT LUNCH PROGRAM IN SEASIDE SINCE 19-85. BUT THIS WEEK HAD TO CLOSE ITS DOORS AT THE CHRISTIAN MEMORIAL CHURCH.
<P>
THE CHURCH SAYS IT NEEDS THE KITCHEN SPACE FOR ITS OWN ACTIVITIES.
<P>
REGULARS AT THE KITCHEN ARE BEING REFERRED TO THE SALVATION ARMY IN SEASIDE. WHERE THEY CAN GET SACK LUNCHES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Good News/Ca wine>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good News/Ca wine</H3><BR>
GOOD NEWS FOR THE CALIFORNIA WINE INDUSTRY. HUGE SALES HAVE MADE FOR ANOTHER RECORD BREAKING YEAR.
<P>
19-97 SALES WERE UP A WHOPPING 11-PERCENT TO NEARLY SIX BILLION DOLLARS.
<P>
AROUND THE WORLD PEOPLE ENJOYED MORE THAN 400-MILLION GALLONS OF CALIFORNIA WINE.
<P>
AND JUST FOR THE RECORD. THREE OUT OF EVERY FOUR BOTTLES SOLD IN THE UNITED STATES COME FROM RIGHT HERE IN THE GOLDEN STATE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(tornado) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(tornado) </H3><BR>
COMING UP ON FOX NEWS FIRST AT TEN.
<P>
TORNADOS CONTINUE TO RAVAGE THE SOUTH. THIS LAST TWISTER TOUCHING DOWN IN GEORGIA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(Stern show) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(Stern show) </H3><BR>
AND HE'S RUDE. RAUNCHY. AND ONE OF THE MOST POPULAR RADIO TALK SHOW HOSTS IN THE COUNTRY. 
<P>
NOW HE'S HOPING TO TAKE HIS BAD-BOY BRAND OF HUMOR TO LATE-NIGHT T-V.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
THREE PEOPLE ARE HURT. AND A HOUSE IS COMPLETELY DEMOLISHED. AFTER A TORNADO TOUCHES DOWN IN GEORGIA. 
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(Atlanta tornado)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Atlanta tornado)</H3><BR>
RESIDENTS OF RANGER GEORGIA ARE SURVEYING THE DAMAGE FROM A TORNADO THAT TOUCHED DOWN SHORTLY BEFORE MIDIGHT. 
<P>
IT DESTROYED ONE MOBILE HOME AND INJURED THREE PEOPLE INSIDE. 
<P>
NONE OF THE INJURIES WERE LIFE-THREATNING. 
<P>
THERE WAS ALSO DAMAGE TO SOME NEWLY BUILT CHICKEN HOUSES. AND MAJOR TREE DAMAGE IN THE AREA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(TX chemical spill)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(TX chemical spill)</H3><BR>
A RUPTURED PIPE AT A TEXAS PLANT SENT FLAMMABLE CHEMICALS SPEWING INTO THE AIR TODAY.  
<P>
A PLANT SPOKESMAN SAYS BENZENE, ETHYL BENZENE, POLYETHYL BENZENE AND SOME HYDROCHLORIC ACID WERE RELEASED AT THE TEXAS CITY PLANT THIS MORNING. 
<P>
THE CHEMICALS. USED TO MAKE PLASTICS. CAN BE HARMFUL IF  SWALLOWED. 
<P>
POLICE ORDERED ALL 40-THOUSAND PEOPLE IN TEXAS CITY TO STAY INDOORS UNTIL THE SPILL WAS UNDER CONTROL. 
<P>
NO ONE WAS SERIOUSLY HURT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(Philly bus hijack)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Philly bus hijack)</H3><BR>
IN PHILDELPHIA.
<P>
A MAN HIJACKED AND CRASHED A CITY BUS THIS MORNING AFTER REFUSING TO PAY HIS FARE.  
<P>
THE HIJACKER FORCED THE DRIVER AND ABOUT TEN PASSENGERS OFF THE BUS. THEN DROVE THE BUS AT ABOUT FIFTY MILES PER HOUR. BEFORE CRASHING INTO A PILLAR A FEW BLOCKS LATER. 
<P>
THE PILLAR SLICED THROUGH THE FRONT QUARTER 
<P>
OF THE BUS. CRUSHING THE RIGHT SIDE AND LEAVING THE LEFT SIDE. WHERE THE HIJACKER HAD BEEN SEATED. MANGLED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137(Hwy bill passes)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Hwy bill passes)</H3><BR>
IN WASHINGTON D.C.
<P>
THE HOUSE HAS PASSED A HUGE SPENDING PLAN TO REBUILD THE COUNTRY'S HIGHWAYS AND BRIDGES.
<P>
THE BILL WOULD SPEND 217-BILLION DOLLARS OVER SIX YEARS.
<P>
THAT'S 26-BILLION MORE THAN LAST YEAR.
<P>
THE BILL IS EXPECTED THE CREATE HUNDREDS OF THOUSANDS OF HIGH-PAYING CONSTRUCTION JOBS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Spotlight - Hollywood>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Spotlight - Hollywood</H3><BR>
HE'S ALREADY THE MOST FAMOUS RADIO SHOCK JOCK AROUND. NOW HE SAYS HE'S READY TO TACKLE LATE-NIGHT T-V.
<P>
AND ANOTHER WAYANS BROTHER IS LOOKING TO MAKE A SPLASH IN PRIME-TIME.
<P>
THOSE STORIES IN TONIGHT'S FOX SPOTLIGHT ON HOLLYWOOD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144(Howard Stern show)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Howard Stern show)</H3><BR>
--CELEBRITY WRAP STING--
<P>
SHOCK-JOCK HOWARD STERN IS READY TO GIVE "SATURDAY NIGHT LIVE" A RUN FOR ITS MONEY. 
<P>
STERN ANNOUNCED HIS NEW LATE NIGHT TELEVISION SHOW ON THE C-B-S NETWORK TODAY. AT A NEWS CONFERENCE IN NEW YORK CITY. 
<P>
THE RADIO TALK SHOW HOST IS BEST KNOWN FOR PUSHING TO THE LIMIT WHAT IS ALLOWED TO BE SAID ON THE RADIO.AND HE SAYS HE INTENDS TO TEST THE FEDERAL COMMUNICATIONS 
<P>
COMMISSION WATERS ON NETWORK TELEVISION AS WELL.
<P>
WHEN ASKED IF SMALLTOWN U-S-A WAS READY FOR HIS BRAND OF HUMOR. STERN. AS USUAL. TURNED THE TABLES ON FOX REPORTER PENNY CRONE.
<P>
THE SHOW WILL AIR ON SATURDAY NIGHTS.DIRECTLY COMPETING WITH "SATURDAY NIGHT LIVE". STARTING AUGUST FIRST.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145(New Fox show)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(New Fox show)</H3><BR>
A NEW FOX SITCOM IS ONCE AGAIN TEAMING UP COMEDIANS DAMON WAYANS AND DAVID ALAN GRIER.
<P>
THE DUO ALSO APPEARED TOGETHER ON FOX'S "IN LIVING COLOR".
<P>
THIS NEW SHOW. TOUTED AS A MODERN-DAY "ODD COUPLE". FEATURES WAYANS AS  UNDERCOVER POLICE OFFICER. AND AND GRIER AS A SECURITY GUARD WHO COULDN'T MAKE THE CUT AS A COP.  
<P>
THE STARS SAYS WORKING TOGETHER IS JUST LIKE OLD TIMES.
<P>
THE SHOW. CALLED "DAMON". PREMIERES ON MONDAY AT 8 P-M. RIGHT HERE ON FOX 35.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/ATM fees>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/ATM fees</H3><BR>
NEXT TIME YOU GO TO THE BANK, YOU COULD GET TAKEN TO THE CLEANERS.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
ACCORDING TO A NEW STUDY BY CAL-PIRG. THE CALIFORNIA PUBLIC INTEREST RESEARCH GROUP. A-T-M FEES ARE GIVING BANKS MORE BANG FOR YOUR BUCK.
<P>
IN FACT. 54-PERCENT OF ALL BANKS IN CALIFORNIA ARE NOW ADDING A SUR-CHARGE EVERYTIME YOU USE ANOTHER BANK'S A-T-M. AS MUCH AS A-DOLLAR-FIFTY FOR EVERY TRANSACTION.
<P>
        CAL-PIRG RESEARCHERS BELIEVE THE IDEA IS TO DRIVE SMALL BANK CUSTOMERS TO THE LARGER INSTITUTIONS.
<P>
"THOSE WHO WOULD LIKE TO GO TO A SMALL BANK, GET CHARGED $1.50 EVERY TIME THEY FIND ONE OF THE ATM'S, AND IT FORCES A LARGE NUMBER OF PEOPLE TO GO TO WELLS FARGO, BANK OF AMERICA, SOME OF THE LARGER BANKS, SO ITS A STRATEGY TO GAIN MARKET SHARE. AND IN THE END, THE CONSUMER WILL LOSE, BECAUSE BANKS WILL CONTINUE TO FIND NEW FEES, INCREASE FEES."
<P>
        CAL-PIRG SAYS CONSUMERS SHOULD URGE THEIR STATE LEGISLATORS TO VOTE AGAINST A-T-M FEE SURCHARGES.       
<P>
BANKS  DEFEND THE FEES AS A METHOD OF RECOVERING COST.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4049ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
IF EDDIE DEBARTOLO REGAINS FULL OWNERSHIP OF THE 49ERS, AND IF THAT MEANS CARMEN POLICY IS OUT AS TEAM PRESIDENT, IT NOW LOOKS AS THOUGH DEBARTOLO WILL CALL ON THE 2-MEN MOST REPSONSIBLE FOR TURNING THE NINERS INTO ONE OF THE GREAT TEAMS IN PRO FOOTBALL HISTORY.
<P>
THERE ARE REPORTS THAT BILL WALSH AND JOE MONTANA ARE COMING BACK TO THE TEAM.
<P>
WALSH WOULD MOST LIKELY REPLACE POLICY AS TEAM PRESIDENT, AND MONTANA WOULD BECOME A MINORITY OWNER IN THE TEAM, WITH UNSPECIFIED FRONT OFFICE DUTIES.
<P>
WALSH WOULD BE A DIFFERENT KIND OF EXECUTIVE THAN POLICY, WITH DWIGHT CLARK PROBABLY TAKING MORE CONTROL AS GENERAL MANAGER.
<P>
FIRST, DEBARTALO WOULD HAVE TRADE HIS HOLDINGS IN THE FAMILY BUSINESS TO HIS SISTER, DENISE DEBARTOLO YORK, IN EXCHANGE FOR FULL OWNERSHIP IN THE 49ERS. THE LEAGUE WOULD STILL HAVE TO APPROVE THAT DEAL.
<P>
DURING THIS OWNERSHIP STRUGGLE, POLICY AND DEBARTOLO HAD A SERIOS FALLING OUT, POLICY HAS ACKNOWLEDGED THAT HIS DAYS WITH THE NINERS ARE PROBABLY NUMBERED.
<P>
SAN FRANCISCO MAYOR WILLIE BROWN ACKNOWLEGED TODAY THAT THE STADIUM AND MALL DEAL IS NOW IN QUESTION.
<P>
AND IN ANOTHER STATEMENT TODAY, DEBAROLO DENIES THAT ANY FINAL DECISIONS HAVE BEEN MADE CONCERNING THE 49ERS FRANCHISE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
ITS SORT OF A GOOD NEWS/BAD NEWS KIND OF A NIGHT FOR THE GIANTS.
<P>
AFTER TRAILING 4-NOTHING IN THE FIRST INNING, THE TEAM GETS OFF THE MATT TO TAKE THE LEAD, THAT'S THE GOOD NEWS.
<P>
THE BAD NEWS, IS AFTER STRETCHING THEIR BULLPEN TO THE MAX IN THE OPENER, ITS UNABLE TO HOLD THE LEAD TONITE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
COMING OFF A SEASON THAT SAW THEM LOSE A MAJOR LEAGUE WORST 97-GAMES, SHOULD MEAN THINGS CAN ONLY GET BETTER FOR THE OAKLAND A'S.
<P>
THEY'RE EVERYDAY LINEUP ISN'T BAD, BUT THE PITCHING IS STILL SUSPECT.
<P>
TONITE THE A'S OPEN THE NEW CAMPAIGN, AT HOME, VS. THE RED SOX, AND N.L. CY YOUNG AWARD WINNER PEDRO MARTINEZ.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
TO THE ICE, AND TONITE THE SHARKS TAKE THEIR PUSH FOR A PLAYOFF SPOT TO PITTSBURGH, AS THEY SKATE AGAINST THE PENGUINS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50NPS/satellite>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NPS/satellite</H3><BR>
WHEN THE SPACE SHUTTLE DISCOVERY BLASTS OFF IN OCTOBER.IT WILL BE CARRYING CARGO WITH LOCAL TIES.
<P>
NEARLY FIVE DOZEN STUDENTS AT THE NAVAL POSTGRADUATE SCHOOL HAVE BEEN WORKING ON A 19-INCH WIDE SATELLITE.AS SORT OF A "SPACE-BASED" LAB.
<P>
THE SATELLITE WILL RIDE IN WHAT'S CALLED A "HITCH-HIKER" CANNISTER AND WILL BE EJECTED INTO ORBIT ON THE THIRD DAY OF THE FLIGHT.
<P>
IT WILL ORBIT FOR AT LEAST FOUR YEARS.WITH STUDENTS AT NPS COMMUNICATING WITH IT. JUST LIKE WE WOULD WHEN UPLOAD OR DOWNLOAD INFORMATION FROM THE INTERNET.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141SPCA mural dedica>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SPCA mural dedica</H3><BR>
IT STARTED OUT AS A WAY TO PROTECT NEWBORN HARBOR SEALS FROM CURIOUS TOURISTS.NOW THE COLORFUL MURALS NEAR CYPRESS POINT IN PEBBLE BEACH. ARE GIVING LOCAL SCHOOL KIDS A WAY TO SHOW OFF THEIR ARTISTIC TALENTS.
<P>
KIDS FROM 15 SCHOOLS AROUND MONTEREY COUNTY TOOK PART.
<P>
THE PROGRAM HAS BEEN EDUCATING STUDENTS AND PROTECTING HARBOR SEALS FOR FIVE YEARS. 
<P>
IN THAT TIME. MORE THAN 5-THOUSAND STUDENTS ACROSS MONTEREY COUNTY HAVE TAKEN PART. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
