<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (f/Sat), Saturday, 4/18/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (f/Sat), Saturday, 4/18/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#8State Protest>State Protest</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118Sudan Famine>Sudan Famine</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114CA Gov Race-I>CA Gov Race-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#25Bump #3 (50th)>Bump #3 (50th)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112CA Gov Race-G>CA Gov Race-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#38NFL Draft>NFL Draft</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#11AARP>AARP</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#4049ers>49ers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Wats. Tank Sim.>Wats. Tank Sim.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#116Laguna Seca>Laguna Seca</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#9Earth Day SC>Earth Day SC</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#10Earth Day Salinas>Earth Day Salinas</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#12SF Quake Anniv.>SF Quake Anniv.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#17Clinton/Chile-I>Clinton/Chile-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#99Great 18>Great 18</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#18Clinton/Chile-G>Clinton/Chile-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#5050th Anniversaries>50th Anniversaries</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119China Release>China Release</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#105Oldest Woman>Oldest Woman</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#19Shuttle>Shuttle</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#111SQ1 (Protest)>SQ1 (Protest)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#20Ireland>Ireland</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=8State Protest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>State Protest</H3><BR>
GOOD EVENING EVERYONE.I'M CHERI GYURO.THANKS FOR JOINING US.
<P>
GOVERNOR WILSON AND STATE LEGISLATORS MAY SOON HAVE DEEPER POCKETS.
<P>
THE STATE PAY COMMISSION GRANTED THEM A *26-PERCENT* PAY RAISE.     
<P>
MEMBERS OF THE CALIFORNIA STATE EMPLOYEES' ASSOCIATION ARE STEAMING MAD OVER THE SALARY INCREASE.
<P>
THEY RALLIED OUTSIDE THE D-M-V OFFICE IN SALINAS THIS MORNING.
<P>
ONE PROTESTOR SAYS STATE EMPLOYEES HAVE BEEN WORKING WITHOUT A CONTRACT, OR A PAY RAISE FOR THREE YEARS.
<P>
"IT'S JUST VERY UNFAIR.IN LIGHT OF WE ARE THE FOLKS THAT DO THE WORK AND WE'VE GOTTEN NOTHING, WHICH HAS EQUALED A DECREASE AND THEY'VE GOTTEN A VERY HEARTY RAISE."
<P>
"I DONT' SEE ANY JUSTIFICATION FOR IT SEEMS TO ME THAT LEGISLATORS RECEIVE ADEQUATE COMPENSATION AT CURRENT LEVELS.PERHAPS RECONSIDERING IS A GOOD IDEA AND THE THING TO DO."
<P>
ASSEMBLY MEMBER FRED KEELEY SAYS THE MONEY CAN BE USED FOR OTHER NEEDS, SUCH AS EDUCATION AND ENVIRONMENTAL PROTECTION.
<P>
VOTERS APPROVED PROPOSITION 112 IN 19-90, WHICH DOES NOT ALLOW LEGISLATORS TO CONTROL THEIR OWN SALARY.
<P>
IF THE PAY COMMISSION DOES NOT REVERSE ITS DECISION, THE INCREASE WILL GO INTO EFFECT IN DECEMBER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114CA Gov Race-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>CA Gov Race-I</H3><BR>
THE GOVERNOR'S RACE ALSO HEATING UP THE POLITICAL LANDSCAPE IN THE STATE. 
<P>
EVEN BEFORE THE PRIMARIES BEGIN.CANDIDATES WILL SPEND ALMOST 100-MILLION DOLLARS.
<P>
BY COMPARISON. THE PRESIDENTIAL RACE COST ONLY 52-MILLION DOLLARS MORE. 
<P>
JANE WELLS TELLS US ABOUT THE HIGH COST OF CAMPAIGNING. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=112CA Gov Race-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>CA Gov Race-G</H3><BR>
SOT: C-H-E-C-C-H-I.CHEE-CHEE 
<P>
VO#1 
<P>
ACTUALLY IT'S PRONOUNCED CHECCHI, AND IF YOU'VE NEVER HEARD OF 
<P>
DEMOCRAT AL CHECCHI.WELL, HE JUST HASN'T SPENT ENOUGH MONEY YET. 
<P>
SO FAR THIS SELF-MADE MILLIONAIRE HAS SPENT 20-MILLION DOLLARS TO RUN 
<P>
FOR GOVERNOR OF CALIFORNIA. 
<P>
NATS: WHEN THE DISNEY.FAR REACHING CHANGES. 
<P>
VO#2 
<P>
HIS MAIN OPPONENT IN THE JUNE PRIMARY, DEMOCRATIC CONGRESSWOMAN JANE 
<P>
HARMAN. 
<P>
SOT: HI TECH.CREATE THEM. 
<P>
VO#3 
<P>
SHE'S RICH TOO.SPENDING ABOUT FOUR MILLION OF HER FORTUNE SO FAR IN 
<P>
THE RACE. 
<P>
SOT: I'M VERY PROUD TO PAY A LITTLE TO GET A LOT. 
<P>
SOT: THERE IS A REAL PROBLEM WHEN YOU ARE COMING FROM OUTSIDE OF THIS 
<P>
SYTEM. THERE IS NO OTHER WAY TO GET YOUR SELF KNOWN. I CERTAINLY 
<P>
DON'T ENJOY SPENDING THE MONEY. 
<P>
VO#4 
<P>
IN CALIFORNIA, IT REALLY REALLY HELPS TO BE RICH IF YOU'RE RUNNING 
<P>
FOR OFFICE. 
<P>
SOT: IT'S SUCH A BIG STATE WITH SO MANY MEDIA MARKETS THAT YOU HAVE 
<P>
TO SPEND A FORTUNE JUST TO BARELY GET NOTICED. 
<P>
VO#5 
<P>
CHECCHI'S MONEY IS ONE REASON SENATOR DIANNE FEINSTEIN DECIDED NOT TO 
<P>
RUN FOR GOVERNOR. BEING GOVERNOR OF CALIFORNIA IS A BIG DEAL. 
<P>
YOU'RE REALLY PRESIDENT OF A NOT-SO-SMALL COUNTRY.  
<P>
SOT: WE HAVE THE SEVENTH LARGEST ECONOMY IN THE WORLD, WE'RE SO BIG 
<P>
PEOPLE HAVE TO PAY ATTENTION, NOW LET'S BE SO GOOD. 
<P>
VO#6 
<P>
HARMAN AND CHECCHI JUMPED OUT EARLY WITH AD CAMPAIGNS. THE TWO 
<P>
OTHER CANDIDATES FOR GOVERNOR MAY BE PAYING FOR IT. 
<P>
NATS: THANK YOU VERY MUCH 
<P>
VO#7 
<P>
DEMOCRAT GRAY DAVIS--WHO'S NOT A MILLIONAIRE--IS STRUGGLING FOR MONEY 
<P>
TO GET ON TV.REPUBLICAN DAN LUNGREN HAS ALSO BEEN HOLDING BACK, 
<P>
SAVING HIS MONEY FOR LATER.  
<P>
NATS: I'M FORMALLY.STATE OF CALIFORNIA. 
<P>
VO#8 
<P>
LUNGREN IS THE STATE'S ATTORNEY GENERAL. HE HAS NO REPUBLICAN 
<P>
OPPOSITION IN THE PRIMARY FOR GOVERNOR.BUT FOR THE FIRST 
<P>
TIME.CALIFORNIA VOTERS WILL HAVE AN OPEN PRIMARY.THEY CAN VOTE 
<P>
FOR ANYONE THEY CHOOSE. 
<P>
SO YOU WOULD THINK LUNGREN WOULD WIN, SINCE REPUBLICANS WOULD VOTE 
<P>
FOR HIM, AND THEN DEMOCRATS WOULD SPLIT THEIR VOTES AMONG THE OTHER 
<P>
THREE CANDIDATES. WELL GET THIS.HARMAN AND CHECCHI ARE PICKING UP A 
<P>
LOT OF REPUBLICAN SUPPORT.   
<P>
SOT: NOW CAN YOU IMAGINE DAN LUNGREN WITH NO SERIOUS REPUBLICAN 
<P>
PRIMARY OPPOSITION COMING IN EITHER SECOND OR THIRD IN AN OPEN 
<P>
PRIMARY, THAT'S UNHEARD OF. 
<P>
SOT: IF THAT HAPPENS HE CAN KISS OFF NOVEMBER, HE'S COOKED. 
<P>
V0#9 
<P>
WITH THE OPEN PRIMARY IN MIND, DEMOCRAT AL CHECCHI DOESN'T EVEN 
<P>
MENTION HIS PARTY AFFILIATION IN ADS. 
<P>
SOT: REAL WORLD EXPERIENCE.CHECCHI FOR GOVERNOR. 
<P>
VO#10 
<P>
FINALLY, STOP ME IF YOU'VE HEARD THIS ONE BEFORE--THIS REALLY WILL BE 
<P>
THE MOST EXPENSIVE RACE IN STATE HISTORY. 
<P>
SOT: BECAUSE BY THE TIME AL CHECCHI IS FINISHED SPENDING HE'LL HAVE 
<P>
SPENT 50 MILLION DOLLARS ON THE PRIMARY. JANE HARMAN ABOUT 15 MILLION 
<P>
, GRAY DAVIS APPROXIMATELY 6 TO 7 MILLION LUNGREN A COUPLE OF MILLION 
<P>
SO YOU'RE LOOKING AT A HUGE AMOUNT OF MONEY IN A PRIMARY, AND  WE 
<P>
HAVEN'T EVEN GOTTEN TO THE GENERAL ELECTION YET! 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=11AARP>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>AARP</H3><BR>
OVER IN SEASIDE.CANDIDATES REVEAL THEIR OPINIONS ON SOME HOT TOPICS.
<P>
THE AMERICAN ASSOCIATION OF RETIRED PERSONS, OR A-A-R-P. HELD THE 19-98 CANDIDATES FORUM AT THE OLDEMEYER CENTER.
<P>
THE PUBLIC LISTENED TO THOSE RUNNING FOR CONGRESSIONAL DISTRICT 17 AND STATE ASSEMBLY DISTRICTS 27 AND 28.
<P>
MOST CANDIDATES AGREE.THE NEED TO IMPROVE EDUCATION IN CALIFORNIA IS ONE OF THE MOST PRESSING ISSUES THE STATE NEEDS TO ADRESS.
<P>
OTHER DISCUSSIONS FOCUSED ON HEALTH CARE AND SOCIAL SECURITY.
<P>
THE OPEN PRIMARY IS SCHEDULED FOR JUNE SECOND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Wats. Tank Sim.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Wats. Tank Sim.</H3><BR>
NEW TECHNOLOGY IS HELPING THE CALIFORNIA NATIONAL GUARD'S FIRST BATTALION.
<P>
THE MILITARY TROOPS ARE IN WATSONVILLE THIS WEEKEND.
<P>
THEY'RE USING SIMULATORS TO LEARN HOW TO OPERATE TANKS.
<P>
IT'S LESS EXPENSIVE THAN USING REAL EQUIPMENT AND AMMUNITION.
<P>
THE BATALLION IS ALSO GETTING READY FOR A VERY IMPORTANT DEDICATION.
<P>
"IT'S REALLY BEEN AN EXCITING EXPERIENCE OPENING THIS. ON THE 2ND OF MAY WE'LL BE DEDICATING THE CENTER TO ONE OF THE BATALLION'S SURVIVORS FROM WORLD WAR II. A MEMBER OF THE UNIT NOW LIVING IN THE SALINAS AREA."
<P>
THE TRAINING CENTER IS KEY TO HELPING TROOPS LEARN GROUND BATTLE TECHNIQUES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=9Earth Day SC>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Earth Day SC</H3><BR>
IT'S EASY TO FORGET ABOUT THE GROUND WE WALK ON.
<P>
SOME FOLKS SPEND HOURS TRYING TO CLEAN UP THE MESS OTHERS LEAVE BEHIND.
<P>
TODAY.HUNDREDS OF CENTRAL COAST RESIDENTS CELEBRATE WHAT MOTHER EARTH DOES FOR HUMANS.
<P>
TODAY IS EARTH DAY.
<P>
OVER IN SANTA CRUZ.FOLKS CELEBRATE WITH MUSIC, FOOD AND EDUCATIONAL PROGRAMS.
<P>
THE THEME FOR EARTH DAY.HONORING OUR WORLD AND PROTECTING IT'S RESOURCES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=10Earth Day Salinas>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Earth Day Salinas</H3><BR>
SALINAS RESIDENTS FOCUS ON TREES FOR THIS YEAR'S EARTHDAY CELEBRATION.
<P>
A CEREMONY WAS HELD FOR VOLUNTEERS WHO RE-PLANT SHRUBS IN OUR AREA.
<P>
OVER AT NATIVIDAD CREEK.COLORFUL, BLOOMING PLANTS FILL THE PARK.
<P>
THOUSANDS OF TEACHERS AND STUDENTS SPENT THREE YEARS BUILDING THE BEAUTIFUL SCENE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=12SF Quake Anniv.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SF Quake Anniv.</H3><BR>
TODAY IS A DATE TO REMEMBER FOR GREAT QUAKERS.
<P>
THOSE ARE THE SURVIVORS OF THE GREAT SAN FRANCISCO EARTHQUAKE ON APRIL 18TH, 19-06. 
<P>
THE EARTHQUAKE STRUCK AT 5:12 A-M.  AND LASTED FOR LESS THAN A MINUTE.
<P>
BUT IT DEVASTATED THE CITY.
<P>
FIRES BURNED FOR THREE DAYS.
<P>
SCIENTISTS SAY. THE MAGNITUDE WAS 7.8.
<P>
THE OFFICIAL DEATH TOLL WAS 478. BUT HISTORIANS SAY IT MAY HAVE BEEN AS HIGH AS 3-THOUSAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=17Clinton/Chile-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Chile-I</H3><BR>
THE 34-NATION "SUMMIT OF THE AMERICAS" IS UNDERWAY IN CHILE.
<P>
THE FOCUS?FREE-TRADE.     
<P>
BUT PRESIDENT CLINTON HAS OTHER REFORMS HE'D LIKE TO ADDRESS. 
<P>
FOX'S JIM ANGLE TELLS US WHAT'S ON THE PRESIDENT'S MIND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=18Clinton/Chile-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Chile-G</H3><BR>
THE LEADERS OF 34 NATIONS OPENED THE SUMMIT OF THE AMERICAS IN 
<P>
SANTIAGO CHILE THIS MORNING. EVERY ONE OF THEM ELECTED, A MAJOR 
<P>
CHANGE IN A REGION ONCE DOMINATED BY MILITARY DICTATORSHIPS.  
<P>
**** VIDEO OF ARRIVALS***** 
<P>
WHEN PRESIDENT CLINTON ARRIVED, A JOURNALIST HELD UP A SAXOPHONE, 
<P>
GETTING A LAUGH FROM THE PRESIDENT AND A LITTLE AIR SAX. 
<P>
***VIDEO, CLINTON WALKING IN THE ROOM - FED APPROX 9 32 00**** 
<P>
INSIDE, MR CLINTON RECITED A LONG LIST OF ACCOMPLISHMENTS, BOTH 
<P>
ECONOMIC AND POLITICAL, SINCE THE LAST SUMMIT FOUR YEARS AGO. BUT 
<P>
SAID NOW, THERE IS A NEW GOAL:  
<P>
CLINTON AT APPROX 9:43:00:WE MUST DO MORE TO MAKE SURE THAT THE PATH 
<P>
OF REFORM AND DEMOCRACY AND INTEGRATION ACTUALLY LIFTS THE LIVES OF 
<P>
ORDINARY PEOPLE IN ALL OUR NATIONS." 13 
<P>
/  
<P>
*****VIDEO OF SUMMIT-- PAN OF LEADERS? ****** 
<P>
GOOD SHOTS FED AT 09:36:14 AND 09:36:26 
<P>
TOO FEW, HE SAID, FEEL CHANGE WORKING FOR THEM. SO THERE MUST BE 
<P>
A SECOND GENERATION OF REFORMS, ESPECIALLY IN EDUCATION. 
<P>
AND MR CLINTON URGED THESE LEADERS TO WORK ON LIFTING LABOR 
<P>
STANDARDS FOR ALL WORKERS.  
<P>
**ANGLE BACK ON CAM*** 
<P>
THAT ALSO HAPPENS TO BE ONE THE KEY CONCERNS OF CONGRESSIONAL  
<P>
DEMOCRATS.  WHO HAVE BLOCKED MR CLINTON'S EFFORTS TO EXPAND FREE 
<P>
TRADE. 
<P>
THAT, OF COURSE, IS A LITTLE EMBARRASSING FOR PRESIDENT CLINTON 
<P>
-- AFTER HAVING LED THE CHARGE FOR FREE TRADE.  
<P>
HE TOLD THE DELEGATES THIS MORNING THAT U.S. MAY NOT HAVE FAST 
<P>
TRACK  NEGOTIATING AUTHORITY YET-- BUT, HE PROMISED, WE WILL.  
<P>
WITH THE PRESIDENT IN SANTIAGO, JIM ANGLE, FOX NEWS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119China Release>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>China Release</H3><BR>
WE HAVE SOME BREAKING NATIONAL NEWS TO TELL YOU ABOUT TONIGHT.
<P>
A CHINESE NEWS AGENCY REPORTS THAT THE CHINESE GOVERMENT RELEASED ONE OF THE LEADERS FROM THE 19-89 TIANANMEN SQUARE PRO-DEMOCRACY PROTESTS.
<P>
29-YEAR OLD WANG DAN WAS REPORTEDLY RELEASED FROM PRISON AND GONE TO ANOTHER COUNTRY TO SEEK MEDICAL TREATMENT.
<P>
WANG DAN IS THE SECOND PRISONER TO BE RELEASED FOR ALLEGED MEDICAL REASONS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=19Shuttle>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Shuttle</H3><BR>
THE SPACE SHUTTLE COLUMBIA RECEIVES A WAKE-UP CALL FROM THE "QUEEN OF SOUL" TODAY.
<P>
NATURAL SOUND
<P>
ARETHA FRANKLIN'S VOICE ACTED AS THE ALARM CLOCK FOR CREW MEMBERS.
<P>
THEN, THE COLUMBIA CREW GOT TO WORK.STUDYING HOW SPACE AFFECTS THE NERVOUS SYSTEM. 
<P>
FLIGHT SPECIALIST SAY TESTING COULD ANSWER QUESTIONS ABOUT INSOMNIA. BLOOD PRESSURE.BALANCE PROBLEMS AND MOTION SICKNESS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=20Ireland>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ireland</H3><BR>
ANOTHER VICTORY FOR THE PEACE AGREEMENT IN NORTHERN IRELAND TODAY. 
<P>
THE LEADING PROTESTANT PARTY  VOTED TO APPROVE THE  PACT.
<P>
IRISH REPUBLICAN ARMY LEADER GERRY ADAMS SAYS HE WELCOMES THE VOTE.
<P>
THE AGREEMENT WILL REQUIRE IRELAND TO DROP ITS CONSTITUTIONAL CLAIM TO THE NORTHERN PART OF THE ISLAND. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118Sudan Famine>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sudan Famine</H3><BR>
THOUSANDS OF PEOPLE IN THE SOUTHERN PART OF SOODAN ARE AT RISK OF STARVING TO DEATH.
<P>
THE COUNTRY IS CURRENTLY FACING ITS WORST FAMINE EVER.
<P>
ONE ORGANIZATION MANAGED TO RATION OUT ENOUGH FOOD TO LAST FOR TWO WEEKS.
<P>
BUT SOME OF THE IMPOVERISHED PEOPLE WALKED FOR 
<P>
TWO DAYS HOPING TO GET FOOD THAT WOULD LAST A COUPLE OF MONTHS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=25Bump #3 (50th)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump #3 (50th)</H3><BR>
COMING UP ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
WE'LL LET YOU KNOW WHAT THE WEATHER HAS IN STORE FOR THE CENTRAL COAST.
<P>
AND MORE THAN SIX-HUNDRED COUPLES REVEAL THE SECRET TO A HAPPY MARRIAGE.
<P>
STAY WITH US.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=38NFL Draft>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NFL Draft</H3><BR>
THE LOVE AFFAIR BETWEEN AL DAVIS AND HEISMAN TROPHY WINNERS CONTINUES TODAY. AS THE RAIDERS KEEP THEIR NUMBER ONE PICK IN THE N-F-L DRAFT TO TAKE THE 1ST DEFENSIVE PLAYER TO WIN THE COVETED AWARD.
<P>
THE RAIDER FANS IN NEW YORK HAPPY WITH THE PICK WHICH GIVES THE RAIDERS THREE HEISMAN TROPHY WINNERS ON THE ROSTER. WITH WOODSON JOINING TIM BROWN AND DESMOND HOWARD.
<P>
WOODSON HAD 8-INTERCEPTIONS LAST SEASON WITH THE ROSE BOWL CHAMPIONS AND 12 RECEPTIONS AS A RECEIVER, INCLUDING 2 FOR TOUCHDOWNS.
<P>
OAKLAND HAD THE NFL'S WORST DEFENSE LAST YEAR SO THE RAIDERS WERE IN DESPERATE NEED OF A DEFENSIVE STANDOUT. A  LIKE PLAYER IF YOU WILL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=4049ers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>49ers</H3><BR>
THE 49ERS WERE HOPING TO GRAB FLORIDA OFFENSIVE TACKLE MO COLLINS. BUT THE RAIDERS TRADED UP TO GRAB HIM BEFORE SAN FRANCISCO'S 28TH PICK.
<P>
SO INSTEAD. THE NINERS GOT DEFENSIVE.
<P>
SAN FRANCISCO TAKING OKLAHOMA STATE CORNERBACK  WITH THEIR 1ST ROUND PICK.
<P>
AT OKLAHOMA STATE. MCQUARTERS PLAYED CORNER. SAFTEY. WIDE RECIEVER AND RETURNED PUNTS.
<P>
HE ENDED LAST SEASON AS THE NATION'S 2ND RANKED PUNT RETURNER. FINISHING WITH A SCHOOL RECORD 521 YARDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=116Laguna Seca>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Laguna Seca</H3><BR>
THE SUPERBIKES WILL BE BUZZING IN MONTEREY TOMORROW FOR THE HONDA CHALLANGE OF LAGUNA SECA.
<P>
QUALIFYING WRAPPED UP TODAY WITH THE CHAMPIONSHIP RACE SLATED FOR 2 O'CLOCK ON SUNDAY.
<P>
AUSTRALIAN. TAKES THE POLE FOR SUNDAY'S RACE. SETTING A TRACK RECORD TODAY. BREAKING  RECORD BY ONE TENTH OF A SECOND. CHANDLER. THE SALINAS NATIVE.IS 2ND FOLLOWED BY ANOTHER AUSSIE.. PACIFIC GROVE'S  WILL BE IN ROW FOUR AFTER QUALIFYING WITH THE 7TH FASTEST TIME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
TO THE DIAMOND NOW. WHERE THE GIANTS OFFENSIVE STRUGGLES RESUME.AS THEY CONTINUE THEIR 6-GAME ROAD TRIP IN MILWUAKEE.
<P>
STILL LOOKING FOR HIS 1ST WIN OF THE SEASON. ROUGH START THOUGH.  WITH A TWO-RUN BOMB TO LEFT. BREWERS TAKE A 2-NOTHING LEAD IN THE 1ST INNING.
<P>
--------
<P>
IT'S 2-1 IN THE 5TH. WHEN THE WHEEL'S FALL OFF THE BUS.  THROWS ONE INTO THE DIRT.  ALERTLY BACKS UP THE PLAY BUT HIS THROW GOES INTO LEFT. PUT A TENT OVER THIS CIRCUS. CIRILLO IS HELD AT 3RD WHEN THE GIANTS ARE FINALLY ABLE TO SQUEEZE THE BASEBALL.
<P>
----------
<P>
HE WOULDN'T STAY THERE LONG THOUGH.  DRIVES HIM IN TO MAKE IT A 3-1 LEAD. AND THAT'S THE FINAL. HERSHEISER GETS THE LOSS. HIS 1ST DECISION IN FOUR STARTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
MEANTIME. A'S HOSTING THE ROYALS AT THE OAKLAND COLISEUM.
<P>
LOOKING FOR HIS 2ND WIN OF THE SEASON.
<P>
---------
<P>
IT'S SCORELESS IN THE 5TH. WHEN FORMER ATHLETIC  TOUCHES ROGERS FOR A SOLO SHOT. HIS 1ST OF THE SEASON. 1-ZIP K-C.
<P>
---------
<P>
BUT IN THE BOTTOM OF THE INNING.  WOULD PROVIDE SOME UNEXPECTED POP. WITH A 2-OUT.3-RUN HOMER. JUST THE 2ND HOMER OF HIS CAREER IN 665 AT BATS.
<P>
--------
<P>
COMES IN TO CLOSE THINGS OUT. AS THE A'S GO ON TO WIN FOR JUST THE 4TH TIME THIS SEASON. 3-2 IS THE FINAL. SAME TWO TEAMS TOMORROW. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
IN GOLF. DAVIS LOVE THE THIRD HAS A 2-SHOT LEAD OVER PHIL MICKELSON AFTER 3-ROUNDS OF THE MCI CLASSIC.
<P>
LOVE IS A 3-TIME CHAMPION AT THIS EVENT HE FIRED A 66 TODAY. PAYNE STEWART. A TWO TIME CHAMP HIMSELF. SHOT THE TOURNAMENT LOW WITH A 64. HE'S JUST 3 SHOTS BACK OF LOVE.
<P>
MEANTIME. ACTION FROM THE 3RD ROUND OF THE SENIORS CHAMPIONSHIP.  WITH THE TEXAS WEDGE AT NUMBER SEVEN. AND HE CANS IT FOR BIRDIE.  A 3-UNDER 69 FOR IRWIN.
<P>
----------
<P>
MEANTIME.  HAS ANOTHER TOUGH ROUND ON THE COURSE HE DESIGNED. GUESS YOU SHOULDN'T HAVE PUT THOSE TRAPS THERE JACK. THE GOLDEN BEAR IS 12 SHOTS OFF THE PACE AFTER A 75.
<P>
----------
<P>
IRWIN'S THE LEADER AT 11 UNDER PAR. FIVE SHOTS AHEAD OF LARRY NELSON. IT WAS ALMOST 6 SHOTS AFTER THIS ONE AT 15. IRWIN IS THE ONLY PLAYER TO HAVE 3-ROUNDS IN THE 60'S. HE'S ALSO THE TWO TIME DEFENDING CHAMP. TOMORROW HE'LL GO FOR A THIRD. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=99Great 18>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Great 18</H3><BR>
AND FINALLY TONIGHT. IT'S THE 2ND EDITION OF THE KCBA GREAT 18. BRUCE LEWIS AND I TAKING IN A LITTLE COUNTRY CLUB LIFE THIS WEEK AS WE HEAD OUT TO CORRAL DE TIERRA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=5050th Anniversaries>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>50th Anniversaries</H3><BR>
A GOLDEN MOMENT FOR SOME VERY HAPPY COUPLES IN NEW YORK CITY TODAY.
<P>
MORE THAN 600 HUSBANDS AND WIVES WALKED DOWN THE AISLE FIFTY YEARS AFTER THEY DECLARED "I DO" FOREVER. 
<P>
AND IT LOOKS LIKE THESE COUPLES STILL MEAN IT!  
<P>
THEIR VOWS WERE RENEWED AT SAINT PATRICK'S CATHEDRAL TODAY.
<P>
SOME COUPLES SAY THEY HAVE THE SECRET TO A LONG AND HAPPY MARRIAGE.
<P>
"YOU GOTTA KEEP CALM.AND MEET EVERYBODY HALF 
<P>
WAY." 
<P>
HUSBAND AND WIFE SAY "FIGHT LIKE HELL.SAME PROBLEM." 
<P>
WIFE SAYS "GRIN AND BEAR IT." 
<P>
ONE COUPLE EVEN SURPASSED THE GOLDEN YEAR AND WAS NOW CELEBRATING SIXTY-FIVE YEARS TOGETHER. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=105Oldest Woman>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Oldest Woman</H3><BR>
A 117-YEAR-OLD WOMAN FROM ALLENTOWN, PENNSYLVANIA IS NAMED THE OLDEST WOMAN ALIVE.
<P>
SARAH KNAUSS WASN'T VERY EXCITED WHEN SHE FOUND OUT ABOUT HER KNEW TITLE.
<P>
SHE GAVE THE SIMPLE RESPONSE OF "SO WHAT."
<P>
KRAUSS WAS BORN SEPTEMBER 24TH, 18-80.
<P>
HER HUSBAND PASSED AWAY MORE THAN 30-YEARS AGO AT THE AGE OF 85.
<P>
IN HER SPARE TIME KNAUSS ENJOYS WATCHING GOLF ON TELEVISION AND EATING CHOCOLATE TURTLES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=111SQ1 (Protest)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SQ1 (Protest)</H3><BR>
COMING UP ON K-C-B-A FOX NEWS.
<P>
STATE WORKERS TAKE TO THE STREETS AND GET VOCAL ABOUT PAY INCREASES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
