<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Tuesday, 4/21/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Tuesday, 4/21/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (highway 17)>TS1 (highway 17)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(kidnap dad) >Bump 1(kidnap dad) </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(stripper) >bump 2(stripper) </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Highway 17 shoot-IN>Highway 17 shoot-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Highway 17 shoot-T>Highway 17 shoot-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(kidnap dad arrest)>(kidnap dad arrest)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Watsonville stabbing>Watsonville stabbing</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#147(shark attack)>(shark attack)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Campground stab>Campground stab</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(stripper protest)>(stripper protest)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#145train v. truck>train v. truck</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Crimestopper>Crimestopper</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126highway 101 patrols>highway 101 patrols</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox BIZ/enterprize>Fox BIZ/enterprize</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125SB/Postigo arrest>SB/Postigo arrest</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Strawberry contract>Strawberry contract</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Marathon preps>Marathon preps</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44NBA>NBA</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Big Sur shuttle>Big Sur shuttle</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130"A" not enough-IN>"A" not enough-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Chihuahua mania-IN>Chihuahua mania-IN</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141INS/new green card>INS/new green card</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=134TS1 (highway 17)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (highway 17)</H3><BR>
COMING UP ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
A FATAL SHOOTING ON A MAJOR CENTRAL COAST HIGHWAY BACKS UP TRAFFIC FOR HOURS.
<P>
IT'S BEING CALLED THE EL NINO COURSE.
<P>
BIG SUR MARATHON OFFICIALS ARE PUTTING THE FINISHING TOUCHES ON THIS YEAR'S RACE. WHICH IS JUST DAYS AWAY.
<P>
AND THOUSANDS OF STRAIGHT-A STUDENTS WERE DENIED ADMITANCE TO CAL-BERKLEY THIS YEAR. NOW AFFIRMATIVE ACTION SUPPORTERS SAY TOO MANY OF THEM WERE MINORITIES.
<P>
SANDHYA PATEL HAS THE WARM WEATHER FORCAST. KEN ROTHHOUSE HAS MAJOR LEAGUE BASEBALL SCORES AND HILITES. NEXT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
        GOOD EVENING AND THANK YOU FOR JOINING US.I'M ALAN MARSDEN.
<P>
        THOUSANDS OF CARS DEADLOCKED ON HIGHWAY 17 FOR EIGHT HOURS TODAY AFTER AN OFFICER-INVOLVED SHOOTING ON THE ROAD.
<P>
        OUR CHERI GYURO WAS ON THE SCENE.SHE JOINS US LIVE FROM OUR SANTA CRUZ COUNTY BUREAU WITH ALL THE INFORMATION. CHERI WHAT CAN YOU TELL US?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Highway 17 shoot-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Highway 17 shoot-IN</H3><BR>
        ALAN, ONE MAN IS DEAD AFTER A HIGHWAY PATROL OFFICER SHOT HIM.
<P>
        IT STARTED IN LOS GATOS SHORTLY AFTER 10 THIS MORNING.
<P>
        POLICE WERE ON THE LOOKOUT FOR A HIT AND RUN SUSPECT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Highway 17 shoot-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Highway 17 shoot-T</H3><BR>
                THE SANTA CLARA COUNTY SHERIFF'S DEPARTMENT IS HANDLING THE INVESTIGATION.
<P>
        THEY TELL US THEY FOUND EVIDENCE IN THE VEHICLE THAT'S RELATED TO THIS INCIDENT.BUT WOULDN'T BE SPECIFIC.
<P>
        THE REGISTERED OWNER OF THE TAN CAR IS ___________________.
<P>
        CHERI, DO WE KNOW WHO THE VICTIM WAS.OR THE OFFICER WHO FIRED THE SHOT?
<P>
        NO, THAT INFORMATION HASN'T BEEN RELEASED.BUT INVESTIGATORS SAY THEY'LL HAVE MORE INFORMATION AFTER THE AUTOPSY REPORT.
<P>
        REPORTING LIVE FROM THE SANTA CRUZ COUNTY BUREAU I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Watsonville stabbing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Watsonville stabbing</H3><BR>
A MAN RIDING HIS BIKE DOWN MAIN STREET IN WATSONVILLE THIS AFTERNOON IS STABBED IN THE BACK BY TWO OTHER CYCLISTS.
<P>
POLICE SAY THE TWO SUSPECTS.  DESCRIBED AS HISPANIC MALES IN THEIR EARLY TWENTIES. RODE UP BEHIND 19-YEAR-OLD VICTOR TENA. AND STABBED HIM IN THE BACK SEVERAL TIMES.
<P>
IN: "VICTIM RIDING BIKE." OC: "STABBED IN THE BACK."
<P>
THE TWO SUSPECTS ARE STILL ON THE LOOSE TONIGHT. POLICE ARE ASKING ANYONE WITH INFORMATION ABOUT THE ATTACK TO CALL THE WATSONVILLE POLICE DEPARTMENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Campground stab>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Campground stab</H3><BR>
A MAN REMAINS HOSPITALIZED TONIGHT AFTER BEING STABBED IN THE NECK. AT A CAMP GROUND IN SANTA CRUZ LATE LAST NIGHT.
<P>
IT HAPPENED DURING WHAT POLICE ARE CALLING A DRUNKEN BRAWL AT NEW BRIGHTON STATE BEACH.
<P>
TONIGHT. THE SUSPECT. MICHAEL AINSWORTH IS IN JAIL ON ATTEMPTED MURDER CHARGES.
<P>
HIS BAIL IS SET AT A QUARTER OF A MILLION DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=145train v. truck>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>train v. truck</H3><BR>
AN AMTRAK TRAIN SLAMMED INTO A TRUCK THIS AFTERNOON.
<P>
IT HAPPENED ON METZ ROAD JUST NORTH OF KING CITY.
<P>
NO ONE ON THE AMTRAK TRAIN WAS HURT.
<P>
THE TRUCK DRIVER WAS AIRLIFTED TO A SAN JOSE HOSPITAL WHERE HE WAS TREATED AND RELEASED.
<P>
STILL NO WORD ON HOW THE ACCIDENT HAPPENED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126highway 101 patrols>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>highway 101 patrols</H3><BR>
THE C-H-P IS LOOKING TO MAKE A DANGEROUS STRETCH OF HIGHWAY 101 A LITTLE SAFER.
<P>
THE AGENCY IS STEPPING UP PATROL IN PRUNEDALE. LOOKING FOR SPEEDERS.
<P>
THE SPEED LIMIT THROUGH PRUNEDALE IS 55. BUT PETER REESE SAYS TOO MANY DRIVERS IGNORE IT.
<P>
REESE SAYS HE'S SEEN MORE THAN HIS SHARE OF FATAL ACCIDENTS ALONG THE STRETCH OF HI WAY HE CALLS BLOOD ALLEY. 
<P>
HE'S ERECTED CROSSES AND SIGNS. HOPING TO WARN DRIVERS OF THE DANGERS THAT LIE AHEAD. 
<P>
THIS 12 MILE STRETCH. IS THE WORST FROM MEXICO TO CANADA AND IT'S BAD WITH ALL THE CROSS TRAFFIC. 
<P>
THE CHP'S PRESENCE ON THE DANGEROUS ROAD HAS PETER OVERJOYED.
<P>
THE OFFICERS SAY IT'S PART OF AN INTENSIFIED EFFORT ESPECIALLY NOW THAT TOURIST'S ARE MAKING ROADS EVEN BUSIER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125SB/Postigo arrest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SB/Postigo arrest</H3><BR>
A CANDIDATE FOR THE SAN BENITO COUNTY BOARD OF SUPERVISORS IS IN TROUBLE WITH THE LAW TONIGHT.
<P>
SHERIFF HARVEY NYLAND TELLS K-C-B-A. DEPUTIES WERE CALLED TO THE HOME OF JOSEPH POSTIGO ON SUNDAY NIGHT.AFTER THE HOSPITAL CALLED THEM TO REPORT A CASE OF DOMESTIC VIOLENCE.
<P>
SHERIFF NYLAND SAYS POSTIGO HIT HIS WIFE ON THE BACK OF THE HEAD DURING AN ARGUMENT.
<P>
POSTIGO WAS ARRESTED FOR SPOUSAL ABUSE.
<P>
HE HAS POSTED BAIL AND BEEN RELEASED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Strawberry contract>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Strawberry contract</H3><BR>
IT'S A SWEET DEAL FOR STRAWBERRY WORKERS.  
<P>
A NEW CONTRACT WAS SIGNED BETWEEN THE WORKERS AND THE UNITED FARM WORKERS AT THE SWANTON BERRY FARM IN SANTA CRUZ COUNTY. 
<P>
THE NEW CONTRACT WILL BOOST WORKER'S PAY FROM 7-DOLLARS-AN-HOUR TO 11-DOLLARS-AN-HOUR.  
<P>
THEY WILL ALSO HAVE HEALTH BENEFITS ALONG WITH DENTAL AND EYE CARE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Marathon preps>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marathon preps</H3><BR>
THE 13TH ANNUAL BIG SUR MARATHON TAKES OFF THIS SUNDAY. AND THANKS TO EL NINO DAMAGE ON HIGHWAY ONE.  ORGANIZERS WERE FORCED TO ALTER THE 26 MILE COURSE.
<P>
RUNNERS WILL START AT THE TRADITIONAL FINISH LINE IN CARMEL. AND HEAD SOUTH ON HIGHWAY ONE FOR 13 MILES.
<P>
THEY'LL BE TURNED AROUND AT BIXBY BRIDGE, TO RETRACE THEIR STEPS BACK TO THE FINISH LINE.
<P>
THE RACE DIRECTOR HAS ALREADY RUN THE COURSE. AND  SAYS IT'S ALMOST AS CHALLENGING AS THE TRADITIONAL ONE.
<P>
THE FIRST TEN MILES OF NORMAL COURSE ARE FLAT AND DOWNHILL. THIS ONE IS FLAT FOR 1/2 MILE, THEN HILLS START. HAVE TO RUN THE HILLS SMART.
<P>
        CONSTRUCTION CREWS ARE EXPECTED TO HAVE THE ENTIRE RACE COURSE PAVED BY SUNDAY.
<P>
MEANTIME. ORGANIZERS ARE PUTTING THE FINISHING TOUCHES ON PARKING ARRAIGNMENTS FOR THE THOUSANDS OF PARTICIPANTS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Big Sur shuttle>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Sur shuttle</H3><BR>
MEANWHILE. THE ISOLATED COMMUNITY OF BIG SUR GETS SOME GOOD NEWS TODAY.
<P>
BIG SUR BUSINESSES HAVE BEEN LOSING AN ESTIMATED ONE- HUNDRED THOUSAND DOLLARS A WEEK. BECAUSE OF THE SLIDES ON HIGHWAY ONE.
<P>
BUT TODAY THE MONTEREY COUNTY BOARD OF SUPERVISORS APPROVED  A PROPOSED SHUTTLE BUS SERVICE INTO THE AREA.
<P>
THE BUSES WOULD HEAD TO BIG SUR EARLY IN THE MORNING. AND RETURN LATE AT NIGHT.
<P>
THE BUSES WILL ONLY CARRY  A COUPLE DOZEN PEOPLE. BUT THOSE VISITORS GETTING THROUGH COULD ENJOY THE AREA WITHOUT THE USUAL CROWDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130"A" not enough-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>"A" not enough-IN</H3><BR>
WHEN IS BEING A STRAIGHT "A" STUDENT NOT GOOD ENOUGH? 
<P>
WHEN YOU'RE TRYING TO GET INTO ONE OF CALIFORNIA'S MOST PRESTIGIOUS COLLEGES. 
<P>
MORE THAN 7-THOUSAND STRAIGHT "A" STUDENTS FAILED TO GAIN ADMISSION TO THE UNIVERSITY OF CALIFORNIA AT BERKELEY THIS YEAR.  
<P>
AMONG THOSE REJECTED. MORE THAN 8-HUNDRED MINORITY STUDENTS. ALMOST ALL OF WHOM WOULD HAVE GAINED ADMISSION BEFORE CALIFORNIA'S PROPOSITION 2-0-9 WHICH BARS ALL RACIAL PREFERENCES IN THE STATE. 
<P>
FOX'S TRACE GALLAGHER HAS THE STORY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141INS/new green card>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>INS/new green card</H3><BR>
IT'S NOT JUST COMPUTERS THAT ARE GOING "HIGH-TECH" THESE DAYS. 
<P>
TODAY. THE IMMIGRATION AND NATURALIZATION SERVICE UNVEILED IT'S NEW "HIGH TECH" GREEN CARD THAT THE I-N-S CLAIMS WILL UP THE ANTE FOR COUNTERFEITERS. 
<P>
THE NEW CARD IS PLASTIC AND LOOKS LIKE A CREDIT CARD.BUT NOW HAS SECURITY FEATURES, SUCH AS HOLOGRAMS, A DIGITAL PHOTO AND MICRODOT PORTRAITS OF ALL THE NATION'S PRESIDENTS.    
<P>
THE AGENCY SPENT 38-MILLION DOLLARS TO DESIGN AND PRODUCE THE NEW CARD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(kidnap dad) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(kidnap dad) </H3><BR>
COMING UP NEXT ON FOX NEWS FIRST AT TEN.
<P>
POLICE ARREST A MAN WHO THEY SAY KIDNAPPED HIS TWO INFANT DAUGHTERS TWENTY YEARS AGO.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(stripper) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(stripper) </H3><BR>
AND SOME STRIPPERS PUT ON A SHOW IN FRONT OF CITY HALL. 
<P>
WE'LL TELL YOU WHAT'S GOT THEIR BOA'S IN A RUFFLE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
A MAN IS BEHIND BARS TONIGHT ACCUSED OF KIDNAPPING HIS INFANT DAUGHTERS TWENTY YEARS AGO.
<P>
THAT STORY FROM BOSTON TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(kidnap dad arrest)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(kidnap dad arrest)</H3><BR>
POLICE SAY STEPHAN FAGAN TOLD THE KIDS FOR YEARS THAT THEIR MOTHER WAS DEAD. 
<P>
FAGAN IS BEING HELD ON TWO-AND-A-HALF MILLION DOLLARS BAIL. 
<P>
PROSECUTORS WANTED DOUBLE THAT AMOUNT BECAUSE FAGAN HAS CHANGED HIS IDENTITY IN THE PAST.
<P>
THE DAUGHTERS DISAPPEARED IN 19-79. AFTER THEY WERE VISITING THEIR FATHER AT HIS MASSACHUSETTS HOME FOR THE WEEKEND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=147(shark attack)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(shark attack)</H3><BR>
A 50-YEAR-OLD SURFER IS IN THE HOSPITAL TONIGHT. AFTER BEING BITTEN BY A SHARK OFF THE COAST OF OREGON.
<P>
FILM MAKER JOHN FORSE SAYS A 15-FOOT SHARK TOOK A BITE OUT OF HIS THIGH WHILE HE WAS BOARDING THIS MORNING.
<P>
SURGEONS SAY THE BITE IS ABOUT A FOOT-AND-A-HALF LONG. WITH THE BIGGEST TOOTH BITING DOWN ALMOST FOUR INCHES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(stripper protest)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(stripper protest)</H3><BR>
STRIPPERS AND OTHER MEMBERS OF NEW YORK CITY'S ADULT ENTERTAINMENT INDUSTRY PICKED A FIGHT WITH CITY HALL TODAY.  
<P>
A CROWD OF STRIPPERS. GO-GO DANCERS AND SEX SHOP OWNERS TOOK TO THE STEPS OF CITY HALL TO PROTEST THE CITY'S NEW ORDINANCE THAT REGULATES SEX-ORIENTATED ACTIVITY IN THE BIG APPLE. 
<P>
THEY WERE DEMONSTRATING AGAINST THE CITY'S RE-ZONING PLAN THAT MAKES IT DIFFICULT FOR MANY OF THE ESTABLISHMENTS TO REMAIN IN BUSINESS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Crimestopper>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Crimestopper</H3><BR>
CRIMESTOPPERS IS LOOKING FOR CLUES IN A SIX YEAR OLD MONTEREY MURDER CASE TONIGHT.
<P>
THEODORE INTELLI WAS FOUND SHOT TO DEATH NEAR JACK'S PEAK IN 1992.
<P>
INTELLI.  ALSO KNOWN AS "BIG TED".  WAS LAST SEEN AT A MOTEL ON NORTH FREMONT AVENUE WHEN HE LEFT FOR A MEETING WITH THOSE WHO AUTHORITIES PRESUME KILLED HIM.
<P>
INVESTIGATORS BELIEVE SOMEONE IN THE AREA HAS INFORMATION THAT COULD CRACK THE CASE WIDE OPEN.
<P>
TONIGHT THAT SOMEONE COULD RECEIVE A REWARD.
<P>
.JUST BY CALLING THE CRIMESTOPPERS ANONYMOUS LINE. AT 1-800-499-CRIME.
<P>
INFORMATION LEADING TO THE ARREST OF A SUSPECT IS WORTH UP TO A THOUSAND DOLLARS.
<P>
OPERATORS ARE ALWAYS ON DUTY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox BIZ/enterprize>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox BIZ/enterprize</H3><BR>
FIVE FORMER MANAGEMENT TRAINEES HAVE FILED A CALIFORNIA CLASS ACTION LAWSUIT AGAINST THE LARGEST RENTAL CAR AGENCY IN CALIFORNIA.
<P>
HERE'S TONIGHT'S FOX BUSINESS REPORT.
<P>
THE COMPLAINT STATES THAT ENTERPRISE RENT-A CAR HAS VIOLATED BOTH STATE AND FEDERAL LAW BY FAILING TO PAY REQUIRED OVERTIME WAGES TO HUNDREDS OF TRAINEES.
<P>
ACCORDING TO THE TRAINEES.THEY WERE REQUIRED TO WORK 50 TO 60 HOURS A WEEK WITHOUT ANY OVERTIME COMPENSATION.
<P>
FEDERAL AND STATE LAW REQUIRES EMPLOYERS TO PAY TIME AND A HALF AFTER 40 HOURS IN A WORKWEEK.
<P>
THE PLANTIFFS ATTORNEY SAYS THE COMPANY RECLASSIFIED THE POSITION AS A NON EXEMPT ONE IN 19-97 AND STARTED PAYING OVERTIME ONLY AFTER THAT DATE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
HAVING LOST 4-STRAIGHT COMING INTO TONITE'S GAME IN PITTSBURGH, THE GIANTS NEEDED MARK GARDNER TO BE THEIR STOPPER.
<P>
AND GARDNER COMES THROUGH, PITCHING THE GIANTS FIRST COMPLETE GAME OF THE YEAR, AND HE GETS A LITTLE LONG BALL HELP FROM BARRY BONDS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
THE A'S BEAT THE TWINS LAST NIGHT UP AT THE OAKLAND COLISEUM.
<P>
TONITE ITS THE SAME TEAMS AT THE SAME PLACE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44NBA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA</H3><BR>
TO NBA NEWS, BILL FITCH WAS FIRED YESTERDAY BY THE L.A. CLIPPERS, TODAY JIM HARRICK'S NAME COMES UP AS A POSSIBLE REPLACEMENT.
<P>
HARRICK, IN HIS FIRST YEAR AT RHODE ISLAND, WAS ONE GAME AWAY FROM THE FINAL FOUR, AND HE OF COURSE COACHED U.C.L.A. TO A NATIONAL CHAMPIONSHIP.
<P>
NOW L.A.'S PRIMETIME TEAM, THE LAKERS, ARE THE ONLY ONE OF THE FOUR CALIFORNIA TEAMS TO QUALIFY FOR THE NBA PLAYOFFS.
<P>
SOME BELIEVE THE TALENTED LAKERS, UNDERACHIEVED THIS YEAR, BUT THEY STILL FINISHED 61 AND 21, NOT BAD FOR THE YOUNGEST TEAM IN THE LEAGUE.
<P>
THE LAKERS BEGIN A BEST OF 5-GAME SERIES WITH THE BLAZERS ON FRIDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
THE SAN JOSE SHARKS SKATE INTO THE PLAYOFFS TOMORROW WITH A 1ST ROUND MATCH-UP AGAINST THE DALLAS STARS.
<P>
SAN JOSE IS IN THE PLAYOFFS FOR JUST THE 3RD TIME IN FRANCHISE HISTORY. BUT AS ZANE TABARI REPORTS. THE TEAL AND BLACK HAVE A HISTORY OF BEING GIANT KILLERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Chihuahua mania-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chihuahua mania-IN</H3><BR>
THEY'RE TINY, THEY'RE TRENDY.AND THANKS TO THOSE TACO BELL ADS, CHIHUAHUAS ARE FAST BECOMING THE HOTTEST DOGS IN AMERICA. 
<P>
BUT AS FOX'S ADAM SHAPIRO TELLS US, YOU MAY 
<P>
WANT TO THINK TWICE BEFORE YOU THROW DOWN CASH ON THESE CANINES. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
