<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (g/Sun), Sunday, 4/26/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (g/Sun), Sunday, 4/26/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#112Toss to Jinah>Toss to Jinah</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Chernobyl Ann.-T>Chernobyl Ann.-T</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Marathon-I>Marathon-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Spain Bus Crash>Spain Bus Crash</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Marathon-G>Marathon-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21China Hail>China Hail</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Marathon-T>Marathon-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Big Sur>Big Sur</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109PG&E Update>PG&E Update</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Business Impact>Business Impact</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Post Game>Post Game</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Salinas Vote Proj.>Salinas Vote Proj.</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42NBA Playoffs>NBA Playoffs</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121Killer Whale Attack>Killer Whale Attack</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#124Shuttle Today>Shuttle Today</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123Cassini Spacecraft>Cassini Spacecraft</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#104Monastery Fire>Monastery Fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Racing>Racing</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Chernobyl Ann.-I>Chernobyl Ann.-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#133Harley Jump>Harley Jump</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Chernobyl Ann.-G>Chernobyl Ann.-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Lego Champions>Lego Champions</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=112Toss to Jinah>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Toss to Jinah</H3><BR>
GOOD EVENING.I'M CHERI GYURO.THANKS FOR JOINING US.
<P>
EL NINO PUT A TWIST ON THINGS.AND FORCED A CHANGE IN THE COURSE.
<P>
BUT THE 13TH ANNUAL BIG SUR MARATHON WENT OFF WITHOUT A HITCH.
<P>
THE EVENT ATTRACTED THOUSANDS FROM ALL OVER THE WORLD. INCLUDING OUR OWN OBSERVER. JINAH KIM.  WHO JOINS US FROM THE NEWSDESK.
<P>
JINAH! 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=113Marathon-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marathon-I</H3><BR>
YES. THE MARATHON STARTED AND ENDED THIS MORNING, RIGHT ON SCHEDULE.
<P>
AS YOU KNOW, THE BIG SUR HAS ONE OF THE MOST SCENIC MARATHON COURSES IN THE WORLD.
<P>
BUT A LITTLE MORE THAN A MONTH AGO. MARATHON OFFICIALS DIDN'T EVEN KNOW IF THEY WOULD BE ABLE TO RUN *ANY* OF THAT COURSE. BECAUSE MUDSLIDES CLOSED DOWN SO MANY PORTIONS OF HIGHWAY ONE.
<P>
WELL. THE ROUTE FINALLY OPENED. BUT ONLY HALF WAY, AND SO THE COURSE HAD TO CHANGE.
<P>
BUT EVERYTHING ELSE THAT MAKES THE BIG SUR WHAT IT IS. REMAINED THE SAME.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114Marathon-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marathon-G</H3><BR>
FOR THE FIRST TIME IN ITS 13-YEAR HISTORY. THE GUN SIGNALING THE *START* OF THE BIG SUR MARATHON RANG OUT FROM WHERE THE RACE USUALLY *ENDS*!
<P>
RUNNERS. KNOWING FULL WELL THE BIG SUR MARATHON THIS YEAR WOULD NEVER ACTUALLY REACH BIG SUR.
<P>
AND THAT 13 MILES INTO THEIR RUN. THEY'D BE TOLD TO TURN BACK. AND HEAD TO THE STARTING LINE AGAIN.
<P>
BUT THESE RUNNERS DON'T MIND.
<P>
AFTER ALL. THEY KNOW BETTER THAN TO EXPECT THE ORDINARY FROM THE BIG SUR MARATHON.
<P>
AND THIS IS WHY.
<P>
"EINE KLEINE NACHT MUSIK" POURING FROM GROUPS LIKE THE ROBERT LOUIS STEVENSON HIGH SCHOOL BAND.
<P>
A HORN BLOWER GREETING RUNNERS AT THE TURNAROUND.
<P>
BAGPIPERS.
<P>
AND, OF COURSE, THE MAN WHO'S BEEN WITH THE BIG SUR SINCE THE BEGINNING:  PIANIST JONATHON LEE.
<P>
BUT IT'S MORE THAN JUST THE MUSIC.
<P>
IT'S THE PEOPLE, TOO.
<P>
TAKE CORY REDING OF MONTEREY, FOR EXAMPLE. 
<P>
HE'S A 23-YEAR OLD CANCER SURVIVOR WHO UNDERWENT BRAIN SURGERY FOR THE SECOND TIME LESS THAN A MONTH AGO.
<P>
HE FINISHED THE 5-K TODAY IN 23 MINUTES.
<P>
EXTRAORDINARY PEOPLE, EXTRAORDINARY ENTERTAINMENT. AND EXTRAORDINARY VIEWS.
<P>
THE CHANGE IN THE COURSE THIS YEAR HARDLY MADE A DENT.
<P>
AND RUNNERS AGREE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Marathon-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marathon-T</H3><BR>
THAT DOESN'T MEAN THE RUNNERS DON'T WANT THE OLD COURSE BACK.
<P>
ALTHOUGH THIS YEAR'S COURSE WAS EASIER. MOST OF THE PARTICIPANTS WE TALKED TO ARE LOOKING FOWARD TO RETURNING TO BIG SUR AGAIN NEXT YEAR.
<P>
CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109PG&E Update>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>PG&E Update</H3><BR>
THE WORK CONTINUES.GAS SERVICE STILL BEING RESTORED IN SANTA CRUZ COUNTY.
<P>
ABOUT 50-THOUSAND HOMES AND BUSINESS NOW HAVE SERVICE.
<P>
THAT'S ABOUT 82 PERCENT OF ALL  PG& E CUSTOMERS AFFECTED.
<P>
ONLY ABOUT 800 CUSTOMERS REMAIN WITH INTERRUPTED GAS SERVICE. AND PG&E HOPES TO RECONNECT AS MANY AS POSSIBLE TONIGHT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Business Impact>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Business Impact</H3><BR>
RESIDENTS AREN'T THE ONLY ONES THANKFUL TO HAVE GAS BACK ON LINE.
<P>
SANTA CRUZ BUSINESS OWNERS ARE RELIEVED TO SEE CUSTOMERS AGAIN.
<P>
THE OCEAN PACIFIC LODGE EXTENDED A TEN PERCENT DISCOUNT TO GUESTS WHILE THE GAS WAS OUT.
<P>
ONE RESTAURANT LOST A THOUSAND DOLLARS DURING THE CRISIS.BUT STAYED OPEN FOR LOYAL CUSTOMERS.
<P>
"WE HAD TO SERVE A MENU BASICALLY FROM HERE DOWN.SIMPLE FRUIT SALAD, GRANOLA, TOAST.THAT WAS ABOUT IT.WE HAD TO DO THAT FOR ABOUT 4 HOURS UNTIL WE COULDN'T KEEP UP ANYMORE."
<P>
NOAH'S BAGELS LOST ABOUT 10-THOUSAND DOLLARS.
<P>
BUT PG&E IS PROBABLY THE HARDEST HIT.REPAIRS WILL COST ABOUT ONE MILLION DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Salinas Vote Proj.>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas Vote Proj.</H3><BR>
VOTER TURNOUT DURING ELECTIONS USUALLY SEEMS TO BE LOW.
<P>
ONE LOCAL GROUP WANTS TO MOTIVATE VOTERS TO HIT THE POLLS THIS JUNE.
<P>
TODAY, VOLUNTEERS WITH THE CENTRAL COAST CITIZENSHIP PROJECT LAUNCHED A CAMPAIGN TO INCREASE VOTER REGISTRATION.
<P>
COMMUNITY MEMBERS WENT DOOR TO DOOR ASKING FOLKS TO REGISTER IN SALINAS.
<P>
THEY ALSO WANT TO EDUCATE THE PUBLIC ABOUT ISSUES ON THE JUNE BALLOT.
<P>
"OUR GOAL IS TO REGISTER AND RELAY INFORMATION. THAT'S THE BOTTOM LINE. WE WANT TO RELEASE INFORMATION SO PEOPLE CAN BE EDUCATED."
<P>
THE GROUP FOCUSES ON NEW CITIZENS WHO HAVEN'T HAD A CHANCE TO REGISTER YET.
<P>
THEY'VE ALSO DONE SIMILAR PROJECTS IN SANTA CLARA AND SAN BENITO COUNTIES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121Killer Whale Attack>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Killer Whale Attack</H3><BR>
AN AMAZING SCENE FROM THE WATERS OF THE MONTEREY BAY IS CAUGHT ON TAPE.
<P>
A CLUSTER OF ORCAS OR KILLER WHALES.ATTACK A GRAY WHALE AND HER CALF.WHO EVENTUALLY ESCAPE.
<P>
THE PREVIOUS DAY. THE ORCAS ATTACKED AND KILLED TWO BABY GRAY WHALES.
<P>
THE CALVES ARE BORN IN THE WARM WATERS OFF THE COAST OF MEXICO.
<P>
IN APRIL AND MAY.THEY TRAVEL NORTH TO THE BERING SEA 11-THOUSAND MILES AWAY.
<P>
THE CANYON OF THE MONTEREY BAY IS A DANGER AREA FOR THE GRAY WHALES.
<P>
THEY BECOME EASY PREY FOR ORCAS.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=124Shuttle Today>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Shuttle Today</H3><BR>
ASTRONAUTS ABOARD THE SPACE SHUTTLE "COLUMBIA" CAN TAKE A DEEP BREATH.
<P>
THE NEWLY REPAIRED AIR PURIFYING SYSTEM IS BACK IN WORKING CONDITION.
<P>
NOW, CREW MEMBERS ARE REFOCUSING ON THEIR RESEARCH MISSION.
<P>
IF THE SYSTEM HAD NOT BEEN FIXED, THE MISSION WOULD HAVE BEEN CUT SHORT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123Cassini Spacecraft>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cassini Spacecraft</H3><BR>
ON THE NEXT PLANET OVER.THE CASSINI SPACECRAFT GETS A BOOST FROM VENUS ON ITS TREK TO SATURN.
<P>
THE PLUTONIUM-POWERED PROBE RACED PASSED VENUS THIS MORNING, COMING WITHIN 176 MILES.
<P>
CASSINI WILL ALSO PASS EARTH IN AUGUST OF 1999 AND JUPITER IN 2-THOUSAND.
<P>
ONCE IT GETS TO SATURN.THE SPACECRAFT WILL SPEND 4 YEARS STUDYING THE PLANET'S FAMOUS RINGS AND FROZEN MOONS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=104Monastery Fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Monastery Fire</H3><BR>
50 FIREFIGHTERS BATTLE A MASSIVE BLAZE IN MARYLAND TODAY.  
<P>
THE FIRE BROKE OUT IN THE TOWER OF A VACANT  MONASTERY BUILT IN THE EIGHTEEN HUNDREDS.
<P>
AUTHORITIES SAY THE INTERIOR IS COMPLETELY GUTTED.
<P>
ARSON DETECTIVES ARE INVESTIGATING THE CAUSE OF THE INFERNO. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Chernobyl Ann.-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chernobyl Ann.-I</H3><BR>
IT'S A DAY OF REMEBRANCE.
<P>
THE ANNIVERSARY OF THE WORLD'S WORST NUCLEAR DISASTER.CHERNOBYL.
<P>
DEMONSTRATORS IN THE UKRAINE ARE USING THE GRIM ANNIVERSARY AS A CALL TO SHUT DOWN THE PLANET'S NUCLEAR POWER PLANTS. 
<P>
FOX'S VERA FRANKL HAS MORE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Chernobyl Ann.-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chernobyl Ann.-G</H3><BR>
THEY GATHERED TO MARK THE ANNIVERSARY OF THE MOST DEVASTATING  
<P>
NUCLEAR ACCIDENT IN HISTORY.  
<P>
IT'S TWELVE YEARS SINCE CHERNOBYL'S REACTOR NUMBER FOUR  
<P>
EXPLODED, AND AT A SERVICE IN MOSCOW, THE RUSSIAN ORTHODOX  
<P>
PATRIARCH LED A SERVICE OF REMEMBRANCE FOR THOSE WHO DIED.  
<P>
PRAYERS WERE SAID AT CEREMONIES ACROSS THE FORMER SOVIET UNION.  
<P>
THE SHEER SCALE OF THE DISASTER AT CHERNOBYL IS ONLY NOW  
<P>
BECOMING APPARENT.  
<P>
AT LEAST THIRTEEN THOUSAND INVOLVED IN THE CLEANUP OPERATION  
<P>
DIED, AND THE EFFECTS OF CONTAMINATION CONTINUE.  
<P>
TODAY THE REACTOR - IN A CRUMBLING CONCRETE SARCOPHAGOUS - IS  
<P>
THE FOCUS OF A CAMAIGN AIMED NOT JUST AT KEEPING ITS MEMORY  
<P>
ALIVE BUT AT THE CLOSING OF ALL NUCLEAR FACILITIES.  
<P>
SOT IVAN BLOKOV, GREENPEACE: "PEOPLE OF THE./.NUCLEAR POWER."  
<P>
FOR THE THOUSANDS WHO LOST THEIR HOMES AND LOVED ONES, AND THE  
<P>
MANY MORE STILL LIVING WITH THE EFFECTS OF THE BLAST,FORGETTING  
<P>
IS NOT A LUXURY THEY CAN AFFORD.  
<P>
THE ANNIVERSARY IS MOST SOMBER IN TOWNS WHERE CHERNOBYL WORKERS  
<P>
LIVED.  
<P>
WITH EIGHT HUNDRED THOUSAND CHILDREN IN RUSSIA, THE UKRAINE AND  
<P>
BELARUS SUFFERING FROM RADIATION RELATED ILLNESSES AS A RESULT  
<P>
OF CHERNOBYL, GRIEF REMAINS ALL TOO FAMILIAR.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Chernobyl Ann.-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Chernobyl Ann.-T</H3><BR>
THAT WAS FOX'S VERA FRANKL REPORTING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Spain Bus Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Spain Bus Crash</H3><BR>
A TOURIST DAY-TRIP ENDS IN DISASTER.
<P>
A DOUBLE DECKER BUS SLIDES OFF A ROAD IN SPAIN.KILLING 12 PEOPLE.INJURING 36 OTHERS. 
<P>
THE BUS WAS PACKED WITH ELDERLY SPANISH TOURISTS FROM PARIS.
<P>
AUTHORITIES SAY THE BUS SLID OUT OF CONTROL ON WET PAVEMENT. AND ROLLED OVER THE SIDE OF A SMALL BRIDGE.  AND THEN DOWN AN EMBANKMENT. 
<P>
PASSING MOTORISTS STOPPED TO HELP. 
<P>
THE INJURED TOURISTS WERE TAKEN TO LOCAL HOSPITALS FOR TREATMENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21China Hail>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>China Hail</H3><BR>
21 PEOPLE ARE DEAD IN CHINA.AFTER A FREAK WEATHER SYSTEM HAMMERS THE FAR EAST. 
<P>
STRONG WINDS AND TORNADOES WERE ACCOMPANIED BY FIST-SIZED HAIL.
<P>
DEEP HOLES WERE LEFT IN THE GROUND OVER A 37 MILE PATH  OF FARMLAND. 
<P>
MORE THAN 400 HOUSES COLLAPSED IN THE SAVAGE STORM.
<P>
MORE THAN 35-THOUSAND HOMES WERE BADLY DAMAGED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Big Sur>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Big Sur</H3><BR>
IT WAS A BEAUTIFUL DAY FOR A RUN. AND AN EVEN BETTER DAY FOR A MARATHON AS MORE THAN 3-THOUSAND RUNNERS TOOK PART IN THE 13TH ANNUAL BIG SUR MARATHON.
<P>
THIS YEAR THE COURSE LOOKING A LITTLE DIFFERENT THANKS TO "EL NINO" DAMAGE TO HIGHWAY ONE. BUT IT DIDN'T DAMPEN THE SPIRIT OF THOSE PARTICIPATING.
<P>
---------------
<P>
ANY WAY YOU SLICE IT. THE RACE IS STILL A GRUELING 26-POINT TWO MILES. THIS TIME AROUND THOUGH. NO HURRICAN POINT. THAT MEANS IT WAS A DOWN AND BACK. WITH THE RUNNERS TURNING AROUND AFTER THE BIXBI BRIDGE.
<P>
---------------
<P>
AT THE 18-MILE MARK. DEFENDING CHAMP SERBA NICOLIC WOULD PULL AWAY.AND HE CROSSES THE FINISH LINE IN A TIME OF 2 HOURS 21 MINUTES AND 36 SECONDS. BECOMING THE FIRST MENS RUNNER TO REPEAT SINCE BRAD HAWTHORNE IN '93.
<P>
-----------
<P>
ON THE WOMEN'S SIDE. IT'S JANINA SAXER OF SWITZERLAND CROSSING THE FINISH LINE FIRST. IN 2:46:24. NEARLY 4-MINUTES AHEAD OF DEFENDING CHAMP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
FROM RUNNING TO SKATING. WE TURN OUR ATTENTION TO THE NHL PLAYOFFS.THE SHARKS RETURNING TO THE TANK DOWN 2-NOTHING IN THEIR BEST OF SEVEN SERIES WITH DALLAS.
<P>
BUT GAME THREE WOULD BE A DIFFERENT STORY THEN THE PREVIOUS. WITH THE SHARKS FINALLY GETTING TO EDDIE THE EAGLE.
<P>
THE FANS LETTING BELFOUR HEAR IT ALL GAME LONG. AND THE SHARKS WOULD GET TO HIM IN THE 2ND PERIOD. DOWN 1-ZIP.  FOLLOWS HIS OWN SHOT AND TIES THE GAME AT ONE.
<P>
----------
<P>
THEN. 1-MINUTE SEVEN SECONDS LATER.  SCORES ON THE POWER PLAY. AND IT'S TWO ONE SAN JOSE.
<P>
---------
<P>
THE SHARKS WOULD HAVE 14 POWERPLAY OPPORTUNITIES IN THE GAME AND SCORE ON THREE OF THEM. A COMPLETE TURNAROUND FROM GAME TWO.  WITH ONE THE GOAL TO MAKE IT 3-1.
<P>
----------
<P>
THE STARS TRAIL 4-1 LATE IN THE GAME WHEN THEY LOSE THEIR COOL. BELFOUR GOING AFTER. AND THEN HE SCRAPS WITH. BELFOUR WAS EJECTED. THE SHARKS WIN. 4-1 IS THE FINAL. STARS STILL LEAD THE SERIES 2-1. BUT THE SHARKS ARE BACK IN THIS ONE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Post Game>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Post Game</H3><BR>
THE SHARKS CAN TIE THE SERIES UP WITH A WIN ON TUESDAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42NBA Playoffs>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA Playoffs</H3><BR>
TO HOOPS NOW. THE L.A. LAKERS LOOKING TO GO UP TWO GAMES TO NONE ON PORTLAND. AND IT WOULD BE EDDIE JONES LEADING THE WAY FOR L.A.
<P>
THE LAKER ALL-STAR HEARING FROM ISIAH RIDER ALL WEEK ABOUT HOW HE WOULD DOMINATE HIM. AND JONES SCORES A CAREER PLAYOFF HIGH 21.
<P>
------------
<P>
THE LAKERS GETTING HELP FROM EVERYWHERE.   ALSO WITH A CAREER HIGH 24 TO LEAD THE LAKERS. L-A BY TWO AT THE BREAK. 
<P>
--------------
<P>
THEY PULL AWAY IN THE 3RD QUARTER. SHAQ WITH TWO OF HIS 19. LAKERS WIN IT. 108-99.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
IT WAS A HITTERS PARADISE AT THE STICK ON SUNDAY AND THE GIANTS WERE WAY OVER DUE.
<P>
COMING INTO THE GAME WITH MILWAUKEE. THE GIANTS HAD ONLY HIT TEN HOME RUNS AS A TEAM. THE SAME TOTAL AS MARK MCGWIRE.
<P>
IS STARTING TO HEAT UP. IN THE 7TH. GIANTS TRAIL 6-NOTHING. WHEN BONDS CONNECTS WITH THE BAGS FULL. AND IT SAILS NORTH OF THE BOARDER. HIS 5TH OF THE SEASON AND 8TH CAREER GRAND SLAM.
<P>
------------
<P>
IT'S 7-6 MILWAUKEE LEADING IN THE 9TH. WHEN  TIES THE GAME WITH THE LONG BALL. AND PINCH HITTER      WIN'S IT WITH ANOTHER TO LEFT.  BOTH HOMERS COMING OFF. ONE OF FOUR IN THE GAME FOR THE GIANTS. THEY WIN IT 8-7. THE WIN LIFTS THEM TO THE FIVE HUNDERED MARK AS THEY TAKE TWO OF THREE FROM THE BREW CREW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
THE A'S WOULD COMPLETE THE BAY AREA SWEEP. AS TOM CANDIOTTI FLUTTERED HIS KNUCKLER IN BALTIMORE.
<P>
HE ALSO GOT A LOT OF SUPPORT. DOWN 4-3 IN THE 3RD.  DRILLS A DOUBLE TO THE GAP IN RIGHT. IT'LL SCORE TWO RUNS. A'S TAKE A 5-4 LEAD.
<P>
-------------
<P>
THE CANDY MAN GOES 7 INNINGS ALLOWING JUST FIVE HITS. LOOK AT THE EASY 5-4-3 DOUBLE PLAY.
<P>
-----------
<P>
BLOWS THIS ONE OPEN IN THE 7TH WITH A GRAND SLAM. THE 2ND IN HIS CAREER. A'S WIN 12-4. CANDIOTTI GETS HIS 2ND STRAIGHT VICTORY AFTER OPENING THE SEASON WITH 3-LOSSES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
IN GOLF. HALE IRWIN WON FOR THE 2ND STRAIGHT WEEK. TAKING THE LAS VEGAS SENIOR CLASSIC.
<P>
AND LISELOTTE  SHOT A FINAL ROUND 70 TO WIN THE CHICK FIL-A CLASSIC. HER 2ND VICTORY OF THE SEASON AND 12TH CAREER TITLE.
<P>
MEANTIME. FINAL ROUND OF THE G-G-C.  WAS THE LEADER AFTER THE 1ST ROUND. HE WOULD SHOOT A 75 TODAY. BUT AT NUMBER 12. THE MOST EXCITING SHOT IN GOLF. SUTTON WITH THE 11TH ACE THIS SEASON.
<P>
--------------
<P>
TRAILING  BY ONE SHOT AT 18. THIS TO FORCE A PLAYOFF. AND HE DRILLS IT. FROM 30 FEET. VERPLANK ON THE PRACTICE RANGE. AND PRACTICE MAKES PERFECT.
<P>
-----------
<P>
THIS IS DODDS APPROACH ON THE 1ST PLAYOFF HOLE. AND IT'S A GOOD ONE. HE WOULD 2-PUTT FOR THE VICTORY. HIS 1ST ON THE PGA TOUR.     
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Racing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Racing</H3><BR>
AND IT WAS ROUGH GOING AT THE DIEHARD 500.  A 20-CAR CRASH ON LAP 142.  AMOUNG THE BANGED AND BATTERED. EARNHARD WOULD SUFFER 2ND DEGREE BURNS TO HIS NECK AND FACE. BUT NO ONE ELSE WAS SERIOUSLY INJURED.
<P>
-------------
<P>
WOULD END HIS DROUGHT AT THE TALLADEGA SPEEDWAY BY BLOWING PAST HIS BROTHER,
<P>
TERRY, ON THE NEXT-TO-LAST LAP TO WIN THE DIEHARD 500. HE BECOMES THE FIRST PONTIAC DRIVER TO WIN AT
<P>
TALLADEGA SINCE  IN 1983.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=133Harley Jump>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Harley Jump</H3><BR>
THOUSANDS OF PEOPLE LINED THE STREETS IN FRONT OF THE WORLD'S LARGEST HARLEY-DAVIDSON DEALERSHIP TODAY.FOR A RECORD BREAKING JUMP. 
<P>
STUNT RIDER BUBBA BLACKWELL SUCCESSFULLY JUMPED 20 CARS ON HIS CUSTOMIZED HARLEY-DAVIDSON XR-750.
<P>
THE STUND SHATTERED EVIL KNIEVEL'S 19-CAR RECORD SET BACK IN 19-71.  
<P>
IF YOU'RE WONDERING.BLACKWELL'S BIKE IS THE SAME TYPE KNIEVEL USED TO SET THE OLD RECORD. 
<P>
THE DIFFERENCE?
<P>
THE 20 CARS BLACKWELL JUMPED ON HIS AMERICAN MADE BIKE WERE HUNDAIS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Lego Champions>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lego Champions</H3><BR>
IT'S AN ADVANCED BUILDING COMPETITION. USING CHILDHOOD BUILDING BLOCKS. 
<P>
SIX FINALISTS HAD TWO-HOURS TO DESIGN AND CONSTRUCT THEIR VISIONS OF FUTURISTIC UNDERWATER EXPLORATION VEHICLES. USING "LEGOS".
<P>
YES.  WITH LEGOS. 
<P>
THE WINNER USED THESE MINIATURE BUILDING BLOCKS TO WIN " THE LEGO DEEP-SEA CHALLENGE BUILDING CONTEST". 
<P>
ALL THE FUN IS SPONSORED BY THE LEGO COMPANY.
<P>
THEY'RE HOPING TO ENCOURAGE KIDS TO BECOME THE  OCEANOGRAPHERS.SCIENTISTS. AND ENGINEERS OF THE FUTURE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
