KCBA FIRST AT TEN, Thursday, 4/16/98


           SQ1 (Killer)
                                        Across America
           TOSS TO FOX
                                        (Ohio flooding)
           NASA El Nino survey
                                        (miami warehse fire)
           El Nino fishermen
                                        (mcdonald's strike)
           Pajaro river agency
                                        (tim allen rehab)
           Price of Berries
                                        Fox Biz/bullet car
           Osio plaza GB
                                        Seifert
           Crivello Bldg GB
                                        Sharks
           Beach development
                                        A's
           SC Sheriff's grant
                                        PGA Tour Golf
           Panhandling ban
                                        Senior Golf
           Gilroy internet porn
                                        Laguna Seca
           Felton Fire
                                        Mambo marathon
           Bump 1(tim allen) 
                                        Object Affection-INT
           bump 2(fox biz) 
                                        Hole-in-one



    SQ1 (Killer)


COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN. 

MORE THAN A HUNDRED PEOPLE ARE HURT AS TORNADOS CONTINUE
THEIR RAMPAGE ON THE SOUTHWEST. 

WE'LL HAVE A LIVE REPORT FROM NASHVILLE. WITH THE LATEST ON
DEVASTATION. 

AND HERE ON THE CENTRAL COAST. FISHERMEN ARE SEEING SOME
RELIEF AFTER BEING DUNKED BY EL NINO. 

BUT FARMERS AREN'T SO LUCKY. THE HEAVY RAINS HAVE DESTROYED
CROPS. 

LOSSES WHICH MAY SOON TRICKLE DOWN TO CONSUMERS. 

WE'LL HAVE ALL THE NEWS, WEATHER AND SPORTS.KCBA FOX NEWS IS
NEXT. 

Return to index of stories...


    TOSS TO FOX


GOOD EVENING. AND THANKS FOR JOINING US. I'M CHERI GYURO. ALAN
MARSDEN HAS THE NIGHT OFF. 

A RAINY AFTERNOON TURNS VIOLENT IN NASHVILLE, TENNESSEE. 

TWO TORNADOES TEAR THROUGH DOWNTOWN WITHIN A COUPLE HOURS.

AT LEAST ONE HUNDRED PEOPLE ARE HURT. MOSTLY FROM FLYING
GLASS AND DEBRIS. 

SO FAR NO DEATHS HAVE BEEN CONFIRMED. 

ABOUT 3-HUNDRED BUILDINGS ARE DAMAGED. INCLUDING THE STATE
CAPITOL, THE RED CROSS HEADQUARTERS AND A HOTEL. 

TENNESSEE'S GOVERNOR HAS DECLARED NASHVILLE A DISASTER
AREA. 

FOX'S GRANT RAMPY JOINS US LIVE FROM NASHVILLE WITH THE LATEST. 

GRANT. 

AND SAYS STATE WORKERS SHOULD TAKE TOMORROW OFF SO
AUTHORITIES CAN ASSESS DAMAGE. 

Return to index of stories...


    NASA El Nino survey


BACK HERE ON THE CENTRAL COAST. 

SCIENTISTS ARE MEETING TO TALK ABOUT HOW MUCH OF THE COAST
LINE WAS WIPED OUT BY EL NINO. 

THEY HOPE THE INFORMATION THEY GATHER WILL IMPROVE THEIR ABILITY
TO PREDICT COASTAL EROSION IN THE FUTURE. 

IF WE CAN PREDICT COASTAL EROSION BETTER, WE CAN DECIDE
WHETHER TO SET CONSTRUCTION BACK FAR ENOUGH FROM THE
COASTLINE, SO THAT SOMETHING LIKE THIS DOESN'T CONTINUE TO
HAPPEN. IT'S VERY EXPENSIVE TO KEEP REPLACING HOMES, ETC THAT
FALL INTO THE OCEAN, BUT FOR PROPERTY OWNERS, IT'S A VERY
DIFFICULT QUESTION TO APPROACH. 

THIS IS THE LARGEST SCALE STUDY OF COASTAL EROSION EVER
UNDERTAKEN. 

Return to index of stories...


    El Nino fishermen


FISHERMEN WHO'VE LOST MONEY BECAUSE OF EL NINO.WILL NOW BE
ELIGIBLE FOR SMALL BUSINESS ADMINSTRATION LOANS. 

THE ANNOUNCEMENT WAS MADE BY CONGRESSMAN SAM FARR TODAY. 

THE LOANS COVER THE IMPACT OF EL NINO STARTING BACK IN JUNE OF
LAST YEAR. 

SMALL BUSINESSES THAT RELY ON THE FISHING INDUSTRY WILL ALSO BE
ABLE TO RECEIVE A LOAN. 

APPLICATIONS WILL BE ACCEPTED UNTIL JANUARY 13-TH OF NEXT YEAR. 

Return to index of stories...


    Pajaro river agency


A NEW AGENCY COULD TAKE THE HELM OF THE PAJARO RIVER. AND TRY
TO PUT A CORK IN ALL THE FLOODING PROBLEMS. 

FLOODING ALONG THE RIVER IN RECENT YEARS HAS LED TO LOSSES IN
THE MILLIONS OF DOLLARS. 

NOW. STATE ASSEMBLYMAN FRED KEELY IS LOOKING TO CREATE A
PAJARO RIVER AGENCY. 

THE GROUP WOULD BE GIVEN AUTHORITY TO RAISE TAXES AND
SPEARHEAD FLOOD CONTROL PROJECTS. 

Return to index of stories...


    Price of Berries


THE IMPACT OF EL NINO ALSO BEING FELT TONIGHT IN LOCAL
STRAWBERRY FIELDS. 

AND SOON.CONSUMER'S WILL FEEL THE PINCH IN THEIR POCKETBOOKS. 

HEAVY RAINS KEPT GROWERS FROM THEIR FIELDS. 

IT'S HAVING A DOMINO EFFECT ON THE INDUSTRY OVERALL. 

THE CONSTANT RAIN HAS ALREADY RUINED AN ENTIRE CROP IN PAUL
KOHATSU'S FIELD. 

MOST OF HIS BERRIES ARE HEADED FOR THE JUICER. NOT THE MARKET. 

WE'RE NOT WITH OUR FULL FORCE. TO THE LACK OF WORK. 

KOHATSU SAYS HIS FIELDS ARE DRYING OUT.THANKS TO THE SUNNY
WEATHER WE'VE BEEN HAVING. 

SOON, HIS BUSINESS WILL BE BACK TO NORMAL. 

STILL.HE'S LOST 1/3RD OF HIS CROP FOR THE SEASON. 

CONSUMERS WILL ALSO FEEL THE BRUNT OF THE LOSS WHEN LOW
STOCK DRIVES UP PRICES. 

Return to index of stories...


    Osio plaza GB


A NEW LOOK FOR DOWNTOWN MONTEREY. 

THE HISTORIC AREA GETS A FACELIFT. 

GROUNDBREAKING FOR ONE OF A SERIES OF PROJECTS WAS HELD THIS
AFTERNOON. 

IT'LL BE KNOWN AS "OSEEO PLAZA". 

THE PROJECT WILL INCLUDE. A MOVIE THEATRE COMPLEX AND 30 NEW
APARTMENTS. 

CITY OFFICIALS SAY THIS DEVELOPMENT IS PART OF THEIR CONTINUING
EFFORTS TO RE-VITALIZE THE DOWNTOWN AREA. 

WE'RE VERY EXCITED. SIX THEATRES, MODERATE AND LOW INCOME
APARTMENTS, AND RETAIL, WILL BRING ADDED LIFE TO THE DOWNTOWN. 

IT'LL TAKE ABOUT A YEAR BEFORE THE "OSEEO" PLAZA IS COMPLETE. 

Return to index of stories...


    Crivello Bldg GB


JUST A COUPLE BLOCKS AWAY. ANOTHER MAJOR RETAIL CONSTRUCTION
PROJECT IS ABOUT TO GET UNDERWAY. 

INSTEAD OF THE TRADITIONAL RIBBON CUTTING CEREMONY, DEVELOPER
JOHN CRIVELLO HELD A "TIE" CUTTING. 

IT WAS HELD ON THE SITE THAT WILL HOUSE A NEW OFFICE AND RETAIL
COMPLEX. 

THE TWO STORY STRUCTURE WILL INCLUDE OVER 15 THOUSAND
SQUARE FEET OF OFFICE SPACE. JUST THREE BLOCKS FROM
DOWNTOWN. 

CONSTRUCTION IS EXPECTED TO TAKE ABOUT SIX MONTHS. 

Return to index of stories...


    Beach development


CITY PLANNERS IN SANTA CRUZ ARE HOSTING A PUBLIC MEETING
TONIGHT. 

IT'S A DISCUSSION ABOUT A MAJOR EFFORT TO RE-DEVELOP THE BEACH
AREA. 

THE LONG-TERM PLAN FIRST TOOK SHAPE LAST 

SUMMER. 

THE IDEA IS TO MAKE THE SANTA CRUZ BEACH BOARDWALK, 

THE WHARF, AND AREAS IN BETWEEN, MORE ATTRACTIVE 

FOR TOURISTS. 

ALSO A CONCERN. THE BEACH FLATS. 

"THE REAL CRITICAL ISSUE FACING THE CITY IS THAT THE BEACH FLATS
AREA 

HAS THE HIGHEST CRIME RATE IN THE CITY. IT'S 48-PERCENT OF THE
CITY'S FELONY ARRESTS WITH ONLY 2-PERCENT OF THE POPULATION." 

CITY PLANNER EILEEN FOGARTY SAYS THE CITY'S GOAL IS TO CREATE
NEW AFFORDABLE HOUSING. AND CREATE A MORE LIVABLE
NEIGHBORHOOD. 

A SERIES OF PUBLIC MEETINGS WILL BE HELD OVER THE NEXT SEVERAL
MONTHS. 

Return to index of stories...


    SC Sheriff's grant


FOLKS IN SANTA CRUZ COUNTY WILL SOON HAVE MORE LAW
ENFORCEMENT OFFICERS ON THE JOB. 

THAT'S THANKS TO A NEW GRANT SPEAR-HEADED BY PRESIDENT
CLINTON. 

THE SHERIFF'S OFFICE WILL BE ADDING FOUR NEW DEPUTIES TO ITS
FORCE. 

THE 300- THOUSAND DOLLAR AWARD IS PART OF THE PRESIDENT'S PUSH
FOR "COMMUNITY ORIENTED POLICING SERVICES". 

IT WILL BE PAID OUT OVER A PERIOD OF THREE YEARS. 

Return to index of stories...


    Panhandling ban


PAN-HANDLERS LOOKING FOR SPARE CHANGE MAY GET A TICKET
INSTEAD. 

THE NEW PANHANDLING ORDINANCE TAKES AFFECT IN SALINAS TODAY. 

IT'S NOW A MISDEMEANOR TO COMMIT AN ACT OF AGGRESSIVE
PAN-HANDLING. 

STORE-OWNERS ON MAIN STREET IN OLD TOWN SAY THEY'RE HAPPY TO
SEE THE CITY TAKE A TOUGH STANCE. 

THEY BLAME PAN-HANDLERS FOR CHASING AWAY SOME OF THEIR
BUSINESS. 

Return to index of stories...


    Gilroy internet porn


GILROY ^PARENTS^ ARE ONE STEP CLOSER TO WIPING OUT
PORNOGRAPHY ON THE INTERNET AT LOCAL LIBRARIES. 

ABOUT 3-THOUSAND CONCERNED PARENTS WANT LIBRARIES TO INSTALL
SOFTWARE THAT WOULD PREVENT KIDS FROM ACCESSING
PORNOGRAPHY ON THE INTERNET. 

A BILL WAS INTRODUCED AFTER THOSE PARENTS FORMED A PROTEST
GROUP. 

THE LEGISLATION HAS BEEN APPROVED IN ONE ASSEMBLY
SUB-COMMITTEE. 

THE NEXT STEP FOR THE BILL. IS A REVIEW BY THE INFORMATION AND
TECHNOLOGY COMMITTEE. 

Return to index of stories...


    Felton Fire


FIRE GUTTED A SMALL HOME IN FELTON 

TODAY. LEAVING AN ELDERLY WOMAN HOMELESS. 

ISABEL KELLY SAYS SHE WAS COOKING HER LUNCH. WHEN A PIECE OF
PAPER CAUGHT FIRE ON HER STOVE. 

A FIREFIGHTER. WHO JUST HAPPENED TO BE DRIVING BY. WAS ON THE
SCENE IN MINUTES TO HELP GET KELLY OUT OF THE HOME AND PREVENT
THE BLAZE FROM SPREADING TO OTHER HOMES. 

Return to index of stories...


    Bump 1(tim allen) 


COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN. 

BEFORE HE CAN GET BACK TO HOME IMPROVEMENT. TIM ALLEN WILL BE
MAKING A PIT STOP AT A REHAB CENTER. 

Return to index of stories...


    bump 2(fox biz) 


AND. MOST PEOPLE THINK OF THEIR CARS AS CASTLES ON WHEELS. BUT
WE'LL SHOW YOU ONE THAT'S MORE LIKE A FORTRESS. 

RIGHT AFTER THIS. 

Return to index of stories...


    Across America


ROADS ARE CLOSED AND SEVERAL CITIES GO THROUGH EMERGENCY
EVACUATIONS AS SPRING FLOODING CAUSES BIG TROUBLE. 

THAT STORY FROM CINCINATI, OHIO. TOPS OUR LOOK AT NEWS ACROSS
AMERICA. 

Return to index of stories...


    (Ohio flooding)


OVERNIGHT STORMS DUMPED SIX INCHES OF WATER IN PARTS OF THE
STATE. 

RESIDENTS PLOWED THROUGH FLOODED STREETS CLOGGED UP WITH
WITH LOGS AND DEBRIS. 

ABOUT SIX THOUSAND CUSTOMERS HAVE NO POWER. 

THE GREAT MIAMI RIVER IS EXPECTED TO CREST NEAR 18 AND A HALF
FEET. 

Return to index of stories...


    (miami warehse fire)


SOME TENSE MOMENTS TODAY FOR MIAMI FIREFIGHTERS. 

EMERGENCY CREWS RESPONDED TO A MASSIVE FIRE AT A FERTILIZER
WAREHOUSE STORAGE FACILITY. 

FLAMES ENGULFED THE ENTIRE BUILDING LETTING OFF TOXIC FUMES. 

LUCKILY, THERE WERE NO INJURIES. 

Return to index of stories...


    (mcdonald's strike)


THE FIRST MCDONALD'S STRIKE IN U.S. HISTORY IS OVER. 

AFTER FIVE DAYS OF PICKETING.TEEN-AGE WORKERS IN CLEVELAND
ARE GOING BACK TO FLIPPING BURGERS AND MAKING FRENCH FRIES. 

THE WORKERS CLAIMED THAT THEY WERE VERBALLY ABUSED BY THEIR
MANAGER. 

THEY ALSO COMPLAINED THAT SOME NEW 

HIRES GOT PAID MORE THAN EXPERIENCED WORKERS. 

UNDER THE SETTLEMENT, THE OWNER AND HIS MANAGERS WILL
UNDERGO HUMAN RELATIONS TRAINING. 

Return to index of stories...


    (tim allen rehab)


ON THE HOLLYWOOD SCENE.A PUBLICIST FOR COMEDIAN TIM ALLEN
SAYS THE STAR CHECKED INTO A COURT-ORDERED REHAB CENTER FOR
ALCOHOL COUNSELING TODAY. 

THE ACTOR OF A-B-C'S SITCOM "HOME IMPROVEMENT" PLEAD GUILTY TO
A DRUNK-DRIVING CHARGE IN MICHIGAN LAST YEAR. 

THE PUBLICIST DID NOT DISCLOSE THE NAME OR LOCATION OF THE
REHAB CLINIC.BUT SAYS THE SHOW WILL CONITNUE WITHOUT ALLEN. 

Return to index of stories...


    Fox Biz/bullet car


IN THE MARKET FOR A NEW CAR.? 

WELL, BESIDES THE NORMAL FEATURES LIKE ANTI-LOCK BRAKES AND
CRUISE CONTROL. HOW ABOUT BULLET PROOF GLASS.?? 

IT'S THE LATEST THING TO ROLL OFF THE ASSEMBLY LINE. 

WE'LL STEER THROUGH THE DETAILS IN TONIGHT'S FOX BUSINESS
REPORT. 

B-M-W IS TARGETING CELEBRITIES, EXECUTIVES AND JUST ABOUT
ANYONE LOOKING TO STAY SAFE THESE DAYS. 

WHAT THEY'RE SELLING IS THE 540-PROTECTION CAR. A BULLET PROOF
LUXURY SEDAN. 

FOR ABOUT 88-THOUSAND DOLLLARS YOU GET BULLET RESISTANT
GLASS. BULLET-RESISTANT FIBER BEHIND THE SHEET METAL. TIRES THAT
WORK EVEN WHEN THEY'RE FLAT. AND A P-A SYSTEM THAT'S LETS YOU
BE HEARD OUTSIDE THE VEHICLE WITHOUT OPENING ANY WINDOWS OR
DOORS. 

OTHER AUTO MAKERS ARE JUMPING ON THE BANDWAGON. SAYING
THEY'RE LOOKING INTO DEVELOPING THEIR OWN ARMORED CARS. 

Return to index of stories...


    Seifert


IF GEORGE SEIFERT WASN'T ACTUALLY FORCED OUT AS COACH OF THE
49ERS, IT WOULD BE ACCURATE TO SAY HE WAS GIVEN A GENTLE
NUDGE. 

AND EVER SINCE THE HEAD COACH WITH THE NFL'S BEST ALL-TIME
WINNING PERCENTAGE STEPPED ASIDE, THE BIG QUESTION HAS BEEN,
WHERE WOULD HE COACH NEXT. 

THE QUESTION IS ANSWERED TODAY, SORT OF. GEORGE SEIFERT, WHO
TOOK LAST YEAR OFF, HAS DECIDED COACHING IS HARD WORK AND
TAKES TOO MUCH TIME. 

SO HE HAS SIGNED ON TO BE A STUDIO ANALYST WITH CBS THIS YEAR.
CBS IS GETTING BACK IN THE FOOTBALL BUSINESS THIS FALL, FOR THE
FIRST TIME IN 4-YEARS. 

SEIFERT WILL BE JOINED IN THE STUDIO BY JIM NANCE, MARCUS ALLEN,
AND HIS FORMER PLAYER, BRENT JONES. 

THIS WAY HE'LL STILL HAVE TIME TO FISH. IN FAIRNESS TO SEIFERT, THE
RIGHT COACHING JOB JUST MAY NOT HAVE COME UP FOR HIM. 

Return to index of stories...


    Sharks


CONGRADULATIONS TO THE SAN JOSE SHARKS, WITH LAST NIGHT'S TIE
AT CALGARY, COUPLED WITH CHICAGO'S LOSS, SAN JOSE CLINCHES ITS
FIRST PLAYOFF BIRTH SINCE 1995. 

THE SHARKS ARE UNBEATEN IN THEIR LAST 7-GAMES, AND TONITE THEY
VISIT THE COLORADO AVALANCHE, WITH PLAYOFF SEEDINGS STILL ON
THE LINE. 

Return to index of stories...


    A's


THE GIANTS ARE OFF, BUT THE A'S ARE IN ACTION. 

OAKLAND HAS LOST 6-STRAIGHT, DESPITE HAVING LEADS IN EACH OF
THOSE GAMES. 

TONITE THE ATHLETICS RETURN HOME TO OPEN A 4-GAME SERIES WITH
THE KANSAS CITY ROYALS. 

Return to index of stories...


    PGA Tour Golf


TO GOLF, AND FOLLOWING LAST WEEK'S EXCITING MASTERS, THE PGA
TOUR LANDS ON HILTON HEAD ISLAND, SOUTH CAROLINA, FOR THE M.C.I.
CLASSIC. 

WE WON'T CALL HIM THE 5-TIME AT&T CHAMP ANYMORE, MARK O'MEARA
IS NOW THE MASTERS CHAMP. IN HIS FIRST ROUND SINCE AUGUSTA,
O'MEARA FIRES A 1-UNDER PAR 70. HE'S FOUR SHOTS OFF THE LEAD. 

DAVIS LOVE THE THIRD ALWAYS PLAYS WELL AT HILTON HEAD, HERE'S
HIS APPROACH AT 17. VERY NICE. LOVE SHOOTS A 67, HE'S 1-SHOT OFF
THE LEAD. 

THREE GOLFERS ARE TIED AT THE TOP, JAY HAAS WITH THE BIRDIE HERE
SHOOTS A 5-UNDER 66, AS DOES JOHN HUSTON AND DOUG TEWELL. 

Return to index of stories...


    Senior Golf


MEANWHILE THE SENIOR TOUR CHAMPIONSHIP IS TAKING PLACE IN PALM
BEACH GARDENS, FLORIDA. 

JACK NICKLAUS, FRESH OFF HIS GREAT SHOWING AT THE MASTERS, IS
MAKING A RUN AT A SENIOR MAJOR THIS WEEK. 

THE GOLDEN BEAR SHOOTS A 4-UNDER 68, AND IS TIED FOR THE FIRST
ROUND LEAD WITH. 

2-DEFENDING CHAMP HALE IRWIN. NICKLAUS AND IRWIN LEAD GIL
MORGAN AND LARRY NELSON BY ONE STROKE. 

Return to index of stories...


    Laguna Seca


AND FINALLY, QUALIFYING FOR THE HONDA CHALLENGE OF LAGUNA
SECA GETS UNDERWAY TOMORROW. 

WE HAD A CHANCE TO CHAT WITH SALINAS' DOUG CHANDLER, WHO'S
WON THE LAST TWO AMA SUPERBIKE RACES HERE. 

WE ASKED DOUG, WHO WILL BE 33 IN SEPTEMBER AND WHO HAS A
FAMILY NOW, IF HE EVER WORRIES ABOUT THE DANGERS OF
MOTORCYCLE RACING? 

Return to index of stories...


    Mambo marathon


MAMBO DANCERS MOBBED TO NEW YORK'S FAMED "COPACABANA"
NIGHTCLUB TODAY. FOR THE CHANCE TO WIN 5-THOUSAND BUCKS. 

THE COUPLES ARE EXPECTED TO DANCE ALL NIGHT. 

THE LAST COUPLE STILL DANCING.OR AT LEAST STANDING.WINS THE BIG
PRIZE. 

THE CONTEST WAS SPONSORED BY THE RELEASE OF THE DISNEY
COMEDY "FLUBBER" ON HOME VIDEO. 

IN THE MOVIE.HUNDREDS OF LITTLE "FLUBBERS" MAMBO THEIR WAY
ONTO THE BIG SCREEN. 

Return to index of stories...


    Object Affection-INT


THEY SAY EVERYONE HAS A SOLE MATE.IT'S HARD ENOUGH 

TO FIND THAT PERSON.BUT WHAT DO YOU DO IF THEY TURN OUT TO BE
GAY? 

THAT'S WHAT JENNIFER ANISTON FACES IN HER NEW MOVIE "THE OBJECT
OF MY AFFECTION." 

FOX'S DOROTHY LUCEY TAKES A LOOK. 

Return to index of stories...


    Hole-in-one


FINALLY TONIGHT. 

THE PHRASE SAYS IT ALL."HOLE IN ONE!" 

ITS THE ULTIMATE BULLSEYE AND A LOCAL GOLFER SCORED ONE
TODAY. 

JEFF KROPHOLLER IS A PHARMACEUTICAL REPRESENTATIVE FROM
MONTEREY. WHO WAS ENJOYING A "NOT SO GREAT" ROUND OF GOLF.
UNTIL HE REACHED THE 14TH HOLE AT CARMEL VALLEY RANCH GOLF
COURSE. 

IT'S A 300-YARD. PAR FOUR. 

JEFF TOOK OUT HIS DRIVER. STOOD OVER THE BALL. AND CLOBBERED IT.

"A HOLE IN ONE IS A PRETTY GOOD THING, BUT A DOUBLE EAGLE IS EVEN
BETTER, AND CONSIDERING I'D NEVER HAD A WHOLE IN ONE BEFORE, A
DOUBLE EAGLE AND A HOLE IN ONE, ALL IN ONE SHOT, WAS A REALLY
GOOD THING FOR ME. 300 YARDS WITH A DRIVER, IN THE HOLE, PRETTY
AMAZING. I DIDN'T EXPECT IT TO HAPPEN." 

JEFF SAYS. TODAY'S SHOT WAS THE HIGHLIGHT OF HIS GOLF CAREER
AND ITS THE FIRST HOLE-IN-ONE EVER ON THAT GREEN. 

Return to index of stories...

                               Copyright © 1998
 All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.
   Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for
 broadcast or publication or redistribution directly or indirectly in any medium. Neither these AP materials nor any portion
  thereof may be stored in a computer except for personal and non-commercial use. AP will not be held liable for any
  delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any
                        damages arising from any of the foregoing.
