<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (g/Sun), Sunday, 4/12/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (g/Sun), Sunday, 4/12/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#113Local Easter-I>Local Easter-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134Britain Floods>Britain Floods</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Local Easter-G>Local Easter-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Dodi/Di Movie>Dodi/Di Movie</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Local Easter-T>Local Easter-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39Masters>Masters</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#124Cuba Easter>Cuba Easter</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41Leaderboard>Leaderboard</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Pope Easter Mass>Pope Easter Mass</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#135German Bikers>German Bikers</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#110Gays/Canterbury>Gays/Canterbury</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121SC Sleeping Ban>SC Sleeping Ban</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#144Salinas Robberies>Salinas Robberies</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Racing>Racing</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#132Cosmonauts Day>Cosmonauts Day</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#138Easter Parade-I>Easter Parade-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#104Mexico Forest Fires>Mexico Forest Fires</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137Easter Parade-G>Easter Parade-G</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#133Peru/El Nino>Peru/El Nino</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=113Local Easter-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Local Easter-I</H3><BR>
IF IT WAS ANY OTHER HOLIDAY. IT WOULD PROBABLY MEAN YOU GOT TO SLEEP IN. BUT NOT TODAY.
<P>
CERTAINLY THERE WERE A LOT OF PEOPLE JUST TAKING IT EASY AND HEADING TO THE BEACH. BUT A LOT OF OTHERS HEADED TO CHURCHES FOR THEIR TRADITIONAL EASTER SUNDAY SERVICES.
<P>
AND LOCALS KNOW. ONE OF THE MOST POPULAR PLACES TO GET THAT SUNRISE SERVICE. IS AT LOVERS POINT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=114Local Easter-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Local Easter-G</H3><BR>
THE MUSIC BEGAN POURING OUT OF LOVERS POINT BEFORE SUNRISE.
<P>
HUNDREDS OF PEOPLE BRAVING THE EARLY MORNING HOURS. AND THE BONE-CHILLING TEMPERATURES. FOR AN EVENT THAT ONLY HAPPENS ONCE A YEAR. ONLY IN PACIFIC GROVE.
<P>
SOME FAMILIES DRIVE HUNDREDS OF MILES EVERY YEAR TO ATTEND THEIR EASTER SERVICES HERE. OUT IN THE OPEN BEAUTY, SURROUNDED BY THE OCEAN. WATCHING THE SUN RISE BEFORE THEIR EYES.
<P>
INDOOR SERVICES WERE POPULAR TOO.  THE HISTORIC CARMEL MISSION SAW STANDING-ROOM ONLY CROWD AT ITS EASTER MASSES ALL DAY LONG.
<P>
MEANWHILE. THOSE WHO SKIPPED OUT ON CHURCH TO GO TO THE BEACH. LIKE THESE DIVERS FROM SAN JOSE. FOUND THEMSELVES. WELL, IN NEED OF SOME DIVINE INTERVENTION.  BLAME IT ON WHAT YOU WILL. THE WAVES THAT LOOKED SO INVITING YESTERDAY. TURNED RUTHLESS TODAY, SPOILING THEIR DIVING PLANS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Local Easter-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Local Easter-T</H3><BR>
OTHER TOURISTS WE SPOKE TO TODAY. WERE JUST GRATEFUL THE RAIN DIDN'T SPOIL THEIR PLANS.-
<P>
CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=124Cuba Easter>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cuba Easter</H3><BR>
HISTORY WAS MADE IN CUBA TODAY.
<P>
FOR THE FIRST TIME IN 37 YEARS.EASTER IS CELEBRATED.
<P>
AUTHORITIES AGREED TO ALLOW THE FIRST EASTER PARADE SINCE 19-61.  
<P>
PARADES WERE CONSIDERED ANTI-REVOLUTIONARY.AND WERE BANNED.
<P>
SOME SAY THE HISTORIC VISIT OF POPE JOHN PAUL THE SECOND LAST JANUARY PROMPTED CUBAN AUTHORITIES CHANGE OF HEART.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Pope Easter Mass>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Pope Easter Mass</H3><BR>
IN ROME.THE POPE DELIVERED HIS TRADITIONAL EASTER MESSAGE TODAY.
<P>
AN ESTIMATED AT 150-THOUSAND PEOPLE CROWDED SAINT PETER'S SQUARE.
<P>
THE PONTIFF URGED HUMANITY NOT TO REPEAT THE TRAGIC ERRORS OF THE TWENTIETH CENTURY. 
<P>
HE WARNED THE WORLD WAS BEING SOWN WITH "SEEDS OF DEATH." 
<P>
THE POPE ALSO PRAYED FOR PEACE IN THE MIDDLE EAST
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=135German Bikers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>German Bikers</H3><BR>
OPEN-AIR EASTER CHURCH SERVICES IN GERMANY. ATTRACTED A CROWD OF MOTORCYCLE ENTHUSIASTS.
<P>
MORE THAN TEN THOUSAND BIKERS FROM ALL OVER EUROPE RODE IN FOR THE EVENT.
<P>
THREE COUPLES DECIDED TO TAKE ADVANTAGE OF THE GOOD COMPANY TO TIE THE KNOT. 
<P>
THEN THEY RODE OFF ON THEIR HOGS WITH THEIR FELLOW BIKERS FOR EASTER BRUNCH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=110Gays/Canterbury>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gays/Canterbury</H3><BR>
AN EASTER SERMON IN ENGLAND IS DISRUPTED BY GAY RIGHTS ACTIVISTS.     
<P>
MEMBERS OF THE GAY RIGHTS GROUP "OUTRAGE" INTERRUPTED THE ARCHBISHOP OF CANTERBURY'S SERMON.
<P>
PROTESTORS SHOUTED THAT THE CHURCH SUPPORTS DISCRIMINATION.
<P>
POLICE QUICKLY ESCORTED THEM OUT OF THE CHURCH.
<P>
GAY ACTIVISTS SAY THEY'RE UPSET THAT THE ARCHBISHOP OPPOSES EQUAL RIGHTS FOR GAYS TO ADOPT CHILDREN AND FOR OPPOSING THE ORDINATION OF HOMOSEXUALS INTO THE ANGLICAN CHURCH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121SC Sleeping Ban>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Sleeping Ban</H3><BR>
CHURCH LEADERS IN SANTA CRUZ ARE TRYING TO REPEAL THE CITY'S CURRENT SLEEPING BAN.
<P>
PEOPLE FOUND SLEEPING IN PUBLIC CAN BE TICKETED. OR EVEN ARRESTED.
<P>
SOME SAY THE LAW TARGETS THE HOMELESS.
<P>
SO TODAY. MEMBERS OF LOCAL GROUPS STOOD OUTSIDE A SANTA CRUZ CHURCH HOPING TO GET ENOUGH SIGNATURES TO PLACE AN INITIATIVE ON THE NOVEMBER BALLOT.
<P>
"WELL. I CERTAINLY THINK. THIS IS THE WRONG WORD TO USE BUT A BLANKET ON SLEEPING IN PUBLIC IS NOT ALL THAT HUMAN."
<P>
REPEAL SUPPORTERS SAY THEY HOPE A NEW LAW CAN BE MADE SAFEGUARDING THE RIGHTS OF PROPERTY OWNERS AND THE HOMELESS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=144Salinas Robberies>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas Robberies</H3><BR>
SALINAS POLICE SEARCHING TONIGHT FOR FIVE SUSPECTED GANG MEMBERS.
<P>
INVESTIGATORS SAY THREE PEOPLE WERE BEATEN AND ROBBED.INCLUDING A PREGNANT WOMAN.
<P>
        THE VICTIMS. ALL SALINAS RESIDENTS. WERE NOT SERIOUSLY INJURED.
<P>
        THE FIRST INCIDENT TOOK PLACE ON BRIDGE STREET. WHERE A 25-YEAR OLD MAN WAS ROBBED AND BEATEN.
<P>
A SHORT TIME LATER.  TWO PEOPLE. INCLUDING THE WOMAN. WERE ROBBED ON SOLEDAD STREET NEAR MARKET WAY.
<P>
THE VICTIMS WERE TREATED FOR MINOR INJURIES AND RELEASED.
<P>
THE SUSPECTS WERE RIDING IN A DARK BROWN MONTE CARLO. AND WERE WEARING BLUE CLOTHING.
<P>
        
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=132Cosmonauts Day>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Cosmonauts Day</H3><BR>
WELCOME BACK.
<P>
ON THIS DATE 37 YEARS AGO. OUR WORLD CHANGED.
<P>
ON APRIL 12TH, 1961.YURI GA-GARIN. A MAJOR IN THE RUSSIAN AIR FORCE. BECAME THE FIRST MAN TO TRAVEL IN SPACE. 
<P>
THE JOURNEY CONSISTED OF ONE ORBIT AROUND THE EARTH WHICH LASTED ONE HOUR AND 48 MINUTES. 
<P>
THE EVENT PROMPTED AMERICA TO SPEED UP ITS OWN SPACE PROGRAM TO KEEP UP WITH THE SOVIETS. 
<P>
THE CREW OF THE "MIR" SPACE STATION BROADCAST A SPECIAL TRIBUTE TODAY. HONORING THE ACHIEVEMENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=104Mexico Forest Fires>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mexico Forest Fires</H3><BR>
MEXICO'S THIRD LARGEST CITY. MONTERREY.  IS BEING THREATENED BY FOREST FIRES. 
<P>
JUST OUTSIDE THE CITY.A BLAZE DESTROYED 15-HUNDRED ACRES. 
<P>
THE MEXICAN GOVERNMENT SAYS MOST OF THE FIRES WERE CAUSED BY FARMERS CLEARING LAND FOR CROPS.
<P>
ABOUT 330-THOUSAND ACRES OF LAND HAVE ALREADY BEEN CONSUMED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=133Peru/El Nino>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Peru/El Nino</H3><BR>
EL NINO BACK IN THE NEWS AGAIN.THIS TIME IN PERU.
<P>
WEATHER PROBLEMS ARE THREATENING THE COUNTRY'S HISTORICAL SITES AND TOURISM INDUSTRY.     
<P>
PREHISTORIC RUINS ARE CRUMBLING DUE TO TORRENTIAL RAINS.
<P>
ARCHEOLOGISTS FEAR THE DAMAGE MAY BE IRREVERSIBLE.AND SOME HISTORICAL SITES MIGHT HAVE TO BE CLOSED. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=134Britain Floods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Britain Floods</H3><BR>
PEOPLE IN ENGLAND ARE RECOVERING FROM MASSIVE DOWNPOURS THAT FLOODED THE AREA. 
<P>
FLOOD WATERS THREATENED TO OVERRUN CANALS AND STREAMS THROUGHOUT THE MIDSECTION OF ENGLAND. 
<P>
TRAILERS IN A PARK WERE LIFTED UP BY THE WATERS AND MOVED IN STRATFORD ON AVON. 
<P>
ONE PERSON IS DEAD.ANOTHER MISSING.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Dodi/Di Movie>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Dodi/Di Movie</H3><BR>
CONTROVERSY OVER THE LATE PRINCESS DIANA'S LIFE AND DEATH CONTINUES.
<P>
A FILM.  CALLED "DIANA, A TRIBUTE TO THE PEOPLE'S PRINCESS". WAS SHOWN ON A BRITISH CABLE CHANNEL THIS WEEKEND. 
<P>
THE FILM USES LOOK-ALIKES TO PORTRAY DIANA'S LAST YEAR OF LIFE. 
<P>
IT BEGINS WITH EVENTS IMMEDIATELY PRIOR TO DIANA'S DEATH.AND ENDS WITH THE PARIS CAR CRASH ON SEPTEMBER 31ST, 19-97. 
<P>
THE FILM-MAKER. LIVE T-V. SAYS THE MOVIE IS A TRIBUTE 
<P>
TO DIANA.BUT THE LATE PRINCESS'S LAWYERS SAY THE COMPANY IS JUST TRYING TO CASH IN ON HER DEATH. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39Masters>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Masters</H3><BR>
MARK O'MEARA HAD BEEN KNOW FOR HIS DOMINANCE AT PEBBLE BEACH. AFTER ALL.5 OF HIS 14 VICTORIES HAD COME RIGHT HERE ON THE CENTRAL COAST.
<P>
BUT AFTER SUNDAY'S STIRRING VICTORY AT THE MASTERS. PEOPLES PERCEPTION OF THE 41-YEAR OLD VETERAN MAY HAVE CHANGED A BIT.
<P>
SO MANY GREAT STORIES IN THE FINAL ROUND. HOW ABOUT.   THE GOLDEN BEAR MAKING A CHARGE RIGHT OUT OF THE GATE. HE CHIPS IN FOR BIRDIE AT NUMBER THREE. NICKLAUS FINISHES WITH A 68. GOOD ENOUGH FOR 6TH PLACE.
<P>
------------
<P>
WAS NOT AS FORTUNATE. THE DEFENDING CHAMPION NEVER A FACTOR IN THIS ONE. HE WOULD CLOSE WITH A 70. AND FINISH IN 8TH.
<P>
-----------
<P>
THIS ONE COMES DOWN TO THE BACK NINE AS USUAL.. THE LEADER FOR MOST OF THE TOURNEY. BUT AT 13. HIS APPROACH WILL FIND IT'S WAY INTO RAY'S CREEK. HE WOULD TAKE A DOUBLE.
<P>
----------
<P>
HE BOUNCES BACK THOUGH AND MAKES UP FOR THE DOUBLE AT THE PAR FIVE 15TH. THIS HIS 2ND SHOT. AND IT'S A BEAUTY. IT LEADS TO AN EAGLE AND COUPLES WAS BACK IN THE HUNT.
<P>
-----------
<P>
BUT O'MEARA WAS SOLID. PLAYING IN THE SAME GROUP AS COUPLES. A BIRDIE AT 15. AND THEN ANOTHER AT 17. TO TIE COUPLES FOR THE LEAD AT 8-UNDER ALONG WITH  WHO WAS IN THE CLUB HOUSE.
<P>
----------
<P>
AT 18. O'MEARA HAS THIS 20-FOOT BIRDIE PUTT FOR THE WIN. AND HE DRAINS IT BECOMING JUST THE 3RD GOLFER IN HISTORY TO WIN THE MASTERS WITH A BIRDIE AT 18. O'MEARA CLOSES WITH A FIVE UNDER 67. IT'S HIS 1ST MAJOR IN 57 TRIES. AND HE BECOMES THE 14TH DIFFERENT WINNER IN THE LAST 14 MAJORS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41Leaderboard>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Leaderboard</H3><BR>
IN FACT. O'MEARA'S 279 WAS 9-SHOTS HIGHER THAN TIGERS RECORD SETTING TOTAL OF LAST YEAR.
<P>
BUT LIKE TIGER. O'MEARA'S PUTTER WAS THE DIFFERENCE. WITH O'MEARA THREE PUTTING JUST ONCE DURING THE TOURNAMENT.
<P>
O'MEARA'S PREVIOUS BEST WAS A 4TH PLACE FINISH IN 1992. THE YEAR COUPLES WON. IT'S JUST HIS 2ND TOP TEN FINISH IN 14 TRIES.  IN CONTRAST. JACK NICKLAUS WRAPS UP HIS 40TH MASTERS BY FINISHING IN THE TOP TEN FOR THE 22ND TIME. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
TO BASEBALL NOW. THE GIANTS AND CARDINALS CONTINUING THEIR 4-GAME SERIES AT THE STICK. AND WITH THE GIANTS OFFENSE IN A SLUMP. IT WAS UP TO OREL HERSHEISER TO PROVIDE ANOTHER SOLID PERFORMANCE.  
<P>
THE BULLDOG ENDEARING HIMSELF TO GIANTS FANS ONE MORE TIME. TRAILING 1-ZIP IN THE 4TH. HE WHIFFS. ONE OF 6 K'S IN SEVEN INNINGS OF WORK.
<P>
-----------
<P>
HE ALSO GETS SOME HELP FROM THE GUYS BEHIND HIM. IN THE 5TH. DRIVES ONE TO THE GAP. BUT  RUNS IT DOWN TO END THE INNING.
<P>
------------
<P>
GAME TIED AT ONE IN THE 7TH WITH ONE OUT.  SENDS A FLY TO RIGHT.  WILL TEST  ARM. AND IT LOOKS LIKE HE GETS IN THERE BUT THE UMP CALLS HIM OUT. IT ENDS THE INNING WITH THE SCORE STILL TIED AT ONE. BUT NOT BEFORE SNOW GOES BALISTIC. AND UMPIRE  RUNS HIM. 
<P>
-----------
<P>
THE GIANTS WOULD GET REDEMPTION. GAME TIED AT ONE IN THE BOTTOM OF THE 9TH. AND BAGS FULL OF GIANTS.
<P>
----------
<P>
THE 3-0 OFFERING TO  IS LOW AND  WALKS HOME THE WINNING RUN. AS THE GIANTS WIN IT. 2-1 IS THE FINAL. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
OVER IN THE A-L. THE A'S PROBLEMS CONTINUE IN THE BIG APPLE.
<P>
OAKLAND GETTING SWEPT BY THE RED HOT YANKEE PIN-STRIPERS. AS THE A'S LOSE THEIR 6TH STRAIGHT IN THE HOUSE THAT RUTH BUILT.
<P>
ON HAND FOR THIS ONE.
<P>
---------
<P>
SPEAKING OF SWEET THINGS. LOOK AT THE SWING FROM  WITH THE SINGLE TO RIGHT.  SCORES 2-ZIP A'S.
<P>
----------
<P>
IT'S 5-4 IN THE 6TH. WHEN  DELIVERS WITH A SINGLE UP THE MIDDLE. THAT SCORES TWO RUNS. YANKS GO ON TOP 6-5.
<P>
----------
<P>
THEN. IN THE 7TH. IT'S DAR-YL. DARRYL STRAWBERRY WITH A SOLO SHOT OFF MIKE MOHLER. YANKS WIN IT. 7-5. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
THE RED HOT SHARKS ARE UNBEATEN IN THE PAST SIX GAMES. AND CURRENTLY IN 8TH PLACE IN THE WEST WITH 3 GAMES TO PLAY.

<P>
THEY ARE HOWEVER JUST ONE POINT BACK OF EDMONTON AND 3-BACK OF PHOENIX. THEIR NEXT GAME IS WEDNESDAY IN CALGARY.
<P>
LIGHT NIGHT ON THE ICE. PHOENIX BEATS CHICAGO KEEPING THE BLACKHAWKS 3-POINTS BACK OF THE SHARKS.
<P>
IT'S DALLAS OVER ST. LOUIS 4-3.
<P>
---------
<P>
AND THE PANTHERS AND DEVILS SKATE TO A FIVE-FIVE TIE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
TO TENNIS NOW.  TAKING ON  IN THE FINALS OF THE BAUSCH AND LOMB CHAMPIONSHIP.
<P>
-----------
<P>
MARTINEZ IN THE NEAR COURT. AND SHE WOULD JUMP OUT TO AN EARLY LEAD WINNING THE 1ST SET 10-8 IN THE TIEBREAKER.
<P>
---------
<P>
PIERCE SETTLES DOWN THOUGH WINNING THE 2ND SET 6-LOVE. SHE WOULD WIN 8-STRAIGHT GAMES JUMPING OUT TO A 2-OH LEAD IN THE 2ND SET.
<P>
----------
<P>
ON MATCH POINT. MARTINEZ WILL HIT IT INTO THE NET. AND PIERCE WIN'S. 6-2 IN THE 3RD. IT'S HER 2ND VICTORY THIS SEASON AND 10TH CAREER SINGLES TITLE. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Racing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Racing</H3><BR>
FINALLY. TO FORMULA ONE RACING. LOTS OF SLIP SLIDING AWAY AT THE ARGENTINA GRAND PRIX.
<P>
SPINS  ACROSS THE GRASS AND OUT OF THE RACE. 
<P>
POLE SITTER  WOULD HAVE TROUBLES AS WELL.
<P>
THAT OPENS THE DOOR FOR  WHO HOLDS ON FOR THE WIN IN THE FERRARI, HIS FIRST THIS SEASON. AND THE 28TH GRAND PRIX VICTORY IN HIS CAREER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=138Easter Parade-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Easter Parade-I</H3><BR>
FINALLY. WE'VE ALL HEARD THAT SONG. "IN YOUR EASTER BONNET."
<P>
YES. IT'S THE EASTER PARADE.  ONE OF THE MOST CHERISHED HOLIDAY TRADITIONS.
<P>
FOX'S ELISE HART TAKES US TO THE SIDEWALKS OF NEW YORK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137Easter Parade-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Easter Parade-G</H3><BR>
YOU COULDN'T PREDICT WHAT WOULD LAND ON FIFTH AVENUE THIS 
<P>
EASTER. 
<P>
THERE WERE THE TRADITIONAL AND NOT SO-TRADITIONAL EASTER BONNETS. 
<P>
WITH ALL THE TRIMMINGS ON THEM. 
<P>
SOUND IN 1:16 IT'S A WATERING PAIL - RAINING ON FLOWERS. APRIL 
<P>
SHOWERS BRING MAY FLOWERS?? RIGHT 
<P>
SOUND IN    6:03 I'VE BEEN DOING THIS FOR 13 YEARS AND 
<P>
I'VE NEVER SEEN ANYTHING LIKE THIS BEFORE. SO COLORFUL AND LOOK AT 
<P>
THAT IT'S CHOREOGRAPHED. 
<P>
- NEVER SEEN THAT BEFORE. 
<P>
MUSIC NAT BREAK 
<P>
SOUND IN 15:37 IT'S NEWSPAPER, RIBBONS AND FLOWERS WE'RE STAYING AT 
<P>
THE YOUTH HOSTEL AND WE MADE IT CHEAP. 
<P>
STANDUP:  I'M FEELING A LITTLE LEFT OUT HERE - SEEMS I'M ONE OF THE 
<P>
ONLY ONES WITHOUT AN EASTER BONNET - BU MIKE HERE SAID I COULD BORROW 
<P>
HIS. OK NOW I'M READY -- WELL ALMOST - HA HA. 
<P>
22:32 I THINK IT'S A WONDERFUL TRADITION AND I THINK ITS THE MOST 
<P>
BEAUTIFUL DAY FOR IT. 
<P>
A DAY WHICH INCLUDED SOME THEME HATS -- PEOPLE PROUDLY DISPLAYED 
<P>
THEIR FAVORITE SINGING GROUPS AND, FAVORITE MOVIES. 
<P>
8:12 IT'S A TRIBUTE TO THE TITANIC THIS YEAR'S BIG MOVIE - I'M THE 
<P>
TITANIC HE'S THE ICEBERG. 
<P>
WHICH PROVES PEOPLE WILL SINK TO ALL LEVELS -- TO CATCH YOUR EYE ON 
<P>
EASTER. 
<P>
IN NY ELISE HART FOX NEWS 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
