KCBA FIRST AT TEN, Thursday, 4/9/98


                      Click here for a text-only version of this page
           TS1 (AL tornado)
                                        (disney dead animal)
           TOSS TO FOX
                                        (plane stuck)
           Morrow baby abuse
                                        (pow museum)
           Shannon jury trial
                                        (wynette memorial)
           Cordoba sentence
                                        Fox Biz/Mty parking
           SC Stalker arrest
                                        TZ/Toss to Sandhya
           TOSS TO JINAH
                                        Bump #4 (Sports)
           Methyl Bromide-IN
                                        Masters
           Methyl Bromide-GU
                                        Giants
           Methyl Bromide-TA
                                        NFL
           Mo Co health Dept
                                        Bibby
           Good News/lotto
                                        Warriors
           Bump 1(h.s. hostage) 
                                        Boxing
           bump 2(plane stuck) 
                                        Bump #5b (F5/D3)
           Across America
                                        weinermobile race
           (high sch hostage)
                                        Dog book recall
           (chained to bed)
                                        bye bye



    TS1 (AL tornado)


NEXT ON FOX NEWS FIRST AT TEN. 

THE DEATH TOLL FOLLOWING LAST NIGHT'S TORNADOS IN THE SOUTH.
IS APPROACHING 40. WE'LL HAVE THE VERY LATEST. 

A CONTROVERSIAL PESTICIDE. USED HERE ON THE CENTRAL COAST.
GETS SLAMMED BY A NEW NATIONAL REPORT. 

WE'LL HAVE LOCAL REACTION 

AND THREE LUCKY TICKET HOLDERS WILL SHARE THE SECOND
BIGGEST JACKPOT IN CALIFORNIA LOTTERY HISTORY. 

WE'LL TELL YOU WHERE THE TICKETS WERE PURCHASED. 

PLUS. SANDHYA PATEL TELLS US HOW THE EASTER WEEKEND IS
SHAPING UP. 

AND KEN ROTHHOUSE HAS BASEBALL. AND MASTERS HILITES. NEXT. 

Return to index of stories...


    TOSS TO FOX


GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN. 

THEY'RE TALLYING UP LOST LIVES AND LOST PROPERTY ACROSS
THREE SOUTHERN STATES AFTER LAST NIGHT'S DEADLY STORMS. 

THE DEATH TOLL IS UP TO THIRTY-EIGHT ACROSS ALABAMA, GEORGIA
AND MISSISSIPPI. 

FOX'S MIKE EMANUEL JOINS US NOW FROM CONCORD, ALABAMA WITH
THE LATEST. 

MIKE. 

Return to index of stories...


    Morrow baby abuse


THE MARINA WOMAN. CONVICTED IN THE NEAR FATAL BEATING OF HER
13 MONTH OLD DAUGHTER. WILL SPEND THE NEXT NINE YEARS BEHIND
BARS. 

32 YEAR OLD MARY ANN MORROW WAS CONVICTED YESTERDAY ON
TWO COUNTS OF CHILD ABUSE. 

THE TODDLER SUFFERED A SKULL FRACTURE AND INTERNAL
BLEEDING THAT CAUSED A STROKE. 

THE CHILD ALSO SUFFERED A LACERATED LIVER. AND NEEDED BLOOD
TRANSFUSIONS. 

Return to index of stories...


    Shannon jury trial


OPENING ARGUMENTS GET UNDERWAY TODAY IN THE 2ND TRIAL OF A
FORMER GREENFIELD COP ACCUSED OF BEATING TWO PRISONERS. 

MICHAEL SHANNON'S FIRST TRIAL ENDED WITH A HUNG JURY IN
FEBRUARY. 

IN COURT TODAY. BOTH SIDES RELATED DIFFERENT VERSIONS OF THE
SERIES OF EVENTS THAT TOOK PLACE THE NIGHT OF SEPTEMBER
14TH. OF LAST YEAR. 

THE PROSECUTION SAYS THAT SHANNON USED UNNECESSARY FORCE.
WITNESSED BY TWO KING CITY OFFICERS. 

THE DEFENSE PAINTS A DIFFERENT PICTURE. 

WE EXPECT THE FACTS TO SHOW THE CIRCUMSTANCES. AND THE TWO
ROOKIE OFFICERS. 

WORTHINGTON SAYS SHANNON HAD TO USE FORCE TO GET THE TWO
PRISONERS TO COMPLY. 

SHANNON FACES CHARGES ON SIX CONVICTIONS INCLUDING ASSAULT
BY AN OFFICER. INHUMANITY TO PRISONERS AND BATTERY. 

Return to index of stories...


    Cordoba sentence


A FORMER NORTH SALINAS VOLLEYBALL COACH IS HEADED TO PRISON
FOR THREE YEARS. FOR A SEXUAL ASSAULT WHILE ON PROBATION. 

29-YEAR-OLD STEVEN CORDOBA WAS WORKING AS A HOME DELIVERY
DRIVER WHEN HE ATTACKED A WOMAN IN HER SALINAS HOME. 

CORDOBA WAS ON PROBATION FOR FOUR COUNTS OF HAVING SEX
WITH UNDERAGE GIRLS. WHILE HE WAS A COACH AT NORTH SALINAS
HIGH. 

THE GIRLS WERE ALL STUDENTS AT THE HIGH SCHOOL. 

Return to index of stories...


    SC Stalker arrest


A BOULDER CREEK MAN IS ARRESTED FOR STALKING HIS EX-WIFE
AFTER POLICE RECEIVED A TIP FROM THE WOMAN'S FRIENDS. 

TODD BENEDICT WAS ARRESTED AFTER FRIENDS OF HIS EX-WIFE
TOLD POLICE THAT SHE WAS A VICTIM OF SPOUSAL ABUSE. AND THAT
BENEDICT WAS STALKING HER. 

SANTA CRUZ COUNTY SHERIFF DEPUTIES SEARCHED BENEDICT'S
HOUSE. WHERE THEY CONFISCATED SEMI-AUTOMATIC WEAPONS.
SHOTGUNS, RIFLES, THROWING STARS AND KNIVES.EVEN A
DERRINGER. 

BENEDICT WAS CHARGED WITH SPOUSAL BATTERY.ASSAULT WITH A
DEADLY WEAPON FOR REFUSING TO LET OFFICERS IN. AND
POSSESSION OF ILLEGAL WEAPONS AND DRUGS. 

HE'S BEING HELD ON 100-THOUSAND DOLLARS BAIL. 

Return to index of stories...


    TOSS TO JINAH


A DOUBLE WHAMMY AGAINST THE CONTROVERSIAL PESTICIDE
"METHYL BROMIDE" TODAY. 

A CALIFORNIA LAWMAKER INTRODUCES A GROUND-BREAKING BILL
THAT OUTLAWS METHYL BROMIDE USE WITHIN A THOUSAND FEET OF
HOMES AND SCHOOLS. 

THAT, ON THE HEELS OF A NEW STUDY THAT SHOWS SCHOOLS IN
MONTEREY AND SANTA CRUZ COUNTIES. ARE EXPOSED TO SOME OF
THE HIGHEST LEVELS OF THE PESTICIDE *ANYWHERE* IN THE STATE. 

FOR MORE ON THIS STORY. WE GO TO JINAH KIM, WHO JOINS US NOW
FROM THE NEWSDESK. 

JINAH!!! 

Return to index of stories...


    Methyl Bromide-IN


METHYL BROMIDE HAS *LONG* BEEN A HOT TOPIC HERE LOCALLY. BUT
TONIGHT, ANTI-PESTICIDE GROUPS ARE APPLAUDING THE BILL AND THE
STUDY AS THE FIRST OF THEIR KIND. 

AND LOCAL ACTIVISTS ARE JUMPING ON THIS OPPORTUNITY TO RENEW
THEIR PLEAS TO STOP USING THE CHEMICALS NEAR SCHOOLS AND
HOMES. 

Return to index of stories...


    Methyl Bromide-GU


ACCORDING TO A STUDY JUST RELEASED BY THE "ENVIRONMENTAL
WORKING GROUP,". PAJARO MIDDLE SCHOOL RANKS *THIRD* IN A LIST
OF CALIFORNIA SCHOOLS MOST EXPOSED TO METHYL BROMIDE. 

IN FACT, OUT OF 15 SCHOOLS CONSIDERED MOST *AT RISK
THROUGHOUT THE STATE,* *EIGHT* OF THEM ARE IN MONTEREY AND
SANTA CRUZ COUNTIES. 

WITH THOSE STATISTICS IN MIND, ASSEMBLYWOMAN LIZ FIGUEROA
ANNOUNCED A BILL TODAY THAT ASKS THE STATE TO INCREASE THE
BUFFER ZONE BETWEEN FARMS AND SCHOOLS FROM ITS CURRENT
100 FEET. TO 1,000 FEET. 

THE BILL ALSO APPLIES TO HOMES. 

AT A SEPARATE RALLY IN WATSONVILLE THIS AFTERNOON. LOCAL
ANTI-PESTICIDE GROUPS HAILED THE LEGISLATION. AND CALLED ON
THE COMMUNITY TO SUPPORT IT. 

Return to index of stories...


    Methyl Bromide-TA


DESPITE ALL THIS, OF COURSE. LOCAL FARMS DON'T *HAVE* TO DO
ANYTHING UNTIL THAT BILL ACTUALLY PASSES AND THE STATE TELLS
THEM TO INCREASE THE BUFFER ZONE. 

BUT RIGHT NOW, FARMERS HAVE THE STATE ON THEIR SIDE. BECAUSE
THE DEPARTMENT OF PESTICIDE REGULATION SAYS THE CURRENT
BUFFER ZONE IS MORE THAN SAFE. 

ALAN, BACK TO YOU. 

Return to index of stories...


    Mo Co health Dept


A RARE LOOK TODAY *BEHIND* THE SCENES AT THE MONTEREY
COUNTY HEALTH DEPARTMENT. 

LOCAL RESIDENTS WERE INVITED TO TOUR THE SALINAS FACILITY. AND
SEE THE CLINIC LABORATORIES. 

IT'S HERE TECHNICIANS TEST FOR EVERYTHING FROM S-T-D'S AND AIDS.
TO NITRATE CONTAMINATION IN THE WATER. 

WE ALSO TEST RECREATIONAL WATERS, 60 TIMES A MONTH, COASTAL
WATERS, LAKES, MAKE SURE SAFE FOR SWIMMING, SCUBA AND
SURFING. 

THE HEALTH DEPARTMENT SAYS THE GOAL OF TODAY'S OPEN HOUSE
WAS TO DEBUNK THE MYTH THAT IT'S SERVICES ARE ONLY FOR LOW
INCOME RESIDENTS. 

Return to index of stories...


    Good News/lotto


GOOD NEWS FOR THE LUCKY OWNERS OF THE THREE WINNING
LOTTERY TICKETS. IN LAST NIGHT'S SUPER LOTTO DRAWING. 

THREE TICKETS MATCHED ALL SIX NUMBERS LAST NIGHT. WINNING THE
102 MILLION-DOLLAR JACKPOT. 

EACH TICKET IS WORTH AN ESTIMATED 34 MILLION. 

LOTTERY OFFICIALS SAY THE TICKETS WERE BOUGHT IN
VENTURA.SANTA CLARITA AND BAKERSFIELD. 

BEFORE THE DRAWING. LOTTERY COMPUTERS SHUT DOWN DURING A
TICKET-BUYING FRENZY WHEN ABOUT 100-THOUSAND TICKETS A
MINUTE WERE BEING SOLD. 

Return to index of stories...


    Bump 1(h.s. hostage) 


COMING UP ON K-C-B-A FOX NEWS FIRST AT TEN. 

ANOTHER TENSE SITUATION AT A HIGH SCHOOL INVOLVING A GROUP OF
STUDENTS AND GUNS. 

Return to index of stories...


    bump 2(plane stuck) 


AND THE PILOT OF A SMALL PLANE FINDS HIMSELF IN AN UNUSUALLY
PRECARIOUS SITUATION TODAY. WE'LL TELL YOU HOW IT HAPPENED.
RIGHT AFTER THIS. 

Return to index of stories...


    Across America


A STANDOFF BETWEEN A STUDENT WHO ALLEGEDLY PULLED A GUN
ON A PRINCIPAL. AND THEN HOLED UP INSIDE THE SCHOOL WITH FOUR
OTHER STUDENTS. IS NOW OVER. 

THAT STORY FROM POCATELLO, IDAHO TOPS OUR LOOK AT NEWS
ACROSS AMERICA. 

Return to index of stories...


    (high sch hostage)


IT HAPPENED AT A SCHOOL FOR TROUBLED KIDS. 

POLICE SAY A THE 14-YEAR-OLD BOY WAS THE RING LEADER. 

AFTER FIVE HOURS. THE BOY AND FOUR OTHER STUDENTS WALKED
OUT. 

EARLIER THE STUDENTS HAD TRADED TWO HANDGUNS 

FOR PIZZA, CIGARETTES AND SODA. 

NO ONE WAS HURT. 

STILL NO WORD ON A MOTIVE FOR THE ATTACK. 

Return to index of stories...


    (chained to bed)


A FLORIDA COUPLE IS FACING FALSE IMPRISONMENT CHARGES FOR
ALLEGEDLY CHAINING THEIR EMOTIONALLY DISTURBED SON TO HIS
BED. 

18 YEAR-OLD NICHOLAS PEACE TOLD POLICE HIS MOTHER AND FATHER
PUT CHAINS ON HIM. BOLTED HIS DOOR. AND COVERED HIS BEDROOM
WINDOW WITH WOOD. 

THE COUPLE SAYS THEY DID SO TO STOP HIM FROM SNEAKING OUT AT
NIGHT. 

Return to index of stories...


    (disney dead animal)


FEDERAL INVESTIGATORS ARE LAUNCHING A NEW INVESTIGATION INTO
COMPLAINTS ABOUT ANIMAL CARE AT DISNEY'S SOON-TO-BE-OPEN
ANIMAL KINGDOM IN ORLANDO, FLORIDA. 

THE INVESTIGATION IS IN RESPONSE TO THE RECENT DEATHS OF
SEVERAL ANIMALS AT THE PARK. 

THE U-S DEPARTMENT OF AGRICULTURE HAS ALREADY REVIEWED
MOST OF THE DEATHS.BUT ARE LOOKING AGAIN AFTER AN ANONYMOUS
CALL. 

DISNEY SAYS THEY WELCOME THE NEW INSPECTIONS. 

Return to index of stories...


    (plane stuck)


A SEATTLE PILOT'S WORLD WAS LITERALLY TURNED UPSIDE DOWN
TODAY. WHEN HE TRIED TO ABORT HIS LANDING ATTEMPT. 

47-YEAR-OLD MIKE WARREN'S CESSNA VEERED OFF THE RUNWAY AT
BOEING FIELD. SENDING HIM STRAIGHT INTO SOME POWER LINES. 

ONE OF THE PLANE'S WHEELS GOT TANGLED. CAUSING THE PLANE TO
FLIP UPSIDE DOWN. 60 FEET ABOVE THE GROUND. 

WARREN WAS RESCUED ABOUT FOUR HOURS LATER. WITH NO MAJOR
INJURIES. 

Return to index of stories...


    (pow museum)


MORE THAN 3-THOUSAND PEOPLE WERE ON HAND AT THE OPENING OF
A MUSEUM HONORING AMERICAN PRISONERS OF WAR TODAY. 

THE NEW NATIONAL P-O-W MUSEUM OPENED UP IN ANDERSONVILLE,
GEORGIA.SITE OF A NOTORIOUS CIVIL WAR PRISON CAMP. 

THE 56-MILLION-DOLLAR MUSEUM PAYS TRIBUTE TO ALL AMERICAN
P-O-W'S FROM THE REVOLUTIONARY WAR TO THE GULF WAR. 

Return to index of stories...


    (wynette memorial)


THE COUNTRY MUSIC INDUSTRY SAID A FINAL FAREWELLL TO ITS "FIRST
LADY." 

A PRIVATE FUNERAL FOR TAMMY WYNETTE WAS HELD AT JUDSON
BAPTIST CHURCH. IN NASHILLE THIS AFTERNOON. 

THE EMOTIONAL SERVICE INCLUDED PERFORMANCES BY DOLLY
PARTON, RANDY TRAVIS AND TRISHA YEARWOOD. 

A PUBLIC MEMORIAL SERVICE WAS HELD AT RYMAN AUDITORIUM.
FORMER SITE OF THE GRAND OLE OPRY. 

THE COUNTRY MUSIC LEGEND DIED FROM A BLOOD CLOT IN HER LUNGS
MONDAY. 

SHE WAS 55. 

Return to index of stories...


    Fox Biz/Mty parking


A PARKING SHORTAGE IN ONE CENTRAL COAST CITY IS *DRIVING* OUT
CUSTOMERS.AND CITY OFFICIALS HAVE A PLAN TO CHANGE THAT. 

DETAILS IN TONIGHT'S FOX BUSINESS REPORT. 

THE CITY OF MONTEREY IS EXPERIMENTING WITH *PERMIT ONLY
PARKING* FOR EMPLOYEES OF BUSINESSES IN NEW MONTEREY. 

THE PARKING AREAS WILL EXTEND FOR ONE BLOCK IN EACH
DIRECTION FROM LIGHTHOUSE AVENUE BETWEEN REESIDE AND DAVID
AVENUES. 

THE NEW MONTEREY BUSINESS ASSOCIATION WANTS WORKERS TO
PAY FIVE DOLLARS A MONTH FOR PARKING. 

THE FINAL PRICE WILL BE DISCUSSED BY THE CITY COUNCIL ON MAY
5-TH. 

Return to index of stories...


    TZ/Toss to Sandhya


COMING UP A LITTLE LATER ON FOX NEWS. A HOT DOG GOES UP
AGAINST CHOCOLATE. WE'LL TELL YOU CAME OUT ON TOP. 

BUT FIRST. 

SANDHYA WILL HOPEFULLY HAVE A GOOD WEEKEND FORECAST FOR
US. 

SANDHYA. 

Return to index of stories...


    Bump #4 (Sports)


COMING UP, A HUGE DAY IN SPORTS. 

AUGUSTA NATIONAL SHOWS ITS TEETH AT THE FIRST ROUND OF THE
MASTERS, WE'LL HAVE A FULL REPORT. 

THE GIANTS, WARRIORS AND SHARKS ARE IN ACTION. 

AN NFL GREAT SAYS SO LONG, WHILE A FUTURE NBA STAR SAYS SHOW
ME THE MONEY. 

AND CLOSER TO HOME, ITS THE RIOT AT THE HYATT, PRO BOXING
HILITES ARE STRAIGHT AHEAD. 

Return to index of stories...


    Masters


A GUSTY, AUGUSTA MAKES FOR A LONG DAY AT THE FIRST ROUND OF
THE MASTERS. 

AFTER TIGER WOODS' RECORD SETTING PERFORMANCE LAST YEAR,
THE CRIES WENT OUT FOR THE MEN OF THE MASTERS TO TOUGHEN UP
THE COURSE. 

WELL THAT JOB WAS TAKEN CARE OF BY MOTHER NATURE, AND HER
30-MILE PER HOUR WINDS. 

Return to index of stories...


    Giants


IN A BALLGAME SEEN HERE ON KCBA, THE GIANTS LOOK TO WIN THE
RUBBER MATCH OF THEIR 3-GAME SET WITH THE ASTROS. 

Return to index of stories...


    NFL


TO FOOTBALL NEWS, AND A RUNNING BACK WHO SPENT 16-YEARS
DODGING DEFENDERS, WAS FINALLY CAUGHT, BY FATHER TIME. 

AT AGE 38, AND AFTER 16-YEARS IN THE NFL, A TEARFUL MARCUS
ALLEN ANNOUNCED HIS RETIREMENT FROM FOOTBALL. 

HIS 123 RUSHING TOUCHDOWNS IS AN NFL RECORD. ALLEN WAS THE
1982 HEISMAN TROPHY WINNER AT U.S.C. HE WAS THE 1984 SUPER
BOWL M.V.P. WITH THE RAIDERS. 

HE JOINED THE CHIEFS IN '93, WHERE HE BECAME THE FIRST BACK TO
GAIN BOTH 10-THOUSAND YARDS RUSHING AND 5-THOUSAND YARDS
RECEIVING. 

ALLEN WILL NOW BECOME AN ANALYST THIS FALL FOR CBS. 

Return to index of stories...


    Bibby


SO ONE PLAYER IS OUT, AND ANOTHER IS COMING IN, TO THE NBA. 

MIKE BIBBY ANNOUNCES HE WILL FORGO HIS FINAL 2-SEASONS AT
ARIZONA TO ENTER THE NBA DRAFT. BIBBY LED ARIZONA TO A
NATIONAL TITLE THE YEAR BEFORE LAST. 

HE WAS A 1ST TEAM ALL-AMERICAN THIS YEAR, AND THE PAC-10
PLAYER OF THE YEAR. 

IF THE WARRIORS CAN HANG ON TO THEIR 4TH PICK IN THE DRAFT,
THERE IS NO DOUBT THEY WOULD BE INTERESTED IN THIS POINT
GUARD. 

Return to index of stories...


    Warriors


AND SPEAKING OF THE WARRIORS, THEY ARE IN ACTION TONITE, VS. A
HOUSTON ROCKETS TEAM TRYING TO GET A BETTER SEEDING FOR THE
UPCOMING PLAYOFFS. 

Return to index of stories...


    Boxing


AND LAST, BUT CERTAINLY NOT LEAST, PRO BOXING RETURNS TO THE
CENTRAL COAST. 

ITS THE 3RD EDITION OF THE RIOT AT THE HYATT. 

THE CARD HAD TO BE CUT FROM 6-FIGHTS DOWN TO 5, BECAUSE JUAN
RIVERA OF LOS ANGELES WAS A SCRATCH, SO SALINAS' JESUS VEGA
DOES NOT GET TO STEP INTO THE RING TONITE. 

Return to index of stories...


    Bump #5b (F5/D3)


COMING UP NEXT. 

THE OSCAR MEYER WEINERMOBILE IS LOOKING TO MAKE A NAME FOR
ITSELF IN THE WORLD OF DRAG RACING. 

WE'LL EXPLAIN. RIGHT AFTER THIS. 

Return to index of stories...


    weinermobile race


HOT DOGS AND MILK CHOCOLATE.WENT HEAD-TO-HEAD IN A DRAG
RACE AT THE TEXAS MOTORPLEX NEAR DALLAS. 

THE VETERAN OSCAR-MAYER WIENERMOBILE TOOK ON THE NEW
CONTENDER HERSHEY CHOCOLATE KISSMOBILE. 

THE WIENER STEAMED OUT OF THE GATE FIRST. LOOKING LIKE IT
WOULD MELT AWAY THE COMPETITION. 

BUT THE KISSMOBILE GOT SWEET REVENGE FINISHING IN A TIE. 

Return to index of stories...


    Dog book recall


FINALLY TONIGHT. 

THE AMERICAN KENNEL CLUB FINDS ITSELF IN THE DOG HOUSE OVER
ITS LATEST EDITION OF "THE COMPLETE DOG BOOK". 

IN FACT, IT'S RECALLING THE EDITION. 

THAT'S BECAUSE PET OWNERS ARE BARKING ABOUT THEIR PETS
BEING DESCRIBED AS UNSUITABLE FOR CHILDREN. 

AMONG THOSE LISTED. 

CHIHUAHUAS, DACHSHUNDS, LHASA APSOS, PEKINGESE, TOY
POODLES, AND CHOW CHOWS. 

A MORE PEOPLE-FRIENDLY VERSION OF THE DOG BOOK WILL HIT
STORE SHELVES THIS SUMMER. 

Return to index of stories...


    bye bye


THAT'S GOING TO DO IT FOR FOX NEWS FIRST AT TEN. 

TUNE IN AGAIN TOMORROW NIGHT AT TEN. 

UNTIL THEN, TAKE CARE. 

Return to index of stories...

                              Copyright © 1998
  All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this
                                  report.
  Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for
  broadcast or publication or redistribution directly or indirectly in any medium. Neither these AP materials nor any
 portion thereof may be stored in a computer except for personal and non-commercial use. AP will not be held liable for
 any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for
                      any damages arising from any of the foregoing.
