<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA Fox News at Ten (g/Sun), Sunday, 4/5/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA Fox News at Ten (g/Sun), Sunday, 4/5/98</H2></CENTER></TD>
</TABLE>
<FONT SIZE=-2><A HREF=x040503.htm>Click here for a text-only version of this page</A></FONT><BR>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#114Sleep Deprivation-I>Sleep Deprivation-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Japan Bridge>Japan Bridge</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108Sleep Deprivation-G>Sleep Deprivation-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#124Canada Floods>Canada Floods</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Sleep Deprivation-T>Sleep Deprivation-T</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#39Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#123Baskets/Bikers>Baskets/Bikers</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#41A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#122Military Re-enact>Military Re-enact</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Warriors>Warriors</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Good Old Days>Good Old Days</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Golf>Golf</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Everest Clean-up-I>Everest Clean-up-I</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#128Racing>Racing</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Everest Clean-up-G>Everest Clean-up-G</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Tennis>Tennis</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#21Mecca/Haj>Mecca/Haj</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Clash>Clash</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#24Ukraine Folo>Ukraine Folo</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115Taco-Bell Dog>Taco-Bell Dog</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#22Australia Crash>Australia Crash</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=114Sleep Deprivation-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sleep Deprivation-I</H3><BR>
FEW PEOPLE KNOW THIS. BUT ACCORDING TO A REPORT IN THE NEW ENGLAND JOURNAL OF MEDICINE. THE NUMBER OF TRAFFIC ACCIDENTS ACTUALLY GOES *UP* EVERY TIME WE LOSE AN HOUR OF SLEEP IN THE SPRING. AND *DECREASES* IN THE FALL. WHEN WE CHANGE OUR CLOCKS BACK AGAIN.
<P>
SO DAYLIGHT SAVINGS TIME ISN'T SOMETHING TO BE TAKEN LIGHTLY.
<P>
AND THOUGH WE DIDN'T RUN INTO ANYONE WHO GOT INTO A CAR ACCIDENT TODAY. IT WAS PRETTY CLEAR A LOT OF PEOPLE FELT THAT ONE HOUR LOSS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108Sleep Deprivation-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sleep Deprivation-G</H3><BR>
IT HAPPENS EVERY FALL.
<P>
AND IT HAPPENS EVERY SPRING.
<P>
SO WHY IS IT THAT WE STILL CAN'T GET THE HANG OF IT?
<P>
AFTER ALL. WE'RE ONLY LOSING ONE HOUR.   AND ON A MORNING WHEN MOST OF US DON'T HAVE TO GET UP TO GO TO WORK.
<P>
BUT IT STILL MANAGES TO THROW US INTO CONFUSION.
<P>
SLEEP EXPERTS CAN'T DENY THAT EVEN JUST *ONE* LESS HOUR OF ZZ'S IS ENOUGH TO TIP OUR BODY CLOCKS OFF BALANCE.
<P>
AND WHERE IT CAN HAVE THE MOST DETRIMENTAL EFFECTS IS ON THE ROADS. WHERE ON A DAY LIKE THIS. YOU FIND MORE THAN THE *USUAL* NUMBER OF SLEEPY DRIVERS BEHIND THE WHEEL.
<P>
BUT SLEEP SPECIALISTS SAY ONE HOUR'S LOSS OF SLEEP IS JUST NOT A SIGNIFICANT CHANGE FOR MOST PEOPLE. AND WITHIN 24 HOURS, OUR BODY CLOCKS SHOULD HAVE FULLY ADAPTED.
<P>
BUT TRY TELLING THAT TO REGULAR FOLKS WHO SWEAR. THE EFFECTS LAST MUCH LONGER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Sleep Deprivation-T>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sleep Deprivation-T</H3><BR>
DOCTOR KANAK GAVE US A LITTLE TIP ABOUT ADJUSTING BETTER TO DAYLIGHT SAVINGS TIME.
<P>
WHEN WE LOSE AN HOUR LIKE THIS. HE SAYS IT USUALLY DOESN'T HELP TO SLEEP *EARLIER* THAT NIGHT.
<P>
THE BODY ADAPTS BETTER WHEN YOU GO TO BED AT THE REGULAR TIME AND JUST WAKE UP AN HOUR LATER THE NEXT MORNING.
<P>
CHERI, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=123Baskets/Bikers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Baskets/Bikers</H3><BR>
A LOCAL CHURCH DEVISTATED BY THIS YEAR'S FLOODS GETS AN EARLY EASTER GIFT TODAY.
<P>
VALLEY CHURCHES UNITED IN BEN LOMOND HELPS FAMILIES IN NEED EVERY EASTER BY HANDING OUT BASKETS.
<P>
BUT THE CHURCH LOST ABOUT 60-THOUSAND DOLLARS WORTH OF EASTER SUPPLIES THIS YEAR DURING THE STORMS.
<P>
THAT'S WHY HUNDREDS OF BIKERS HOPPED ON THEIR HARLEYS.AND PITCHED IN TO HELP THE CHURCH.
<P>
"THEY ARE GOING TO BE A BIG HELP.BECAUSE THEY'RE BRINGING IN CASH DONATIONS AS WELL AS HELP WITH FOOD VOUCHERS TO PUT FRESH FOOD ON THE TABLE FOR PEOPLE."
<P>
THIS IS THE ELEVENTH YEAR THE SANTA CRUZ HOG RIDERS HAVE HELPED THOSE IN NEED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=122Military Re-enact>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Military Re-enact</H3><BR>
MARCHING, DRILLING, AND MUSKET SHOOTING ARE ACTIVITIES YOU DON'T NORMALLY SEE IN MONTEREY.
<P>
BUT A LOCAL HISTORY TEACHER GOT TOGETHER WITH SEVERAL LIVING-HISTORY RE-ENACTORS.  TO PORTRAY THE FIRST NEW YORK VOLUNTEER REGIMENT OF 18-47.
<P>
THE GROUP PERFORMED AT THE CUSTOM HOUSE. NEAR FISHERMAN'S WHARF. JUST AS THEY DID 150-YEARS AGO.
<P>
"WE ARE THE 1ST NEW YORK VOLUNTEER REGIMENT AND WE ARE RE-ENACTING THE TROOPS THAT WERE SENT HERE IN 1847 TO GUARD THE COAST AGAINST THE ENGLISH AND THE FRENCH."
<P>
THE ORIGINAL MEMBERS WERE COLONISTS. WHO DECIDED TO SETTLE IN MONTEREY AND THROUGHOUT CALIFORNIA.
<P>
YOU CAN ALSO CATCH THE PERFORMANCE IN JULY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Good Old Days>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Good Old Days</H3><BR>
IT WAS ANOTHER  "GOOD OLD DAY" IN PACIFIC GROVE. AS THE ANNUAL CELEBRATION CAME TO A CLOSE.
<P>
TODAY'S ACTIVITIES INCLUDED THE FIRE-FIGHTING MUSTER. WHERE LOCAL FIRE FIGHTERS. AND CELEBRITIES.  COMPETED IN A HOSE-CART RACE.  AND A BUCKET BRIGADE*.
<P>
GOOD FOOD. ARTS AND CRAFTS. MUSIC. AND DISPLAY BOOTHS GAVE VISITORS. AND LOCALS. THE CHANCE TO ENJOY THE ATMOSPHERE OF "BUTTEREFLY TOWN U-S-A."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Everest Clean-up-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Everest Clean-up-I</H3><BR>
IT'S WHERE MANKIND GOES TO CONQUER NATURE. THE HIGHEST PLACE IN THE WORLD. MOUNT EVEREST. 
<P>
BUT IN THE ATTEMPT TO TAKE ON THE NATURAL WONDER.  PEOPLE HAVE LEFT MORE THAN FOOTPRINTS.THEY'VE LEFT TRASH. 
<P>
LAURIE DUE TELLS US HOW SOME CLIMBERS FROM THE BAY AREA ARE CLEANING IT UP.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Everest Clean-up-G>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Everest Clean-up-G</H3><BR>
YET AGAIN, A TEAM OF AMERICAN HIKERS PLAN TO TREK UP MOUNT EVEREST, THEIR GOAL 
<P>
IS TO REACH THE SUMMIT, BUT 
<P>
ALSO TO RETRIEVE WHAT OTHERS HAVE LEFT BEHIND.   
<P>
----------------------------- 
<P>
SOT INQ: 12:50 THE ENVIRONMENTAL EXPEDITION. 
<P>
OUT: 12:59 LAST 40-45 YEARS." 
<P>
------------------------------ 
<P>
THE 15 MEMBER TEAM, WHICH LEFT SATURDAY, IS LED BY CALIFORNIA PHYSICIAN MARK 
<P>
COLE.   
<P>
THE MISSION SHOULD TAKE ABOUT TWO MONTHS AND WON'T BE EASY. 
<P>
-------------------------------- 
<P>
SOT INQ: 14:56 12 POUND BOTTLES OF OXYGEN. 
<P>
15:19 UP ON EVEREST." 
<P>
--------------------------------- 
<P>
COLE SAYS MANY CLIMBERS HAVE BECOME ENVIRONMENTALLY AWARE, CLEANING UP 
<P>
AFTER THEIR TREK. THE NEPALESE GOVERNMENT HAS THREATENED TO FINE CLIMBERS WHO 
<P>
FAIL TO TAKE THEIR GARBAGE.   
<P>
SUCH ACTIONS HAVE HELPED REDUCE TRASH AT THE EVEREST BASE CAMP.BUT AT HIGHER 
<P>
ELEVATIONS, THE WEIGHT OF GARBAGE ONLY ADDS TO OTHER PROBLEMS, LIKE FATIGUE. 
<P>
----------------------------------- 
<P>
SOT INQ: 13:39 PEOPLE GET SO TIRED. 
<P>
OUT: 13:47 SAFELY OFF THE MOUNTAIN." 
<P>
------------------------------------- 
<P>
THE OXYGEN BOTTLES WILL BE LUGGED OFF THE MOUNTAIN AND EVENTUALLY SHIPPED TO 
<P>
SAN FRANCISCO, WHERE THE GROUP HOPES TO SELL THEM AS EVEREST MOMENTOS FOR 156 
<P>
DOLLARS EACH. 
<P>
THAT, EXPEDITION LEADERS SAY WILL DO LITTLE TO OFFSET TO 25-THOUSAND DOLLAR PER 
<P>
PERSON COST OF THE TRIP.BUT THEY HOPE THEIR EFFORT WILL SEND A MESSAGE: 
<P>
SWEEPING THE ROOFTOP OF THE WORLD SHOULD BE EVERY INDIVIDUAL CLIMBERS 
<P>
RESPONSIBILTY. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=21Mecca/Haj>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mecca/Haj</H3><BR>
IT'S ALSO "HOLY WEEK" FOR THE ISLAMIC FAITH.
<P>
TWO-MILLION MUSLIMS PARTICIPATE IN ANCIENT RELIGIOUS RITUALS. 
<P>
IT'S CALLED THE HAJ.THE JOURNEY TO THE GRAND MOSSQUE IN THE SAUDI ARABIAN CITY OF MECCA. 
<P>
THE PILGRIMS HAVE COMPLETED THE FIRST STEP. CIRCLING THE CUBE-SHAPED SHRINE CALLED THE "KAABA".
<P>
TOMORROW. THEY HEAD TO MOUNT ARAFAT. WHERE THE PROPHET "MOHAMMED" GAVE HIS LAST SERMON FOURTEEN CENTURIES AGO. 
<P>
THE HAJ ENDS TUESDAY WITH THE SLAUGHTER OF SHEEP AND OTHER ANIMALS. WHOSE MEAT IS DONATED TO THE POOR. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=24Ukraine Folo>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ukraine Folo</H3><BR>
THE DEATH TOLL CONTINUES TO CLIMB FROM YESTERDAY'S EXPLOSION AT A COAL MINE IN UKRAINE. 
<P>
63 PEOPLE ARE DEAD.AND 43 INJURED.
<P>
IT'S ONE OF UKRAINE'S WORST MINING DISASTERS.
<P>
6-HUNDRED MINERS WERE WORKING BELOW GROUND WHEN A MIXTURE OF METHANE GAS AND COAL DUST EXPLODED.  
<P>
SOME OF THE WORKERS DIED IN THE BLAST.OTHERS SUFFOCATED.
<P>
OFFICIALS SAY THEY'LL INVESTIGATE THE CAUSE OF THE ACCIDENT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=22Australia Crash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Australia Crash</H3><BR>
AN AUSTRALIAN PILOT PULLS OFF A DARING CRASH LANDING.
<P>
THE CESSNA TWO-TEN WAS CARRYING AN AUSTRALIAN FAMILY. WHEN SOMETHING WENT WRONG. AND THE PLANE'S WHEELS FAILED TO LOWER.
<P>
TO MAKE MATTERS WORSE. FUEL WAS RUNNING LOW. 
<P>
THE PILOT CALLED GROUND CONTROL AND WAS TOLD HE HAD NO CHOICE BUT TO CRASH LAND. 
<P>
EMERGENCY VEHICLES STOOD BY AS THE PLANE HIT A GRASSY STRIP NEAR THE RUNWAY.THEN FINALLY SKIDDED TO A STOP. 
<P>
LUCKILY, NO ONE WAS HURT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Japan Bridge>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Japan Bridge</H3><BR>
DRIVING AROUND JAPAN HAS NOW BECOME EASIER. AND MORE BREATHTAKING. 
<P>
A NEW BRIDGE OPENED CONNECTING THE CITY OF KO-BAY.  AND AHWA-GEE ISLAND. 
<P>
IT'S THE LARGEST SUSPENSION BRIDGE IN THE WORLD.MORE THAN A MILE LONG. 
<P>
ITS DEEP FOUNDATION ENABLES TOWERS TO WITHSTAND 180 MILE PER HOUR WINDS. 
<P>
BUT THIS ENGINEERING MARVEL CARRIES A BIG TICKET PRICE. 
<P>
TOTAL CONSTRUCTION COST: 3.7 BILLION DOLLARS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=124Canada Floods>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Canada Floods</H3><BR>
IN CANADA. AN EARLY SPRING THAW CAUSES RIVERS TO JUMP THEIR BANKS.TURNING STREETS INTO STREAMS. 
<P>
PEOPLE WHO LIVE IN LOW-LYING AREAS HAVE HEADED FOR HIGHER AND  DRIER GROUND. 
<P>
THE  ARMY IS TRYING TO PREVENT FURTHER DESTRUCTION BY LINING SANDBAGS ALONG THE BANKS OF SWOLLEN RIVERS. 
<P>
TWO TEENAGERS  DROWNED IN THE HIGH WATERS FROM THE FLOODING. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=39Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
THE GIANTS BRING OUT THE BROOMS IN ARIZONA TONIGHT LOOKING TO CLOSE OUT THEIR SEASON OPENING 6-GAME ROAD TRIP WITH A 5-1 RECORD.    
<P>
A BEAUTIFUL DAY AT THE BOB. THE ROOF OPEN AND READY FOR BASEBALL.
<P>
--------
<P>
GETS THINGS GOING FOR THE GIANTS WITH THIS 1ST INNING HOMER OFF. GIANTS UP 1-ZIP.
<P>
---------
<P>
ON THE MOUND FOR SAN FRANCISCO LOOKING FOR HIS 1ST VICTORY. STILL IN THE 1ST. HE GETS  TO POP ONE TO RIGHT. BUT THIS ONE HAS EYES. FALLING IN BETWEEN KENT AND JAVIER. THE D-BACK SCORE 3 IN THE 1ST. 
<P>
--------
<P>
IT'S STILL 3-1 IN THE 6TH WHEN MILLER STRIKES AGAIN. HIS 2ND HOMER OF THE GAME. BUT IT'S ANOTHER SOLO SHOT. CUTTING THE LEAD TO 3-2.
<P>
--------
<P>
THAT'S AS CLOSE AS THEY WOULD GET AS  FLIES OUT TO END THE GAME. THE D-BACKS GET THEIR 1ST WIN. FINAL. 3-2. ARIZONA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=41A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
AFTER WINNING THEIR 1ST GAME OF THE SEASON. THE A'S LOOK TO MAKE IT TWO IN A ROW AGAINST THE BRONX BOMBERS. WHO COME INTO SUNDAY'S GAME AS ONE OF 4-WINLESS TEAMS IN THE MAJORS.    
<P>
A'S TRAIL 1-ZIP IN THE 1ST WHEN  DELIVERS THE BASEHIT UP THE MIDDLE. IT SCORES  GAME TIED AT ONE.
<P>
---------
<P>
OAKLAND UP 4-3 IN THE 8TH. WHEN  GIVES UP THE GOPHER BALL TO  A 2-RUN HOMER. YANKS GO UP 5-4.
<P>
---------
<P>
IT'S 7-5 IN THE 9TH. WHEN  GETS IN ON THE ACTION. A 2-RUN HOMER OFF.HIS 1ST OF THE SEASON THAT TIES THE GAME AT 7. 
<P>
---------
<P>
BUT THE YANKS LEAD 8-7 IN THE 10TH. FORMER ATHLETIC  ON THIRD.  DELIVERS THE RBI SINGLE OFF  AND THE YANKEES GO ON TO WIN.
<P>
FINAL. 9-7. IT'S THE YANKS FIRST WIN OF THE SEASON.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Warriors>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Warriors</H3><BR>
HAVING LOST TO SAN ANTONIO IN OVERTIME SATURDAY. THE WARRIORS DROPED TO 16-AND-59 A MERE 40 AND A HALF GAMES OUT OF 1ST PLACE.
<P>
THEY'LL FINISH UP WITH 6 OF THEIR FINAL 7-GAMES AT HOME. BEGINING WITH UTAH ON TUESDAY.    
<P>
MICHAEL JORDAN AND THE BULLS IN HOUSTON. SIR CHARLES WITH A LITTLE BUMP FOR HIS AIRNESS.
<P>
----------
<P>
THE BULLS PLAYING THEIR TRADEMARK SMOTHERING DEFENSE.  WITH THE BLOCK AND THEN THE JAM ON THE OTHER END. PIPPEN WITH 20 POINTS AND FIVE BLOCKED SHOTS.
<P>
---------
<P>
ANSWERS AT THE OTHER END WITH THE THREE BALL. DREXLER ALSO SCORES 20.
<P>
--------
<P>
BUT HERE COMES JORDAN. RIGHT BACK IN DREXLERS FACE. JORDAN LIGHTING UP THE ROCKETS IN THE SUMMIT WITH 40 POINTS AS THE BULLS WIN THEIR 12TH STRAIGHT. FINAL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Golf>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf</H3><BR>
ON THE LPGA TOUR.DONNA ANDREWS BIRDIED 3 OF THE FINAL FIVE HOLES TO WIN THE LONGS DRUGS CHALLANGE. IT'S HER 6TH CAREER VICTORY.    
<P>
IS MAKING WINNING SOMEWHAT OF A TRADITION. AT THE TRADITION. THE GOOD DOCTOR REPEATING AS CHAMPION TODAY IN THE FIRST SENIOR MAJOR OF THE YEAR. MORGAN WITH A FINAL ROUND 70 TO ERASE A 2-SHOT DEFECIT AND BEAT  BY 2-SHOTS.
<P>
----------
<P>
THE RED HOT MORGAN HAS NOW WON 5-TIMES IN HIS LAST 10 STARTS.
<P>
AT THE FREEPORT-MCDERMOTT. 24 YEAR OLD  CONTINUED HIS FINE PLAY WITH A FINAL ROUND 69 TO WIN FOR THE 1ST TIME IN THE U-S. THE YOUNG BRIT FINISHES  WITH 4-ROUNDS IN THE 60'S AND WINS BY 3-SHOTS OVER ROOKIE STEVE FLESH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=128Racing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Racing</H3><BR>
TO RACING NOW. TOUGH DAY IN LONG BEACH FOR. WATCH AS HIS LEFT FRONT TIRE JUST SHREDS. IT WOULD BE THE END OF THE DAY FOR ANDRETTI.
<P>
----------
<P>
WOULD COME BACK FROM A LAP DOWN TO WIN THE GRAND PRIX OF LONG BEACH. IT'S THE FIRST VICTORY OF THE SEASON FOR ZANARDI AND THE 9TH OF HIS CAREER. TEAMMATE  FINISHES IN 8TH.
<P>
TO THE OVAL NOW. WHERE  WOULD SPEED TO VICTORY AT THE TEXAS 500. A RACE THAT WAS MARED BY A 10 CAR WRECK ON THE 2ND LAP.
<P>
---------
<P>
IT'S THE 24TH WIN OF MARTIN'S CAREER AND SECOND THIS SEASON.
<P>
HE POCKETS NEARLY 357-THOUSAND DOLLARS FOR THE VICTORY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Tennis>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tennis</H3><BR>
IN DAVIS CUP ACTION. THE U-S DEFEATED RUSSIA IN DOUBLES TO TAKE A 2-1 LEAD IN THE BEST OF FIVE SERIES.
<P>
MONDAY ANDRE AGASSI WILL PLAY YEVGENY KAFELNIKOV AND JIM COURIER WILL FACE MARAT SAFEEN.THE AMERICANS NEEDING JUST ONE MORE VICTORY TO ADVANCE TO THE 2ND ROUND.
<P>
MEANTIME. 49ER LINEMAN  TRADING IN HIS PADS FOR A TENNIS RACQUET AT THE CHAMISAL TENNIS CLUB.      DALMAN PLAYING AN EXHIBITION ALONG WITH TEAMMATE FRANK POLLACK. AS PART OF THE ELITE 16.
<P>
IN THE FINALS. TOP SEED PAT CROW WOULD HAVE LITTLE TROUBLE WITH HEATH MONTGOMERY. CROW WINNING THE 1ST SET 6-2.
<P>
-----------------
<P>
HE WOULD TAKE THE MATCH IN STRAIGHT SETS.  6-4 IN THE 2ND. AND THE LONG BEACH NATIVE DEFENDS HIS TITLE AT THE 8TH ANNUAL ELITE 16.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Clash>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clash</H3><BR>
FINALLY. TO SOCCER. THE CLASH HOSTING THE DALLAS BURN AT STANFORD STADIUM.
<P>
---------     
<P>
CLASH TRAIL 2-1 IN THE 2ND HALF. WHEN  RIPS A SHOT FROM 25 YARDS OUT. AND IT GOES. THAT TIES THE GAME AT 2 IN THE 83RD MINUTE.
<P>
---------
<P>
THE CLASH GO TO A SHOOT-OUT FOR THE 3RD TIME IN 3 GAMES. THEY TRAIL 3-2.DOWN TO THEIR LAST SHOT. BUT WADE BARRETT CAN'T SCORE. THE CLASH LOSE. 3-2 IN THE SHOOTOUT. SAN JOSE NOW 0-3. DALLAS IMPROVES TO 3-0.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115Taco-Bell Dog>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Taco-Bell Dog</H3><BR>
ONE SMALL SPANISH-SPEAKING DOG SPARKED A HUGE CONTROVERSY IN A TACO-BELL AD CAMPAIGN. 
<P>
NOW.  MORE THAN HUNDRED "TACO BELL WANNA-BE'S" ARE READY TO JUMP THROUGH HOOPS FOR A CHANCE TO MEET THE FAMOUS DOG. 
<P>
CHIHUAHUAS RACED ACROSS AN OBSTACLE COURSE TO WIN A TRIP TO HOLLYWOOD FOR AN ON-SET VISIT WITH TACO BELL'S FAMOUS STAR. 
<P>
THE DOGS ALSO SANG.  DANCED.  AND PRANCED AROUND IN COSTUMES FOR THE BLUE RIBBON. 
<P>
THE CONTEST LAUNCHED TACO-BELL'S NEW 99-CENT 
<P>
"GORDITAS".A GRILLED MEXICAN FLATBREAD TACO. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
