<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Monday, 4/20/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Monday, 4/20/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (alisal bomb)>TS1 (alisal bomb)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106Alisal bomb threat>Alisal bomb threat</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(pot plane crash)>(pot plane crash)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107William Brown sente>William Brown sente</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(CA car chase)>(CA car chase)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Bowen new charges>Bowen new charges</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(Marine cable car)>(Marine cable car)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#155Monterey PD fire>Monterey PD fire</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Qualified teachers-I>Qualified teachers-I</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#150Ng competent-IN>Ng competent-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/sal peppers>Fox Biz/sal peppers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Gilroy taggers caught>Gilroy taggers caught</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131SC bombay funds>SC bombay funds</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#151SC Mission st plan>SC Mission st plan</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43NBA>NBA</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#152Marina city plan>Marina city plan</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44Boston Marathon>Boston Marathon</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(pot plane) >Bump 1(pot plane) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Golf: Saving Strokes>Golf: Saving Strokes</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#115bump 2(qual teach) >bump 2(qual teach) </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Junior achievement>Junior achievement</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Victim's rights wk-IN>Victim's rights wk-IN</A></TD>


<TD BGCOLOR=#FFFFF0> </TD>
</Table>
</CENTER><HR><BR>
<A NAME=134TS1 (alisal bomb)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (alisal bomb)</H3><BR>
UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
A LOCAL PRINCIPAL CALLS IN THE BOMB SQUAD AFTER FINDING A SUSPICIOUS PACKAGE INSIDE HIS SCHOOL.
<P>
A MAN ACCUSED OF KILLING A DOZEN PEOPLE A DECADE AGO IS FACING HIS DAY IN COURT.
<P>
AND.TEARS ARE SHED AS SURVIVORS OF VIOLENT CRIMES SPEAK ABOUT THEIR PAIN.
<P>
WE'LL HAVE ALL THE DAY'S NEWS, SANDHYA WITH WEATHER AND KEN WITH SPORTS.KCBA FOX NEWS IS NEXT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106Alisal bomb threat>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Alisal bomb threat</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M CHERI GYURO. ALAN MARSDEN HAS THE NIGHT OFF.
<P>
ANOTHER BOMB SCARE ON THE CENTRAL COAST TODAY. THIS ONE. A SUSPICIOUS PACKAGE FOUND INSIDE A LOCAL SCHOOL.
<P>
THE BOMB-SQUAD FROM ALAMEDA COUNTY CAME IN TO DETONATE THE DEVICE.
<P>
ALISAL HIGH PRINCIPAL JOHN TORRES FOUND A PLASTIC BOX, BOUND WITH DUCT TAPE AND WIRES STICKING OUT NEAR A CLASSROOM.
<P>
AS A PRECAUTION. TORRES LEFT THE PACKAGE ON THE GROUND. AND CALLED THE BOMB SQUAD.
<P>
IT LOOKED SUSPICIOUS, SO CALLED THE BOMB SQUAD, THEY X-RAYED IT, DETONATED IT, MAY HAVE BEEN JUST TO DISRUPT SCHOOL WE TREATED IT LIKE IT WAS A BOMB.
<P>
SOME CLASSROOMS WERE EVACUATED AND THE STUDENTS WERE MOVED TO ANOTHER PART OF THE SCHOOL.
<P>
STILL NO WORD ON A SUSPECT OR A MOTIVE IN THE CASE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107William Brown sente>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>William Brown sente</H3><BR>
THE SANTA CRUZ MAN CONVICTED OF DOUSING HIS WIFE WITH GASOLINE.AND SETTING HER AND THEIR HOME ON FIRE.WILL SPEND THE NEXT 13 YEARS BEHIND BARS.
<P>
        WILLIAM BROWN'S WIFE. PATRICIA JENKINS. EVENTUALLY DIED FROM HER INJURIES.
<P>
        TODAY. THEIR 17-YEAR OLD DAUGHTER BEGGED THE JUDGE TO HAND BROWN THE MAXIMUM PENALTY.
<P>
        INVESTIGATORS SAY BROWN ADMITTED USING THE GASOLINE. BUT SAID IT WAS HIS WIFE WHO LIT THE MATCH.
<P>
OC: "PULLED THE TRIGGER."
<P>
        BROWN PLED NO CONTEST TO THE MANSLAUGHTER CHARGE BACK IN JANUARY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Bowen new charges>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bowen new charges</H3><BR>
A SANTA CRUZ MAN. ALREADY IN TROUBLE WITH THE LAW FOR SELLING BOGUS COMPUTER PARTS AND STOCKS ON THE INTERNET. NOW FACES CHARGES OF PIMPING AND PANDERING.
<P>
POLICE IN SANTA CLARA COUNTY SAY WILLIAM BOWEN WAS RUNNING A MASSAGE PARLOR AS A FRONT FOR A PROSTITUTION RING.
<P>
BOWEN WAS FIRST LINKED TO THE RING LAST YEAR. WHEN INVESTIGATORS FOUND HIS PAGER AND A PHONE NUMBER TO A MASSAGE BUSINESS.
<P>
THIS NEW CHARGE ADDS ANOTHER 5-HUNDRED THOUSAND DOLLARS TO HIS ONE MILLION DOLLAR BAIL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=155Monterey PD fire>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Monterey PD fire</H3><BR>
THE FIRING OF A MONTEREY POLICE OFFICER IS MAKING IT DIFFICULT FOR THE DISTRICT ATTORNEY TO PROSECUTE CERTAIN D-U-I CASES.
<P>
THE CITY FIRED D-U-I ENFORCEMENT OFFICER JEFF WARREN EARLIER THIS YEAR. 
<P>
NOW, DRUNK DRIVING SUSPECTS ARRESTED BY WARREN ARE BEING ALLOWED TO PLEAD GUILTY TO A LESSER CHARGE. 
<P>
THE DISTRICT ATTORNEY SAYS THAT'S BECAUSE WARREN IS NO LONGER A CREDIBLE WITNESS IN COURT, AND CAN'T TESTIFY FOR THE PROSECUTION.
<P>
IN THE MEANTIME, SUSPECTS ARRESTED BY WARREN WHO ARE CONVICTED ARE GETTING MORE LENIENT SENTENCES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=150Ng competent-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ng competent-IN</H3><BR>
ACCUSED MASS MURDERER CHARLES NG  WAS IN AN ORANGE  COUNTY CALIFORNIA COURTROOM THIS MORNING FOR A COMPETENCY HEARING. 
<P>
IT'S BEEN ALMOST 13 YEARS SINCE HE WAS ARRESTED IN CANADA  AND CHARGED WITH KILLING A DOZEN PEOPLE IN AN UNDERGROUND CHAMBER IN THE SIERRA NEVADA FOOTHILLS. 
<P>
FOX'S BRUCE MANNING HAS MORE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Gilroy taggers caught>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Gilroy taggers caught</H3><BR>
THEY LEFT THEIR MARK AND MADE FOLKS STINKING MAD IN THE GARLIC CAPITOL.
<P>
BUT NOW THE ACCUSED VANDALS ARE IN JUVENILLE HALL.
<P>
GILROY POLICE ARRESTED TWO TEENAGE BOYS LAST NIGHT FOR VANDALIZING BROWNELL SCHOOL.
<P>
INVESTIGATORS SAY THEY BELIEVE THE 15 AND 13 YEAR OLD BROTHERS ARE RESPONSIBLE FOR SPRAY PAINTING THE WREN AVENUE MEDICAL COMPLEX LAST WEEK.CAUSING THOUSANDS OF DOLLARS WORTH OF DAMAGE.
<P>
THE BROTHERS ARE ALSO CHARGED WITH STEALING THE PAINT FROM A GILROY HOME.   
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131SC bombay funds>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC bombay funds</H3><BR>
CITY OFFICIALS AND ENVIRONMENTALISTS  ARE GOING HEAD TO HEAD WITH A MAJOR CORPORATION.
<P>
THE FIGHT IS OVER A SCENIC PIECE OF PROPERTY IN SANTA CRUZ.
<P>
THEY'VE STARTED A CAMPAIGN TO RAISE MONEY TO HELP BUY THE LAND BORDERING MOORE CREEK.
<P>
RIGHT NOW IT'S SLATED TO BE DEVELOPED INTO A SUBDIVISION.
<P>
TO STOP IT. THE CITY HAS TO BUY THE LAND FROM THE COMPANY THAT OWNS IT FOR 3 POINT 8 MILLION DOLLARS BY JUNE 30-TH.OR 3.9 MILLION BY NOVEMBER 15-TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=151SC Mission st plan>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Mission st plan</H3><BR>
ALSO IN SANTA CRUZ.CITIZENS HAD THE CHANCE TO SEE FIRST HAND HOW THE CITY PLANS TO EXPAND MISSION STREET.
<P>
AN OPEN HOUSE WAS HELD THIS AFTERNOON AT THE CIVIC AUDITORIUM.
<P>
RESIDENTS WERE ABLE TO LOOK AT  PLANS TO EXPAND MISSION FROM CHESTNUT TO SWIFT STREET. AND TALK WITH CITY ENGINEERS ABOUT THE DESIGNS.
<P>
IN: "CAL TRANS WOULD LIKE TO CUT." OC: "PRESERVED AS POSSIBLE."
<P>
IN: "WE'VE HAD A LOT OF COMMENT TODAY." OC: "ADDRESS THOSE CONCERNS."
<P>
THE PROJECT IS SCHEDULED TO START BY THE END OF THIS YEAR. FINISH IN ABOUT TWO YEARS. AND COST ABOUT TEN MILLION DOLLARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=152Marina city plan>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marina city plan</H3><BR>
IN MARINA TONIGHT. THE CITY COUNCIL HELD A SPECIAL MEETING TO TALK WITH RESIDENTS ABOUT FUTURE PLANS FOR THE CITY.
<P>
THE COUNCIL. ALONG WITH CITY ENGINEERS AND PLANNERS. LOOKED AT POSSIBLE SITES FOR FOR NEW SCHOOLS AND TOWN CENTERS.
<P>
THERE WAS ALSO DISCUSSION ABOUT WHAT TO DO WITH FORMER FORD ORD LAND.
<P>
TONIGHT'S INPUT FROM THE COMMUNITY WILL HELP PLANNERS DECIDE FUTURE LAYOUTS FOR THE CITY.
<P>
IN: "THAT'S WHY THIS MEETING IS SO IMPORTANT." OC: "FROM OUR COMMUNITY."
<P>
ANOTHER MEETING FOR PUBLIC INPUT IS SCHEDULED FOR MAY 30TH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(pot plane) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(pot plane) </H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
CUSTOMS OFFICIALS GIVE CHASE FOR OVER 15-HUNDRED MILES.WE'LL TELL YOU HOW IT ENDED.    
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=115bump 2(qual teach) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>bump 2(qual teach) </H3><BR>
AND FIND OUT WHY ONE GROUP IS SAYING SOME TEACHERS IN CALIFORNIA SHOULD BE ON THE RECEIVING END OF THE LESSON PLAN.
<P>
WE'LL BE RIGHT BACK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Victim's rights wk-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Victim's rights wk-IN</H3><BR>
TO A SURVIVOR OF A VIOLENT CRIME.EVERY DAY IS PRECIOUS.
<P>
HUNDREDS OF THOSE FOLKS GOT TOGETHER IN SALINAS TODAY TO SHARE THEIR PAIN AND CELEBRATE THE BEGINNING OF VICTIM'S RIGHTS WEEK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
CUSTOMS OFFICIALS CHASE A SMALL PLANE CARRYING MARIJUANA FOR MORE THE 15-HUNDRED MILES.
<P>
THAT STORY FROM DETROIT TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(pot plane crash)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(pot plane crash)</H3><BR>
THE SMALL PLANE. CARRYING MORE THAN 3-HUNDRED POUNDS OF MARIJUANA. EVENTUALLY CRASHED IN A BASEBALL FIELD NEXT TO A JUNIOR HIGH SCHOOL IN DETROIT. KILLING THE PILOT. 
<P>
U-S CUSTOMS OFFICIALS HAVE JUST RELEASED THIS RADAR VIDEO OF THE CHASE FROM EL PASO TO DETROIT.
<P>
EYEWITNESSES SAY SOME PEOPLE ON THE SCENE MADE OFF WITH SOME OF THE POT. WITHOUT EVEN CHECKING ON THE CONDITION OF THE PILOT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(CA car chase)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(CA car chase)</H3><BR>
A MAN LEADS POLICE ON A HIGH SPEED CHASE. HOLDS A CHILD HOSTAGE.THEN TRIES TO MAKE A RUN FOR IT.
<P>
THE CHASE LASTED TWO-AND-A-HALF HOURS BEFORE HE FINALLY SURRENDERED THE CHILD IN SAN DIEGO. AT THE U.S./ MEXICAN BORDER. 
<P>
POLICE SAY THE MAN KIDNAPPED THE TODDLER WHEN THEY WENT TO HIS HOME TO QUESTION HIM ABOUT A ROBBERY IN DECEMBER. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(Marine cable car)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Marine cable car)</H3><BR>
FOUR MARINES INVOLVED IN A FATAL CABLE CAR CRASH IN ITALY COULD FACE CHARGES OF NEGLIGENT HOMICIDE.
<P>
A MILITARY HEARING WAS CONDUCTED ON THE CASE TODAY IN NORTH CAROLINA.
<P>
IN FEBRUARY. A MILITARY JET SLICED A CABLE WIRE AT A SKI RESORT. SENDING 20 PEOPLE FALLING TO THEIR DEATHS. 
<P>
MARINE INVESTIGATORS SAY THE PLANE WAS BEING FLOWN TOO FAST AND WELL BELOW THE MINIMUM HEIGHT LIMIT FOR THAT AREA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Qualified teachers-I>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Qualified teachers-I</H3><BR>
IT'S A PROBLEM CRIPPLING SCHOOLS ACROSS THE NATION. THE STAGGERING LACK OF PROPERLY CREDENTIALED TEACHERS. 
<P>
AND AS FOX'S CLAUDIA COWAN REPORTS, IT'S A PROBLEM WITH NO SOLUTION IN SIGHT. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/sal peppers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/sal peppers</H3><BR>
THE CITY OF SALINAS HAS FINALLY STRUCK A DEAL THAT WILL CUT LOOSE THE SALINAS PEPPERS.
<P>
WE'LL HAVE THE LINEUP IN TONIGHT'S FOX BUSINESS REPORT.
<P>
THE SHUGART CORPORATION WILL PAY 20 THOUSAND DOLLARS WITHIN TWO WEEKS FOR THE FINAL TWO YEARS OF ITS FIVE YEAR LEASE OF THE STADIUM.
<P>
THAT'S ONLY HALF OF WHAT IT OWED.
<P>
ANOTHER FIVE THOUSAND WILL BE PAID BY MAY OF 19-99 IF ANOTHER WESTERN BASEBALL LEAGUE FRANCHINSE IS NOT UNDER CONTRACT BY SUMMER OF THAT SAME YEAR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
THE A'S ARE OFF TO THEIR WORST START SINCE MOVING TO OAKLAND IN 1968.
<P>
THEY'RE 4 AND 12, WHICH ACTUALLY WAS THE RAIDERS RECORD THIS LAST YEAR, NOT TO MENTION THE WARRIORS SHARE THAT OAKLAND COLISEUM PARKING LOT AS WELL.
<P>
NOT A LOT OF GOOD KARMA THERE RIGHT NOW.
<P>
THE A'S OPEN A 3-SERIES WITH THE TWINS TONITE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
OKAY, ITS TIME TO JUMP ON THE BANDWAGON. YOU MAY NOT BE MUCH OF A HOCKEY FAN MOST OF THE YEAR, BUT HECK, THE SHARKS MADE THE PLAYOFFS.
<P>
THEY BEGIN THEIR BEST OF 7-GAME SERIES WITH THE TOP SEED IN THE WESTERN CONFERENCE, THE DALLAS STARS, ON WEDNESDAY.
<P>
NOW THIS POTENTIAL UPSET FOR THE SHARKS ISN'T AS LONG OF A LONGSHOT AS YOU MIGHT THINK.
<P>
SAN JOSE IS 6 AND 2 VS. THE STARS OVER THE LAST 2-YEARS, AND THEY WON BOTH GAMES IN DALLAS THIS SEASON.
<P>
DALLAS IS LED BY GOALIE ED BELFOUR, WHO BOLTED FROM SAN JOSE IN THE OFF-SEASON, TO SIGN WITH THE STARS.
<P>
THE PRESSURE IS ON DALLAS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43NBA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA</H3><BR>
THE "NBA" PLAYOFFS GET UNDERWAY ON THURSDAY.
<P>
BUT 2-COACHES WHO'S TEAM FAILED TO QUALIFY FOR THE POST SEASON, GET THEIR WALKING PAPERS TODAY.
<P>
BILL HANZLIK, WHO COACHED THE DENVER NUGGETS TO THE 2ND WORST RECORD IN LEAGUE HISTORY, IS FIRED.
<P>
AS IS BILL FITCH, WHO COACHED THE L.A. CLIPPERS FOR THE LAST 4-YEARS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44Boston Marathon>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Boston Marathon</H3><BR>
WELL FOR THE LAST 102-YEARS, THEY'VE BEEN RUNNING THE BOSTON MARATHON.
<P>
WHICH IS ESPECIALLY FUN NOW, WITH THE RUNNING OF THE BIG SUR MARATHON JUST 6-DAYS AWAY.
<P>
ITS PATRIOTS DAY IN BOSTON, OVER 11-THOUSAND RUNNERS TAKE PART IN THE MARATHON.
<P>
ITS ALWAYS IMPRESSIVE TO SEE SUCH A MASS OF HUMANITY.
<P>
KENYA'S MOSES TANUI MAKES A STRONG KICK, PASSING HIS COUNTRYMAN JOSEPH CHEBET WITH A LITTLE OVER 200-METERS TO GO.
<P>
KENYA WINS ITS 8TH STRAIGHT BOSTON MARATHON, AS TANUI WINS WITH HIS PERSONAL BEST TIME OF 2-HOURS, 7-MINUTES, AND 34-SECONDS. 
<P>
ITS THE 3RD BEST TIME IN THE RACE'S HISTORY. HE WON IN '96 AS WELL.
<P>
THE WOMEN'S WINNER, FATUMA ROBA, OF ETHEOPIA, WINS FOR THE 2ND STRAIGHT YEAR. ROBA, THE 1996 OLYMPIC GOLD MEDALIST, ALSO SET A PERSONAL BEST WITH A TIME OF 2:23:21.
<P>
SHE BROKE AWAY FROM THE PACK EARLY, AND NEVER LOOKED BACK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Golf: Saving Strokes>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf: Saving Strokes</H3><BR>
AND FINALLY, IF YOUR TROUBLE ON THE GOLF COURSE IS AROUND THE GREENS, BRUCE LEWIS OFFERS A TIP THAT IS WEIGHTED IN YOUR DIRECTION.
<P>
TIME NOW FOR SAVING STROKES AT SAN JUAN OAKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Junior achievement>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Junior achievement</H3><BR>
FINALLY TONIGHT.
<P>
SOME FOLKS FROM K-C-B-A VISITED A SALINAS CLASSROOM TO HELP KIDS PREPARE FOR THE REAL WORLD.
<P>
THE PROGRAM CALLED "JUNIOR ACHIEVEMENT VOLUNTEERS" LETS PROFESSIONALS SHARE THEIR EXPERIENCES WITH KIDS.
<P>
THIS ONE AT GAVILAN VIEW MIDDLE SCHOOL WAS ABOUT GETTING THE SKILLS NEEDED TO LAND A JOB.
<P>
IN: "ONE OF THE THINGS I MENTIONED. " OC: "GO TO COLLEGE"
<P>
IN: "I'D BE TOTALLY LOST. OC: "FIGURE IT OTU BY YOURSELF."
<P>
IF YOU WOULD LIKE TO VOLUNTEER TO TEACH YOUR SKILL TO JUNIOR ACHIEVERS. YOU CAN CALL THEM AT.
<P>
1-800-THE NEW-J. THAT TRANSLATES TO 1-800-843-6395.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
