<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Friday, 4/10/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Friday, 4/10/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107SC Gang Rape-INT>SC Gang Rape-INT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#147Ireland peace accor>Ireland peace accor</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#108SC Gang Rape-GUT>SC Gang Rape-GUT</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109SC Gang Rape-TAG>SC Gang Rape-TAG</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(Gore/tornados)>(Gore/tornados)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Shannon jury trial>Shannon jury trial</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(Perot/Gays)>(Perot/Gays)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#139Monterey 7-11 shoot>Monterey 7-11 shoot</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#118(Deadly chase)>(Deadly chase)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129Lopez arrest>Lopez arrest</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/tax wkend>Fox Biz/tax wkend</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Curfew ordinance>Curfew ordinance</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Masters>Masters</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140Stilwell hall meeting>Stilwell hall meeting</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#43Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Marathon course>Marathon course</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126Watsonville landslide>Watsonville landslide</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#45Jaguars>Jaguars</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142So Cal mudslide>So Cal mudslide</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#150Boxing>Boxing</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#146Mexico holy week>Mexico holy week</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50elephant easter>elephant easter</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=107SC Gang Rape-INT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Gang Rape-INT</H3><BR>
        SHERIFF'S OFFICIALS WORKED ON THIS CASE ALL LAST NIGHT INTO
<P>
THIS MORNING AND THEY DO HAVE FOUR SUSPECTS IN CUSTODY. AN 18-YEAR
<P>
OLD, TWO 17-YEAR OLDS AND A 16-YEAR OLD.
<P>
        THE NATURE OF THEIR ALLEGED CRIME IS SO DISTURBING. EVEN
<P>
VETERAN INVESTIGATORS ARE APPALLED.
<P>
        
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=108SC Gang Rape-GUT>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Gang Rape-GUT</H3><BR>
        AT THE DOWNTOWN SANTA CRUZ METRO CENTER TODAY, PEOPLE WERE
<P>
*SHOCKED* TO HEAR THE NEWS:
<P>
        AROUND TWO O'CLOCK YESTERDAY AFTERNOON, FOUR MEN ALLEGEDLY
<P>
PICKED UP AN 11-YEAR OLD GIRL HANGING OUT AT THE METRO CENTER.
<P>
        THE GIRL APPARENTLY KNEW ONE OF THE MEN AND IT APPEARS SHE
<P>
WILLINGLY GOT IN THE CAR.
<P>
        BUT SHE COULDN'T HAVE IMAGINED WHAT WOULD HAPPEN NEXT.
<P>
        STILL INTOXICATED ON ALCOHOL AND DRUGS, THE GIRL WAS
<P>
REPORTEDLY DROPPED OFF BACK AT THE METRO CENTER.
<P>
        SHE WALKED BACK HOME. AND COLLAPSED.
<P>
        THIS MORNING, SHERIFF'S OFFICIALS ARRESTED THIS MAN, 18-YEAR
<P>
OLD ERNESTO GARCIA OF SANTA CRUZ, ALONG WITH THREE OTHER TEENS.
<P>
        ALL HAVE BEEN CHARGED WITH RAPE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109SC Gang Rape-TAG>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SC Gang Rape-TAG</H3><BR>
        THE SUSPECTS ARE EXPECTED TO BE ARRAIGNED NEXT WEEK.
<P>
        AS FOR THE VICTIM. WE'RE TOLD SHE'S STILL IN THE
<P>
HOSPITAL TONIGHT. BUT IN STABLE CONDITION.
<P>
        ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Shannon jury trial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Shannon jury trial</H3><BR>
A FORMER GREENFIELD POLICE OFFICER WILL HAVE TO WAIT UNTIL MONDAY TO HEAR A JURY'S DECISION.
<P>
MICHAEL SHANNON IS ACCUSED OF BEATING TWO PRISONERS.
<P>
HE'S BEEN CHARGED WITH TWO COUNTS OF INHUMANITY TO PRISONERS, ASSAULT AND BATTERY.
<P>
SHANNON'S ATTORNEY SAYS HE'S CONFIDENT THE JURY WILL AQUIT.
<P>
"I THINK WE HAVE A VERY ATTENTIVE JURY.  THROUGHOUT THE TRIAL THEY SEEMED TO BE LISTENING AND THE JUDGE ASKED A LOT OF QUESTIONS AND SEEMED TO CLARIFY THINGS AND IT SEEMS THE JURY WAS IMPRESSED."
<P>
THE PROSECUTION REFUSED TO COMMENT UNTIL A VERDICT IS REACHED.
<P>
THE CASE WENT TO THE JURY AROUND THREE-30 THIS AFTERNOON.
<P>
THE PANEL DELIBERATED FOR ABOUT THREE HOURS BEFORE ENDING FOR THE DAY.
<P>
A PREVIOUS TRIAL, IN FEBRURY, ENDED IN A HUNG JURY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=139Monterey 7-11 shoot>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Monterey 7-11 shoot</H3><BR>
ONE MAN IS IN CRITICAL CONDITION TONIGHT AND ANOTHER IS BEHIND BARS AFTER A SHOOTING IN MONTEREY.
<P>
MONTEREY POLICE SAY THEY RESPONDED TO THE *7-ELEVEN*, ON NORTH FREMONT STREET, JUST AFTER FOUR THIS MORNING.
<P>
AT THE SCENE THEY FOUND A MAN WITH SEVERAL GUN SHOT WOUNDS.
<P>
AN INVESTIGATION LED POLICE TO SALINAS, WHERE THEY ARRESTED 18-YEAR-OLD SEASIDE RESIDENT, ANGEL GARCIA.
<P>
OFFICERS SAY THE VICTIM AND THE SUSPECT KNOW ONE ANOTHER AND HAD A DISAGREEMENT EARLIER IN THE DAY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129Lopez arrest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Lopez arrest</H3><BR>
A 29-YEAR OLD MAN HAS BEEN ARRESTED. AND CHARGED IN CONNECTION WITH THE MARCH 12TH SHOOTING DEATH OF A SALINAS MAN.
<P>
GERARDO LOPEZ WAS ARRAIGNED TODAY ON CHARGES OF MURDER AND ATTEMPTED MURDER. IN THE SHOOTING DEATH OF JOSE GARCIA. AND THE WOUNDING OF ALEJANDRO MARTINEZ.
<P>
THE SHOOTINGS TOOK PLACE AT A STRIP MALL ON SANBORN ROAD.
<P>
POLICE SAY.  THE GUNMAN RAN UP TO THE VICTIM'S CAR AND FIRED THROUGH THE PASSENGER SIDE WINDOW.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Curfew ordinance>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Curfew ordinance</H3><BR>
TEENAGERS IN MONTEREY COUNTY THAT AREN'T INDOORS RIGHT NOW. COULD BE PICKED UP BY THE POLICE.
<P>
THAT'S BECAUSE A NEW CURFEW GOES INTO EFFECT TONIGHT.
<P>
THE UNINCORPORATED AREAS OF MONTEREY COUNTY HAVE HAD A CURFEW FOR SEVERAL YEARS. BUT BEGINNING TONIGHT, IT'S ABOUT TO GET A LOT TOUGHER.
<P>
TEENAGERS UNDER THE AGE OF 18 MUST BE OFF THE STREETS BY TEN O'CLOCK AT NIGHT. THE OLD CURFEW WAS 11 PM.
<P>
THE SHERIFFS DEPARTMENT SAYS THE NEW CURFEW RULES ARE AIMED AT PROTECTING, NOT PUNISHING THE TEENS.
<P>
THE NEW ORDINANCE PROVIDES FOR ENVFORCEMENT AGAINST MINORS AND PARENTS. OR BUSINESS ESTABLISHEMENTS PERMITTING MINORS TO BE THERE AFTER CURFEW HOURS.
<P>
MINORS WHO ARE CAUGHT OUT PAST TEN. WILL BE TAKEN TO THE SALINAS RECREATION CENTER. AND THEIR PARENTS WILL BE CALLED.  
<P>
PARENTS CAN BE HELD RESPONSIBLE. AND CHARGED WITH A MISDEMEANOR.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140Stilwell hall meeting>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Stilwell hall meeting</H3><BR>
STILL NO WORD ON THE FATE OF STILWELL HALL.
<P>
THE FORT ORD RE-USE AUTHORITY MET TODAY TO TRY TO DECIDE WHAT TO DO WITH THE OLD OFFICERS CLUB.
<P>
THE STRUCTURE. BUILT DURING WORLD WAR TWO. IS NOW ONLY ABOUT 10 FEET AWAY FROM THE OCEAN. BECAUSE OF CLIFF EROSION AND DEGRADATION.
<P>
SEASIDE MAYOR DON JORDAN SAYS THE BUILDING HAS SPECIAL MEANING FOR EVERYONE INVOLVED WITH THE PROJECT.
<P>
THE ARMY AND CALIFORNIA PARKS AND RECREATION ARE PRESENTING THEIR COST ESTIMATES FOR SEVERAL ALTERNATIVES. INCLUDING DEMOLITION. MOVING THE STRUCTURE. OR RE-ENFORCING THE EXISTING SEA-WALL.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Marathon course>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Marathon course</H3><BR>
AFTER MONTHS OF WATCHING AND WAITING. AS HIGHWAY ONE IS REPAIRED. BIG SUR MARATHON OFFICIALS HAVE DECIDED TO GO AHEAD AND DESIGNATE A NEW COURSE FOR THIS YEAR'S RACE.
<P>
THE 13TH ANNUAL BIG SUR MARATHON WILL START AND FINISH IN CARMEL.
<P>
THE INTERIM COURSE WILL TAKE RUNNERS FROM THE CROSSROADS. TO THE BIXBY BRIDGE. AND THEN TURN AROUND. AND RACE BACK TO CARMEL.
<P>
MORE THAN SIX THOUSAND RUNNERS ARE EXPECTED FOR THE APRIL 26TH RACE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126Watsonville landslide>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Watsonville landslide</H3><BR>
SLIDING EARTH IS THREATENING AT LEAST TWO 
<P>
HOMES IN A WATSONVILLE NEIGHBORHOOD.
<P>
ONE HOUSE HAS ALREADY BEEN EVACUATED ALONG WILLOW CREEK STREET NEAR GREEN VALLEY ROAD.
<P>
A COMBINATION OF GROUND SHIFTING FROM THE 
<P>
1989 LOMA PRIETA EARTHQUAKE, AND OUR RECENT RAINS. THREATENS TO PULL THESE HOMES DOWN THE HILLSIDE.
<P>
        BUT THE HISTORY OF THIS  SLIDE MAY GO MUCH FURTHER BACK.
<P>
"INDICATIONS WE HAVE RIGHT NOW FROM THE SOILS PEOPLE IS THIS IS A SLIDE
<P>
THAT HAS OCCURRED HUNDREDS OF THOUSANDS OF YEARS AGO, AND IS JUST
<P>
MOVING AGAIN."
<P>
        COMMUNITY DEVELOPMENT DIRECTOR DAVE WILLIAMS SAYS 
<P>
WATSONVILLE'S ONLY RESPONSIBILITY AT THIS POINT, IS THE SAFETY OF THE RESIDENTS.
<P>
HOWEVER. THE CITY IS GETTING SOIL SAMPLES ANALYZED, AND THE DEVELOPER HAS SENT OUT CREWS TO TRY AND HELP SHORE UP THE HILLSIDE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142So Cal mudslide>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>So Cal mudslide</H3><BR>
THERE WERE MAJOR TRAFFIC DELAYS TODAY IN SOUTHERN CALIFORNIA. AFTER A MUDSLIDE CRASHES DOWN ON INTERESTATE-FIVE. ABOUT FIFTY MILES SOUTH OF BAKERSFIELD. 
<P>
TRAFFIC WAS BACKED UP FOR MILES THIS MORNING AS WORK CREWS TRIED TO CLEAR TONS OF MUD FROM THE ROADWAY. 
<P>
THE SLIDE HAPPENED JUST NORTH OF GORMON ON I-FIVE. THE MAIN ARTERY CONNECTING L-A AND BAKERSFIELD. 
<P>
THE HIGHWAY PATROL SAYS NO ONE WAS HURT BY THE FALLING MUD.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=146Mexico holy week>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Mexico holy week</H3><BR>
HOLY WEEK IS ALSO BEING CELEBRATED BY CHRISTIANS.IN LATIN AMERICA WITH A TRADITION THAT EMPHASIZES DRAMA AND PAGEANTRY. 
<P>
THE CITY OF TAXCO. ABOUT ONE HUNDRED MILES SOUTHWEST OF MEXICO CITY. IS A CENTER OF HOLY WEEK POMP AND RITUAL.   
<P>
THE COLORFUL PROCESSIONS THAT DOMINATE THE CLIMACTIC DAYS OF HOLY WEEK ATTRACT THOUSANDS TO THE CITY.
<P>
THE CEREMONIES DATE FROM THE 16-CENTURY. WHEN THE FRIARS OF THE MONASTERY OF SAINT BERNARDINE BEGAN TO REENACT THE CRUCIFIXION OF CHRIST. 
<P>
THE RITUAL. WHICH BEGINS IN DAYLIGHT AND ENDS WELL AFTER DARK. RUNS FOR MORE THAN SEVEN HOURS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=147Ireland peace accor>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ireland peace accor</H3><BR>
THIRTY YEARS AFTER THE FIRST VIOLENCE STARTED IN NORTHERN IRELAND. LEADERS HAVE APPARENTLY REACHED AN AGREEMENT TO END THE FIGHTING.
<P>
EIGHT NORTHERN IRELAND POLITICAL PARTIES. AND THE BRITISH IRISH GOVERNMENT. TODAY ANOUNCED A PLAN TO SPLIT THE PROVINCE.
<P>
KNOWN AS THE "GOOD FRIDAY PEACE ACCORD". THE PLAN WILL ALLOW PROTESTANTS AND CATHOLICS TO GOVERN NORTHERN IRELAND TOGETHER. IN AN ASSEMBLY OF A-HUNDRED-AND-EIGHT MEMBERS.
<P>
THE DEAL MUST BE APPROVED BY VOTERS IN NORTHER IRELAND. AND THE REPUBLIC OF IRELAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
VICE-PRESIDENT AL GORE TOURS THE TORNADO-RAVAGED SOUTHEASTERN STATES TODAY. WHERE THE DEATH TOLL HAS REACHED 40.
<P>
THAT STORY TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(Gore/tornados)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Gore/tornados)</H3><BR>
THE THREE TWISTERS KILLED 33 PEOPLE IN ALAMBAMA. AND LEFT MORE THAN 160 HURT.
<P>
FIVE PEOPLE WERE KILLED IN GEORGIA. AND ONE EACH IN MISSISSIPPI AND NORTH CAROLINA.
<P>
THE VICE PRESIDENT SAID THE DAMAGE WAS THE WORST HE'S EVER SEEN. AND PROMISED FEDERAL AID FOR EVERYONE THAT WAS AFFECTED BY THE POWERFUL STORMS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(Perot/Gays)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Perot/Gays)</H3><BR>
GAY RIGHTS GROUPS ARE CRITICIZING ROSS PEROT TODAY. 
<P>
GAY AND LESBIAN EMPLOYEES ARE UP IN ARMS BECAUSE NEW HIRES AT PEROT SYSTEMS CORPORATION WILL NO LONGER BE ABLE TO GET HEALTH INSURANCE BENEFITS FOR THEIR PARTNERS. 
<P>
IN 19-96. PEROT SYSTEMS CORPORATION BECAME THE FIRST COMPANY TO OFFER COVERAGE FOR SAME SEX PARTNERS. 
<P>
PEROT HAS SAID THAT HE WANTED TO BE FAIR TO OTHER SINGLE EMPLOYEES WITH HOUSEMATES WHO ARE NOT ELIGIBLE FOR BENEFITS. 
<P>
PEROT NOW CLAIMS THAT COVERING EVERYBODY'S HOUSEMATES WOULD BE TOO EXPENSIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=118(Deadly chase)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(Deadly chase)</H3><BR>
A 19-YEAR-OLD MAN IS IN CRITICAL CONDITION AFTER LEADING POLICE ON AN 80-MILE AN HOUR CAR CHASE.
<P>
IT HAPPENED ON THE STREETS OF NARRAGANSETT, RHODE ISLAND.
<P>
POLICE SAY THE TEENAGER GAVE CHASE WITH HIS FATHER AMAZINGLY CLINGING TO THE HOOD OF THE CAR THE ENTIRE TIME. 
<P>
AS THE CHASE ENDED THE TEEN LOCKED THE CAR DOORS AND SHOT HIMSELF IN THE HEAD. 
<P>
HIS FATHER SAYS THE YOUNG MAN WAS DESPONDENT OVER A BREAK-UP WITH HIS GIRLFRIEND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/tax wkend>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/tax wkend</H3><BR>
THE DREADED TAX DEADLINE IS LESS THAN A WEEK AWAY.     AND LOCAL TAX PREPARERS SAY MORE AND MORE PEOPLE ARE WAITING UNTIL THE LAST MINUTE TO FILE. 
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
THIS H AND R BLOCK OFFICE IN SALINAS WASN'T SEEING ITS USUAL RUSH. 
<P>
SOME DESKS WERE ACTUALLY EMPTY. DUE TO LOW DEMAND. 
<P>
THE MANAGER OF H AND R BLOCK BELIEVES NEW TAX LAWS ARE CONFUSING MANY PEOPLE. 
<P>
PEOPLE ARE WAITING. CAPITAL GAINS.
<P>
ANOTHER REASON THE OFFICES MAY BE EMPTY. TAX PREPARERS SAY THE NUMBER OF PEOPLE USING ELECTRONIC FILING IS UP DRAMATICALLY. JUMPING BY 60 PERCENT.  
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Masters>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Masters</H3><BR>
TIGER WOODS STEPPED TO THE FIRST TEE AT THE MASTERS TODAY, TO FIND HIMSELF PLAYING WITH 2-OF HIS GREATEST NEMESIS.
<P>
FUZZY ZOELLER, WHO MADE THE "FRIED CHICKEN" COMMENTS AT LAST YEAR'S MASTERS, AND COLIN MONTGOMERIE, WHO SAID ALL 12 OF HIS EUROPEAN RYDER CUP TEAMMATES COULD EASILY BEAT TIGER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=43Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
TO BASEBALL, AND TONITE THE 5 AND 4 GIANTS BEGIN A 4-GAME SERIES WITH MARK MCGWIRE AND THE ST. LOUIS CARDINALS. THE BLEACHER BUMS HAVE GOT TO BE EXCITED.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
MEANWHILE THE A'S ARE AT YANKEE STADIUM TODAY, FOR THE BRONX BOMBERS HOME OPENER.
<P>
AND YOU CAN'T BEAT JOE DIMAGGIO FOR THROWING OUT YOUR FIRST PITCH.
<P>
JOLTIN' JOE LOOKS GREAT AT 83.
<P>
TO SAY THAT THERE IS A LOT OFFENSE IN THIS GAME, IS AN UNDERSTATEMENT. TINO MARTINEZ HOMERS FOR THE YANKEES, THIS TIES IT AT 5 IN THE 3RD.
<P>
BUT EVERY A'S REGULAR SCORES A RUN AND DRIVES IN A RUN  BY THE 5TH INNING.
<P>
COMBINED, 30-RUNS ARE SCORED ON 32-HITS. 10-PITCHERS ALLOW 18 WALKS.
<P>
THIS IS THE HIGHEST SCORING GAME IN THE 75-YEAR HISTORY AT YANKEE STADIUM.
<P>
THE BOSS WILL GO HOME HAPPY, FINAL YANKEES 17 AND THE A'S 13.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=45Jaguars>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jaguars</H3><BR>
PRO SOCCER RETURNS TO THE CENTRAL COAST TONITE, AS THE CALIFORNIA JAGUARS PLAY THEIR HOME OPENER.
<P>
THE JAGS HOST THE EL PASO PATRIOTS AT THE SALINAS SPORTS COMPLEX.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=150Boxing>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Boxing</H3><BR>
AND FINALLY, WE CLOSE THE BOOK ON THE RIOT AT THE HYATT.
<P>
LAST NIGHT WE WEREN'T ABLE TO SHOW THE MAIN EVENT, BECAUSE IT JUST ENDED AS WE WENT ON.
<P>
DANNY LUJAN JUNIOR, A LIGHTWEIGHT WHO HAILS FROM SALINAS, AND IS RANKED 8TH BY THE IBF, TAKES ON GUSTAVIO TAPIA OF SANTA ANA.
<P>
AND DESPITE BEING KNOCKED DOWN THE 2ND ROUND, LUJAN GETS UP TO WIN A SPLIT DECISION. 2-JUDGES THOUGHT LUJAN WON, WHILE THE OTHER JUDGE THOUGHT IT WAS A DRAW.
<P>
LUJAN IMPROVES HIS RECORD TO 15 AND 4.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50elephant easter>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>elephant easter</H3><BR>
COLORED EGGS AND CHOCOLATE BUNNIES MAY BE POPULAR AMONG CHILDREN DURING EASTER.BUT KIDS AREN'T THE ONLY ONES WHO GET TO ENJOY HOLIDAY TREATS THESE DAYS. 
<P>
AS A KICKOFF TO SPRING AT THE BALTIMORE ZOO, ELEPHANTS HAD THEIR OWN EASTER HUNT.SEARCHING FOR TREATS IN THE ELEPHANT YARD. 
<P>
BREAD ROLLS DYED IN DIFFERENT COLORS AND STUFFED WITH HONEY AND PEANUT BUTTER WERE HIDDEN THROUGHOUT THE ELEPHANT YARD BY "HOPPY THE BUNNY." 
<P>
THEY'RE MEANT TO GET THE ANIMALS TO ACT AS THEY WOULD IN THEIR NATURAL HABITAT AND TO ENCOURAGE THEIR NATURAL BEHAVIORS. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
