<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 3.0//EN" "html.dtd">
<HTML>

<HEAD>

    <TITLE>KION News Archives</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>


<BODY>

<TABLE>

<TR><TD>



</TD></TR>
<TR><TD ALIGN="CENTER">
<BR><BR>
<H2>
KION News Archive
</H2></TD></TD></TR>
</TR>
</TABLE>

<FORM ACTION="query.idq" METHOD="GET">
<TABLE width="400">
<TR>
<td>Enter your query below:</td>
</TR>
<TR>
<TD><INPUT TYPE="TEXT" NAME="CiRestriction" SIZE="40" MAXLENGTH="100" VALUE=""><INPUT TYPE="SUBMIT" VALUE="Search"></TD>
</TR>

</TABLE>

        <INPUT TYPE="HIDDEN" NAME="CiScope" VALUE="/newsarchives">
        <INPUT TYPE="HIDDEN" NAME="CiMaxRecordsPerPage" VALUE="10">
	    <INPUT TYPE="HIDDEN" NAME="TemplateName" VALUE="query">
	    <INPUT TYPE="HIDDEN" NAME="CiSort" VALUE="rank[d]">
        <INPUT TYPE="HIDDEN" NAME="HTMLQueryForm" VALUE="query.asp">
</FORM>

<h3>Search Tips:</h3>

<UL>
<LI><em>Use 'and' to search for multiple keywords.</em>
<LI><em>To find news from a specific date, search for the date in 1/31/98 format in your query.</em>
<LI><em>To further narrow your search to a specific show, include the name of the show also.</em></ul>
<br><br><br><br>
<!--#include file="../footer.inc"-->

</BODY>
</HTML>

