<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Eyewitness News</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD class="a">
<IMG SRC="../images/eyeonjobs.gif" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<center><h3>WEB SITE COORDINATOR/PROMO ASSISTANT POSITION</h3></center>

<a href="http://www.ackerley.com" target="_top">Ackerley Communications Inc.</a>, operator of KCBA FOX 35 and KION CBS 46, has an opening for a Web site Coordinator/Promotions Assistant at our studio facilities in Salinas, California. Position will be responsible for creation and daily maintenance of promotional and sales content for Web sites of both television stations as well as general clerical and organizational duties within the Promotion Department. HTML programming experience helpful but not required. Qualified applicants will be extremely organized, competent/comfortable with computers, experienced with a wide range of software and familiar with the World Wide Web.  Following is a more complete list of duties associated with this position:  
<br><br>

<center><h3><u><em>PRIORITIZED WEB SITE COORDINATOR/ PROMOTION ASSISTANT DUTIES</em></u></h3></center>

<strong>Website Coordinator for both KCBA-TV & KION-TV:</strong><br>
Each station has it's own Web site that must remain fresh, entertaining and informative enough to assure repeated visits from viewers attracted to the Web sites through on-air promotional announcements… Repeat visits that, in turn, assure the revenues necessary to justify the existence of each Web site.  Website Administrator/Promotion Assistant monitors both sites for accuracy and freshness of content; works with Promotion Director, Assistant Promotion Director and Web site designers in creating new content for Web sites; makes sure new material is delivered to Web site designers, and acts as liaison between sales departments and web designers for material necessary in Web site advertising.  	
<br><br>
<strong>Promotion Inventory Maintenance:</strong><br>
Each station's promotional inventory changes on a daily basis.  Promotion Assistant makes sure each stations promotional inventory stays current…  adding or removing physical promotional spots from each station's master control inventory as it is necessary.				
<br><br>
<strong>Log Discrepancy Recon:</strong><br>
Master Control Operators for both stations fill out daily log discrepancy forms to explain if and when problems occur with the planned execution of that days log.  Promotion Assistant meets with Promotion Manager on a daily basis to discuss and fix any log discrepancy problems that come under the direct responsibility of the Promotion Department. 				
<br><br>
<strong>Coordinates promotional satellite feeds:</strong><br>
Along with programming, commercial and news satellite feeds; each station receives several promotional satellite feeds on a daily basis.  These feeds contain the network and syndicated programming episodic and generic promotions necessary for us to effectively promote our programming.  As a rule, the satellite feeds are subject to change on a moment's notice.  Promotion Assistant keeps track of updated satellite schedules through daily Network/Syndicator feed facsimiles and coordinates with the Programming department to make sure feeds are received in a timely manner.				
<br><br>
<strong>Filters and disseminates written promotional communications:</strong><br>
On a daily basis, the Promotion Department receives a huge amount of written communications.  Promotion Assistant filters useless information and then files and/or disseminates important information to the Promotion Director, Assistant Promotion Director and affected departments. 	
<br><br>
<strong>General Promotion Department Clerical Duties:</strong><br>
Includes filing; word processing; maintaining promotion department scheduling book; answering and directing department phone calls; assisting with implementation of outside promotional events for both stations and running errands.						
<br><br>
<strong>PSA library maintenance:</strong><br>
Both stations have as many as 100 PSAs airing on a rotating basis.  Each station is sent new Public Service Announcements on a daily basis.  Promotion Assistant views all incoming PSAs and continuously updates each station's PSA library by entering 10 new PSAs and deleting 10 old PSAs for each station on a weekly basis.							
<br><br>
Please e-mail your Resume and Cover Letter to <a href="mailto:bcalvin@redshift.com">bcalvin@redshift.com</a>. Or snail mail them to Brent Calvin, Promotion Director, KCBA FOX 35/KION CBS 46,1550 Moffett Street, Salinas, CA  93905.  No phone calls please.  Ackerley Communications Inc. is an Equal Opportunity Employer.

<br><br><br>



<!--#include file="../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>
