<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Sandhya Patel</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<CENTER><H1>SANDHYA PATEL</H1>
<H2>Meteorologist</H2>
<H3>KCBA FOX News At Ten</H3></CENTER>

<img src="../../images/sandhya_patel.jpg" width=117 height=150 alt="" border=0 align="right">
<P>Birthplace: 		San Francisco, California</P>
<P>Education: 		Graduate, San Francisco State University</P>
<P>Special interests:	Painting, Talking and Children</P>

<P>Sandhya was born in San Francisco, CA, and raised in Salinas.  In search of a career in reporting, Sandhya graduated with a degree in radio and television from San Francisco State University.  Hired at KCBA Fox 35 as an assignment editor and reporter, she found herself with the opportunity to become the weekend weather anchor for KCBA FOX News at Ten.  In June of 1996, Sandhya's drive and commitment to her craft made her the first choice to become KCBA Fox News at Ten's main Weather Anchor.  Sandhya is extremely serious about her position as a forecaster, she is a certified National Weather Association meteorologist and is currently working towards her American Meteorological Society certification. Sandhya sees weather as an exciting field and loves her job.  As passionate as Sandhya is about meteorology, she plans to someday make room in her life for marriage and children.</P>


<BR><BR>
<!--#include file="../../footer.inc" -->

</BODY>
</HTML>
