<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Zane Tabari</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>
<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">

<CENTER><H1>Zane Tabari</H1>
<H2>Weekend Sports Anchor</H2>
<H3>KCBA Fox News At Ten</H3></CENTER>


<P>Birth Place: Saratoga, California</P>
<P>Education:   Arizona State University</P>
<P>Special Interests: Golf, Movies, Running</P>


<P>Born and raised in the South Bay area of California, Zane Tabari has been a sports enthusiast since childhood.  After high school, Zane moved to Arizona, where he studied </P>
<P>Broadcast Journalism at Arizona State University from 1986, through 1990. During College, he found a friend and mentor in the Sports Director of the Campus Radio Station, who encouraged Zane to broadcast the sports updates and game play by plays. He realized through his experiences in radio, that he really enjoyed being able to tell people about the events happening in the sports world.  Sports would soon become his main focus.  Zane gained experience through several internships and was hired in 1990 by KCBA Fox 35 in Salinas, California.  He worked in various positions for KCBA Fox News before being appointed to his current position, Weekend Sports anchor position in 1993, a place where he feels quite at home.</P>
<P>Zane is single, and  enjoys life in Santa Cruz, on the Central Coast of California. </P>
<P>A self-proclaimed "Golf Addict", he has the luxury of being close to two of his favorite things...the ocean and plenty of golf courses!</P>
<BR><BR>
<!--#include file="../../footer.inc" -->

</BODY>
</HTML>
