
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KCBA News</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">

<a href="news.asp"><img src="../images/news.gif" width=284 height=32 alt="" border="0"></a><br>
<p><strong><a href="news.asp">Top news stories</a></strong>  Get the latest from the KCBA Fox News at Ten news team.</p>

<center><h1>The KCBA Fox News Team</h1>
<p><img src="../images/fox_news_team2.jpg" width=250 height=202 alt="" border=0><br>
<A HREF="bios/ken.asp">Ken Rothhouse</A> Alan Marsden <A HREF="bios/sandhya.asp">Sandhya Patel</A></p>

<br>
<center><a href="http://www.foxnews.com" target="_blank"><img src="../images/foxnews.gif" width=77 height=54 alt="Fox News" border=0 hspace=5 align="left"></a><h2>Find the latest national news at <a href="http://www.foxnews.com" target="_blank">Foxnews.com</a></h2></center>

<!--#include file="../footer.inc" -->


</BODY>
</HTML>
