<HTML>
<BODY BGCOLOR=#FFFFFF BGPROPERTIES=FIXED>
<FONT FACE=ARIAL SIZE=3>
<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>KCBA FIRST AT TEN, Monday, 4/27/98</TITLE>
</HEAD>
<CENTER>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>KCBA FIRST AT TEN, Monday, 4/27/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH=80% BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#134TS1 (Filler)>TS1 (Filler)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#137(tomb of unknown)>(tomb of unknown)</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#127Filler trial day 2>Filler trial day 2</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Fox Biz/computers>Fox Biz/computers</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#126MAC historic tax>MAC historic tax</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#13Bump 1(SJ arena) >Bump 1(SJ arena) </A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#125Salinas shooting>Salinas shooting</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#140SJ-arena-int>SJ-arena-int</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#106TOSS TO CHERI>TOSS TO CHERI</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#141SJ-arena-guts>SJ-arena-guts</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#107Teacher protest-IN>Teacher protest-IN</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#142SJ-arena-tag>SJ-arena-tag</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#109Teacher protest-TA>Teacher protest-TA</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#121TZ/Toss to Sandhya>TZ/Toss to Sandhya</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#131Teacher of the year>Teacher of the year</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#40Giants>Giants</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#130Clinton/Prop 227>Clinton/Prop 227</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#42A's>A's</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#129SCOTUS muni elect>SCOTUS muni elect</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#44NBA Playoffs>NBA Playoffs</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#120Across America>Across America</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#143Sharks>Sharks</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#119(dance shooting)>(dance shooting)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#98Golf: Saving Strokes>Golf: Saving Strokes</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#117(children found)>(children found)</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#50Sly & Tweety stamp>Sly & Tweety stamp</A></TD>

</Table>
</CENTER><HR><BR>
<A NAME=134TS1 (Filler)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TS1 (Filler)</H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT TEN.
<P>
DAY TWO OF THE CASE AGAINST THE MAN ACCUSED IN THE FORT ORD SNIPER ATTACK.
<P>
LOCAL TEACHERS GO TO BAT FOR THEIR PRINCIPAL.
<P>
AND IN PART ONE. OF AUTHORIZED PERSONNEL ONLY. WE'LL GO BEHIND THE SCENES OF THE SAN JOSE ARENA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=127Filler trial day 2>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Filler trial day 2</H3><BR>
GOOD EVENING. AND THANKS FOR JOINING US. I'M ALAN MARSDEN.
<P>
JAMES GAUGHRAN. THE MAN SHOT AND WOUNDED BY A FORT ORD SNIPER LAST JUNE. TESTIFIES THIS MORNING.AS DAY TWO OF THE JOHN FILLER CASE GETS UNDERWAY.
<P>
GORAN TOLD THE COURT HE NEVER WORKED WITH DEFENDANT JOHN FILLER.
<P>
HE DIDN'T EVEN KNOW THE MAN.
<P>
HE SAYS HE HEARD POPPING SOUNDS. JUST BEFORE FILLER TURNED A RIFLE ON HIM. 
<P>
JOE LLOYD OF PRUNEDALE WAS KILLED DURING THAT DEADLY AMBUSH.
<P>
GORAN PROUDLY TOLD THE COURT IT WAS LLOYD WHO SAVED HIS LIFE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=126MAC historic tax>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>MAC historic tax</H3><BR>
A LOCAL HISTORICAL PRESERVATION GROUP WANTS TO INCREASE TAXES TO MAINTAIN LOCAL CULTURE.
<P>
THE GROUP. CALLED THE MONTEREY ACTION COALITION.  WANTS TO RAISE THE CITY TO RAISE ITS HOTEL TAX BY ONE HALF PERCENT.
<P>
THE MONEY WOULD FUND A SERIES OF CULTURAL PROGRAMS AND HISTORIC CAPITAL IMPROVEMENT PROJECTS.
<P>
TODAY. THE GROUP ASKED THE MONTEREY CITY COUNCIL TO PLACE THE HALF PERCENT HOTEL TAX ON THE NOVEMBER BALLOT.
<P>
THE GROUP IS ALSO STARTING A PETITION DRIVE TO QUALIFY THE INITIATIVE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=125Salinas shooting>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas shooting</H3><BR>
SALINAS POLICE ARE ON THE LOOKOUT FOR TWO MEN  SUSPECTED OF GUNNING DOWN A SALINAS MAN EARLY THIS MORNING.
<P>
POLICE FOUND 19 YEAR OLD JOSE FERNANDEZ.LYING ON THE GROUND. NEAR AN ELEMENTARY SCHOOL ON NORTH SANBORN ROAD.
<P>
FERNANDEZ WAS REPORTEDLY WALKING DOWN THE STREET WHEN HE WAS CONFRONTED. AND THEN SHOT TO DEATH. BY TWO MEN.
<P>
POLICE HAVE NO MOTIVE AND NO SUSPECTS IN THE CASE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=106TOSS TO CHERI>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TOSS TO CHERI</H3><BR>
CONTROVERSY AT THE SALINAS CITY SCHOOL DISTRICT TONIGHT.
<P>
PARENTS AND TEACHERS ARE UPSET ABOUT A DECISION MADE BY SCHOOL BOARD MEMBERS.
<P>
CHERI GYURO IS FOLLOWING THE ISSUE.SHE JOINS US NOW FROM THE NEWSDESK WITH MORE, CHERI?
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=107Teacher protest-IN>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teacher protest-IN</H3><BR>
ALAN, ALL THE FUSS IS OVER THE PRINCIPAL AT EL GABILAN ELEMENTARY.
<P>
BOARD MEMBERS DEMOTED HER.SO THE PICKET SIGNS CAME OUT.AND THE PROTESTORS SHOUTED IN FULL FORCE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=109Teacher protest-TA>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teacher protest-TA</H3><BR>
SEIERSEN ASKED THE SCHOOL BOARD TO RESCIND THE DECISION.
<P>
MEANWHILE.SHE'S HIRED AN ATTORNEY FROM THE ACLU.
<P>
SCHOOL BOARD MEMBERS WOULD NOT COMMENT ON THE ISSUE.
<P>
REPORTING LIVE FROM THE NEWSDESK I'M CHERI GYURO.ALAN, BACK TO YOU.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=131Teacher of the year>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teacher of the year</H3><BR>
A CENTRAL COAST TEACHER IS HONORED AS ONE OF THE BEST. FOR WHAT HE GIVES BACK TO HIS STUDENTS.
<P>
KENT KRAEMER.BUSINESS TEACHER AND COMMUNITY SERVICE ADVISOR AT MOUNT TORO HIGH SCHOOL IN SALINAS.HAS BEEN NAMED CALIFORNIA TEACHER OF THE YEAR.      KRAEMER SAYS HE WAS SHOCKED AT THE AWARD
<P>
.BUT HE SAYS HE'S NOT CONCERNED ABOUT WHAT OTHERS THINK.BUT WHAT HIS STUDENTS ARE ABSORBING IN HIS CLASSES.
<P>
THE BOTTOM LINE IS THE SUCCESS OF A GOOD TEACHER NOT HOW HOW GOOD YOU THINK YOU ARE OR HOW GOOD A TEACHER SOMEONE ELSE THINKS YOU MAY BE.  THE BOTTOM LINE IS WHAT ARE THE STUDENTS LEARNING.
<P>
THE CALIFORNIA CONTINUATION EDUCATION ASSOCIATION RECOGNIZES KRAEMER'S PASSION FOR TEACHING.
<P>
THE COMPETITION WAS AMONG 12 REGIONS WHICH REPRESENTS DISTRICTS FROM THE OREGON TO THE MEXICAN BORDERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=130Clinton/Prop 227>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Clinton/Prop 227</H3><BR>
PRESIDENT CLINTON HAS COME OUT *AGAINST* CALIFORNIA'S PROP 227.
<P>
THE MEASURE ELIMINATES BILINGUAL EDUCATION.
<P>
EDUCATION SECRETARY RICHARD RILEY SAYS THE MEASURE WOULD LEAD TO FEWER CHILDREN LEARNING ENGLISH. AND MANY CHILDREN FALLING BEHIND IN THEIR STUDIES.
<P>
PRESIDENT CLINTON IS SUPPORTING A BILINGUAL PROGRAM LIMITED TO THREE YEARS.
<P>
VOTERS WILL DECIDE THE ISSUE IN JUNE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=129SCOTUS muni elect>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SCOTUS muni elect</H3><BR>
THE U-S SUPREME COURT IS ABOUT TO HEAR A CASE THAT'S BEEN DEBATED IN MONTEREY COUNTY FOR DECADES.
<P>
THE COURT WILL BE ASKED TO DECIDE HOW RESIDENTS OF MONTEREY COUNTY ELECT MUNICIPAL COURT JUDGES.
<P>
JUSTICE DEPARTMENT LAWYERS WANT DISTRICTS THAT PARALLEL A COUNTY'S ETHNIC DIVERSITY.
<P>
THAT WOULD MEAN TWO ADDITIONAL LATINO JUDGES. 
<P>
OTHERS ARGUE THAT JUDGES SHOULD BE ELECTED IN COUNTY-WIDE RACES. 
<P>
THE SUPREME COURT IS EXPECTED TO SET A PRECEDENT FOR THE ENTIRE COUNTRY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=120Across America>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Across America</H3><BR>
STUDENTS REMEMBER A TEACHER THAT WAS SHOT AND KILLED AT A SCHOOL DANCE OVER THE WEEKEND.
<P>
POLICE SAY THE SHOOTER WAS A FELLOW STUDENT.
<P>
THAT STORY FROM EDINBORO, PENNSYVANIA. TOPS OUR LOOK AT NEWS ACROSS AMERICA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=119(dance shooting)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(dance shooting)</H3><BR>
SCIENCE TEACHER JOHN GILLETTE WAS VOLUNTEERING AT AN EIGHTH GRADE DANCE HE HELPED ORGANIZE. WHEN HE WAS SHOT IN THE HEAD.
<P>
POLICE SAY THE ALLEGED SHOOTER. 14-YEAR-OLD ANDREW WURST. HAD TALKED ABOUT SHOOTING SOMEONE AT THE DANCE. BUT DID NOT TARGET THE TEACHER.
<P>
WURST WILL BE CHARGED AS AN ADULT. BUT WILL NOT FACE THE DEATH PENALTY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=117(children found)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(children found)</H3><BR>
IN ARKANSAS. A FOUR-MONTH-OLD BABY AND A 16-MONTH-OLD TODDLER HAVE DIED AFTER BEING LEFT IN A PARKED CAR FOR EIGHT HOURS.IN EIGHTY-DEGREE HEAT. 
<P>
POLICE SAY THE WINDOWS WERE ROLLED UP AND THE GIRLS WERE STRAPPED IN THEIR CAR SEATS. 
<P>
THE ADULTS WHO WERE SUPPOSED TO BE CARING FOR THEM ARE NOW UNDER ARREST. CHARGED WITH  
<P>
MANSLAUGHTER AND ENDANGERING THE WELFARE OF A CHILD. 
<P>
ONE OF THE ADULTS. THE FATHER OF THE 4-MONTH OLD. WAS CARING FOR THE CHILD BECAUSE THE MOTHER COULD NOT FIND A SITTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=137(tomb of unknown)>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>(tomb of unknown)</H3><BR>
THE MYSTERY OF WHO IS BURIED IN THE TOMB OF THE UNKNOWNS AT ARLINGTON NATIONAL CEMETARY MAY SOON BE SOLVED.
<P>
THE PENTAGON HAS RECOMMENDED THE REMAINS INSIDE BE EXHUMED AND ANALYZED. TO CONFIRM THE SOLDIER'S IDENTITY.
<P>
AIR FORCE FIRST LIEUTENANT MICHAEL BLASSIE'S FAMILY SAYS THE REMAINS MAY BE HIS. 
<P>
BLASSIE'S PLANE WAS SHOT DOWN OVER VIETNAM IN 19-72. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Fox Biz/computers>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Fox Biz/computers</H3><BR>
AFTER MONTHS OF LAGGING SALES. COMPUTERS ARE ONCE AGAIN FLYING OFF THE SHELVES.
<P>
DETAILS IN TONIGHT'S FOX BUSINESS REPORT.
<P>
THE LATEST NUMBERS ARE A BREATH OF FRESH AIR FOR COMPUTER HARDWARE MANUFACTURERS.
<P>
RESEARCH REPORTS FROM DATA-QUEST AND INTERNATIONAL DATA CORP. SAY PERSONAL COMPUTER SALES GREW 12-PERCENT WORLDWIDE IN THE FIRST QUARTER OF THIS YEAR.
<P>
WITH A 21-PERCENT JUMP IN SALES IN EUROPE.
<P>
LOW COST COMPUTERS. INCLUDING ANYTHING UNDER A-THOUSAND DOLLARS. ARE CREDITED FOR HELPING COMPANIES LIKE COMPAQ AND HEWLITT PACKARD TURN A PROFIT.
<P>
INDUSTRY ANALYSTS SAY IT' NOT LIKELY TO STOP HERE. WITH PROFITS EXPECTED TO GO UP AS MUCH AS 15-PERCENT IN THE NEXT QUARTER.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=13Bump 1(SJ arena) >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Bump 1(SJ arena) </H3><BR>
COMING UP NEXT ON K-C-B-A FOX NEWS FIRST AT A TEN.
<P>
WHILE MOST OF US ARE ASLEEP IN BED. WORKERS AT THE SAN JOSE ARENA ARE JUST STARTING THEIR DAY. 
<P>
WE'LL FOLLOW ALONG RIGHT AFTER THIS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=140SJ-arena-int>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SJ-arena-int</H3><BR>
"AUTHORIZED PERSONNEL ONLY." 
<P>
EVERY TIME I SEE ONE OF THOSE SIGNS. I WANT TO KNOW WHAT'S BEHIND THAT DOOR.
<P>
WELL WE'RE ABOUT TO FIND OUT. IN A SERIES OF REPORTS.
<P>
FIRST OFF.   "THE SHARK TANK."  
<P>
THE NICKNAME IS STILL INFORCE NOW THAT THE SAN JOSE ARENA'S PRIMARY TENANT IS IN THE PLAYOFFS.
<P>
BUT JUST LIKE THE REGULAR N-H-L SEASON. THE ARENA CONTINUES TO HOST MANY OTHER EVENTS. LIKE CONCERTS?
<P>
IMAGINE.    WHAT HAPPENS WHEN A CONCERT ENDS AT MIDNIGHT FRIDAY. AND THE SHARKS HAVE A NATIONALLY TELEVISED GAME AT NOON ON SATURDAY?
<P>
A WHOLE BUNCH OF PEOPLE MOVE VERY QUICKLY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=141SJ-arena-guts>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SJ-arena-guts</H3><BR>
WELCOME TO "THE BOMB."  AN ANNUAL CONCERT FEATURING BIG NAME RAP GROUPS.
<P>
WE ARRIVED AT THE SAN JOSE ARENA JUST IN TIME TO CATCH THE LAST ACT.
<P>
OKAY. IT'S NOT "SMOOTH JAZZ". BUT EVERYONE ELSE SEEMS TO DIG IT.
<P>
WHAT THE THOUSANDS OF DANCING RAP FANS MAY NOT KNOW IS THAT BENEATH THEM. LIES N-H-L ICE.
<P>
AND IN 12 HOURS THERE WILL BE NO FOLDING CHAIRS. NO STAGE. NO LOUD MUSIC.
<P>
AT 12-NOON. THE SAN JOSE SHARKS TAKE ON THE COLORADO AVALANCHE.  
<P>
THE INSTANT TONIGHT'S SHOW ENDS. THE CLOCK STARTS TICKING.
<P>
SCORES OF STAGE HANDS. 
<P>
.CLEANING PERSONNEL.  
<P>
. AND ICE SPECIALISTS MOVE INTO ACTION.
<P>
AND WHILE THE "BOARDS" GO UP. EVERYTHING ELSE HAS TO GO.
<P>
"WE'RE LOOKING AT ABOUT THREE HOURS."
<P>
THREE HOURS TO CLEAR AND BREAKDOWN THE STAGE. REMOVE ALL THE LIGHTING AND SOUND EQUIPMENT. AND REMOVE THE 435 INSULATION PANELS WHICH COVER THE ICE.
<P>
THAT'S RIGHT. THE ICE IS ALWAYS THERE. NO MATTER WHAT'S GOING ON ABOVE.
<P>
THE CONCERT HAS BEEN OVER FOR ABOUT 20 MINUTES. AND ALREADY. THE 25-HUNDRED FOLDING CHAIRS ARE STACKED AND ON THEIR WAY OUT.   .REVEALING THAT RAP FANS ENJOY SODA AND NACHOS AS MUCH AS ANYBODY ELSE. AND THAT'S NOT ALL.
<P>
"BEER. YOU NAME IT WE GOT IT."
<P>
THE STAGE HANDS' JOB CAN BE A BIT MORE COMPLICATED.
<P>
"HOW MUCH CABLE WILL YOU ROLL TONIGHT?"  "A WHOLE BUNCH MAN. A WHOLE BUNCH."
<P>
THE SOUND CREW IS CONSTANTLY PROVING NEWTON'S LAW. WHAT GOES UP. MUST COME DOWN.
<P>
"YEA. IT MAKES FOR A LONG DAY.  YOU START AT 7A.M. IT'S MIDNIGHT NOW. WE'LL JUST KEEP ON GOING, LOAD TRUCK UP.  I'LL DRIVE BACK TO SAN DIEGO TONIGHT."
<P>
"THIS IS ONE OF THE LONELIEST PLACES IN THE SAN JOSE ARENA. BUT IT'S NOT FOR THE FAINT OF HEART AND YOU BETTER NOT BE AFRAID OF HEIGHTS.  THAT'S BECAUSE WE'RE IN THE CATWALKS ABOUT A HUNDRED FEET ABOVE THE ARENA FLOOR.  IT'S THE PLACE WHERE TWO OF THE BRAVEST, IF NOT CRAZIEST CREW MEMBERS DO THEIR JOB."
<P>
BRETT BARCLAY IS DERIGGING THE TONS OF CONCERT EQUIPMENT FROM THE RAFTERS.
<P>
HE LOOKS PRETTY CALM CONSIDERING A FEW YEARS BACK. HE ACTUALLY TOOK A FALL.
<P>
"STRETCHED ROPE SUCKED UP. HIT CEMENT."
<P>
ALAN:  "HOW FAR?"
<P>
BRETT:  "65 FEET.  I BROKE LEG, HEEL, ARM."
<P>
ALAN:  "YET HERE YOU ARE."
<P>
BRETT:  "YEP!  GET OVER IT.  IT HAPPENS."
<P>
THE CLEANING CREW'S JOB IS ALMOST FINISHED. AND THE PLACE IS BEGINNING TO LOOK MORE LIKE A HOCKEY ARENA.
<P>
THE TECHNICAL CREWS HAVE PACKED UP AND ARE ON THEIR WAY OUT.
<P>
ALL THOSE INSULATION PANELS ARE ON THEIR WAY OUT TOO.  
<P>
"SHARKY'S" BEEN ASSEMBLED. AND LIFTED INTO PLACE.
<P>
BY 4:05 A.M. THE ICE IS CLEAR.
<P>
AND THANKS TO A POWERFUL COOLING SYSTEM THAT RUNS THROUGH THE CEMENT FLOOR..THE ICE IS STILL THERE. THREE-QUARTERS OF AN INCH THICK. AND ABOUT 12 DEGREES.
<P>
FINALLY THE LAST PIECE OF THE BOARDS GOES INTO PLACE.  AND OUT COMES THE ZAMBONI.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=142SJ-arena-tag>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>SJ-arena-tag</H3><BR>
THE SHARKS DID LOOSE THAT GAME BACK ON MARCH 21ST.
<P>
BUT IT DOESN'T MATTER 'CUZ THEY'RE IN THE PLAYOFFS.
<P>
WITH A WIN TOMORROW NIGHT AT THE "SHARK TANK" THEY CAN EVEN THIS SERIES WITH DALLAS AT TWO WINS A PIECE.
<P>
TOMORROW NIGHT AT TEN. WE WALK THE TRACKS OF THE SANTA CRUZ BEACH BOARDWALK'S "GIANT DIPPER."
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=121TZ/Toss to Sandhya>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>TZ/Toss to Sandhya</H3><BR>
COMING UP A LITTLE LATER.
<P>
THE POST OFFICE GIVES THE STAMP OF APPROVAL TO SYLVESTER THE CAT AND TWEETY BIRD.
<P>
BUT FIRST WE'LL GO TO SANDHYA IN THE WEATHER CENTER FOR A PREVIEW OF TONIGHT'S WEATHER FORECAST.
<P>
SANDHYA.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=40Giants>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Giants</H3><BR>
LAST WEDNESDAY DANNY DARWIN DUKED IT OUT WITH BARRY BONDS, TONITE HE BATTLES THE PITTTSBURGH PIRATES.
<P>
THE GIANTS ARE LOOKING TO BUILD SOME MOMENTUM FOLLOWING YESTERDAY'S DRAMATIC COME FROM BEHIND WIN.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=42A's>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>A's</H3><BR>
THE A'S MEANWHILE VISIT THE EXPANSION TAMPA BAY DEVIL RAYS, AND PLAY IN THE NEW TROPICANA DOME FOR THE FIRST TIME TONITE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=44NBA Playoffs>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>NBA Playoffs</H3><BR>
ANTWAIN JAMISON IS HOPING TO BE THE NBA'S ROOKIE OF THE YEAR NEXT SEASON. THE JOHN WOODEN AWARD WINNER HAS ANNOUNCED HE'LL FORGO HIS SENIOR SEASON AT NORTH CAROLINA TO ENTER THE DRAFT.
<P>
MEANWHILE TODAY SAN ANTONIO'S TIM DUNCAN WAS RUNAWAY WINNER FOR THIS SEASON'S ROOKIE OF THE YEAR.
<P>
HIS SPURS HOST THE SUNS IN GAME THREE OF THEIR SERIES TONITE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=143Sharks>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sharks</H3><BR>
THE SHARKS HAVE THE NIGHT OFF AFTER BEATING THE DALLAS STARS ON SUNDAY.THEIR 1ST PLAYOFF VICTORY IN 3 YEARS.
<P>
THE TEAL AND BLACK ARE DOWN 2-1 IN THEIR BEST OF SEVEN SERIES, WITH GAME FOUR TUESDAY IN SAN JOSE.
<P>
SUNDAY'S GAME WAS PHYSICAL ONCE AGAIN. WITH THE STARS GETTING HIT WITH 20 PENALTIES RESULTING IN 14 POWERPLAYS FOR THE SHARKS. GOALIE EDDIE BELFOUR EVEN WENT SO FAR AS TO KICK.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=98Golf: Saving Strokes>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Golf: Saving Strokes</H3><BR>
AND FINALLY, IF YOU SPEND MORE TIME IN THE BUNKER THAN EVA BRAUN, BRUCE LEWIS CAN HELP.
<P>
TIME NOW FOR SAVING STROKES AT SAN JUAN OAKS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=50Sly & Tweety stamp>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Sly & Tweety stamp</H3><BR>
IF YOU THOUGHT YOU SAW A "PUDDY TAT" AND A BIRD ON A  POSTAGE STAMP --   YOU DID. YOU DID.
<P>
THE U-S POSTAL SERVICE HAS UNVEILED A NEW STAMP HONORING THAT CARTOON FELINE-AND-CANARY DUO, "SYLVESTER AND TWEETY". 
<P>
THE STAMP CEREMONY TOOK PLACE AT  A NEW WARNER BROTHERS THEME STORE.WHICH NOW BRIGHTENS UP A CORNER IN THE BIG APPLE'S TIMES SQUARE WITH ITS ANIMATION HALL-OF-FAME. 
<P>
IT'S ONLY THE SECOND TIME CARTOON CHARACTERS HAVE APPEARED ON A POSTAGE STAMP.THE FIRST WAS BUGS BUNNY.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER>
</BODY>
</HTML>
