<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Family Talk</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD class="a">
<IMG SRC="../images/eyeonthismorning2.GIF" WIDTH=350 HEIGHT=75 BORDER=0><BR><BR>

<CENTER><IMG SRC="../images/familytalk.GIF" WIDTH=51 HEIGHT=75 BORDER=0 ALT="Family Talk"></CENTER><BR><BR>
Family Talk


<BR><BR>
<!--#include file="../footer.inc" -->
</TD></TR></TABLE>

</BODY>
</HTML>
