<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Grocery Guy</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD class="a">
<IMG SRC="../images/eyeonthismorning2.gif" WIDTH=350 HEIGHT=75 BORDER=0 ALT="The Grocery Guy"><BR><BR>

<center><img src="../images/grocery.gif" width=100 height=75 border=0 alt=""></center><br><br>


The Grocery Guy


<BR><BR>
<!--#include file="../footer.inc" -->

</TD></TR></TABLE>

</BODY>
</HTML>
