<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KION Travel Advice</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../images/travelstore.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>
This Function is not yet online.<br><br>

<a href="travelstore.asp"><strong>Return to the KION Travelstore</strong></a>
<br><BR><BR>
<!--#include file="../footer.inc" -->
</TD></TR>
</TABLE>
</BODY>
</HTML>
