<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KION Travel Package Purchase Form</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../images/travelstore.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>


When you submit this form, our database will check the availability of reservations on the requested date you will recieve a response informing you of availability and connecting you to a secure server from which you may purchase your vacation.<br><br>
<form action="buynow2.asp" method="POST">
<table>
<tr><td class=a><strong>First Name:</strong><br>
<input type="Text" name="firstname" align="LEFT" size="10"></td>
<td class=a colspan="2" rowspan="2"><a href="http://www.americanair.com" target="_top"><img src="travel/aalogo.gif" width=150 height=82 border=0 alt=""></a></td></tr>
<tr><td class=a><strong>Last Name:</strong><br>
<input type="Text" name="lastname" size="20"></td></tr>
<tr><td class=a colspan="3"><strong>Email Address:</strong><br>
<input type="Text" name="email" size="30"><br>
<strong>Street Address:</strong><br>
<input type="Text" size="30" name="streetaddress"><br>
<strong>Street Address 2:</strong><br>
<input type="Text" name="" size="30"></td></tr>
<tr><td class=a><strong>City:</strong><br>
<input type="Text" name="city" size="20"></td>
<td class=a><strong>State:</strong><br>
<input type="Text" name="state" size="2"></td>
<td class=a><strong>Zip:</strong><br>
<input type="Text" name="zip" size="5"></td></tr>

<tr><td class=a><strong>Desired Package:</strong><br>
<select name="package">
<option value="costarica" selected>Costa Rica
<option value="hawaii">Hawaii
<option value="spain">Spain
</select></td>

<td class=a colspan="2"><strong>Desired Departure Date:</strong><br>
<select name="date">
<option value="jan">Jan
<option value="feb">Feb
<option value="mar">Mar
<option value="apr">Apr
<option value="may">May
<option value="jun">Jun
<option value="jul">Jul
<option value="aug">Aug
<option value="sep">Sep
<option value="oct">Oct
<option value="nov">Now
<option value="dec">Dec
</select>
<select name="day">
   <option>1
   <option>2
   <option>3
   <option>4
   <option>5
   <option>6
   <option>7
   <option>8
   <option>9
   <option>10
   <option>11
   <option>12
   <option>13
   <option>14
   <option>15
   <option>16
   <option>17
   <option>18
   <option>19
   <option>20
   <option>21
   <option>22
   <option>23
   <option>24
   <option>25
   <option>26
   <option>27
   <option>28
   <option>29
   <option>30
   <option>31
</select></td></tr>
<tr><td class=a colspan="3"><input type="Checkbox" name="letmeknow" checked>Let me know about other vacation Packages<br>
<input type="Submit" name="buy"><input type="reset"></td></tr>


</table>
</form>

<br><BR><BR>
<!--#include file="../footer.inc" -->
</TD></TR>
</TABLE>
</BODY>
</HTML>
