<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Travel Package Response</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../images/travelstore.GIF" WIDTH=400 HEIGHT=54 BORDER=0>
<center><h2>This function is not yet online.</h2></center><br>

<a href="travelstore.asp">Back to the KION Travelstore</a>

<br><BR><BR>
<!--#include file="../footer.inc" -->
</TD></TR>
</TABLE>
</BODY>
</HTML>
