<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Ordering</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a ALIGN="CENTER">
<IMG SRC="../images/bookstore.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>
Sorry, this area is not yet available.<br><br>
<A HREF="bookstore.asp">Return to the Bookstore</A>

<!--#include file="../footer.inc" -->
</TD></TR>
</TABLE>

</BODY>
</HTML>
