<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KION Travelstore Packages</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../images/travelstore.GIF" WIDTH=400 HEIGHT=54 BORDER=0>

<center><h1>Travel Packages</h1></center>

<center><h3>Costa Rica Vacation</h3></center>
The KION Travelstore, in partnership with American Airlines, and the Buena Vista Hotel has put together a fantastic vacation package to <strong>Costa Rica</strong><br><br>


<img src="travel/buenavista.jpg" width=200 height=118 alt="" border=0 align="right">
<strong><u>The package includes:</u></strong><br>
<UL>
<LI>Roundtrip Airfare on American Airlines.
<LI>5 days/ 4 nights at the <a href="http://www.arweb.com/buenavista/" target="_blank">Buena Vista Hotel</a> outside of San Jose.
<LI>Tour of Poás volcano.
<LI>Tour of the Cafe Tierra coffee plantation.
</UL><br clear=left>

<center><strong><u>Package Price:</u> $950.</strong></center><br>

<center><strong><a href="buynow.asp">Buy Now</a> &nbsp;&nbsp;<a href="letmeknow.asp">Other Packages</a></strong></center>




<br><BR><BR>
<!--#include file="../footer.inc" -->
</TD></TR>
</TABLE>



</BODY>
</HTML>
