<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Murphy Brown</TITLE>
<!--#include file="../style2.inc" -->


</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">
<table width="400" border="0" cellspacing="0" cellpadding="5"><TR><TD class=a>
<IMG SRC="../images/murphybrown.gif" WIDTH=400 HEIGHT=54 BORDER=0 alt="">
<br><br>
<h2>Next Episode:</h2>



<img src="show2.jpg" width=163 height=200 alt="" border=0 align="right">
"<B>I Hear a Symphony</B>" - December 10<br><br>



<B>Olivia Newton-John</B> Guest Stars as Herself<br><br>



Murphy's bout with cancer has her thinking a lot about the things she'd like to do - climb Mount Everest, memorize all the words to <I>American Pie,</I> and learn how to juggle. When Corky tells her that a charity auction is offering the chance to conduct a symphony orchestra, Murphy adds "maestro for an evening" to the list. But, once at the auction, she receives heavy one-on-one competition from overzealous bidder <B>Olivia Newton-John.</B><br><br> 



To obtain a <I>Murphy Brown</I> brochure that will answer basic questions about breast cancer detection, diagnosis and treatment, contact the American Cancer Society at 1-800-ACS-2345 or consult their Web site at <A HREF="http://www.cancer.org">www.cancer.org</A>.<br><br>

<strong>Take the KION Murphy Brown <a href="quiz.asp">Trivia Quiz</a></strong><br><br>

<strong><u>Links to other Murphy Brown sites:</u></strong><br>





Murphy Brown <a href="http://www.xnet.com/~djk/MurphyBrown_2.shtml">Episode Guide</a><br>
<a href="http://updateit.qdeck.com/~gundersn/murphy_main.asp">My Day on the Set</a> of Murphy Brown<br>
<a href="http://members.aol.com/murphypage/index.htm">The (Un)Official</a> Murphy Brown Homepage<br>
<a href="http://www.virtuallot.com/cmp/comedy/cm09.htm">Warner Brothers</a> Murphy Brown site<br>

<a href="http://www.oncolink.upenn.edu/psychosocial/books/murphy_brown.html">Oncolink</a> review of Murphy's battle with breast cancer<br>

<!--#include file="../footer.inc" -->

</td></tr></table>
</BODY>
</HTML>
