<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Eyewitness News</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD class="a">
<IMG SRC="../images/eyeonjobs.gif" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<h3><a href="post.asp">Post your resume online.</a></h3>

<h3><a href="search.asp">Search job opportunities.</A></h3>

<B><a href="westech.htm" target="_top">Westech</a></B> - Check out job opportunities in high-tech via our partner, Westech, home of 
the Virtual Job Fair." 
<br><br><br>



<!--#include file="../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>
