<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Andrew Amador</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD>
<IMG SRC="../../images/teambios.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<CENTER>
<H1>Andrew Amador</H1>
<H2>News Anchor</H2> 
<H3>KION 46 Eyewitness News at 5</H3></CENTER>

<img src="../../images/personel/andrew_amador.jpg" width=168 height=200 border=0 align="right" alt="">
<P>Birth Place:		San Francisco, CA</P>

<P>Education:		BA/CSU, Long Beach - Graduate Studies/CSU, Fullerton</P>

<P>Special interests:  	Tennis, Theatre</P>

<p>It was Walter Cronkite's depiction of the events surrounding the assassination of John F. Kennedy that prompted Andrew's first interest in journalism.</p>
 
<p>During his nearly 30 year career, Andrew has worked for major broadcast news operations in Los Angeles, San Francisco and Detroit.</p>

<p>He  spent eight years as a Reporter/Anchor for KCAL-TV in Los Angeles and, in the early 1990's, he was a network anchor for CBS Radio News during the Gulf War.</p>

<p>On the showbiz side, Andrew has appeared in many television series including "Murder She Wrote" and "Dallas."  He has had feature roles in the theatrical releases:, "L.A. Story", "Taking Care Of Business", "The Net" and "First Power."</p>

<p>Andrew is a native Californian and has spent much of his broadcasting career here in the golden state.  He  loves the Central Coast and now calls Carmel-By-The-Sea "Home".</p>

<p>You can see Andrew at work every weekday as he anchors the KION 46 First at Five newscast.</p>

<BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>
