<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Barry Brown</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD>
<IMG SRC="../../images/teambios.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>
<CENTER>
<H1>BARRY BROWN</H1>
<H2>Meteorologist</H2>
<H3>Executive Producer / Anchor<BR>
 KION 46 "Eye On This Morning"</H3>
 </CENTER>


<img src="../../images/personel/barry_brown.jpg" width=140 height=200 alt="" border=0 align="right">
<P>Birth Place: Oakland, California</P>
<P>Education: University of Southern California</P>
<P>Special Interests: Golf, Baseball, Art</P>

<P>With visions of playing Beatles records on the air, Barry Brown began his radio career announcing "Lost Dog Reports" on a small station in Petaluma, California.</P>
       
<P>Eventually he got to play those Beatles records--along with the Rolling Stones, Supremes, Eagles and Doobie Brothers--at KIDD Radio in Monterey, California.  It was there he was dubbed "Downtown Barry Brown," a nickname which continues to follow him even today.</P>
       
<P>In 1983, he moved from radio to television when he became the weatherman at KMST  television in Monterey.  Two years later, he joined the NBC affiliate in Sacramento as a weathercaster and feature reporter.  in 1988 he took a similar position at KOFY TV in San Francisco.  In 1991, he returned to the central coast of California, where he forecasted the weather for KCBA Fox 35 until making the switch to KION in 1996.</P>
      
<P>Barry holds a degree in Broadcast Journalism from the University of Southern California and a certificate in Broadcast Meteorology from Mississippi State University. He is a member of the National Weather Association and has earned that organization's Seal of Approval.  He is executive producer and anchor for "Eye On This Morning" on KION CBS 46.   He lives in Salinas with his wife Sue and their two children, Matthew and Carolyn.</P>

<BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>

