<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Colleen Odegaard</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD>
<IMG SRC="../../images/teambios.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>



<CENTER><H1>COLLEEN ODEGAARD</H1>
<H2>News Anchor</H2>
<H3>KION 46 "Eye on This Morning"</H3></CENTER>


<img src="../../images/personel/colleen_odegaard.jpg" width=152 height=200 alt="" border=0 align="right">
<P>Birth Place:           Ridgewood, New Jersey</P>

<P>Education:             San Jose State University</P>

<P>Special interests:   Music, Reading, Biking</P>

<P>Raised in  San Jose, California,  Colleen decided  to stay in the area to attend San Jose State University.  During college, she worked as an intern in the news department at KNTV in San Jose.  Her  internship led to a position in the KNTV Production department where she gained first hand experience producing newscasts.  Working behind the cameras and shining the light on others helped to shed light on her real desire...to be in front of the camera.</P>
<P>Colleen didn't waste any time pursuing her goal.  In 1992, three days after graduating from  San Jose State University with a degree in Broadcast Journalism, she moved to Laredo Texas where she was news anchor  and producer for a local television station until 1993.  Texas hadn't seen the last of  Colleen though.  She spent the next year as a reporter and photographer for  a station in Lubbock Texas.  </P>
<P>In 1994, Colleen decided it was time to return home.  She joined the team at KCBA FOX 35 in August as weekend anchor / reporter, and was soon promoted to main anchor for KCBA Fox News At Ten.  She joined KION in March of 1997 and currently Anchors KION "Eye On This Morning", and Eyewitness News at Noon.</P>
<P>Colleen lives on the Monterey Peninsula, an area she calls "One of the most beautiful places on earth." It's not uncommon to see her around town enjoying the weather and the people in her community!</P>
<BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>


