<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Ed Bradford</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../../images/teambios.gif" WIDTH=400 HEIGHT=54 BORDER=0 alt=""><BR><BR>
<CENTER>
<H1>ED BRADFORD</H1>
<H2>News Anchor</H2>
<H3>KION 46 Eyewitness News at Noon</H3>
 </CENTER>

<img src="../../images/personel/ed_bradford.jpg" width=161 height=200 border=0 alt="" align="right">
<p>Birth Place: Gary, Indiana</p>
<p>Education:  Arizona State University</p>
<p>Special Interests:  Hiking, Tennis, Antiques</p>


<p>As the most experienced News Anchor on the Central Coast, Ed Bradford brings more than 22 years of Television broadcast experience to KION.  He has spent his career covering the news everywhere from Panama City, Florida, to Phoenix, Arizona, to Colorado Springs, Colorado. </p> 

<p>He has been honored for his outstanding performance as a field reporter and feature reporter on numerous occasions, including the 1996 Central Coast  Press Club Award for best feature reporting for a story about the International Big Sur Marathon, entitled "magnificent Marathon."  He was also active in reporting on the problems of  Native Americans in Arizona and received an Emmy Award nomination for a series of investigative reports on that subject.</p>

<p>Ed joined the Eyewitness News team in June of 1996 after many years of solid performance as both reporter and anchor.  He enjoys His home on the coast, in Pacific Grove. </p> 




<br><BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR>
</TABLE>
</BODY>
</HTML>
