<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Elsa Ramon</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../../images/teambios.gif" WIDTH=400 HEIGHT=54 BORDER=0 alt=""><BR><BR>
<center><h1>Elsa Ramon</h1>
<h2>News Anchor</h2>
<h3>KION 46 Eyewitness News at 5</h3></center>
<img src="../../images/personel/elsa_ramon.jpg" width=159 height=200 border=0 alt="" align="right">

<p>Birth Place: Hollywood, California</p>
<p>Education:   University of California, Irvine</p>
<p>Special Interests: Skiing, Rollerblading, camping</p>

<p>The "News Bug" bit Elsa Ramon early.   At the age of eleven,
She was chosen to be a kid reporter for a children's news program called "Kids World".   Elsa reported for the Austin, Texas based program for one year.</p>

<p>Elsa was born in Hollywood, and grew up in Venice, California.  She remained in the Southern California area to attend the University of California at Irvine, where she earned her Bachelor of Arts degree in English Literature.</p>

<p>Before joining the KION 46 Eyewitness News team, Elsa worked for KNBC - Los Angeles as a field producer and production assistant on special series projects such as the O.J.  Simpson trial.</p>

<p>Elsa currently reports for KION 46 Eyewitness News, and anchors the nightly Five O'clock Newscast.  She spends her free time at home in Santa Cruz, where the beautiful coastal setting allows her to enjoy her favorite outdoor activities, rollerblading and camping. </p>

<br><BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR>
</TABLE>
</BODY>
</HTML>
