<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Gary Butterworth</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../../images/teambios.gif" WIDTH=400 HEIGHT=54 BORDER=0 alt=""><BR><BR>
<center><h1>Gary Butterworth</h1>
<h2>KION CBS 46 Meteorologist</h2>
</center>

<img src="../../images/personel/gary_butterworth.jpg" width=145 height=200 border=0 alt="" align="right">
<p>Birth Place:  Santa Monica, California</p>
<p>Education:   San Diego State/ Mississippi State University</p>
<p>Special Interests:  Tennis, Beach Volleyball, reading</p>

<p>Gary Butterworth first became interested in weather during his Junior year of college, when he traveled around the world, witnessing what he calls,  "The wonders of the sky over Africa, India and Asia".</p>
<p>
Raised in Redondo Beach, California, a suburb of Los Angeles, Gary remained in Southern California to attend college at San Diego State University.  He earned a Bachelor of Arts Degree in Broadcasting, Film and Drama and still has a keen interest in film and theater.</p>  
<p>
His first experience in broadcasting was with  KACI - Radio,  in The Dalles, Oregon where he played the "Hits" as the station's "Morning Guy".
When he's not enjoying Tennis and spending time with his wife and their 2 year old son, Ryan at home in Salinas,  Gary can be found forecasting the weather each night on KION Eyewitness News at 5, 6 & 11</p>



<br><BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR>
</TABLE>
</BODY>
</HTML>
