<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Hunter Finnell</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD>
<IMG SRC="../../images/teambios.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<CENTER><H1>Hunter Finnell</H1>
<H2>Sports Director / Anchor</H2>
<H3>KION 46 Eyewitness News</H3></CENTER>

<img src="../../images/personel/hunter_finnell.jpg" width=155 height=200 border=0 align="right" alt="">
<P>Birth Place:  Calgary, Alberta, Canada</P>
<P>Education:    Southern Methodist University, Dallas</P>
<P>Special Interests:  Golf, Tennis </P>

<P>With three AP Awards for Best Sportscast under his belt, KION CBS 46 Eyewitness Sports Director, Hunter Finnell brings the Central Coast of California excellence in sports coverage.  His weekly segment, Scholar Athlete, features high school athletes who achieve greatness not only on the playing field but also in the classroom.</P>
<P>Becoming a Sports Anchor / Reporter was a dream come true for Hunter.  He was active in sports as a spectator and participant until he injured his leg in college at Vanderbilt University.  Bone cancer was diagnosed and Hunter spent the next year and a half undergoing chemotherapy and several operations.</P>
<P>He studied a semester at the University of Southern California while completing his treatment, and then  moved on to Southern Methodist University.</P>
<P>He took his first job at KECY-TV in El Centro California, and soon moved on to WBBH-TV in Ft. Myers, Fl.  A year and a half later, he headed north to Winston-Salem, NC,  where he met his future wife, Lynn.  Hunter delivered sports, and Lynn anchored the news for WXII-TV.  In 1989, Hunter moved to the Central Coast of California where he became Sports Director / Anchor for KMST-TV.  Lynn soon landed a job with KMST also, and joined forces with Hunter later that year.  Hunter and Lynn were married in April, of  1991.  They  live in Carmel Valley with their daughter Logan, son Skyler, and two Golden Retrievers.  Hunter is now busy as Sports Director / Anchor KION CBS 46 Eyewitness News.   </P>
      
<BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>

