<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Karina Rusk</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD>
<IMG SRC="../../images/teambios.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<CENTER>
<H1>Karina Rusk</H1>
<H2>News Anchor</H2>
<H3>KION 46 Eyewitness News at 6 & 11 pm</H3></CENTER>

<img src="../../images/personel/karina_rusk.jpg" width=158 height=200 border=0 align="right" alt="">
<P>Birth Place: Santa Cruz California</P>
<P>Education:  California State University, Chico</P>
<P>Special Interests:  Cooking, Hiking, Travelling and Writing</P>

<P>As News Anchor for KION 46 Eyewitness News at Six, Karina Rusk enjoys exploring the issues important to California's Central Coast and taking an active role in community activities.</P>
<P>Karina was born in Santa Cruz.  She has lived in California all her life and now calls Monterey County 'home'.</P>
<P>After graduating form Chico State University with a degree in Broadcast Journalism, Karina began her career working in television news.  Before coming to the Central Coast, she worked at several stations including KCPM in Chico, KTEH in San Jose and KOVR in Sacramento.</P>
<P>Karina joined KCCN in 1990 as a general assignment reporter and currently anchors the Six o'clock newscast for KION 46 Eyewitness News.  She considers the Central Coast a very special place to live and work and is involved with a number of local non-profit agencies.  As a board member for the Volunteer Center of Monterey County, Karina encourages everyone to volunteer.  She says, "There are so many worthy organizations on the Central Coast.  People really appreciate it when you give of yourself and volunteer your time.  It's not only a learning experience but extremely rewarding."</P>

<BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>

