<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Gary Butterworth</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../../images/teambios.gif" WIDTH=400 HEIGHT=54 BORDER=0 alt=""><BR><BR>
<center><h1>Romney Dunbar</h1>
<h2>News Anchor</h2>
<h3>KION 46 Eyewitness News at 6 & 11</h3></center>
<img src="../../images/personel/romney_dunbar.jpg" width=183 height=200 border=0 alt="" align="right">

<p>Birth Place:  San Francisco, California</p>
<p>Education:   University of Montana</p>
<p>Special Interests:  Skiing, Music, in-line skating, cycling</p>


<p>Romney Dunbar has been covering news on the Central Coast for nearly fifteen years.  His first broadcasting experience was in radio during high school in Montana.  He continued working in radio while attending college at the University of Montana in Missoula, and eventually made the switch to television.  He moved to the Central Coast of California in 1983 and has been a well-known  member of the local news community ever since.</p>

<p>Romney spends much of his free time enjoying outdoor activities like skiing, in-line skating and cycling.  He and his wife Priscilla enjoy an active life in Santa Cruz County where there are plenty of cycling trails and scenic skate paths.</p>


<br><BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR>
</TABLE>
</BODY>
</HTML>
