<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KION News Team</TITLE>
<!--#include file="../../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD>
<IMG SRC="../../images/teambios.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<center>
<% if 1 = 2 then %>
<IMG SRC="../../images/newsteam.jpg" WIDTH=319 HEIGHT=192 BORDER=0 ALT=""><BR>
<EM>Your Central Coast News Team</EM><BR><BR>
<% end if %>
<table>
<tr><td width="200" align="CENTER" valign="TOP" class="a"><a href="barry.asp"><img src="../../images/personel/smallbarry.jpg" width=50 height=75 alt="" border=0><br>
Barry Brown</a><BR>
Eye On This Morning Anchor/Meteorologist<BR>
Weekdays 6am-9am & Noon
<br><br></td>

<td align="CENTER" valign="top" class="a"><a href="colleen.asp"><img src="../../images/personel/smallcolleen.jpg" width=54 height=75 alt="" border=0><br>
Colleen Odegaard</a><BR>
Eye On This Morning Anchor<BR>
Weekdays 6am-9am & Noon
<br><br></td></tr>

<tr>
<td width="200" align="CENTER" valign="TOP" class="a"><a href="andy.asp"><img src="../../images/personel/smallandy.jpg" width=54 height=75 alt="" border=0><br>
Andrew Amador</a><BR>
Eyewitness News Anchor<BR>
Weeknights at 5pm
<br><br></td>

<td width="200" align="CENTER" valign="TOP" class="a"><a href="karina.asp"><img src="../../images/personel/smallkarina.jpg" width=54 height=75 alt="" border=0><br>
Karina Rusk</a><BR>
Eyewitness News Anchor<BR>
Weeknights at 6pm & 11pm
<br><br></td></tr>

<tr>
<td align="CENTER" valign="TOP" class="a"><a href="romney.asp"><img src="../../images/personel/smallromney.jpg" width=58 height=75 border=0 alt=""><br>
Romney Dunbar</a><BR>
Eyewitness News Anchor<BR>
Weeknights at 6pm & 11pm
<BR><BR></td>

<td width="200" align="CENTER" valign="TOP" class="a"><a href="hunter.asp"><img src="../../images/personel/smallhunter.jpg" width=54 height=75 alt="" border=0><br>
Hunter Finnell</a><BR>
Eyewitness Sports Anchor<BR>
Weeknights at 5pm, 6pm & 11pm
<br><br></td>
</tr>

<tr>
<td align="CENTER" valign="TOP" class="a"><a href="gary.asp"><img src="../../images/personel/smallgary.jpg" width=54 height=75 alt="" border="0"><br>
Gary Butterworth</a><BR>
Eyewitness Meteorologist<BR>
Weeknights at 5pm, 6pm & 11pm
<br><br></td>

<td align="CENTER" valign="TOP" class="a"><a href="ed.asp"><img src="../../images/personel/smalled.jpg" width=54 height=75 border=0 alt=""><br>
Ed Bradford</a><BR>
Eyewitness News Anchor<BR>
Weekdays at Noon
<BR><BR></td>
</tr>

<TR>
</tr>

</table></center>



<BR><BR>
<!--#include file="../../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>
