<% if day(date) = 11 then %>
	<Table><TR><TD valign="TOP"><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_freestyle2.jpg" align="left" border=0 ></A></TD>
	<TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>(7-9 a.m. PT, 8-11 p.m. PT and 12:35-3 a.m. PT) Freestyle skiing (men's and women's), alpine skiing (Men's Combined Slalom), luge (women's), speed skating (women's) and a preview of men's figure skating will be shown. 
</TD></TR></TABLE><br><br>

<% elseif day(date) = 12 then %>
	<Table><TR><TD valign="TOP"><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_figureskate.jpg" align="left" border=0 ></A></TD>
	<TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(7-9 a.m. PT and 8-11 p.m. PT and 12:35-3 a.m. PT) -- The men's figure skating short program will highlight the primetime broadcast which will also include continued coverage of alpine skiing (Men's Super G), speed skating (men's), cross-country skiing (men's and women's), snowboarding (men's and women's) and previews of men's ice hockey and the women's downhill event. Late night coverage will feature live men's ice hockey as USA plays its first game in the "Dream Tournament" against Sweden. 
</TD></TR></TABLE><br><br>

<% elseif day(date) = 13 then %>
	<Table><TR><TD valign="TOP"><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_downhill.jpg" align="left" border=0></A></TD>
	<TD align="CENTER" valign="TOP" class=b><strong><a href="<!--#include file="dailylink2.inc"-->" target="main">XVIII Olympic Winter Games</strong><br></A>
	(7-9 a.m. PT, 8-11 p.m. PT and 12:35-3 a.m. PT) More live action will be seen with the women's downhill event and late night coverage of USA's second game of the "Dream. Tournament" in men's ice hockey. Other events in prime time will include figure skating (ice dancing), speed skating (women's), luge (doubles) and a men's ice hockey report. </TD></TR></TABLE><br><br>

<% elseif day(date) = 14 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_whockey.jpg" border=0 hspace=5 vspace=5 align="left" alt=""></A>
	<strong><a href="<!--#include file="dailylink2.inc"-->" target="main">XVIII Olympic Winter Games</strong><br></A>
	(11:30 a.m.-3 p.m. PT, 7-11 p.m. PT and 11:35 p.m.-2 a.m. PT) -- Primetime coverage features men's figure skating long program. The weekend daytime coverage will continue with men's and women's ice hockey (Sweden vs. Canada/Canada vs. USA, respectively) and nordic combined. Primetime coverage also will show alpine skiing (Women's Combined Downhill), speed skating (women's), cross-country skiing (men's), bobsled (two-man) and men's and women's ice hockey reports. Men's ice hockey (Russia vs. Finland) will be broadcast in late night.
	</TD></TR></TABLE><br><br>

<% elseif day(date) = 15 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_speedskate.jpg" align="left" hspace=5 vspace=5 align="left" border=0 ></A>
	<a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(1-3 p.m. PT, 8-11 p.m. PT and 11:35 p.m.-2 a.m. PT) -- The primetime broadcast will show figure skating (ice dancing -- Original program), bobsled (two-man) and speed skating (men's). The afternoon will showcase men's ice hockey and figure skating (men's review and ice dancing preview). Late night men's ice hockey action will see a rematch of the World Cup hockey tournament as Canada takes on the USA.
	</TD></TR></TABLE><br><br>

<% elseif day(date) = 16 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_figureskate.jpg" border=0 hspace=5 vspace=5 align="left"></A>
	<strong><a href="<!--#include file="dailylink2.inc"-->" target="main">XVIII Olympic Winter Games</strong><br></A>
	(7-9 a.m. PT, noon-5 p.m. PT, 8-11:30 p.m. PT and 1:05-3:30 a.m. PT) -- Figure skating (ice dancing -- long program), speed skating (women's), freestyle skiing (men's and women's), ski jumping and cross-country skiing (women's) will be shown in prime time. Additional weekday coverage due to the President's Day holiday will include men's ice hockey and cross-country skiing (women's) in the afternoon.  </TD></TR></TABLE><br><br>

<% elseif day(date) = 17 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_freestyle2.jpg" hspace=5 vspace=5 align="left" border=0 ></A>
	<a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(7-9 a.m. PT, 8-11 p.m. PT and 12:35-3 a.m. PT) -- Freestyle skiing (men's and women's) will be highlighted in prime time. Also broadcast in prime time will be a preview of ladies figure skating, alpine skiing (Women's Combined Slalom), short track speed skating (men's and women's), speed skating (men's) and a wrap-up of women's ice hockey. The late night broadcast will show quarterfinal action in men's ice hockey.
	</TD></TR></TABLE><br><br>

<% elseif day(date) = 18 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_figureskate2.jpg" hspace=5 vspace=5 align="left" border=0 ></A>
	<a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(1-3 p.m. PT, 8-11 p.m. PT and 11:35 p.m.-2 a.m. PT) -- The primetime broadcast will show figure skating (ice dancing -- Original program), bobsled (two-man) and speed skating (men's). The afternoon will showcase men's ice hockey and figure skating (men's review and ice dancing preview). Late night men's ice hockey action will see a rematch of the World Cup hockey tournament as Canada takes on the USA.
	</TD></TR></TABLE><br><br>

<% elseif day(date) = 19 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_wfigureskate.jpg" hspace=5 vspace=5 align="left" border=0 ></A>
	<a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(7-9 a.m. PT, 8-11 p.m. PT and 12:35-3 a.m. PT) -- A preview of the ladies figure skating long program will be shown in prime time with alpine skiing (Women's Slalom), speed skating (women's), short track speed skating (men's and women's) and nordic combined. Semifinal men's ice hockey action will face-off live in late night.
	</TD></TR></TABLE><br><br>

<% elseif day(date) = 20 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_xcountry.jpg" hspace=5 vspace=5 align="left" border=0 ></A>
	<a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(7-9 a.m. PT, 8-11:30 p.m. PT, 1:05-3:30 a.m. PT) -- Alpine skiing (Women's GS), bobsled (four-man), cross-country skiing (women's) and a men's ice hockey report also will be shown. Men's ice hockey featuring the bronze medal game will be shown during the late night broadcast.
	</TD></TR></TABLE><br><br>

<% elseif day(date) = 21 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/oly_biatholon.jpg" hspace=5 vspace=5 align="left" border=0 ></A>
	<a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(10 a.m.-3 p.m. PT, 7-11 p.m. PT and 11:35 p.m.-2 a.m. PT) -- Prime time will feature special performances by figure skating's medal winners, alpine skiing (Men's Slalom), bobsled (four-man) and short track speed skating (men's and women's). Final weekend broadcasts will begin with speed skating (women's), nordic combined, biathlon (men's), alpine skiing (Men's Slalom preview) and a recap of the figure skating events in the afternoon. Late night will showcase coverage of the gold medal men's ice hockey game.
	</TD></TR></TABLE><br><br>

<% elseif day(date) = 22 then %>
	<Table><TR><TD align="CENTER" valign="TOP" class=b><a href="<!--#include file="dailylink2.inc"-->" target="main"><img src="images/shows/Mondaythe9th_sm.jpg" hspace=5 vspace=5 align="left" border=0 ></A>
	<a href="<!--#include file="dailylink2.inc"-->" target="main"><strong>XVIII Olympic Winter Games</strong><br></A>
	(PT, 12:30-3 p.m. PT, 8-11 p.m. PT and 11:35 p.m.-12:35 a.m. PT) -- CBS Sports' final day of Olympic coverage will be highlighted by the Closing Ceremony in prime time and in the afternoon include cross-country skiing (men's), a recap of men's ice hockey and an overall review of the Games. The Network's final hour of its 128 hours of coverage will be seen in late night.
	</TD></TR></TABLE><br><br>

<% End If %>

