
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Menu</TITLE>
</HEAD>

<BODY BGCOLOR="#003071" BACKGROUND="kionback3.gif" TEXT="#FFFFFF" LINK="#D90037" VLINK="#C0C0C0" ALINK="#FF0000">
<A HREF="main.asp" TARGET="main"><IMG SRC="images/kionlogo_sm.gif" BORDER=0 ALT="KION" width=100 height=81></A><BR>

<a href="news/features.asp" target="main"><img src="images/eyewitnessmenu.gif" width=130 height=20 border=0 alt="Eyewitness News"></a><br>
<a href="programming/today_detail.asp" target="main"><img src="images/programmenu.gif" width=130 height=19 border=0 alt="Programming"></a><br>
<a href="marketplace/marketplace.asp" target="main"><img src="images/marketmenu.gif" width=130 height=18 border=0 alt="Marketplace"></a><br>
<a href="eyeonthismorning/eyeonthismorning.asp" target="main"><img src="images/morningmenu.gif" width=130 height=31 border=0 alt="Eye On This Morning"></a><br>
<a href="centralcoast/centralcoast.asp" target="main"><img src="images/centralmenu.gif" border=0 alt="Eye On The Central Coast" width=130 height=31></a><br>
<a href="weather/weather.asp" target="main"><img src="images/weathermenu.gif" width=130 height=22 border=0 alt="KION Weather"></a><br>
<a href="contact/contact.asp" target="main"><img src="images/contactmenu.gif" width=130 height=17 border=0 alt="Contact KION"></a>
<BR>
</BODY>
</HTML>

