<STYLE type="text/css">
	P {font-family: 12pt Arial, Sans-Serif; color: black}
	H1 {font-family: 16pt Arial, Sans-Serif; color: black}
	H2 {font-family: 14pt Arial, Sans-Serif; color: black}
	H3 {font-family: 12pt Arial, Sans-Serif; color: black}
	UL LI {font-family: 10pt Arial, Sans-Serif; color: black}
	TD.a {font-family: 12pt Arial, Sans-Serif; color: black}
	TD.b {font-family: 12pt Arial, Sans-Serif; color: white}
	TD.c {font-family: 14pt Arial, Sans-Serif; font-weight: bold; color: black}
	H5 {font-family: 10pt Arial, Sans-Serif; color: black}
	A {font-family: Arial, San-Serif}
	H6 {font-family 6pt Arial, Sans-Serif; font-weight: bold; color: black}
</STYLE>