
<STYLE type="text/css">
	H1 {font-family: 16pt Arial, Sans-Serif; color: white}
	H2 {font-family: 14pt Arial, Sans-Serif; color: white}
	H3 {font-family: 12pt Arial, Sans-Serif; color: white}
	P {font-family: 12pt Arial, Sans-Serif; color: white}
	UL LI {font-family: 10pt Arial, Sans-Serif; color: white}
	TD.a {font-family: 12pt Arial, Sans-Serif; color: white}
	TD.b {font-family: 10pt Arial, Sans-Serif; color: white}
</STYLE>