<html>

<head>
<title>Content</title>
<!--########################################################
//-Client: KUBE 93.3fm - Seattle
//-Created by: Digital-Sherpas (www.digital-sherpas.com)
//-Date: 9.97
//-Site-Section: You Say We Play DEFAULT CONTENT
//-Version: v.1.0
//-Developer: Steve Karr (steve@digital-sherpas.com)
//-Version: v.1.01
//-Developer: Danny Mavromatis (danny@digital-sherpas.com)
//##########################################################-->
</head>

<body background="graphics/yswp_bk.GIF" bgcolor="#FFFFFF" BGPROPERTIES="FIXED" text="#000000" link="#FF0000" vlink="#FF0000" leftmargin="0">

<form method="POST">
    <div align="center"><center><table border="0" cellpadding="0"
    cellspacing="0" width="95%">
        <tr>
            <td width="95%"><p align="center"><br>
            <font face="Arial"><strong><img
            src="graphics/YSWP_LOGOGIF.gif" width="400"
            height="63"></strong></font></p>
            <p><font face="Arial" SIZE=-1><strong>
Tell KUBE 93 what you really want to hear. 
<br><br>
Here’s a few songs KUBE 93 might add to its hit music lineup. YOU help us decide if we should. Click on the picture to hear a sample of the song, vote for your favorite, then to see which song is the fave of other KUBE 93 listeners submit your vote. One vote per poll please.
</strong></font><font
            size="2" face="Arial"><br>
            </font></p>
            </td>
        </tr>
    </table>
    </center></div><div align="center"><center><BR><table border="0"
    cellpadding="0" cellspacing="0" width="550">
	<tr>
<TD ALIGN="CENTER" VALIGN="TOP">
<!--#include file="poll.inc"-->
</TD>
</tr>
    </table>
    </center></div><p align="center"><font face="Arial"><B><I>LAST WEEK'S WINNER:</B></I><BR>
<font face="Arial"><a href="../rafiles/magoo-clockstrikes.ram"><img src="graphics/timbaland-magoo.jpg" width=100 height=100 border=0></a><br>
            </font><font size="1" face="Arial"><strong>Timbaland & Magoo<br>
            </strong>Clock Strikes<br>
            </font><font face="Arial"><br>
<P><strong><center><img
    src="graphics/YSWP_LOGOGIF.gif" width="400" height="63"></strong></font></p>
    <p align="center"><br><P><center><font face="Arial" size="1">©1998. All rights reserved.<BR>
KUBE93.COM is created and maintained by <a href="http://www.kube93.com/credits.htm" target="new">Digital Sherpas</A>.</P><BR><P></font>
    </p>
</form>
</body>
</html>
