<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>

<head>
<meta http-equiv="Content-Type"
content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 2.0">
<title>Content</title>
<!--########################################################
//-Client: KUBE 93.3fm - Seattle
//-Created by: Digital-Sherpas (www.digital-sherpas.com)
//-Date: 9.97
//-Site-Section: You Say We Play DEFAULT CONTENT
//-Version: v.1.0
//-Developer: Steve Karr (steve@digital-sherpas.com)
//-Version: v.1.01
//-Developer: Danny Mavromatis (danny@digital-sherpas.com)
//##########################################################-->
</head>

<body background="graphics/paddle_bk.GIF" bgcolor="#FFFFFF" BGPROPERTIES="FIXED" text="#000000" link="#FF0000" vlink="#FF0000" leftmargin="0">

<form method="POST">
    <div align="center"><center><table border="0" cellpadding="0"
    cellspacing="0" width="95%">
        <tr>
            <td width="95%"><p align="center"><br>
            <font face="Arial"><strong><img
            src="graphics/paddle_banner.gif"></strong></font></p>
            <p><font face="Arial" SIZE=-1><strong>
So who will be the victor? 
<br><br>
T-Man and Steven are going to grab hold of the paddles tomorrow and take it to tthe table. So, tell us who you think will be victorious. One vote per poll, please and if you've already voted, you'll go straight to the results page.
</strong></font><font
            size="2" face="Arial"><br>
            </font></p>
            </td>
        </tr>
    </table>
    </center></div><div align="center"><center><BR><table border="0"
    cellpadding="0" cellspacing="0" width="550">
	<tr>
<TD ALIGN="CENTER" VALIGN="TOP">
<!--#include file="poll2.inc"-->
</TD>
</tr>
    </table>
    </center></div><p align="center"><font face="Arial"><strong><img
    src="graphics/paddle_banner.gif"></strong></font></p>
    <p align="center"><br><P><center><font face="Arial" size="1">©1998. All rights reserved.<BR>
KUBE93.COM is created and maintained by <a href="http://www.kube93.com/credits.htm" target="new">Digital Sherpas</A>.</P><BR><P></font>
    </p>
</form>
</body>
</html>
