<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KION Weather</TITLE>

<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">
<TABLE WIDTH=400><TR><TD CLASS="a">
<IMG SRC="../images/weather.GIF" WIDTH=400 HEIGHT=54 BORDER=0>
<center><h2>Doppler Radar Map</h2>
<img src="http://kion.cbsnow.com/network/template/northwest_rad_300x187_ub.gif" border="0" width="300" height="187"></center>
<br><br>
<p><font size="-1"><a href="weather.asp">Return to the weather forecast page.</a></font></p>
<P>
Be sure to watch KION Eyewitness News at 6am, Noon, 5, 6 and 11pm for our complete weather coverage.
<BR><BR>
<!--#include file="../footer.inc" -->
</TD>
</TR>
</TABLE>
</BODY>
</HTML>
