<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Dr. Bob</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD class=a>
<IMG SRC="../images/drbob.GIF" WIDTH=400 HEIGHT=54 BORDER=0 ALT="Dr. Bob"><BR><BR>
<center><h1>Dr. Bob</h1></center>

<img src="../images/personel/dr_bob.jpg" width=161 height=200 border=0 alt="Dr. Bob" align="right">
The field of medicine is constantly changing.  Our "Eye on Health"
segment is designed to keep viewers informed about what is current in
medical research and tell them how these changes affect their daily
lives.<br><br>
Doctor Bob Mraule was raised in Salinas and graduated from Salinas High
School.  He did his undergraduate work at the University of California
at Berkeley.  He then received a Doctor of Dental Surgery degree
(D.D.S.) from the University of the Pacific and a Doctor of Medicine
degree (M.D.) from the University of Nebraska.  He also did an
internship in general surgery and a residency in oral and maxillofacial
surgery.  He is in a group practice with offices located in both Salinas
and Monterey.



<BR><BR><br>
<!--#include file="../footer.inc" -->
</TD></TR></TABLE>

</BODY>
</HTML>
