<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Eyewitness News</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 WIDTH=400><TR><TD class="a">
<IMG SRC="../images/newsfeatures.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<a href="news.asp"><img src="../images/features_top.gif" width=350 height=17 alt="" border="0"></a><br>
KION Eyewitness News brings you the most up to date news on the Central Coast.  Our <A HREF="news.asp">Top Stories</A> feature provides internet users with quick access to the day's news and links to related sites for more information.<BR><BR>

<a href="bob.asp"><img src="../images/features_bob.gif" width=350 height=17 alt="" border="0"></a><br>
<A HREF="bob.asp">Dr. Bob</A> provides you with the most current health and medical information to make sure you have the tools to deal with your health concerns.<BR><BR> 

<a href="bios/team.asp"><img src="../images/features_team.gif" width=350 height=17 alt="" border="0"></a><br>
Meet the KION <A HREF="bios/team.asp">News Team</A> and find out about the experience they bring to KION Eyewitness News and Eye On This Morning.<br><br>

<a href="http://207.66.185.129/kion/kionnewsstart.htm"><img src="../images/features_quiz.gif" width=350 height=17 alt="" border="0"></a><br>
Take the KION <A HREF="http://207.66.185.129/kion/kionnewsstart.htm">"In The News" Quiz</A> and find out how much you know about what's going on along The Central Coast.<br><br>

<a href="../newsarchives/query.asp"><img src="../images/features_archive.gif" width=350 height=17 alt="" border="0"></a><br>
Take a look in the KION <A HREF="../newsarchives/query.asp">News Archive</A> and find out what you missed yesterday or get more information about what happened a month ago.<br><br>


<!--#include file="../footer.inc" -->
</TD></TR></TABLE>
</BODY>
</HTML>
