<HTML>

<HEAD>
<META NAME="GENERATOR" CONTENT="AP NewsCenter">
<TITLE>NEW CYCLE #1, Tuesday, 4/28/98</TITLE>
<!#include file="../style2.inc" >
</HEAD>
<BODY BGCOLOR="#FFFFFF" BACKGROUND="http://www.kiontv.com/images/background3.gif">
<IMG SRC="http://www.kiontv.com/images/b_topstories.gif" BORDER=0 ALT="Top Stories">
<TABLE WIDTH="400" BORDER=1 BORDERCOLORLIGHT=#E0E0E0>
<TR><TD><TR><TD BGCOLOR=#FFFFF0><FONT SIZE=+2>
<A NAME=StoryIndex>
<CENTER><H2>NEW CYCLE #1, Tuesday, 4/28/98</H2></CENTER></TD>
</TABLE>
<TABLE WIDTH="400" BORDER=1 BORDERCOLORLIGHT=#E0E0E0 >
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#26Filler Trial>Filler Trial</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#24Caught on Tape>Caught on Tape</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#27Salinas Shooting>Salinas Shooting</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#20Wall Street>Wall Street</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#28Hwy 17 187 Update>Hwy 17 187 Update</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#18Line Item Veto>Line Item Veto</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#29Teacher Protest>Teacher Protest</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#19Tomb of Unknown>Tomb of Unknown</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#37Care Center Fire >Care Center Fire </A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#23Jimmy Carter>Jimmy Carter</A></TD>
<TR><TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#25Teacher Buried>Teacher Buried</A></TD>
<TD BGCOLOR=#FFFFF0><IMG SRC=script.gif ALIGN=LEFT HSPACE=5><A HREF=#11Ag Prices>Ag Prices</A></TD>

</Table>
<Table width=400 border=0><TR><TD><A HREF="../newsarchives/query.asp"><CENTER>Search the KION news archive.</CENTER></A><BR><BR><A HREF=..main/asp>Return To KION Home Page</A><BR>
</CENTER><HR><BR>
<A NAME=26Filler Trial>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Filler Trial</H3><BR>
AN F-B-I AGENT IS EXPECTED TO TESTIFY TODAY IN THE FORT ORD SNIPER ATTACK.
<P>
THE AGENT IS EXPECTED TO SAY THAT JOHN FILLER CONFESSED TO THE COMMITING THE SHOOTING AFTER HE WAS TAKEN INTO CUSTODY.
<P>
JAMES GAUGHRAN. THE MAN SHOT AND WOUNDED BY A FORT ORD SNIPER LAST JUNE. TOOK THE STAND IN THE CASE YESTERDAY.
<P>
GAUGHRAN. TOLD THE COURT HE NEVER WORKED WITH DEFENDANT JOHN FILLER.
<P>
HE DIDN'T EVEN KNOW THE MAN.
<P>
HE SAYS HE HEARD POPPING SOUNDS. JUST BEFORE FILLER TURNED A RIFLE ON HIM. 
<P>
IN: THIS MAN PUT. OC: TO BE ALIVE.
<P>
JOE LLOYD OF PRUNEDALE WAS KILLED DURING THAT AMBUSH.
<P>
GORAN PROUDLY TOLD THE COURT IT WAS LLOYD WHO SAVED HIS LIFE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=27Salinas Shooting>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Salinas Shooting</H3><BR>
THE VICTIM OF A SHOOTING NEAR AN ELEMENTARY SCHOOL HAS BEEN IDENTIFIED.
<P>
19-YEAR-OLD JOSE FERNANDEZ FROM SALINAS WAS SHOT AND KILLED YESTERDAY ON NORTH SANBORN STREET AROUND 2-THIRTY IN THE MORNING.  
<P>
FERNANDEZ WAS REPORTEDLY WALKING DOWN THE STREET WHEN HE WAS CONFRONTED BY TWO MEN AND SHOT.
<P>
IF YOU HAVE ANY INFORMATION YOUR ASKED TO CALL THE SALINAS POLICE DEPARTMENT.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=28Hwy 17 187 Update>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Hwy 17 187 Update</H3><BR>
AUTHORITIES HAVE IDENTIFIED THE WOMAN WHOSE BODY WAS FOUND FRIDAY IN THE SANTA CRUZ MOUNTAINS.
<P>
SHE IS 38-YEAR OLD DEBBIE MACKAY.AND HER HUSBAND IS UNDER ARREST FOR MURDER.
<P>
POLICE ARRESTED DAN MACKAY AFTER FINDING HIM STANDING NEXT TO HIS STALLED, BLOOD-SPLATTERED TRUCK ON THE SIDE OF HIGHWAY 17.
<P>
MACKAY THEN LED OFFICERS TO HIS WIFE'S BODY.
<P>
FREMONT POLICE SAY THE COUPLE'S FOUR CHILDREN ARE NOW STAYING WITH RELATIVES.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=29Teacher Protest>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teacher Protest</H3><BR>
CONTROVERSY THIS MORNING AT THE SALINAS CITY SCHOOL DISTRICT.
<P>
ANGRY PARENTS AND TEACHERS STAGED A PROTEST YESTERDAY OVER A SCHOOL BOARD DECISION. TO DEMOTE AN ELEMENTARY SCHOOL PRINCIPAL
<P>
MARY SEIRSEN IS THE PRINCIPAL FOR EL GABILAN ELEMENTARY SCHOOL.
<P>
LAST MONTH THE SCHOOL BOARD DEMOTED HER TO TEACHER. SAYING SHE LOST CONFIDENCE IN THE POSITION.
<P>
SEIRSEN SAYS THERE MAY BE OTHER MOTIVES.
<P>
"I FILED A DISCRIMINATION HARRASSMENT COMPLAINT WITH THE DISTRICT, SO SINCE THERE HASN'T BEEN ANYTHING ELSE. I BELIEVE IT'S RETALIATION."
<P>
"PROBABLY TO OTHER PEOPLE. IT DOESNT' MATTER. BUT IT COULD HAPPEN TO THEIR PRINCIPAL TOO."
<P>
THE BOARD HAS DENIED THE DISCRIMINATION COMPLAINT.
<P>
MEANWHILE. SEIRSEN HAS FORMALLY ASKED THE SCHOOL BOARD TO RESCIND ITS DECISION AND REINSTATE HER BACK TO PRINCIPAL. 
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=37Care Center Fire >
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Care Center Fire </H3><BR>
FIVE PEOPLE ARE DEAD THIS MORNING FOLLOWING A LATE NIGHT FIRE AT A HOME FOR THE ELDERLY NEAR SEATTLE.
<P>
THE BLAZE WAS QUICKLY CONTAINED BUT FIREFIGHTERS SAY MOST OF THE WOOD FRAME BUILDING WAS FILLED WITH HOT GAS AND BLACK SMOKE BY THE TIME THEY ARRIVED AT THE SCENE.
<P>
23 PEOPLE HAVE BEEN TAKEN TO THE HOSPITAL.MOST OF THEM WITH MINOR INJURIES.
<P>
THE 90-YEAR-OLD BUILDING THAT WAS CONVERTED INTO A CENTER FOR THE ELDERLY REPORTEDLY HAD NO SPRINKLERS INSTALLED INSIDE.
<P>
FIRE INVESTIGATORS ARE STILL TRYING TO DETERMINE THE CAUSE OF THE DEADLY BLAZE.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=25Teacher Buried>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Teacher Buried</H3><BR>
THE PENNSYLVANIA MIDDLE SCHOOL TEACHER WHO WAS GUNNED DOWN BY A STUDENT FRIDAY NIGHT WILL BE LAID TO REST TODAY.
<P>
AT LEAST TWO THOUSAND PEOPLE ARE EXPECTED TO SAY GOODBYE AT A FUNERAL SERVICE FOR JOHN GILLETTE IN EDINBORO, PENNSYLVANIA.
<P>
COUNSELORS WERE ON HAND YESTERDAY AT THE MIDDLE SCHOOL TO HELP STUDENTS COPE WITH THEIR EMOTIONS.
<P>
MEANWHILE POLICE HAVE CHARGED 14-YEAR-OLD ANDREW WURST WITH THE SCIENCE TEACHER'S SHOOTING DEATH.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=24Caught on Tape>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Caught on Tape</H3><BR>
LIKE A GENIE GOING BACK INTO HIS LAMP.THE ALADDIN HOTEL CASINO IN LAS VAGAS DISAPPEARED IN A CLOUD OF SMOKE YESTERDAY.
<P>
THE 17 STORY BUILDING WAS IMPLODED BY A SERIES OF STRATEGICALLY PLACED EXPLOSIVES.
<P>
THE HOTEL CASINO HAD ITS PLACE IN HISTORY.ROCK LEGEND ELVIS PRESLEY MARRIED PARCILLA PRESLEY THERE IN 19-67.
<P>
THE ALADDIN FOLLOWS OTHER LAS VEGAS HOTELS WHICH HAVE MET THE SAME FATE TO MAKE ROOM FOR  LARGER AND IMPROVED HOTEL CASINOS.
<P>
A NEWER VERSION OF THE ALADDIN WILL BE CONSTRUCTED ON THE SAME SITE, AND ITS EXPECTED TO OPEN IN THE YEAR TWO THOUSAND.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=20Wall Street>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Wall Street</H3><BR>
WALL STREET STOCKS TOOK A BIT OF A TUMBLE MONDAY, AS FEARS OF A HIKE IN FEDERAL INTEREST RATES LED TO A WIDESPEAD SELLOFF.
<P>
THE DOW PLUNGED MORE THAN 200-POINTS BEFORE REBOUNDING TO CLOSE DOWN 147-POINTS.
<P>
THE SHOCK WAVE WAS FELT IN THE ASIAN MARKETS AS WELL.      IN TOKYO, STOCK PRICES FELL IN TRADING TODAY, DUE IN PART TO WALL STREET'S JITTERS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=18Line Item Veto>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Line Item Veto</H3><BR>
IN WASHINGTON, THE SUPREME COURT IS CONSIDERING THE CONSTITUTIONALITY OF THE PRESIDENTIAL POWER OF LINE ITEM VETO.
<P>
ALMOST EVERY PRESIDENT THIS CENTURY HAS SOUGHT THE POWER TO VETO "PART" OF A BILL WITHOUT KILLING IT ENTIRELY.
<P>
CRITICS CHARGE THE LINE ITEM GIVES THE PRESIDENT THE POWER TO MAKE LAW, WHICH CONSTITUTIONALLY, IS CONGRESS' JOB.
<P>
SUPPORTERS TOLD THE COURT YESTERDAY THE LINE ITEM ALLOWS A PRESIDENT TO REMOVE WASTEFULL SPENDING IN BILLS AND DOES NOT VIOLATE THE CONSTITUTION'S SEPARATION OF POWER BETWEEN THE PRESIDENT AND CONGRESS.
<P>
THE LINE ITEM VETO WAS ENACTED IN 19-96.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=19Tomb of Unknown>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Tomb of Unknown</H3><BR>
A PENTAGON PANEL IS RECOMMENDING THAT THE REMAINS OF AN AIR FORCE PILOT WHO WAS SHOT DOWN OVER SOUTH VIETNAM IN 19-72 BE EXHUMED.
<P>
THE PANEL WANTS TO MAKE SURE THAT THE REMAINS OF THE DOWNED PILOT AREN'T THOSE OF MICHAEL BLASSIE AS ONCE THOUGHT.
<P>
THE REMAINS ARE BURIED IN THE TOMB OF THE UNKNOWNS, A MONUMENT THAT'S DEDICATED TO THE NATION'S UNIDENTIFIED WAR DEAD.
<P>
THE BLASSIE FAMILY IS ALSO ASKING THE DEFENSE DEPARTMENT TO EXHUME THE REMAINS FOR D-N-A TESTING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=23Jimmy Carter>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Jimmy Carter</H3><BR>
THE NAVY'S NEWEST SUBMARINE IS BEARING THE NAME OF THE NATION'S 39-TH PRESIDENT.
<P>
JIMMY CARTER, WHO SERVED IN THE NAVY, JOINS THE LIST OF PRESIDENTS WHO HAVE NAVAL VESSELS NAMED AFTER THEM.
<P>
CARTER WAS ON HAND AT A CEREMONY AT THE PENTAGON'S CENTRAL COURTYARD YESTERDAY.
<P>
THE FORMER PRESIDENT CALLED THE NAMING CEREMONY ONE OF HIS PROUDEST DAYS.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<A NAME=11Ag Prices>
<H3><IMG SRC=script.gif ALIGN=left HSPACE=5>Ag Prices</H3><BR>
MOST PRODUCE PRICES CONTINUE TO RISE THIS MORNING.  HERE'S A LOOK AT WHAT LOCAL GROWERS ARE GETTING, COURTESY OF THE U-S-D-A'S AGRICULTURE MARKETING SERVICE.
<P>
IT'S  AND YOU'RE WATCHING EYE ON THIS MORNING.
<P>

<FONT SIZE=-2><A HREF=#StoryIndex>Return to index of stories...</FONT></A><BR CLEAR=LEFT>
<HR>
<CENTER>
<A HREF=..main/asp>Return To KION Home Page</A><BR>
<FONT SIZE=1>
<B>Copyright © 1998</B><BR>
All rights reserved. This material may not be published, broadcast, rewritten, or redistributed. AP contributed to this report.<BR>
Associated Press text, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistribution directly or indirectly in any medium.  Neither these AP materials nor any portion thereof may be stored in a computer except for personal and non-commercial use.  AP will not be held liable for any delays, inaccuracies, errors or omissions therefrom or in the transmission or delivery of all or any part thereof or for any damages arising from any of the foregoing.</CENTER><!--#include file="../footer.inc" --></TD></TR></TABLE>
</BODY>
</HTML>
