<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KCBA Update</TITLE>
<!--#include file="../style1.inc"-->
</HEAD>

<BODY BGCOLOR="#003071" TEXT="#FFFFFF" LINK="#D90037" VLINK="#C0C0C0" ALINK="#FF0000">
<h1>KCBA News Headline Update</h1>


<BR><BR>Current Headlines:
<br>

<FORM METHOD=POST ACTION="newsudkcba.asp">
 <P><TABLE>

<TR>
<td bgcolor="#254525">Link</td>
<td bgcolor="#254525">Story</td></TR>
<TR>
<TD bgcolor="#808000"><textarea name="link1" cols="20" rows="1" wrap="VIRTUAL"><!--#include virtual="\kionkcbaupdate\text\newslink1kcba.txt"--></textarea></TD>
<TD bgcolor="#808000"><textarea name="story1" cols="50" rows="3" wrap="VIRTUAL"><!--#include virtual="\kionkcbaupdate\text\newsstory1kcba.txt"--></textarea></TD>
</TR>

<TR>
<TD bgcolor="#808000"><textarea name="link2" cols="20" rows="1" wrap="VIRTUAL"><!--#include virtual="\kionkcbaupdate\text\newslink2kcba.txt"--></textarea></TD>
<TD bgcolor="#808000"><textarea name="story2" cols="50" rows="3" wrap="VIRTUAL"><!--#include virtual="\kionkcbaupdate\text\newsstory2kcba.txt"--></textarea></TD>
</TR>

</table>
<P><INPUT TYPE=SUBMIT VALUE="Submit Form">
<br>
<font size="+1" color="Red">Remember, One click does the trick with the submit button!</font>
<br>
<INPUT TYPE=RESET VALUE="Reset Form">

</form>

<BR><BR>
<A HREF="default.html">Return to the main update page</A>
<br><br>

<A HREF="http://206.159.0.73" target="_top">KCBA Home</A>

</BODY>
</HTML>
