<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>Eye On The Central Coast</TITLE>

<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background3.gif">

<TABLE WIDTH=400><TR><TD class=a>
<IMG SRC="../images/centralcoast2.GIF" WIDTH=400 HEIGHT=54 BORDER=0><BR><BR>

<h2>Red Cross Contact Information:</h2>

<strong>CARMEL-BY-THE-SEA CHAPTER</strong><br>
EIGHTH AVE AT DELORES<br>
CARMEL CA<br>
93921-1689<br>
<em>408-624-6921 </em><br><br>

<strong>MONTEREY COUNTY CHAPTER </strong><br>
942 LUPIN DR<br>
SALINAS CA<br>
93906-3910<br>
<em>408-424-4824 </em><br><br>

<strong>SAN BENITO COUNTY CHAPTER </strong><br>
2300 TECHNOLOGY PKY STE 8<br>
HOLLISTER CA<br>
95023-2536<br>
<em>408-636-2100 </em><br><br>


<strong>SANTA CRUZ COUNTY </strong><br>
2960 SOQUEL AVE<br>
SANTA CRUZ CA<br>
95062-1412<br>
<em>408-462-2881 </em><br><br>




<BR><BR>
<!--#include file="../footer.inc" -->

</TD></TR>
</TABLE>






</BODY>
</HTML>
