	<TITLE>Eyewitness News</TITLE>
<!--#include file="../style2.inc" -->

</HEAD>

<BODY BGCOLOR="#FFFFFF" BACKGROUND="../images/background2.gif">



<font SIZE=+2>NCAA Pool Status Report</font><br>

<p>Tell your browser to &quot;Reload&quot; to make sure you get the most

current results. </p>

<center><strong> Status Report  (through 03/31/98)</strong> </center>
<table border>
<th rowspan=3> Pl </th>
<th rowspan=3> Name </th>
<th colspan=6 rowspan=2> # Correct <br> by Round</th>
<th colspan=2> </th>
<th colspan=8> Final 8 </th>
<tr>
<th rowspan=2>Cur<br>Pts</th>
<th rowspan=2>Pos<br>Pts</th>
<th colspan=4> Final 4 </th>
<tr>
<th >1</th>
<th >2</th>
<th >3</th>
<th >4</th>
<th >5</th>
<th >6</th>
<th >1st</th>
<th >2nd</th>
<th >  </th>
<th >  </th>
<th >  </th>
<th >  </th>
<th >  </th>
<th >  </th>
<th>Tie</th>
<tr>
<td align=center><pre>  1
<td><pre>KSBWBoy
<td align=right><pre>23
<td align=right><pre>11
<td align=right><pre>6
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>0
<td align=right><strong><pre>81
<td align=right><pre>81
<td><pre>UNC
<td><pre>Ky 
<td><pre>Ari
<td><pre>Kan
<td><pre>Con
<td><pre>Cin
<td><pre>Sta
<td><pre>Duk
<td align=right><pre>177  
<tr>
<td align=center><pre>  2
<td><pre>FredWArnold
<td align=right><pre>22
<td align=right><pre>10
<td align=right><pre>5
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>0
<td align=right><strong><pre>75
<td align=right><pre>75
<td><pre>UNC
<td><pre>Ky 
<td><pre>Ari
<td><pre>Kan
<td><pre>Was
<td><pre>Ark
<td><pre>Sta
<td><pre>Duk
<td align=right><pre>160  
<tr>
<td align=center><pre>  3
<td><pre>Al Cillas
<td align=right><pre>24
<td align=right><pre>12
<td align=right><pre>3
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>0
<td align=right><strong><pre>75
<td align=right><pre>75
<td><pre>UNC
<td><pre>Ky 
<td><pre>Ari
<td><pre>Kan
<td><pre>SC 
<td><pre>Cin
<td><pre>Pur
<td><pre>Syr
<td align=right><pre>167  
<tr>
<td align=center><pre>*
<td><pre>Timmy O'Tool
<td align=right><pre>24
<td align=right><pre>12
<td align=right><pre>3
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>0
<td align=right><strong><pre>75
<td align=right><pre>75
<td><pre>UNC
<td><pre>Ky 
<td><pre>Ari
<td><pre>Kan
<td><pre>SC 
<td><pre>Cin
<td><pre>Pur
<td><pre>Syr
<td align=right><pre>167  
<tr>
<td align=center><pre>*
<td><pre>Zakee Imam
<td align=right><pre>22
<td align=right><pre>11
<td align=right><pre>6
<td align=right><pre>2
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>72
<td align=right><pre>72
<td><pre>Cin
<td><pre>Duk
<td><pre>UNC
<td><pre>Sta
<td><pre>Con
<td><pre>Ari
<td><pre>Kan
<td><pre>Ky 
<td align=right><pre>165  
<tr>
<td align=center><pre>*
<td><pre>Tim O'Mara
<td align=right><pre>20
<td align=right><pre>9
<td align=right><pre>4
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>0
<td align=right><strong><pre>68
<td align=right><pre>68
<td><pre>UNC
<td><pre>Ky 
<td><pre>Cin
<td><pre>Kan
<td><pre>Con
<td><pre>Md 
<td><pre>Cle
<td><pre>Duk
<td align=right><pre>148  
<tr>
<td align=center><pre>*
<td><pre>d.evans
<td align=right><pre>22
<td align=right><pre>11
<td align=right><pre>6
<td align=right><pre>1
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>67
<td align=right><pre>67
<td><pre>Duk
<td><pre>Ari
<td><pre>UNC
<td><pre>Kan
<td><pre>SC 
<td><pre>Uta
<td><pre>Sta
<td><pre>Ky 
<td align=right><pre>175  
<tr>
<td align=center><pre>*
<td><pre>jim green
<td align=right><pre>22
<td align=right><pre>9
<td align=right><pre>6
<td align=right><pre>1
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>63
<td align=right><pre>63
<td><pre>Duk
<td><pre>Ari
<td><pre>UNC
<td><pre>Kan
<td><pre>Con
<td><pre>Uta
<td><pre>Cle
<td><pre>Ky 
<td align=right><pre>151  
<tr>
<td align=center><pre>*
<td><pre>Jeremy Fisher
<td align=right><pre>23
<td align=right><pre>11
<td align=right><pre>4
<td align=right><pre>1
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>62
<td align=right><pre>62
<td><pre>Ari
<td><pre>Duk
<td><pre>UNC
<td><pre>Kan
<td><pre>Xav
<td><pre>Cin
<td><pre>Pur
<td><pre>Ky 
<td align=right><pre>169  
<tr>
<td align=center><pre>*
<td><pre>Brent Calvin
<td align=right><pre>20
<td align=right><pre>8
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>1
<td align=right><pre>0
<td align=right><strong><pre>55
<td align=right><pre>55
<td><pre>Ind
<td><pre>Ky 
<td><pre>Neb
<td><pre>Det
<td><pre>NLV
<td><pre>Ari
<td><pre>Kan
<td><pre>Syr
<td align=right><pre>178  
<tr>
<td align=center><pre>*
<td><pre>Steve Karr
<td align=right><pre>22
<td align=right><pre>9
<td align=right><pre>3
<td align=right><pre>1
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>54
<td align=right><pre>54
<td><pre>UNC
<td><pre>Kan
<td><pre>Ari
<td><pre>Duk
<td><pre>SC 
<td><pre>Cin
<td><pre>Pur
<td><pre>Mic
<td align=right><pre>170  
<tr>
<td align=center><pre>*
<td><pre>Jesse Arnold
<td align=right><pre>23
<td align=right><pre>9
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>52
<td align=right><pre>52
<td><pre>Kan
<td><pre>UNC
<td><pre>Ari
<td><pre>Mic
<td><pre>Xav
<td><pre>Ark
<td><pre>Pur
<td><pre>NMx
<td align=right><pre>168  
<tr>
<td align=center><pre>*
<td><pre>Dave James
<td align=right><pre>19
<td align=right><pre>7
<td align=right><pre>4
<td align=right><pre>1
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>50
<td align=right><pre>50
<td><pre>UNC
<td><pre>Duk
<td><pre>Ari
<td><pre>Cle
<td><pre>SC 
<td><pre>Cin
<td><pre>Kan
<td><pre>Ky 
<td align=right><pre>131  
<tr>
<td align=center><pre>*
<td><pre>Matt Winterowd
<td align=right><pre>20
<td align=right><pre>7
<td align=right><pre>2
<td align=right><pre>1
<td align=right><pre>0
<td align=right><pre>0
<td align=right><strong><pre>45
<td align=right><pre>45
<td><pre>UCL
<td><pre>UNC
<td><pre>Ark
<td><pre>Kan
<td><pre>Ind
<td><pre>Ten
<td><pre>Pur
<td><pre>Duk
<td align=right><pre>142  
<tr>
</table>
<pre>* = mathematically eliminated
</pre>
</font>

	</td>

</tr>

<tr><td align=left valign=top><br>&nbsp;<br></td></tr>

</table>

<!--#include file="../footer.inc" -->

</BODY>
</HTML>
