
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">

<HTML>
<HEAD>
	<TITLE>KCBA</TITLE>
<!--#include file="../style2.inc" -->
</HEAD>

<BODY TEXT="#000000" VLINK="#1C0058" LINK="#005B91" ALINK="#FF0000" BGCOLOR="#FFFFFF">
<img src="../images/john_dalman.jpg" width=117 height=150 alt="" border=0 align="left" HSPACE="3">
<h1>Jon Dalman</h1>
<h2>Kids Club Host and Coordinator</h2>
<em>KCBA Fox 35</em>

<p>Birth Place: Salinas, Ca.</p>
<p>Education: San Jose State University, Hartnell College, Palma High School.</p>
<p>Special Interest: Cycling, traveling, spending time with family.</p>
<br><br>
<p>Jon first became interested in working with children while still in high school and participating in a community service project placed him in an elementary school classroom. This great experience made Jon realize that he wanted  to work with kids so he volunteered at Special Olympics, was a camp counselor at a camp for multi-handicapped adults, and a teachers assistant for an adaptive physical education class.</p>
<p>After high school Jon enlisted in the Army and was stationed in Ft.Bragg, N.C where he served with the 82nd Airborne and Seventh Special Forces Group traveling to locations like Panama and Honduras. Following his military service Jon returned to Salinas to graduate from Hartnell College and then transfer on to San Jose State. Jon graduated from San Jose State with a major in Liberal Studies and a minor in Special Education.</p>
<p>Serving as a school teacher, fitness director, and health educator Jon finally came to TV by appearing on the KCBA Kids Club and talking about the importance of wearing bicycle helmets with the old host Wendy. After Wendy left Jon stepped in and began his current stint as the Kids Club Host.</p>
<p>Jon's mission is to get kids off of their couches and involved in positive activities like PAL, 4H, scouting, and other after school activities. You can watch Jon on the KCBA Kids Club every weekday morning from 6:00-9:00, afternoons from 3:00-5:00, and on weekend mornings during children's programming.</p>

<br><br><br><br>

<!--#include file="../footer.inc" -->


</BODY>
</HTML>

